### ISSUE TITLE
src/mux_h2.c: null pointer dereference suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1727] opened 2022-05-28 03:54 UTC
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1489435:  Null pointer dereferences  (REVERSE_INULL)
/src/mux_h2.c: 6770 in h2_show_fd()
6764                                  h2s_sc(h2s));
6765                    if (h2s_sc(h2s))
6766                            chunk_appendf(msg, "(.flg=0x%08x .app=%p)",
6767                                          h2s_sc(h2s)->flags, h2s_sc(h2s)->app);
6768     
6769                    chunk_appendf(msg, "sd=%p", h2s->sd);
>>>     CID 1489435:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "h2s->sd" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
6770                    if (h2s->sd)
6771                            chunk_appendf(msg, "(.flg=0x%08x)",
6772                                          se_fl_get(h2s->sd));
6773     
6774                    chunk_appendf(&trash, " .subs=%p", h2s->subs);
6775                    if (h2s->subs) {
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by capflam** [comment] 2022-05-30 06:18
It is a false positive. Previous use of `h2s->sd` was to print the pointer. Thus it may be NULL, it is not an issue. However, now by design, this pointer is always defined. The test on it is useless.

**Comment by capflam** [comment] 2022-05-30 06:49
It should be fixed.

**Closed as completed** 2022-05-30 06:53 UTC
Labels: type: code-report
