### ISSUE TITLE
HAProxy 2.0.0 build w/ Prometheus exporter shows a sudden and permanent increase in CPU load after several hours

### ISSUE THREAD

**Issue by d22d101852** [haproxy/haproxy#129] opened 2019-06-20 09:36 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.0 2019/06/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=14).
Built with OpenSSL version : OpenSSL 1.1.0j  20 Nov 2018
Running on OpenSSL version : OpenSSL 1.1.0j  20 Nov 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```
```
Linux --snip-- 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 GNU/Linux
```
Running inside a docker container.

## What's the configuration?

```
global
    daemon
    log localhost:514 local0
    maxconn 5000
    chroot /var/empty
    user haproxy
    group haproxy

    # SSL Mozilla profile 'modern' with HSTS here
defaults

    mode http
    log global
    option httplog
    monitor-net 127.1.25.25/32
    retries 3
    option redispatch

    maxconn 5000
    timeout connect 5s
    timeout server 10s
    timeout client 30s

frontend stats
    bind <IP>:9101 ssl crt /usr/local/etc/haproxy/cert.pem
    option http-use-htx
    http-request use-service prometheus-exporter if { path /metrics }

*additional front and backends*
```

## Steps to reproduce the behavior

1. Build HAProxy 2.0.0. with the integrated Prometheus exporter: `EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"`
2. Run HAProxy & wait. It takes several hours for this error to occur.

## Actual behavior

After a **fixed** amount of time (about 8 hours and 20 min after startup) the CPU load across all threads gradually increases over the time span of 10 -- 15min. At this point CPU usage permanently spikes to 100% across all threads resulting in a high load average (here: ~5 instead of the usual <0.5).
This is often followed by another, this time sudden, increase in CPU load several hours later. Sometimes to the point where HAProxy (or at least the metrics) won't react anymore. After this peak the load tempers off again, but only to the elevated level it had before the additional increase.

This picture shows the 5min load average over a period of 12 hours:

[![5 min load average](https://i.imgur.com/3Jx9QfQ.png "5 min load average")](https://i.imgur.com/3Jx9QfQ.png)

Of the 4 instances of HAProxy only the 2 nodes with the internal Prometheus exporter enabled show this behavior. This affects both idle and busy servers.

As mentioned above, this always occurs after a fixed amount of time, as can be seen here:
[![5 min load average](https://i.imgur.com/HqrTPWH.png "5 min load average")](https://i.imgur.com/HqrTPWH.png)

All nodes have been started at the same time. I could not yet determine if the actual time after which this occurs is always the same, I only have (complete) data from the last incident.

## Expected behavior

Normal operation w/o an increase in CPU usage after some time.

## Do you have any idea what may have caused this?

This is definitely caused by building HAProxy with the Prometheus exporter. Other instances of HAProxy 2.0.0. build w/o the exporter don't show this behavior.

Unfortunately, I can't tell if this only occurs on nodes that are actively scraped or in conjunction with other/specific configuration options, as it always takes several hours for the error to occur. 

I only had a quick look at the actual scraped haproxy metrics, but found nothing unusual so far.

**Comment by d22d101852** [comment] 2019-06-22 05:53
Using `strace` I noticed yesterday that HAProxy seems to have problems with `clock_gettime()`

This is the output of the stuck process:

```
  --- SIGALRM {si_signo=SIGALRM, si_code=SI_TIMER, si_timerid=0x9, si_overrun=0, si_value={int=7, ptr=0x7}} ---
clock_gettime(0xfffffeb6 /* CLOCK_??? */, {8046, 108527491}) = 0
timer_settime(9, 0, {it_interval={0, 0}, it_value={1, 0}}, NULL) = 0
rt_sigreturn({mask=[]})                 = 0
epoll_wait(3, [{EPOLLIN, {u32=7, u64=7}}, {EPOLLIN, {u32=8, u64=8}}, {EPOLLIN, {u32=9, u64=9}}], 200, 0) = 3
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 136965444}) = 0
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137031005}) = 0
epoll_wait(3, [{EPOLLIN, {u32=7, u64=7}}, {EPOLLIN, {u32=8, u64=8}}, {EPOLLIN, {u32=9, u64=9}}], 200, 0) = 3
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137073832}) = 0
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137127460}) = 0
epoll_wait(3, [{EPOLLIN, {u32=7, u64=7}}, {EPOLLIN, {u32=8, u64=8}}, {EPOLLIN, {u32=9, u64=9}}], 200, 0) = 3
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137170621}) = 0
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137200867}) = 0
epoll_wait(3, [{EPOLLIN, {u32=7, u64=7}}, {EPOLLIN, {u32=8, u64=8}}, {EPOLLIN, {u32=9, u64=9}}], 200, 0) = 3
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137243853}) = 0
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137274817}) = 0
epoll_wait(3, [{EPOLLIN, {u32=7, u64=7}}, {EPOLLIN, {u32=8, u64=8}}, {EPOLLIN, {u32=9, u64=9}}], 200, 0) = 3
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137317883}) = 0
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137353713}) = 0
epoll_wait(3, [{EPOLLIN, {u32=7, u64=7}}, {EPOLLIN, {u32=8, u64=8}}, {EPOLLIN, {u32=9, u64=9}}], 200, 0) = 3
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137396663}) = 0
clock_gettime(CLOCK_THREAD_CPUTIME_ID, {7997, 137438152}) = 0
```
I then tried and compiled HAProxy with `RT=` but to no avail. Both instances (`RT=` and `RT=1`) show the same error again. Using `RT=` seems to actually make it worse. With that I get a constant load average of 14, compared to the 2-4 of `RT=1`.

**Comment by wtarreau** [comment] 2019-06-22 06:33
Where do you see an error in your strace output ? All of them appear to be OK and are increasing correctly. Confused.

**Comment by wtarreau** [comment] 2019-06-22 06:37
Regarding your CPU usage, how many frontends/backends do you have ? If I understood correctly, prometheus scans the metrics in the most possibly expensive way (ie fixes a metric then scans all nodes for that metric, then fixes another metric and does this again). Thus it results in a huge number of node lookups instead of the regular traversal that any other tool would do. But this should only impact huge configurations, small ones will never notice a difference.

Also in your trace I'm seeing POLLIN events which do not seem to be handled. This may actually be the reason for the CPU usage you're seeing. It might be possible that the response buffer is almost full and the operation cannot be performed, but in this case the other side should be blocked, it should not loop like this.

**Comment by d22d101852** [comment] 2019-06-22 07:58
@wtarreau sorry, I think didn't phrase that correctly. There's no error with `get_clocktime()` *per se*, it is just that the system gets hammered with these during CPU spikes. `strace` output is instantly flooded with thousands of these calls during a CPU spike. But you are right about the polling. This is weird.

I have a total of 6 front and backends, nothing major.

**Comment by wtarreau** [comment] 2019-06-22 12:09
It's not hammered in fact, there's one call before epoll_wait() and one call
after. Given that something prevents the poller from sleeping, you naturally
see tons of wakeups, each surrounded by its pair of clock_gettime().

Anyway this should not happen so there definitely is a bug somewhere.

Willy

**Comment by capflam** [comment] 2019-07-05 12:53
Several fixes was pushed and backported to 2.0, not only about Prometheus. I was unable to reproduce your exact issue. But some fixed bugs may be related.

**Comment by capflam** [comment] 2019-07-09 14:31
I will mark it as a duplicate of #151 because the fix was linked to this issue. And I guess it is the same bug.

**Comment by capflam** [comment] 2019-07-09 14:31
Duplicate of #151

**Closed as completed** 2019-07-09 14:32 UTC
Labels: type: bug, status: duplicate
