### ISSUE TITLE
Log-forwarding via syslog ring does not work anymore

### ISSUE THREAD

**Issue by Tristan971** [haproxy/haproxy#2561] opened 2024-05-07 04:34 UTC
### Detailed Description of the Problem

It seems that ring-based log-forwarding has recently stopped working. Specifically between 7151076522eface09dc3268e9d12286ff570e9b0 and 03ca16f38b23897f440f6fb8d730a96a0b864c9f

Specifically, it seems that HAProxy doesn't emit valid syslog messages anymore

### Expected Behavior

Unsure if I was relying on a now-fixed bug or not, so not sure.

### Steps to Reproduce the Behavior

Unclear

### What is your configuration?

```haproxy
...

ring promtail
    format rfc5424
    maxlen 8192

    timeout client 10s
    timeout connect 5s
    timeout server 10s

    server promtail 127.0.0.1:9083 log-proto octet-count

defaults defaults-base
    log ring@promtail len 8192 local0
    ...

// frontends and backends all use that defaults section, directly or indirectly
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0-dev10-03ca16f+mangadex-2e432d6 2024-05-06T10:01+00:00 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.15.126-1-pve #1 SMP PVE 5.15.126-1 (2023-10-03T17:24Z) x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -ggdb3 -gdwarf-4 -fwrapv -DMAX_SESS_STKCTR=5
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_MEMORY_POOLS -DDEBUG_STRICT

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1w+quic-mangadex-2e432d6  6 May 2024
Running on OpenSSL version : OpenSSL 1.1.1w+quic-mangadex-2e432d6  6 May 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 17.0.6 (++20231208085813+6009708b4367-1~exp1~20231208085906.81)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

I noticed a few things through the update:
1. The ring-level maxlen which I had set to 16384 triggered a warning:

**Comment by Tristan971** [comment] 2024-05-07 04:39
Setting the defaults-level maxlen to 8KB and the ring level one to 12KB also results in a single massive line being sent, with content in the form:

```
2024-05-07 05:36:08.688	[log line 1]����<129>1 2024-05-07T04:19:23.311952+00:00 [log line 2] ...
```

Not sure what the seemingly mis-encoded content is supposed to be in this case, as I can't see the raw bytes easily.

**Comment by wtarreau** [comment] 2024-05-07 05:14
Oh that's definitely not cool, especially with such a large range of commit which covers the ring changes :-/ I did test quite a bit with logs, but apparently not enough if that broke something for you. I'll need to have a look into that, thank you Tristan for this report!

**Comment by Tristan971** [comment] 2024-05-07 05:16
I have a trivial reproducer which works on our dev environment, so I'll try and at least bisect it first, hang on.

**Comment by Tristan971** [comment] 2024-05-07 05:16
Also annoyingly seems like Github ate a portion of my "additional notes" section somehow... Doesn't matter anyway, I guess.

**Comment by wtarreau** [comment] 2024-05-07 05:22
Ah cool if you can bisect, it will definitely help a lot. And indeed I noticed it ate your comments but I figured it was not critical ;-) I won't be much available today as I absolutely need to finish the buffer_wait fixes (we managed to get it to work yesterday, 30+ patches to clean up, squash/rewrite/rebase now), so do not pressure yourself to get me something quick as I'm unlikely to be able to handle it immediately (though others could be interested anyway). Thanks Tristan!

**Comment by Darlelet** [comment] 2024-05-07 07:52
Regarding this observation:
```
The ring-level maxlen which I had set to 16384 triggered a warning:
```

I guess you're talking about this kind of warning?
```
[WARNING]  (103159) : config : ring 'promtail' event max length '16384' exceeds max payload size, forced to '16379'.
```
This behavior was introduced with ddd8671b ("BUG/MEDIUM: ring: adjust maxlen consistency check")  (shipped in 2.9).

With 2.9 having ring's maxlen greater than the ring's size (either implicit=BUFSIZE or explicit with `size` directive) MINUS ring's overhead should already correct and warn about the error to prevent logs from being silently dropped at runtime. But according to your observations, you didn't hit this warning until very recently when deploying 3.0-dev?

---

Now back to the log-fowarding issue in itself (broken syslog message), I think I was able to reproduce something similar to what you described: since 01aa0a05 ("MEDIUM: ring: change the ring reader to use the new vector-based API now") invalid trailing bytes may be found at the end the syslog messages, when it was not the case before.

Before 01aa0a05:
```
181 <134>1 2024-05-07T09:45:21.543263+02:00 - haproxy 113700 - - 127.0.0.1:56136 [07/May/2024:09:45:21.491] front front/s1 0/0/21/30/51 404 369 - - ---- 1/1/0/0/0 0/0   "GET / HTTP/1.1"
```

After 01aa0a05:
```
<134>1 2024-05-07T09:41:37.390878+02:00 - haproxy 112729 - - 127.0.0.1:37372 [07/May/2024:09:41:37.238] front front/s1 0/0/66/39/105 404 369 - - ---- 1/1/0/0/0 0/0   "GET / HTTP/1.1"-fwr
```

In addition to that, the tcp syslog header announcing the payload's length (rfc-6587 octet counting) seems to be gone as well.

**Comment by Tristan971** [comment] 2024-05-07 07:57
> I guess you're talking about this kind of warning?

Yes exactly!

> With 2.9 having ring's maxlen greater than the ring's size (either implicit or explicit size) MINUS ring's overhead should already correct and warn about the error to prevent logs from being silently dropped at runtime. But according to your observations, you didn't hit this warning until very recently when deploying 3.0-dev?

Correct as well. But that's probably because of the older 3.0-dev build I am running atm (dev4).

Do you by any chance know if I should stick to powers-of-two or just set size = maxlen + overhead?
(finding out what the overhead is is a bit tricky, but thankfully the warning actually mentions the expected size, so it's easy enough to swap in)

> I think I was able to reproduce something similar to what you described [...]

Haven't finished bisecting yet (you're too fast :) but that sounds quite likely related indeed. I'll still finish my bisect in any case, but cool to see that at least it won't be a dead end and unreproduceable on your side :smile:

**Comment by Darlelet** [comment] 2024-05-07 08:01
>In addition to that, the tcp syslog header announcing the payload's length (rfc-6587 octet counting) seems to be gone as well.

Just thinking, perhaps the extra invalid bytes are there because the octet counting header is missing and as we're sending the same amount of bytes in both cases we get garbage bytes at the end of the buffer/vector.

**Comment by Darlelet** [comment] 2024-05-07 08:15
>Do you by any chance know if I should stick to powers-of-two or just set size = maxlen + overhead?
(finding out what the overhead is is a bit tricky, but thankfully the warning actually mentions the expected size, so it's easy enough to swap in)

`maxlen` causes log truncation when it's reached, similarly to log directive maxlen (ie: to comply with log consumer limitation for instance)
Thus if you expect `maxlen` to work properly, you should consider that you cannot fully use the ring's size for that purpose, so the ring size needs to be adjusted depending on your expected `maxlen`. 
For example, since ring's implicit size defaults to BUFSIZE (16k), to really set maxlen to 16K, the way to go would be to increase ring's size by a few bytes, or to the next power of two for performance reasons.

On the other hand, if you don't want to increase ring's size and don't care about log messages being truncated below 16K (by a few bytes), you could simply lower `maxlen` by a few bytes, just like the warning does.

**Comment by Tristan971** [comment] 2024-05-07 08:48
> For example, since ring's implicit size defaults to BUFSIZE (16k), to really set maxlen to 16K, the way to go would be to increase ring's size by a few bytes, or to the next power of two for performance reasons.

Yes that's what I was thinking, just wasn't sure how important it is to have a power of 2 as ring size, and if there was a big tradeoff in memory or something related for it.

> On the other hand, if you don't want to increase ring's size and don't care about log messages being truncated below 16K (by a few bytes), you could simply lower maxlen by a few bytes, just like the warning does.

Well in practice I was already limiting it to 8k inside my defaults anyway, so I am not expecting anything to be even close to the ring's maxsize in the first place.

Either way thanks for clarifying :+1: (and bisect still in progress, a bit slowly)

**Comment by Darlelet** [comment] 2024-05-07 08:53
> I'll still finish my bisect in any case, but cool to see that at least it won't be a dead end and unreproduceable on your side 😄

oh yes of course, thank you for that btw, it'll be interesting to know if it's related to the same stuff. We never know :)

>Yes that's what I was thinking, just wasn't sure how important it is to have a power of 2 as ring size, and if there was a big tradeoff in memory or something related for it.

Memory-wise it isn't that expensive because the ring is only allocated once (so 16K vs 32K is not a big difference), now for performance gain (when exclusively sticking to power of 2 for ring's size).. can't tell you if it'll be significant or not without testing it honestly :/ But I don't think it matters a lot

> Well in practice I was already limiting it to 8k inside my defaults anyway, so I am not expecting anything to be even close to the ring's maxsize in the first place.

Ok, great :)

**Comment by Darlelet** [comment] 2024-05-07 08:53
Regarding the regression described earlier (due to 01aa0a05), this patch seems to fix it on my side:
```diff
diff --git a/src/log.c b/src/log.c
index 0ab8c3308..e5d3782fb 100644
--- a/src/log.c
+++ b/src/log.c
@@ -5597,7 +5597,7 @@ ssize_t syslog_applet_append_event(void *ctx, struct ist v1, struct ist v2, size
 		return -2;
 
 	/* try to transfer it or report full */
-	trash.data += vp_peek_ofs(v1, v2, ofs, trash.area, len);
+	trash.data += vp_peek_ofs(v1, v2, ofs, trash.area + trash.data, len);
 	if (applet_putchk(appctx, &trash) == -1)
 		return -1;
```
(without that, we're actually rewriting trash.area and this explains why we "loose" octet counting prefix)

Once you're done bisecting @Tristan971, it could be interesting to check if the patch fixes it for you as well (if it's not too painful to deploy and test it of course)

**Comment by Tristan971** [comment] 2024-05-07 08:55
I will test it as soon as I'm done :+1: (as you pointed out, just in case it's a similar bug in a different place)

Thanks for the quick turnaround either way!

**Comment by wtarreau** [comment] 2024-05-07 09:12
Good catch Aurélien, indeed I lost +trash.data in the conversion here! I'm quite confident it should work better now!

**Comment by Darlelet** [comment] 2024-05-07 15:21
>Regarding the regression described earlier (due to https://github.com/haproxy/haproxy/commit/01aa0a057c1553590891078854ddbbccf0eeffe3), this patch seems to fix it on my side:

Here's the redacted patch:
[0001-BUG-MEDIUM-log-ring-broken-syslog-octet-counting.patch.txt](https://github.com/haproxy/haproxy/files/15237591/0001-BUG-MEDIUM-log-ring-broken-syslog-octet-counting.patch.txt)

**Comment by wtarreau** [comment] 2024-05-07 15:29
Thank you Aurélien, feel free to push it if not done yet.

**Comment by Tristan971** [comment] 2024-05-07 17:03
Alright, had to go away for a bit but my bisection lead the to the same commit :)

```
$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 1 step)
[01aa0a057c1553590891078854ddbbccf0eeffe3] MEDIUM: ring: change the ring reader to use the new vector-based API now
```

I'll try the patch now

**Comment by Tristan971** [comment] 2024-05-07 17:21
And I can confirm that the patch fixes the issue on my end, so merge away :+1:

**Comment by Darlelet** [comment] 2024-05-07 17:24
Now merged! Thanks guys

**Closed as completed** 2024-05-10 08:40 UTC
Labels: type: bug, dev, status: fixed
