### ISSUE TITLE
src/hlua.c: uninitialized pointer read suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1569] opened 2022-02-22 06:28 UTC
### Tool Name and Version

coverity

### Code Report

```plain
12203void hlua_init(void) {
12204        int i;
     1. var_decl: Declaring variable errmsg without initializer.
12205        char *errmsg;
12206#ifdef USE_OPENSSL
12207        struct srv_kw *kw;
12208        int tmp_error;
12209        char *error;
12210        char *args[] = { /* SSL client configuration. */
12211                "ssl",
12212                "verify",
12213                "none",
12214                NULL
12215        };
12216#endif
12217
12218        /* Init post init function list head */
     2. Condition i < 65U /* (unsigned int)sizeof (long) * 8 + 1 */, taking true branch.
     4. Condition i < 65U /* (unsigned int)sizeof (long) * 8 + 1 */, taking true branch.
     6. Condition i < 65U /* (unsigned int)sizeof (long) * 8 + 1 */, taking false branch.
12219        for (i = 0; i < MAX_THREADS + 1; i++)
     3. Jumping back to the beginning of the loop.
     5. Jumping back to the beginning of the loop.
12220                LIST_INIT(&hlua_init_functions[i]);
12221
12222        /* Init state for common/shared lua parts */
12223        hlua_state_id = 0;
12224        ha_set_thread(NULL);
12225        hlua_states[0] = hlua_init_state(0);
12226
12227        /* Init state 1 for thread 0. We have at least one thread. */
12228        hlua_state_id = 1;
12229        ha_set_thread(NULL);
12230        hlua_states[1] = hlua_init_state(1);
12231
12232        /* Proxy and server configuration initialisation. */
     CID 1469683 (#1 of 1): Uninitialized pointer read (UNINIT)7. uninit_use_in_call: Using uninitialized value errmsg when calling alloc_new_proxy. [show details]
12233        socket_proxy = alloc_new_proxy("LUA-SOCKET", PR_CAP_FE|PR_CAP_BE|PR_CAP_INT, &errmsg);
12234        if (!socket_proxy) {
12235                fprintf(stderr, "Lua init: %s\n", errmsg);
12236                exit(1);
12237        }
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment] 2022-02-24 15:53
For me it's a duplicate of #1568 as it mentions the uninit errmsg from alloc_new_proxy(). Marking it as such and closing.

**Closed as completed by wtarreau** 2022-02-24 15:53 UTC
Labels: status: duplicate, type: code-report
