### ISSUE TITLE
src/mux_h2.c: uninitialized vasriable suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2013] opened 2023-01-27 04:39 UTC
### Tool Name and Version

coverity

### Code Report

```plain
long report


5341static size_t h2s_snd_bhdrs(struct h2s *h2s, struct htx *htx)
5342{
    1. var_decl: Declaring variable list without initializer.
5343        struct http_hdr list[global.tune.max_http_hdr];
5344        struct h2c *h2c = h2s->h2c;
5345        struct htx_blk *blk;
5346        struct buffer outbuf;
5347        struct buffer *mbuf;
5348        struct htx_sl *sl;
5349        struct ist meth, uri, auth, host = IST_NULL;
5350        enum htx_blk_type type;
5351        int es_now = 0;
5352        int ret = 0;
5353        int hdr;
5354        int extended_connect = 0;
5355
    2. Condition trace_h2.state != TRACE_STATE_STOPPED, taking false branch.
5356        TRACE_ENTER(H2_EV_TX_FRAME|H2_EV_TX_HDR, h2c->conn, h2s);
5357
5358        /* get the start line (we do have one) and the rest of the headers,
5359         * that we dump starting at header 0 */
5360        sl = NULL;
5361        hdr = 0;
    3. Condition blk, taking true branch.
    6. Condition blk, taking true branch.
    9. Condition blk, taking true branch.
    19. Condition blk, taking true branch.
    22. Condition blk, taking false branch.
5362        for (blk = htx_get_head_blk(htx); blk; blk = htx_get_next_blk(htx, blk)) {
5363                type = htx_get_blk_type(blk);
5364
    4. Condition type == HTX_BLK_UNUSED, taking true branch.
    7. Condition type == HTX_BLK_UNUSED, taking true branch.
    10. Condition type == HTX_BLK_UNUSED, taking false branch.
    20. Condition type == HTX_BLK_UNUSED, taking true branch.
5365                if (type == HTX_BLK_UNUSED)
    5. Continuing loop.
    8. Continuing loop.
    21. Continuing loop.
5366                        continue;
5367
    11. Condition type == HTX_BLK_EOH, taking false branch.
5368                if (type == HTX_BLK_EOH)
5369                        break;
5370
    12. Condition type == HTX_BLK_HDR, taking false branch.
5371                if (type == HTX_BLK_HDR) {
5372                        BUG_ON(!sl); /* The start-line mut be defined before any headers */
5373                        if (unlikely(hdr >= sizeof(list)/sizeof(list[0]) - 1)) {
5374                                TRACE_ERROR("too many headers", H2_EV_TX_FRAME|H2_EV_TX_HDR|H2_EV_H2S_ERR, h2c->conn, h2s);
5375                                goto fail;
5376                        }
5377
5378                        list[hdr].n = htx_get_blk_name(htx, blk);
5379                        list[hdr].v = htx_get_blk_value(htx, blk);
5380
5381                        /* Skip header if same name is used to add the server name */
5382                        if ((h2c->flags & H2_CF_IS_BACK) && isttest(h2c->proxy->server_id_hdr_name) &&
5383                            isteq(list[hdr].n, h2c->proxy->server_id_hdr_name))
5384                                continue;
5385
5386                        /* Convert connection: upgrade to Extended connect from rfc 8441 */
5387                        if ((sl->flags & HTX_SL_F_CONN_UPG) && isteqi(list[hdr].n, ist("connection"))) {
5388                                /* rfc 7230 #6.1 Connection = list of tokens */
5389                                struct ist connection_ist = list[hdr].v;
5390                                do {
5391                                        if (isteqi(iststop(connection_ist, ','),
5392                                                   ist("upgrade"))) {
5393                                                if (!(h2c->flags & H2_CF_RCVD_RFC8441)) {
5394                                                        TRACE_STATE("reject upgrade because of no RFC8441 support", H2_EV_TX_FRAME|H2_EV_TX_HDR, h2c->conn, h2s);
5395                                                        goto fail;
5396                                                }
5397
5398                                                TRACE_STATE("convert upgrade to extended connect method", H2_EV_TX_FRAME|H2_EV_TX_HDR, h2c->conn, h2s);
5399                                                h2s->flags |= (H2_SF_BODY_TUNNEL|H2_SF_EXT_CONNECT_SENT);
5400                                                sl->info.req.meth = HTTP_METH_CONNECT;
5401                                                meth = ist("CONNECT");
5402
5403                                                extended_connect = 1;
5404                                                break;
5405                                        }
5406
5407                                        connection_ist = istadv(istfind(connection_ist, ','), 1);
5408                                } while (istlen(connection_ist));
5409                        }
5410
5411                        if ((sl->flags & HTX_SL_F_CONN_UPG) && isteq(list[hdr].n, ist("upgrade"))) {
5412                                /* rfc 7230 #6.7 Upgrade = list of protocols
5413                                 * rfc 8441 #4 Extended connect = :protocol is single-valued
5414                                 *
5415                                 * only first HTTP/1 protocol is preserved
5416                                 */
5417                                const struct ist protocol = iststop(list[hdr].v, ',');
5418                                /* upgrade_protocol field is 16 bytes long in h2s */
5419                                istpad(h2s->upgrade_protocol, isttrim(protocol, 15));
5420                        }
5421
5422                        if (isteq(list[hdr].n, ist("host")))
5423                                host = list[hdr].v;
5424
5425                        hdr++;
5426                }
    13. Condition type == HTX_BLK_REQ_SL, taking true branch.
5427                else if (type == HTX_BLK_REQ_SL) {
    14. Condition sl != NULL, taking false branch.
5428                        BUG_ON(sl); /* Only one start-line expected */
5429                        sl = htx_get_blk_ptr(htx, blk);
5430                        meth = htx_sl_req_meth(sl);
5431                        uri  = htx_sl_req_uri(sl);
    15. Condition sl->info.req.meth == HTTP_METH_HEAD, taking true branch.
5432                        if (sl->info.req.meth == HTTP_METH_HEAD)
5433                                h2s->flags |= H2_SF_BODYLESS_RESP;
    16. Condition uri.len == 0, taking false branch.
5434                        if (unlikely(uri.len == 0)) {
5435                                TRACE_ERROR("no URI in HTX request", H2_EV_TX_FRAME|H2_EV_TX_HDR|H2_EV_H2S_ERR, h2c->conn, h2s);
5436                                goto fail;
5437                        }
    17. Falling through to end of if statement.
5438                }
5439                else {
5440                        TRACE_ERROR("will not encode unexpected htx block", H2_EV_TX_FRAME|H2_EV_TX_HDR|H2_EV_H2S_ERR, h2c->conn, h2s);
5441                        goto fail;
5442                }
    18. Jumping back to the beginning of the loop.
5443        }
5444
5445        /* The start-line me be defined */
    23. Condition !sl, taking false branch.
5446        BUG_ON(!sl);
5447
5448        /* Now add the server name to a header (if requested) */
    24. Condition h2c->flags & 32768, taking true branch.
    25. Condition isttest(h2c->proxy->server_id_hdr_name), taking true branch.
5449        if ((h2c->flags & H2_CF_IS_BACK) && isttest(h2c->proxy->server_id_hdr_name)) {
5450                struct server *srv = objt_server(h2c->conn->target);
5451
    26. Condition srv, taking false branch.
5452                if (srv) {
5453                        list[hdr].n = h2c->proxy->server_id_hdr_name;
5454                        list[hdr].v = ist(srv->id);
5455                        hdr++;
5456                }
5457        }
5458
5459        /* marker for end of headers */
5460        list[hdr].n = ist("");
5461
5462        mbuf = br_tail(h2c->mbuf);
5463 retry:
    27. Condition !h2_get_buf(h2c, mbuf), taking false branch.
5464        if (!h2_get_buf(h2c, mbuf)) {
5465                h2c->flags |= H2_CF_MUX_MALLOC;
5466                h2s->flags |= H2_SF_BLK_MROOM;
5467                TRACE_STATE("waiting for room in output buffer", H2_EV_TX_FRAME|H2_EV_TX_HDR|H2_EV_H2S_BLK, h2c->conn, h2s);
5468                return 0;
5469        }
5470
5471        chunk_reset(&outbuf);
5472
    28. Condition 1, taking true branch.
    63. Condition 1, taking true branch.
    98. Condition 1, taking true branch.
5473        while (1) {
5474                outbuf = b_make(b_tail(mbuf), b_contig_space(mbuf), 0, 0);
    29. Condition outbuf.size >= 9, taking true branch.
    64. Condition outbuf.size >= 9, taking true branch.
    99. Condition outbuf.size >= 9, taking true branch.
5475                if (outbuf.size >= 9 || !b_space_wraps(mbuf))
    30. Breaking from loop.
    65. Breaking from loop.
    100. Breaking from loop.
5476                        break;
5477        realign_again:
5478                b_slow_realign(mbuf, trash.area, b_data(mbuf));
    62. Jumping back to the beginning of the loop.
    97. Jumping back to the beginning of the loop.
5479        }
5480
    31. Condition outbuf.size < 9, taking false branch.
    66. Condition outbuf.size < 9, taking false branch.
    101. Condition outbuf.size < 9, taking false branch.
5481        if (outbuf.size < 9)
5482                goto full;
5483
5484        /* len: 0x000000 (fill later), type: 1(HEADERS), flags: ENDH=4 */
5485        memcpy(outbuf.area, "\x00\x00\x00\x01\x04", 5);
5486        write_n32(outbuf.area + 5, h2s->id); // 4 bytes
5487        outbuf.data = 9;
5488
5489        /* encode the method, which necessarily is the first one */
    32. Condition !hpack_encode_method(&outbuf, sl->info.req.meth, meth), taking false branch.
    67. Condition !hpack_encode_method(&outbuf, sl->info.req.meth, meth), taking false branch.
    102. Condition !hpack_encode_method(&outbuf, sl->info.req.meth, meth), taking false branch.
5490        if (!hpack_encode_method(&outbuf, sl->info.req.meth, meth)) {
5491                if (b_space_wraps(mbuf))
5492                        goto realign_again;
5493                goto full;
5494        }
5495
5496        h2_trace_header(ist(":method"), meth, H2_EV_TX_FRAME|H2_EV_TX_HDR, ist(TRC_LOC), __FUNCTION__, h2c, h2s);
5497
5498        auth = ist(NULL);
5499
5500        /* RFC7540 #8.3: the CONNECT method must have :
5501         *   - :authority set to the URI part (host:port)

    Test Coverage
    Test Policy Rule
    Exclusions
    Line Impact
    Function Impact

5502         *   - :method set to CONNECT
5503         *   - :scheme and :path omitted
5504         *
5505         *   Note that this is not applicable in case of the Extended CONNECT
5506         *   protocol from rfc 8441.
5507         */
    33. Condition sl->info.req.meth == HTTP_METH_CONNECT, taking false branch.
    68. Condition sl->info.req.meth == HTTP_METH_CONNECT, taking false branch.
    103. Condition sl->info.req.meth == HTTP_METH_CONNECT, taking false branch.
5508        if (unlikely(sl->info.req.meth == HTTP_METH_CONNECT) && !extended_connect) {
5509                auth = uri;
5510
5511                if (!h2_encode_header(&outbuf, ist(":authority"), auth, H2_EV_TX_FRAME|H2_EV_TX_HDR,
5512                                      ist(TRC_LOC), __FUNCTION__, h2c, h2s)) {
5513                        /* output full */
5514                        if (b_space_wraps(mbuf))
5515                                goto realign_again;
5516                        goto full;
5517                }
5518
5519                h2s->flags |= H2_SF_BODY_TUNNEL;
5520        } else {
5521                /* other methods need a :scheme. If an authority is known from
5522                 * the request line, it must be sent, otherwise only host is
5523                 * sent. Host is never sent as the authority.
5524                 *
5525                 * This code is also applicable for Extended CONNECT protocol
5526                 * from rfc 8441.
5527                 */
5528                struct ist scheme = { };
5529
    34. Condition uri.ptr[0] != '/', taking true branch.
    35. Condition uri.ptr[0] != '*', taking true branch.
    69. Condition uri.ptr[0] != '/', taking true branch.
    70. Condition uri.ptr[0] != '*', taking true branch.
    104. Condition uri.ptr[0] != '/', taking true branch.
    105. Condition uri.ptr[0] != '*', taking true branch.
5530                if (uri.ptr[0] != '/' && uri.ptr[0] != '*') {
5531                        /* the URI seems to start with a scheme */
5532                        int len = 1;
5533
    36. Condition len < uri.len, taking true branch.
    37. Condition uri.ptr[len] != ':', taking true branch.
    39. Condition len < uri.len, taking true branch.
    40. Condition uri.ptr[len] != ':', taking true branch.
    42. Condition len < uri.len, taking true branch.
    43. Condition uri.ptr[len] != ':', taking false branch.
    71. Condition len < uri.len, taking true branch.
    72. Condition uri.ptr[len] != ':', taking true branch.
    74. Condition len < uri.len, taking true branch.
    75. Condition uri.ptr[len] != ':', taking true branch.
    77. Condition len < uri.len, taking true branch.
    78. Condition uri.ptr[len] != ':', taking false branch.
    106. Condition len < uri.len, taking true branch.
    107. Condition uri.ptr[len] != ':', taking true branch.
    109. Condition len < uri.len, taking true branch.
    110. Condition uri.ptr[len] != ':', taking true branch.
    112. Condition len < uri.len, taking true branch.
    113. Condition uri.ptr[len] != ':', taking true branch.
    115. Condition len < uri.len, taking true branch.
    116. Condition uri.ptr[len] != ':', taking false branch.
5534                        while (len < uri.len && uri.ptr[len] != ':')
    38. Jumping back to the beginning of the loop.
    41. Jumping back to the beginning of the loop.
    73. Jumping back to the beginning of the loop.
    76. Jumping back to the beginning of the loop.
    108. Jumping back to the beginning of the loop.
    111. Jumping back to the beginning of the loop.
    114. Jumping back to the beginning of the loop.
5535                                len++;
5536
    44. Condition len + 2 < uri.len, taking true branch.
    45. Condition uri.ptr[len + 1] == '/', taking true branch.
    46. Condition uri.ptr[len + 2] == '/', taking true branch.
    79. Condition len + 2 < uri.len, taking true branch.
    80. Condition uri.ptr[len + 1] == '/', taking true branch.
    81. Condition uri.ptr[len + 2] == '/', taking true branch.
    117. Condition len + 2 < uri.len, taking true branch.
    118. Condition uri.ptr[len + 1] == '/', taking true branch.
    119. Condition uri.ptr[len + 2] == '/', taking true branch.
5537                        if (len + 2 < uri.len && uri.ptr[len + 1] == '/' && uri.ptr[len + 2] == '/') {
5538                                /* make the uri start at the authority now */
5539                                scheme = ist2(uri.ptr, len);
5540                                uri = istadv(uri, len + 3);
5541
5542                                /* find the auth part of the URI */
5543                                auth = ist2(uri.ptr, 0);
    47. Condition auth.len < uri.len, taking true branch.
    48. Condition auth.ptr[auth.len] != '/', taking true branch.
    50. Condition auth.len < uri.len, taking true branch.
    51. Condition auth.ptr[auth.len] != '/', taking true branch.
    53. Condition auth.len < uri.len, taking true branch.
    54. Condition auth.ptr[auth.len] != '/', taking false branch.
    82. Condition auth.len < uri.len, taking true branch.
    83. Condition auth.ptr[auth.len] != '/', taking true branch.
    85. Condition auth.len < uri.len, taking true branch.
    86. Condition auth.ptr[auth.len] != '/', taking true branch.
    88. Condition auth.len < uri.len, taking true branch.
    89. Condition auth.ptr[auth.len] != '/', taking false branch.
    120. Condition auth.len < uri.len, taking true branch.
    121. Condition auth.ptr[auth.len] != '/', taking true branch.
    123. Condition auth.len < uri.len, taking true branch.
    124. Condition auth.ptr[auth.len] != '/', taking false branch.
5544                                while (auth.len < uri.len && auth.ptr[auth.len] != '/')
    49. Jumping back to the beginning of the loop.
    52. Jumping back to the beginning of the loop.
    84. Jumping back to the beginning of the loop.
    87. Jumping back to the beginning of the loop.
    122. Jumping back to the beginning of the loop.
5545                                        auth.len++;
5546
5547                                uri = istadv(uri, auth.len);
5548                        }
5549                }
5550
5551                /* For Extended CONNECT, the :authority must be present.
5552                 * Use host value for it.
5553                 */
    55. Condition extended_connect != 0, taking false branch.
    90. Condition extended_connect != 0, taking false branch.
    125. Condition extended_connect != 0, taking false branch.
5554                if (unlikely(extended_connect) && isttest(host))
5555                        auth = host;
5556
    56. Condition !scheme.len, taking true branch.
    91. Condition !scheme.len, taking true branch.
    126. Condition !scheme.len, taking true branch.
5557                if (!scheme.len) {
5558                        /* no explicit scheme, we're using an origin-form URI,
5559                         * probably from an H1 request transcoded to H2 via an
5560                         * external layer, then received as H2 without authority.
5561                         * So we have to look up the scheme from the HTX flags.
5562                         * In such a case only http and https are possible, and
5563                         * https is the default (sent by browsers).
5564                         */
    57. Condition (sl->flags & (384U /* 0x80 | 0x100 */)) == (384U /* 0x80 | 0x100 */), taking true branch.
    92. Condition (sl->flags & (384U /* 0x80 | 0x100 */)) == (384U /* 0x80 | 0x100 */), taking true branch.
    127. Condition (sl->flags & (384U /* 0x80 | 0x100 */)) == (384U /* 0x80 | 0x100 */), taking true branch.
5565                        if ((sl->flags & (HTX_SL_F_HAS_SCHM|HTX_SL_F_SCHM_HTTP)) == (HTX_SL_F_HAS_SCHM|HTX_SL_F_SCHM_HTTP))
    58. Falling through to end of if statement.
    93. Falling through to end of if statement.
    128. Falling through to end of if statement.
5566                                scheme = ist("http");
5567                        else
5568                                scheme = ist("https");
5569                }
5570
    59. Condition !hpack_encode_scheme(&outbuf, scheme), taking true branch.
    94. Condition !hpack_encode_scheme(&outbuf, scheme), taking true branch.
    129. Condition !hpack_encode_scheme(&outbuf, scheme), taking false branch.
5571                if (!hpack_encode_scheme(&outbuf, scheme)) {
5572                        /* output full */
    60. Condition b_space_wraps(mbuf), taking true branch.
    95. Condition b_space_wraps(mbuf), taking true branch.
5573                        if (b_space_wraps(mbuf))
    61. Jumping to label realign_again.
    96. Jumping to label realign_again.
5574                                goto realign_again;
5575                        goto full;
5576                }
5577
    130. Condition auth.len, taking true branch.
    131. Condition !h2_encode_header(&outbuf, ({...; struct ist({.ptr = __x, .len = 1 ? (0 /* (void *)":authority" == NULL */) ? 0 : __builtin_strlen(__x) : ({...; __l;})});}), auth, 71303168UL /* (1ULL << 22) | (1ULL << 26) */, ({...; struct ist({.ptr = __x, .len = 1 ? (0 /* (void *)"src/mux_h2.c:5580" == NULL */) ? 0 : __builtin_strlen(__x) : ({...; __l;})});}), <anonymous>, h2c, h2s), taking false branch.
5578                if (auth.len &&
5579                    !h2_encode_header(&outbuf, ist(":authority"), auth, H2_EV_TX_FRAME|H2_EV_TX_HDR,
5580                                      ist(TRC_LOC), __FUNCTION__, h2c, h2s)) {
5581                        /* output full */
5582                        if (b_space_wraps(mbuf))
5583                                goto realign_again;
5584                        goto full;
5585                }
5586
5587                /* encode the path. RFC7540#8.1.2.3: if path is empty it must
5588                 * be sent as '/' or '*'.
5589                 */
    132. Condition !uri.len, taking true branch.
5590                if (unlikely(!uri.len)) {
    133. Condition sl->info.req.meth == HTTP_METH_OPTIONS, taking false branch.
5591                        if (sl->info.req.meth == HTTP_METH_OPTIONS)
5592                                uri = ist("*");
5593                        else
5594                                uri = ist("/");
5595                }
5596
    134. Condition !hpack_encode_path(&outbuf, uri), taking false branch.
5597                if (!hpack_encode_path(&outbuf, uri)) {
5598                        /* output full */
5599                        if (b_space_wraps(mbuf))
5600                                goto realign_again;
5601                        goto full;
5602                }
5603
5604                h2_trace_header(ist(":path"), uri, H2_EV_TX_FRAME|H2_EV_TX_HDR, ist(TRC_LOC), __FUNCTION__, h2c, h2s);
5605
5606                /* encode the pseudo-header protocol from rfc8441 if using
5607                 * Extended CONNECT method.
5608                 */
    135. Condition extended_connect != 0, taking false branch.
5609                if (unlikely(extended_connect)) {
5610                        const struct ist protocol = ist(h2s->upgrade_protocol);
5611                        if (isttest(protocol)) {
5612                                if (!h2_encode_header(&outbuf, ist(":protocol"), protocol, H2_EV_TX_FRAME|H2_EV_TX_HDR,
5613                                                      ist(TRC_LOC), __FUNCTION__, h2c, h2s)) {
5614                                        /* output full */
5615                                        if (b_space_wraps(mbuf))
5616                                                goto realign_again;
5617                                        goto full;
5618                                }
5619                        }
5620                }
5621        }
5622
5623        /* encode all headers, stop at empty name. Host is only sent if we
5624         * do not provide an authority.
5625         */
    136. Condition hdr < sizeof (list) / 32UL /* sizeof (list[0]) */, taking true branch.
5626        for (hdr = 0; hdr < sizeof(list)/sizeof(list[0]); hdr++) {
5627                struct ist n = list[hdr].n;
    CID 1504178 (#1 of 1): Uninitialized scalar variable (UNINIT)137. uninit_use: Using uninitialized value list[hdr].v.
5628                struct ist v = list[hdr].v;
5629
```
```


### Additional Information

_No response_

### Output of `haproxy -vv`

```plain
no
```

**Comment by capflam** [comment] 2023-01-30 07:11
Duplicate of #1084

**Closed as not planned** 2023-01-30 07:17 UTC
Labels: status: duplicate, status: invalid, type: code-report
