### ISSUE TITLE
Many connections left in state CLOSE-WAIT with HTX enabled

### ISSUE THREAD

**Issue by tbabut** [haproxy/haproxy#541] opened 2020-03-10 14:08 UTC
## Output of `haproxy -vv` and `uname -a`
```
# haproxy -vv
HA-Proxy version 2.0.13-1ppa1~bionic 2020/02/15 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-ooLwkU/haproxy-2.0.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=40).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

# uname -a
Linux blackbox 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?
```
global
  chroot /var/lib/haproxy
  maxconn 250000
  user haproxy
  group haproxy
  log /dev/log len 8192 local1
  log /dev/log len 8192 local2 err
  stats timeout 2m
  tune.maxrewrite 1024
  tune.bufsize 18432
  tune.ssl.default-dh-param 2048
  ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
  ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  ssl-default-server-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
  ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  master-worker
  nbproc 1
  hard-stop-after 1h
  stats socket /var/run/haproxy.sock mode 600 expose-fd listeners level admin process 1

listen stats
  mode http
  stats enable
  stats uri /
  timeout connect 10s
  timeout client 1m
  timeout server 1m
  option http-use-htx
  http-request use-service prometheus-exporter if { path /metrics }

defaults
  log global
  option log-separate-errors
  maxconn 100000
  timeout connect 5s
  timeout client 50s
  timeout server 10m
  timeout http-request 10s
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

backend example
  fullconn 250000
  timeout connect 25s
  timeout server 10m
  timeout http-request 25s
  mode http
  option accept-invalid-http-response
  http-request del-header X-Forwarded-For
  compression algo gzip
  compression type text/css text/html text/javascript application/javascript text/plain text/xml application/json
  hash-type consistent
  default-server inter 3s fastinter 1s downinter 500ms fall 3 rise 2 slowstart 10s
  server example 192.168.1.100:8000 source 192.168.1.1 check maxconn 45000 send-proxy

frontend example
  timeout client 3h
  timeout http-request 25s
  mode http
  default_backend example
```

## Steps to reproduce the behavior

1. Start HAProxy
2. Wait for traffic
3. Monitor TCP sockets with *ss* or *netstat*

## Actual behavior

There are a lot of TCP connections with state CLOSE-WAIT.

## Expected behavior

There should be a few TCP connections with state CLOSE-WAIT. Actually it's a problem for us because we run a huge amount of connections.

## Do you have any idea what may have caused this?

When we disable HTX (with "no option http-use-htx" in the _defaults_ section) the problem disappears and we see a very small amount of connections with state CLOSE-WAIT.

## Do you have an idea how to solve the issue?

Unfortunately not. :)

But when I try to find the corresponding connections in HAProxy I only get a small number of sessions. I guess these are the expected/normal connections in CLOSE-WAIT state and sessions, that we also see when HTX is disabled.

```
# echo "show sess" | socat unix-connect:/var/run/haproxy.sock stdio > /tmp/haproxy-sessions.txt; for i in $(ss -tn | grep CLOSE-WAIT | awk '{print $4}' | cut -f2 -d':'); do grep ":$i" /tmp/haproxy-sessions.txt; done
0x7f83e814d3d0: proto=tcpv4 src=x.x.x.x:42214 fe=example be=example srv=example ts=00 age=4h29m calls=33 rate=0 cpu=0 lat=0 rq[f=848202h,i=0,an=00h,rx=2h59m,wx=,ax=] rp[f=80048202h,i=0,an=00h,rx=9m46s,wx=,ax=] s0=[8,200008h,fd=8728,ex=] s1=[8,200018h,fd=8782,ex=] exp=6m45s
0x555819693140: proto=tcpv4 src=x.x.x.x:51326 fe=example be=example srv=example ts=00 age=58s calls=5 rate=0 cpu=0 lat=0 rq[f=848202h,i=0,an=00h,rx=2h59m,wx=,ax=] rp[f=80048202h,i=0,an=00h,rx=9m59s,wx=,ax=] s0=[8,200008h,fd=554,ex=] s1=[8,200018h,fd=1423,ex=] exp=9m26s
0x7f840c1185f0: proto=tcpv4 src=x.x.x.x:60816 fe=example be=example srv=example ts=00 age=23h55m calls=151 rate=0 cpu=0 lat=0 rq[f=848202h,i=0,an=00h,rx=2h59m,wx=,ax=] rp[f=80048202h,i=0,an=00h,rx=9m43s,wx=,ax=] s0=[8,200008h,fd=598,ex=] s1=[8,200018h,fd=640,ex=] exp=5m38s
0x7f840c1542b0: proto=tcpv4 src=x.x.x.x:32082 fe=example be=example srv=example ts=00 age=4h54m calls=35 rate=0 cpu=0 lat=0 rq[f=848202h,i=0,an=00h,rx=2h59m,wx=,ax=] rp[f=80048202h,i=0,an=00h,rx=9m36s,wx=,ax=] s0=[8,200008h,fd=3920,ex=] s1=[8,200018h,fd=4681,ex=] exp=1m36s
0x7f842c134a90: proto=tcpv4 src=x.x.x.x:60810 fe=example be=example srv=example ts=00 age=23h55m calls=151 rate=0 cpu=0 lat=0 rq[f=848202h,i=0,an=00h,rx=2h59m,wx=,ax=] rp[f=80048202h,i=0,an=00h,rx=9m36s,wx=,ax=] s0=[8,200008h,fd=833,ex=] s1=[8,200018h,fd=906,ex=] exp=5m23s

# wc -l /tmp/haproxy-sessions.txt 
1923

# ss -tn |grep CLOSE-WAIT|wc -l
275
```
Figures are captured at a moment with low traffic.

Please let me know, if you need more data or informations. Thank you very much.

**Comment by wtarreau** [comment] 2020-03-10 14:52
When you say you see many of them, are they mostly between clients and haproxy (targeting the frontend's address+port) or between haproxy and the servers ? If the latter you could try to see if "http-reuse never" on the server improves or degrades the situation.

**Comment by tbabut** [comment] 2020-03-10 15:39
It's on the server side (between haproxy and servers). I have added "http-reuse never" to the backend and will report back.

**Comment by wtarreau** [comment] 2020-03-10 17:36
OK thank you.

**Comment by tbabut** [comment] 2020-03-11 08:59
It doesn't change anything, unfortunately. I see the same high amount of CLOSE-WAITs to the backend servers.

**Comment by tbabut** [comment] 2020-03-17 12:53
Any ideas anyone? Do you need some more information?

Thank you very much.

**Comment by capflam** [comment] 2020-03-18 09:43
Just by curiosity. It may be unrelated but in your configuration you have enabled the option `accept-invalid-http-response`. Is there any reason to do so ? The HTX is stricter with the message parsing. Maybe the end of the response is not properly handled because of that.

**Comment by tbabut** [comment] 2020-03-27 08:06
Thanks for your suggestion. Our application in the backend handles invalid requests. But with disabling this option nothing has changed. There are still many connections in CLOSE-WAIT state.

**Comment by wtarreau** [comment] 2020-04-02 12:10
Hi,
there's actually a fix in latest 2.0 tree which looks like it could very well be related to your issue:  c0caac2cc ("BUG/MINOR: connections: Make sure we free the connection on failure.")

In some error situations a failed connection was not freed. Probably that some of them were left hanging. We're going to issue another round of stable releases today so it would be nice if you could upgrade to 2.0.14 once it's out and verify if you're still affected by the issue.

**Comment by tbabut** [comment] 2020-04-22 13:36
I'm afraid not. So both servers with similar load show the same amount of CLOSE-WAITs. One server is running with 2.0.13 and the other with 2.0.14.

**Comment by tbabut** [comment] 2020-06-18 06:51
Hi, I have tested again with 2.0.15 with no measurable improvement unfortunately.

**Comment by wtarreau** [comment] 2020-06-18 09:42
Thanks for the feedback. I must admit at this point I have absolutely no idea what to look for, given that all places where we close a session or connection also close the FD.

**Comment by wtarreau** [comment] 2020-06-18 09:43
I'm marking it as "cannot reproduce" for now, hoping we can correlate it to something else and ultimately spot the problem.

**Comment by tbabut** [comment] 2020-06-23 07:51
We have tested also HAProxy 2.1.7 with no changes/improvements to the behaviour.

**Comment by capflam** [comment] 2020-06-24 09:30
It could be useful to have the anonymized `show sess all` for these connexions and '`show fd` too. If you prefer to send it me privately, it's ok.

**Comment by tbabut** [comment] 2020-06-24 12:58
[fd.txt](https://github.com/haproxy/haproxy/files/4825474/fd.txt)
[sess.txt](https://github.com/haproxy/haproxy/files/4825475/sess.txt)

Please let me know if there is still something missing. Thank you very much.

**Comment by capflam** [comment] 2020-06-29 11:50
Sorry for the late reply. I've checked info you provided. For me there is nothing strange. For a bit less than 4000 sessions, there is 325 sessions remotely closed on the backend side, waiting the frontend side is closed too. It is symptomic of a client who disappeared. Because you have huge timeouts, it is pretty visible. You can set `tcp-ut <delay>` on the bind line. It should mitigate the number of CLOSE_WAIT.

But it is strange to observe this behaviour with the HTX enabled only. It means HAProxy closes both sides at once when the HTX is disabled. I guess you have also more `CD--` terminate state in your logs when the HTX is enabled. I may miss something, but I tend to think the HTX is working as expected in such situation while the legacy HTTP mode is buggy. We are talking here tunnelled about connections using CONNECT requests. Once the tunnel is established, the HTP session is equivalent to a raw TCP session. With a frontend and a backend in TCP mode, you will observe the same behaviour than when the HTX is enabled. With the HTTP legacy mode, the tunnel mode is probably detected after the half-close is disabled on the backend side.

Whatever, try the `tcp-ut` parameter on the bind line. It should be ok this way.

**Comment by wtarreau** [comment] 2020-07-17 12:59
@tbabut any feedback on this one maybe ?

**Comment by tbabut** [comment] 2020-07-29 12:22
Sorry for not answering for longer period of time, I was on vacation. I will report back soon.

**Comment by wtarreau** [comment] 2020-07-30 06:15
No problem, thanks!

**Comment by tbabut** [comment] 2020-07-31 08:06
Thanks for your input by the way. We have added the `tcp-ut` option with a timeout of 7m to the bind configuration as well as to the servers in the backend. But there is no visible change in our graphs. This week we made a run with 2.0.16 which also didn't change anything in this regard. We have switched the HTX enabled configuration between two loadbalancers with pretty similar traffic just to be sure and the problem respectively the behaviour clearly moves back and forth.

Here is a connection in a CLOSE-WAIT state for example:
```
0x7f41845bdf90: [31/Jul/2020:07:43:27.903802] id=4784571 proto=tcpv4 source=xxx.xxx.239.173:16118
  flags=0x84e, conn_retries=3, srv_conn=0x55e10b3ac0f0, pend_pos=(nil) waiting=0
  frontend=frontend1 (id=7 mode=http), listener=? (id=2) addr=172.16.0.1:80
  backend=backend1 (id=3 mode=http) addr=10.10.1.1:56940
  server=server1 (id=1) addr=10.10.2.1:8080
  task=0x7f41b42fc0f0 (state=0x00 nice=0 calls=6 rate=0 exp=1h9m tmask=0x4000000000 age=20m3s)
  txn=0x7f416c6959d0 flags=0x100000 meth=7 status=200 req.st=MSG_TUNNEL rsp.st=MSG_TUNNEL
      req.f=0x0e blen=0 chnk=0 next=0
      rsp.f=0x00 blen=0 chnk=0 next=0
  si[0]=0x7f41845be238 (state=EST flags=0x200000 endp0=CS:0x7f418c3975f0 exp=<NEVER> et=0x000 sub=1)
  si[1]=0x7f41845be290 (state=EST flags=0x280018 endp1=CS:0x7f416c206a40 exp=<NEVER> et=0x000 sub=0)
  co0=0x7f418c343370 ctrl=tcpv4 xprt=RAW mux=H1 data=STRM target=LISTENER:0x55e10b3c2b50
      flags=0x80283306 fd=4610 fd.state=25 fd.cache=0 updt=0 fd.tmask=0x4000000000
      cs=0x7f418c3975f0 csf=0x00008040 ctx=0x7f41841241b0
  co1=0x7f41841338c0 ctrl=tcpv4 xprt=RAW mux=H1 data=STRM target=SERVER:0x55e10b3ac0f0
      flags=0x10243300 fd=3990 fd.state=22 fd.cache=0 updt=0 fd.tmask=0x4000000000
      cs=0x7f416c206a40 csf=0x00009000 ctx=0x7f416c70c940
  req=0x7f41845bdfa0 (f=0x848000 an=0x0 pipe=0 tofwd=-1 total=36474)
      an_exp=<NEVER> rex=2h55m wex=<NEVER>
      buf=0x7f41845bdfa8 data=(nil) o=0 p=0 req.next=0 i=0 size=0
      htx=0x55e10a42df60 flags=0x0 size=0 data=0 used=0 wrap=NO extra=0
  res=0x7f41845be000 (f=0x8004a020 an=0x0 pipe=0 tofwd=-1 total=3494)
      an_exp=<NEVER> rex=<NEVER> wex=<NEVER>
      buf=0x7f41845be008 data=(nil) o=0 p=0 rsp.next=0 i=0 size=0
      htx=0x55e10a42df60 flags=0x0 size=0 data=0 used=0 wrap=NO extra=0
```

**Comment by tbabut** [comment] 2020-09-07 12:24
Today we have installed the new stable version 2.2.2 but without any change in the behaviour. So quickly after the start the amount of CLOSE-WAIT connections rises up.

**Comment by wtarreau** [comment] 2020-09-08 07:32
Looking at your trace above, evreything seems normal. The server has closed, the close was forwarded to the client, which does not acknowledge, and we're waiting for a timeout supposed to arrive in 1 hour 9 minutes (which added to the 20mn age would likely mean a 90mn tunnel timeout set somewhere). The thing is, I can't find any such timeout value in your configuration, so I gan only guess that you've probably experimented a bit with some settings. But if that's the case, then the capture above just makes me think that in the worst case this connection will close in ~1h.  If you don't want to keep half-closed connections for that long (which I can easily understand), you may want to set "timeout client-fin", possibly to 1 minute or so.

**Comment by tbabut** [comment] 2020-09-08 12:36
Good news, this option helps keeping the CLOSE-WAIT connections down even to a level comparable to HAProxy 2.0 without HTX. We have set a timeout of 3m at the moment.

So, with HTX enabled HAProxy seems to handle this scenario differently!?

**Comment by wtarreau** [comment] 2020-09-08 12:53
I think you spotted something. The condition when HTX is used is in mux_h1 and it does this:
```
static void h1_refresh_timeout(struct h1c *h1c)
{
	if (h1c->task) {
		h1c->task->expire = TICK_ETERNITY;
		if ((!h1c->h1s && !conn_is_back(h1c->conn)) || b_data(&h1c->obuf)) {
			/* front connections waiting for a stream, as well as any connection with
			 * pending data, need a timeout.
			 */
			h1c->task->expire = tick_add(now_ms, ((h1c->flags & (H1C_F_CS_SHUTW_NOW|H1C_F_CS_SHUTDOWN))
							      ? h1c->shut_timeout
							      : h1c->timeout));
			task_queue(h1c->task);
			TRACE_DEVEL("refreshing connection's timeout", H1_EV_H1C_SEND, h1c->conn);
		}
	}
}
```

Note the test on `!h1s` (absence of streap, doesn't match) and the test on presence of data. So if we could send the data to the TCP stack, the clientfin timeout will not be used.

A right test would probably be something like this:
```
static void h1_refresh_timeout(struct h1c *h1c)
{
	if (h1c->task) {
		h1c->task->expire = TICK_ETERNITY;
		if (h1c->flags & (H1C_F_CS_SHUTW_NOW|H1C_F_CS_SHUTDOWN)) {
			h1c->task->expire = tick_add(now_ms, h1c->shut_timeout);
			task_queue(h1c->task);
			TRACE_DEVEL("refreshing connection's timeout (half-closed)", H1_EV_H1C_SEND, h1c->conn);
		} else if ((!h1c->h1s && !conn_is_back(h1c->conn)) || b_data(&h1c->obuf)) {
			/* front connections waiting for a stream, as well as any connection with
			 * pending data, need a timeout.
			 */
			h1c->task->expire = tick_add(now_ms, h1c->timeout);
			task_queue(h1c->task);
			TRACE_DEVEL("refreshing connection's timeout", H1_EV_H1C_SEND, h1c->conn);
		}
	}
}
```
@capflam what do you think ?

**Comment by wtarreau** [comment] 2020-09-08 13:53
Finally I pushed a variant of the above after discussing it with Christopher. I've backported it to latest 2.2 that I'm going to release now. I'm obviously interested in your observations after this!

**Comment by tbabut** [comment] 2020-09-08 13:55
Thank you very much for your effort und input. We'll try out and report back.

**Comment by wtarreau** [comment] 2020-09-08 14:01
I'm marking it as fixed and removing 2.2 and dev since they both have the commit above. If it's not sufficient we'll re-label them.

**Comment by tbabut** [comment] 2020-09-10 11:03
We have tested the new version and the patch doesn't help anything in our case unfortunately. Only by applying a short client-fin timeout the CLOSE-WAIT connections disappear. 

The bug is not mentioned in the changelog for 2.2.3 but the patch is included in the sources.

So is the bugfix not working for our case or do I miss here something?

**Comment by wtarreau** [comment] 2020-09-10 15:33
It's this one in 2.2: ee6ed47bb ("BUG/MEDIUM: mux-h1: always apply the timeout on half-closed connections") so it definitely is there. It might not be sufficient for the case that triggers it on your side :-/ I'm wondering if there could be any particular case where a hutr connection is not closed, but I can't think of any. Just so that there is no ambiguity, do you confirm that the CLOSE-WAIT connections are between the client and haproxy ?

**Comment by tbabut** [comment] 2020-09-11 07:38
It's still between HAProxy and the servers configured in the backend.

**Comment by wtarreau** [comment] 2020-09-11 07:47
Ah thanks, that's the info I couldn't find, but I see that I already asked back then in March. During the debugging above I assumed it was on the client side, and from your dump I assumed it was the client connection that was in CLOSE-WAIT state :-/

**Comment by tbabut** [comment] 2020-09-11 07:53
No problem, so you have fixed a bug anyway. :) But I am wondering, why setting "timeout client-fin" helps in this situation.

**Comment by wtarreau** [comment] 2020-09-11 07:54
Now I'm confused after looking at your trace and focusing on the server-side connection: the response buffer is empty, the stream interface is in the established state, yet there's no subscriber. That definitely explains that any activity on this connection will not be reported, but I fail to understand why it's in this state. I'm seeing that the stream interface has flags SI_FL_RXBLK_SHUT | SI_FL_RX_WAIT_EP so it's both waiting for the server to speak and blocked due to a received shutdown. The response channel indicates CF_SHUTW | CF_SHUTR so the shutdown was received and processed, the shutw was made but didn't seem to make its way down to the connection layer otherwise the stream-int wouldn't be in EST state anymore. There's definitely something wrong there.

**Comment by wtarreau** [comment] 2020-09-11 07:59
Regarding why timeout client-fin helps, I'm suspecting that we're missing an event to finalize the close in the current code, and that it's hidden by the short client latency, so that usually when we close to the client, the client closes in turn and causes another even which is caught and causes everything to get closed. If a client disappears for the last packets, it will not respond and will cause the connection to remain open for a long time. The client-fin will simply shorten this delay and result in the close event to be passed to the other side earlier. But I still don't understand what even is missing here.

**Comment by wtarreau** [comment] 2020-09-11 08:01
Oh there's something quite important there, that I hadn't noticed: you're in tunnel mode after a CONNECT request. So it is actually expected that the close to the server waits for the client to close in turn, it works like a TCP proxy! I just don't get why there's a SHUTW to the server then! Let me recheck your trace.

**Comment by wtarreau** [comment] 2020-09-11 08:06
OK so I said crap, CF_SHUTW|CF_SHUTR are on the response channel so the SHUTR was received from the server and passed to the client. There's no SHUTW on the server side (hence the request channel). So in fact, no, your trace is perfectly logical for a tunnel mode which follows the 4-step close:
  (1)shutr ---> shutw(2)
  (4)shutw <--- shutr(3)

Now I'd say the question would more likely be: how could we explain you observe a different behavior without HTX. It makes me think that we possibly close a bit too fast in non-HTX mode while this should not happen since the connection ought to remain in half-closed mode to drain remaining data from either side.

**Comment by capflam** [comment] 2021-04-09 15:43
Finally, everything seems to work as expected here, can we close this issue now ?

**Comment by wtarreau** [comment] 2022-04-14 18:09
One year without feedback is enough to close.

**Closed as completed by wtarreau** 2022-04-14 18:09 UTC
Labels: type: bug, dev, severity: medium, status: cannot reproduce, 2.0, 2.2, 2.3, 2.4, 2.5
