### ISSUE TITLE
haproxy 2.0.17: body response truncated with "no option http-use-htx"

### ISSUE THREAD

**Issue by aderumier** [haproxy/haproxy#840] opened 2020-09-03 07:41 UTC
Hi,
I have upgraded from 2.0.16 to 2.0.17, with "no option http-use-htx".

(debian buster, with 2.0.16-1~bpo10+1 to 2.0.17-1~bpo10+1 packages)

I have some strange problem with differents websites, with page not fully loading. (some websites are working fine).

I have remove the option, it's working fine with the new engine. (I had disable it by security as it was pretty new).

I didn't have time to get trace currently, I'll try to reproduce on a test server tomorrow.

**Comment by aderumier** [comment] 2020-09-03 12:52
I have reproduce the problem, with curl && http1.1

randomly, when I'm calling the same page, the response body is truncated around 32k with "CD--"

```
10.59.100.98:40336 [03/Sep/2020:14:46:33.641] FO~ preprod/server1 0/0/0/1/1 200 100218 - - ---- 1/1/0/0/0 0/0 {test.com|curl/7.71.1|}  "GET / HTTP/1.1"
10.59.100.98:40352 [03/Sep/2020:14:46:34.685] FO~ preprod/server1 0/0/0/0/1 200 33288 - - CD-- 1/1/0/0/0 0/0 {test.com|curl/7.71.1|}  "GET / HTTP/1.1"
10.59.100.98:40396 [03/Sep/2020:14:46:39.495] FO~ preprod/server1 0/0/0/0/1 200 33288 - - CD-- 1/1/0/0/0 0/0 {test.com|curl/7.71.1|}  "GET / HTTP/1.1"
10.59.100.98:40468 [03/Sep/2020:14:46:47.766] FO~ preprod/server1 0/0/0/1/2 200 33291 - - CD-- 2/1/0/0/0 0/0 {test.com|curl/7.71.1|}  "GET / HTTP/1.1"
10.59.100.98:40500 [03/Sep/2020:14:46:50.221] FO~ preprod/server1 0/0/0/1/1 200 33291 - - CD-- 2/1/0/0/0 0/0 {test.com|curl/7.71.1|}  "GET / HTTP/1.1"
10.59.100.98:40518 [03/Sep/2020:14:46:53.160] FO~ preprod/server1 0/0/0/1/1 200 33288 - - CD-- 1/1/0/0/0 0/0 {test.com|curl/7.71.1|} "GET / HTTP/1.1"
10.59.100.98:40904 [03/Sep/2020:14:47:36.683] FO~ preprod/server1 0/0/0/2/2 200 33288 - - CD-- 1/1/0/0/0 0/0 {test.com|curl/7.71.1|} "GET / HTTP/1.1"
10.59.100.98:40924 [03/Sep/2020:14:47:38.697] FO~ preprod/server1 0/0/0/1/1 200 33291 - - CD-- 1/1/0/0/0 0/0 {test.com|curl/7.71.1|} "GET / HTTP/1.1"
10.59.100.98:40942 [03/Sep/2020:14:47:41.124] FO~ preprod/server1 0/0/0/0/1 200 33289 - - CD-- 2/1/0/0/0 0/0 {test.com|curl/7.71.1|} "GET / HTTP/1.1"
10.59.100.98:40990 [03/Sep/2020:14:47:46.091] FO~ preprod/server1 0/0/0/1/2 200 100216 - - ---- 2/1/0/0/0 0/0 {test.com|curl/7.71.1|} "GET / HTTP/1.1"
```

**Comment by aderumier** [comment] 2020-09-03 12:58
global && defaults options: 
(nothing special in frontend/backend)

```
#
global
        log /dev/log local0 notice
        log /dev/log local1 info
        daemon
        stats timeout 30s
        user haproxy
        group haproxy
        stats socket /var/run/haproxy.socket user haproxy group haproxy mode 666 level admin  expose-fd listeners
        stats timeout 10m
        ssl-engine rdrand  # intel engine available in openssl
        ssl-mode-async
        # Default SSL material locations
        ca-base /etc/haproxy/ssl
        crt-base /etc/haproxy/ssl
        ssl-default-bind-options no-sslv3 no-tls-tickets  no-tlsv10 no-tlsv11
        ssl-default-bind-ciphers TLS13-AES-128-GCM-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-E$
        ssl-default-server-ciphers TLS13-AES-128-GCM-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE$
        ssl-default-server-options no-sslv3 no-tls-tickets  no-tlsv10 no-tlsv11
        tune.ssl.default-dh-param 2048
        #Increase TLS session cache size and lifetime to avoid computing too many symmetric keys
        tune.ssl.cachesize 100000
        tune.ssl.lifetime 600
        #set up a TLS record to match a TCP segment size, in order to improve client side rendering of content:
        tune.ssl.maxrecord 1460
        maxconn 300000
        hard-stop-after 300s

defaults
        log global
        mode http
        maxconn 32768
        balance leastconn
        option dontlognull
        option http-server-close
        option log-separate-errors
        option abortonclose
        option redispatch
        option httplog
        default-server inter 3s rise 2 fall 3
        option tcp-smart-connect
        timeout connect 5s
        timeout check 3s
        timeout queue 30s
        timeout client 30s
        timeout server 30s
        timeout http-request 10s
        timeout http-keep-alive 10s
        errorfile 408 /dev/null
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

       no option http-use-htx
```

**Comment by jmagnin** [comment] 2020-09-03 15:36
this has nothing to do with your problem but you should remove ssl-mode-async and ssl-engine rdrand from your config. ssl-mode-async can only be used with an async engine and rdrand isn't one. Intel QAT is the only async engine publicly available that I know of.

**Comment by capflam** [comment] 2020-09-07 09:55
Sorry, I missed this issue. I'm surprised you have a bug when the HTX is disabled in 2.0.17 and not in 2.0.16. The diff between these two versions is not huge. There is a bug about the H2 when the HTX is disabled. But you are doing H1 requests. So that's probably not related. Just in case, could you share your frontend/backend configuration if possible ?

**Comment by aderumier** [comment] 2020-09-07 10:08
I'll try to bisect it as indeed they are not too  much commits between 2.0.16 && 2.0.17.


here the backend/frontend config

```
frontend FO
        bind *:80,:::80 v6only
        bind *:443,:::443 v6only ssl crt /etc/haproxy/ssl/ strict-sni alpn h2,http/1.1

        maxconn 200000

        capture request header Host len 50
        capture request header User-Agent len 200
        capture request header Referer len 200
        capture response header x-cache len 10
        capture response header Content-Type len 30

        acl from_cloudflare src -f /etc/haproxy/acls/cloudflare.lst
        acl cloudflare_ip_hdr req.hdr(CF-Connecting-IP) -m found
        acl staticfiles path_end -f /etc/haproxy/map.d/staticfiles.map
        acl acl_odiso src -f /etc/haproxy/acls/odiso.lst
        acl acl_globalwhitelist src -f /etc/haproxy/acls/xxx.lst
        acl acl_search_engines src -f /etc/haproxy/acls/xxxx.lst
        acl is_jscss path_end .js .css
        acl is_image path_end .png .jpg .jpeg

        http-response set-header X-Frame-Options SAMEORIGIN
        http-response set-header X-Content-Type-Options nosniff
        http-request set-var(sess.fromcloudflare) always_true if { http_first_req } from_cloudflare
        http-request set-src hdr(CF-Connecting-IP) if { var(sess.fromcloudflare) -m found } cloudflare_ip_hdr
        http-request set-header X-Country-Code %[src,map_ip(/etc/haproxy/geoip/geoip.lst)]
        http-request set-priority-class int(1) if is_jscss
        http-request set-priority-class int(10) if !is_jscss !is_image
        http-request set-priority-class int(100) if is_image
        http-request set-header X-Forwarded-for %[src]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        option  forwardfor if-none
        errorfile 408 /dev/null

        acl domain_xxxx hdr(host) -i xxx.com
        use backend xxx if domain_xxxxx


backend serviceclient
        option httpchk GET / "HTTP/1.0\r\nUser-Agent:\ haproxy\r\nX-forwarded-proto:\ https\r\nHost: xxx.com"
        redirect scheme https code 301 if !{ ssl_fc }
        http-response set-header Strict-Transport-Security max-age=31536000; if { ssl_fc }
        timeout check 10000
        server server1 xxxxx:80 maxconn 30 check
```

**Comment by capflam** [comment] 2020-09-07 10:23
Are you sure you are doing HTTP/1.1 requests ? because, in legacy HTTP mode, the request version is not correctly reported in the logs. I'm asking because a bug introduced in the 2.0.17 may explain your issue. It was fixed with the commit 307f31ec in the 2.0, after the 2.0.17. But it is related to the HTTP/2 without the HTX. To convince you, you may try the last 2.0 snapshot.

**Comment by capflam** [comment] 2020-09-16 19:24
Any news about this issue ? No problem if not. It is just a gentle ping :)

**Closed as completed** 2021-03-20 09:10 UTC
Labels: type: bug, status: feedback required

**Comment by EmericBr** [comment] 2021-11-17 14:05
Just for note: ssl-mode-async is useless on engine rdrand, since this engine doesn't use a device and was not blocking. ssl-mode-async was designed to work using intel quick assist engine.
