### ISSUE TITLE
option httpclose causes 400 with http/2

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#15] opened 2019-01-19 20:33 UTC
Sander Klein reported this issue here on the mailing list: https://www.mail-archive.com/haproxy@formilux.org/msg29067.html

## Output of `haproxy -vv` and `uname -a`

```
haproxy 1.8.4
```

## What's the configuration?

unknown

## Steps to reproduce the behavior

apparently nothing special

## Actual behavior

From the message :
"After enabling all requests to a certain backend started to give 400's while requests to other backend
worked as expected. I get the following in haproxy.log:

Feb 21 14:31:35 localhost haproxy[22867]:
2001:bad:coff:ee:cd97:5710:4515:7c73:52553 [21/Feb/2018:14:31:30.690] backend-name/backend-04 1/0/1/-1/4758 400 1932 - - CH-- 518/215/0/0/0 0/0 {host.name.tld|Mozilla/5.0 (Mac||https://referred.name.tld/some/string?f=%7B%22la_la_la%22:%7B%22v%22:%22thingy%22%7D%7D} {} "GET /some/path/here/filename.jpg HTTP/1.1"

The backend server is nginx which proxies to a nodejs application. When
looking at the request on nginx it gives an HTTP 499 error.
"

## Do you have any idea what may have caused this?

Nothing, failed to reproduce. Since 1.8.4 we fixed many H2 issues, and some half-closed issues at the stream layer, thus it might be that this problem is now fixed. No more tests can be done without more info.

## Do you have an idea how to solve the issue?

Removing httpclose fixes the issue.

**Comment by roedie** [comment] 2019-07-08 19:26
This one can be closed. It was fixed somewhere after 1.8.4. I didn’t know. There was a issue for it here.

**Comment by lukastribus** [comment] 2019-07-08 20:10
I was unable to reproduce this a few months ago, even though I did go back to 1.8.4. I assume this is a timing thing and backend dependent.

Anyway, I agree that we can close this; we can always reopen if the issue comes up again.

**Closed as completed by lukastribus** 2019-07-08 20:10 UTC
Labels: type: bug, 1.8, severity: medium, subsystem: http, subsystem: h2, status: cannot reproduce
