### ISSUE TITLE
httpchk 404 When Backend Services Normal

### ISSUE THREAD

**Issue by gwg127** [haproxy/haproxy#2330] opened 2023-10-30 13:40 UTC
### Detailed Description of the Problem

- Description
The backend service proxied by HAProxy can be accessed normally, but the status detected by HAProxy is DOWN. Therefore, proxy cannot be used.

- Error log:
![image](https://github.com/haproxy/haproxy/assets/48542638/858d7367-e5c6-4774-8d0f-9bad0b9a25a2)

- Show stat:
![image](https://github.com/haproxy/haproxy/assets/48542638/aa6c18b8-20eb-47b6-aeda-92f8b01dbf1b)
  some states:
  status: DOWN
  chkfail: 1
  check_status: L7STS
  check_code: 404
  lastchg: 32796
  downtime: 32796
  last_chk: Not Found
  check_desc: Layer7 wrong status

- Return value for direct access to the backend service "/" by python:
![image](https://github.com/haproxy/haproxy/assets/48542638/b1698bda-bb18-46ad-8c31-478a8d6498dd)

### Expected Behavior

When the status code of the interface "/" is 200, HAProxy detects that the service status is UP.

### Steps to Reproduce the Behavior

1. start haproxy
2. The backend is down and cannot be recovered.

### Do you have any idea what may have caused this?

Does an empty response body cause this?

### What is your configuration?

```haproxy
global
  daemon
  user qaq
  group qaq
  nbproc 1
  maxconn 10000
  log     /dev/tmp_log    local2   info
  tune.ssl.default-dh-param 4096
  tune.bufsize 1000000
  ssl-dh-param-file /etc/haproxy/dhparam.pem
  h1-case-adjust date Date
  h1-case-adjust server Server
  h1-case-adjust x-frame-options X-Frame-Options
  h1-case-adjust content-length Content-Length
  h1-case-adjust x-subject-token X-Subject-Token
  h1-case-adjust vary Vary
  h1-case-adjust content-type Content-Type
  stats socket /var/run/haproxy.sock level admin process 1
  stats timeout 2m
 
defaults
  log global
  maxconn 8000
  option redispatch
  retries 5
  mode http
  option httplog
  option logasap
  option splice-auto
  option h1-case-adjust-bogus-client
  option h1-case-adjust-bogus-server
  no option http-use-htx
  timeout http-request 10s
  timeout queue 1m
  timeout connect 10s
  timeout client 2h
  timeout server 2h
  timeout check 10s

frontend 8743
  bind 10.0.0.101:8743 ssl crt /etc/haprox/cert/ ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:DHE-DSS-AES128-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305-SHA256:ECDHE-PSK-CHACHA20-POLY1305-SHA256:ECDHE-PSK-AES128-GCM-SHA256:ECDHE-PSK-AES256-GCM-SHA384:ECDHE-PSK-AES128-CCM-SHA256:ECDHE-ECDSA-AES128-CCM:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-CHACHA20-POLY1305-SHA256:!aNULL:!eNULL:!DHE:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK:@STRENGTH no-sslv3 no-tlsv10 no-tlsv11
  mode http
  option httpclose
  default_backend local_server_cluster

backend local_server_cluster
  balance static-rr
  option tcpka
  option httpchk
  option httplog
  server controller_10.0.0.149 10.0.0.149:8743  check inter 20s fastinter 5s downinter 30s rise 2 fall 5 ssl verify required ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:DHE-DSS-AES128-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305-SHA256:ECDHE-PSK-CHACHA20-POLY1305-SHA256:ECDHE-PSK-AES128-GCM-SHA256:ECDHE-PSK-AES256-GCM-SHA384:ECDHE-PSK-AES128-CCM-SHA256:ECDHE-ECDSA-AES128-CCM:ECDHE-ECDSA-AES256-CCM:ECDHE-ECDSA-CHACHA20-POLY1305-SHA256:!SHA1:!SHA256:!SHA384 no-sslv3 no-tlsv10 no-tlsv11 ca-file /etc/haproxy/cert/ca.crt
```

### Output of `haproxy -vv`

```plain
host-01:/home/fsp # haproxy -vv
HAProxy version 2.4.12-4b7772e 2022/01/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.12.html
Running on: Linux 4.18.0-147.5.2.10.h913.eulerosv2r10.x86_64 #1 SMP Thu May 19 08:23:57 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = x86_64
  CC      = cc
  CFLAGS  = -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/openEuler/openEuler-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fstack-protector-all -fPIE
  OPTIONS = USE_NETFILTER=1 USE_PCRE2=1 USE_TPROXY=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_LIBCRYPT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.35 2020-05-09
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by capflam** [comment] 2023-10-31 08:34
The report is confused. First your HAProxy is outdated, you should upgrade to the latest 2.4 (2.4.24). Then your error log report a connection issue while an HTTP error is reported by `show stat`. But if a `404-Not Found` is returned by your server, it means your server is not happy with the http-check request. By default, a `OPTIONS / HTTP/1.0`  request is sent with no `host` header.  It is hard to say why your server replies a 404 error. But it seems to be a configuration issue and not a bug.

You may ask for help on the forum or the mailing list:

* The forum is at: https://discourse.haproxy.org/
* The mailing list (no need to subscribe) is: [haproxy@formilux.org](mailto:haproxy@formilux.org)
* Subscribe to the list: [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)
* Unsubscribe from the list: [haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)

**Comment by capflam** [comment] 2023-11-10 08:56
I guess we can close this one. Feel free to re-open if there is something new.

**Closed as completed by capflam** 2023-11-10 08:56 UTC
Labels: type: bug, status: feedback required
