### ISSUE TITLE
[v2.4] dontlognull behaviour change

### ISSUE THREAD

**Issue by wdauchy** [haproxy/haproxy#1336] opened 2021-07-24 17:59 UTC
### Detailed Description of the Problem

I am using `option dontlognull` to hide some `HTTP/1.1 400 Bad request` in logs. Since v2.4, the behaviour seems changed as I can now see those 400.
(To confirm the behaviour change, I removed the option in v2.3; the 400 comes back; in v2.4 it seems to have no effect)
in both case I am not using `http-ignore-probes`

### Expected Behavior

the 400 requests should not appear, at least for those coming from a connect without data.

### Steps to Reproduce the Behavior

use dontlognull in v2.4, and try requests which connects without sending data.

**Comment by jmagnin** [comment] 2021-07-24 18:16
Thanks for the report William.
Looks like it started behaving this way starting with  b74debd82

**Comment by jmagnin** [comment] 2021-07-24 18:37
@wdauchy  do you also have `option http-ignore-probes` ? 
I think my previous comment is not correct. 

```
defaults
  mode http
  option dontlognull
  option http-ignore-probes

listen foo
  bind *:8443 ssl crt ssl.pem
  bind *:8080
  option httplog
  log stdout local0
  http-request return status 200
```

I did bisect with this config and using s_client to the non ssl port. before b74debd I don't get a log, after I do.
but that is not what you report, and I can not reproduce the 400 when connecting with no data.

**Comment by wdauchy** [comment] 2021-07-24 18:40
> @wdauchy do you also have `option http-ignore-probes` ?

no in both cases I am not using it. Sorry I updated my orignal post about it, that's an important info.

**Comment by jmagnin** [comment] 2021-07-24 18:43
can you share simple reproducer  ?
are you just doing something like `nc -z ip port` to reproduce ?

**Comment by jmagnin** [comment] 2021-07-24 19:13
using the config below and  nc -z  I reproduce your problem.

```
defaults
  mode http
  option dontlognull
  timeout http-request 1s

listen foo
  bind *:8080
  option httplog
  log stdout local0
  http-request return status 200
```

c4bfa59f1 is the first bad commit.

**Comment by wdauchy** [comment] 2021-07-24 19:39
> using the config below and nc -z I reproduce your problem.
> 
> ```
> defaults
>   mode http
>   option dontlognull
>   timeout http-request 1s
> 
> listen foo
>   bind *:8080
>   option httplog
>   log stdout local0
>   http-request return status 200
> ```
> 
> [c4bfa59](https://github.com/haproxy/haproxy/commit/c4bfa59f1d534f226d309c9932c0d35b279cffe7) is the first bad commit.

Thanks Jerome for your quick research! I did not test your bisection, but I trust you ;)
for the reproducer, I must say I lazily expose my instance in a public cluster where I know there are traffic like browsers which open many connection "to probe" without sending any data.

**Comment by capflam** [comment] 2021-07-26 13:25
It should be fixed now. Thanks !

**Closed as completed** 2021-07-27 06:26 UTC
Labels: type: bug, status: fixed

**Comment by wdauchy** [comment] 2021-07-27 08:02
> It should be fixed now. Thanks !

Thanks Christopher!
