### ISSUE TITLE
ca-verify-file add the CA into the certificate chain

### ISSUE THREAD

**Issue by withings-sas** [haproxy/haproxy#781] opened 2020-07-27 14:32 UTC
Hi,
I would like to use optional client certificate verification without sending any intermediate or CA certificate in the certificate chain.
However, when I specifiy the Root CA that I want to use for client certificate verification (and which has also issued the server certificate), that certificat is sent too in the certificate chain.

crt-list file :
`/path/to/mycert.ecdsa [ca-verify-file /path/to/my/rootca/myca.pem verify optional] myserver.mydomain.mytld`

```
$ openssl s_client -connect myserver.mydomain.mytld:443 -servername myserver.mydomain.mytld -sigalgs ed25519
CONNECTED(00000003)
---
Certificate chain
 0 s:CN = myserver.mydomain.mytld
   i:CN = MY CA
 1 s:CN = MY CA
   i:CN = MY CA
---
Server certificate
[...]
```

Is it a way not to send it ?

I'm using haproxy 2.2.0-1ppa1~bionic

**Comment by wlallemand** [comment] 2020-07-27 15:22
Hello,

Your crt "mycert.ecdsa" is supposed to contain everything you want to send to the client, so if there is the Root CA inside, it will be sent too. Could you check the content of this file?
The "ca-verify-file" keyword is supposed to be used only to verify.

**Comment by withings-sas** [comment] 2020-07-27 15:51
thanks for your reply.
The file only contains the server certificate, no CA.

What I witnesses is that if the CA in the "ca-verify-file" file has emitted the server certificate, the CA will be sent to the client too.
(If the server certificate is not issued by the "ca-verify-file" CA, it works as expected : no CA is sent with the server certificate).

**Comment by wlallemand** [comment] 2020-07-29 12:43
@ehocdet any clue about this?

**Comment by withings-sas** [comment] 2020-08-12 08:46
This is not especially a regression, i see the same behavior on the 1.8 branch.

This behavior breaks TLS handshake on our small embedded devices that are not able to read such a big packet (extra bytes due to unwanted CA)

**Comment by wlallemand** [comment] 2020-08-12 09:29
Okay, thanks for the details, I'm looking into this today.

**Comment by wlallemand** [comment] 2020-08-12 14:50
I can reproduce this exact issue with both "ca-file" and "ca-verify-file". The good news is that you can remove the Root CA with the "ssl-skip-self-issued-ca" keyword, it works in this case (at least with the fix from issue #804) but that's only available in 2.2. I'm still investigating the code to fix the issue.

**Comment by wlallemand** [comment] 2020-08-12 16:43
Unfortunately it doesn't seem to be a problem in HAProxy code, looking at the OpenSSL API documentation:

 > SSL_CTX_build_cert_chain() builds the certificate chain for ctx normally this uses the chain store or the verify store if the chain store is not set.

Which means that OpenSSL is completing the chain itself using your verify store if you only have a server certificate.

I'm looking for a code workaround...

**Comment by wlallemand** [comment] 2020-08-12 18:15
Could you try the attached patch? It should fix your issue
[0001-BUG-MEDIUM-ssl-never-generates-the-chain-from-the-ve.patch.txt](https://github.com/haproxy/haproxy/files/5064857/0001-BUG-MEDIUM-ssl-never-generates-the-chain-from-the-ve.patch.txt)

**Comment by withings-sas** [comment] 2020-08-13 09:42
I confirm the patch is working as expected on 2.2 tgz, many thanks

**Comment by wlallemand** [comment] 2020-08-13 09:51
Thanks, I pushed it in the master, it will be backported for the next releases.

**Comment by wlallemand** [comment] 2020-09-01 14:41
It looks like this was correctly done in 2.1 and 2.0. The problem was introduced in 2.2 with the "find_chain" variable and the chain completion feature.
If the problem exists in 1.8, it probably lacks a sk_X509_new_null()  in ssl_sock_load_cert_chain_file().

**Comment by capflam** [comment] 2020-11-04 06:14
The 1.8 doesn't seems to be affected by this bug. I close the issue now.

**Closed as completed by capflam** 2020-11-04 06:14 UTC
Labels: type: bug, subsystem: ssl, status: fixed
