### ISSUE TITLE
`haproxy` consumes 100% of CPU time and leaves unclosed connections

### ISSUE THREAD

**Issue by pfactum** [haproxy/haproxy#2395] opened 2023-12-20 16:38 UTC
### Detailed Description of the Problem

I've just upgraded `haproxy` from v2.9.0 to v2.9.1 in Arch Linux and got an issue with it consuming 100% of CPU time after a short burst of traffic. Once started, `haproxy` doesn't consume CPU. Once `rsync-ssl` is run on the client side and finishes transfer, `haproxy` burns CPU.

Downgrading `haproxy` back to v2.9.0 eliminates the problem.

### Expected Behavior

`haproxy` should not use 100% of CPU time while idle.

### Steps to Reproduce the Behavior

I'm using the `rsync-fe` frontend with `rsync-be-example1` backend as per the configuration pasted below. `unix@/run/rsyncd-proxy/example1/sock` is being listened to by `systemd-socket-proxyd` that proxies the traffic to a namespaced `rsync` daemon.

### What is your configuration?

```haproxy
global
    daemon

frontend rsync-fe
    bind :::874 v4v6 tfo ssl crt /var/lib/haproxy/tls/example1.com/bundle.pem crt /var/lib/haproxy/tls/example2.com/bundle.pem
    mode tcp
    timeout client 20s
    acl ACL_rsync-example1 ssl_fc_sni example1.com
    acl ACL_rsync-example2 ssl_fc_sni example2.com
    use_backend rsync-be-example1 if ACL_rsync-example1
    use_backend rsync-be-example2 if ACL_rsync-example2

backend rsync-be-example1
    mode tcp
    timeout connect 5s
    timeout server 20s
    server static unix@/run/rsyncd-proxy/example1/sock

backend rsync-be-example2
    mode tcp
    timeout connect 5s
    timeout server 20s
    server static unix@/run/rsyncd-proxy/example2/sock

frontend dot-fe
    bind :::853 v4v6 tfo ssl crt /var/lib/haproxy/tls/example3.com/bundle.pem
    mode tcp
    timeout client 10s
    default_backend dot-be

backend dot-be
    mode tcp
    timeout connect 5s
    timeout server 5s
    server static 127.0.0.2:53
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.1-f72603c 2023/12/15 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.1.html
Running on: Linux 6.6.0-pf4 #1 SMP PREEMPT_DYNAMIC Mon, 11 Dec 2023 10:10:44 +0000 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/haproxy/src=/usr/src/debug/haproxy -flto=auto -fwrapv
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.2.0 23 Nov 2023
Running on OpenSSL version : OpenSSL 3.2.0 23 Nov 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.3
Running on zlib version : 1.3
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 13.2.1 20230801

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

While `haproxy` was burning CPU, I've `strace`d it and got the following:

```
[pid 13911] epoll_wait(6, [], 200, 0)   = 0
[pid 13911] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=1, tv_nsec=211623108}) = 0
[pid 13911] clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=1, tv_nsec=211671458}) = 0
```

These lines repeat very fast for an indefinite amount of time till I kill `haproxy`.

**Comment by wioo** [comment] 2023-12-20 17:13
Same here. I am using official docker image (x86-64). 2.9.0 and 3.0-dev images are fine. All 2.9.1 images consume 100% of cpu. I should also mention that with all working versions (2.9.0 and 3.0-dev) I get normal logs but with 2.9.1 there is no logs, just two lines about forked worker and successful loading.

**Comment by cleocir** [comment] 2023-12-20 18:02
Same problem here. I am tried to use 2.9.1 with postgres (patroni ha)  backends, then all CPUs go to up 100% immediate after start. Other problem i detected was the connections to tcp backends not hangup (down) after close the tcp session. I was forced to downgrade to version 2.9.0 (it works fine).

**Comment by NullIsNot0** [comment] 2023-12-20 18:19
When checking through API, it seems no connection is released on 2.9.1
`echo "show info" | socat stdio tcp4-connect:127.0.0.1:9999 | grep "CurrConns: " | awk {'print $2'}` number is only growing until it reaches maximum and no new connections can be made to service. This hit me this morning. Was using 2.9.1-alpine, downgraded back to 2.9.0 and everything works again.

**Comment by capflam** [comment] 2023-12-20 19:06
Thanks for report. Anyone could get `show sess all` and `show fd` outputs when this happens ? In addition, you can try to disable the zero-copy forwarding by adding `-dZ` parameter on the command line or by adding `tune.disable-zero-copy-forwarding` in the global section. I suspect there is something wrong with commit 2421c6fa7db.

**Comment by cleocir** [comment] 2023-12-20 19:10
> Thanks for report. Anyone could get `show sess all` and `show fd` outputs when this happens ? In addition, you can try to disable the zero-copy forwarding by adding `-dZ` parameter on the command line or by adding `tune.disable-zero-copy-forwarding` in the global section. I suspect there is something wrong with commit [2421c6f](https://github.com/haproxy/haproxy/commit/2421c6fa7db5b06109a88bffa411c8ba8f948384).

i haved tried with tune.disable-zero-copy-forwarding and the problem continued here

**Comment by capflam** [comment] 2023-12-20 20:18
Hum ok thanks for the test.

**Comment by cleocir** [comment] 2023-12-20 20:31
> Hum ok thanks for the test.

Sorry! i haved test with `tune.h2.zero-copy-fwd-send off` with ` tune.disable-zero-copy-forwarding` i dont have tried

**Comment by capflam** [comment] 2023-12-20 20:35
If you have something else than HTTP/2 clients, fully disabling the zero-copy forwarding will help to be sure. And `show sess all` and `show fd` outputs will help to better understand what happens under the hood.

**Comment by capflam** [comment] 2023-12-20 20:36
The commit above is the best candidate to explain the regression between 2.9.0 and 2.9.1.

**Comment by pfactum** [comment] 2023-12-20 20:38
[show_fd.log](https://github.com/haproxy/haproxy/files/13732315/show_fd.log)
[show_sess_all.log](https://github.com/haproxy/haproxy/files/13732316/show_sess_all.log)

**Comment by capflam** [comment] 2023-12-20 20:39
Thanks, I'll take a look

**Comment by pfactum** [comment] 2023-12-20 20:44
Setting `tune.disable-zero-copy-forwarding` seems to help.

**Comment by capflam** [comment] 2023-12-20 20:48
Thanks guys, I'm able to reproduce the issue. I'm on it

**Comment by capflam** [comment] 2023-12-21 10:09
I pushed a fix, it should be ok now for the 3.0-dev. It will be backported as usual with other fixes. Thanks for your help !

**Comment by pfactum** [comment] 2023-12-21 10:58
@capflam thank you!

**Comment by eworm-de** [comment] 2023-12-22 16:04
Should be fixed in Arch Linux with `haproxy 2.9.1-2`.

**Comment by pfactum** [comment] 2023-12-22 16:07
@eworm-de can confirm that, thanks for proactiveness

**Comment by capflam** [comment] 2024-01-02 09:30
Now backported to 2.9

**Closed as completed by capflam** 2024-01-02 09:30 UTC
Labels: type: bug, status: fixed

**Comment by franzos** [comment] 2024-01-12 19:18
Saw the same issue on `haproxy:latest` and `haproxy:alpine`. Looks like `3.0-dev1` resolved it.

**Comment by Darlelet** [comment] 2024-01-12 19:49
2.9.2 was just released with the fix, it should take some more hours for the `:latest` docker tag to point to it

**Comment by lukastribus** [comment] 2024-02-09 10:22
I have "pinned" this issue now (right Github menu), as people continue to open duplicates about this.

Hopefully this increases visibility for this bug.

When people stop using 2.9.1 we can remove the pin.
