### ISSUE TITLE
Segmentation fault 0x00005555555c0375 in http_process_request ()

### ISSUE THREAD

**Issue by basos9** [haproxy/haproxy#63] opened 2019-03-14 14:45 UTC
## Output of `haproxy -vv` and `uname -a`

```
 haproxy -vv
HA-Proxy version 1.9.4-1~bpo9+1 2019/02/07 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-1.9.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.0f  25 May 2017
Running on OpenSSL version : OpenSSL 1.1.0j  20 Nov 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.22 2016-07-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace




Linux x.x.x.x 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

```

## What's the configuration?

```
global
 
  log /dev/log  local0
 
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  daemon
  
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s
 
  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private

  maxconn 100000



## Defaults
##
defaults

  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

  log global
  option log-separate-errors

  log-format "%ci - %[capture.req.hdr(0),regsub(^Basic ,),b64dec,field(1,:)] [%tr] %{+Q}r %ST %B %{+Q}[capture.req.hdr(1),regsub(^\$,-)] %{+Q}[capture.req.hdr(2),regsub(^\$,-)] HA %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq ID:%ID"

  option dontlognull

  mode  http

  unique-id-header x-req-id

  unique-id-format "%{+X}o %ci%cp%fi%Ts%rt%pid"


  frontend https-in
    bind *:444 ssl crt x.pem
    maxconn 40000

    capture request header Authorization len 64
    capture request header Referer len 128
    capture request header User-Agent len 200

    default_backend bb


  backend bb
    default-server maxconn 1000 check
    server x1 192.168.1.1:80 cookie x1
    server x2 192.168.1.2:80 cookie x2

```

## Steps to reproduce the behavior

1.  Load some requests, prererably in a web page with 40 or more requests, e.g. use chrome and continuously press F5 
2.  In my setup after some seconds the process segfaults
3. 

## Actual behavior

```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555c0375 in __pool_get_from_cache (pool=0x555555957540 <pool_base_start>) at include/common/memory.h:199
199	include/common/memory.h: No such file or directory.
(gdb) bt
#0  0x00005555555c0375 in __pool_get_from_cache (pool=0x555555957540 <pool_base_start>) at include/common/memory.h:199
#1  __pool_get_first (pool=0x555555957540 <pool_base_start>) at include/common/memory.h:216
#2  pool_alloc_dirty (pool=0x555555957540 <pool_base_start>) at include/common/memory.h:258
#3  pool_alloc (pool=0x555555957540 <pool_base_start>) at include/common/memory.h:272
#4  http_process_request (s=0x555555aa09e0, req=<optimized out>, an_bit=2048) at src/proto_http.c:2880
#5  0x00005555555ea726 in process_stream (t=<optimized out>, context=0x555555aa09e0, state=<optimized out>)
    at src/stream.c:1984
#6  0x00005555556b58c4 in process_runnable_tasks () at src/task.c:432
#7  0x000055555562d551 in run_poll_loop () at src/haproxy.c:2621
#8  run_thread_poll_loop (data=<optimized out>) at src/haproxy.c:2686
#9  0x00005555555865d2 in main (argc=<optimized out>, argv=<optimized out>) at src/haproxy.c:3315
```

## Expected behavior

normal operation

## Do you have any idea what may have caused this?
NOTE: It seems that commenting out the lines regarding to unique id hides  the issue. Also looking at the code it seems that the crash is near the code relating to unique id generation.
```
  # these lines seem suspicious
  #unique-id-header x-req-id
  #unique-id-format "%{+X}o %ci%cp%fi%Ts%rt%pid"
```

```
	if (!LIST_ISEMPTY(&sess->fe->format_unique_id) && !s->unique_id) {
		if ((s->unique_id = pool_alloc(pool_head_uniqueid)) == NULL)  // ******* CRASH HERE
			goto return_bad_req;
		s->unique_id[0] = '\0';
		build_logline(s, s->unique_id, UNIQUEID_LEN, &sess->fe->format_unique_id);
	}
```

**Comment by TimWolla** [comment] 2019-03-14 14:48
Duplicate of #40

**Closed as completed by TimWolla** 2019-03-14 14:48 UTC
Labels: type: bug, status: duplicate
