### ISSUE TITLE
3.0-dev8 runtime API "clear map" not clearing the whole map

### ISSUE THREAD

**Issue by felipewd** [haproxy/haproxy#2543] opened 2024-04-20 02:23 UTC
### Detailed Description of the Problem

We use the runtime API to update a large (almost 200,000 entries) map.

We do a `clear map <map>` and do a series of `add map <map> << <payload>` to add the entries.

Using 3.0 branch we've noticed a lot of duplicate entries, and digged a bit to discover the `clear map` is not working (it used to work on 2.9) as expected...it deletes only a few entries.

Just a quick example:

```
$ echo show map /etc/haproxy/storage.lst | socat stdio unix-connect:/var/run/haproxy_conexoes_backend10.sock   | wc -l
121508

$ echo clear map /etc/haproxy/storage.lst | socat stdio unix-connect:/var/run/haproxy_conexoes_backend10.sock

$ echo show map /etc/haproxy/storage.lst | socat stdio unix-connect:/var/run/haproxy_conexoes_backend10.sock   | wc -l
121308

<another clear map>
<another show map>: 121108
<another clear map>
<another show map>: 120908
```

### Expected Behavior

`clear map <map>` should delete all entries.

### Steps to Reproduce the Behavior

- We loop 200,000 entries map adding a payload of 2,000 entries per `add map`  with bufsize of 128KB

- Try and clear the map

### Do you have any idea what may have caused this?

Nope

### Do you have an idea how to solve the issue?

Not really

### What is your configuration?

```haproxy
global
    nbthread 16
    hard-stop-after 10m
    maxconn 900000
    ulimit-n 2700596
    user haproxy
    group haproxy
    daemon
...
    tune.bufsize 131072
...
    stats socket /var/run/haproxy_conexoes_backend10.sock mode 666 level admin expose-fd listeners
    stats timeout 10m
...
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0-dev8-ad6760b 2024/04/19 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 6.1.11 #1 SMP PREEMPT_DYNAMIC Fri Feb 10 01:29:15 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_NS=1 USE_PCRE=1 USE_PCRE_JIT=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT +PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=128).
Built with OpenSSL version : OpenSSL 1.1.1m  14 Dec 2021
Running on OpenSSL version : OpenSSL 1.1.1m  14 Dec 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
.
```

**Comment by felipewd** [comment] 2024-04-20 02:25
To make things easy to reproduce, we can load the map referencing the config-file, reload haproxy and try and clear the map right after a usual reload. 

No need to use `add map` to reproduce the issue

**Comment by Darlelet** [comment] 2024-04-20 12:12
Thanks for the report @felipewd!

```c
static int cli_io_handler_clear_map(struct appctx *appctx)
{
        struct show_map_ctx *ctx = appctx->svcctx;
        int finished;

        HA_RWLOCK_WRLOCK(PATREF_LOCK, &ctx->ref->lock);
        finished = pat_ref_purge_range(ctx->ref, ctx->curr_gen, ctx->prev_gen, 100);
        HA_RWLOCK_WRUNLOCK(PATREF_LOCK, &ctx->ref->lock);

        if (!finished) {
                /* let's come back later */
                applet_have_more_data(appctx);
```
map pruning is segmented through batches of 100 entries each to prevent the process from monopolizing a CPU core which would cause contention otherwise. If entries still remain after a pruning batch, the applet is re-scheduled to continue where it left off.

As you pointed out this used to work properly in the past, but since f37ddbeb4 ("MAJOR: cli: Update the CLI applet to handle its own buffers") it looks like the applet is not woken back properly and because of that it doesn't get the chance to finish the pruning process, and only a few hundreds items maximum are removed. When this happens, we can also notice that the cli command hangs instead of returning promptly.

**Comment by capflam** [comment] 2024-04-22 16:04
Indeed. Thanks @Darlelet ! The issue is in `sc_applet_recv()`. `SE_FL_HAVE_NO_DATA` flag is updated in the same way than for muxes while it is in fact the applet responsibility to do so.  I will push a commit soon. But in the mean time the following should fix the issue: 

```diff
diff --git a/src/stconn.c b/src/stconn.c
index 930b92b1bd..621d51e429 100644
--- a/src/stconn.c
+++ b/src/stconn.c
@@ -2094,9 +2094,7 @@ int sc_applet_recv(struct stconn *sc)
        }
 
  done_recv:
-       if (!cur_read)
-               se_have_no_more_data(sc->sedesc);
-       else {
+       if (cur_read) {
                channel_check_xfer(ic, cur_read);
                sc_ep_report_read_activity(sc);
        }
@@ -2125,12 +2123,7 @@ int sc_applet_recv(struct stconn *sc)
                sc->flags |= SC_FL_ERROR;
                ret = 1;
        }
-       else if (!cur_read &&
-                !(sc->flags & (SC_FL_WONT_READ|SC_FL_NEED_BUFF|SC_FL_NEED_ROOM)) &&
-                !(sc->flags & (SC_FL_EOS|SC_FL_ABRT_DONE))) {
-               se_have_no_more_data(sc->sedesc);
-       }
-       else {
+       else if (cur_read || (sc->flags & (SC_FL_WONT_READ|SC_FL_NEED_BUFF|SC_FL_NEED_ROOM))) {
                se_have_more_data(sc->sedesc);
                ret = 1;
        }
```

**Comment by capflam** [comment] 2024-04-23 05:35
Pushed ! It should be fixed now. Thanks !

**Closed as completed by capflam** 2024-04-23 05:35 UTC
Labels: type: bug, status: fixed

**Comment by felipewd** [comment] 2024-04-23 13:09
hey @capflam I can confirm this patches fixes the issue, thanks!
