### ISSUE TITLE
[Regression 2.3.0] crt-list parsing with negated hostnames fails

### ISSUE THREAD

**Issue by darix** [haproxy/haproxy#940] opened 2020-11-05 21:51 UTC
## Detailed description of the problem

A working crt-list config fails to serve some SAN entries after upgrading to 2.3.0. 2.2.x and older releases worked fine.

## Expected behavior

```bash
for i in host1 host2 ; do
  openssl s_client -servername ${i} -connect ${i}:1443 < /dev/null
done
```

This should report 2 successfull connections. But the connection for the TLSv1.3 only hosts (host2) fails. (see crt-list below)

## Steps to reproduce the behavior 

1. create SSL cert with 2 hostnames in it

2. haproxy.cfg
```haproxy.cfg
global
  log stderr daemon
  maxconn 32768
  tune.bufsize 32768

  tune.ssl.default-dh-param 2048

  ssl-default-bind-ciphers   ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

  ssl-default-bind-ciphersuites   TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384
  ssl-default-server-ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384

  ssl-default-bind-options ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.3 no-tls-tickets
  ssl-default-server-options ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.3 no-tls-tickets

defaults
  log global
  timeout connect      5s
  timeout client    3600s
  timeout server     450s

frontend ssl_bug
  mode http
  bind 0.0.0.0:1443   tfo ssl crt-list /path/to/certlist.cfg alpn h2 npn h2 strict-sni
  http-request return status 200 content-type text/plain string "hello world"



```

3. create cerlist.cfg
```
/path/to/somecert.pem   [ssl-min-ver TLSv1.2] host1 !host2
/path/to/somecert.pem   [ssl-min-ver TLSv1.3] host2 !host1
```

## Do you have any idea what may have caused this?

My guess is no certificate is listed for host2, and due to strict-sni no fallback is done.
Without strict-sni, the fallback works in my test setup, but in a setup with more than one cert,
it might pick the wrong cert in the fallback.

## What is your configuration?

see above

## Output of `haproxy -vv` and `uname -a`

```
CPE_NAME="cpe:/o:opensuse:tumbleweed:20201030"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
```

```
haproxy -vv
HA-Proxy version 2.3.0 2020/11/05 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.0.html
Running on: Linux 5.8.15-1-default #1 SMP Thu Oct 15 08:10:08 UTC 2020 (c680e93) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = x86_64
  CC      = cc
  CFLAGS  = -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_PTHREAD_PSHARED=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_PIE=1 USE_STACKPROTECTOR=1 USE_RELRO_NOW=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD +PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=24).
Built with OpenSSL version : OpenSSL 1.1.1h  22 Sep 2020
Running on OpenSSL version : OpenSSL 1.1.1h  22 Sep 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20200825 [revision c0746a1beb1ba073c7981eb09f55b3d993b32e5c]

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```

**Comment by wlallemand** [comment] 2020-11-06 09:12
There was a problem with the previous implementation of the negative filters, it was not working at all and was fixed in 2.2.3.
This filters were simply ignored by HAProxy letting the user think it was doing something if there was a corresponding positive filter on another line. 

It does not make sense to use it this way, because the positive filter has priority, so you can simply remove the negative filters from your configuration and you will have the right behavior. The negative filters should be used only to negate some part of a wildcard.

For example:
`foobar.pem *.host1.com !nossl.host1.com`

However I agree with you that it should work even if the negative filter is useless here, I'll take a look at this.

**Comment by wlallemand** [comment] 2020-11-06 10:33
I just tested with your configuration with the latest 2.2 and 2.3 and I can't reproduce your problem at all.
Could you share the error returned by your openssl commands ? thanks

Edit: I'm reproducing now, it's not related to the min-ssl-ver nor the negative filter, looks like something is seriously broken.

**Comment by wlallemand** [comment] 2020-11-06 10:58
The crt-list are broken, the bug was introduced by commit 47da821 "MEDIUM: ssl: emulates the multi-cert bundles in the crtlist". I'm working on a fix.

**Comment by wlallemand** [comment] 2020-11-06 16:01
This was fixed in the master repository and backported in 2.3. Thanks for the report !

**Closed as completed** 2020-11-06 16:03 UTC
Labels: type: bug, status: fixed

**Comment by darix** [comment] 2020-11-06 16:21
Fixed confirmed with 2.4dev0+git40.50c03aac0. updated my package for devel and 2.3 already.

just one curious observation:

client openssl s_client version 1.1.1h

as you see in the config above I have set no-tls-tickets. the same as in my production config.

production host openssl 1.1.1d
test host openssl 1.1.1.h

production host does:

```
---
No client certificate CA names sent
Peer signing digest: SHA384
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3168 bytes and written 382 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_CHACHA20_POLY1305_SHA256
Server public key is 384 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
DONE
```

test host:

```
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2236 bytes and written 386 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_CHACHA20_POLY1305_SHA256
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_CHACHA20_POLY1305_SHA256
    Session-ID: 634239CC1A9750AA2369F08493A0DC43BF504AA677858BD7EE4B82968280C5A8
    Session-ID-ctx: 
    Resumption PSK: 024F388C1709C5F803CEF95B9F49DC49041D1FE132C1CA0171FC946FD406761D
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 4c 5a b6 48 4e 28 91 e9-0f 0f cd 38 ed ed 72 6e   LZ.HN(.....8..rn
    0010 - 88 f1 b1 d6 20 13 f3 17-a7 e1 ca 56 3d 1b 6a 5a   .... ......V=.jZ

    Start Time: 1604679663
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_CHACHA20_POLY1305_SHA256
    Session-ID: 8AB87851C0F8F132772A4E9358D9148B61C8A168CAE0B852386E12F6C23B8446
    Session-ID-ctx: 
    Resumption PSK: F54603185DFB499B4FB6C14B989C187303D8ED403386F10D78E5358E7DC9209B
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - ce b5 39 70 ea d0 15 2d-de fe f3 77 f3 bc d4 c8   ..9p...-...w....
    0010 - 26 d8 21 e9 a4 83 be 77-66 c6 1b ee 47 fc 6e 00   &.!....wf...G.n.

    Start Time: 1604679663
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
DONE
```

Why do I get tickets there?

tested 2.2.4, 2.3.0, 2.4.0dev0+git40 and all show that behavior

**Comment by lukastribus** [comment] 2020-11-09 09:42
> Why do I get tickets there?
> 
> tested 2.2.4, 2.3.0, 2.4.0dev0+git40 and all show that behavior

Because you are using TLSv1.3.

As per the docs:
https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#5.1-no-tls-tickets

`The TLS ticket mechanism is only used up to TLS 1.2.`

**Comment by darix** [comment] 2020-11-09 14:35
both connections are using tls 1.3 one does tickets the other doesnt. and I would like to understand why.

**Comment by lukastribus** [comment] 2020-11-09 15:27
Ok, then please use the support channels, not the bug tracker.
