### ISSUE TITLE
haproxy + 0rtt starts using 100% CPU at random times

### ISSUE THREAD

**Issue by joellimberg** [haproxy/haproxy#411] opened 2019-12-16 16:01 UTC
At random times, Haproxy goes to 100% CPU usage and stays there. It doesn’t seem that requests are actually failing during that time.

I’ve seen this behaviour with many different haproxy versions, starting from (I think 1.8) (that is — upgrading to the latest version hasn’t solved it)

## Output of `haproxy -vv` and `uname -a`

```
haproxy -vv

    HA-Proxy version 2.1.1-1ppa1~bionic 2019/12/14 - https://haproxy.org/
    Status: stable branch - will stop receiving fixes around Q1 2021.
    Known bugs: http://www.haproxy.org/bugs/bugs-2.1.1.html
    Build options :
      TARGET  = linux-glibc
      CPU     = generic
      CC      = gcc
      CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-GwOBOb/haproxy-2.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
      OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

    Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

    Default settings :
      bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

    Built with multi-threading support (MAX_THREADS=64, default=2).
    Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
    Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
    OpenSSL library supports TLS extensions : yes
    OpenSSL library supports SNI : yes
    OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
    Built with Lua version : Lua 5.3.3
    Built with network namespace support.
    Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
    Built with PCRE2 version : 10.31 2018-02-12
    PCRE2 library supports JIT : yes
    Encrypted password support via crypt(3): yes
    Built with zlib version : 1.2.11
    Running on zlib version : 1.2.11
    Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
    Built with the Prometheus exporter as a service

    Available polling systems :
          epoll : pref=300,  test result OK
           poll : pref=200,  test result OK
         select : pref=150,  test result OK
    Total: 3 (3 usable), will use epoll.

    Available multiplexer protocols :
    (protocols marked as <default> cannot be specified using 'proto' keyword)
                  h2 : mode=HTTP       side=FE|BE     mux=H2
                fcgi : mode=HTTP       side=BE        mux=FCGI
           <default> : mode=HTTP       side=FE|BE     mux=H1
           <default> : mode=TCP        side=FE|BE     mux=PASS

    Available services :
    	prometheus-exporter

    Available filters :
    	[SPOE] spoe
    	[CACHE] cache
    	[FCGI] fcgi-app
    	[TRACE] trace
    	[COMP] compression
```

```
uname -a
Linux host.name.example.com 4.15.0 #1 SMP Thu Jun 27 15:10:55 MSK 2019 x86_64 x86_64 x86_64 GNU/Linu
```

## What's the configuration?

```
global
            log ${LOCAL_SYSLOG}:514 local0
            # log /dev/log    local0
            # log /dev/log    local1 notice
            chroot /var/lib/haproxy
            stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
            stats timeout 30s
            user haproxy
            group haproxy
            daemon

            log-send-hostname

            tune.ssl.default-dh-param 2048

            # Default SSL material locations
            ca-base /etc/ssl/certs
            crt-base /etc/ssl/private

            ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
            ssl-default-bind-options no-sslv3 no-tlsv10

    defaults
            log     global
            mode    http
            option  httplog
            option  dontlognull
            timeout http-request 20s
            timeout http-keep-alive 4s
            timeout connect 10s
            timeout client  20s
            timeout server  10s
    	timeout queue	6s
            errorfile 400 /etc/haproxy/errors/400.http
            errorfile 403 /etc/haproxy/errors/403.http
            errorfile 408 /etc/haproxy/errors/408.http
            errorfile 500 /etc/haproxy/errors/500.http
            errorfile 502 /etc/haproxy/errors/502.http
            errorfile 503 /etc/haproxy/errors/503.http
            errorfile 504 /etc/haproxy/errors/504.http

    	log-format %ci:%cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r\ REQUESTID=%ID


    frontend http-in
            mode http
            bind :80

    	http-response set-header Server CustomName

    	unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
    	unique-id-header X-Request-ID

            acl is_acme_challenge path_beg /.well-known/acme-challenge/

    	acl is_valid_http_method method GET HEAD OPTIONS
            http-request deny if ! is_valid_http_method

    	redirect scheme https code 301 if ! is_acme_challenge

            use_backend letsencrypt-backend if is_acme_challenge
            use_backend nothing


    frontend http-in-secure
            mode http
            bind :443 name https ssl strict-sni crt /etc/haproxy/certs/domain.pem allow-0rtt alpn h2,http/1.1

    	maxconn 5000

            capture request header Host len 60
            capture request header Content-Length len 10
            capture request header Referer len 100

    	http-response set-header Server CustomName

    	capture cookie __acookie= len 49

            unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
            unique-id-header X-Request-ID

            tcp-request inspect-delay 5s

            stick-table type ip size 500k expire 60s store http_req_rate(60s),conn_rate(60s)

            tcp-request connection reject if { src_http_req_rate gt 1200 }
    	tcp-request connection reject if { src_conn_rate gt 1200 }

            http-request deny if { src_http_req_rate gt 1200 }
            tcp-request connection track-sc1 src

            acl is_too_long_url url_len gt 2000
            http-request deny if is_too_long_url

    	acl is_valid_http_method method GET HEAD OPTIONS
    	http-request deny if ! is_valid_http_method

            use_backend nothing if ! { hdr(host) hostname-1.example.com } ! { hdr(host) hostname-2.example.com }

            use_backend varnish


    frontend internal-varnish-be
            mode http
            bind :8080
    	option dontlog-normal
    	no log
            use_backend mybackend-h-5


    backend varnish
            server mybackend-varnish 127.0.0.1:8090 maxconn 2000


    backend mybackend-h-5
            http-request set-header Host hostname-x.example.com

            server mybackend-h-5 11.11.11.11:443 ssl sni str(hostname-x.example.com) maxconn 70 verify required ca-file DST_Root_CA_X3.pem


    backend nothing
            errorfile 400 /etc/haproxy/errors/400-empty.http
            http-request deny deny_status 400


    backend letsencrypt-backend
            server letsencrypt 127.0.0.1:8091 maxconn 5
```

```
strace -tt output snippet:

14:54:09.596398 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 10) = 7
14:54:09.596460 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539479278}) = 0
14:54:09.596515 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539493232}) = 0
14:54:09.596566 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 10) = 7
14:54:09.596629 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539514516}) = 0
14:54:09.596683 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539527943}) = 0
14:54:09.596734 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 9) = 7
14:54:09.596796 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539549215}) = 0
14:54:09.596851 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539562981}) = 0
14:54:09.596907 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 9) = 7
14:54:09.596983 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539584806}) = 0
14:54:09.597039 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539598420}) = 0
14:54:09.597090 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 9) = 7
14:54:09.597152 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539619711}) = 0
14:54:09.597206 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539633047}) = 0
14:54:09.597257 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 9) = 7
14:54:09.597320 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539654265}) = 0
14:54:09.597374 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539667936}) = 0
14:54:09.597425 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 9) = 7
14:54:09.597487 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539689171}) = 0
14:54:09.597542 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539702935}) = 0
14:54:09.597593 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 9) = 7
14:54:09.597655 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539724153}) = 0
14:54:09.597709 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539737633}) = 0
14:54:09.597760 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 8) = 7
14:54:09.597822 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539758879}) = 0
14:54:09.597876 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539772377}) = 0
14:54:09.597931 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 8) = 7
14:54:09.597994 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539793548}) = 0
14:54:09.598049 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=6385, tv_nsec=539807298}) = 0
14:54:09.598100 epoll_wait(7, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=245, u64=245}}, {EPOLLOUT, {u32=79, u64=79}}, {EPOLLOUT, {u32=319, u64=319}}, {EPOLLOUT, {u32=351, u64=351}}, {EPOLLOUT, {u32=352, u64=352}}, {EPOLLOUT, {u32=279, u64=279}}, {EPOLLOUT, {u32=280, u64=280}}], 200, 8) = 7

```

```
strace -c output
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
64.82    2.622832           9    292307           clock_gettime
35.18    1.423343          10    146147           epoll_wait
0.00    0.000146          12        12           timer_settime
0.00    0.000134          11        12           rt_sigreturn
------ ----------- ----------- --------- --------- ----------------
100.00    4.046455                438478           total
```

## Steps to reproduce the behavior

Sorry, I don't have a specific idea, other than:

1. start haproxy with the given configuration
2. wait
3. observe haproxy process stuck in 100% CPU usage

## Actual behavior

Haproxy runs normally for (random period of time), but then CPU usage spikes:

<img width="1278" alt="Screen Shot 2019-12-16 at 17 58 35" src="https://user-images.githubusercontent.com/875872/70921876-c6413200-202d-11ea-8374-621752b89065.png">

<img width="786" alt="Screen Shot 2019-12-16 at 18 00 34" src="https://user-images.githubusercontent.com/875872/70921993-fc7eb180-202d-11ea-87b1-98cf46e2150b.png">

**Comment by wtarreau** [comment] 2019-12-16 16:19
Thank you for your report, Joel. I hoped these ones were only bad memories
now, but it seems there's still at least a remnant. I'm not seeing anything
unusual in your configuration which could explain this.

Next time it happens it would be nice if you could issue a "show fd" on the
CLI to correleate with the FDs reported as writable by epoll_wait(). I really
don't see what type of write event could be ignored :-/

**Comment by joellimberg** [comment] 2019-12-16 16:27
@wtarreau It just happened again.

Hoping `echo "show fd" | socat /run/haproxy/admin.sock -` is the correct command to run — 

This is the output: https://f.limberg.me/s/201912/161626140931a7138326/show-fd.txt

**Comment by joellimberg** [comment] 2019-12-16 16:30
Not sure if this is relevant, but I saw somewhere that close-wait is also something to track.

The output of `ss -atn | grep "CLOSE-WAIT"` is:

```
CLOSE-WAIT  1        0               127.0.0.1:38800           127.0.0.1:8090   
CLOSE-WAIT  1        0               127.0.0.1:39146           127.0.0.1:8090   
CLOSE-WAIT  1        0               127.0.0.1:37906           127.0.0.1:8090   
CLOSE-WAIT  1        0               127.0.0.1:39156           127.0.0.1:8090   
CLOSE-WAIT  1        0               127.0.0.1:37278           127.0.0.1:8090   
CLOSE-WAIT  1        0               127.0.0.1:39148           127.0.0.1:8090   
CLOSE-WAIT  1        0               127.0.0.1:38266           127.0.0.1:8090   
CLOSE-WAIT  143711   0               127.0.0.1:47730           127.0.0.1:8090   
CLOSE-WAIT  0        0               127.0.0.1:47728           127.0.0.1:8090   
```

(When haproxy is running normally, `ss -atn | grep "CLOSE-WAIT"` is empty)

**Comment by wtarreau** [comment] 2019-12-16 16:53
On Mon, Dec 16, 2019 at 08:27:17AM -0800, Joel Limberg wrote:
> @wtarreau It just happened again.
> 
> Hoping `echo "show fd" | socat /run/haproxy/admin.sock -` is the correct command to run -- 

Yes that's it, however it seems it's not on the same process as the previou
one, what's needed is to be able to compare the strace output to ths show fd
output. Sorry if I wasn't clear.

Still, in your trace I'm seeing fd #217 which is different from others in
that it was not yet converted to a session, maybe there's something there.

**Comment by joellimberg** [comment] 2019-12-16 16:57
Just for clarity: when the problem happens again, I should get the `strace -tt` & `show fd` outputs at the same time?

**Comment by wtarreau** [comment] 2019-12-16 17:13
On Mon, Dec 16, 2019 at 08:57:57AM -0800, Joel Limberg wrote:
> Just for clarity: when the problem happens again, I should get the `strace
> -tt` & `show fd` outputs at the same time?

Yes, that's exactly this. There's no hurry though because as you noticed,
those FDs will not disappear and that's precisely what is causing the CPU
loop and the CLOSE_WAIT.

Thanks!
Willy

**Comment by joellimberg** [comment] 2019-12-17 12:07
Here are 2 zipped log files (strace + show fd), run at the same time, during a high-CPU-usage event:

https://send.firefox.com/download/2c9d32c7040a04c4/#l0CMI_tEhPBMGaAdjc0CyQ

(I hope this expiring link is ok, wouldn't really want these logs to stay on the internet _forever_)

**Comment by wtarreau** [comment] 2019-12-17 12:35
Got them, thank you Joel!
So here's what we can see:
```
11:37:41.637514 epoll_wait(4, [{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=256, u64=256}}, {EPOLLOUT, {u32=218, u64=218}}, {EPOLLOUT, {u32=245, u64=245}}, {EPOLLOUT, {u32=103, u64=103}}, {EPOLLOUT, {u32=178, u64=178}}], 200, 43) = 5
$ grep 256 haproxy-2019-12-17-11-37-31.showfd.log 
    256 : st=0x32(R:Ra W:RA) ev=0x1c(HEOpi) [lc] tmask=0x1 umask=0x0 owner=0x7f9a703601f0 iocb=0x55ad6f36f410(conn_fd_handler) back=0 cflg=0x8020f360 fe=http-in-secure mux=H1 ctx=0x7f9a704d4dc0 h1c.flg=0x42 .sub=2 .ibuf=0@(nil)+0/0 .obuf=16384@0x7f9a70428f30+0/16384 h1s=0x55ad6fbd4da0 h1s.flg=0x4010 .req.state=MSG_DONE .res.state=MSG_DATA .meth=GET status=200 .cs.flg=0x00004000 .cs.data=0x55ad6fb8c678
```
So apparently we wake up the mux on the frontend side to emit data while there's an error and we don't do anything. The mux is blocked with IN_BUSY, this might explain why it doesn't handle the error. I'll have a deeper look.

Many thanks for capturing these!

**Comment by wtarreau** [comment] 2019-12-17 12:46
All of the problematic FDs have CO_FL_EARLY_SSL_HS set, indicating a 0-RTT handshake in progress! And indeed it prevent ssl_sock_from_buf() from doing anything, so we return without doing anything.

@cognet could you please have a look into this to figure if we're doing everything right ? I find it problematic that we call the send function because we're owken up on an EPOLLOUT event but we can't send since we have this flag set, an as a result we don't make progress. Very likely something needs to be called when we have this handshake in progress but I have no idea what :-/

@joellimberg in the mean time you can work around the issue by removing "allow-0rtt" from your bind lines if it is really too annoying.

**Comment by roidelapluie** [comment] 2019-12-17 12:48
@wtarreau We are experiencing this CPU usage but we don't have 0-rtt. What do you need to investigate?

**Comment by wtarreau** [comment] 2019-12-17 12:49
@roidelapluie be very careful, a number of *very* different issues can look similar as you might have noticed in the past in other bug reports. The simple fact that you don't have 0-rtt means it's not the same. Are you up-to-date ? We've fixed 2 or 3 of them in 2.1.1/2.0.11.

**Comment by cognet** [comment] 2019-12-17 12:51
It may mean the connection died early before we completed the handshake, I'm investigating

**Comment by lukastribus** [comment] 2019-12-17 12:52
@roidelapluie in case you are on 2.1.1 or 2.0.11, please file a new bug. Multiple bugs in the same GH issue cause confusion for everyone.

If it later turns out to have the same root cause, we can just mark it as duplicate.

**Comment by roidelapluie** [comment] 2019-12-17 12:52
Note: I don't see 0rtt in the config above neither.

**Comment by joellimberg** [comment] 2019-12-17 12:52
@wtarreau, @cognet Thanks for looking into this! I've disabled 0-rtt for now.

**Comment by joellimberg** [comment] 2019-12-17 12:54
@roidelapluie in my config (posted above), `frontend http-in-secure` does have `allow-0rtt` set

**Comment by wtarreau** [comment] 2019-12-17 12:57
Note, since a number of similar symptoms were reported lately, I've edited the subject to explicitly mention 0rtt to help distinguish the various reports. It doesn't mean it's the root cause but at least it's involved and participates here :-)

**Comment by wdauchy** [comment] 2019-12-17 18:57
(a side comment: we tested several times 0rtt with 2.0.x on our side but it always had to be reverted because of the mentioned cpu issues; we unfortunately never had time to dig into it and produce a proper bug report; we can however retest anything to provide more info if needed; so I'm just confirming we had similar behavior)

**Comment by wtarreau** [comment] 2019-12-19 08:34
FYI @cognet fixed it yesterday but forgot to mention it here and to mention the bug ID. It's now backported to 2.1 as commit a0a513399 and 2.0 as commit e82c1d451.

**Comment by cognet** [comment] 2019-12-19 10:22
It's not fixed yet ?

**Comment by wtarreau** [comment] 2019-12-19 10:24
@cognet I don't understand, is it a question ? I'm puzzled since you appear to be the only one able to respond it given that it's your fix :-/

**Comment by cognet** [comment] 2019-12-19 10:25
No, it is not a question.

**Comment by roidelapluie** [comment] 2019-12-19 10:26
I think the question is why the github issue is not closed @wtarreau

**Comment by cognet** [comment] 2019-12-19 10:26
No, it is more like "what makes you think it is fixed ?"

**Comment by wtarreau** [comment] 2019-12-19 10:27
I thought your patch about early data was this for this. I could have got confused. Maybe I should stop working on 160 bugs at the same time :-(

**Comment by TimWolla** [comment] 2019-12-19 10:41
I have reset the status labels until this confusion is cleared up.

**Comment by cognet** [comment] 2019-12-19 10:43
Thanks :) @wtarreau I'll take care of the issue

**Comment by cognet** [comment] 2019-12-19 14:11
Hi @joellimberg,

Any chance you can test the attached patch 0001-BUG-MEDIUM-ssl-Revamp-the-way-early-data-are-handled.txt ?
You may need 0001-BUG-MEDIUM-ssl-Don-t-set-the-max-early-data-we-can-r.txt too if you're not running the master of 2.1

Thanks !
[0001-BUG-MEDIUM-ssl-Revamp-the-way-early-data-are-handled.txt](https://github.com/haproxy/haproxy/files/3983932/0001-BUG-MEDIUM-ssl-Revamp-the-way-early-data-are-handled.txt)
[0001-BUG-MEDIUM-ssl-Don-t-set-the-max-early-data-we-can-r.txt](https://github.com/haproxy/haproxy/files/3983933/0001-BUG-MEDIUM-ssl-Don-t-set-the-max-early-data-we-can-r.txt)

**Comment by joellimberg** [comment] 2019-12-19 14:16
@cognet I'm sorry, but I'm not comfortable enough with Linux to actually compile Haproxy myself (I'm using the packages from https://launchpad.net/~vbernat/+archive/ubuntu/haproxy-2.1).

(Plus, this is a production server; and while I could divert live traffic away temporarily this wouldn't actually simulate actual traffic…)

**Comment by cognet** [comment] 2019-12-19 14:18
Of course, I understand, I guess I'll make sure it reaches 2.1 for the next release, then :)

**Comment by joellimberg** [comment] 2019-12-19 14:18
@cognet Thanks!

**Comment by wtarreau** [comment] 2019-12-20 13:22
Since the fix was merged and backported already, and you need to have the release to test it, I'll mark it as fixed for now and will close the issue to ease tracking of remaining ones. Do not hesitate to reopen it if the problem persists!

**Closed as completed by wtarreau** 2019-12-20 13:22 UTC
Labels: type: bug, subsystem: ssl, status: fixed

**Comment by joellimberg** [comment] 2019-12-28 15:52
FYI: I've upgraded to 2.1.2 and re-enabled 0-rtt, and haven't seen any issues (for 5 days). 👍

**Comment by cognet** [comment] 2019-12-28 15:57
That's nice to read, thanks a lot for letting us know :)

**Comment by wdauchy** [comment] 2020-01-07 13:05
it seems ok on our side as well, thanks for the patch!
