### ISSUE TITLE
Alpine docker images are not accessible

### ISSUE THREAD

**Issue by johnjeffers** [haproxy/haproxy#2820] opened 2024-12-14 09:38 UTC
### Detailed Description of the Problem

I'm not sure if this is the correct place to report an issue with Docker images, but this is critical. It seems that none of the `alpine` tagged docker images are currently working. Attempting to `docker pull` any `alpine` based image fails with a `manifest unknown` error.

### Expected Behavior

`docker pull haproxy:2.8-alpine` should work as expected and pull the image

### Steps to Reproduce the Behavior

```
# docker pull haproxy:2.8-alpine

2.8-alpine: Pulling from library/haproxy
manifest for haproxy:2.8-alpine not found: manifest unknown: manifest unknown
```

This problem occurs with every image I have tried that is based on `alpine`, not just the `2.8` image.

### What is your configuration?

```haproxy
Fails on multiple configurations, linux and Mac, local laptop and EC2.
```

### Output of `haproxy -vv`

```plain
n/a
```

**Comment by Darlelet** [comment] 2024-12-14 10:20
Should probably be filed here: https://github.com/docker-library/haproxy/issues

Could be related to https://github.com/docker-library/haproxy/issues/240

**Comment by johnjeffers** [comment] 2024-12-14 10:27
> Should probably be filed here: https://github.com/docker-library/haproxy/issues
> 
> Could be related to [docker-library/haproxy#240](https://github.com/docker-library/haproxy/issues/240)

Yes, thank you, that is the same problem I'm seeing

**Comment by Tristan971** [comment] 2024-12-14 11:28
fyi https://github.com/haproxytech/haproxy-docker-alpine exists and works roughly the same, if you don't particularly need the images that Docker-the-company manages

**Comment by thaJeztah** [comment] 2024-12-14 17:14
- https://github.com/docker-library/docker/issues/519
- https://github.com/docker-library/docker/issues/520

**Comment by thaJeztah** [comment] 2024-12-14 19:17
Update on this issue; a colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"

There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images. These images will likely be processed later, which may be done after the weekend.

**Comment by Darlelet** [comment] 2024-12-16 14:28
Closing as the upstream issue now seems to be resolved

**Closed as completed by Darlelet** 2024-12-16 14:28 UTC
Labels: type: bug, status: invalid
