### ISSUE TITLE
splice-response on 2.0.15-18 makes slow transfers

### ISSUE THREAD

**Issue by felipewd** [haproxy/haproxy#901] opened 2020-10-16 18:55 UTC
## Detailed description of the problem

When enabling `splice-response` as a default setting, after 2.0.10 (we've tested 2.0.15 up until 2.0.18), our server behaves very odd: Our app server (unix-socket on the same machine as haproxy) starts filling up with slow-delivering data, up until everything grinds to a nearly halt.

Using 2.0.10 fixes this, but there a few bugs that are currently crashing the server, so we need to upgrade. Disabling `splice-response` fixes this behavior, but we'd like the benefits of it for our HTTP transfers.

## Expected behavior

Using the latest 2.0.18 version, `splice-response` doesn't slow down the transfers.

## Steps to reproduce the behavior

Right...not sure if this is related to HTTP transfers, 1.1 TLS or 2.0 TLS transfers. Since this happens using production traffic, our for debugging options are limited

## What is your configuration?

Typical stuff, but the not-so-usual are:
```
global
    nbproc 10
    user haproxy
    group haproxy
    daemon
    hard-stop-after 10m
    ssl-engine rdrand
    ssl-mode-async
    unix-bind user haproxy mode 777

    tune.ssl.default-dh-param 2048
    tune.ssl.maxrecord 1419
    tune.idletimer 1000

defaults
    mode    http 

option splice-response 
 
    option abortonclose 
 
    retries 1 
    maxconn 900000 
    timeout connect 10s 
    timeout server 40s 
    timeout server-fin 600ms 
    timeout client 40s
    timeout client-fin 600ms
    timeout http-request 10s
    timeout http-keep-alive 10s
    timeout tunnel 40s

```

## Output of `haproxy -vv` and `uname -a`

Currently using 2.0.18 without `splice-response`:

```
HA-Proxy version 2.0.18-be8b761 2020/09/30 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -fPIC -g -march=haswell
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_NS=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=24).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

```

But using a local-compiled 2.0.10 version (same build options) make this part works. (crashes for known bugs in that version unrelated to this).

```
Linux s3 4.18.16 #1 SMP PREEMPT Tue Oct 30 21:07:44 -03 2018 x86_64 Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz GenuineIntel GNU/Linux
```

**Comment by capflam** [comment] 2020-10-16 20:25
Some bugs concerning the splicing was fixed in the 2.0.16 and some others in the 2.0.17. Unfortunately, I made some tests and there is still a bug in the 2.0.18. In fact, there is a forgotten fix, pushed in the early stage of the 2.1 and never backported. I guess the bug was hidden till now and revealed because of recent fixes.

Because it is a sensitive part, I will perform more tests before backporting it. But on your part, you may try it to be sure it fixes your problem. You may apply it on top of the 2.0.18 or on top of the 2.0 repository.

[0001-BUG-MEDIUM-h1-Always-try-to-receive-more-in-h1_rcv_b.patch.txt](https://github.com/haproxy/haproxy/files/5394100/0001-BUG-MEDIUM-h1-Always-try-to-receive-more-in-h1_rcv_b.patch.txt)

**Comment by felipewd** [comment] 2020-10-17 01:31
Hi @capflam,

Thank you for the quick reply. I can confirm that this patch (on top of 2.0.18) fixes our issue!

Thanks!

**Comment by capflam** [comment] 2020-10-19 06:53
Ok, I backported the fix. Thanks !

**Closed as completed by capflam** 2020-10-19 06:53 UTC
Labels: type: bug, status: fixed, subsystem: h1

**Comment by EmericBr** [comment] 2021-11-17 14:04
Just for note: ssl-mode-async is useless on engine rdrand, since this engine doesn't use a device and was not blocking. ssl-mode-async was designed to work using intel quick assist engine.
