### ISSUE TITLE
src/http_client.c: couple of coverity findings

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1687] opened 2022-05-05 05:57 UTC
### Tool Name and Version

coverity

### Code Report

```plain
** CID 1488478:  Null pointer dereferences  (NULL_RETURNS)


________________________________________________________________________________________________________
*** CID 1488478:  Null pointer dereferences  (NULL_RETURNS)
/src/http_client.c: 550 in httpclient_start()
544                     ist2str(trash.area, host);
545                     ss_dst = str2ip2(trash.area, &ss_url, 0);
546                     if (!ss_dst) { /* couldn't get an IP from that, try to resolve */
547                             doresolve = 1;
548                             ss_dst = str2ip2("0.0.0.0", &ss_url, 0);
549                     }
>>>     CID 1488478:  Null pointer dereferences  (NULL_RETURNS)
>>>     Dereferencing a pointer that might be "NULL" "ss_dst" when calling "sock_inet_set_port".
550                     sock_inet_set_port(ss_dst, port);
551             }
552     
553             /* The HTTP client will be created in the same thread as the caller,
554              * avoiding threading issues */
555             appctx = appctx_new(applet, NULL);

** CID 1488477:  Null pointer dereferences  (REVERSE_INULL)
/src/http_client.c: 585 in httpclient_start()


________________________________________________________________________________________________________
*** CID 1488477:  Null pointer dereferences  (REVERSE_INULL)
/src/http_client.c: 585 in httpclient_start()
579                             ha_alert("httpclient: OpenSSL is not available %s:%d.\n", __FUNCTION__, __LINE__);
580                             goto out_free_sess;
581     #endif
582                             break;
583             }
584     
>>>     CID 1488477:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "ss_dst" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
585             if (!ss_dst) {
586                     ha_alert("httpclient: Failed to initialize address %s:%d.\n", __FUNCTION__, __LINE__);
587                     goto out_free_sess;
588             }
589     
590             if (!sockaddr_alloc(&addr, ss_dst, sizeof(*ss_dst)))
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by capflam** [comment] 2022-05-18 07:24
Duplicate of #1705 and #1706.

**Closed as completed by capflam** 2022-05-18 07:24 UTC
Labels: type: code-report
