### ISSUE TITLE
Wrong value return after clear map execution ( runtime api )

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#844] opened 2020-09-07 08:31 UTC
haproxy version : 2.1.4, 2.2.4

We've used to user-agent blacklist by map acl(blacklist) in haproxy
But our haproxy was broken this morning after "clear map"runtime api execution

I got a log below from haproxy 
### error log 
```
Lua sample-fetch 'compare_values': runtime error: lua/functions.lua:22: attempt to index a number value (local 'host1') from lua/functions.lua:22 C function line 13.
```

### blacklist map example
```
# key         domain 
python-request aa.example.com
```

### haproxy config example
```
http-request set-var(txn.host1) hdr(User-Agent),lower,map_sub(ua_blacklist.map)
http-request set-var(txn.host2) hdr(Host),field(1,:),lower
acl BLACKLIST lua.compare_value(txn.host1,txn.host2)
http-request deny if BLACKLIST

# purporse ( multiple domain managing )
# Rejected if request host header is aa.example.com and user agent is python-request/xxx
# Pass the request if host is bb.example and user-agent is python-request/xxx 
```

### lua script
```lua
function compare_values(txn,var1,var2)
    local host1 = txn:get_var(var1)
    local host2 = txn:get_var(var2)
    --if host1 == nil or host2 == nil then  old condition --
    if host1 == nil or type(host1) == "number" or host2 == nil then -- for haproxy-2.2.x
        return false
    end
    --core.log(core.debug, "UA match: " .. host1) -- debug

    for match in (host1):gmatch("[^,]+") do
       --core.log(core.debug, "Host: " .. host2) -- debug
       if host2 == match then
           --core.log(core.debug, "compare match: " .. match) -- debug
           return true
       end
    end
    return false
end

core.register_fetches("compare_values",compare_values)
```

### problem 
I think that host1's correct value is nil (null)  but haproxy map replay wrong value as number or strange string in haproxy 2.1.4
Reply only number value in haproxy 2.2.2.

Host1 value will same to host2 value after Strange word  in haproxy 2.1.x.
meaning)
if real request is that host is bb.example and user-agent is python-request/xxx, 
host1 is changed aa.example.com after "Clear map" so bb.example.com will be denied. <- problem 

if i execute <b>"delete map <map-file> <key>" , threre is no problem.</b> : correct host1 value is null
but if i execute "clear map <map-file>", haproxy is wrong operated.

**Comment by wtarreau** [comment] 2020-09-08 07:51
I cannot reproduce this with either 2.1, 2.2 or 2.3. I had to slightly adjust your config to this (missing 's' in 'values', and missing `-m bool`) :
```
http-request set-var(txn.host1) hdr(User-Agent),lower,map_sub(ua_blacklist.map)
http-request set-var(txn.host2) hdr(Host),field(1,:),lower
acl BLACKLIST lua.compare_values(txn.host1,txn.host2) -m bool
http-request deny if BLACKLIST
```
I correctly get a 403 only when sending `aa.example.com` when the map contains it. When issuing `clear map #0` then it doesn't match anymore and bb.example.com doesn't start to match. Are you sure you don't have a bug somewhere in your more complete config or script ?

**Comment by zino7825** [comment] 2020-09-09 06:08
@wtarreau thx your interesting

`acl BLACKLIST lua.compare_values(txn.host1,txn.host2) -m bool` is right ( I already use this // above is typo )

you should try to below

1.  Request with user-agent including python-request
```
while : ;do 
  curl -s 'Host: aa.example.com' -H 'User-Agent: python-request:/2.2.2' localhost/xxx; 
  curl -s 'Host: bb.example.com' -H 'User-Agent: python-request:/2.2.2' localhost/xxx; 
done
```

2. try to add map ua_blacklist.map python-request aa.example.com
you can see the dropped request of aa.example.com 

3. try to clear map ua_blacklist.map 
you can see the strange things 

If you want to see the value in the log directly you have to remove the annotation( debug line) in lua script. 
I assure It will appear different result between 'clear map' and 'delete map'.

**Comment by wtarreau** [comment] 2020-09-09 06:45
Indeed I managed to get one crash now, but I didn't have core dumps enabled. However seeing where it died, it makes me suspect there is insufficient locking in pat_ref_prune(). I don't know the data model well there, but it seems to me that some of the elements that are manipulated under the read lock in pattern_exec_match() are the same that are modified/freed out of the lock by pat_ref_prune in the second loop. Probably that the element is not sufficiently detached from the first list under the lock and that we ought not find it.

**Comment by zino7825** [comment] 2020-09-09 07:12
I can easily reproduce this situation anytime.

I wonder what is reason that there is no problem when i execute delete map.
if I execute delete map,  txn.host1 value is null so there is no problem.

when i did a test(clear map test) in the Haproxy 2.2.2,  txn.host1 is always get a number (1, 10, ... ) so
I can avoid this issue through adding a this condition `( type(host1) == number )` in lua
but we can't prevent a problem in 2.1.x version because txn.host1 variable has got strange word or same to host header value or number.

**Comment by wtarreau** [comment] 2020-09-09 07:47
It clearly is a race condition, so once you meet the "strange situation", you don't know anymore if you can still trust the process. What you observe might be OK during your tests and happen differently in production for example.

**Comment by wtarreau** [comment] 2020-09-09 07:59
I've had a quick look at doc/internals/pattern.pdf to figure whether the locking is sufficient, and of now I must admit it still remains very obscure to me :-/

**Comment by wtarreau** [comment] 2020-09-09 07:59
Please could you at least verify that if you set "nbthread 1" in the global section, it doesn't fail anymore ?

**Comment by capflam** [comment] 2020-09-09 08:45
It is also obscure for me, but without any concurrency, `clear map` and `del map` does not "always" produce the same result. I've tested removing the key "python-request" or clearing the map after HAProxy startup and both produce the same result, no matching when a request is evaluated. 

But if I send at least a request before clearing the map, `pattern_exec_match()` succeeds for subsequent requests. At the end, it returns a pattern with data set to NULL, but inside the function, it is set with junk data. Deleting the key always produce the expected result.

I guess `pat_ref_prune()` does not totally remove all keys or it does not clear the cache. I don't know yet.

**Comment by capflam** [comment] 2020-09-09 14:05
After some tests, it is indeed a problem with the LRU cache of patterns. With several threads, it is pretty easy to have a crash if the map is cleared during a stress test. It works as expected by setting ` tune.pattern.cache.-size` global value to 0.

Here is a quick patch that seems to fix the bug :

```diff
iff --git a/src/pattern.c b/src/pattern.c
index a404ac34d..5de9de1ab 100644
--- a/src/pattern.c
+++ b/src/pattern.c
@@ -1093,6 +1093,7 @@ void pat_prune_val(struct pattern_expr *expr)
        struct pattern_list *pat, *tmp;
 
        list_for_each_entry_safe(pat, tmp, &expr->patterns, list) {
+               LIST_DEL(&pat->list);
                free(pat->pat.data);
                free(pat);
        }
@@ -1100,6 +1101,7 @@ void pat_prune_val(struct pattern_expr *expr)
        free_pattern_tree(&expr->pattern_tree);
        free_pattern_tree(&expr->pattern_tree_2);
        LIST_INIT(&expr->patterns);
+       expr->revision = rdtsc();
 }
 
 void pat_prune_ptr(struct pattern_expr *expr)
@@ -1107,6 +1109,7 @@ void pat_prune_ptr(struct pattern_expr *expr)
        struct pattern_list *pat, *tmp;
 
        list_for_each_entry_safe(pat, tmp, &expr->patterns, list) {
+               LIST_DEL(&pat->list);
                free(pat->pat.ptr.ptr);
                free(pat->pat.data);
                free(pat);
@@ -1115,6 +1118,7 @@ void pat_prune_ptr(struct pattern_expr *expr)
        free_pattern_tree(&expr->pattern_tree);
        free_pattern_tree(&expr->pattern_tree_2);
        LIST_INIT(&expr->patterns);
+       expr->revision = rdtsc();
 }
 
 void pat_prune_reg(struct pattern_expr *expr)
@@ -1122,6 +1126,7 @@ void pat_prune_reg(struct pattern_expr *expr)
        struct pattern_list *pat, *tmp;
 
        list_for_each_entry_safe(pat, tmp, &expr->patterns, list) {
+               LIST_DEL(&pat->list);
                regex_free(pat->pat.ptr.ptr);
                free(pat->pat.data);
                free(pat);
@@ -1130,6 +1135,7 @@ void pat_prune_reg(struct pattern_expr *expr)
        free_pattern_tree(&expr->pattern_tree);
        free_pattern_tree(&expr->pattern_tree_2);
        LIST_INIT(&expr->patterns);
+       expr->revision = rdtsc();
 }
 
 /*
```
Renewing the revision when a pattern expression is pruned is a good way to evict it from the LRU cache. But I'm not totally convinced it really fixes the problem.

**Comment by wtarreau** [comment] 2020-09-09 14:14
Good! I have also been wondering where these missing LIST_DEL() were made and still couldn't figure it out.
I must admit I had not thought about the LRU cache at all here! I don't remember how the pattern is linked there, my concerns are about who's responsible for freeing the attached memory locations. But as long as `expr` remains present, updating the revision will indeed ensure we don't return an old pattern.

By the way I only got a crash once and could never make it fail at all anymore, even with 8 threads, 100k req/s and 100 clear+add per second :-(

**Comment by zino7825** [comment] 2020-09-11 05:07
> Please could you at least verify that if you set "nbthread 1" in the global section, it doesn't fail anymore ?

We do not consider "nbhtread 1"

**Comment by zino7825** [comment] 2020-09-11 05:10
> After some tests, it is indeed a problem with the LRU cache of patterns. With several threads, it is pretty easy to have a crash if the map is cleared during a stress test. It works as expected by setting ` tune.pattern.cache.-size` global value to 0.
> 
> Here is a quick patch that seems to fix the bug :
> 
> ```diff
> iff --git a/src/pattern.c b/src/pattern.c
> index a404ac34d..5de9de1ab 100644
> --- a/src/pattern.c
> +++ b/src/pattern.c
> @@ -1093,6 +1093,7 @@ void pat_prune_val(struct pattern_expr *expr)
>         struct pattern_list *pat, *tmp;
>  
>         list_for_each_entry_safe(pat, tmp, &expr->patterns, list) {
> +               LIST_DEL(&pat->list);
>                 free(pat->pat.data);
>                 free(pat);
>         }
> @@ -1100,6 +1101,7 @@ void pat_prune_val(struct pattern_expr *expr)
>         free_pattern_tree(&expr->pattern_tree);
>         free_pattern_tree(&expr->pattern_tree_2);
>         LIST_INIT(&expr->patterns);
> +       expr->revision = rdtsc();
>  }
>  
>  void pat_prune_ptr(struct pattern_expr *expr)
> @@ -1107,6 +1109,7 @@ void pat_prune_ptr(struct pattern_expr *expr)
>         struct pattern_list *pat, *tmp;
>  
>         list_for_each_entry_safe(pat, tmp, &expr->patterns, list) {
> +               LIST_DEL(&pat->list);
>                 free(pat->pat.ptr.ptr);
>                 free(pat->pat.data);
>                 free(pat);
> @@ -1115,6 +1118,7 @@ void pat_prune_ptr(struct pattern_expr *expr)
>         free_pattern_tree(&expr->pattern_tree);
>         free_pattern_tree(&expr->pattern_tree_2);
>         LIST_INIT(&expr->patterns);
> +       expr->revision = rdtsc();
>  }
>  
>  void pat_prune_reg(struct pattern_expr *expr)
> @@ -1122,6 +1126,7 @@ void pat_prune_reg(struct pattern_expr *expr)
>         struct pattern_list *pat, *tmp;
>  
>         list_for_each_entry_safe(pat, tmp, &expr->patterns, list) {
> +               LIST_DEL(&pat->list);
>                 regex_free(pat->pat.ptr.ptr);
>                 free(pat->pat.data);
>                 free(pat);
> @@ -1130,6 +1135,7 @@ void pat_prune_reg(struct pattern_expr *expr)
>         free_pattern_tree(&expr->pattern_tree);
>         free_pattern_tree(&expr->pattern_tree_2);
>         LIST_INIT(&expr->patterns);
> +       expr->revision = rdtsc();
>  }
>  
>  /*
> ```
> 
> Renewing the revision when a pattern expression is pruned is a good way to evict it from the LRU cache. But I'm not totally convinced it really fixes the problem.

Thx, I will patch this and share after testing.

**Comment by zino7825** [comment] 2020-09-11 06:05
@capflam 
I've finished test of patch.
No more problem after patch. Thanks!

**Comment by capflam** [comment] 2020-09-11 08:07
Nice ! thanks for testing. I pushed the fix. I'm on the backport

**Closed as completed** 2020-09-11 09:19 UTC
Labels: type: bug, severity: medium, status: fixed
