### ISSUE TITLE
NOSRV when I enable CORS

### ISSUE THREAD

**Issue by AnassDriate** [haproxy/haproxy#2250] opened 2023-08-11 15:04 UTC
### Detailed Description of the Problem

Hello,

When i enable CORS, i start getting NOSRV (cors.lua) in the logs, but still everything works as expected, just the logs get more complicated.

Regards,

```
Apr 13 16:00:25 XXX haproxy[790172]: xx:xxx:xxx:xxx:xx [13/Apr/2023:16:00:25.576] https-in~ matrix-well-known-client/**<NOSRV>**  0/-1/-1/-1/0 200 479 - - LR-- 6/5/0/0/3 0/0 "GET /.well-known/matrix/server HTTP/1.1"
Apr 13 16:00:26 XXX haproxy[790172]: xx:xxx:xxx:xxx:xx [13/Apr/2023:16:00:26.632] https-in~ matrix-well-known-client/**<NOSRV>**  0/-1/-1/-1/0 200 479 - - LR-- 8/6/0/0/3 0/0 "GET /.well-known/matrix/server HTTP/1.1"
Aug 11 17:06:08 XXX haproxy[3342655]: xx:xxx:xxx:xxx:xx [11/Aug/2023:17:06:08.909] https-in~ https-in/<NOSRV> 0/-1/-1/-1/0 204 166 - - LR-- 4/4/0/0/0 0/0 "OPTIONS /r0/login HTTP/1.1"
```

### Expected Behavior

logs without LR NOSRV ...

### Steps to Reproduce the Behavior

load cors.lu 

### What is your configuration?

```haproxy
#lua-load /etc/haproxy/cors.lua

 ## CORS
    #http-request lua.cors "*" "my.domain.com" "*"
    #http-response lua.cors
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.9-2+deb11u5 2023/04/10 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
Running on: Linux 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -ffile-prefix-map=/build/haproxy-6Gqgxt/haproxy-2.2.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

**Comment by capflam** [comment] 2024-02-29 14:32
Sorry, the issue was lost in middle of other bug reports. It is expected. The response is returned by HAProxy. So `LR--` termination state is expected. And because it happens before any server was selected, `<NOSRV>` is reported. It is totally normal. If it is a problem, you can use `dontlog-normal` option, but it will concern all logs. It may be unexpected. Another way to do is to use `http-request set-log-level silent` rule with the right conditions.

As a side note, there is a lua function to change the log level too: `txn.set_loglevel`. But there is a bug, I must fix it. In addition, I will add `core.silent` because it is not possible to disable logging via lua for now.

But, here there is no bug. It is the expected behavior. I'm closing the issue. Thanks !

**Closed as not planned by capflam** 2024-02-29 14:32 UTC
Labels: type: bug, status: works as designed
