### ISSUE TITLE
2.2.5 cannot enable a frontend that was launched disabled

### ISSUE THREAD

**Issue by domdom82** [haproxy/haproxy#1047] opened 2021-01-12 14:06 UTC
## Detailed description of the problem

I am trying to dynamically load certificates into HAproxy using the socket API.
The crt-list will be empty on startup. I have sidecar process that fetches the certificates from an external source and pushes them to HAproxy. So to prevent the HAproxy from getting any traffic while it does not yet have all certificates loaded, I want to disable a frontend that acts as a health check for an upstream load balancer.
Once the certificates are uploaded to HAproxy, I would like to re-enabled the health check frontend so that HAproxy starts to receive traffic.

However whenever I run the command to enable the health check frontend, I get this error:
```
Frontend was previously shut down, cannot enable.
```

## Expected behavior

HAproxy should launch the frontend but in stopped mode as described in the docs here: http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#4.2-disabled

## Steps to reproduce the behavior

1. Add a listen or frontend section with `disabled` keyword
2. Launch HAproxy
3. Try to enable via `echo "enable frontend health_check_http_url" | socat /var/run/haproxy.sock -`

## Do you have any idea what may have caused this?

It seems the frontend gets created in "shutdown" mode instead of "stopped" mode.

## Do you have an idea how to solve the issue?

The keyword should cause the frontend to be created but stopped instead of shutdown mode.

## What is your configuration?

```
global
  log /dev/log len 4096 format rfc3164 syslog info
  stats socket /var/run/haproxy.sock mode 600 expose-fd listeners level admin

defaults
  log global
  mode http
  timeout connect 5s
  timeout client 5s
  timeout server 5s

listen health_check_http_url
  disabled
  bind :8080
  mode http
  monitor-uri /health
  acl httpstatus_down nbsrv(httpstatus) eq 0
  monitor fail if httpstatus_down

frontend myfrontend
  bind :443 ssl crt /etc/cert/server.pem crt-list /crt-list
  log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslc %sslv"
  default_backend httpstatus

  capture request header Host len 256
  capture request header User-agent len 256

  http-request set-header Host httpstat.us

backend httpstatus
	server httpstatus httpstat.us:80

```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.5-34b2b10 2020/11/05 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.5.html
Running on: Linux 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

Linux 9d914f3992b7 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
no crashes
```

## Additional information (if helpful)
n/a

**Comment by lukastribus** [comment] 2021-01-12 14:17
This is not a bug, it's simply not supported, as per the error message.

The real feature request behind this is about disabling and enabling listeners during runtime, which is filed here:
https://github.com/haproxy/haproxy/issues/270

**Comment by domdom82** [comment] 2021-01-12 14:24
hi @lukastribus thanks for the quick response. I am not sure if both issues mean the same thing. Notice that I actually CAN disable the listener after it has been started initially.

So this works if I remove the `disabled` keyword from the config:
```
echo "disable frontend health_check_http_url" | socat /var/run/haproxy.sock -

(do something else)

echo "enable frontend health_check_http_url" | socat /var/run/haproxy.sock -
```

It just doesn't work if the listener is disabled in the config to begin with.

**Comment by lukastribus** [comment] 2021-01-12 14:28
Yes, I'm aware. This boils down to disabling / enabling listeners, which is what the other feature request is about.

**Comment by domdom82** [comment] 2021-01-12 14:52
Hmm then it could be a documentation bug. The docs say:
```
The "disabled" keyword is used to disable an instance, mainly in order to
liberate a listening port or to temporarily disable a service. The instance
will still be created and its configuration will be checked, but it will be
created in the "stopped" state and will appear as such in the statistics.
```

So my assumption was that the frontend is still created but should be something like this in `show stat`:
```
health_check_http_url,FRONTEND,,,0,4,512000,1711479,260145445,249875934,0,0,0,,,,,STOP,,,,,,,,,1,3,0,,,,0,0,0,14,,,,0,1711479,0,0,0,0,,0,14,1711479,,,0,0,0,0,,,,,,,,,,,,,,,,,,,,,http,,0,14,1711479,1711479,0,0,0,,,0,0,,,
health_check_http_url,BACKEND,0,0,0,0,51200,0,260145445,249875934,0,0,,0,0,0,0,UP,0,0,0,,0,545175,,,1,3,0,,0,,1,0,,0,,,,0,0,0,0,0,0,,,,0,0,0,0,0,0,0,-1,,,0,0,0,0,,,,,,,,,,,,,,http,roundrobin,,,,,,,0,0,0,0,0,,,
```
(this is how it looks like after I send the `disable frontend` socket command)

Instead when I add the `disabled` keyword it does not show up at all:
```
echo "show stat" | socat ./haproxy.sock -
# pxname,svname,qcur,qmax,scur,smax,slim,stot,bin,bout,dreq,dresp,ereq,econ,eresp,wretr,wredis,status,weight,act,bck,chkfail,chkdown,lastchg,downtime,qlimit,pid,iid,sid,throttle,lbtot,tracked,type,rate,rate_lim,rate_max,check_status,check_code,check_duration,hrsp_1xx,hrsp_2xx,hrsp_3xx,hrsp_4xx,hrsp_5xx,hrsp_other,hanafail,req_rate,req_rate_max,req_tot,cli_abrt,srv_abrt,comp_in,comp_out,comp_byp,comp_rsp,lastsess,last_chk,last_agt,qtime,ctime,rtime,ttime,agent_status,agent_code,agent_duration,check_desc,agent_desc,check_rise,check_fall,check_health,agent_rise,agent_fall,agent_health,addr,cookie,mode,algo,conn_rate,conn_rate_max,conn_tot,intercepted,dcon,dses,wrew,connect,reuse,cache_lookups,cache_hits,srv_icur,src_ilim,qtime_max,ctime_max,rtime_max,ttime_max,eint,idle_conn_cur,safe_conn_cur,used_conn_cur,need_conn_est,
myfrontend,FRONTEND,,,0,0,524270,0,0,0,0,0,0,,,,,OPEN,,,,,,,,,1,3,0,,,,0,0,0,0,,,,0,0,0,0,0,0,,0,0,0,,,0,0,0,0,,,,,,,,,,,,,,,,,,,,,http,,0,0,0,0,0,0,0,,,0,0,,,,,,,0,,,,,
httpstatus,httpstatus,0,0,0,0,,0,0,0,,0,,0,0,0,0,no check,1,1,0,,,73,,,1,4,1,,0,,2,0,,0,,,,0,0,0,0,0,0,,,,0,0,0,,,,,-1,,,0,0,0,0,,,,,,,,,,,,104.18.49.187:80,,http,,,,,,,,0,0,0,,,0,,0,0,0,0,0,0,0,0,0,
httpstatus,BACKEND,0,0,0,0,52427,0,0,0,0,0,,0,0,0,0,UP,1,1,0,,0,73,0,,1,4,0,,0,,1,0,,0,,,,0,0,0,0,0,0,,,,0,0,0,0,0,0,0,-1,,,0,0,0,0,,,,,,,,,,,,,,http,roundrobin,,,,,,,0,0,0,0,0,,,0,0,0,0,0,,,,,
```

So it seems, contrary to what the documentation says, that the listener is never created when the `disabled` keyword is used.

**Comment by wtarreau** [comment] 2021-01-13 07:27
Hi,

right now "disabled" is the only alternative to entirely removing a config section. The most common use case for not binding a listening port that is temporarily bound to another process (other haproxy instance or the server). For example let's say you're trying to install haproxy in front of Apache or NGINX, each time you try you figure a few config mistakes, you certainly don't want to comment/uncomment everything again and again while validating your changes, so you just add "disabled" in your config for the time it takes you to refine your config during which it continues to run on your origin server.

There are other cases I've seen, such as two distinct frontends used for A/B testing. Enable one or the other depending on the application version, with different switching rules there.

Thus I'm convinced we cannot change this behavior without ruining plenty of users' experience and breaking their valid use cases.

I think that what you'd need instead would be to start with your backend enabled and the bind lines temporarily disabled. We could then possibly set them in the right state, but it would not work on all operating systems (disable/enable are OS-dependent). Do you think that having, say, "disabled" per bind line would suit your needs ? We'd then document the limits (e.g. that it might prevent from starting on some OSes if another process is already there, and that on other OSes it would even not be enabled at run time).

There is historically a confusing choice of words between "disabled" (as in the frontend config) and "disable" on the CLI, because at the beginning the CLI's "disable" was not supposed to be reversible and was the closest possible action to put a frontend in something equivalent to the "disabled" state. But it's definitely not the same thing as you noticed. We could possibly imagine a more general "start-disabled" option for a frontend, that would propagate to all bind lines, but I suspect that it would further complicate the already extremely complex bind mechanism and that it would not be bug-free anymore :-/

**Comment by domdom82** [comment] 2021-01-13 09:07
hi @wtarreau thanks for the clarification. Just for my understanding, by `"disabled" per bind line` you mean instead of this

```
listen health_check_http_url
  disabled
  bind :8080
  mode http
```

we could do this
```
listen health_check_http_url
  bind :8080   disabled
  mode http
```
?

so the frontend would actually be created and then there would be some API to enable just the port bind later?

**Comment by wtarreau** [comment] 2021-01-13 16:46
Yes, that was the idea. We can currently re-enable disabled listeners on some operating systems. We'd just start the socket in the same state (bound but not listening), so that via the CLI you could enable the frontend and it would automatically re-enable all of its listeners (and possibly later offer finer control, but at the moment we don't even know how to designate a bind line nor a listener from the CLI, which is the main limitation).

**Comment by domdom82** [comment] 2021-01-13 20:10
I see. Yes I think what you proposed would satisfy my requirement. My goal is to keep haproxy out of traffic until I have fully set the dynamic parts of the configuration (namely crt-list and certificates). So having a frontend that does not (yet) listen and can be turned on later would be fine.

**Comment by capflam** [comment] 2021-02-05 14:01
I'm closing this issue with the label "works as designed". Feel free to re-open it if I'm wrong.

**Closed as completed by capflam** 2021-02-05 14:01 UTC
Labels: type: bug, status: works as designed
