### ISSUE TITLE
2.2: UUID() fails to validate.

### ISSUE THREAD

**Issue by lseelenbinder** [haproxy/haproxy#763] opened 2020-07-18 09:54 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.0-1~bpo10+1 2020/07/15 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.0.html
Running on: Linux 5.4.10-x86_64-linode132 #1 SMP PREEMPT Thu Jan 9 21:17:12 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.2.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

Linux <hostname> 5.4.10-x86_64-linode132 #1 SMP PREEMPT Thu Jan 9 21:17:12 UTC 2020 x86_64 GNU/Linux
```

## What's the configuration?

```
…snip…
http-request set-header request-id %[uuid()]
…snip…
```

## Steps to reproduce the behavior

1. Use `uuid()` in a fetch.

## Actual behavior

Fails to validate the configuration.

## Expected behavior

Validates the configuration.

## Do you have any idea what may have caused this?

Change to how `uuid` is instantiated causing it to default to `uuid(0)` (which isn't a valid option) instead of `uuid(4)` by default.

## Do you have an idea how to solve the issue?

- Fix the docs
[or]
- Update the default

**Comment by capflam** [comment] 2020-07-20 09:52
A quick fix is to omit the parenthesis in this case. In the documentation we can read : 
```
  When all arguments are optional, the parenthesis may be omitted.
```

So it suggests it is allowed to use empty parenthesis. Unfortunately there is a bug with the first argument parsing when it is optional. When it is not passed, the argument type is set while it should not. So `smp_name()` is not equivalent to `smp_name`. Worse, some sample fetches behave differently.  For instance, `req.hdr()` works as expected while `req.hdr` fails (at runtime). It is the opposite for `uuid`.

Note that this is specific to the first argument. The other optional arguments, when not specified, are initialized with a special type (`ARGT_STOP`).

**Comment by lseelenbinder** [comment] 2020-07-20 12:53
> A quick fix is to omit the parenthesis in this case.

Ah! I didn't realize that. Thanks for the clarification and documentation link. I already quick fixed it by explicitly using `uuid(4)`, so I think I'll leave it as that for now.

**Comment by wtarreau** [comment] 2020-07-21 13:08
It is possible that I broke this when reworking the argument parser to better handle commas and quotes. I'll compare with 2.1.

**Comment by wtarreau** [comment] 2020-07-21 13:57
So I can confirm that I did break the argument parser for the exact case where there is one single optional argument! Now fixed, thanks Luke! I'm closing since it's already backported, but do not hesitate to reopen if needed!

**Closed as completed by wtarreau** 2020-07-21 13:57 UTC
Labels: type: bug, severity: medium, status: fixed
