### ISSUE TITLE
src/mux_h2.c: null pointer dereference suspected by coverity (new finding)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1086] opened 2021-01-29 08:06 UTC
```
5300        /* encode the method, which necessarily is the first one */
    CID 1445800 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)21. var_deref_op: Dereferencing null pointer sl.
5301        if (!hpack_encode_method(&outbuf, sl->info.req.meth, meth)) {
5302                if (b_space_wraps(mbuf))
5303                        goto realign_again;
5304                goto full;
5305        }
```

**Comment by capflam** [comment] 2021-01-29 08:54
The `sl` variable is always defined at this stage because `h2s_bck_make_req_headers()` is called on a HTX start-line block. So functionally speaking, we know the `sl` variable will be set. But by reading the function code, it is not obvious, especially because there are some checks on the `sl` variable. I guess, we can add some BUG_ON() and a comment to make things clear and remove unnecessary tests.

It is not a bug, but keep it open as a reminder. I'll try to address it soon.

**Comment by capflam** [comment] 2021-01-29 12:45
It should be fixed now.

**Closed as completed** 2021-02-01 10:34 UTC
Labels: status: fixed, type: code-report
