### ISSUE TITLE
cppcheck report, realloc bad usage

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1030] opened 2021-01-05 16:39 UTC
```
src/cfgparse.c:1986:5: error: Common realloc mistake: 'outline' nulled but not freed upon failure [memleakOnRealloc]
    outline = realloc(outline, outlinesize);
    ^

```

**Comment by wtarreau** [comment] 2021-01-06 10:46
Yeah indeed there are a few other occurrences of this common pattern along all the code base. It can be fixed by using a temporary variable for the result (the realloc API isn't great for this, but that's easy to criticize after it was designed). I'd argue this one is harmless since it's during the boot and it will quit if it fails. I don't know for the few other ones, we must at least make sure none of them does it at run time.

**Comment by capflam** [comment] 2021-01-06 11:03
using `my_realloc2` should do the trick in all cases I guess. Except if there is a good reason to not do so. I didn't checked.

**Comment by wtarreau** [comment] 2021-01-06 11:05
Ah excellent, I didn't remember about this one, seems like it was created exactly for this problem already :-)

**Closed as completed** 2021-01-10 15:26 UTC
Labels: status: fixed, type: code-report
