### ISSUE TITLE
haproxy 2.2.3 producing status 204

### ISSUE THREAD

**Issue by appsolute-alex** [haproxy/haproxy#852] opened 2020-09-11 10:25 UTC
## Detailed description of the problem

Since version 2.2.3 haproxy produces sporadically a 204 or terminates the connection. This is undepended of backends. This issue appears for all backends.

## Expected behavior

If the backend is sending correct response haproxy should not terminate connection or send back a 204. In this case I would expect to receive a 302 instead of the 204.

## Steps to reproduce the behavior

Bash command ```for ((i=1;i<=6;i++)); do curl -I -o /tmp/o https://HOST 2&> /dev/null | cat /tmp/o | grep "HTTP/2" && sleep 10; done``` produced the following output:

```
HTTP/2 302
HTTP/2 204
HTTP/2 302
HTTP/2 204
HTTP/2 204
HTTP/2 204
```

## Do you have any idea what may have caused this?

Maybe it's about SNI and SSL termination, but I was not able to dig deeper into it.

## Do you have an idea how to solve the issue?

No, I was able to solve it by going back to 2.2.2

## What is your configuration?

```
global
  log 127.0.0.1:514 len 4096 local0 info
  log 127.0.0.1:514 len 4096 local2 notice
  log 127.0.0.1:514 len 4096 local3
  pidfile /run/haproxy.pid
  daemon

  ca-base /etc/ssl/certs
  crt-base /etc/ssl/private

  ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11
  ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:TLS13-CHACHA20-POLY1305-SHA256:EECDH+AESGCM:EECDH+CHACHA20:!ECDHE-RSA-DES-CBC3-SHA:!ECDHE-RSA-AES256-SHA384:!ECDHE-RSA-AES256-SHA:!DHE-RSA-AES256-SHA256:!ECDHE-RSA-AES128-SHA256:!ECDHE-RSA-AES128-SHA:!DHE-RSA-AES128-SHA256:!DHE-RSA-AES128-SHA:!DHE-RSA-AES256-SHA:!AES256-GCM-SHA384:!AES128-GCM-SHA256:!AES256-SHA256:!AES128-SHA256:!AES256-SHA:!AES128-SHA:!aNULL:!MD5:!DSS:!AESCCM
  ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11
  ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:TLS13-CHACHA20-POLY1305-SHA256:EECDH+AESGCM:EECDH+CHACHA20:!ECDHE-RSA-DES-CBC3-SHA:!ECDHE-RSA-AES256-SHA384:!ECDHE-RSA-AES256-SHA:!DHE-RSA-AES256-SHA256:!ECDHE-RSA-AES128-SHA256:!ECDHE-RSA-AES128-SHA:!DHE-RSA-AES128-SHA256:!DHE-RSA-AES128-SHA:!DHE-RSA-AES256-SHA:!AES256-GCM-SHA384:!AES128-GCM-SHA256:!AES256-SHA256:!AES128-SHA256:!AES256-SHA:!AES128-SHA:!aNULL:!MD5:!DSS:!AESCCM
  maxconn 8192
  tune.ssl.default-dh-param 2048
  tune.h2.initial-window-size 1048576
  stats socket /tmp/haproxysock level admin

defaults
  log global
  mode http
  option httplog
  option http-server-close
  timeout http-request 30s
  timeout connect 10s
  timeout check 10s
  timeout client 30s
  timeout server 30s
  option httpclose
  errorfile 400 /usr/local/etc/haproxy/errors/400.http
  errorfile 403 /usr/local/etc/haproxy/errors/403.http
  errorfile 408 /usr/local/etc/haproxy/errors/408.http
  errorfile 500 /usr/local/etc/haproxy/errors/500.http
  errorfile 502 /usr/local/etc/haproxy/errors/502.http
  errorfile 503 /usr/local/etc/haproxy/errors/503.http
  errorfile 504 /usr/local/etc/haproxy/errors/504.http
```

## Output of `haproxy -vv` and `uname -a`

Sorry, I need to avoid it right now, because I have no container any more running with 2.2.3, but normally I`m using the official haproxy:latest image from docker hub.

## Additional information (if helpful)

Nothing special. No unusual workload, no limits reached

**Comment by TimWolla** [comment] 2020-09-11 10:42
> Sorry, I need to avoid it right now, because I have no container any more running with 2.2.3, but normally I`m using the official haproxy:latest image from docker hub.

That would be the following then (except for kernel):

```
$ docker run -it --rm haproxy haproxy -vv
Unable to find image 'haproxy:latest' locally
latest: Pulling from library/haproxy
d121f8d1c412: Pull complete 
1cae796857a0: Pull complete 
718fed174203: Pull complete 
Digest: sha256:a24b18b09c223e606fe170ac83916f6cfb707d2c97db4b9eb8aa9eaab3649acb
Status: Downloaded newer image for haproxy:latest
HA-Proxy version 2.2.3-0e58a34 2020/09/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.3.html
Running on: Linux 4.4.0-189-generic #219-Ubuntu SMP Tue Aug 11 12:26:50 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

**Comment by capflam** [comment] 2020-09-11 12:24
It could also be useful to have your frontend/backend configuration. At first glance, I don't see how it is possible. If your webserver returns a valid response, HAProxy will not alter the status code.  Did you experienced this bug in HTTP/2 only, or it also happens with HTTP/1 requests ? If you can reproduce it a preprod/dev environment, it could be useful to enable mux traces using `trace` CLI command : 

```
socat  /tmp/haproxysock readline
trace h2 sink buf0; trace h2 level developer; trace h2 verbosity complete; trace h2 start now; show events buf0 -w 
```
(To enable H1 traces, just replace h2 by h1. Both may be enabled in same time)

With these traces, you will have details of what is received and sent by multiplexers on the client and server side. Be careful, it is pretty verbose.

**Comment by capflam** [comment] 2020-09-18 12:43
A gentle ping. Any news ?

**Comment by appsolute-alex** [comment] 2020-09-19 05:28
> A gentle ping. Any news ?

Hey Christopher, thanks a lot. We created a ticket to work on that topic. So I assume that we maybe should be able to deliver further (debug) informations within approximately next week when my collegue will work on that topic.

It's a tough topic and of course we like to support for finding the issue. So please give us some more days working on that. Thanks for your understanding.

**Comment by capflam** [comment] 2020-09-21 07:58
No problem. Thanks for the feedback.

**Comment by wibbly13** [comment] 2020-09-28 11:51
Hi @capflam 

I'm @appsolute-alex colleague. I have done several tests on the issue, I will describe the tests and results below:

- The tests are done using docker containers of the `latest` tag (running v2.2.3) and the `2.2.2` tag.
- Status 204 is being generated by our HaProxy configuration, therefore that is not the actual issue. The actual issues seems to be on the processing in the `acl` we are using. I've described this further below.
- The issue happens when using https with HTTP/2

**HaProxy Configuration**
```
  frontend fe_cockpit_204_debugging
  bind *:443 ssl crt /certs/bundle_with_key.pem alpn h2,http/1.1
  mode tcp
  option tcpka
  option tcplog
  stick-table type ip size 100k expire 30s store conn_cur
  tcp-request inspect-delay 2s
  tcp-request content accept if { req_ssl_hello_type 1 }
  capture request header origin len 128
  compression algo gzip
  compression type text/css text/html text/javascript application/javascript text/plain text/xml application/json

  ### Test1 Configuration ###
  # acl is_options method OPTIONS AND hdr_sub(host) -i api
  # use_backend bk_cors if is_options

  ### Test2 Configuration ###
  acl is_options method OPTIONS
  acl is_options_2 hdr_sub(host) -i api
  use_backend bk_cors if is_options is_options_2
  

  ### This has to be after the above acl declarations ###
  use_backend bk_xxx if { hdr(host) -i xxx.my-appsolute-mobility.com }
  default_backend bk_cockpit_204_debugging
```

**Note:** `bk_cors` is what ends up returning a 204 in our configuration.

I've come to understand the following from the above configuration:
- The `acl` statement doesn't support multiple criteria both in `v2.2.3` and `v.2.2.2`. Therefore,  in `acl is_options method OPTIONS AND hdr_sub(host) -i api` only the first criteria `OPTIONS` is considered. Also, HaProxy doesn't throw an error when it encounters this kind of `acl` statement during start-up.

**I've come across 2 issues:**
1. In `v2.2.3`, a GET request is sometimes processed as an OPTIONS request. This leads to `bk_cors` being selected as opposed to `bk_xxx`. I tested this using `Test1 Configuration` (see configuration above). When I changed to `Test2 Configuration` this issue went away. I ran the test by running a continuous loop that did a GET request to `xxx.my-appsolute-mobility.com`. Sometimes `bk_cors` could be called and sometimes `bk_xxx` could be called.
2. In `v2.2.3`, `is_options_2` is not being handled. Therefore if the host is e.g. `api.my-appsolute-mobility.com` and an OPTIONS request is done, `bk_cors` will not be selected. I then deployed `v2.2.2` and thereafter `bk_cors` was being selected correctly as it should.

**My 2 cents**
I wonder if the general issue is with the methods used in `acl` criteria such as `hdr_sub` and `method`. The above 2 issues I've come across center on the use of these methods. Now, in the first issue I described above, I mentioned that, _"a GET request is sometimes processed as an OPTIONS request"_, perhaps the problem is actually with `method OPTIONS` criteria in the `acl` statement, which ends up sometimes accepting a GET. Also, in the same first issue I described above, I mentioned that changing to `Test2 Configuration` fixed the problem i.e. `bk_cors` was not being called when a GET request is done. Perhaps what happened is that since `is_options_2` is always false even when `api.my-appsolute-mobility.com` is used, then `bk_cors` will never be called, even when `method OPTIONS` mistakenly accepts a GET request. Therefore, when doing the test in `2.2.3` it seems there is no issue, but actually, the second issue I described above is masking the first issue .

**Comment by capflam** [comment] 2020-09-28 13:40
Well, there are 3 configuration issues here.

* Your `tcp-request` rule is useless because `req_ssl_hello_type` must be used on raw content and not on deciphered content. To convince you, change it this way to reject all your incoming connections (including SSL ones) : 
  ```
  tcp-request content reject if ! { req_ssl_hello_type 1 }
  ```

* You cannot add several conditions in the same ACL. You must use rules with several ACLs instead. Read [Using ACLs and fetching samples](https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#7) for details, especially §7.1 and §7.2. Thus each part after the `method` keyword of your ACL `is_options` (the first one, from Test1) is interpreted as a pattern.

* The ACLs from the Test2 is the right way to do. But, because you are using a TCP frontend, you must wait the request content. Otherwise, there is no warranty you have a well formed request when the http-request ruleset is executed. Use the following tcp-request rule to do so :
  ```
  tcp-request inspect-delay 2s
  tcp-request content accept if HTTP ## (or reject if ! HTTP)
  ```
  Be sure the delay is set to the proper value. 2 seconds seem reasonable though.

Now, this will work for HTTP/1.X requests, but not for HTTP/2 ones. Because the parsing performed on raw content is unable to parse HTTP/2 messages. The easiest would be to use an HTTP frontend instead.

Note that I fixed a bug that may explain your matching issue on the request method. See d2414a23c. The fix was backported to 2.2 but it is not part of the 2.2.3. It will be packaged with the next 2.2 release.

**Comment by wibbly13** [comment] 2020-09-29 03:32
Thanks @capflam 

I'm I correct in thinking that the following rules will not be necessary if the frontend **mode** is `http`? 
```
tcp-request inspect-delay 2s
tcp-request content accept if HTTP ## (or reject if ! HTTP)
```

**Comment by capflam** [comment] 2020-09-29 07:30
Yes, it is useless. It is just an old trick for TCP frontends, to be sure to wait for the HTTP request before executing any http sample fetches. It may be useful if you want to handle different protocols through the same frontend. If your frontend only handles http traffic, there is no reason to not use the http mode.

**Comment by wibbly13** [comment] 2020-09-29 09:52
I've made changes to our HaProxy configuration according to [this](https://github.com/haproxy/haproxy/issues/852#issuecomment-700405040) and the preliminary tests show that the `haproxy:latest` (v2.2.3) is working as expected.

**Comment by capflam** [comment] 2020-09-29 09:58
Nice ! Because it seems to be a configuration problem, I'm closing this issue, tagging it as invalid. But, feel free to reopen it if I'm wrong.

**Closed as completed** 2020-09-29 09:58 UTC
Labels: type: bug, status: invalid
