### ISSUE TITLE
2.2.5, 2.3 HAproxy does not handle huge CA lists correctly

### ISSUE THREAD

**Issue by domdom82** [haproxy/haproxy#1011] opened 2020-12-17 11:19 UTC
## Detailed description of the problem

This is an edge case of TLS client authentication.
We've noticed that when HAproxy is configured with a CA list whose distinguished names combined exceed the 64K as defined in https://tools.ietf.org/html/rfc5246#section-7.4.4 HAproxy does only handle the too large list correctly.

HAproxy still sends the entire list, but the SSL handshake always fails. For example OpenSSL will report this error:
```
verify return:1
4540653228:error:1400A098:SSL routines:CONNECT_CR_CERT_REQ:excessive message size:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.2/libressl-2.8/ssl/ssl_both.c:524:
``` 

HAproxy will log simply:
```
SSL handshake failure
```

## Expected behavior

HAproxy should throw an alert and not load the CA list.

## Steps to reproduce the behavior

1. Construct a CA list pem file with a large number of CAs. (I've used 10000) 
2. Add a crt-list entry or normal ca-list entry to a bind config that uses the large CA list
3. Try a TLS handshake, e.g. using OpenSSL

## Do you have any idea what may have caused this?

Yes. The CA list is non RFC 5246 compliant.

## Do you have an idea how to solve the issue?

Yes. HAproxy should reject non-compliant CA lists.

## What is your configuration?

```
global
  log /dev/log len 4096 format rfc3164 syslog info
  stats socket /var/run/haproxy.sock mode 600 expose-fd listeners level admin

defaults
  log global
	mode http
  timeout connect 5s
  timeout client 5s
  timeout server 5s

frontend myfrontend
  bind :443 ssl crt /etc/cert/server.pem crt-list /crt-list
  log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslc %sslv"
  default_backend httpstatus

  capture request header Host len 256
  capture request header User-agent len 256

  http-request set-header Host httpstat.us

backend httpstatus
	server httpstatus httpstat.us:80
```

crt-list
```
/etc/cert/server.pem [ca-file /allCerts.pem verify optional] crt-test-bad.localhost.io
```
(allCerts.pem contains 10000 generated CA certificates)

## Output of `haproxy -vv` and `uname -a`

```
Linux 3f3199783f72 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux

HA-Proxy version 2.3.2-d522db7 2020/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.2.html
Running on: Linux 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```

## If HAProxy crashed: Last outputs and backtraces

```
no crashes
```

## Additional information (if helpful)

tested on both 2.2.5 and 2.3

**Comment by wlallemand** [comment] 2021-01-12 11:33
Thanks for the report, I'm reproducing the issue as far as 1.8. I'm looking for the problem.

**Comment by wlallemand** [comment] 2021-01-15 17:28
I'm really not sure how to fix this, I'm not even sure I'm reproducing the same problem in fact.
My OpenSSL version is not exactly the same (1.1.1i), so maybe your problem was fixed in OpenSSL.

After generating a large number of CAs, I reproduce a failure with 476 CAs, however the `openssl s_client` command didn't return the same error, in fact HAProxy does not sends the CA names once reached this number of CAs, so the client simply fail because there are no CA names.

Looking at the code, we are using the `SSL_CTX_set_client_CA_list()` function, which does not return any error when it fails. I tried to bypass the problem by checking is the CA list is right with `
SSL_CTX_get_client_CA_list()` but it does not return any error either.

Then I reworked this whole thing to return a STACK_OF(X509) * instead of a X509_STORE in order to apply individually each X509 * with `SSL_CTX_add_client_CA()` because this function actually return errors! But... no error appeared. I really feel like I'm missing something here.

**Comment by domdom82** [comment] 2021-01-18 15:50
I am pretty sure it is related to the combined size of all CA names. I have found a tipping point of 1480 CAs. Each have the following form of the DN:
```
/CN=Name_1234/O=ABC/C=DE
```

Each DN notation has exactly 25 bytes. So multiplying that with 1480 gives me 37000 bytes. 

Trying 1481 CAs (which equals 37025 bytes) no longer works. So I am pretty sure the limit is around the 37k area. 
This is somewhat disappointing as I expected it to be more close to the 65535 as per the RFC. My guess is that OpenSSL itself has either deviated from the RFC or needs the space for something else.

Regarding HAproxy I was hoping there was a way to ask OpenSSL before loading the CA file. Otherwise we would have to read the CA list manually and check the combined size of the CA DNs.

**Comment by domdom82** [comment] 2021-01-18 15:54
https://github.com/openssl/openssl/issues/4819 may be related

**Comment by wlallemand** [comment] 2021-01-18 20:53
Unfortunately there is no way to check this with OpenSSL, or we will need to do an arbitrary computation which will depends of the OpenSSL implementation... Which is ugly. You can still bypass the problem by using the [no-ca-names](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#no-ca-names) option, but it looks like there is no clean way to detect the problem.

**Comment by domdom82** [comment] 2021-01-19 08:23
What is weird that OpenSSL does send an error (SSL alert number 80 == internal error) during the server hello message in the TLS handshake. So there must be logic that checks the size, even though it does not return an error to HAproxy. I'm not familiar with the code base unfortunately so I don't know where to look. Can you tell me how / where HAproxy calls into OpenSSL?

**Comment by wlallemand** [comment] 2021-01-19 11:32
Right, but it's an error generated during the handshake, not during the configuration of the SSL_CTX so it can't fail at startup.

And we are currently limited by HAProxy for handshake errors, it can only output "SSL hanshake failure" if a handshake fails. Look for "CO_ER_SSL_HANDSHAKE" in src/ssl_sock.c, this is the error code which define this error.

**Comment by wtarreau** [comment] 2021-01-20 10:58
Note that the largest list you can send is probably around 65535 (more or less whatever fatty chunks needed around) given that most TLS fields lengths are encoded on uint16. At 1480 entries, this gives 44 bytes per entry max. If you're using 25 chars per name, this leaves 19 bytes of encoding per record, which doesn't seem excessive. Thus it's very possible that you've hit a hard limit imposed by the protocol. This would indicate that a total size of 65120 is OK but 65164 is not.

With that said, I agree that the error should be cleanly reported, if possible at all, of course.

**Comment by buchmui** [comment] 2021-04-28 15:16
Same error here.

Default debian 10 install

```
HA-Proxy version 2.2.8-1~bpo10+1 2021/01/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.8.html
Running on: Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-Dyw9cm/haproxy-2.2.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```
openssl:
```
openssl                        1.1.1d-0+deb10u6
```
The startup of the haproxy process does not fail. only ``openssl s_client -connect server:port`` or an nmap cipher scan would indicate, that the haproxy process is not able to serve the chain. In my opinion the process must fail to start or an config check should print out a warning. Only the ansible module is giving a reference to the error ``unable to load chain certificate into SSL Context`` which is is handled by https://fossies.org/linux/haproxy/src/ssl_sock.c#3086 AFAIK. This error message makes no sense for us, due to the fact 1.1.1d-0+deb10u6 is installed. 

The only workaround is, to save only the server cert + ca1 + ca2 + key in the pem file (without the root certificates). 
 We must  serve  the complete chain.   @wlallemand  do you know if there is any progress into this?

Thank you

**Comment by wlallemand** [comment] 2021-04-28 15:38
There is unfortunately no clean way to detect this, because OpenSSL does not return an error. You can bypass the issue by using "no-ca-names"

**Comment by wlallemand** [comment] 2021-04-28 15:54
Also, I'm confused about the error you are linking, this bug report is about the ca-file directive, not the crt one.

**Comment by buchmui** [comment] 2021-07-21 04:24
@wlallemand ,
we have fixed the problem for us by storing a shorter certificate chain in the file.
However. Thanks for the feedback! It has helped us a lot.

**Comment by wtarreau** [comment] 2022-04-14 18:24
What is the status of this issue ? I'm fine with a "works as designed" or anything else, but if everyone's happy there's no reason to keep it open.

**Comment by domdom82** [comment] 2022-04-17 17:49
Seems hard to fix and was only an edge-case anyway. I am OK with closing for now until it causes more trouble or is easier to fix.

**Comment by wtarreau** [comment] 2022-04-20 05:56
OK thank you Dominik. I'll mark it as "future fix" and close, so that we remember that there might still be something to look around there. Newer versions use a completely revamped cert storage, maybe it's not affected anymore, but I do not know, to be honest. Do not hesitate to open a new one linking to this one if you face the problem again when upgrading in the future.

**Closed as completed by wtarreau** 2022-04-20 05:56 UTC
Labels: type: bug, status: future fix

**Comment by wlallemand** [comment] 2022-04-20 07:50
It's a limitation of the SSL library, we can't do much about it right now.

**Comment by lukenowak** [comment] 2023-04-05 15:06
FYI I was hit by this issue with haproxy, `-vv` gives:

```
HAProxy version 2.6.9-3a3700a 2023/02/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.9.html
Running on: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :                                                            
  TARGET  = linux-glibc                                                    
  CPU     = generic                                                        
  CC      = cc                      
  CFLAGS  = -m64 -march=x86-64 -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-o
verflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clo
bbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_DL=1 USE_QUIC=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS                         
                                                                           
Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT
 +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCT
L -PROMEX +QUIC +RT -SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB
                                                                           
Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=40).
Built with OpenSSL version : OpenSSL 3.0.8+quic 7 Feb 2023
Running on OpenSSL version : OpenSSL 3.0.8+quic 7 Feb 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.3                                         
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with zlib version : 1.2.12
Running on zlib version : 1.2.12
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

I have side-by-side binary (no QUIC), it works fine:

```
HAProxy version 2.6.9-3a3700a 2023/02/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.9.html
Running on: Linux 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
Build options :                                                            
  TARGET  = linux-glibc                                                    
  CPU     = generic                 
  CC      = cc
  CFLAGS  = -m64 -march=x86-64 -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-o
verflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clo
bbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_DL=1      
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS         
                                                                           
Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT
 +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCT
L -PROMEX -QUIC +RT -SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB
                                     
Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
                                     
Built with multi-threading support (MAX_THREADS=64, default=40).
Built with OpenSSL version : OpenSSL 1.1.1t  7 Feb 2023
Running on OpenSSL version : OpenSSL 1.1.1t  7 Feb 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.3
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with zlib version : 1.2.12
Running on zlib version : 1.2.12
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

So

> Newer versions use a completely revamped cert storage, maybe it's not affected anymore, but I do not know, to be honest. 

Seems not enough in this case.

I am happy to coordinate on fixing/providing workarounds for such issue...

...in the same time, I'd prefer haproxy to being able to start and emit warnings and do not support such configuration, instead of not being able to start at all (I have >500 in this case and in other cases >few-k for crt-list).
