### ISSUE TITLE
src/proto_tcp.c: coverity suspect negative argument passed to "close"

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#499] opened 2020-02-12 06:44 UTC
this is really nice

```
747                        ha_warning("Failed to create a temporary socket!\n");
748                else {
749                        if (getsockopt(fd, IPPROTO_TCP, TCP_MAXSEG, &default_tcp_maxseg,
750                            &ready_len) == -1)
751                                ha_warning("Failed to get the default value of TCP_MAXSEG\n");
752                }
   CID 1403827 (#1 of 1): Argument cannot be negative (NEGATIVE_RETURNS)6. negative_returns: fd is passed to a parameter that cannot be negative.
753                close(fd);
754        }
```

**Comment by wdauchy** [comment] 2020-02-12 08:56
I will handle this one

**Comment by wtarreau** [comment] 2020-02-12 10:16
Amusing. The bug is harmless, however in case of error there, a value of -2 is assigned and used as-is later without checking :-/   I'm going to clean this mess up. Thanks Ilya!

**Comment by wdauchy** [comment] 2020-02-12 10:36
@wtarreau oh you mean there is more than what I sent in my patch?

**Comment by wtarreau** [comment] 2020-02-12 11:03
Ah I don't know, I hadn't seen your response. That's the beauty of web-based interfaces... You get hundreds of tabs pre-loaded and when you respond they're already old :-)

OK now I can see it. Your fix is indeed right, I'll take it as-is. The second part of the problem is that the defaultmss value set to -2 is used inconditionally everywhere. It should be checked for >0 before being used. Feel free to propose one patch for this as well, I'll take it.

**Comment by wdauchy** [comment] 2020-02-12 11:11
indeed, thanks, I will work on defaultmss patch as well.

**Comment by wtarreau** [comment] 2020-02-12 15:15
now backported everywhere, closing.

**Closed as completed by wtarreau** 2020-02-12 15:15 UTC
Labels: type: bug, severity: minor, status: fixed
