### ISSUE TITLE
certificate and private key in separate files not supported for backend server entries

### ISSUE THREAD

**Issue by smh** [haproxy/haproxy#848] opened 2020-09-08 11:03 UTC
## Detailed description of the problem

We want to keep the certificate and private keys separate. For `bind` this works fine:
```
bind *:8443 ca-file /Users/smh/src/haproxy-ssl-split-key/certs/ssl-root-ca.pem ssl crt /Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem verify none
```
haproxy will find the private key in the file called `/Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem.key` if the private key is not included in the `crt` file.

For `server` the same does not work:
```
server backend1 localhost:8444 ssl verify none ca-file /certs/ssl-root-ca.pem crt /certs/ssl-cert.pem check no-check-ssl inter 2m downinter 2m observe layer4 error-limit 10 on-error mark-down check port 8444
```

haproxy will complain with the following message:
```
[ALERT] 250/120807 (65226) : config : backend 'ssl-backend', server 'backend1': unable to load SSL private key from PEM file '/Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem'.
[ALERT] 250/120807 (65226) : Fatal errors found in configuration.
```

Please see https://github.com/smh/haproxy-ssl-split-key for a simple setup that reproduces the problem.

## Expected behavior

I would expect the `crt` loading of certificates from files to behave the same both on `bind` and `server`, and that there is no error starting haproxy. The documentation does not seem to differentiate the `crt` keyword in the context of `bind` or `server`.

## Steps to reproduce the behavior

1. `git clone https://github.com/smh/haproxy-ssl-split-key.git`
2. `./run.sh`
3. haproxy fails to run

## Do you have any idea what may have caused this?

This is related to #221 that makes it possible to load private key and certificate separate files in the first place.
 
## What is your configuration?

```
❯ haproxy -vv
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = clang
  CFLAGS  =
  OPTIONS = USE_KQUEUE=1 USE_PCRE=1 USE_POLL=1 USE_THREAD=1 USE_OPENSSL=1 USE_ZLIB=1

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL -LUA -FUTEX -ACCEPT4 +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with clang compiler version 11.0.3 (clang-1103.0.32.62)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
❯ uname -a
Darwin Steins-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

imeouts are set to a non-zero value: 'client', 'connect', 'server'.
[NOTICE] 251/125312 (40913) : haproxy version is 2.2.2
[ALERT] 251/125312 (40913) : config : backend 'ssl-backend', server 'backend1': unable to load SSL private key from PEM file '/Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem'.
[ALERT] 251/125312 (40913) : Fatal errors found in configuration.

   | While not properly invalid, you will certainly encounter various problems
   | with such a configuration. To fix this, please ensure that all following
   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
[NOTICE] 251/125524 (41890) : haproxy version is 2.2.2
[ALERT] 251/125524 (41890) : config : backend 'ssl-backend', server 'backend1': unable to load SSL private key from PEM file '/Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem'.
[ALERT] 251/125524 (41890) : Fatal errors found in configuration.

[NOTICE] 251/125524 (41890) : haproxy version is 2.2.2
[ALERT] 251/125524 (41890) : config : backend 'ssl-backend', server 'backend1': unable to load SSL private key from PEM file '/Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem'.
[ALERT] 251/125524 (41890) : Fatal errors found in configuration.

global

defaults
    mode http
    timeout connect         10s
    timeout client          30s
    timeout server          90s

frontend frontend-ssl
    bind *:8443 ca-file /Users/smh/src/haproxy-ssl-split-key/certs/ssl-root-ca.pem ssl crt /Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem verify none
    use_backend ssl-backend

backend ssl-backend
    # unable to load key by looking for file named basename.key
    server backend1 localhost:8444 ssl verify none ca-file /Users/smh/src/haproxy-ssl-split-key/certs/ssl-root-ca.pem crt /Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem check no-check-ssl inter 2m downinter 2m observe layer4 error-limit 10 on-error mark-down check port 8444

    # the following works as the crt file includes the private key
    #server backend1 localhost:8444 ssl verify none ca-file /Users/smh/src/haproxy-ssl-split-key/certs/ssl-root-ca.pem crt /Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert-with-key.pem check no-check-ssl inter 2m downinter 2m observe layer4 error-limit 10 on-error mark-down check port 8444
```

## Output of `haproxy -vv` and `uname -a`

```
❯ haproxy -vv
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Darwin 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = clang
  CFLAGS  =
  OPTIONS = USE_KQUEUE=1 USE_PCRE=1 USE_POLL=1 USE_THREAD=1 USE_OPENSSL=1 USE_ZLIB=1

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE -LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL -LUA -FUTEX -ACCEPT4 +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with clang compiler version 11.0.3 (clang-1103.0.32.62)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

```
❯ uname -a
Darwin Steins-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

## If HAProxy crashed: Last outputs and backtraces

```
[NOTICE] 251/125524 (41890) : haproxy version is 2.2.2
[ALERT] 251/125524 (41890) : config : backend 'ssl-backend', server 'backend1': unable to load SSL private key from PEM file '/Users/smh/src/haproxy-ssl-split-key/certs/ssl-cert.pem'.
[ALERT] 251/125524 (41890) : Fatal errors found in configuration.
```

**Comment by TimWolla** [comment] 2020-09-08 11:06
Duplicate of #845

**Comment by smh** [comment] 2020-09-08 11:12
Thanks, I didn't see that one

**Comment by jmagnin** [comment] 2020-09-08 11:30
the configuration manual has an entry for both crt as a [bind](https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#crt%20(Bind%20options)) or [server]( https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#crt%20(Server%20and%20default-server%20options)) option. The latter does not hint at support for separate key file.

**Closed as completed** 2020-09-14 09:36 UTC
Labels: type: bug, status: duplicate
