### ISSUE TITLE
HTTP/2 flow control: window size increment exceeds max

### ISSUE THREAD

**Issue by uinseann241** [haproxy/haproxy#2719] opened 2024-09-17 08:44 UTC
### Detailed Description of the Problem

While using HAProxy to proxy HTTP/2 to a backend server we've observed that Haproxy exceeds the max allowed flow control window size if _tune.h2.initial-window-size_ is omitted from the haproxy.cfg file(not set).

Flow:
Haproxy sends SETTINGS frame with an initial window size of 65,536 to the backend server (Note: 1 greater than default 65535)
The server sends a data frame which is 482 in length. The windows is now 65,536 – 482 = 65,054
Haproxy sends a WINDOW_UPDATE on stream 0 with a window size increment of 2,147,418,594. 
2,147,418,594 + 65,054 is 2,147,483,648 which exceeds the max allowed of 2,147,483,647 by 1. 
The server detects the error and sends a GOAWAY frame to initiate termination of the TCP connection.

### Expected Behavior

Windows size increment from Haprocy does not exceed the max allowed flow control window size.

### Steps to Reproduce the Behavior

Setup haproxy to loadbalance to http/2 backend.
Do not specify an initial-window-size in haproxy.cfg
Send GET request to backend server.

### Do you have any idea what may have caused this?

Looks like an incorrect initial window size

### Do you have an idea how to solve the issue?

A work-around for this issue is to manually set tune.h2.initial-window-size to 65535 in haproxy config.  
With this setting haproxy does not set an initial window size and does not exceed the maximum allowed flow control window size.

### What is your configuration?

```haproxy
global
    log         /dev/log local0
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     10000
    user        haproxy
    group       haproxy
    daemon

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option                  http-keep-alive
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    http-reuse              safe
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 1000

frontend app_frontend
    mode  http           
    bind  *:8890 proto h2   
    default_backend  app_backend

backend app_backend
    mode  http
    balance  roundrobin
    server udr1 server1:8444 ssl verify none alpn h2 check
    server udr2 server2:8544 ssl verify none alpn h2 check
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.9-ad75c48 2024/06/14 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.9.html
Running on: Linux 4.18.0-553.8.1.el8_10.x86_64 #1 SMP Fri Jun 14 03:19:37 EDT 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_QUIC=1 USE_PCRE2=1 USE_QUIC_OPENSSL_COMPAT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION +QUIC +QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-22)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wtarreau** [comment] 2024-09-17 13:46
Hi!

Good catch, and kudos for the accurate analysis! I understand why it is happening. There was a discussion a few years ago on regarding the fact that the size of 65535 was extremely inefficient and causing single-byte window size increase for some clients, or maybe one-byte transfers only if I remember correctly. Then the participants togerther agreed to adjust their respective implementations and haproxy received such a fix as well: 0012f899dd ("OPTIM: mux-h2: increase h2_settings_initial_window_size default to 64k"). The discussion started there: https://github.com/nghttp2/nghttp2/issues/1722 and there's also the haproxy discussion here: https://www.mail-archive.com/haproxy@formilux.org/msg42418.html

The problem is stupid, it's just that this commit changed the initial window but not the increment, which remained this one, which perfectly explains your observation:

  #define H2_INITIAL_WINDOW_INCREMENT ((1U<<31)-1 - 65535)

The approach above remains wrong once it's possible to configure the initial window size, because instead it should advertise the maximum value minus what had already been advertised!

I'm going to check what it implies to do that. Hopefully it's simple enough for a quick fix...

**Comment by wtarreau** [comment] 2024-09-17 15:02
I'm sorry but now I'm confused by the report and can't wrap my head around it when running tests. It seems to me that two notions are conflated here:

- the STREAM window size, which is advertised in SETTINGS as SETTINGS_INITIAL_WINDOW_SIZE and which is indeed 65536 and defined using the `tune.h2.initial-window-size` config setting
- the CONNECTION window size, which starts at the protocol-defined 65535 (hard-coded) and to which is added the increment mentioned above, so that the max window size cannot exceed 2^31-1.

And given that the two are completely independent, I can't figure how it's possible that one impacts the other. Because in my tests these are never possible:

- connection window size starts at 65535 (non-negotiable)
- window_update adds 2^31-1-65535 to it => new value = 2^31-1

Are you sure that your server was not patched with the patch mentioned above but accidentally received the fix to affect the default **connection** window size at the same time ? Because the default connection size is **not** advertised in settings, it's only augmented using WINDOW_UPDATES, so by definition we can't set it to 65536, it's the receiver that fixes it for itself.

**Comment by uinseann241** [comment] 2024-09-18 08:15
Thanks for the updates.

No, haproxy has not been patched with any fix.  We're running version 2.9.9-ad75c48.

> the CONNECTION window size, which starts at the protocol-defined 65535 (hard-coded) and to which is added the increment mentioned above, so that the max window size cannot exceed 2^31-1.

We are seeing the CONNECTION window size set to 65536

I'm attaching what we are seeing on the wire between haproxy and the backend server
[http-flow.txt](https://github.com/user-attachments/files/17040622/http-flow.txt)

If our interpretation is correct we see:
frame (1):  haproxy sends SETTINGS[0] to set the CONNECTION initial window size to 65536
frame (5):  server sends 482 bytes (server decrements CONNECTION window size to 65,536 – 482 = 65,054)
frame (6):  haproxy sends WINDOWS_UPDATE[0] to increment CONNECTION window size by 2147418594.

2147418594  + 65,054 = 2^31

**Comment by wtarreau** [comment] 2024-09-18 09:20
Thanks for the capture, that's much clearer this way. There's a confusion in the analysis since the INITIAL_WINDOW_SIZE is not for the connection flow control but for stream flow control: it's the initial window that each stream will use: https://datatracker.ietf.org/doc/html/rfc9113#name-defined-settings

- **SETTINGS_INITIAL_WINDOW_SIZE** (0x04): This setting indicates the
   sender's initial window size (in units of octets) for **stream-level**
   flow control. The initial value is 2^16-1 (65,535) octets.

The connection's window size starts at 65535 (as per the protocol specification) and is exclusively incremented using WINDOW_UPDATE frames: https://datatracker.ietf.org/doc/html/rfc9113#section-6.9.2
- When an HTTP/2 connection is first established, new streams are
  created with an initial flow-control window size of 65,535 octets.
  The connection flow-control window is also 65,535 octets. Both
  endpoints can adjust the initial window size for **new streams** by
  including a value for **SETTINGS_INITIAL_WINDOW_SIZE** in the SETTINGS
  frame. The **connection** flow-control window can only be changed using
  **WINDOW_UPDATE** frames.

So in your trace, the server starts with a connection flow control of 65535 as per the spec, sends 482 bytes, it keeps 65053, and when the connection window is increased by 2147418594, it reaches 2^31-1.

The simple fact that you said that changing the initial setting to 65535 in the config fixes the problem really makes me think there's something odd with the way the server considers the initial value. Since the large increment in the WINDOW_UPDATE is only on the connection, it's certain that the server is upset about the connection's flow control length. But since it depends on the configured initial value, it means that at some point it combines them together, which it must not.

I don't know what server it is, but I think that with this trace, and an equivalent one taken with a initial stream window set to 65535 showing there is no problem anymore, the developers of the server will quickly understand the problem and spot the mistake. I really suspect that when dealing with the setting from the SETTINGS frame, they mistakenly applied the value to the connection's window size (and I agree that the two are easy to confuse, as I made the mistake myself yesterday when trying to address the "issue").

**Comment by wtarreau** [comment] 2024-10-12 16:14
Now closing.

**Closed as completed by wtarreau** 2024-10-12 16:14 UTC
Labels: type: bug, status: invalid, subsystem: h2
