### ISSUE TITLE
Incorrect frontend IP and port logged in 2.5.0

### ISSUE THREAD

**Issue by welbymcroberts** [haproxy/haproxy#1479] opened 2021-12-07 13:08 UTC
### Detailed Description of the Problem

When configuing a custom log format, the frontend_ip and frontend_port (%fi & %fp) do not log the frontend IP / port, but instead log the client ip / port.

The same configuration has worked in 2.4.x, however after upgrading to 2.5.0 this no longer works as expected.

### Expected Behavior

Log entries should contain the frontend ip & port.

### Steps to Reproduce the Behavior

1. Configure Frontend with `mode http`
2. Configure Frontend with log-format
```
log-format '{ "request_time": "%tr", "response_status": %ST, "request_method": "%HM", "request_host": "%[capture.req.hdr(0)]", "request_uri": "%HU", "request_http_version": "%HV", "request_size": %U, "response_size": %B, "src_addr": "%ci", "src_port": %cp, "dst_addr": "%fi", "dst_port": %fp, "frontend_name": "%f", "backend_name": "%b", "server_name": "%s", "handshake_time": %Th, "client_send_time": %TR, "queue_time": %Tw, "server_wait_time": %Tc, "server_response_time": %Tr, "total_request_time": %Ta, "termination_state": "%tsc", "backend_retries": "%rc", "client_ssl_version":"%sslv" }'
```
3. Check logs, and observe that src_addr and dst_addr are the same value, and that src_port and dst_port are the same value similar to below

```
{ "request_time": "07/Dec/2021:13:04:30.634", "response_status": 200, "request_method": "GET", "request_host": "REDACTED", "request_uri": "https://REDACTED/", "request_http_version": "HTTP/2.0", "request_size": 158, "response_size": 402, "src_addr": "212.69.X.X", "src_port": 50220, "dst_addr": "212.69.X.X", "dst_port": 50220, "frontend_name": "REDACTED", "backend_name": "REDACTED", "server_name": "REDACTED", "handshake_time": 37, "client_send_time": 1, "queue_time": 0, "server_wait_time": 0, "server_response_time": 0, "total_request_time": 38, "termination_state": "----", "backend_retries": "0", "client_ssl_version":"TLSv1.3"}
```

### Do you have any idea what may have caused this?

Commit f9c4d8d5be alters src/log.c to use a different method to capture the source / destination IP/port.

### What is your configuration?

```haproxy
Frontend configuration


frontend redacted_frontend_name
        bind redacted_ip:redacted_port ssl crt redacted_cert_path_and_name alpn h2,http/1.1
        mode http
        default_backend redacted_backend_name

        option forwardfor

<some custom request headers removed>

        http-request capture req.hdr(Host) len 255

        log-format '{ "request_time": "%tr", "response_status": %ST, "request_method": "%HM", "request_host": "%[capture.req.hdr(0)]", "request_uri": "%HU", "request_http_version": "%HV", "request_size": %U, "response_size": %B, "src_addr": "%ci", "src_port": %cp, "dst_addr": "%fi", "dst_port": %fp, "frontend_name": "%f", "backend_name": "%b", "server_name": "%s", "handshake_time": %Th, "client_send_time": %TR, "queue_time": %Tw, "server_wait_time": %Tc, "server_response_time": %Tr, "total_request_time": %Ta, "termination_state": "%tsc", "backend_retries": "%rc", "client_ssl_version":"%sslv" }'
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.0-f2e0833 2021/11/23 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
Running on: Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Additional Information

HAProxy is running as a container, with image 
`docker.io/library/haproxy                    2.5.0       6f62cf2dd2c9`

**Comment by capflam** [comment] 2021-12-07 17:21
I'm unable to reproduce the bug. Could you provide the minimal configuration, but complete, to reproduce it on you side please ?

**Comment by capflam** [comment] 2022-01-13 09:49
I'm closing this issue because without more info, we are unable to investigate on it. Feel free to reopen if it is still an issue for you. Thanks !

**Closed as completed by capflam** 2022-01-13 09:49 UTC
Labels: type: bug, status: feedback required, dev, 2.5
