### ISSUE TITLE
Haproxy 2.3.0-2.3.2 sometimes produce corrupted status report csv

### ISSUE THREAD

**Issue by vooon** [haproxy/haproxy#992] opened 2020-12-04 08:33 UTC
## Detailed description of the problem

After update to 2.3.0 we started to observe problems with monitoring. Old sensu plugin stopped working, so i wrote new one.
But that plugin started to fire false positive alarms, while debugging i found out that sometimes "show stat" table may have empty `status` and even `svname`.

To catch output i added `--debug` flag to my check: https://github.com/sardinasystems/sensu-go-haproxy-check/blob/master/main.go#L251
Here is example of incorrect data:
```
ft_service_api,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,http,,0,4,8122,4149,0,0,0,,,0,0,,,,,,,0,,,,,,-,0,0,0,0,0,0,0,0,0,0,0,0,0,
bk_service_api,p091,0,0,0,3,,11148,4467668,18004150,,0,,0,0,0,0,UP,1,1,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,http,,,,,,,,0,1325,0,,,1,,0,6,24,24,0,1,0,0,1,1,-,,,,,,,,,,,,,,
bk_service_api,p092,0,0,0,3,,11147,4477117,17531876,,0,,0,0,0,0,UP,1,1,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,http,,,,,,,,0,1324,0,,,0,,0,6,130,130,0,0,0,0,1,1,-,,,,,,,,,,,,,,
bk_service_api,p093,0,0,0,3,,11147,4472388,17665686,,0,,0,0,0,0,UP,1,1,0,2,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,http,,,,,,,,0,1324,0,,,0,,0,5,36,36,0,0,0,0,1,1,-,,,,,,,,,,,,,,
bk_service_api,BACKEND,0,0,0,4,20000,33442,13417173,53201712,0,0,,0,0,0,0,UP,3,3,0,,0,82951,0,,1,30,0,,33442,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,http,,,,,,,,0,3973,0,0,0,,,0,6,130,130,0,,,,,3,-,0,0,0,0,0,0,0,0,0,0,0,0,0,
```
(we use `ft_` and `bk_` prefixes for frontends and backends).

As you can see frontend entry have empty most of the fields.
Sometimes we do not get backend entry, only server ones, sometimes we get server entries with empty `status`.

## Expected behavior

Expected to have pxname, svname, status fields populated.

## Steps to reproduce the behavior

Query `show stat` several times in a row, at some point you'll get that result. I think that it occurs at health check moment.
You can use my sensu check to catch that problem, but you need to remove workarounds from that function:
https://github.com/sardinasystems/sensu-go-haproxy-check/blob/master/haproxy/stat.go#L206

## Do you have any idea what may have caused this?

No, but i think that problems arises when haproxy performs service health check.

## What is your configuration?

```
frontend ft_service_api
  bind      192.168.50.10:8776
  mode      http
  option    httplog
  default_backend bk_service_api

backend bk_service_api
  mode      http
  balance   roundrobin
  option    tcpka
  option    httpchk GET /v2
  http-check expect status 401
  http-request set-header X-Forwarded-Prefix /service if { path_beg -i /service }
  http-request set-path %[path,regsub(^/service/?,/)]
  server p091 192.168.50.91:18776 check inter 2000 rise 2 fall 5
  server p092 192.168.50.92:18776 check inter 2000 rise 2 fall 5
  server p093 192.168.50.93:18776 check inter 2000 rise 2 fall 5
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3.2-d522db7 2020/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.2.html
Running on: Linux 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1c FIPS  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c FIPS  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.1 20191121 (Red Hat 8.3.1-5)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

```
Linux p090 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
(latest CentOS 8, vanilla Haproxy built from source)

**Comment by capflam** [comment] 2021-01-06 12:34
A push a patch that should fix this issue. It is probably a duplicate of #972.

**Comment by vooon** [comment] 2021-01-06 14:12
@capflam i hope it would help.
I tried to build current master, but unfortunately it segfaults. Maybe because i only copy haproxy binary, not sure.
To me it's easier to build rpm from release tarball, so i would check next release.

```
# /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock -f /etc/haproxy/extra.cfg
...
[NOTICE] 005/170605 (300765) : haproxy version is 2.4-dev4-153d4a-85
[NOTICE] 005/170605 (300765) : path to executable is /sbin/haproxy
[ALERT] 005/170605 (300765) : Current worker #1 (300767) exited with code 139 (Segmentation fault)
[ALERT] 005/170605 (300765) : exit-on-failure: killing every processes with SIGTERM
[WARNING] 005/170605 (300765) : All workers exited. Exiting... (139)
```

**Comment by capflam** [comment] 2021-01-06 14:20
Not good ... could you run it within gdb and without the master-worker mode to have a trace ? It could be good to know why it segfaults before the release.

**Comment by vooon** [comment] 2021-01-06 14:28
I tried to replace `-Ws` with `-db` and `-d`. In that mode it's working.
Will try to use foreground mode + increase monitoring frequency.

**Comment by vooon** [comment] 2021-01-06 14:57
I'm apologise, wrong binary!

```
# gdb /tmp/haproxy
(gdb) run -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock -f /etc/haproxy/extra.cfg -d
....
[WARNING] 005/175437 (856915) : Health check for server ipmi_exporter/p092 succeeded, reason: Layer7 check passed, code: 200, check duration: 1ms, status: 5/5 UP.

Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
0x0000000000469ae3 in http_debug_stline (dir=dir@entry=0x5c3d1a "clireq", s=s@entry=0xaf60e0, sl=sl@entry=0x0) at src/http_ana.c:4848
4848	src/http_ana.c: No such file or directory.
Missing separate debuginfos, use: yum debuginfo-install libblkid-2.32.1-24.el8.x86_64 libcap-2.26-4.el8.x86_64 libgcc-8.3.1-5.1.el8.x86_64 libgcrypt-1.8.5-4.el8.x86_64 libgpg-error-1.31-1.el8.x86_64 libmount-2.32.1-24.el8.x86_64 libselinux-2.9-4.el8_3.x86_64 libuuid-2.32.1-24.el8.x86_64 libxcrypt-4.1.1-4.el8.x86_64 lz4-libs-1.8.3-2.el8.x86_64 openssl-libs-1.1.1g-11.el8.x86_64 pcre2-10.32-2.el8.x86_64 sssd-client-2.3.0-9.el8.x86_64 systemd-libs-239-41.el8_3.x86_64 xz-libs-5.2.4-3.el8.x86_64 zlib-1.2.11-16.el8_2.x86_64
(gdb)
```

Will try to build directly on that server...

**Comment by capflam** [comment] 2021-01-06 15:08
Hum, that's totally unexpected to have no request start-line at this stage. I must check how it is possible.

**Comment by vooon** [comment] 2021-01-06 15:09
Now i compiled directly on dev lb:

```
make CPU="generic" TARGET="linux-glibc" USE_OPENSSL=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_ZLIB=1 USE_LINUX_TPROXY=1 DEFINE=-DTCP_USER_TIMEOUT=18 USE_SYSTEMD=1 USE_TFO=1 USE_NS=1 EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"
```

```
[root@p090 haproxy]# ./haproxy -vv
HA-Proxy version 2.4-dev4-153d4a-85 2021/01/06 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.1 20191121 (Red Hat 8.3.1-5)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

Gdb with `-db`:
```
[WARNING] 005/180538 (1065319) : Health check for server ipmi_exporter/p093 succeeded, reason: Layer7 check passed, code: 200, check duration: 0ms, status: 5/5 UP.

Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
http_wait_for_request (s=0xb0ce20, req=0xb0ce30, an_bit=<optimized out>) at src/http_ana.c:148
148		txn->meth = sl->info.req.meth;
Missing separate debuginfos, use: yum debuginfo-install libblkid-2.32.1-24.el8.x86_64 libcap-2.26-4.el8.x86_64 libgcc-8.3.1-5.1.el8.x86_64 libgcrypt-1.8.5-4.el8.x86_64 libgpg-error-1.31-1.el8.x86_64 libmount-2.32.1-24.el8.x86_64 libselinux-2.9-4.el8_3.x86_64 libuuid-2.32.1-24.el8.x86_64 libxcrypt-4.1.1-4.el8.x86_64 lz4-libs-1.8.3-2.el8.x86_64 openssl-libs-1.1.1g-11.el8.x86_64 pcre2-10.32-2.el8.x86_64 sssd-client-2.3.0-9.el8.x86_64 systemd-libs-239-41.el8_3.x86_64 xz-libs-5.2.4-3.el8.x86_64 zlib-1.2.11-16.el8_2.x86_64
```

Gdb `-d`:
```
[WARNING] 005/180620 (1078537) : Health check for server bk_service/p093 succeeded, reason: Layer7 check passed, code: 200, check duration: 5ms, status: 5/5 UP.
0000003e:ft_service_api.accept(0024)=00bf from [192.168.50.91:40664] ALPN=<none>

Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
0x0000000000469ae3 in http_debug_stline (dir=dir@entry=0x5c3d1a "clireq", s=s@entry=0xaf1820, sl=sl@entry=0x0) at src/http_ana.c:4848
4848	        max = HTX_SL_P1_LEN(sl);
```

**Comment by capflam** [comment] 2021-01-06 15:49
I don't understand how it possible. There is a code-path to create a stream without any request, but I didn't find it till now. In the first case (gdb with `-db` only), could you execute following commands ?
```
p *req
p *msg
p *txn
p *htx
bt full
```

**Comment by vooon** [comment] 2021-01-06 15:58
```
# gdb ./haproxy
(gdb) run -f /etc/haproxy/haproxy.cfg -db
...
Thread 1 "haproxy" received signal SIGSEGV, Segmentation fault.
http_wait_for_request (s=0xaffbc0, req=0xaffbd0, an_bit=<optimized out>) at src/http_ana.c:148
148		txn->meth = sl->info.req.meth;
Missing separate debuginfos, use: yum debuginfo-install libblkid-2.32.1-24.el8.x86_64 libcap-2.26-4.el8.x86_64 libgcc-8.3.1-5.1.el8.x86_64 libgcrypt-1.8.5-4.el8.x86_64 libgpg-error-1.31-1.el8.x86_64 libmount-2.32.1-24.el8.x86_64 libselinux-2.9-4.el8_3.x86_64 libuuid-2.32.1-24.el8.x86_64 libxcrypt-4.1.1-4.el8.x86_64 lz4-libs-1.8.3-2.el8.x86_64 openssl-libs-1.1.1g-11.el8.x86_64 pcre2-10.32-2.el8.x86_64 sssd-client-2.3.0-9.el8.x86_64 systemd-libs-239-41.el8_3.x86_64 xz-libs-5.2.4-3.el8.x86_64 zlib-1.2.11-16.el8_2.x86_64
(gdb) p *req
$1 = {flags = 9469954, analysers = 2308, buf = {size = 0, area = 0x0, data = 0, head = 0}, pipe = 0x0, output = 0, to_forward = 0, last_read = 44825, xfer_large = 0 '\000', xfer_small = 0 '\000', total = 349, rex = 0, wex = 0, rto = 120000, wto = 0, analyse_exp = 0}
(gdb) p *msg
value has been optimized out
(gdb) p *txn
value has been optimized out
(gdb) p *htx
$3 = {size = 0, data = 0, tail = -1, head = -1, first = -1, tail_addr = 0, head_addr = 0, end_addr = 0, extra = 0, flags = 0, blocks = 0x84fb10 ""}
(gdb) bt full
#0  http_wait_for_request (s=0xaffbc0, req=0xaffbd0, an_bit=<optimized out>) at src/http_ana.c:148
        sess = <optimized out>
        txn = <optimized out>
        msg = <optimized out>
        htx = 0x84fae0 <htx_empty>
        sl = 0x0
        __x = <optimized out>
        __l = <optimized out>
#1  0x000000000047fc2d in process_stream (t=t@entry=0xaff4b0, context=0xaffbc0, state=<optimized out>) at src/stream.c:1786
        max_loops = 198
        ana_list = 2308
        ana_back = 2308
        flags = <optimized out>
        srv = <optimized out>
        s = 0xaffbc0
        sess = <optimized out>
        rqf_last = <optimized out>
        rpf_last = 2147483648
        rq_prod_last = 8
        rq_cons_last = 0
        rp_cons_last = 8
        rp_prod_last = 0
        req_ana_back = <optimized out>
        req = 0xaffbd0
        res = 0xaffc30
        si_f = 0xaffe68
        si_b = 0xaffec0
        rate = <optimized out>
#2  0x0000000000557d03 in run_tasks_from_lists (budgets=budgets@entry=0x7fffffffe134) at src/task.c:497
        process = <optimized out>
        tl_queues = 0x8df7b0 <task_per_thread+48>
        t = 0xaff4b0
        budget_mask = 7 '\a'
        done = <optimized out>
        queue = <optimized out>
        state = <optimized out>
        ctx = <optimized out>
#3  0x0000000000558668 in process_runnable_tasks () at src/task.c:700
        tt = 0x8df780 <task_per_thread>
        lrq = <optimized out>
        grq = <optimized out>
        t = <optimized out>
        max = {0, 198, 0}
        max_total = <optimized out>
        tmp_list = <optimized out>
        queue = 3
        max_processed = <optimized out>
        picked = <optimized out>
        budget = <optimized out>
#4  0x000000000052de24 in run_poll_loop () at src/haproxy.c:2851
        next = <optimized out>
        wake = <optimized out>
#5  0x000000000052e163 in run_thread_poll_loop (data=data@entry=0x0) at src/haproxy.c:3016
        ptaf = <optimized out>
        ptif = 0x849930 <per_thread_init_list>
        ptdf = <optimized out>
        ptff = <optimized out>
        init_left = 0
        init_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}
        init_cond = {__data = {{__wseq = 93, __wseq32 = {__low = 93, __high = 0}}, {__g1_start = 81, __g1_start32 = {__low = 81, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 24, __wrefs = 0, __g_signals = {0, 0}}, 
          __size = "]\000\000\000\000\000\000\000Q", '\000' <repeats 23 times>, "\030", '\000' <repeats 14 times>, __align = 93}
#6  0x000000000041f0b2 in main (argc=<optimized out>, argv=0x7fffffffe498) at src/haproxy.c:3710
        blocked_sig = {__val = {18446744067199990583, 18446744073709551615 <repeats 15 times>}}
        old_sig = {__val = {0, 140737321603190, 1, 9581072, 8645744, 4, 140737488348312, 5414826, 1, 16, 8, 4324535, 0, 9581072, 65535, 0}}
        i = <optimized out>
        err = <optimized out>
        retry = <optimized out>
        limit = {rlim_cur = 200252, rlim_max = 200252}
        pidfd = <optimized out>
```

**Comment by capflam** [comment] 2021-01-06 16:18
Thanks ! I got it. It happens during a TCP to HTTP stream upgrade for a TCP frontend routed to an HTTP backend. It is really annoying, I missed this point during my last changes on the H1 multiplexer. It only happens on the 2.4. It is unrelated to this issue though. A temporary workaround is to use an HTTP frontend.

**Comment by vooon** [comment] 2021-01-06 18:31
Ok, i will test tomorrow. But i have a lot of proxies to update...
But TCP-TCP proxies would be ok, right? Because i have few plain tcp services.
Also after migration to 2.2 i have to revert to tcp for grpc (didn't have enough time to check what's wrong with my 2.1 config).

**Comment by capflam** [comment] 2021-01-06 20:18
Right, no pb with TCP-TCP proxies.

**Comment by capflam** [comment] 2021-01-07 10:09
The fix about the stats was backported to 2.3. Thus I'm closing this issue. I will create a new issue for the TCP-HTTP upgrade. It is unrelated with this one and it only affects the 2.4-dev. Thanks !

**Closed as completed by capflam** 2021-01-07 10:09 UTC
Labels: type: bug, subsystem: stats, status: fixed

**Comment by vooon** [comment] 2021-01-07 10:14
I have been updated frontends and haproxy runs for a few hours without any problem.
I also do not see monitoring notifications, so stats must be fixed. Thanks!

**Comment by capflam** [comment] 2021-01-07 10:15
Thanks for the feedback.
