### ISSUE TITLE
High CPU USAGE / no requests handling in haproxy 2.0.1

### ISSUE THREAD

**Issue by radut** [haproxy/haproxy#156] opened 2019-07-06 19:51 UTC
I have upgraded to latest stable haproxy from 1.8 to 2.0, and added prometheus stats, http-use-htx. While I had no CPU usage before on 1.8.. now I have permanent 100% cpu usage, all cores are used by haproxy(similar workload). I have tried to disable prometheus stats to see if related, then http-use-htx.. problem still present. The strange thing is that if I restart the haproxy, cpu si back to normal, then after a while.. it goes to 100%

while the cpu is 100% I noticed that the requests are being hanged
systemctl restart haproxy - gets back to normal
systemctl reload haproxy - gets back to normal

## Output of `haproxy -vv` and `uname -a`
```
uname -a
Linux es-master-1 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
haproxy -vvv
HA-Proxy version 2.0.1-1ppa1~bionic 2019/06/27 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-O7_wB6/haproxy-2.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```
config
```
cat /etc/haproxy/haproxy.cfg
#https://www.haproxy.com/blog/haproxy-2-0-and-beyond/
global
  log /dev/log  local0
  log /dev/log  local1 notice
  user haproxy
  group haproxy
  stats socket /run/haproxy/admin.sock user haproxy group haproxy mode 660 level admin
  daemon

  nbproc 1

  #http://www.loadbalancer.org/blog/how-to-get-more-out-of-and-in-to-haproxy/
  #This setting is only available when support for threads was built in. It
  #  makes haproxy run on <number> threads. This is exclusive with "nbproc". While
  #  "nbproc" historically used to be the only way to use multiple processors, it
  #  also involved a number of shortcomings related to the lack of synchronization
  #  between processes (health-checks, peers, stick-tables, stats, ...) which do
  #  not affect threads. As such, any modern configuration is strongly encouraged
  #  to migrate away from "nbproc" to "nbthread". See also "nbproc".
  nbthread 2

	# Default ciphers to use on SSL-enabled listening sockets.
	# For more information, see ciphers(1SSL). This list is from:
	#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3
    tune.ssl.default-dh-param 2048

defaults
  log global
  mode  http
  option  dontlognull
  maxconn 20000000

  timeout connect 5000
  timeout client 50000
  timeout server 50000


frontend stats
   bind *:8404
   option http-use-htx
   http-request use-service prometheus-exporter if { path /metrics }
   stats enable  # Enable stats page
   stats hide-version  # Hide HAProxy version
   stats uri /haproxy_stats  # Stats URI



  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

# https://www.haproxy.com/blog/haproxy-2-0-and-beyond/#peers-stick-tables-improvements
# https://www.haproxy.com/blog/introduction-to-haproxy-stick-tables/





frontend ElasticSearch
    bind *:19200
    mode http
    option httplog
    # Enable HTX, the new native http representation
    option  http-use-htx
    maxconn 1000
    default_backend ElasticSearch_Backend


backend ElasticSearch_Backend
    mode http
    # Enable HTX, the new native http representation
    option  http-use-htx
    fullconn 1000
    balance roundrobin


    option forwardfor if-none
    option redispatch
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost

    cookie route insert indirect nocache

    #server lo localhost:1 cookie lo disabled

    server es-master-1 192.168.16.61:9200 cookie s61 check inter 2000 rise 2 fall 3
    server es-master-2 192.168.16.62:9200 cookie s62 check inter 2000 rise 2 fall 3
    server es-master-3 192.168.16.63:9200 cookie s63 check inter 2000 rise 2 fall 3


frontend LogStash
    bind *:15001
    mode tcp
    option tcplog
    maxconn 1000
    default_backend LogStash_Backend


backend LogStash_Backend
    mode tcp
    fullconn 1000
    balance leastconn


    option tcp-check


    #server lo localhost:1 cookie lo disabled

    server es-master-1 192.168.16.61:5001 check inter 2000 rise 2 fall 3
    server es-master-2 192.168.16.62:5001 check inter 2000 rise 2 fall 3
    server es-master-3 192.168.16.63:5001 check inter 2000 rise 2 fall 3


frontend Kibana
    bind *:80
    mode http
    option httplog
    # Enable HTX, the new native http representation
    option  http-use-htx
    maxconn 1000
    default_backend Kibana_Backend


backend Kibana_Backend
    mode http
    # Enable HTX, the new native http representation
    option  http-use-htx
    fullconn 1000
    balance roundrobin


    option forwardfor if-none
    option redispatch
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost

    cookie route insert indirect nocache

    #server lo localhost:1 cookie lo disabled

    server es-master-1 192.168.16.61:5601 cookie s61 check inter 2000 rise 2 fall 3
    server es-master-2 192.168.16.62:5601 cookie s62 check inter 2000 rise 2 fall 3
    server es-master-3 192.168.16.63:5601 cookie s63 check inter 2000 rise 2 fall 3

```

```
(paste your output here)
```

## What's the configuration?

```
(paste your output here)
```

## Steps to reproduce the behavior

1. Install Latest stable haproxy 2.0 from ppa ppa:vbernat/haproxy-2.0 / ubuntu 18.04
2. Add some tcp / http backends with health check
3. do some traffic (20-40 rpm), don't restart haproxy and wait a few hours.
4. add prometheus requests every 10 seconds to :8404/metrics path
5. No requests are being handled anymore, everything is t/o 
```
curl -m 5 -v localhost:8404/metrics
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8404 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:8404
> User-Agent: curl/7.58.0
> Accept: */*
>
* Operation timed out after 5001 milliseconds with 0 bytes received
* stopped the pause stream!
* Closing connection 0
curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received
curl -m 5 -v localhost:80/metrics
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /metrics HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
>
* Operation timed out after 5000 milliseconds with 0 bytes received
* stopped the pause stream!
* Closing connection 0
curl: (28) Operation timed out after 5000 milliseconds with 0 bytes received
```

**--after some more tests i found this valid path to trigger 100% cpu usage, which seems to be connected to prometheus stats (I will let this instance without prometheus stats a while and edit back this bug)** might be related to https://github.com/haproxy/haproxy/issues/151
1. ab -c 300 -t 10 http://192.168.16.61:8404/metrics  #(do not use -k / keep alive) after ab finishes / cancel it after few seconds, you will see that no other request is being handled, and soon enough cpu will go to 100% 
2. wait 5 minutes max after you get request timeout to any frontend, and observe cpu usage.

*** I will let this instance run 24 hours without prometheus stats to double check if this is only related to prometheus stats ***

## Actual behavior

CPU 100%
![image](https://user-images.githubusercontent.com/4960306/60760593-4788a780-a040-11e9-8da5-405e5e9b9fda.png)
![image](https://user-images.githubusercontent.com/4960306/60760594-4a839800-a040-11e9-9a7b-08213c0ba09d.png)

## Expected behavior
Normal CPU (after restart)
![image](https://user-images.githubusercontent.com/4960306/60760595-53746980-a040-11e9-87a0-e0a12df71165.png)

is there something that raise any red flag in my config ?
Is prometheus stats something that can cause this kind of cpu usage ?

**Comment by TimWolla** [comment] 2019-07-06 22:45
Possible duplicate of #129.

**Comment by radut** [comment] 2019-07-07 04:55
I saw that you fixed the number of increasing sessions in haproxy stats frontend. Is it easy to push to : https://launchpad.net/~vbernat/+ppa-packages so I can give it one more try ?

**Comment by madebyCL** [comment] 2019-07-09 07:49
Same issues on Centos 7/x64 

easy to reproduction : 

curl --connect-timeout 3 --max-time 3 -s http://localhost:[statport]/metrics

or try to ab then less than one minutes, haproxy will fail to non-responding status, and cpu 100%


inspection debug logs


Jul  9 16:33:11 lb haproxy: 0000020e:stats.accept(000a)=0085 from [1.2.3.4:45112] ALPN=<none>
Jul  9 16:33:11 lb haproxy: 0000020e:stats.clireq[0085:ffffffff]: GET /metrics HTTP/1.1
Jul  9 16:33:11 lb haproxy: 0000020e:stats.clihdr[0085:ffffffff]: host: 1.2.5.5:8104
Jul  9 16:33:11 lb haproxy: 0000020e:stats.clihdr[0085:ffffffff]: user-agent: Go-http-client/1.1
Jul  9 16:33:11 lb haproxy: 0000020e:stats.clihdr[0085:ffffffff]: accept-encoding: gzip
Jul  9 16:33:11 lb haproxy: 0000020e:stats.srvrep[0085:ffffffff]: HTTP/1.1 200 OK
Jul  9 16:33:11 lb haproxy: 0000020e:stats.srvhdr[0085:ffffffff]: cache-control: no-cache
Jul  9 16:33:11 lb haproxy: 0000020e:stats.srvhdr[0085:ffffffff]: connection: close
Jul  9 16:33:11 lb haproxy: 0000020e:stats.srvhdr[0085:ffffffff]: content-type: text/plain; version=0.0.4
Jul  9 16:33:11 lb haproxy: 0000020e:stats.srvhdr[0085:ffffffff]: transfer-encoding: chunked
Jul  9 16:33:11 lb haproxy: 0000020e:stats.srvcls[0085:ffffffff]
Jul  9 16:33:11 lb haproxy: 0000020e:stats.clicls[0085:ffffffff]
Jul  9 16:33:11 lb haproxy: 0000020e:stats.closed[0085:ffffffff]

<- well closed

Jul  9 16:32:40 lb haproxy: 000001e0:stats.accept(000a)=0080 from [1.2.3.4:44978] ALPN=<none>
Jul  9 16:32:40 lb haproxy: 000001e0:stats.clireq[0080:ffffffff]: GET /metrics HTTP/1.1
Jul  9 16:32:40 lb haproxy: 000001e0:stats.clihdr[0080:ffffffff]: host: 1.2.5.5:8104
Jul  9 16:32:40 lb haproxy: 000001e0:stats.clihdr[0080:ffffffff]: user-agent: Prometheus/2.3.2
Jul  9 16:32:40 lb haproxy: 000001e0:stats.clihdr[0080:ffffffff]: accept: text/plain;version=0.0.4;q=1,*/*;q=0.1
Jul  9 16:32:40 lb haproxy: 000001e0:stats.clihdr[0080:ffffffff]: accept-encoding: gzip
Jul  9 16:32:40 lb haproxy: 000001e0:stats.clihdr[0080:ffffffff]: x-prometheus-scrape-timeout-seconds: 10.000000
Jul  9 16:32:40 lb haproxy: 000001e0:stats.srvrep[0080:ffffffff]: HTTP/1.1 200 OK
Jul  9 16:32:40 lb haproxy: 000001e0:stats.srvhdr[0080:ffffffff]: cache-control: no-cache
Jul  9 16:32:40 lb haproxy: 000001e0:stats.srvhdr[0080:ffffffff]: connection: close
Jul  9 16:32:40 lb haproxy: 000001e0:stats.srvhdr[0080:ffffffff]: content-type: text/plain; version=0.0.4
Jul  9 16:32:40 lb haproxy: 000001e0:stats.srvhdr[0080:ffffffff]: transfer-encoding: chunked
Jul  9 16:32:40 lb haproxy: 000001e0:stats.srvcls[0080:ffffffff]

<- not closed, this will be stacked in counters.  prometheus scrapper


Current configuration 

frontend stats
    mode http
    bind *:8104
    option http-use-htx
    option http-server-close // not working
    option httpclose // not working
    http-request use-service prometheus-exporter if { path /metrics }

I'm just guessing some htx issue or exporter module issue.

**Comment by lukastribus** [comment] 2019-07-09 07:55
Please try 2.0 HEAD or a current 2.0 snapshot.

**Comment by capflam** [comment] 2019-07-09 07:55
@madebyCL, what is your HAProxy version ? Because this bug should be fix. See #151. However, you need to use [the latest 2.0 snapshot](http://www.haproxy.org/download/2.0/src/snapshot/haproxy-ss-LATEST.tar.gz) to have this fix.

**Comment by madebyCL** [comment] 2019-07-09 07:56
HA-Proxy version 2.0.1 2019/06/26 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

**Comment by madebyCL** [comment] 2019-07-09 07:59
@capflam  Now I tried 2.0 ss, confirm that fixed

**Comment by capflam** [comment] 2019-07-09 14:34
Thanks for your feedback. I will mark it as a duplicate of #151 because the fix was linked to this issue.

**Comment by capflam** [comment] 2019-07-09 14:34
Duplicate of #151

**Closed as completed by capflam** 2019-07-09 14:34 UTC
Labels: type: bug, status: duplicate

**Comment by radut** [comment] 2019-07-09 14:37
I can confirm that the issue dissapeared when I builded the haproxy.

But again sorry for insisting..  can you update the ppa ?

**Comment by capflam** [comment] 2019-07-09 14:46
We are not responsible of the Debian/Ubuntu packages. You must ask to the Debian maintainer, @vincentbernat. But most of time, he packages HAProxy releases.

FYI, we probably make new 2.0, 1.9 and 1.8 releases very soon.

**Comment by radut** [comment] 2019-07-09 14:53
Thank you.

**Comment by wtarreau** [comment] 2019-07-09 16:21
Also, please be kind with distro maintainers. Most of them do this solely
on their spare time, just like a number of the community members here,
and the only way to keep a high quality along the whole chain is by
respecting each participant's rhythm and process. Typically it doesn't
sound realistic to ask them to package nightly snapshots. In practice it
already works fairly well this way, and it's normal to experience a few
hickups in the early days of a new major release. If it is not compatible
with your process (which I can perfectly understand), you should probably
step back to 1.9 for a few more weeks waiting for the dust to settle.

**Comment by radut** [comment] 2019-07-15 20:31
Please reopen this as the issue seems to not be fixed(haproxy hangs, cpu is ok, sessions on stats keep increasing until hang):
```
HA-Proxy version 2.1-dev0 2019/06/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS =

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

```

stats :
```
frontend stats
   bind *:8404
   option http-use-htx
   http-request use-service prometheus-exporter if { path /metrics }
   stats enable  # Enable stats page
   stats hide-version  # Hide HAProxy version
   stats uri /haproxy_stats  # Stats URI
```


```
ab -c 300 -t 30 http://localhost:8404/metrics
##or
httperf --server=localhost --port=8404 --uri=/metrics --num-conns=30000 --rate=300
```
makes haproxy not responding. 
Before haproxy hangs I see that sessions keep increasing in frontend stats, both "Current" and "Max"

<img width="1670" alt="Screenshot 2019-07-15 at 23 12 06" src="https://user-images.githubusercontent.com/4960306/61245793-05edb000-a756-11e9-8687-46cb3557ce66.png">
 
From my tests the CPU does not jump anymore to 100%, but very fast haproxy hangs and never respond to any other connection
```
root@es-master-1:/home/ubuntu/haproxy-master# curl -m5 http://localhost:8404/metrics
curl: (28) Connection timed out after 5000 milliseconds
root@es-master-1:/home/ubuntu/haproxy-master#
```

```
root@es-master-1:/home/ubuntu# cat /etc/haproxy/haproxy.cfg |grep 9200
    bind *:19200
    server es-master-1 192.168.16.61:9200 cookie s61 check inter 2000 rise 2 fall 3
    server es-master-2 192.168.16.62:9200 cookie s62 check inter 2000 rise 2 fall 3
    server es-master-3 192.168.16.63:9200 cookie s63 check inter 2000 rise 2 fall 3
root@es-master-1:/home/ubuntu# curl -I -m5 192.168.16.61:9200
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 490

root@es-master-1:/home/ubuntu# curl -I -m5 localhost:19200
curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received
root@es-master-1:/home/ubuntu#
```

Maybe CPU will hit later.. or maybe because it hangs so fast about 400-500 sessions, there are less threads to keep cpu busy.
