### ISSUE TITLE
haproxy 2.0.5: reload: former process  take 15min to shutdown

### ISSUE THREAD

**Issue by aderumier** [haproxy/haproxy#228] opened 2019-08-21 15:42 UTC
Hi,

I have an haproxy 2.0.5, but I have also seen this behaviour on 1.9.9, both debian buster with systemd.

when I reload haproxy, sometime the former old process  take 10-15min to shudown and sometime stuck at 100% of 1core

here the sample config

```
#
global
        log /dev/log local0 notice
        log /dev/log local1 info
        daemon
        stats timeout 30s
        user haproxy
        group haproxy
        stats socket /var/run/haproxy.socket user haproxy group haproxy mode 666 level admin  expose-fd listeners
        stats timeout 10m
        #haproxy 1.8 async
        ssl-engine rdrand  # intel engine available in openssl
        ssl-mode-async
        # Default SSL material locations
        ca-base /etc/haproxy/ssl
        crt-base /etc/haproxy/ssl
        ssl-default-bind-options no-sslv3 no-tls-tickets  no-tlsv10 no-tlsv11
        ssl-default-bind-ciphers TLS13-AES-128-GCM-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-E$
        ssl-default-server-ciphers TLS13-AES-128-GCM-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE$
        ssl-default-server-options no-sslv3 no-tls-tickets  no-tlsv10 no-tlsv11
        tune.ssl.default-dh-param 2048
        #Increase TLS session cache size and lifetime to avoid computing too many symmetric keys
        tune.ssl.cachesize 10000
        tune.ssl.lifetime 600
        #set up a TLS record to match a TCP segment size, in order to improve client side rendering of content:
        tune.ssl.maxrecord 1460
        maxconn 32768

defaults
        log global
        mode http
        maxconn 32768
        balance leastconn
        option dontlognull
        option http-server-close
        option log-separate-errors
        option abortonclose
        option redispatch
        option httplog
        default-server inter 3s rise 2 fall 3
        option tcp-smart-connect
        timeout connect 5s
        timeout check 3s
        timeout queue 30s
        timeout client 600s
        timeout server 600s
        timeout http-request 10s
        timeout http-keep-alive 75s
        errorfile 408 /dev/null
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        no option http-use-htx

cache cacheimage
        total-max-size 1024
        max-age 86400

frontend FO
        bind *:80,:::80 v6only
        bind *:443,:::443 v6only ssl crt /etc/haproxy/ssl/ strict-sni alpn h2,http/1.1

        capture request header Host len 50
        capture request header User-Agent len 200
        capture request header Referer len 200

        acl from_cloudflare src -f /etc/haproxy/acls/cloudflare.lst
        acl cloudflare_ip_hdr req.hdr(CF-Connecting-IP) -m found
        acl staticfiles path_end -f /etc/haproxy/map.d/staticfiles.map
        acl url_wellknown path_beg /.well-known
          acl acl_odiso src -f /etc/haproxy/acls/odiso.lst
        acl acl_globalwhitelist src -f /etc/haproxy/acls/odiso.lst
        acl acl_globalwhitelist src -f /etc/haproxy/acls/moteur_recherche.lst
        acl is_jscss path_end .js .css
        acl is_image path_end .png .jpg .jpeg
        acl url_honeypot url,url_dec -m reg -i -f /etc/haproxy/acls/honeypot.patterns

        acl prerender-user-agent-bot hdr_sub(User-Agent) -i googlebot baiduspider twitterbot facebookexternalhit rogerbot linkedinbot embedly showyoubot outbrain pinterest slackbot vkShare W3C_Validator
        acl prerender-url-escaped-fragment url_sub _escaped_fragment_

        acl ipwhitelist src -f /etc/haproxy/map.d/xxxxx.map
        acl blackfire src -f /etc/haproxy/map.d/blackfire.map
        acl blackfire_whilelist req.hdr(X-Blackfire-Query) -m found


        http-request set-src hdr(CF-Connecting-IP) if from_cloudflare cloudflare_ip_hdr
        http-request set-header X-Country-Code %[src,map_ip(/etc/haproxy/geoip/geoip.lst)]
        http-request set-priority-class int(1) if is_jscss
        http-request set-priority-class int(10) if !is_jscss !is_image
        http-request set-priority-class int(100) if is_image

        http-request set-header X-Forwarded-for %[src]
        http-request set-header X-Forwarded-Proto https if { ssl_fc }
        option  forwardfor if-none
        errorfile 408 /dev/null

     
        use_backend prod_static if domain_prod staticfiles
        use_backend prod if domain_prod

```
(nbthread is autocompute to 8,maxproc=1)

systemd log
```
août 21 17:09:21 haproxy[25044]: [NOTICE] 232/170921 (25044) : New worker #1 (2188) forked
août 21 17:09:21  systemd[1]: Reloaded HAProxy Load Balancer.
août 21 17:25:58 haproxy[25044]: [WARNING] 232/172558 (25044) : Former worker #1 (25628) exited with code 0 (Exit)
```

ps after start
```
oot      8833  0.3 12.3 1524052 1513736 ?     Ss   17:27   0:01 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
haproxy   8844  8.5  4.7 2049580 578448 ?      Rl   17:27   0:47 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
```

ps after reload
```
root      8833  0.6 12.3 1524188 1513820 ?     Ss   17:27   0:03 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock -sf 8844 -x /var/run/haproxy.socket
haproxy   8844  8.0  4.7 2049580 580212 ?      Sl   17:27   0:47 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock
haproxy  12058  9.1  3.4 2046136 424372 ?      Sl   17:37   0:03 /usr/sbin/haproxy -Ws -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid -S /run/haproxy-master.sock -sf 8844 -x /var/run/haproxy.socket
```

memory is huge because if cache enable 1G + geoip map(400mb)
sessions in frontend are between 1000-2000.

I have tried to remove "expose-fd listeners" to remove hitless reload, still same.
I can reproduce it easily, if you have some hint to debug this, it could be great :)

**Comment by aderumier** [comment] 2019-08-21 16:12
Also, looking at lsof, I'm still seeing tcp established connection on old process (maybe 30-40, slowly decreasing). Maybe this is why the process is not shutdown.

I'm not sure of the reload process, but with hitless reload, the connections should be transfered to new process, right ?

**Comment by wtarreau** [comment] 2019-08-21 16:17
On Wed, Aug 21, 2019 at 09:12:53AM -0700, alexandre derumier wrote:
> Also, looking at lsof, I'm still seeing tcp established connection on old
> process (maybe 30-40, slowly decreasing). Maybe this is why the process is
> not shutdown.

So this is completely normal then.

> I'm not sure of the reload process, but with hitless reload, the connections
> should be transfered to new process, right ?

The *listening* sockets are transferred. Not active connections. You cannot
transfer a connection with a running active context (streams, data in buffers,
counters in stick tables, Lua processing in progress, compression context,
mux context, etc).

If you want to force your old process to die after a certain time, there is
the "hard-stop-after" setting in the global section for this.

Note that with the master-worker model you can have a CLI on the master
which allows you to connect to all workers including the old ones, and
inspect them, retrieve their stats, see their connections etc. This is
pretty convenient for such situations as it will allow you to decide if
you want to kill these processes or let them finish.

**Comment by aderumier** [comment] 2019-08-21 16:29
Oh, ok , thanks willy !

my "timeout client" is pretty high (10min).
as It's mostly http server, I have reduce the timeout client to 10s, like for http-request 10s.
(I'm not sure, maybe  timeout client should be a litte bit bigger than http-request ?)

and now it's shutdown a lot of faster.

**Comment by wtarreau** [comment] 2019-08-21 16:42
On Wed, Aug 21, 2019 at 09:29:05AM -0700, alexandre derumier wrote:
> my "timeout client" is pretty high (10min).
> as It's mostly http server, I have reduce the timeout client to 10s,

You should leave it a bit higher, some poorly connected visitors might
experience issues if they face multiple drops in sequence, especially
on POSTs or large document downloads. I tend not to go below 30s in
general.

> like for http-request 10s.
> (I'm not sure, maybe  timeout client should be a litte bit bigger than http-request ?)

It doesn't /need/ to be larger, though in this case it does make sense
as http-request mostly covers the headers.

> and now it's shutdown a lot of faster.

Great! You were probably facing idle visitors (in this case, you
can adjust timeout http-keep-alive) or a few visitors that had been
violently disconnected from the net (but you wouldn't have had 40
connections). Thus I guess they were mostly idle conns and you'd
rather set a short keep-alive timeout (10s likely) and a higher
client timeout to allow engaged transfers to complete nicely.

**Comment by wtarreau** [comment] 2019-08-21 20:16
Since in the end it was not a bug I'm closing this issue, but feel free to continue on the mailing list or discourse if you need more advanced help. I it's just for a short final question I'm fine with it being sent here :-)

**Closed as completed by wtarreau** 2019-08-21 20:16 UTC
Labels: type: bug, status: invalid

**Comment by EmericBr** [comment] 2021-11-17 14:08
Just for note: ssl-mode-async is useless on engine rdrand, since this engine doesn't use a device and was not blocking. ssl-mode-async was designed to work using intel quick assist engine.
