### ISSUE TITLE
[2.4-dev19] Segfault when using stick-tables

### ISSUE THREAD

**Issue by pierrecdn** [haproxy/haproxy#1247] opened 2021-05-11 16:52 UTC
## Detailed description of the problem

I gave a try to 2.4-dev19 and I'm experiencing a segfault on a part on my infrastructure using stick tables.

```
$ haproxy -v
HAProxy version 2.4-dev19-46b93af-dev19_criteo.el7.1 2021/05/10 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.10.32-1.el7.x86_64 #1 SMP Fri Apr 23 12:01:09 UTC 2021 x86_64
```

## Steps to reproduce the behavior

Here is the config structure: 

```
 backend foo
    stick-table type ip size 200k expire 30s store conn_rate(60s)
    tcp-request content track-sc1 src
```

And here is the thread backtrace:

```
Thread 1 (Thread 0x7fabf0da9180 (LWP 6838)):
#0  0x00005615d4e874d4 in smp_fetch_src (args=0x5615d4fec1e0 <empty_arg_list>, smp=0x7fff83a3d230, kw=0x0, private=0x0) at src/tcp_sample.c:52
#1  0x00005615d4de7ace in smp_fetch_sc_stkctr (sess=<optimized out>, strm=<optimized out>, args=0x7fabec897880, kw=<optimized out>, stkctr=stkctr@entry=0x7fff83a3d300) at src/stick_table.c:2365
#2  0x00005615d4de91f1 in smp_fetch_sc_conn_rate (args=<optimized out>, smp=0x7fff83a3d3c0, kw=<optimized out>, private=<optimized out>) at src/stick_table.c:2915
#3  0x00005615d4dcdd9f in sample_process (px=px@entry=0x7fabeb255000, sess=sess@entry=0x7fabeb02f2c0, strm=strm@entry=0x7fabec9c5f00, opt=opt@entry=6, expr=0x7fabec80aaa0, p=p@entry=0x7fff83a3d3c0)
    at src/sample.c:1098
#4  0x00005615d4e75e1c in acl_exec_cond (cond=0x7fabeb215ec0, px=px@entry=0x7fabeb255000, sess=sess@entry=0x7fabeb02f2c0, strm=strm@entry=0x7fabec9c5f00, opt=6, opt@entry=2) at src/acl.c:1111
#5  0x00005615d4d5f297 in http_req_get_intercept_rule (px=px@entry=0x7fabeb255000, rules=0x7fabeb255040, s=s@entry=0x7fabec9c5f00) at src/http_ana.c:2790
#6  0x00005615d4d622cf in http_process_req_common (s=0x7fabec9c5f00, req=0x7fabec9c5f10, an_bit=<optimized out>, px=0x7fabeb255000) at src/http_ana.c:370
#7  0x00005615d4d84f4a in process_stream (t=<optimized out>, context=<optimized out>, state=<optimized out>) at src/stream.c:1897
#8  0x00005615d4e6ae5b in run_tasks_from_lists (budgets=budgets@entry=0x7fff83a3d750) at src/task.c:558
#9  0x00005615d4e6b843 in process_runnable_tasks () at src/task.c:799
#10 0x00005615d4e32e55 in run_poll_loop () at src/haproxy.c:2602
#11 0x00005615d4e33469 in run_thread_poll_loop (data=data@entry=0x0) at src/haproxy.c:2775
#12 0x00005615d4d0a8d9 in main (argc=<optimized out>, argv=0x7fff83a3dba8) at src/haproxy.c:3438
```

## Do you have any idea what may have caused this?

Our integration tests seem to say that using sticktables and actually using the backend will crash the server, maybe due to the empty list passed to `smp_fetch_src`?

https://github.com/haproxy/haproxy/blob/dec1c36b3a4a2856496fd2ed79735a11818e7e56/src/tcp_sample.c#L52

**Comment by a-denoyelle** [comment] 2021-05-12 07:50
It seems there is a problem with the kw argument which is null. I'm investigating on it...

**Comment by a-denoyelle** [comment] 2021-05-12 08:14
Thanks for the report. I can reproduce the issue with sticky fetches "src_*". I'm on a fix.

**Comment by wtarreau** [comment] 2021-05-13 19:04
Closing since assuming fixed. Pierre, do not hesitate to reopen if that's not the case. 2.4-final should be ready tomorrow so no need to patch your 2.4-dev :-)

**Closed as completed by wtarreau** 2021-05-13 19:04 UTC
Labels: type: bug, status: fixed
