### ISSUE TITLE
Backend connection leak after connection failures

### ISSUE THREAD

**Issue by jaroslawr** [haproxy/haproxy#1003] opened 2020-12-14 09:19 UTC
## Detailed description of the problem

HAProxy will sometimes increase the backend connection pool by a lot (while not receiving more req/s) and then it never shrinks it back. I *suspect* it happens during a burst of failed connection attempts, e.g. when `timeout connect` fires. These leaked connections are counted in the stats as "Current used connections".

Here are two servers w304 and w305 which at the moment of collecting the info receive roughly the same share of traffic and take the same time to respond, but w304 has suffered from the problem. 

w304:
![w304_broken_stats](https://user-images.githubusercontent.com/26233/102061371-b0f31500-3df3-11eb-94eb-79bb09b0b52d.png)
`show fd` results on the connections: [w304_broken_fd_info.txt](https://github.com/haproxy/haproxy/files/5687646/w304_broken_fd_info.txt)

w305:
![w305_ok_stats](https://user-images.githubusercontent.com/26233/102061374-b2244200-3df3-11eb-8284-261b1d7c869f.png)
`show fd` results on the connections: [w305_ok_fd_info.txt](https://github.com/haproxy/haproxy/files/5687648/w305_ok_fd_info.txt)

We collect stats with 1 minute resolution, w304 "Current used connections" grew from 10 to a few thousands in one minute while there were some failures connecting, then fell to the value seen on the screen shot and now it will stay like this. 

## Expected behavior

Connection pool grows and shrinks with traffic demands.

## Steps to reproduce the behavior

`-`

## Do you have any idea what may have caused this?

My suspicion is it happens after a burst of connection failures but I might be wrong about this.

## Do you have an idea how to solve the issue?

`-`

## What is your configuration?

```
global
        user haproxy
        group haproxy

        nbthread 38
        maxconn 120000
        hard-stop-after 10s

        tune.bufsize 32768
        tune.ssl.default-dh-param 2048
        tune.ssl.cachesize 10000000
        tune.ssl.lifetime 3600

        log /dev/log local0 info info
        log /dev/log local1 notice

        stats socket /run/haproxy/haproxy-node1.sock mode 660 level admin

defaults
        mode http
        option httplog
        option dontlognull
        option forwardfor
        option http-buffer-request

        maxconn 110000

        retries 0
        no option redispatch

        # time client can be idle
        # on timeout: client connection is closed
        timeout client 50000

        # time backend server can be idle
        # on timeout: 504 Gateway Timeout response, client connection is not closed
        timeout server 500

        # time to connect to backend server
        # on timeout: 503 Service Unavailable response, client connection is not closed
        timeout connect 5

        # time to wait in queue for an available backend server
        # on timeout: 503 Service Unavailable response, client connection is not closed
        timeout queue 5

frontend xyz.com
        bind *:80
        bind *:443 ssl crt /etc/haproxy/xyz.com.pem alpn h2,http/1.1
        default_backend workers

        log global
        http-request set-log-level silent unless { rand(5000) lt 5 }

backend workers
        balance leastconn
        option httpchk
        http-check send meth HEAD uri /worker/healthcheck
        default-server check inter 1000 maxqueue 1

        server w101.xyz.net_8082 w101.xyz.net:8082 weight 6 maxconn 64
        server w102.xyz.net_8082 w102.xyz.net:8082 weight 64 maxconn 64
        server w103.xyz.net_8082 w103.xyz.net:8082 weight 64 maxconn 64
        server w104.xyz.net_8082 w104.xyz.net:8082 weight 64 maxconn 64
        server w105.xyz.net_8082 w105.xyz.net:8082 weight 32 maxconn 32
        server w106.xyz.net_8082 w106.xyz.net:8082 weight 64 maxconn 64
        server w107.xyz.net_8082 w107.xyz.net:8082 weight 64 maxconn 64
        server w108.xyz.net_8082 w108.xyz.net:8082 weight 80 maxconn 80
        server w109.xyz.net_8082 w109.xyz.net:8082 weight 128 maxconn 128
        server w110.xyz.net_8082 w110.xyz.net:8082 weight 80 maxconn 80
        ...
        server w567.xyz.net_8082 w567.xyz.net:8082 weight 128 maxconn 128
        server w568.xyz.net_8082 w568.xyz.net:8082 weight 128 maxconn 128
        server w999.xyz.net_8082 w999.xyz.net:8082 weight 60 maxconn 60

listen stats
        bind *:7655
        log global
        stats enable
        stats uri /
        stats refresh 5s
        acl valid_src src 10.0.0.0/8 172.16.0.0/12 127.0.0.0/8 5.135.236.132
        http-request deny if ! valid_src
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3.2-d522db7 2020/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.2.html
Running on: Linux 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64
root@a101:/# haproxy -vv
HA-Proxy version 2.3.2-d522db7 2020/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.2.html
Running on: Linux 4.15.0-66-generic #75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=38).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment] 2020-12-21 09:53
It could be possible that in some error paths we don't readjust the counters. It will take time to dig through this as this code is extremely complex :-/

**Comment by jaroslawr** [comment] 2020-12-21 10:43
@wtarreau FWIW it went away after increasing the connect timeout from `5` to `25`, or at least it doesn't manifest itself as frequently.

**Comment by wtarreau** [comment] 2020-12-21 12:04
Thanks for this hint, it could indeed help us dig into the right direction.

**Comment by a-denoyelle** [comment] 2020-12-21 17:10
I have taken a quick look. One path of the code which is suspect is in h1_timeout_task where the connection is removed from the list without decrementing the counters. The same code is present in mux_h2. It should probably use srv_del_conn_from_list.

However, I tried to trigger various timeouts but did not pass on this particular line (either h1c is already NULL or not in a list).

**Comment by jaroslawr** [comment] 2020-12-22 06:18
Just to be clear, it's not only the counters, there are actual TCP connections to the backend left (see the `show fd` output I attached).

**Comment by wtarreau** [comment] 2020-12-22 06:56
Thanks, but it's pretty possible that this is related, possibly by the connection not being moved back to the idle list, hence not being killed for example.

**Comment by rieger-jared** [comment] 2021-03-01 08:10
Hi, just wanted to know if there's an update to this issue? I'm having a similar issue with having a high used connections count. In my case this causes my servers hosting HAProxy to be under a higher load. Would it help to also supply information?

**Comment by rieger-jared** [comment] 2021-03-06 17:35
> @wtarreau FWIW it went away after increasing the connect timeout from `5` to `25`, or at least it doesn't manifest itself as frequently.

@jaroslawr This is in ms right?

**Comment by jbaanus** [comment] 2021-05-05 11:41
We have noticed similar behaviour, when the HTTP request to backend server fails with `HTTP 502`, tested both in HAProxy versions 2.0 and 2.2.

Configuration:
```
    retry-on all-retryable-errors
    option redispatch
    retries 3
```

On statistics page we can see increase in both `Warnings > Retr` and `Warnings > Redis`, however the number of `Sessions > Cur` is always increasing, never decreasing, according to the number of original requests from the client to the frontend.

Update: Verified this to be case on latest version 2.3.0 as well

**Comment by capflam** [comment] 2021-05-05 14:53
I confirm the counter issue but not the connection leak

**Comment by capflam** [comment] 2021-05-05 15:26
Note that @jbaanus's bug is probably not the same than @jaroslawr because in the config snippet provided by @jaroslawr, there is no connection retry. For me the issue about the current session counter is only visible with L7 retries.

**Comment by capflam** [comment] 2021-05-05 19:20
@jaroslawr, do you know if the bug still exists on the latest 2.3 release (2.3.10) ?

**Comment by jaroslawr** [comment] 2021-05-06 07:04
@capflam No, we increased the timeout and no longer trigger this problem.

**Comment by jbaanus** [comment] 2021-05-06 09:44
> Note that @jbaanus's bug is probably not the same than @jaroslawr because in the config snippet provided by @jaroslawr, there is no connection retry. For me the issue about the current session counter is only visible with L7 retries. 

Thank you for fixing this, we can confirm that the commit fixed the session count bug we are experiencing with 2.0 and 2.2

**Comment by capflam** [comment] 2021-05-06 14:36
@jbaanus thanks for the feedback ! @jaroslawr copy that. I will close the issue with the label "cannot reproduce" but that remains strange...

**Closed as completed by capflam** 2021-05-06 14:36 UTC
Labels: type: bug, status: cannot reproduce, 2.3
