### ISSUE TITLE
last server is not being removed from backend after consul service is deleted

### ISSUE THREAD

**Issue by ivoronin** [haproxy/haproxy#50] opened 2019-02-23 23:54 UTC
## Output of `haproxy -vv` and `uname -a`
```
$ uname -a
Linux ws02 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ ./haproxy -vv
HA-Proxy version 2.0-dev0-b8e602-315 2019/02/22 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_OPENSSL=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

## What's the configuration?
```
global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/run/haproxy.stats
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-server-ciphers PROFILE=SYSTEM
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000
listen stats
    bind :9000
    mode http
    stats enable
    stats admin if TRUE
    stats refresh 1s
resolvers consul
    nameserver consul 127.0.0.1:8600
frontend web-frontend
    bind *:8000
    default_backend web-backend
backend web-backend
    mode http
    balance leastconn
    option httpchk GET / HTTP/1.1\r\nHost:\ haproxy
    server-template web-backend- 8 _web-service._tcp.service.consul check resolvers consul
```

## Steps to reproduce the behavior

Start haproxy with no servers available:
```
[WARNING] 054/024235 (18393) : Server web-backend/web-backend-1 is DOWN, reason: Socket error, check duration: 0ms. 7 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 054/024236 (18393) : Server web-backend/web-backend-2 is DOWN, reason: Socket error, check duration: 0ms. 6 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 054/024236 (18393) : Server web-backend/web-backend-3 is DOWN, reason: Socket error, check duration: 0ms. 5 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 054/024236 (18393) : Server web-backend/web-backend-4 is DOWN, reason: Socket error, check duration: 0ms. 4 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 054/024236 (18393) : Server web-backend/web-backend-5 is DOWN, reason: Socket error, check duration: 0ms. 3 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 054/024237 (18393) : Server web-backend/web-backend-6 is DOWN, reason: Socket error, check duration: 0ms. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 054/024237 (18393) : Server web-backend/web-backend-7 is DOWN, reason: Socket error, check duration: 0ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[WARNING] 054/024237 (18393) : Server web-backend/web-backend-8 is DOWN, reason: Socket error, check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
[ALERT] 054/024237 (18393) : backend 'web-backend' has no server available!
```

Register a service:
```
$ consul services register -name=web-service -port=80
Registered service: web-service
$ dig +short -t SRV -p 8600 _web-service._tcp.service.consul @127.0.0.1
1 1 80 ws02.node.lab.consul.
```

```
[WARNING] 054/024416 (18393) : web-backend/web-backend-1 changed its IP from  to 192.168.90.34 by consul/consul.
[WARNING] 054/024419 (18393) : Server web-backend/web-backend-1 is UP, reason: Layer7 check passed, code: 200, info: "OK", check duration: 0ms. 1 active and 0 backup servers online. 0 sessions requeued, 0 total in queue.
```

Deregister a service:
```
$ consul services deregister -id=web-service
Deregistered service: web-service
$ dig +short -t SRV -p 8600 _web-service._tcp.service.consul @127.0.0.1
$
```

## Actual behavior

Nothing happens. Backend stays in UP state.

## Expected behavior
Backend should be declared DOWN

## Do you have any idea what may have caused this?
Are empty DNS responses handled poorly?

## Do you have an idea how to solve the issue?
No

**Comment by nbari** [comment] 2020-05-04 15:07
Same issue here using [FreeBSD 12.1](https://www.freebsd.org/releases/12.1R/announce.html) `HA-Proxy version 2.0.14 2020/04/02 `

I am using `unbound` forwarding queries to `consul`, using a configuration similar to:

```
resolvers consul
    nameserver dns0 10.0.0.3:53
    nameserver dns1 10.0.0.4:53
    nameserver dns2 10.0.0.5:53
    nameserver dns3 10.0.0.6:53
    nameserver dns4 10.0.0.7:53
    accepted_payload_size 8192
    hold valid 5s

backend test-consul
    default-server check fastinter 1s fall 3 rise 2 maxconn 30
    server-template srv 3 _test-consul._tcp.service.consul resolvers consul resolve-opts allow-dup-ip resolve-prefer ipv4
```
<img width="916" alt="Screenshot 2020-05-04 at 16 59 47" src="https://user-images.githubusercontent.com/364199/80980985-9dc5a300-8e29-11ea-9aa3-b9cbbadc676d.png">

**Comment by bedis** [comment] 2020-11-15 18:33
Hi,
I am able to reproduce this behavior.
Will now work on a fix.

**Comment by bedis** [comment] 2020-11-20 06:29
Quick update here: I have a patch for 2.2 and above, which I adapted to 2.0 and 2.1. That said, 1.8 and 1.9 are also affected and part of the patch must be rewritten for those versions.
@nbari since you're on HAProxy 2.0, I can send you the patch for your version and you can give it a try and confirm whether it helps or not :)  
@ivoronin same for you.

**Comment by nbari** [comment] 2020-11-20 12:33
hi @bedis thanks for your time on this 👍, I upgraded to `HA-Proxy version 2.2.5-34b2b10` so that should be fine from my side.

**Comment by bedis** [comment] 2020-11-22 18:26
Here you go:
[0001-BUG-MINOR-dns-new-callback-to-properly-handle-SRV-re.patch.txt](https://github.com/haproxy/haproxy/files/5580000/0001-BUG-MINOR-dns-new-callback-to-properly-handle-SRV-re.patch.txt)

Note that it's not the definitive one, I need to validate some corner cases.

**Comment by nbari** [comment] 2021-02-01 15:23
Any chance to include this in `2.2.9`?

**Comment by capflam** [comment] 2021-02-01 15:32
This patch was not merged at all and I don't really know why. @bedis, what is the status of this patch ?

**Comment by capflam** [comment] 2021-02-11 10:32
@bedis, ping ?

**Comment by capflam** [comment] 2021-02-25 08:35
FYI, I finally push the proposed patch. For now it was backported to 2.3

**Comment by capflam** [comment] 2021-03-01 11:50
Now backported as far as 2.0.

**Closed as completed by capflam** 2021-03-01 11:50 UTC
Labels: type: bug, subsystem: dns, status: fixed
