### ISSUE TITLE
incorrect use of "len" parameter on http-request capture req.hdr(User-Agent)

### ISSUE THREAD

**Issue by thomaswieland** [haproxy/haproxy#794] opened 2020-08-04 11:51 UTC
I am using the "http-request capture" directive as described in the docs: https://www.haproxy.com/documentation/hapee/latest/onepage/#4.2-capture%20request%20header

Expected behaviour: 
When setting "`http-request capture req.hdr(User-Agent) len 50`" I want to have logged "50 characters, beginning from position 0" (left end of the line).

Observed behaviour:
I get "50 characters, beginning from position 50".

Conclusion: It seems like the "len" parameter is not only interpreted for the "num of characters", but also for the starting position.

please find below my haproxy.cfg:

```
global
    daemon
    maxconn 256
    ssl-server-verify none
    tune.ssl.default-dh-param 2048
    log stdout daemon

    defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

frontend website
    bind :8080
    http-request capture req.hdr(x-forwarded-client-cert) len 58
    http-request capture req.hdr(User-Agent) len 50
    option httplog
    log global
    default_backend drm-service
    
backend drm-service
    server backend drm-service:8080
```

**Comment by TimWolla** [comment] 2020-08-04 11:57
I'm unable to reproduce the issue with your example config and:

```
HA-Proxy version 2.3-dev2-1f927d-2 2020/07/31 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64
```

See:
```
00000002:website.accept(0004)=0010 from [127.0.0.1:48550] ALPN=<none>
00000002:website.clireq[0010:ffffffff]: GET / HTTP/1.1
00000002:website.clihdr[0010:ffffffff]: host: localhost:8080
00000002:website.clihdr[0010:ffffffff]: accept-encoding: gzip, deflate
00000002:website.clihdr[0010:ffffffff]: accept: */*
00000002:website.clihdr[0010:ffffffff]: user-agent: aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggg
00000002:drm-service.srvrep[0010:0011]: HTTP/1.1 404 Not Found
00000002:drm-service.srvhdr[0010:0011]: content-type: text/html
00000002:drm-service.srvhdr[0010:0011]: date: Tue, 04 Aug 2020 11:55:49 GMT
00000002:drm-service.srvhdr[0010:0011]: server: ECS (dcb/7F16)
00000002:drm-service.srvhdr[0010:0011]: content-length: 345
00000002:drm-service.srvcls[0010:0011]
00000002:drm-service.clicls[0010:0011]
00000002:drm-service.closed[0010:0011]
<30>Aug  4 13:55:49 *snip* haproxy[13659]: 127.0.0.1:48550 [04/Aug/2020:13:55:49.309] website drm-service/backend 0/0/98/98/196 404 482 - - ---- 1/1/0/0/0 0/0 {|aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee} "GET / HTTP/1.1"
```

Also: Please make sure to fill in the full issue template when reporting a Bug.

**Comment by thomaswieland** [comment] 2020-08-04 13:46
Hello Tim,

I am sorry for missing the issue template, my bad. Also, I double-checked when I saw your version number (2.3-dev), which one I run, and its 2.2.1 (lts). 
```
$ haproxy -v
HA-Proxy version 2.2.1 2020/07/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.1.html
```
If its already fixed in 2.3 I will then try to upgrade soon. I will hence close this issue. Thanks, and sorry again for the unnecessary work. best regards!

**Comment by TimWolla** [comment] 2020-08-04 13:52
> If its already fixed in 2.3 I will then try to upgrade soon.

Hey, wait, not that fast! There's a reason there's a -dev in there. Can you please give a full `haproxy -vv` (note the duplicate `v`)?

**Comment by TimWolla** [comment] 2020-08-04 13:54
And before I forget: You *should* update. But not to 2.3.something, but to 2.2.2: http://www.haproxy.org/bugs/bugs-2.2.1.html

**Comment by thomaswieland** [comment] 2020-08-04 14:00
```
$ haproxy -vv
HA-Proxy version 2.2.1 2020/07/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.1.html
Running on: Linux 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue May 26 15:05:43 EDT 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=24).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```
this was the version I was running. I am currently pulling "haproxy:latest" from dockerhub, which contains 2.2.2 according to https://hub.docker.com/layers/haproxy/library/haproxy/latest/images/sha256-a1e144fa553f4d3edf2d2f0885615c6ad7a15454bc46d2b76319c532d99b9074?context=explore

**Comment by TimWolla** [comment] 2020-08-04 15:37
I'm afraid, but I am not able to reproduce the issue on 2.2.1 either. Neither in Docker, nor manually compiled:

```
$ ./haproxy -vv
HA-Proxy version 2.2.1 2020/07/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.1.html
Running on: Linux 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 5.4.0 20160609

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

$ ./haproxy -d -f ./crasher.cfg
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
Using epoll() as the polling mechanism.
<29>Aug  4 17:34:21 haproxy[17921]: Proxy website started.
00000000:website.accept(0004)=0010 from [127.0.0.1:56582] ALPN=<none>
00000000:website.clireq[0010:ffffffff]: GET / HTTP/1.1
00000000:website.clihdr[0010:ffffffff]: host: localhost:8080
00000000:website.clihdr[0010:ffffffff]: accept-encoding: gzip, deflate
00000000:website.clihdr[0010:ffffffff]: accept: */*
00000000:website.clihdr[0010:ffffffff]: user-agent: aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggg
00000000:drm-service.srvrep[0010:0011]: HTTP/1.1 404 Not Found
00000000:drm-service.srvhdr[0010:0011]: content-type: text/html
00000000:drm-service.srvhdr[0010:0011]: date: Tue, 04 Aug 2020 15:34:23 GMT
00000000:drm-service.srvhdr[0010:0011]: server: ECS (dcb/7FA6)
00000000:drm-service.srvhdr[0010:0011]: content-length: 345
00000000:drm-service.srvcls[0010:0011]
00000000:drm-service.clicls[0010:0011]
00000000:drm-service.closed[0010:0011]
<30>Aug  4 17:34:23 haproxy[17921]: 127.0.0.1:56582 [04/Aug/2020:17:34:23.229] website drm-service/backend 0/0/133/203/336 404 482 - - ---- 1/1/0/0/0 0/0 {|aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee} "GET / HTTP/1.1"
```

**Comment by thomaswieland** [comment] 2020-08-04 20:10
OK, I tested again with the latest haproxy container (2.2.2). Originally I was running under OpenShift (Kubernetes), so I tried to run it under plain docker daemon under Ubuntu 18.04 LTS. Both show the same behaviour:

Testing with a generic string like you above: runs fine. 
Testing with a real User-Agent (here: Edge/Chromium under Windows Server 2019): shows the bug as described.

## Console output:
### random string:
` curl -H "user-agent: aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffgggggggggghhhhhhhhhhhhh" http://localhost:8081/swagger`
`<30>Aug  4 20:06:17 haproxy[8]: 10.0.2.2:48080 [04/Aug/2020:20:06:14.613] website drm-service/backend 0/0/-1/-1/3004 503 222 - - SC-- 1/1/0/0/3 0/0 {|aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee} "GET /swagger HTTP/1.1"`
### real header:
`curl -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52" http://localhost:8081/swagger`
`<30>Aug  4 20:06:05 haproxy[8]: 10.0.2.2:48068 [04/Aug/2020:20:06:02.899] website drm-service/backend 0/0/-1/-1/3002 503 222 - - SC-- 1/1/0/0/3 0/0 {|like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg} "GET /swagger HTTP/1.1"`

## version: 
root@0d3cbe713b26:/# haproxy -vv
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app

**Comment by lukastribus** [comment] 2020-08-04 20:16
Yes, that's what [req.hdr](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#7.3.6-req.hdr) does, it extracts *parts* of the header, delimited by commas. You need to use fhdr instead:

> The function considers any comma as a delimiter for distinct values. If full-line headers are desired instead, use req.fhdr().

In other words, this has nothing to do with `len`.

**Comment by TimWolla** [comment] 2020-08-04 20:21
With that from Lukas being said, there's an alternative configuration syntax if the only thing you want to capture is headers:

```
frontend foo
    capture request header User-Agent len 255
```

**Comment by thomaswieland** [comment] 2020-08-04 20:28
I re-read the page where I got the sample from: https://www.haproxy.com/documentation/hapee/latest/onepage/ and I did not come to the conclusion that this alternative syntax (capture request header User-Agent len 50) would be better then what I did. And I did not know the special syntax of req.hdr which takes the header apart by commas and interprets only the last occurence (this is what I understood now). So basically 
`User-Agent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52`
is the same as
```
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML
User-Agent:  like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52
```
I am sorry for mistakenly filing a bug, and apologize for the inconvenience caused. Nevertheless, have a great day!

**Comment by TimWolla** [comment] 2020-08-04 20:44
> I re-read the page where I got the sample from: https://www.haproxy.com/documentation/hapee/latest/onepage/ and I did not come to the conclusion that this alternative syntax (capture request header User-Agent len 50) would be better then what I did.

The link is for the enterprise version. As you use the regular Docker images this one is better suited (even if the differences should be minimal): http://cbonte.github.io/haproxy-dconv/2.2/configuration.html

> I am sorry for mistakenly filing a bug, and apologize for the inconvenience caused. Nevertheless, have a great day!

No need to apologize. Sometimes a configuration mistake indicates that the documentation can be clarified. Maybe the comma gotcha should be made more prominent in the documentation for `req.hdr`. It only appears fairly late within a long paragraph.

I'll be closing the issue at this point, having filed #796.

**Closed as completed** 2020-08-04 20:43 UTC
Labels: type: bug, status: works as designed
