### ISSUE TITLE
Unable to allocate SSL session cache after consecutive reloads

### ISSUE THREAD

**Issue by blaaat** [haproxy/haproxy#800] opened 2020-08-06 05:44 UTC
## Output of `haproxy -vv` and `uname -a`

```

HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-39)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

````

```
Linux haproxy1-xxx.xxx.nl 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
#
# /etc/haproxy/haproxy.cfg
#

#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
mailers alertmailers
  mailer mail9 xxx:587
  mailer mail10 xxx:587

global
  # to have these messages end up in /var/log/haproxy.log you will
  # need to:
  #
  # 1) configure syslog to accept network log events.  This is done
  #    by adding the '-r' option to the SYSLOGD_OPTIONS in
  #    /etc/sysconfig/syslog
  #
  # 2) configure local2 events to go to the /var/log/haproxy.log
  #   file. A line like the following can be added to
  #   /etc/sysconfig/syslog
  #
  #    local2.*                       /var/log/haproxy.log
  #
  tune.bufsize 32768
  chroot      /var/lib/haproxy
  pidfile     /var/run/haproxy.pid
  maxconn     20000   # See also: ulimit -n
  user        haproxy
  group       haproxy
  daemon
  tune.ssl.default-dh-param	2048
  tune.ssl.cachesize 5000000

  ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA

  # turn on stats unix socket
  stats socket /var/lib/haproxy/stats.sock mode 600 level admin
  stats timeout 2m

#---------------------------------------------------------------------
# common defaults that all the 'frontend' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------

defaults
  mode    http
  log     global
  option  dontlognull
  option  redispatch
  maxconn 20000
  retries                   3
  timeout queue             2m
  timeout connect           10s
  timeout client            5m
  timeout server            30m
  timeout check             20s
  email-alert mailers alertmailers
  email-alert from hosting@xxx.nl
  email-alert to hosting@xxx.nl

#---------------------------------------------------------------------
# HAProxy statistics backend
#---------------------------------------------------------------------
listen haproxy-monitoring
  bind 	  *:8888
  mode    http
  stats   enable
  stats   show-legends
  stats   refresh           20s
  stats   uri               /
  stats   realm             Haproxy\ Statistics
  stats   auth              monitor:745689
  stats   admin             if TRUE

frontend all-web--haproxy1-yyy.xxx.nl
	bind    1.2.3.4:80
	bind    1.2.3.4:443 ssl crt-list /etc/ssl/private/letsencrypt/cluster.crtlist alpn h2,http/1.1 no-sslv3
	bind    2A02:AA:BB:3:::80 transparent
	bind    2A02:AA:BB:3:::443 transparent ssl crt-list /etc/ssl/private/letsencrypt/cluster.crtlist alpn h2,http/1.1 no-sslv3
    acl assets path_beg /assets/ /image_cache /img_uploads/ /img_proxy/ /i/
    acl varnish_available nbsrv(cluster-varnish) ge 1
    acl letsencrypt-acl path_beg /.well-known/acme-challenge/

	capture request header Host len 32
	capture request header Referer len 64
	capture request header User-Agent len 128
	capture response header Location len 300
	log         127.0.0.1 local2
	option httplog
	http-request set-header X-Forwarded-Proto https if  { ssl_fc }
	http-request set-header X-Forwarded-Proto http  if !{ ssl_fc }
	http-request set-header X-Forwarded-HaProxy true

	use_backend letsencrypt-backend if letsencrypt-acl
    use_backend cluster-varnish if assets varnish_available

	default_backend           backend-web

frontend x2-api--haproxy1-yyy.xxx.nl
	bind    1.2.3.5:80
	bind    1.2.3.5:443 ssl crt-list /etc/ssl/private/letsencrypt/cluster.crtlist alpn h2,http/1.1 no-sslv3
    acl letsencrypt-acl path_beg /.well-known/acme-challenge/

	capture request header Host len 32
	capture request header Referer len 64
	capture request header User-Agent len 128
	capture response header Location len 300
	log         127.0.0.1 local2
	option httplog
	http-request set-header X-Forwarded-Proto https if  { ssl_fc }
	http-request set-header X-Forwarded-Proto http  if !{ ssl_fc }
	http-request set-header X-Forwarded-HaProxy-OA true

	use_backend letsencrypt-backend if letsencrypt-acl

	default_backend           x2-web


frontend rabbitmq-haproxy1-yyy.xxx.nl-1
  mode          tcp
  bind    :::5672  v4v6 transparent
  timeout client  3h
  default_backend           rabbitmq-cluster

frontend galera-haproxy1-yyy.xxx.nl
  mode    tcp
  bind    *:3306
  default_backend           galera-cluster

backend letsencrypt-backend
   server letsencrypt 6.4.5.3:6000

backend rabbitmq-cluster
  mode    tcp
  timeout server  3h
  balance roundrobin

    	server  rabbit1-yyy             10.0.0.60:5672 check
    	server  rabbit2-yyy             10.0.0.61:5672 check backup
    	server  rabbit3-yyy             10.0.0.62:5672 check backup

backend x2-web
	mode    http
	balance roundrobin
  option httpchk HEAD /status.php HTTP/1.1\r\nHost:www.xxx.net\r\nX-Forwarded-Proto:https
	option forwardfor
	option http-server-close

			server  uuu3.xxx.nl             10.0.0.72:8080 check


backend backend-web
  mode    http
  balance roundrobin
  cookie G_WEB insert
  option httpchk HEAD / HTTP/1.1\r\nHost:ee.xxx.nl
  option forwardfor
  option http-server-close

    	server  cc-web1.xxx.nl             10.0.0.68:80 cookie ccweb1 check
    	server  cc-web2.xxx.nl             10.0.0.69:80 cookie ccweb2 check

backend galera-cluster
  mode    tcp
  balance roundrobin
  option  httpchk

    	server  galera3-sv1.xxx.nl             10.0.0.65:3306 check port 9200 inter 5000 rise 3 fall 3 backup
    	server  galera3-sv4.xxx.nl             10.0.0.66:3306 check port 9200 inter 5000 rise 3 fall 3
    	server  galera3-sv5.xxx.nl             10.0.0.67:3306 check port 9200 inter 5000 rise 3 fall 3 backup

backend cluster-varnish
  mode    http
  balance roundrobin
  option httpchk HEAD / HTTP/1.1\r\nHost:ee.xxx.nl\r\nX-Forwarded-Proto:https
  option forwardfor
  option http-server-close
    	server  varnish1-yyy.xxx.nl             10.0.0.70:8081 check

```

## Steps to reproduce the behavior

1. crtlist has 315 names in it 
2. get some traffic on it
3. reload haproxy 
4. reload haproxy again within a couple of minutes

## Actual behavior

Second (or later) reloads fail; following errors in log: 

```
haproxy: [NOTICE] 217/182119 (1347) : New worker #1 (62358) forked
systemd: Reloading HAProxy Load Balancer.
haproxy: [ALERT] 217/182124 (62369) : Unable to allocate SSL session cache.
haproxy: [ALERT] 217/182124 (62369) : Unable to allocate SSL session cache.
haproxy: [ALERT] 217/182124 (62369) : Unable to allocate SSL session cache.
haproxy: [ALERT] 217/182124 (62369) : Fatal errors found in configuration.
systemd: haproxy.service: control process exited, code=exited status=1
systemd: Reload failed for HAProxy Load Balancer.

```
## Expected behavior

Reload haproxy

## Do you have any idea what may have caused this?

No, same problem exists in 2.1.3

## Do you have an idea how to solve the issue?

No

**Comment by wtarreau** [comment] 2020-08-06 08:28
I'm wondering if it couldn't be caused by too low values in /proc/sys/kernel/shm*. Maybe you have just enough to have one process but not two. Please try to halve your tune.ssl.cachesize to see if that addresses it, it would confirm the cause.

**Comment by blaaat** [comment] 2020-08-06 08:41
> I'm wondering if it couldn't be caused by too low values in /proc/sys/kernel/shm*. Maybe you have just enough to have one process but not two. Please try to halve your tune.ssl.cachesize to see if that addresses it, it would confirm the cause.

I initially had a cachesize of 1.000.000. (1/5th) configured; tried to higher this without any affect. Quick test with 50.000 appears to solve this issue. 

First reload works as expected; so I guess there is room for two processes. No clue about the workings; but it it possible that the cleanup of the first process takes some time?

**Comment by wtarreau** [comment] 2020-08-06 14:09
OK, useful info, thanks. The doc indicates that an entry uses roughly 200 bytes of memory, so you were able to allocate 200 to 400 MB of RAM (1-2 processes) total. The older process stays until its connections are down, or the "hard-stop-after" timer is expired. So it would we well possible that you can handle 2 processes but not 3 for example.

**Comment by wtarreau** [comment] 2020-08-07 07:06
By the way, someone will correct me if I'm wrong, but I seem to remember that nowadays the SSL cache is almost unused, because recent TLS versions (1.2 and above IIRC) do not require any state to be stored anymore.

**Comment by lukastribus** [comment] 2020-08-07 07:24
That is not exactly true.

Apple does not implement TLS tickets at all, at least for <= TLSv1.2. And some users disable TLS tickets so they don't have to rotate the tls ticket keys to avoid breaking Forward Secrecy.

In TLSv1.3, I believe we have resumption based on both a statefull and a stateless method, I hope all clients implement the latter.

**Comment by blaaat** [comment] 2020-08-07 07:32
> OK, useful info, thanks. The doc indicates that an entry uses roughly 200 bytes of memory, so you were able to allocate 200 to 400 MB of RAM (1-2 processes) total. The older process stays until its connections are down, or the "hard-stop-after" timer is expired. So it would we well possible that you can handle 2 processes but not 3 for example.

At time of the error; this (small) vm still had 1G of free mem (and swap), which is way more than haproxy uses with this configuration.

Halving the tune.ssl.cachesize fixed the issue for me; thanks!

**Comment by wtarreau** [comment] 2020-08-12 08:54
Hi, I'm marking it as "works as designed" as I think it's the tag that best matches the situation. I'll close it, but feel free to reopen in case of future issue on this point.

**Closed as completed by wtarreau** 2020-08-12 08:54 UTC
Labels: type: bug, status: works as designed
