### ISSUE TITLE
Websockets over HTTP/2 failing with golang backend

### ISSUE THREAD

**Issue by thomas-kaltenbach** [haproxy/haproxy#1402] opened 2021-10-01 09:26 UTC
### Detailed Description of the Problem

We are running HAProxy as loadbalancer in front of cloud foundry environments. HAProxy communicates with the component `Gorouter`. Repo: https://github.com/cloudfoundry/gorouter
Gorouter handles http requests and websocket connections.

Currently we are trying to enable http/2. We noticed that when we activate h2 for the backend connection the websockets are failing and haproxy returns `502 Bad Gateway`. In the accesslog we see the termination state `SH--`.

HAProxy debug logs:
```
haproxy  | 00000003:gorouter.clireq[001e:ffffffff]: GET / HTTP/1.1
haproxy  | 00000003:gorouter.clihdr[001e:ffffffff]: host: localhost:4401
haproxy  | 00000003:gorouter.clihdr[001e:ffffffff]: connection: Upgrade
haproxy  | 00000003:gorouter.clihdr[001e:ffffffff]: upgrade: websocket
haproxy  | 00000003:gorouter.clihdr[001e:ffffffff]: sec-websocket-version: 13
haproxy  | 00000003:gorouter.clihdr[001e:ffffffff]: sec-websocket-key: qZ1ZY4i43G1UEji613DW8g==
haproxy  | 00000003:gorouter-backends.srvcls[001e:001f]
haproxy  | 00000003:gorouter-backends.clicls[001e:001f]
haproxy  | 00000003:gorouter-backends.closed[001e:001f]
```

### Expected Behavior

Downgrade the connection to http1.1 if websockets over http/2 report a protocol_error.

### Steps to Reproduce the Behavior

1. run haproxy > 2.4
2. clone https://github.com/thomas-kaltenbach/golang-http2-example (as fake gorouter)
3. run command `go run main.go`
4. open `websocat wss://localhost:4401`

### Do you have any idea what may have caused this?

I debugged the behaviour at the gorouter and I noticed that the request doesn't reach the gorouter coding. Therefore I enabled the golang verbose logging and I could see the problem:

Golang logs:
```
2021/10/01 11:08:58 http2: server: client 127.0.0.1:54449 said hello
2021/10/01 11:08:58 http2: Framer 0xc0002980e0: wrote WINDOW_UPDATE len=4 (conn) incr=983041
2021/10/01 11:08:58 http2: Framer 0xc0002980e0: read SETTINGS len=12, settings: ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=100
2021/10/01 11:08:58 http2: server read frame SETTINGS len=12, settings: ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=100
2021/10/01 11:08:58 http2: server processing setting [ENABLE_PUSH = 0]
2021/10/01 11:08:58 http2: server processing setting [MAX_CONCURRENT_STREAMS = 100]
2021/10/01 11:08:58 http2: Framer 0xc0002980e0: wrote SETTINGS flags=ACK len=0
2021/10/01 11:08:58 http2: Framer 0xc0002980e0: read SETTINGS flags=ACK len=0
2021/10/01 11:08:58 http2: server read frame SETTINGS flags=ACK len=0
2021/10/01 11:08:58 http2: Framer 0xc0002980e0: read HEADERS flags=END_HEADERS stream=1 len=118
2021/10/01 11:08:58 http2: decoded hpack field header field ":method" = "CONNECT"
2021/10/01 11:08:58 http2: decoded hpack field header field ":scheme" = "https"
2021/10/01 11:08:58 http2: decoded hpack field header field ":authority" = "localhost:4401"
2021/10/01 11:08:58 http2: decoded hpack field header field ":path" = "/"
2021/10/01 11:08:58 http2: decoded hpack field header field ":protocol" = "websocket"
2021/10/01 11:08:58 http2: decoded hpack field header field "sec-websocket-version" = "13"
2021/10/01 11:08:58 http2: decoded hpack field header field "sec-websocket-key" = "awAMpVvvxd4+QugLH68vyA=="
2021/10/01 11:08:58 http2: invalid pseudo headers: invalid pseudo-header ":protocol"
2021/10/01 11:08:58 http2: Framer 0xc0002980e0: wrote RST_STREAM stream=1 len=4 ErrCode=PROTOCOL_ERROR
```
Golang can't handle websockets over http/2. https://github.com/golang/go/issues/32763

### What is your configuration?

```haproxy
listen gorouter
	mode http
	bind *:4401 ssl crt-list /etc/ssl/crt-list  ca-file /etc/ssl/ca-certificates.crt verify none alpn h2,http1.1
	log global
	option httplog

	default_backend gorouter-backends

backend gorouter-backends
    mode http
    balance roundrobin
	server webapp localhost:8000 ssl verify none alpn h2,http1.1
```

### Output of `haproxy -vv`

I run locally haproxy docker haproxy:2.5-dev8 same at haproxy:latest

```
haproxy  | [NOTICE]   (1) : haproxy version is 2.5-dev8-538f3e0
haproxy  | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
haproxy  | Note: setting global.maxconn to 524262.
haproxy  | Available polling systems :
haproxy  |       epoll : pref=300,  test result OK
haproxy  |        poll : pref=200,  test result OK
haproxy  |      select : pref=150,  test result FAILED
haproxy  | Total: 3 (2 usable), will use epoll.
haproxy  | 
haproxy  | Available filters :
haproxy  |      [SPOE] spoe
haproxy  |      [CACHE] cache
haproxy  |      [FCGI] fcgi-app
haproxy  |      [COMP] compression
haproxy  |      [TRACE] trace
haproxy  | Using epoll() as the polling mechanism.
haproxy  | [NOTICE]   (1) : New worker #1 (8) forked
```

**Comment by capflam** [comment] 2021-10-01 13:00
Duplicate of #1364

**Closed as completed** 2021-10-27 10:17 UTC
Labels: type: bug, status: duplicate
