### ISSUE TITLE
2.2.0 and 2.2.1 segfault in snr_update_srv_status when SRV record is removed

### ISSUE THREAD

**Issue by cventers** [haproxy/haproxy#775] opened 2020-07-23 21:00 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.1 2020/07/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.1.html
Running on: Linux 2.6.32-754.30.2.el6.x86_64 #1 SMP Wed Jun 10 11:14:37 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_THREAD=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO= USE_NS=

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY -TFO -NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.0.1e-fips 11 Feb 2013
Running on OpenSSL version : OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.5
Built with zlib version : 1.2.3
Running on zlib version : 1.2.3
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 7.8 2008-09-05
Running on PCRE version : 7.8 2008-09-05
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.4.7 20120313 (Red Hat 4.4.7-23)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app

Linux REDACTED 2.6.32-754.30.2.el6.x86_64 #1 SMP Wed Jun 10 11:14:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

Redactions are numbered by unique token to hopefully show which values might or might not be the same.

```
global
        maxconn                 10000
        stats socket    /var/run/haproxy.stat mode 600 level admin
        log                             /var/run/haproxy.log local0 info
        pidfile                 /var/run/haproxy.pid
        user                    haproxy
        group                   haproxy
#       daemon

resolvers internal
        accepted_payload_size   8192
        nameserver                              REDACT1 REDACT2:54
        nameserver                              REDACT3 REDACT4:54
        timeout resolve                 1s
        timeout retry                   1s
        hold other                              30s
        hold refused                    30s
        hold nx                                 30s
        hold timeout                    30s
        hold valid                              10s
        hold obsolete                   30s

defaults
        timeout                                 connect 10s
        timeout                                 client 30s
        timeout                                 server 30s
        log                                             /var/run/haproxy.log local1 info

frontend stats
        mode                                    http
        bind                                    REDACT2:8404
        stats                                   enable
        stats                                   uri /
        stats                                   refresh 5s
        option                                  httplog

listen mxi
        bind                                    REDACT2:25000
        mode                                    tcp
        balance                                 roundrobin
        description                             REDACT5
        option                                  tcplog
        server-template                 mx 1-2 REDACT6 resolvers internal check

listen mxb
        bind                                    REDACT7:25000
        mode                                    tcp
        balance                                 roundrobin
        description                             REDACT8
        option                                  tcplog
        server-template                 mx 1-2 REDACT9 resolvers internal check
```

## Steps to reproduce the behavior

1. Start haproxy when the DNS server is returning two SRV & IP address answers for the SRV query
2. After haproxy applies the two SRV records to the server-template, remove one of the SRV records
3. Wait for haproxy to recognize the change

## Actual behavior

Segmentation fault. My custom RPM debuginfo did not correctly capture the source tree; however the source is unpatched and `srv/server.c:3734` corresponds to the `switch` statement seen in `snr_update_srv_status` of 2.2.1.

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5e7f700 (LWP 13440)]
snr_update_srv_status (s=0x9f00a0, has_no_ip=1) at src/server.c:3734
3734    src/server.c: No such file or directory.
        in src/server.c
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-24.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 nss-softokn-freebl-3.44.0-6.el6_10.x86_64 openssl-1.0.1e-58.el6_10.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) print resolution
$1 = (struct dns_resolution *) 0x0
```

## Expected behavior

haproxy either removes the server record for the SRV answer no longer present, or puts it into maintenance mode.

## Do you have any idea what may have caused this?

No.

## Do you have an idea how to solve the issue?

No.

**Comment by cventers** [comment] 2020-07-23 21:18
Here's a little more context (with a few redactions).

```
(gdb) print *s
$1 = {obj_type = OBJ_TYPE_SERVER, next_state = SRV_ST_RUNNING, cur_state = SRV_ST_RUNNING, next_admin = SRV_ADMF_HMAINT, cur_admin = 0, use_ssl = 0 '\000', pp_opts = 0, next = 0x0,
  cklen = 0, rdr_len = 0, cookie = 0x0, rdr_pfx = 0x0, proxy = 0x9ed500, mux_proto = 0x0, served = 0, cur_sess = 0, maxconn = 0, minconn = 0, nbpend = 0, queue_idx = 0, maxqueue = 0,
  sess_per_sec = {curr_sec = 0, curr_ctr = 0, prev_ctr = 0}, counters = {conn_max = 0, cum_conn = 0, cum_sess = 0, cum_lbconn = 0, last_sess = 0, cps_max = 0, sps_max = 0,
    nbpend_max = 0, cur_sess_max = 0, bytes_in = 0, bytes_out = 0, comp_in = 0, comp_out = 0, comp_byp = 0, denied_req = 0, denied_resp = 0, connect = 0, reuse = 0, failed_conns = 0,
    failed_resp = 0, cli_aborts = 0, srv_aborts = 0, retries = 0, redispatches = 0, failed_rewrites = 0, internal_errors = 0, failed_checks = 1, failed_hana = 0, down_trans = 1,
    q_time = 0, c_time = 0, d_time = 0, t_time = 0, qtime_max = 0, ctime_max = 0, dtime_max = 0, ttime_max = 0, p = {http = {cum_req = 0, comp_rsp = 0, rps_max = 0, rsp = {0, 0, 0,
          0, 0, 0}, cache_lookups = 0, cache_hits = 0}}}, pendconns = {b = {0x0, 0x0}}, actconns = {n = 0x9f0268, p = 0x9f0268}, idle_conns = 0x9f2920, safe_conns = 0x9f29b0,
  available_conns = 0x9f2890, pool_purge_delay = 5000, low_idle_conns = 0, max_idle_conns = 4294967295, curr_idle_conns = 0, curr_idle_nb = 0, curr_safe_nb = 0, curr_used_conns = 0,
  max_used_conns = 0, est_need_conns = 0, curr_idle_thr = 0x9f2a40, next_takeover = 0, max_reuse = -1, idle_node = {node = {branches = {b = {0x0, 0x0}}, node_p = 0x0, leaf_p = 0x0,
      bit = 0, pfx = 0}, key = 0}, warmup = 0x0, conn_src = {opts = 0, iface_len = 0, iface_name = 0x0, sport_range = 0x0, source_addr = {ss_family = 0,
      __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}, tproxy_addr = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}, bind_hdr_name = 0x0,
    bind_hdr_len = 0, bind_hdr_occ = 0}, track = 0x0, trackers = 0x0, tracknext = 0x0, trackit = 0x0, consecutive_errors = 0, consecutive_errors_limit = 10, observe = 0, onerror = 2,
  onmarkeddown = 0, onmarkedup = 0, flags = 2048, slowstart = 0, id = 0x9f0df0 "mx2", iweight = 1, uweight = 5, cur_eweight = 80, wscore = 0, next_eweight = 80, rweight = 0,
  cumulative_weight = 16, npos = 53, lpos = 0, lb_node = {node = {branches = {b = {0x9ef648, 0x9f0488}}, node_p = 0x0, leaf_p = 0x9ee358, bit = -1, pfx = 0}, key = 13819},
  lb_tree = 0x9ee358, next_full = 0x0, lb_nodes_tot = 0, lb_nodes_now = 0, lb_nodes = 0x0, netns = 0x0, addr = {ss_family = 2,
    __ss_padding = "\000\000\n\024<\025", '\000' <repeats 111 times>, __ss_align = 0}, xprt = 0x877a40, svc_port = REDACT, down_time = 0, last_change = 1595538857, puid = 2,
  tcp_ut = 0, do_check = 1, do_agent = 0, check = {obj_type = OBJ_TYPE_CHECK, sess = 0x0, vars = {head = {n = 0x9f0590, p = 0x9f0590}, scope = SCOPE_CHECK, size = 0, rwlock = 0},
    xprt = 0x877a40, cs = 0x0, bi = {size = 16384, area = 0xa50c10 "", data = 0, head = 0}, bo = {size = 16384, area = 0xa54c20 "", data = 0, head = 0}, task = 0xa64ee0, start = {
      tv_sec = 0, tv_usec = 0}, duration = 0, status = 6, code = 0, port = REDACT, desc = '\000' <repeats 127 times>, use_ssl = 0 '\000', send_proxy = 0, tcpcheck_rules = 0x9eea28,
    current_step = 0x0, inter = 2000, fastinter = 0, downinter = 0, result = CHK_RES_PASSED, state = 6, health = 4, rise = 2, fall = 3, type = -1879048192, server = 0x9f00a0,
    proxy = 0x9ed500, argv = 0x0, envp = 0x0, curpid = 0x0, addr = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}, wait_list = {tasklet = 0xa58c30,
      events = 0}, sni = 0x0, alpn_str = 0x0, alpn_len = 0, mux_proto = 0x0, via_socks4 = 0}, agent = {obj_type = OBJ_TYPE_CHECK, sess = 0x0, vars = {head = {n = 0x0, p = 0x0},
      scope = SCOPE_SESS, size = 0, rwlock = 0}, xprt = 0x877a40, cs = 0x0, bi = {size = 0, area = 0x0, data = 0, head = 0}, bo = {size = 0, area = 0x0, data = 0, head = 0},
    task = 0x0, start = {tv_sec = 0, tv_usec = 0}, duration = 0, status = 1, code = 0, port = 0, desc = '\000' <repeats 127 times>, use_ssl = 0 '\000', send_proxy = 0,
    tcpcheck_rules = 0x0, current_step = 0x0, inter = 2000, fastinter = 0, downinter = 0, result = CHK_RES_UNKNOWN, state = 0, health = 1, rise = 1, fall = 1, type = 0,
    server = 0x9f00a0, proxy = 0x9ed500, argv = 0x0, envp = 0x0, curpid = 0x0, addr = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}, wait_list = {
      tasklet = 0x0, events = 0}, sni = 0x0, alpn_str = 0x0, alpn_len = 0, mux_proto = 0x0, via_socks4 = 0}, dns_requester = 0xa38920, resolvers_id = 0x9f0dd0 "internal",
  resolvers = 0x9e7890, lastaddr = 0x0, dns_opts = {family_prio = 10, pref_net = {{family = 0, addr = {in4 = {s_addr = 0}, in6 = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>,
              __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}, mask = {in4 = {s_addr = 0}, in6 = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>,
              __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}}, {family = 0, addr = {in4 = {s_addr = 0}, in6 = {__in6_u = {
              __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}, mask = {in4 = {s_addr = 0}, in6 = {__in6_u = {
              __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}}, {family = 0, addr = {in4 = {s_addr = 0}, in6 = {
            __in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}, mask = {in4 = {s_addr = 0}, in6 = {__in6_u = {
              __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}}, {family = 0, addr = {in4 = {s_addr = 0}, in6 = {
            __in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}, mask = {in4 = {s_addr = 0}, in6 = {__in6_u = {
              __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}}, {family = 0, addr = {in4 = {s_addr = 0}, in6 = {
            __in6_u = {__u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}, mask = {in4 = {s_addr = 0}, in6 = {__in6_u = {
              __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}}}}, pref_net_nb = 0, accept_duplicate_ip = 0,
    ignore_weight = 0}, hostname_dn_len = 25, hostname_dn = 0x7fffe002c9a0 "REDACT", hostname = 0x7fffe002c920 "REDACT",
  init_addr = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}, init_addr_methods = 0, log_proto = SRV_LOG_PROTO_LEGACY, sni_expr = 0x0, ssl_ctx = {
    ctx = 0x0, reused_sess = 0x0, ciphers = 0x0, options = 0, verify = 0, methods = {flags = 0, min = 0 '\000', max = 0 '\000'}, verify_host = 0x0, ca_file = 0x0, crl_file = 0x0,
    client_crt = 0x0, sni = 0x0, npn_str = 0x0, npn_len = 0}, srvrq = 0x9efff0, lock = 4294967300, conf = {file = 0x0, id = {node = {branches = {b = {0x9efdd0, 0x9f0c10}},
        node_p = 0x9eebd8, leaf_p = 0x9f0c11, bit = 1, pfx = 0}, key = 2}, name = {node = {branches = {b = {0x9efdf8, 0x9f0c38}}, node_p = 0x9eebe8, leaf_p = 0x9f0c39, bit = 22,
        pfx = 0}, {<No data fields>}, key = 0x9f0df0}, line = 0}, tmpl_info = {prefix = 0x0, nb_low = 0, nb_high = 0}, op_st_chg = {duration = 0, status = -1, code = -1,
    reason = '\000' <repeats 127 times>}, adm_st_chg_cause = '\000' <repeats 47 times>, socks4_addr = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}}
(gdb) print *s->dns_requester
$2 = {owner = 0x9f00a0, resolution = 0x0, requester_cb = 0x4ff9e0 <snr_resolution_cb>, requester_error_cb = 0x4ff970 <snr_resolution_error_cb>, list = {n = 0xa38718, p = 0xa38718}}
```

**Comment by jmagnin** [comment] 2020-07-26 09:50
Can you tell which DNS server you use to service SRV records. I've had a look at your problem to try and reproduce it, only to face a different issue (srv records not working at all in my case), introduced by commit 13a9232ebc63fdf357ffcf4fa7a1a5e77a1eac2b

**Comment by cventers** [comment] 2020-07-26 12:38
PowerDNS Authoritative Server

**Comment by jmagnin** [comment] 2020-07-26 13:57
Thanks, I can reproduce it with PowerDNS.

**Comment by jmagnin** [comment] 2020-07-26 16:25
From what I understood, before 13a9232 haproxy would get the list of A records for a given SRV record, and associate each A record to one of the server-template'd server lines. From this point each server line resolves its own A record. After 13a9232 we get this from the Additional records in the DNS response to be more efficient, but as far as I understand each server line is no longer responsible for resolving its A record and i'm wondering if it's the reason for resolution being NULL. Maybe @bedis would know better.

with the attached patch when I remove one of the entries in the SRV record, the associated server line goes to maintenance.
[srv_segfault.txt](https://github.com/haproxy/haproxy/files/4977917/srv_segfault.txt)

**Comment by cventers** [comment] 2020-07-26 16:37
In my scenario, the SRV query returned two SRV answers, each with a distinct weight. Each SRV answer also had a corresponding A record in additional answers.

If the SRV query returned only one SRV answer but multiple A’s for the SRV, it would not be easy to apply weights to the different A’s.

**Comment by jmagnin** [comment] 2020-07-28 12:00
I discussed the issue with @bedis today and sent a patch to the mailing list for a fix.

**Comment by bedis** [comment] 2020-07-28 12:57
patch validated :+1:

**Comment by capflam** [comment] 2020-07-30 08:34
Backported now

**Closed as completed by capflam** 2020-07-30 08:34 UTC
Labels: type: bug, severity: major, subsystem: dns, status: fixed
