### ISSUE TITLE
Spin loop upon exhausting ephemeral port numbers for backend connections

### ISSUE THREAD

**Issue by brian-pane** [haproxy/haproxy#579] opened 2020-04-11 18:56 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.14 2020/04/02 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_TFO=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

Linux [hostname_redacted] 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
backend [name]
  fullconn 250000
  default-server pool-purge-delay 30s
  http-request set-header X-Forwarded-Proto https
  server [name] [ip_address]:443 ssl verify required ca-file /haproxy/run/[redacted] check inter 3s fall 3 rise 1
```
This HAProxy server was an edge proxy that forwarded all its requests to a single backend VIP at an origin datacenter. (Note: there used to be multiple backend `server`s but we consolidated everything behind a single VIP. Thus the `fullconn 250000` is too large - with just one source IP address on the HAProxy host and one destination IP address for the backend, it's impossible to create that many connections. I think that enabled HAProxy to get into the state described below, but there are other, more common situations that could have caused the same exhaustion of ephemeral TCP port numbers: old connections spending too long in `TIME_WAIT`, for example.)

## Steps to reproduce the behavior

We saw this on several production servers under high load. I don't have a synthetic test case that recreates it. But the key ingredients are: a combination of high backend response time and high request rate that results in the number of concurrent connections to one backend IP address growing to ~50,000.

## Actual behavior

Each host running HAProxy hit 100% CPU utilization on 64 cores. I was able to log in to one of the HAProxy hosts to grab the output of `perf top`, which showed most of the time being spent in the kernel:
<img width="741" alt="Profile" src="https://user-images.githubusercontent.com/24847780/79052331-97f1ee80-7bea-11ea-95a4-d76ac7d5aa96.png">

(Under normal circumstances, these hosts would be spending most of their CPU time in TLS processing.)

## Expected behavior

Probably return an HTTP 503 response to the client when it can't find an available backend connection and can't allocate a new one. But mostly: don't use 100% CPU or leak file descriptors. (More about the file descriptors in the next section.)

## Do you have any idea what may have caused this?

It appears to have been triggered by running out of ephemeral TCP port numbers for the HAProxy host's connections to the backend server. On the host running HAProxy, the distribution of TCP states for connections to that backend server looked like this:
```
  45329 CLOSE_WAIT
   7901 ESTABLISHED
    737 LAST_ACK
     30 SYN_SENT
```
Those add up to just a few less than the system limit on the total number of ephemeral TCP ports per 4-tuple. 

Based on the `CLOSE_WAIT`s, though, I suspect the problem is that, once the host ran out of ephemeral port numbers for connections to the backend server, HAProxy got into a state where it wan't able to create new backend connections (which was expected) but also stopped closing the file descriptors for closed backend connections (which seems like a bug).

## Do you have an idea how to solve the issue?

My theory is that there may be a bug in the error handling when various socket operations fail for backend connections. (Unfortunately I wasn't able to get a stack trace or core dump before I had to restart the HAProxy process.)

**Comment by lukastribus** [comment] 2020-04-11 20:46
I think it's more likely that that the CLOSE_WAIT's and the subsequent source port exhaustion are caused by the the spinning loop in haproxy, instead of the other way around.

**Comment by wtarreau** [comment] 2020-04-23 18:20
Here the CPU is spent entirely in the kernel: connect() takes longer and longer when source ports become scarce. With so many CLOSE_WAIT, each call takes ages to try to find one port. It's even possible it finds some from time to time by the way.

The question is how could we end up with asymmetric shutdowns to the backend without first disabling lingering then enforcing a close! Normally each connection to a server sets linger_risk on its FD to indicate that we must absolutely pass a setsockopt(SO_LINGER) on it before closing or shutting for writes, and the only situation where it's cleared is when we've received a shutdown from the other side. So apparently there's a case where something is missing.

@brian-pane I'm wondering, are you passing CONNECT requests to your backends, or maybe truncated POST payloads ? I'm wondering if that couldn't be what triggers it. But your server should respond and the connection should be turned to a TIME_WAIT at least, so that looks pretty fishy.

Do you have server-side timeouts at least ? Maybe these ones accumulate over time by lack of timeouts and occasional server-side connection drops ?

**Closed as completed** 2021-04-06 06:15 UTC
Labels: type: bug, status: feedback required

**Comment by capflam** [comment] 2021-04-06 06:20
Not enough info to work on it. It this issue is still relevant, please try the latest 2.0 release first.
