### ISSUE TITLE
Can not set the HTTP2 scheme to http when sending healthcheck GET queries.

### ISSUE THREAD

**Issue by gscorrea** [haproxy/haproxy#1222] opened 2021-04-14 01:27 UTC
HAPROXY
I need to send a HTTP2 GET request where the HEADER :scheme: is set to http (not https) and HEADER :authority: is the IP address of each server on the server line
 
````
frontend nrfs
    bind 10.10.10.1:80
    mode http
    acl nrf-52 dst 10.10.20.1
    acl nrf-56 dst 10.10.20.2
    acl nrf-61 dst 10.10.20.3
    use_backend rdm52-nrf if nrf-52 { path -i -m beg /nnrf-nfm/v1/nf-instances }
    use_backend rdm56-nrf if nrf-56 { path -i -m beg /nnrf-nfm/v1/nf-instances }
    use_backend rdm61-nrf if nrf-61 { path -i -m beg /nnrf-nfm/v1/nf-instances }

backend rdm52-nrf
    source 10.10.10.2
    option httpchk
    http-check send meth GET uri /nnrf-disc/v1/nf-instances ver HTTP/2 hdr :scheme http
    http-check expect rstatus (2|3|4)[0-9][0-9]
    server nrf52 10.10.20.1:80 check inter 2m downinter 2m proto h2
    server nrf61 10.10.20.3:80 check backup inter 2m downinter 2m proto h2
    server nrf56 10.10.20.2:80 check backup inter 2m downinter 2m proto h2

backend rdm61-nrf
    source 10.10.10.2
    option httpchk
    http-check send meth GET uri /nnrf-disc/v1/nf-instances ver HTTP/2 hdr :scheme http
    http-check expect rstatus (2|3|4)[0-9][0-9]
    server nrf61 10.10.20.3:80 check inter 2m downinter 2m proto h2
    server nrf56 10.10.20.2:80 check backup inter 2m downinter 2m proto h2
    server nrf52 10.10.20.1:80 check backup inter 2m downinter 2m proto h2

backend rdm56-nrf
    source 10.10.10.2
    option httpchk
    http-check send meth GET uri /nnrf-disc/v1/nf-instances ver HTTP/2 hdr :scheme http
    http-check expect rstatus (2|3|4)[0-9][0-9]
    server nrf56 10.10.20.2:80 check inter 2m downinter 2m proto h2
    server nrf61 10.10.20.3:80 check backup inter 2m downinter 2m proto h2
    server nrf52 10.10.20.1:80 check backup inter 2m downinter 2m proto h2
````

**Comment by capflam** [comment] 2021-04-14 07:18
If the issue is invalid, can we close it ?

**Comment by TimWolla** [comment] 2021-04-14 08:40
> If the issue is invalid, can we close it ?

This happens automatically if the “Question” issue template is selected and the issue author completely ignores any warnings that the issue tracker is not appropriate for questions.

For this reason I am closing the issue at this point. @gscorrea If you believe you found an actual bug, then please file a new issue using the “Bug Report” issue template. Make sure to fill in the issue template. If you just have a question, then use either the Mailing List or Discourse.

**Closed as completed by TimWolla** 2021-04-14 08:40 UTC
Labels: status: invalid

**Comment by capflam** [comment] 2021-04-14 09:41
Good to know. Thanks @TimWolla
