### ISSUE TITLE
Load State and server-state-file of Haproxy

### ISSUE THREAD

**Issue by DiscoveringWorld** [haproxy/haproxy#409] opened 2019-12-12 02:58 UTC
When I reload the service or reboot the VM, the state of the server is lost. So there is the way to ssave the states in a file and when the reload occur, the file will be state file will be read.

So I created a service that save the state each 3 sec. But I think it should come with Haproxy ? We should not have, as a user of the software, create a service in systemd to save the stats?

```
#!/bin/sh  
while true  
do 
 
#Execute the command to export the states
echo "show servers state" |nc -U /var/lib/haproxy/stats > /var/lib/haproxy/server-state
sleep 3  # each 3 sec export the state of each servers in a file.
done
```

**Comment by bricewge** [comment] 2022-09-07 10:14
This looks like a duplicate of issue #199.

**Comment by wtarreau** [comment] 2022-09-09 08:18
Indeed, I'm closing it as duplicate since we now have the link in the other issue.

**Closed as completed by wtarreau** 2022-09-09 08:18 UTC
Labels: status: duplicate, type: feature
