### ISSUE TITLE
Resolvers 'hold valid' doesn't override DNS TTL

### ISSUE THREAD

**Issue by sveniu** [haproxy/haproxy#239] opened 2019-08-29 11:26 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.5-1ppa1~bionic 2019/08/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-IlcC1x/haproxy-2.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```
```
Linux ip-192-168-10-141 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
resolvers dnsserver
    parse-resolv-conf
    resolve_retries        3
    timeout resolve   1000ms
    timeout retry     1000ms
    hold valid        1500ms
    hold refused      7000ms
    hold nx           7000ms
    hold timeout      7000ms
    hold other        7000ms
    hold obsolete     7000ms

defaults
    default-server init-addr none resolvers dnsserver weight 50 check inter 10s fastinter 2s fall 3 rise 20

listen mysrv
    server-template myservice 8 service.sd.example.com:80
```

## Steps to reproduce the behavior

1. Set DNS TTL for service.sd.example.com A records to 5 seconds.
2. Set haproxy.cfg `hold valid 1500ms`
3. Start haproxy.
4. Observe DNS lookup interval with `tcpdump -nttti eth0 dst port 53`

## Actual behavior
The DNS re-lookup frequency is 6 seconds (that is 4 x 1500 ms):
```
 00:00:00.000 192.168.10.141.51598 > 192.168.0.2.53: 36773+ A? service.sd.example.com. (61)
 00:00:06.033 192.168.10.141.50348 > 192.168.0.2.53: 61401+ A? service.sd.example.com. (61)
 00:00:06.018 192.168.10.141.60473 > 192.168.0.2.53: 36064+ A? service.sd.example.com. (61)
 00:00:06.030 192.168.10.141.45798 > 192.168.0.2.53: 12440+ A? service.sd.example.com. (61)
 00:00:06.023 192.168.10.141.38204 > 192.168.0.2.53: 58082+ A? service.sd.example.com. (61)
 00:00:06.021 192.168.10.141.37944 > 192.168.0.2.53: 20918+ A? service.sd.example.com. (61)
 00:00:06.021 192.168.10.141.41611 > 192.168.0.2.53: 18723+ A? service.sd.example.com. (61)
 00:00:06.019 192.168.10.141.50237 > 192.168.0.2.53: 61470+ A? service.sd.example.com. (61)
```

## Expected behavior

Expected 1500 ms between each DNS lookup.

## Do you have any idea what may have caused this?

The backend server's DNS A records have TTL 5 seconds. Any `hold valid` setting over 5 seconds works as it should. If `hold valid` is below 5 seconds, it seems that the DNS TTL has to lapse first, then the next `hold valid` will cause a re-lookup.

It is not certain that it is the DNS TTL that interferes, and the observed 5-second threshold might stem from elsewhere.

## Do you have an idea how to solve the issue?

No.

**Comment by bedis** [comment] 2019-09-10 06:06
Hi
HAProxy does not follow-up responses TTLs. There must be something else happening.
I'll try to reproduce your issue.
Can you confirm your DNS server is answering a real valid A record?

**Comment by bedis** [comment] 2019-09-10 07:42
I just gave a try with latest 2.0 code with your config (but with my local home made dns server) and I get the following frequency:
```
 00:00:01.501817 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
 00:00:00.000358 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
 00:00:01.501145 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
 00:00:00.000408 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
 00:00:01.502099 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
 00:00:00.000660 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
 00:00:01.501676 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
 00:00:00.000520 IP 127.0.0.1.15429 > 127.0.0.1.5300: UDP, length 35
```
There are 2 requests because first one is issued for AAAA, then HAProxy fails over to A

**Comment by bedis** [comment] 2019-09-10 07:45
note since my DNS server listen on port 5300, tcpdump does not seem able to parse the request content...

**Comment by frickenate** [comment] 2019-11-07 19:03
~~@bedis Does your statement of "HAProxy does not follow-up responses TTLs" mean that HAProxy completely ignores the TTL of the returned DNS records, and thus the `hold` configurations are guaranteed to take effect? The documentation for `hold` does not make this clear.~~

We found the source code indicating that the TTL is indeed ignored, and only the `hold` values are considered. Perfect.

**Comment by bedis** [comment] 2019-11-11 09:45
So `hold` timers will keep said status of said for given time.
Note that request frequency is driven by `timeout resolve` (which was not applied when status was `valid` as discussed in #345 )

So to expect 1500ms between 2 DNS lookup, set `timeout resolve` accordingly.

Can we close this issue?

**Comment by wtarreau** [comment] 2019-12-11 15:44
No response for one month, closing now.

**Closed as completed by wtarreau** 2019-12-11 15:44 UTC
Labels: type: bug, status: feedback required
