### ISSUE TITLE
[2.9, 2.9.1] haproxy won't connect to ipv4 protocol backend

### ISSUE THREAD

**Issue by lprimak** [haproxy/haproxy#2393] opened 2023-12-16 20:56 UTC
### Detailed Description of the Problem

The following services stopped working after upgrading to haproxy 2.9 from 2.8 (latest)
- Sonatype Nexus Repository
- Jenkins

There are no logs, just no response and a "service unavailable" page from haproxy

Looks like HTTP/2 backends work, but HTTP/1.1 backends don't

### Expected Behavior

Same as 2.8, working proxy

### Steps to Reproduce the Behavior

Not sure there is a "simple" way to reproduce

### Do you have any idea what may have caused this?

Something when calling HTTP/2 frontend into HTTP/1.1 backend

### What is your configuration?

```haproxy
https://github.com/lprimak/infra/blob/main/etc/haproxy.cfg

# Hope Website HAProxy Config

    global
        maxconn 256
        # Enable the HAProxy Runtime API - SSL reloads
        stats socket ipv4@localhost:9999 level admin expose-fd listeners
        crt-base "${HOME}/var/ssl-links"

    defaults
        mode http
        timeout connect 5s
        timeout client 50s
        timeout server 50s
        option forwardfor

    frontend main-web
        default_backend payara
        bind :::16380 v4v6
        bind :::16443 v4v6 ssl crt hope-fullchain.pem crt lp-fullchain.pem crt fl-fullchain.pem alpn h2,http/1.1

        # HTTP -> HTTPS redirection
        http-request redirect scheme https unless { ssl_fc }
        http-request set-header X-Forwarded-Proto https if { ssl_fc }

        # Redirect to static web site
        # starts with hope / lennyprimak
        acl static_website hdr_beg(host) -i hope.nyc lennypr www.lennypr
        # starts with a slash, and can have more slashes after, but nothing at the end
        acl is_root path_reg -i ^/+$
        redirect prefix https://www.hope.nyc.ny.us code 301 if static_website is_root

        # redirect apps root to about.html
        acl apps_website hdr_beg(host) -i apps.hope
        redirect location https://apps.hope.nyc.ny.us/about.html code 302 if apps_website is_root

        # Redirect FlowLogix Jenkins
        acl flowlogix_jenkins hdr_beg(host) -i jenkins.flowlogix
        redirect location https://jenkins.hope.nyc.ny.us code 301 if flowlogix_jenkins is_root

        # Redirect old me website bookmarks
        acl old_me_website hdr_beg(host) -i me.hope.nyc
        acl old_me_website hdr_beg(host) -i www.me.hope.nyc
        acl wellknown_path path_beg /.well-known
        redirect prefix https://www.hope.nyc.ny.us code 301 if old_me_website !wellknown_path

        # keep let's encrypt requests going
        acl letsencrypt-acl path_beg /.well-known/acme-challenge/
        use_backend payara if letsencrypt-acl

        # Payara 6
        acl payara-alt-acl hdr_beg(host) -i apps-alt
        use_backend payara-alt if payara-alt-acl

        # Payara admin server
        acl payara-admin-alt hdr_beg(host) -i admin-alt
        use_backend payara-admin-alt if payara-admin-alt
        acl payara-admin hdr_beg(host) -i admin
        use_backend payara-admin if payara-admin

        # Jenkins
        acl jenkins hdr_beg(host) -i jenkins
        use_backend jenkins if jenkins

        # Sonatype Nexus
        acl nexus hdr_beg(host) -i nexus
        use_backend nexus if nexus

        acl nexus-docker-public hdr_beg(host) -i docker-public
        use_backend nexus-docker-public if nexus-docker-public

        acl nexus-docker-private hdr_beg(host) -i docker-private
        use_backend nexus-docker-private if nexus-docker-private

    backend payara
        # HTTP/2 over clear text
        server server1 localhost:1180 maxconn 32
        # server server1 localhost:1181 maxconn 32 ssl alpn h2 verify none

    backend payara-alt
        server server1 localhost:1380 maxconn 32

    backend payara-admin
        server server1 localhost:1148 maxconn 32 ssl alpn h2 verify none

    backend payara-admin-alt
        server server1 localhost:1348 maxconn 32 ssl alpn h2 verify none

    backend jenkins
        timeout server 4m
        server server1 localhost:8088 maxconn 32
        # Blue Ocean currently doesn't work with HTTP/2 proxying
        # server server1 localhost:8081 maxconn 32 ssl alpn h2 verify none

    backend nexus
        server server1 ipv4@localhost:2181 maxconn 32
    backend nexus-docker-public
        http-request set-header X-Forwarded-Proto https
        server server1 ipv4@localhost:8023 maxconn 32
    backend nexus-docker-private
        http-request set-header X-Forwarded-Proto https
        server server1 ipv4@localhost:8024 maxconn 32
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.1-f72603c 2023/12/15 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.1.html
Running on: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64 x86_64
Build options :
  TARGET  = osx
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_ZLIB=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES -ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY -CRYPT_H -DEVICEATLAS -DL -ENGINE -EPOLL -EVPORTS +GETADDRINFO +KQUEUE -LIBATOMIC +LIBCRYPT -LINUX_CAP -LINUX_SPLICE -LINUX_TPROXY -LUA -MATH -MEMORY_PROFILING -NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL -PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT -RT -SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD -TFO +THREAD -THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.2.0 23 Nov 2023
Running on OpenSSL version : OpenSSL 3.2.0 23 Nov 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 14.0.0 (clang-1400.0.29.202)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by capflam** [comment] 2023-12-18 06:50
Thanks for report. Do you know if it is a regression of the 2.9.1 or the 2.9.0 is also affected ?

I'm a bit surprised that a response is returned by HAproxy and no log is emitted. However, there is no log directive in your configuration. It may be an explanation if it really reflects your current configuration.

Have you any way to reproduce the issue on a isolated environnement ? If yes, it could be useful to enable H1 and H2 traces.  To enable H1 and H2 traces, you should add this snippet after your global section:
```
   ring buf1
       size 104857600 # 10MB
       format timed
       backing-file /tmp/blah
   global
       expose-experimental-directives
       trace h1 sink buf1
       trace h1 level developer
       trace h1 verbosity complete
       trace h1 start now

       trace h2 sink buf1
       trace h2 level developer
       trace h2 verbosity complete
       trace h2 start now
```

This will write the traces in /tmp/blah file. You can show the traces by running:
```
     strings /tmp/blah | less
```
If it does not work, you may use haring tool from HAProxy sources. To do so, you should compile it (`make dev/haring/haring`). Then run
```
    ./dev/haring/haring -f /tmp/blah | less
```

In addition, a sensitive feature brought by the 2.9 is the zero-copy forwarding. You may try to disable it by adding `tune.h1.zero-copy-fwd-recv off`  in your global section.

**Comment by lprimak** [comment] 2023-12-18 15:53
Hi, 
2.9.0 is also affected. I will try to get some debugging output when I get some time. I do know that the problem started happening after upgrading from 2.8.4 to 2.9.0

2.9.0 had problems with Jenkins but looks like 2.9.1 only had issues with nexus.

**Comment by lprimak** [comment] 2023-12-19 03:15
Thank you for your feedback, Christopher,

I have tried the following:
- added `tune.h1.zero-copy-fwd-recv off` -  it did not work
- Added `log stdout format raw local0 ` to `global` section - still no logs are produced
- Generated a trace file as you suggested - gzip and upload it here.

Thank you!

**Comment by lprimak** [comment] 2023-12-19 03:20
[haproxy_log.gz](https://github.com/haproxy/haproxy/files/13710735/blah.gz)

**Comment by capflam** [comment] 2023-12-19 07:30
Thanks. About the log, you must also enable the log on your frontend section. For instance: 

```
log global         # To use the global info
option httplog # To use the HTTP log-format
```

About your trace, I can see one `503-Server-Unavailable` reported because of a connection error during the connection establishment after 3 retries. So there is nothing strange here. We must figure out why your haproxy is unable to connect to your nexus server now. The log message will help.

Just to be sure. You said it works for HTTP/2 backends.  In your config, only `payara-admin` and `payara-admin-alt` backends are using HTTP/2 servers. Does it mean you have configured servers of other backends to use HTTP/2 over clear text ? Because, with your trace, it seems to be unrelated to the HTTP version here.

**Comment by lprimak** [comment] 2023-12-19 21:06
> Just to be sure. You said it works for HTTP/2 backend ... , it seems to be unrelated to the HTTP version here

Yes, my premise was that it was HTTP/1.1 vs. HTTP/2, however as you pointed out, that may not actually be true.
The issue is that I am not sure what exactly is causing the issue.
What I do know what 2.9.0 didn't work with Jenkins and Nexus, and 2.9.1 doesn't work with Nexus only (as far as I can tell)

**Comment by lprimak** [comment] 2023-12-19 21:16
After enabling the logs in the frontend as you suggested, the only additional log I get is this:
```::ffff:76.84.35.183:54287 [19/Dec/2023:15:13:51.705] main-web~ nexus/server1 0/0/-1/-1/3013 503 217 - - SC-- 2/2/0/0/3 0/0 "GET https://nexus.hope.nyc.ny.us/ HTTP/2.0"```
Which shows 503 error and is not particularly helpful.

What other logging do you think I can turn on now to be of more help?

Thank you for your continuing help.

**Comment by capflam** [comment] 2023-12-20 10:19
Ok, so your log confirm that haproxy was unable to connect to your server and the 503 was returned after 3 retries. I performed a test and I'm able to reproduce the issue. After a bisect, I found the bug. The regression was introduced by the commit c886fb5. The preferred address family is lost during the initial resolution in functions `srv_set_addr_via_libc()` and `srv_apply_lastaddr()`. 

So in your case, `localhost` is resolved to `::1` instead of `127.0.0.1`.  The following patch should do the trick:

```diff
diff --git a/src/server.c b/src/server.c
index 8e12a3e33a..b36e6d4733 100644
--- a/src/server.c
+++ b/src/server.c
@@ -4281,6 +4281,7 @@ int srv_set_addr_via_libc(struct server *srv, int *err_code)
        struct sockaddr_storage new_addr;
 
        memset(&new_addr, 0, sizeof(new_addr));
+       new_addr.ss_family = srv->addr.ss_family;
        if (str2ip2(srv->hostname, &new_addr, 1) == NULL) {
                if (err_code)
                        *err_code |= ERR_WARN;
@@ -4365,6 +4366,7 @@ static int srv_apply_lastaddr(struct server *srv, int *err_code)
        struct sockaddr_storage new_addr;
 
        memset(&new_addr, 0, sizeof(new_addr));
+       new_addr.ss_family = srv->addr.ss_family;
        if (!str2ip2(srv->lastaddr, &new_addr, 0)) {
                if (err_code)
                        *err_code |= ERR_WARN;
 ```

I will push a fix soon. In the mean time, you can use `127.0.0.1` instead of `ipv4@localhost` or you can configure your server to also listen on `::1`.

**Comment by capflam** [comment] 2023-12-20 12:03
Pushed. It should be fixed now. The patch will be backported as usual. Thanks !

**Comment by lprimak** [comment] 2023-12-20 20:30
Wow. Awesome detective work. Thank you!

**Comment by wtarreau** [comment] 2023-12-21 07:02
reopening until it's backported.

**Comment by capflam** [comment] 2024-01-02 09:29
now backported to 2.9

**Closed as completed by capflam** 2024-01-02 09:29 UTC
Labels: type: bug, status: fixed
