### ISSUE TITLE
HA-Proxy log format changed sice 2.3 -> not logging into separated logfile

### ISSUE THREAD

**Issue by sunflowerbofh** [haproxy/haproxy#963] opened 2020-11-18 12:31 UTC
## Detailed description of the problem

After an upgrade from haroxy-2.2.5 to 2.3.0 (2.3.1 as well) the logs do not go into separate file although explicitely configured and  no config has been changed. It looks as if the "programname" (haproxy) is not interpreted any more.

## Expected behavior

Logs should keep going into haproxy.log when configured in the syslog:

```
$AddUnixListenSocket /var/lib/haproxy/dev/log

:programname, startswith, "haproxy" {
  /var/log/haproxy.log
  stop
}
```

Instead they go into syslog.

## Steps to reproduce the behavior

1. Upgrading from haproxy-2.2.5 to haproxy-2.3.0 in debian package  or
2. Compiling and installing haproxy 2.3.1 from source
3. adding the above mentioned config to rsyslog, causing traffic and looking where log entries go to
4. comparing with behavior in 2.2.5

old log format:

```
Nov 18 04:19:45 node2 haproxy[375313]: 128.14.134.170:45670 [18/Nov/2020:04:19:45.842] http-lb4~ http-nodes4/node2.nextcloud-test.example.com 0/0/16/94/112 400 12935 - - --NN 2/2/0/0/0 0/0 {like Gecko) Chrome/60.0.3112.113 Safari/537.36} "GET / HTTP/1.1"
```

new log format:
```
Nov 18 13:18:41 node2 node2.test.example.com haproxy[24839]: 5.8.10.202:45146 [18/Nov/2020:13:18:41.587] nextcloud-test~ http-nodes4/node2.nextcloud-test.example.com 0/0/16/1/17 400 771 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
```

## Do you have any idea what may have caused this?

Change of default log format. The haproxy[n] entry is further behind in the >= 2.3 version of haproxy.

## Do you have an idea how to solve the issue?

Revert to old default or at least give some working log-format examples section.

## What is your configuration?

```
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend nextcloud-test
        bind    *:443 v4v6 ssl crt /var/lib/dehydrated/certs/(...)/cert.fullchain-privkey.pem ca-file /var/lib/dehydrated/certs/(...)/chain.pem alpn h2,http/1.1
        mode http
        log global
        default_backend http-nodes4

backend http-nodes4
        mode    http
        balance roundrobin
        # NEXTCLOUD IPv4
        server <hostname1 ip1>:443 check ssl verify none
        server <hostname2 ip2>:443 check ssl verify none
        server <hostname3 ip3>:443 check ssl verify none
        stick on src
        stick-table type ip size 1M expire 10m nopurge
```

## Output of `haproxy -vv` and `uname -a`

haproxy -vvv

```
HA-Proxy version 2.3.1-bdd7178 2020/11/13 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.1.html
Running on: Linux 5.9.0-2progress5+u1-amd64 #1 SMP Progress Linux 5.9.6-1~progress5+u1 (2020-11-11) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1h  22 Sep 2020
Running on OpenSSL version : OpenSSL 1.1.1h  22 Sep 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

uname -a
```
Linux dxk1-test.bfh.science 5.9.0-2progress5+u1-amd64 #1 SMP Progress Linux 5.9.6-1~progress5+u1 (2020-11-11) x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces
(no crash)

## Additional information (if helpful)

Workaround is to put

```
  local0.*        /var/log/haproxy.log
```

into the rsylog-conf, but it seems a bit global.

**Comment by TimWolla** [comment] 2020-11-18 13:48
I stumbled upon this as well and I couldn't get any of the log formats to work with rsyslog.

**Comment by wtarreau** [comment] 2020-11-19 05:30
@EmericBr it seems that the changes that were required for syslog forwarding and which always prepend the local host name to comply with the network logging standards are causing trouble when using local logs. Probably that we should change this so that only an explicit rfc3164 format sends the host name and that the default one does not. Maybe a new "local" format should be created to be like 3164 without the host name ? Any other idea ?

**Comment by wtarreau** [comment] 2020-11-19 05:32
Hmmm rfc3164 was already present in 2.2 without the host name either so we'd rather need a separate option to prepend the host name (or strip it).

**Comment by EmericBr** [comment] 2020-11-26 10:39
re-checking the rfc3164, the hostname field seems mandatory, So I would prefer to introduce a "local" format as you propose firstly to strip the hostname.

Your opinion?

**Comment by wtarreau** [comment] 2020-11-26 10:46
I think it's definitely the way to proceed since it's indeed the output format that's affected. It would be nice to adjust the doc to mention clearly that rfc3164/rfc5424 always add the hostname and that it was not the case prior to 2.3, and that "local" may still be used to keep the old format if needed.

Hmmm wait a minute, I seem to remember a "log send-hostname" option or something like this in the past, which would then invalidate the "local" or force what is currently done in 3164. Thus I'm wondering how to deal with all these combinations. Maybe in the end we should continue to rely on this option and decide that it's on by default and that those who don't want it would just have to add "no log-send-hostname" or "log-send-hostname off" or whatever (I really don't remember how it's configured, that's just old memories).

**Comment by EmericBr** [comment] 2020-11-27 15:39
[
[0001-BUG-MEDIUM-local-log-format-regression.patch.txt](https://github.com/haproxy/haproxy/files/5608578/0001-BUG-MEDIUM-local-log-format-regression.patch.txt)
](url)

**Comment by EmericBr** [comment] 2020-11-27 15:41
Here a proposed patch. I hesitate between "local" or "legacy" for the re-introduced log format

**Comment by EmericBr** [comment] 2020-11-27 15:44
[0001-BUG-MEDIUM-local-log-format-regression.patch.txt](https://github.com/haproxy/haproxy/files/5608605/0001-BUG-MEDIUM-local-log-format-regression.patch.txt)

**Comment by EmericBr** [comment] 2020-11-30 09:58
@wtarreau the patch is tested, the behavior is described in comment. let me know if you prefer the name "legacy" instead of "local" for the log  header format.

**Comment by EmericBr** [comment] 2020-11-30 10:21
Note: with that patch, if format is forced to rfc3164 and log-send-hostname is not specified, the string "localhost" is used as hostname in the header. If rfc5424 is is forced without "log-send-hostname", default value "-" is used for hostname as documented in rfc. This is a side effect but in this way the hostname is never exposed since the user doesn't request this explicitly using "log-send-hostname"

**Comment by wtarreau** [comment] 2020-12-01 06:00
That's a good point I hadn't thought about, thanks for the explanation! Now merged.

**Closed as completed** 2020-12-14 11:14 UTC
Labels: type: bug, status: fixed
