### ISSUE TITLE
HAProxy "show stats json" produces invalid JSON when using "tcp-check expect binary" with non-ASCII character codes

### ISSUE THREAD

**Issue by johnson-earls** [haproxy/haproxy#2326] opened 2023-10-26 16:41 UTC
### Detailed Description of the Problem

I have a backend with a tcp-check that is expecting the binary string `0869735772697461626c655072696d6172790001`.

When this check fails, the "show stat json" object for the `Server` object type, `last_chk` field, _intermittently_ reports a value of `{"type":"str","value":" at step 3 of tcp-check (expect string '^HisWritablePrimary') comment: '…'"}` (where the `^H` is an actual backspace character, ascii code 0x08).  This does not conform to the JSON standard (ECMA-404):

> All code points may be placed within the quotation marks except for the code points that must be escaped: quotation mark (U+0022), reverse solidus (U+005C), and the control characters U+0000 to U+001F

This means output that includes this type of text cannot be processed by standards-conforming tools such as `jq`.

_Note_ - I know that I am running an older version of haproxy (the version in the standard YUM repositories for CentOS 8) - but I looked at the current version of the code in the github repository and it _appears_ to not do any processing to the strings which are returned for JSON output, so I assume this bug still exists in the current version.

### Expected Behavior

JSON output should conform to the JSON standard: it should produce escape sequences for characters in quoted strings that are not allowed - the quote mark, the backslash, and any control character in the range of U+0000 through U+001F.  These should be escaped using the respective sequences `\"`, `\\`, or `\u0000` through `\u001f` (or possibly the shortened sequences `\b` for character code 08, `\t` for 09, `\n` for 0A, `\f` for 0C, or `\r` for 0D).

### Steps to Reproduce the Behavior

this example includes a purposely invalid health check to prove the point.

1. `/etc/haproxy/haproxy.cfg`:
    ```
    global
        stats socket /var/lib/haproxy/stats mode 0666
    
    defaults
        timeout connect 10s
        timeout client 1m
        timeout server 1m
    
    frontend smtp-test-2222
        bind *:2222
        default_backend smtp-test-22
    
    backend smtp-test-22
        mode tcp
        option tcp-check
        tcp-check connect
        tcp-check expect binary 736d74700A
        server localhost 127.0.0.1:22 check
    ```

2. Run haproxy in debug mode:
    ```
    haproxy -d -f /etc/haproxy/haproxy.cfg
    ```

3. Wait for the check to fail

4. In another shell, connect to the stats and look for the `last_chk` stat object:
    ```
    echo show stat json | nc -U /var/lib/haproxy/stats | tr ',' '\n' | grep -B4 -A7 last_chk
    ```
    Repeat this until it shows an error message in the value:
    ```
    {"objType":"Server"
    "proxyId":3
    "id":1
    "field":{"pos":56
    "name":"last_chk"}
    "processNum":1
    "tags":{"origin":"Metric"
    "nature":"Output"
    "scope":"Process"}
    "value":{"type":"str"
    "value":" at step 2 of tcp-check (expect string 'smtp
    ')"}}
    ```

This example shows the newline being placed directly into the JSON string, rather than encoded as either `\n` or `\u000A` or `\u000a`.

The same behavior occurs with any binary expect string (up to the first 0x00 nul character, at which point haproxy stops printing the string).

### What is your configuration?

```haproxy
# Stripped down configuration to the appropriate definitions

global
    log localhost local0
    external-check
    stats socket /var/lib/haproxy/stats

defaults
    log global

frontend mongodb_27017
    bind *:27017
    bind 127.0.0.1:27017
    default_backend mongodb_27017

backend mongodb_27017
    mode tcp
    option tcp-check
    tcp-check connect comment 'checking for master mongodb server'
    tcp-check send-binary c200000078563412ffffffffdd0700000000000000ad0000001068656c6c6f00010000000868656c6c6f4f6b000103636c69656e74007c000000036170706c69636174696f6e001b000000026e616d65000c0000006865616c7468636865636b000003647269766572002e000000026e616d65000e000000776972652070726f746f636f6c000276657273696f6e0004000000352e300000036f730015000000027479706500060000006c696e757800000002246462000600000061646d696e0000
    tcp-check expect binary 0869735772697461626c655072696d6172790001
    default-server inter 5s
    server ...  ...:27017 check
```

### Output of `haproxy -vv`

```plain
# uname -a
Linux ... 4.18.0-517.el8.x86_64 #1 SMP Wed Oct 11 00:24:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
# haproxy -vv
HA-Proxy version 1.8.27-493ce0b 2020/11/06
Copyright 2000-2020 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-null-dereference -Wno-unused-label -Wno-stringop-overflow
  OPTIONS = USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.4
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
```

**Comment by capflam** [comment] 2023-10-30 07:58
You're right there is indeed an issue and all stable versions are affected. At first glance, I don't see any reason to dump the decoded version of the binary string. It is internal to HAProxy.  It can easily be fixed as far as 2.2 by reporting the original hexa-string. However, it will be hard to fix it for the 2.0 because internally there is no difference between `expect string <str>` and `expect bnary <hexstr>`. The hexa-string is converted during the configuration parsing and then the info is lost. 
So if the issue is really annoying for you, you should consider to upgrade to a newer version (>= 2.2).

**Comment by capflam** [comment] 2023-10-30 08:06
Note that a workaround could be to use a `tcp-check expect rbinary <regex>` rule instead with the same hexa-string.

**Comment by johnson-earls** [comment] 2023-10-30 18:10
thanks for the work-around.  for now, i'm stuck at the old version (1.8), which also doesn't include the `expect rbinary` option.  i've worked around it in my calling scripts to just strip the invalid characters from the json output before processing; i wanted to report this just to get it fixed for others :)

**Comment by capflam** [comment] 2023-10-31 07:15
It should be fixed now. It will be backported as usual. Thanks !

**Comment by capflam** [comment] 2023-10-31 07:17
Indeed, `expect rbinary` was introduced to 2.2. Sorry for the wrong workaround.

**Closed as completed** 2023-12-18 06:52 UTC
Labels: type: bug, status: fixed
