### ISSUE TITLE
backend server connected even if client tcp connection was reset already

### ISSUE THREAD

**Issue by bjacke** [haproxy/haproxy#403] opened 2019-12-07 00:47 UTC
as a counter measure against some bots I use a delay in a http frontend using

http-request lua.delay_5s if  { path -m dir "somebadpath" }

the lua delay script is:

function delay_5s(txn)
    core.msleep(5000)
end
core.register_action("delay_5s", { "http-req" }, delay_5s);

What I would expect to happen is that if a connecting client doesn't wait 5s and resets the tcp connection, then the frontend will not connect the backend server at all. The opposite is the case however: If the clients send a  tcp reset then the frontend is calling the backend server immediately instead of discarding the request.

**Comment by wtarreau** [comment] 2019-12-07 06:30
This is unclear to me, does the client actually send a request or not ?
Because if it doesn't send a request at all, it's just a probe connection
and should not even report an incoming request. If however you already have
a request, it will be served, unless you have "option abortonclose", which
indicates that a client shutdown should be considered as an abort (in HTTP/1
there's no way to abort other than closing the connection, but a connection
close doesn't really exist, it's just a shutdown, the same that a number of
monitoring scripts happen to send after the request).

**Comment by bjacke** [comment] 2019-12-07 13:40
I try to make it more clear:

- I start a curl client connection that sends a http request
- the 5s sleep lua script in the frontend starts the delay the processing here
- after 1s I stop curl, which triggers a TCP RST send to the frontend
- immediately after the TCP RST from the client the frontend triggers the http request on the backend, 

(also abortonclose is enabled in the defaults)

**Comment by capflam** [comment] 2021-12-03 13:24
I'm closing this issue. HAProxy works as expected here. `abortonclose` option is only used to abort queued connections only. It does not mean this kind of abort should not be addressed. But it is a feature request and not a bug. Thanks !

**Closed as completed by capflam** 2021-12-03 13:24 UTC
Labels: type: bug, status: works as designed
