### ISSUE TITLE
3.0-dev3-56e73d-30: admin page excludes backends

### ISSUE THREAD

**Issue by brenc** [haproxy/haproxy#2453] opened 2024-02-20 21:06 UTC
### Detailed Description of the Problem

Looks like somewhere between dev2 and this commit, the admin page was broken. It lists frontends, listen blocks, but no backends.

### Expected Behavior

Admin page should show backends.

### Steps to Reproduce the Behavior

Update to dev3+, load admin page.

### What is your configuration?

```haproxy
Config in #2429.
```

### Output of `haproxy -vv`

```plain
$ roles/proxy_server/files/haproxy-3.0-dev3.bin -vv
HAProxy version 3.0-dev3-56e73d-30 2024/02/16 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS -DDEBUG_DONT_SHARE_POOLS -DDEBUG_POOL_INTEGRITY

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 3.0.11 19 Sep 2023
Running on OpenSSL version : OpenSSL 3.0.11 19 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by wtarreau** [comment] 2024-02-20 21:12
Hmm not cool, thanks for the report. On plain dev3 on stats.haproxy.org, the backends are correctly listed, so with a bit of luck it broke just after.

**Comment by capflam** [comment] 2024-02-21 08:13
Not good. Its seems there is an issue with the zero-copy forwarding. I don't know what exactly for now. But, on firefox and chrome, with a huge stats page (~57 MB), most of time the page is truncated. But not always. With FF, the connection is reset by the browser. With Chrome, it is unresponsive and the connection timed out. Disabling the zero-copy forwarding, by hand or by enabling the compression, fixes the issue. However, with curl I'm unable to reproduce the issue.

So I'm digging. I suspect there is an issue with the chunk envelop. If I'm right, a workaround is to disable the zero-copy forwarding for applets by adding `tune.applet.zero-copy-forwarding off` in your global config.

**Comment by capflam** [comment] 2024-02-21 08:27
Ok, I got it ! It is possible to insert a 0-CRLF chunk in the middle of the response because amount of data to forward is not properly checked. It was not an issue before the -dev3, because chunks size was announced at the beginning of the forwarding. With the stats page, it is not possible. The chunk size is decided when data are forwarded. When there is no data, for any reason, we must not produce any chunk... I'll fix it. Thanks @brenc !

My workaround remains valid.

**Comment by capflam** [comment] 2024-02-21 10:54
I pushed a fix, it should good now.

**Closed as completed** 2024-04-08 06:04 UTC
Labels: type: bug, status: fixed
