### ISSUE TITLE
Prefer specific TLS certificates over wildcards, when overlapping

### ISSUE THREAD

**Issue by bgdnlp** [haproxy/haproxy#394] opened 2019-12-02 09:35 UTC
## Output of `haproxy -vv` and `uname -a`

```
    HA-Proxy version 2.0.9 2019/11/15 - https://haproxy.org/
    Build options :
      TARGET  = freebsd
      CPU     = generic
      CC      = cc
      CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-ignored-qualifiers -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wtype-limits -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
      OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_REGPARM=1 USE_STATIC_PCRE=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1

    Feature list : -EPOLL +KQUEUE -MY_EPOLL -MY_SPLICE -NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM +STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA -FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

    Default settings :
      bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

    Built with multi-threading support (MAX_THREADS=64, default=1).
    Built with OpenSSL version : OpenSSL 1.1.1a-freebsd  20 Nov 2018
    Running on OpenSSL version : OpenSSL 1.1.1d-freebsd  10 Sep 2019
    OpenSSL library supports TLS extensions : yes
    OpenSSL library supports SNI : yes
    OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
    Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
    Built with zlib version : 1.2.11
    Running on zlib version : 1.2.11
    Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
    Built with PCRE version : 8.43 2019-02-23
    Running on PCRE version : 8.43 2019-02-23
    PCRE library supports JIT : yes
    Encrypted password support via crypt(3): yes

    Available polling systems :
         kqueue : pref=300,  test result OK
           poll : pref=200,  test result OK
         select : pref=150,  test result OK
    Total: 3 (3 usable), will use kqueue.

    Available multiplexer protocols :
    (protocols marked as <default> cannot be specified using 'proto' keyword)
                  h2 : mode=HTTP       side=FE        mux=H2
                  h2 : mode=HTX        side=FE|BE     mux=H2
           <default> : mode=HTX        side=FE|BE     mux=H1
           <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

    Available services : none

    Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```
uname -a:
```
    FreeBSD hapy01.hidden.domain.com 12.1-RELEASE-p1 FreeBSD 12.1-RELEASE-p1 GENERIC  amd64
```

## What should haproxy do differently? Which functionality do you think we should add?

**When choosing which TLS certificate to present to a client, HAProxy should prefer certificates for the specific subdomain requested over wildcard certificates. If present. And maybe prefer valid certificates over self-signed or invalid ones.**

I'm setting up HAProxy to serve multiple certificates, loaded from a directory. I have one certificate for `*.domain.com` (self-signed) and one for `subdomain.domain.com` (valid, LetsEncrypt). When pointing a browser to `subdomain.domain.com` HAProxy will present the self-signed wildcard certificate. The order in which certificates are loaded doesn't seem to make a difference. Maybe it would make more sense if it presented the certificate for that specific subdomain?

Also, the self-signed certificate covers `domain.com`, but if there is a valid certificate for the same domain, the valid one should be preferred. I realize that "valid" is subjective and depends on the CA list, which might be different from the one the client has, so I'm not sure how this second part should work. Maybe consider any certificate that isn't self-signed or expired as valid?

## What are you trying to do?

My intention was to use the self-signed cert as default for any domain that doesn't have a valid certificate yet, and use the specific certs for the domains that do have them.

**Comment by ehocdet** [comment] 2019-12-02 09:45
It's a bug, haproxy should select the specific one before wildcard.
I have a patch for this in stock, i will send it to ML asap.

**Comment by bgdnlp** [comment] 2019-12-02 09:47
Oh, ok. I searched, didn't find it. Should I close this issue then?

**Comment by lukastribus** [comment] 2019-12-02 10:11
No, we will close the issue when the fix is committed to affected repositories.

**Comment by ehocdet** [comment] 2019-12-02 10:22
the case that I pointed is:
- certificate RSA for a.dom
- certificate EC for *.dom

Actually EC is preferred over RSA in every case. I should be only for specific certificate.
That's the case here?

Workaround could be generate a *.dom certificate in RSA.

**Comment by bgdnlp** [comment] 2019-12-02 10:29
That is the case, yes. The wildcard self-signed certificate is "ANSI X9.62 ECDSA Signature with SHA256". The specific one, issued by LetsEncrypt, is RSA.

Thank you for the details and workaround.

**Comment by lukastribus** [comment] 2019-12-02 10:37
So this is not a regression, just a corner case with different certificate types. I'm not so sure this is unexpected then.

@ehocdet are you sure this is an easy, non-intrusive fix?

**Comment by wtarreau** [comment] 2019-12-02 10:40
Well, normally we should match the name first, and then for a given name
see what options are available. Otherwise it means one cannot use default
certs as soon as multiple types are in use. I have no idea about the
changes involved there however. Also given that these parts have changed
a lot between 2.0 and 2.1, it might even be possible that the behaviour
also changed!

**Comment by ehocdet** [comment] 2019-12-02 10:53
@lukastribus it's a regression from 9f9b0c6a "BUG/MEDIUM: ECC cert should work with TLS < v1.2 and openssl >= 1.1.1"   
@wtarreau impact since 1.8

I just need to well comment the patch and send it.

**Comment by wlallemand** [comment] 2019-12-02 10:53
I agree with @wtarreau on this.

Nothing changed regarding this between 2.0 and 2.1, if it changed that's a regression.

**Comment by lukastribus** [comment] 2019-12-02 11:01
@ehocdet ok, thanks for clarifying.

> Well, normally we should match the name first, and then for a given name see what options are available. Otherwise it means one cannot use default certs as soon as multiple types are in use

The argumentation would have been: if you have an ECC wildcard cert, you also need more specific ECC certificates. If you have ECC certs for both, it's doesn't matter if you also have all or some RSA certificates, that's how I understand the behavior.

Having ECC wildcard certificates but only RSA "specific" certificates is a rather strange setup.

But since it is actually a regression, this is a moot point.

**Comment by wtarreau** [comment] 2019-12-02 11:38
I mean, you can have many certs of varying types and then have fallbacks
for all unhandled names just to serve an error page or something like
this. The name is looked up before we even know what cert type can be
presented so it seems important that the most accurate name is always
matched and then that only available types are used. I do agree however
that if you have many cert types it makes sense to have your wildcards
set using all types anyway.

**Comment by wlallemand** [comment] 2019-12-09 08:34
The patch was backported as far as 1.8.

**Closed as completed by wlallemand** 2019-12-09 08:34 UTC
Labels: type: bug, status: fixed
