### ISSUE TITLE
Performance degradation (high CPU consumption) when upgrading from 1.8.20 to 1.9.X/2.03

### ISSUE THREAD

**Issue by ccwilkins** [haproxy/haproxy#209] opened 2019-08-05 16:40 UTC
## Output of `haproxy -vv` and `uname -a`

```
/ # uname -a
Linux f8e108a77b72 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux
```

```
 # haproxy -vv
HA-Proxy version 2.0.3 2019/07/23 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1c  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.33 2019-04-16
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

## What's the configuration?

```
global
  log-send-hostname
  log-tag haproxy
  stats socket /var/run/haproxy.sock mode 600 level admin
  stats timeout 30s
  maxconn 4000
  tune.ssl.default-dh-param 2048
  ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
  ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
  ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
  ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

defaults
  log global
  mode http
  option redispatch
  option httplog
  option dontlognull
  option http-ignore-probes
  option http-server-close
  timeout connect 5s
  timeout client 15s
  timeout server 300s
  timeout http-keep-alive 4s
  timeout http-request 10s
  # for websocket
  timeout tunnel 2m
  timeout client-fin 1s
  timeout server-fin 1s

listen stats
  bind :1936
  mode http
  stats enable
  stats show-node
  stats hide-version
  stats realm Haproxy\ Statistics
  stats uri /
  stats auth stats:stats

frontend http-in
  bind *:80
  bind *:443 ssl crt <cert removed>
  maxconn 4000

  tcp-request inspect-delay 5s

  # Force use of https
  http-request redirect scheme https code 301 if !{ ssl_fc }

  http-request set-header X-Forwarded-For %[src]
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  http-request set-header X-Forwarded-Port %[dst_port]

  # Backend to deny requests if no rules have been matched.
  backend deny
    http-request deny

```

## Steps to reproduce the behavior

1. Switching to 2.0.3 from 1.8.20 using the exact same configuration

## Actual behavior
CPU consumption sits around 85% with spikes to 100%.

## Expected behavior
CPU consumption to match what is seen with 1.8.20. Right around 20% CPU consumption.

## Do you have any idea what may have caused this?
Upgrading to 2.0.3 or 1.9.8.

## Do you have an idea how to solve the issue?
Not at this time.

**Comment by ccwilkins** [comment] 2019-08-05 18:11
Just wanted to add that we are running the haproxies on docker (docker swarms) with no CPU or memory limits.

Each VM has the following setup:

2 Azure Standard_B2s each having:

2 VCPUs
4 GiB memory

**Comment by ccwilkins** [comment] 2019-08-05 19:52
Tried both alpine and Debian versions which resulted in the same huge increase in CPU consumption.

**Comment by lukastribus** [comment] 2019-08-05 22:07
Possible duplicate of #168 

Can you try rebuilding with:
`DEFINE="-DMAX_READ_POLL_LOOPS=1" `

**Comment by ccwilkins** [comment] 2019-08-06 17:39
@lukastribus I saw #168 but wasn't sure. Thanks for the suggestion but I'll wait for the improvements coming in 2.1/2.2. Don't want to use a custom build and it is hard to replicate without huge amounts of traffic. Feel free to mark it duplicate if you want of #168. This appears to me like a serious performance bug.

**Comment by wtarreau** [comment] 2019-08-06 21:05
On Tue, Aug 06, 2019 at 10:39:54AM -0700, ccwilkins wrote:
> @lukastribus I saw #168 but wasn't sure. Thanks for the suggestion but I'll
> wait for the improvements coming in 2.1/2.2. Don't want to use a custom build
> and it is hard to replicate without huge amounts of traffic. Feel free to
> mark it duplicate if you want of #168. This appears to me like a serious
> performance bug.

If it is that high on your side, it cannot be this. This one was not even
a bug and is the only way syscalls are supposed to be used. It's just that
in previous versions we managed to use some heuristics to save *one* syscall
per forward, in the worst case it will represent a few percent CPU, not 10
times more. You may be facing a looping bug like a few people faced in the
past. I'm not aware of any left in 2.0.4, so you may want to recheck,
possibly with Lukas' suggestion. If that works then we can check which
change did the trick, if it doesn't work no need to go further but we'll
need more info (strace etc).

Thanks,
Willy

**Comment by ccwilkins** [comment] 2019-08-09 11:06
Thanks @wtarreau for your response. Are you indicating that there are looping problems in 2.0.3?

**Comment by wtarreau** [comment] 2019-08-10 05:09
We've had looping bugs but to be honest I don't have in mind the mapping of each bug and each version. Looking at http://www.haproxy.org/bugs/bugs-2.0.3.html I see there's at least a locking bug and a possible memory corruption when using tcp-request with HTTP, both of which can explain such issues. We've had a recent report of an infinite loop still present in 2.0.4, not diagnosed yet.

**Comment by wtarreau** [comment] 2019-12-11 15:40
Many related issues were addressed over the last 4 months on this subject, closing on absence of new activity. Feel free to reopen if the issues remains with 2.0.11.

**Closed as completed by wtarreau** 2019-12-11 15:40 UTC
Labels: type: bug
