### ISSUE TITLE
Peers local sync, counters significantly increase on reload

### ISSUE THREAD

**Issue by brenc** [haproxy/haproxy#1497] opened 2021-12-21 06:27 UTC
### Detailed Description of the Problem

Looks like I stumbled upon a bug in 2.5.0 with peers (at least locally which is all I'm using peers for right now). On reload stick table counters significantly increase. This does not happen with 2.2.19 or 2.4.9.

### Expected Behavior

Stick tables should properly sync after a reload.

### Steps to Reproduce the Behavior

Here is what the stick table looks like after a fresh restart and making exactly three requests:

`0x55908ca43960: key=::ffff:X:X:X:X use=0 exp=58232 gpt0=0 conn_cur=0 http_req_rate(60000)=3 http_err_rate(60000)=0`

Then I run "systemctl reload haproxy" which runs (from the example systemd config in the tarball):

```
ExecReload=/usr/local/sbin/haproxy -Ws -f $CONFIG -c -q $EXTRAOPTS
ExecReload=/bin/kill -USR2 $MAINPID
```

This is what the stick table looks like after reload:

`0x5573adf7c1d0: key=::ffff:X:X:X:X use=0 exp=32148 gpt0=0 conn_cur=0 http_req_rate(60000)=26768 http_err_rate(60000)=3661295550`

You can see the counters have increased significantly. If I continue to reload the numbers jump all over the place.

### What is your configuration?

```haproxy
global
  crt-base /etc/haproxy/certs

  chroot /var/lib/haproxy

  group haproxy

  log /dev/log local1

  maxconn 50000

  server-state-file /var/lib/haproxy/server_state

  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

  ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

  ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

  ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

  ssl-dh-param-file /etc/haproxy/dhparam

  stats socket /run/haproxy/admin.sock user haproxy group haproxy mode 660 level admin expose-fd listeners
  stats socket localhost:81 level admin

  tune.h2.initial-window-size 1048576

  user haproxy


defaults
  balance roundrobin
  
  load-server-state-from-file global

  log global

  mode http

  option contstats

  option dontlog-normal

  option httplog

  option http-buffer-request

  option log-separate-errors

  option redispatch -1

  timeout client 30s

  timeout client-fin 30s

  timeout connect 5s

  timeout queue 10s

  timeout http-keep-alive 5s

  timeout http-request 5s

  timeout server 30s

  timeout tarpit 5s

  timeout tunnel 30s

  errorfile 400 /etc/haproxy/errorfiles/400.http
  errorfile 403 /etc/haproxy/errorfiles/403.http
  errorfile 408 /etc/haproxy/errorfiles/408.http
  errorfile 500 /etc/haproxy/errorfiles/500.http
  errorfile 502 /etc/haproxy/errorfiles/502.http
  errorfile 503 /etc/haproxy/errorfiles/503.http
  errorfile 504 /etc/haproxy/errorfiles/504.http


peers local
  peer proxy01 127.0.0.1:10000


frontend fe-main
  bind IP:80
  
  bind IP:443 ssl crt /etc/haproxy/certs alpn h2,http/1.1
  
  maxconn 50000 
  
  no option dontlog-normal
  
  option forwardfor
  
  tcp-request inspect-delay 10s

  acl host_dynamic hdr_dom(host) -i domain.com

  tcp-request content track-sc0 src table be-dynamic if host_dynamic
  
  use_backend be-dynamic if host_dynamic


backend be-dynamic
  cookie SERVERID_D insert indirect nocache secure attr "SameSite=None"

  fullconn 900

  option httpchk GET /lbtest.php HTTP/1.0

  http-check expect string php\ functioning

  option tcp-smart-connect

  stick-table type ipv6 size 100k expire 1m store http_err_rate(1m),http_req_rate(1m),gpt0,conn_cur peers local

  server web-d01 10.0.0.1:80 check cookie web-d01 maxconn 150 weight 100
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.5.0-f2e0833 2021/11/23 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.0.html
Running on: Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -
Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-mis
sing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-v
alue -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=
1 USE_ZLIB=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL
 +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLI
CE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM +ZLIB -SLZ
+CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE
_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw
-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_F
REEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_A
BRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RIS
K|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment] 2021-12-22 09:01
Hi Brendon,

that's particularly shocking indeed. There are not that many changes between 2.4 and 2.5 regarding the peers. However one of them consists in dropping incoming updates for `conn_cur` (which used to either constantly grow or go negative since it's related to the process and nothing else). It is possible that I've done something wrong there (e.g. not consume the entire message or so) resulting in desynchronizing the protocol, leaving garbage values for other fields. Could you please remove `conn_cur` from your list of entries and see if the problem persists ? If not, it means I did something wrong and will have to investigate.

**Comment by brenc** [comment] 2021-12-22 18:56
Hi Willy! Yep I think that was it. This doesn't happen when I remove `conn_cur` from the stick table. As soon as I add it back in and reload, the counters get all wonky again.

**Comment by wtarreau** [comment] 2021-12-22 21:28
Great, so the good news is that we know where this is and the bad one is that I messed up with something I thought I understood but obviously did not, hence the fix will be more difficult. At least now I have good hints about how to reproduce it to figure what I overlooked. Thanks!

**Comment by idl0r** [comment] 2021-12-23 08:55
I'm not familiar with the VTest stuff yet but wouldn't it be possible to add a testcase for stick-table counter + synchronization? At least some basic counter tests perhaps. For a single instance as well as a case for 2 processes with peers.

**Comment by wtarreau** [comment] 2021-12-24 09:15
Vtest cases based on peers are racy by nature, because you need to wait "long enough" to check the other process to be sure the data was pushed. And in some environments like the overloaded (but free) VMs that run GitHub actions we're already facing a non-negligible number of false positives due to timing issues. But in theory you're right, yes. At least maybe we should include conn_cur with some of the existing peers tests to make sure it doesn't break them.

**Comment by wtarreau** [comment] 2021-12-24 12:53
OK it's now fixed and backported. The "funny" thing is that the regtest had already been updated to test for it, but due to the way they work, the range of accepted values is extremely permissive and doesn't allow to distinguish correct values from corrupted ones. No big deal though.

I'm marking as fixed and closing. @brenc I'm attaching the patch in case you want to apply it directly onto your local tree. Thanks for your reproducer :-)

[0001-BUG-MEDIUM-peers-properly-skip-conn_cur-from-incomin.patch.txt](https://github.com/haproxy/haproxy/files/7774329/0001-BUG-MEDIUM-peers-properly-skip-conn_cur-from-incomin.patch.txt)

**Closed as completed by wtarreau** 2021-12-24 12:53 UTC
Labels: type: bug, severity: medium, subsystem: peers, status: fixed

**Comment by brenc** [comment] 2021-12-24 21:49
Applied and tested, looks good. Thanks Willy!
