### ISSUE TITLE
HAProxy fails to gracefully reload its configuration with peers and stick directives

### ISSUE THREAD

**Issue by sreboot** [haproxy/haproxy#443] opened 2020-01-13 09:09 UTC
## Output of `haproxy -vv` and `uname -a`
```
haproxy -vv
HA-Proxy version 2.0.10 2019/11/25 - https://haproxy.org/
Build options :
  TARGET  = solaris
  CPU     = generic
  CC      = gcc
  CFLAGS  = -pipe -O2 -msave-args -fno-aggressive-loop-optimizations -D_FORTIFY_SOURCE=2 -I/opt/local/include -I/usr/include -DFD_SETSIZE=65536 -D_REENTRANT -D__EXTENSIONS__
  OPTIONS = USE_PCRE=1 USE_REGPARM=1 USE_OPENSSL=1 USE_ZLIB=1

Feature list : -EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE -NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA -FUTEX -ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ -CPU_AFFINITY -TFO -NS -DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD +OBSOLETE_LINKER -PRCTL -THREAD_DUMP +EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with transparent proxy support using:
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes

Available polling systems :
    evports : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use evports.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE        mux=H2
              h2 : mode=HTX        side=FE|BE     mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

```
uname -a
SunOS hap01 5.11 joyent_20190912T054018Z i86pc i386 i86pc
```

## What's the configuration?
```
global
  setenv hostname hap01
  master-worker
  daemon
  pidfile /var/run/haproxy.pid
  stats socket /var/run/haproxy.sock mode 777 level admin expose-fd listeners
  description Fabric 129 HAProxy

peers mypeers
    bind :10000
    server hap01 # local node
    server hap02 10.98.129.28:10000 # remote peer
    server hap03 10.98.129.27:10000 # remote peer
    table src_tracking type string size 10m store http_req_rate(10s),http_req_cnt

defaults
  option socket-stats
  default-server init-addr none inter 1s rise 2 fall 2
  mode http
  timeout client 30s
  timeout connect 4s
  timeout http-keep-alive 10s
  timeout http-request 5s
  timeout server 30s

frontend c-proxy
  mode tcp
  bind *:3128
  use_backend proxy

backend proxy
  mode tcp
  option httpchk GET / HTTP/1.1\r\nHost:\ hap
  http-check expect status 403
  server proxy 10.93.110.5:8080 check

frontend http-in
  bind *:80
  maxconn 2000
  use_backend b_%[req.hdr(Host),lower,word(1,:)]

backend b_consul-ui-129.svc.skn.triton
  option httpchk GET / HTTP/1.1\r\nHost:\ bshapk01
  http-check expect status 401
  stick-table type ip size 20k expire 30m peers mypeers
  stick on src
  cookie SRV insert indirect nocache

  server csl01 10.98.129.6:80 check cookie csl01

frontend stats
  bind *:8080
  mode http
  option httpclose
  stats enable
  stats uri /
  stats show-legends
  stats show-desc
  stats show-node
  stats refresh 5
```

## Steps to reproduce the behavior
1. Start HAProxy with:
```
haproxy -f /opt/local/etc/haproxy.cfg -sf $(cat /var/run/haproxy.pid) -x /var/run/haproxy.sock -L hap01
```

2. Issue SIGUSR2 to initiate a graceful reload:
```
kill -SIGUSR2 $(cat /var/run/haproxy.pid)
```

## Actual behavior
```
Note: setting global.maxconn to 32748.
Available polling systems :
    evports : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use evports.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
Using evports() as the polling mechanism.
[WARNING] 012/084838 (586821) : Failed to connect to the old process socket '/var/run/haproxy.sock'
[ALERT] 012/084838 (586821) : Failed to get the sockets from the old process!
[NOTICE] 012/084838 (586821) : New worker #1 (586822) forked
[WARNING] 012/084841 (586821) : Reexecuting Master process
Note: setting global.maxconn to 32748.
Available polling systems :
    evports : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use evports.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
Using evports() as the polling mechanism.
00000002:GLOBAL.accept(0006)=000f from [unix:1] ALPN=<none>
00000002:GLOBAL.srvcls[adfd:ffffffff]
00000002:GLOBAL.clicls[adfd:ffffffff]
00000002:GLOBAL.closed[adfd:ffffffff]
[ALERT] 012/084841 (586821) : [haproxy.main()] .
[ALERT] 012/084841 (586821) : [haproxy.main()] Some protocols failed to start their listeners! Exiting.
```

Output with TRUSS(1):
```
setsockopt(7, SOL_SOCKET, SO_REUSEADDR, 0x005C17A8, 4, SOV_DEFAULT) = 0
getsockopt(7, SOL_SOCKET, SO_LINGER, 0xFFFFFA7FFFDFF588, 0xFFFFFA7FFFDFF584, SOV_DEFAULT) = 0
setsockopt(7, SOL_SOCKET, SO_LINGER, 0xFFFFFA7FFFDFF588, 8, SOV_DEFAULT) = 0
bind(7, 0x0085DB08, 16, SOV_SOCKBSD)            Err#125 EADDRINUSE
close(7)                                        = 0
getpid()                                        = 586836 [586835]
[ALERT] 012/084922 (586836) : write(2, " [ A L E R T ]   0 1 2 /".., 30)        = 30
[haproxy.main()] .
write(2, " [ h a p r o x y . m a i".., 19)      = 19
getpid()                                        = 586836 [586835]
[ALERT] 012/084922 (586836) : write(2, " [ A L E R T ]   0 1 2 /".., 30)        = 30
[haproxy.main()] Some protocols failed to start their listeners! Exiting.
write(2, " [ h a p r o x y . m a i".., 74)      = 74
close(10)                                       = 0
close(11)                                       = 0
close(12)                                       = 0
close(8)                                        = 0
kill(586837, SIGTTIN)                           = 0
_exit(1)
```

## Expected behavior
HAProxy gracefully reloads without terminating.

## Do you have any idea what may have caused this?
It is related to the peers section and likely its bind port being still in use when HAProxy attempts to reload itself, which seem to be recorded under TRUSS(1) line: `bind(7, 0x0085DB08, 16, SOV_SOCKBSD)            Err#125 EADDRINUSE`

## Do you have an idea how to solve the issue?
No, although removing the peers section and the corresponding stick config directives form haproxy.cfg avoids this issue from manifesting.

**Comment by wlallemand** [comment] 2020-01-13 16:44
Hello,

There are several problems there:

- It looks like SO_REUSEPORT is not used, which is weird. According to this [documentation](https://docs.oracle.com/cd/E26502_01/html/E29044/tcp-7p.html) it's supported since solaris 11. Maybe you can see it in your complete truss output, buf if you don't see it anywhere, there might be a compilation problem, but it's not mandatory, it *MUST* work without it.

- the '-x' command failed, for an unknown reason, without this it is unable to get the previous peer socket, which is one of the alternative to SO_REUSEPORT. Are you able to connect to /var/run/haproxy.sock  using socat? 

- When the -x and the REUSEPORT didn't work, HAProxy ask the previous process to pause the binds temporally by sending a SIGTTOU signal. It looks like it doesn't work either.

I made some test on my Linux and I think I reproduce part of the problem on my machine, by starting with -dR (no reuseport) and by using the peers AND the "expose-fd listeners". Could you try to comment the "expose-fd listeners" and start without -x, and see if it works?

Also, in master-worker mode, you don't need to start with -x and -sf, these arguments are called automatically during a kill -USR2.

We might need more of the truss output to be able to understand what's going on.

**Comment by sreboot** [comment] 2020-01-13 20:15
Thanks for looking into this.

Re-tested with expose-fd listeners disabled, the output is below. Basically exits after the last line.

```
# haproxy -f /opt/local/etc/haproxy.cfg -db
[NOTICE] 012/194955 (617880) : New worker #1 (617881) forked
[WARNING] 012/194958 (617880) : Reexecuting Master process
[WARNING] 012/194958 (617881) : Pausing frontend GLOBAL.
[WARNING] 012/194958 (617881) : Pausing frontend c-proxy.
[WARNING] 012/194958 (617881) : Pausing frontend http-in.
[WARNING] 012/194958 (617881) : Pausing frontend stats.
[WARNING] 012/194958 (617881) : Pausing proxy hap01.
[ALERT] 012/194958 (617880) : Starting frontend c-proxy: cannot bind socket [0.0.0.0:3128]
[ALERT] 012/194958 (617880) : Starting frontend http-in: cannot bind socket [0.0.0.0:80]
[ALERT] 012/194958 (617880) : Starting frontend stats: cannot bind socket [0.0.0.0:8080]
[WARNING] 012/195000 (617881) : Enabling frontend GLOBAL.
[WARNING] 012/195000 (617881) : Enabling frontend c-proxy.
[WARNING] 012/195000 (617881) : Enabling frontend http-in.
[WARNING] 012/195000 (617881) : Enabling frontend stats.
[WARNING] 012/195000 (617881) : Enabling proxy hap01.
```

The same with truss (last few lines):
```
[ALERT] 012/195410 (617974) : 617974:   write(2, " [ A L E R T ]   0 1 2 /".., 30)      = 30
Starting frontend c-proxy: cannot bind socket [0.0.0.0:3128]
617974: write(2, " S t a r t i n g   f r o".., 64)      = 64
617974: so_socket(PF_INET, SOCK_STREAM, IPPROTO_TCP, 0x00000000, SOV_DEFAULT) = 8
617974: fcntl(8, F_SETFL, FNONBLOCK)                    = 0
617974: setsockopt(8, SOL_SOCKET, SO_REUSEADDR, 0x005C17A8, 4, SOV_DEFAULT) = 0
617974: getsockopt(8, SOL_SOCKET, SO_LINGER, 0xFFFFFA7FFFDFF598, 0xFFFFFA7FFFDFF594, SOV_DEFAULT) = 0
617974: setsockopt(8, SOL_SOCKET, SO_LINGER, 0xFFFFFA7FFFDFF598, 8, SOV_DEFAULT) = 0
617974: bind(8, 0x0085D508, 16, SOV_SOCKBSD)            Err#125 EADDRINUSE
617974: close(8)                                        = 0
617974: getpid()                                        = 617974 [617973]
[ALERT] 012/195410 (617974) : 617974:   write(2, " [ A L E R T ]   0 1 2 /".., 30)      = 30
Starting frontend http-in: cannot bind socket [0.0.0.0:80]
617974: write(2, " S t a r t i n g   f r o".., 59)      = 59
617974: so_socket(PF_INET, SOCK_STREAM, IPPROTO_TCP, 0x00000000, SOV_DEFAULT) = 8
617974: fcntl(8, F_SETFL, FNONBLOCK)                    = 0
617974: setsockopt(8, SOL_SOCKET, SO_REUSEADDR, 0x005C17A8, 4, SOV_DEFAULT) = 0
617974: getsockopt(8, SOL_SOCKET, SO_LINGER, 0xFFFFFA7FFFDFF598, 0xFFFFFA7FFFDFF594, SOV_DEFAULT) = 0
617974: setsockopt(8, SOL_SOCKET, SO_LINGER, 0xFFFFFA7FFFDFF598, 8, SOV_DEFAULT) = 0
617974: bind(8, 0x0085D208, 16, SOV_SOCKBSD)            Err#125 EADDRINUSE
617974: close(8)                                        = 0
617974: getpid()                                        = 617974 [617973]
[ALERT] 012/195410 (617974) : 617974:   write(2, " [ A L E R T ]   0 1 2 /".., 30)      = 30
Starting frontend stats: cannot bind socket [0.0.0.0:8080]
617974: write(2, " S t a r t i n g   f r o".., 59)      = 59
617974: close(7)                                        = 0
617974: kill(617975, SIGTTIN)                           = 0
617975:     Received signal #26, SIGTTIN, in port_getn() [caught]
617975:       siginfo: SIG#0
617975: port_getn(3, 0x00EB7010, 200, 1, 0xFFFFFA7FFFDFF810) Err#91 ERESTART
617975: lwp_sigmask(SIG_SETMASK, 0x00000000, 0x00000000, 0x00000000, 0x00000000) = 0xFFBFFEFF [0xFFFFFFFF]
617975: sigaction(SIGTTIN, 0xFFFFFA7FFFDFF170, 0xFFFFFA7FFFDFF220) = 0
617975: setcontext(0xFFFFFA7FFFDFEF00)
617975: lwp_sigmask(SIG_SETMASK, 0xEFBFF877, 0xFFFFFFF7, 0x000003FF, 0x00000000) = 0xFFBFFEFF [0xFFFFFFFF]
617975: getpid()                                        = 617975 [617974]
[WARNING] 012/195412 (617975) : 617975: write(2, " [ W A R N I N G ]   0 1".., 32)      = 32
Enabling frontend GLOBAL.
617975: write(2, " E n a b l i n g   f r o".., 26)      = 26
617975: getpid()                                        = 617975 [617974]
617974: _exit(1)
[WARNING] 012/195412 (617975) : 617975: write(2, " [ W A R N I N G ]   0 1".., 32)      = 32
Enabling frontend c-proxy.
617975: write(2, " E n a b l i n g   f r o".., 30)      = 30
617975: getpid()                                        = 617975 [617974]
[WARNING] 012/195412 (617975) : 617975: write(2, " [ W A R N I N G ]   0 1".., 32)      = 32
Enabling frontend http-in.
617975: write(2, " E n a b l i n g   f r o".., 27)      = 27
617975: getpid()                                        = 617975 [617974]
[WARNING] 012/195412 (617975) : 617975: write(2, " [ W A R N I N G ]   0 1".., 32)      = 32
Enabling frontend stats.
617975: write(2, " E n a b l i n g   f r o".., 25)      = 25
617975: getpid()                                        = 617975 [617974]
[WARNING] 012/195412 (617975) : 617975: write(2, " [ W A R N I N G ]   0 1".., 32)      = 32
Enabling proxy hap01.
617975: write(2, " E n a b l i n g   p r o".., 25)      = 25
617975: lwp_sigmask(SIG_SETMASK, 0x00000000, 0x00000000, 0x00000000, 0x00000000) = 0xFFBFFEFF [0xFFFFFFFF]
617975: port_associate(3, 4, 0x00000006, 0x00000001, 0x00000000) = 0
617975: port_associate(3, 4, 0x00000004, 0x00000001, 0x00000000) = 0
617975: port_getn(3, 0x00EB7010, 200, 1, 0xFFFFFA7FFFDFF810) = 0 [1]
617975: port_associate(3, 4, 0x00000004, 0x00000001, 0x00000000) = 0
617975: recv(4, 0xFFFFFA7FFFDFF807, 1, 2)               = 0
617975: _exit(1)
```

This runs on Joyent's SmartOS which is based off Illumos (Originally Solaris).

It seems SmartOS does not expose SO_REUSEPORT in native zones (this is where we run haproxy right now): https://smartos.org/bugview/OS-4543. 

But there is some level of support in its LX (Linux containers) branded zones: https://smartos.org/bugview/OS-4018.

Will ask Joyent to clarify if this is indeed the case.

The socket file is working: ```srwxrwxrwx   1 root     root           0 Jan 13 20:12 /var/run/haproxy.sock``` and I can issue commands via socat just fine.

**Comment by wlallemand** [comment] 2020-01-14 16:37
At least I get why the process is leaving, you are using "master-worker" in your configuration file and not -W as a program argument. Once the master try to reload, it failed to bind so it restart in "wait mode" without configuration. However without configuration, it does not know anymore that it is in master-worker mode. People usually put -W in their init script or their systemd unit so we never faced this problem.

**Comment by wlallemand** [comment] 2020-01-14 17:13
You could retry with the fix above or with -W. It won't fix your problem but at least the process won't quit.

**Comment by sreboot** [comment] 2020-01-14 18:49
Works with -W if `expose-fd listeners` is also commented out in the config file. Thanks for debugging this.

**Comment by jlevon** [comment] 2020-01-14 23:35
illumos/SmartOS indeed does not expose SO_REUSEPORT natively: it looks like there were some concern over expected semantics, as they differ between different OSes.

**Comment by sreboot** [comment] 2020-01-15 09:31
Just an FYI the -W flag is missing from the default startup lines in the pkgsrc packages (which is used by SmartOS, but also others too).

The default SmartOS service [manifest.xml](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/haproxy/files/smf/manifest.xml?annotate=1.3) line 13:
```<exec_method type="method" name="start" exec="@PREFIX@/sbin/haproxy -f %{config_file} -D" timeout_seconds="60" />```

**Comment by wlallemand** [comment] 2020-01-15 09:50
I don't know the service manager on SmartOS, but maybe it does not require the master-worker mode. I don't see anything regarding the reload in this manifest.xml file. The mworker mode was adopted by default on major linux distributions because the reload of the previous mode was incompatible with systemd, but nowadays I recommend it for everyone since it provides more things for process management (master CLI, show proc, etc).

**Comment by sreboot** [comment] 2020-01-15 11:31
Trying to sum up the findings so far (please correct me where required):
  1. ~~the missing SO_REUSEPORT in SmartOS should not be an issue here~~
  2. master-worker in the config is correct and -W is also required (for now)
  3. ~~the peers/sticky section is irrelevant in this instance, the issue manifests regardless~~
  4. ~~*expose-fd listeners* is likely not behaving correctly, breaking the retrieval of listening sockets from the old process~~

Keen to do more testing if required and capture additional details with truss (also dtrace is an option). Would need some light guidance on what to test.

**Comment by jlevon** [comment] 2020-01-15 11:47
I'm not sure I've time to dig into this further right now, but just as a data-point: we are using haproxy 2.0.x seamless reload without issues as part of https://github.com/joyent/muppet including, in particular, expose-fd listeners setting. It might be worth comparing your config with what we have there.

**Comment by sreboot** [comment] 2020-01-15 12:16
Crossed out the points in my previous comment. If the peers section is removed from the configuration file, seamless reload works just fine.

**Comment by wlallemand** [comment] 2020-01-15 13:32
I've done some tests under linux, and it appears that the combination of the seamless reload feature (-x / expose-fd) and the peers has the same behavior. I suspect that the peers listeners are not provided by the socket.

And beyond this problem, the new process should be able to pause the listeners of the previous one if it didn't get all previous sockets, this part probably need some rework.

**Comment by wlallemand** [comment] 2020-01-15 13:42
I found this exact problem in the code, I'm fixing it.

**Closed as completed** 2020-01-26 13:46 UTC
Labels: type: bug, status: fixed
