### ISSUE TITLE
src/mux_h2.c: uninitialized variable suspected by coverity (new finding)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1093] opened 2021-02-01 06:47 UTC
```
*** CID 1403563:  Uninitialized variables  (UNINIT)
/src/mux_h2.c: 5430 in h2s_bck_make_req_headers()
5424     
5425            /* encode all headers, stop at empty name. Host is only sent if we
5426             * do not provide an authority.
5427             */
5428            for (hdr = 0; hdr < sizeof(list)/sizeof(list[0]); hdr++) {
5429                    struct ist n = list[hdr].n;
>>>     CID 1403563:  Uninitialized variables  (UNINIT)
>>>     Using uninitialized value "list[hdr].v".
5430                    struct ist v = list[hdr].v;
5431     
5432                    /* these ones do not exist in H2 and must be dropped. */
5433                    if (isteq(n, ist("connection")) ||
5434                        (auth.len && isteq(n, ist("host"))) ||
5435                        isteq(n, ist("proxy-connection")) ||
```

**Comment by capflam** [comment] 2021-02-01 10:38
Duplicate of #1084

**Closed as completed by capflam** 2021-02-01 10:38 UTC
Labels: type: code-report
