### ISSUE TITLE
TCP connections hanging or incorrectly closed for HEAD requests

### ISSUE THREAD

**Issue by surki** [haproxy/haproxy#1101] opened 2021-02-03 14:17 UTC
## Detailed description of the problem

We have a lua script that responds to certain requests. The lua script, after executing bit of self-contained business logic, responds with status code and a small body. It had a bug where even for HEAD requests, it was sending a body. If the connection reuse is enabled (which we do), this leads to randomly the following behavior:

 - TCP connection hanging at haproxy end, leading to client sending next request but not getting a response
 - Or haproxy does a `close()` without a `Connection: close` header, leading to client seeing a TCP RST (strangly I also don't see a FIN packet being received by client, though HAProxy strace (and filter trace below) shows a socket `close()`)

This service is part of a larger Istio based service mesh, so we see random TCP RSTs or connection hanging all over the place.

This may not just be confined to lua based response, may also have with proper proxied backend (i.e., not just responding from lua, proxying it to backend), I have not tested this issue in that setup though.

## Expected behavior

Even when the response is incorrect, haproxy should not misbehave, either it should enable connection reuse or if not possible, properly close the connection (`Connection: Close` etc)

## Steps to reproduce the behavior

1. Run HAProxy with the configuration give below

2. Run the following curl command:

We should either see a hang or a connection reset and curl creating a new connection sending the request (curl has automatic retry). The below example shows connection reset (note the `Recv failure: Connection reset by peer` line between two requests):

```bash
$ curl -v -I http://127.0.0.1:8080/foo --next -I http://127.0.0.1:8080/foo

*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> HEAD /foo HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< content-type: text/plain
content-type: text/plain
< content-length: 7
content-length: 7

<
* Connection #0 to host 127.0.0.1 left intact
* Found bundle for host 127.0.0.1: 0x55da316d3940 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> HEAD /foo HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* Connection died, retrying a fresh connect(retry count: 1)
* Closing connection 0
* Issue another request to this URL: 'http://127.0.0.1:8080/foo'
* Hostname 127.0.0.1 was found in DNS cache
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#1)
> HEAD /foo HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< content-type: text/plain
content-type: text/plain
< content-length: 7
content-length: 7

<
* Connection #1 to host 127.0.0.1 left intact

```

## What is your configuration?

```
global
  lua-load /etc/haproxy/lua/foo.lua
  debug

defaults
  mode                    http
  option                  redispatch
  retries                 3
  timeout http-request    10s
  timeout queue           1m
  timeout connect         10s
  timeout client          1m
  timeout server          1m
  timeout http-keep-alive 10s
  timeout check           10s
  maxconn                 3000

frontend incoming
  bind *:8080

  filter trace

  http-request use-service lua.foo if { path_beg /foo }
```

Corresponding lua script:

```
core.register_service("foo", "http", function(applet)
  local response = "success"                         

  applet:set_status(200)
  applet:add_header("content-length", string.len(response))
  applet:add_header("content-type", "text/plain")
  applet:start_response()
  applet:send(response)
  return
end)
```

## Output of `haproxy -vv` and `uname -a`

```
./haproxy -vv
HA-Proxy version 2.0.20-f127c3-9 2021/02/01 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_LINUX_TPROXY=1 USE_LUA=1 USE_TFO=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO -OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace


$ uname -r
5.10.11-arch1-1
```

## Additional information (if helpful)

HAProxy trace filter logs

When connection hangs:

```
1612359444.930144 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00064035 0x00000000] trace_attach             : filter-type=frontend
1612359444.930144 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00064035 0x00000000] trace_stream_start
0000000a:incoming.accept(0004)=001c from [127.0.0.1:51158] ALPN=<none>
1612359444.930251 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00064035 0x00000000] trace_chn_start_analyze  : channel=REQUEST    - mode=HTX   (frontend)
1612359444.930251 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00064034 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_WAIT_HTTP - step=PRE
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00064034 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_WAIT_HTTP - step=PRE
0000000a:incoming.clireq[001c:ffffffff]: HEAD /foo HTTP/1.1
0000000a:incoming.clihdr[001c:ffffffff]: host: 127.0.0.1:8080
0000000a:incoming.clihdr[001c:ffffffff]: user-agent: curl/7.74.0
0000000a:incoming.clihdr[001c:ffffffff]: accept: */*
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00064030 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_WAIT_HTTP - step=POST
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00064030 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_HTTP_PROCESS_FE - step=PRE
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x0004c000 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_HTTP_PROCESS_FE - step=POST
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x0004c000 0x00000000] trace_http_headers       : channel=REQUEST    - mode=HTX   (frontend)
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x0004c000 0x00000000]         HEAD /foo HTTP/1.1
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x0004c000 0x00000000]         host: 127.0.0.1:8080
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x0004c000 0x00000000]         user-agent: curl/7.74.0
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x0004c000 0x00000000]         accept: */*
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x00000000] trace_http_payload       : channel=REQUEST    - mode=HTX   (frontend) - offset=89 - len=1 - forward=1
1612359444.930328 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x00000000] trace_http_end           : channel=REQUEST    - mode=HTX   (frontend)
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x33480000] trace_chn_start_analyze  : channel=RESPONSE   - mode=HTX   (frontend)
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x33400000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_WAIT_HTTP - step=PRE
0000000a:incoming.srvrep[001c:ffffffff]: HTTP/1.1 200 OK
0000000a:incoming.srvhdr[001c:ffffffff]: content-type: text/plain
0000000a:incoming.srvhdr[001c:ffffffff]: content-length: 7
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x33000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_WAIT_HTTP - step=POST
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x33000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_HTTP_PROCESS_FE/BE - step=PRE
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x26000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_HTTP_PROCESS_FE/BE - step=POST
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x26000000] trace_http_headers       : channel=RESPONSE   - mode=HTX   (frontend)
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x26000000]         HTTP/1.1 200 OK
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x26000000]         content-type: text/plain
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x26000000]         content-length: 7
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x24000000] trace_http_payload       : channel=RESPONSE   - mode=HTX   (frontend) - offset=75 - len=8 - forward=8
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00048000 0x24000000] trace_http_end           : channel=RESPONSE   - mode=HTX   (frontend)
1612359444.930528 [TRACE/incoming      ] [strm 0x7fdefc011b40(a) 0x00040000 0x24000000] trace_chn_end_analyze    : channel=REQUEST    - mode=HTX   (frontend)
0000000a:incoming.srvcls[001c:ffffffff]
```

Also, it seems the recv queue has some data(I suppose the next request that curl has sent) but HAProxy is not reading:

```
$ ss -tn
State              Recv-Q              Send-Q                             Local Address:Port                             Peer Address:Port               Process
ESTAB              46                  0                                     172.17.0.2:8080                               172.17.0.1:49140
```

When connection gets reset:

```
1612359440.107456 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00064035 0x00000000] trace_attach             : filter-type=frontend
1612359440.107456 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00064035 0x00000000] trace_stream_start
00000008:incoming.accept(0004)=001c from [127.0.0.1:51146] ALPN=<none>
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00064035 0x00000000] trace_chn_start_analyze  : channel=REQUEST    - mode=HTX   (frontend)
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00064034 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_WAIT_HTTP - step=PRE
00000008:incoming.clireq[001c:ffffffff]: HEAD /foo HTTP/1.1
00000008:incoming.clihdr[001c:ffffffff]: host: 127.0.0.1:8080
00000008:incoming.clihdr[001c:ffffffff]: user-agent: curl/7.74.0
00000008:incoming.clihdr[001c:ffffffff]: accept: */*
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00064030 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_WAIT_HTTP - step=POST
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00064030 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_HTTP_PROCESS_FE - step=PRE
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x0004c000 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_HTTP_PROCESS_FE - step=POST
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x0004c000 0x00000000] trace_http_headers       : channel=REQUEST    - mode=HTX   (frontend)
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x0004c000 0x00000000]         HEAD /foo HTTP/1.1
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x0004c000 0x00000000]         host: 127.0.0.1:8080
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x0004c000 0x00000000]         user-agent: curl/7.74.0
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x0004c000 0x00000000]         accept: */*
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x00000000] trace_http_payload       : channel=REQUEST    - mode=HTX   (frontend) - offset=89 - len=1 - forward=1
1612359440.107537 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x00000000] trace_http_end           : channel=REQUEST    - mode=HTX   (frontend)
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x33480000] trace_chn_start_analyze  : channel=RESPONSE   - mode=HTX   (frontend)
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x33400000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_WAIT_HTTP - step=PRE
00000008:incoming.srvrep[001c:ffffffff]: HTTP/1.1 200 OK
00000008:incoming.srvhdr[001c:ffffffff]: content-type: text/plain
00000008:incoming.srvhdr[001c:ffffffff]: content-length: 7
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x33000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_WAIT_HTTP - step=POST
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x33000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_HTTP_PROCESS_FE/BE - step=PRE
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x26000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_HTTP_PROCESS_FE/BE - step=POST
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x26000000] trace_http_headers       : channel=RESPONSE   - mode=HTX   (frontend)
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x26000000]         HTTP/1.1 200 OK
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x26000000]         content-type: text/plain
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x26000000]         content-length: 7
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x24000000] trace_http_payload       : channel=RESPONSE   - mode=HTX   (frontend) - offset=75 - len=8 - forward=8
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00048000 0x24000000] trace_http_end           : channel=RESPONSE   - mode=HTX   (frontend)
1612359440.107768 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00040000 0x24000000] trace_chn_end_analyze    : channel=REQUEST    - mode=HTX   (frontend)
00000008:incoming.srvcls[001c:ffffffff]
1612359440.108457 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00040000 0x20000000] trace_chn_end_analyze    : channel=RESPONSE   - mode=HTX   (frontend)
00000008:incoming.clicls[001c:ffffffff]
00000008:incoming.closed[001c:ffffffff]
1612359440.108457 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00000000 0x00000000] trace_stream_stop
1612359440.108457 [TRACE/incoming      ] [strm 0x5618986f45a0(8) 0x00000000 0x00000000] trace_detach             : filter-type=frontend
1612359440.108926 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00064035 0x00000000] trace_attach             : filter-type=frontend
1612359440.108926 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00064035 0x00000000] trace_stream_start
00000009:incoming.accept(0004)=001c from [127.0.0.1:51148] ALPN=<none>
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00064035 0x00000000] trace_chn_start_analyze  : channel=REQUEST    - mode=HTX   (frontend)
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00064034 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_WAIT_HTTP - step=PRE
00000009:incoming.clireq[001c:ffffffff]: HEAD /foo HTTP/1.1
00000009:incoming.clihdr[001c:ffffffff]: host: 127.0.0.1:8080
00000009:incoming.clihdr[001c:ffffffff]: user-agent: curl/7.74.0
00000009:incoming.clihdr[001c:ffffffff]: accept: */*
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00064030 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_WAIT_HTTP - step=POST
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00064030 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_HTTP_PROCESS_FE - step=PRE
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x0004c000 0x00000000] trace_chn_analyze        : channel=REQUEST    - mode=HTX   (frontend) - analyzer=AN_REQ_HTTP_PROCESS_FE - step=POST
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x0004c000 0x00000000] trace_http_headers       : channel=REQUEST    - mode=HTX   (frontend)
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x0004c000 0x00000000]         HEAD /foo HTTP/1.1
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x0004c000 0x00000000]         host: 127.0.0.1:8080
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x0004c000 0x00000000]         user-agent: curl/7.74.0
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x0004c000 0x00000000]         accept: */*
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x00000000] trace_http_payload       : channel=REQUEST    - mode=HTX   (frontend) - offset=89 - len=1 - forward=1
1612359440.109036 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x00000000] trace_http_end           : channel=REQUEST    - mode=HTX   (frontend)
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x33480000] trace_chn_start_analyze  : channel=RESPONSE   - mode=HTX   (frontend)
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x33400000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_WAIT_HTTP - step=PRE
00000009:incoming.srvrep[001c:ffffffff]: HTTP/1.1 200 OK
00000009:incoming.srvhdr[001c:ffffffff]: content-type: text/plain
00000009:incoming.srvhdr[001c:ffffffff]: content-length: 7
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x33000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_WAIT_HTTP - step=POST
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x33000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_HTTP_PROCESS_FE/BE - step=PRE
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x26000000] trace_chn_analyze        : channel=RESPONSE   - mode=HTX   (frontend) - analyzer=AN_RES_HTTP_PROCESS_FE/BE - step=POST
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x26000000] trace_http_headers       : channel=RESPONSE   - mode=HTX   (frontend)
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x26000000]         HTTP/1.1 200 OK
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x26000000]         content-type: text/plain
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x26000000]         content-length: 7
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x24000000] trace_http_payload       : channel=RESPONSE   - mode=HTX   (frontend) - offset=75 - len=8 - forward=8
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00048000 0x24000000] trace_http_end           : channel=RESPONSE   - mode=HTX   (frontend)
1612359440.109287 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00040000 0x24000000] trace_chn_end_analyze    : channel=REQUEST    - mode=HTX   (frontend)
00000009:incoming.srvcls[001c:ffffffff]
1612359440.109670 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00040000 0x20000000] trace_chn_end_analyze    : channel=RESPONSE   - mode=HTX   (frontend)
00000009:incoming.clicls[001c:ffffffff]
00000009:incoming.closed[001c:ffffffff]
1612359440.109670 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00000000 0x00000000] trace_stream_stop
1612359440.109670 [TRACE/incoming      ] [strm 0x7fdf08012210(9) 0x00000000 0x00000000] trace_detach             : filter-type=frontend
```

**Comment by a-denoyelle** [comment] 2021-02-03 15:52
Thanks for your report,
I can reproduce the issue with your scenario, I will investigate it.

**Comment by surki** [comment] 2021-02-04 11:18
Just for closure to answer this:

> strangly I also don't see a FIN packet being received by client, though HAProxy strace (and filter trace below) shows a socket close()

Before the haproxy calls `close()`, the client has sent the data for next request, so its sitting in the recv queue (of haproxy). With pending data in recv queue calling `close()` sends a TCP RST to client (to inform the potential data loss etc).

**Comment by wtarreau** [comment] 2021-02-04 11:31
Just a point, what you're observing regarding the RST on close when client sends more data is normal, and a client may only reuse a connection if it is able to try again and knows the request is idempotent or has a way to know it's retry-safe (see https://tools.ietf.org/html/rfc7230#section-6.3.1). Of course we all know that in practice there are limits to this, but the absence of `connection: close` is in no way a promise that a connection will stay opened forever. By the way the first cause of such closed connections in general is that they're idling too long. We try as much as we can to emit the `close` token when we know for sure the connection will be closed, but in many situations you don't know and a client must always be prepared to this. This is by the way why haproxy itself implements various degrees of connection reuse, and by default doesn't send non-idempotent requests over non-proven persistent connections (`http-reuse safe`).

**Comment by surki** [comment] 2021-02-08 05:28
Thanks @wtarreau for the detailed explanation.

In our case, the client (Istio/Envoy) has been configured to handle those scenarios: we have idle connection timeout aligned with HAProxy timeouts, retries (on connection reset, certain 5xx etc). Its just that in this specific scenario, HAProxy seems to get into some kind of weird state (due to the bug in our HAProxy/Lua script). Even though we fixed our Lua script, but wanted to make sure to report this and get it fixed as this opens a possibility for DoS attack (via tcp connection poisoning), or worst might lead to some kind of http request smuggling.

@a-denoyelle Please let me know if you need any other information and/or any help in testing out a potential fix.

**Comment by a-denoyelle** [comment] 2021-02-08 07:49
In fact, we have designed a solution with @capflam but we were not sure about the implication and possible regression in other use cases with the fix. Personally I think it looks reasonably safe but I definitely do not have the big picture on it, what is your opinion @capflam ?

**Comment by wtarreau** [comment] 2021-02-08 08:00
@surki regarding Lua scripts, we've progressively made their messaging stricter. Originally you would produce HTTP responses at the byte level, which made it possible to emit totally invalid messages. Over time it became harder and harder but we had to handle that situation to save users from rewriting the Lua code; some of them had errors there that they were not even aware of (e.g. invalid chars in header names, misplaced CRLF, body where not expected etc). In latest 2.4-dev, we take care of silently dropping bodies from bodyless responses for example. But this is very delicate and I'm not even sure whether all of this will be backported, given that at the moment, the risks are only caused by user scripts, which is not much different from having a bogus configuration.

But I agree with you that we need to do our best to save the users from shooting themselves in the foot with bogus scripts (and HTX since 2.0 has improved the situation a lot here for them, even if that added difficulty to us :-)).

**Comment by capflam** [comment] 2021-02-08 13:21
@a-denoyelle, it should be good, especially when the "invalid" response comes from a lua script. However, it is handled as a client abort because the mux on the client side decides to abort. For a lua script, the termination flags are still "LR--". So, it is not a problem. For a server response, it will be flagged as "CD--".  It may be considered as a bug, but it is a deeper problem. We know we have some flaws in the way server errors may be reported by the client side, and the opposite. We need to find some time to tackle this problem. In the mean time, I hope, the fix is thus good enough. Note that's only applicable to HTTP/2 servers. For HTTP/1 servers, responses to HEAD requests are considered to have no body. If a buggy server try to send a body, it will be parsed as a new response.

**Comment by surki** [comment] 2021-02-12 11:24
@capflam regarding this

>  For HTTP/1 servers, responses to HEAD requests are considered to have no body. If a buggy server try to send a body, it will be parsed as a new response.

does it mean it can be confused as a response to the next request? (assuming persistent connections)

**Comment by capflam** [comment] 2021-02-12 17:01
Well, in practice, probably not. Because, if some data remain unparsed on the server side when the HTTP transaction is finished (both the request and the response finished), the connection is closed. Because it is not expected and we don't know how to handle these data. The server connection is also closed when it is idle if some data are received. So if the response payload to a HEAD request is delayed, the result is the same. Most of time, this case happens when the server return a 408-request-time-out response.

However, if the response payload is delayed and the connection is reused for a new request, these data will be parsed as the response to the new request.

**Comment by capflam** [comment] 2021-03-01 20:56
Ok, it should be fixed now. The commit fixing the bug in 2.0 is 192333e6 : 

````
BUG/MINOR: mux-h1: Immediately report H1C errors from h1_snd_buf()

In case an H1 stream tries to send while on error occurred on its underlying
H1 connection, we must report the error. The way the stream-interface is
synchronously notified of the error. It seems to only be a problem on the
2.0. Probably because the scheduling has changed in upper versions. On the
2.0, it prevent the stream to be notified of errors, when for instance, a
payload is found in a response to a HEAD request. Not always though.

This patch must be backported as far as 2.0 because, on 2.0, it should fix the
issue #1101. There is no upstream ID for this commit because on the 2.4, this
fix already exists, it is part of non-backportable commit.
````

**Closed as completed** 2021-03-02 15:34 UTC
Labels: type: bug, status: fixed

**Comment by skaffille** [comment] 2024-10-04 13:20
Is this really fixed?

We observed similar behavior in HAProxy versions 2.9.9 and 2.9.11, but for 2.6.6 and 2.8.11 it is working.
We are running HAProxy on k8s behind an AWS ALB.

HEAD request succeeds for the first request. A subsequent request hangs for about 60s and we receive a 502 error (possibly from the AWS ALB in front of the HAProxy).

**Comment by capflam** [comment] 2024-10-04 13:32
The issue is quite old now. So it could be good to elaborate a bit because it is probably another issue. I guess HEAD requests are sent on the same connection. Do you have a way to isolate the issue on a test platform ?   It could be helpful to enable the H1 traces. Otherwise, you can possible get a network capture (if not in SSL).

**Comment by skaffille** [comment] 2024-10-04 14:03
Yes, they are on the same connection.

I need some time to create a scenario, which I can provide here.

**Comment by capflam** [comment] 2024-10-04 14:06
Ok nice. On my side I tested 2 HEAD requests on the same connection and it works as expected. I added a non-null `content-length` to be sure, and this works too. So at least, it is not a so obvious issue.

**Comment by skaffille** [comment] 2024-10-08 05:57
I have a running test scenario ... on local (kind) cluster using curl for multiple HEAD requests over the same connection it works. Now I have to retry it on an AWS installation with a LoadBalancer in front ... 

I will keep you informed
