### ISSUE TITLE
2,8:{1,2,3}: missing git tag

### ISSUE THREAD

**Issue by kloczek** [haproxy/haproxy#2303] opened 2023-09-25 23:28 UTC
### Detailed Description of the Problem

According to https://haproxy.org/ latest 2.8.x version is 2.8.3 however here in git repo there is no corresponding git tags for 2.8.{1,2,3}.

### Expected Behavior
In git repo should be possible to find all versions git tags.

**Comment by chipitsine** [comment] 2023-09-26 06:40
?

https://github.com/haproxy/haproxy/issues/1318

**Comment by TimWolla** [comment] 2023-09-26 08:00
Duplicate of #1318

**Closed as not planned by TimWolla** 2023-09-26 08:00 UTC
Labels: type: bug, status: duplicate

**Comment by kloczek** [comment] 2023-09-26 08:03
Gosh .. forgot add note about that in my spec file that I already asked about that 😋 
Sorry.

BTW why not merge that branch into one repo to have everything in one place? 🤔
