### ISSUE TITLE
Segfault with using mix mode tcp/h2/h1 with ssl termination

### ISSUE THREAD

**Issue by weikinhuang** [haproxy/haproxy#196] opened 2019-07-26 19:06 UTC
## Output of `haproxy -vv` and `uname -a`

```
docker run -it --rm haproxy:latest haproxy -vv
HA-Proxy version 2.0.3 2019/07/23 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1c  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

```

```
Linux d7810c843e42 4.19.31-coreos #1 SMP Mon Mar 25 15:47:46 -00 2019 x86_64 GNU/Linux
```

#### docker-compose.yaml
```
version: '2'

services:
  haproxy-1:
    image: haproxy:2.0.3
    ports:
      - "8443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./tcp.lan.pem:/etc/ssl/haproxy/tcp.lan.pem

  http:
    image: node:12-alpine
    command: ["node", "/src/x.js"]
    volumes:
      - ./echo.js:/src/echo.js:ro

  sshd:
    image: rastasheep/ubuntu-sshd:18.04
```

#### haproxy.cfg

This is a much simplified version of a much more complex autogenerated config file I'm using as a custom k8s ingress.

```
global
  log           stdout format raw local0
  log           stderr format raw local1 warning
  pidfile       /var/run/haproxy.pid
  group nogroup
  user nobody
  unix-bind user nobody group nogroup

defaults
  log       global

  # tcp options
  option splice-response
  option http-keep-alive
  option clitcpka
  option srvtcpka
  option tcp-smart-accept
  option tcp-smart-connect
  option contstats

  option http-server-close
  option redispatch

  retries 3

  timeout connect         10s
  timeout client          60s
  timeout server          60s

  option httplog

###############################################################################
frontend https.http.ingress.443
bind        *:443 ssl crt "/etc/ssl/haproxy/" alpn h2,http/1.1
  mode tcp

  option tcplog

  acl speak_alpn_h2 ssl_fc_alpn -i h2

  tcp-request inspect-delay 5s
  tcp-request content accept if HTTP

  use_backend https.proxy.tcp.lan.0.alpn if speak_alpn_h2
  use_backend https.proxy.tcp.lan.0.http if HTTP
  use_backend tcp.sshd.default if ! HTTP ! speak_alpn_h2

  default_backend https.proxy.tcp.lan.0.http
  #default_backend https.proxy.tcp.lan.0.alpn

###############################################################################
frontend https.proxy.tcp.lan.0.alpn
  bind        unix@/var/run/haproxy-https.proxy.tcp.lan.0.alpn.sock  proto h2 accept-proxy
  mode http

  default_backend http.h2.default

frontend https.proxy.tcp.lan.0.http
  bind        unix@/var/run/haproxy-https.proxy.tcp.lan.0.http.sock              accept-proxy
  mode http

  default_backend http.h1.default

###############################################################################
backend https.proxy.tcp.lan.0.http
  mode http
  server socket_0 unix@/var/run/haproxy-https.proxy.tcp.lan.0.http.sock send-proxy-v2

backend https.proxy.tcp.lan.0.alpn
  # changing this to tcp works, but then I can't manipulate the request (add headers for ssl info)
  mode http
  server socket_0 unix@/var/run/haproxy-https.proxy.tcp.lan.0.alpn.sock send-proxy-v2

###############################################################################
backend http.h1.default
  mode http
  server h1 http:8080   check   maxconn 1024   weight 1

backend http.h2.default
  mode http
  server h2 http:8081   check   maxconn 1024   weight 1   proto h2

backend tcp.sshd.default
  mode tcp
  server sshd sshd:22   check   maxconn 1024   weight 1
```

#### echo.js
```javascript
const http = require('http');
const http2 = require('http2');

// ============================ plaintext h2 server
const h2cServer = http2.createServer({});
h2cServer.on('error', (err) => console.error(err));
h2cServer.on('request', (_req, res) => res.end('h2\n'));
h2cServer.listen(8081, () => console.log('ready'));

// ============================ plaintext h2 server
const h1Server = http.createServer({});
h1Server.on('error', (err) => console.error(err));
h1Server.on('request', (_req, res) => res.end('h1\n'));
h1Server.listen(8080, () => console.log('ready'));
```

## Steps to reproduce the behavior

1. start the above docker-compose file with `docker-compose up`
2. in another terminal run `curl -vvv --resolve tcp.lan:8443:$(docker-machine ip default) https://tcp.lan:8443 -k -i --http2`
3. request fails

## Actual behavior

After running the curl request there is a segfault and crashes haproxy (if not in worker mode)

If I change the mode to tcp in the `https.proxy.tcp.lan.0.alpn` backend it'll properly respond with `h2`. But then I wouldn't be able to add headers and other request manipulation in that backend.

```
$ curl -vvv --resolve tcp.lan:8443:$(docker-machine ip default) https://tcp.lan:8443 -k -i --http2

* Added tcp.lan:8443:192.168.8.130 to DNS cache
* Rebuilt URL to: https://tcp.lan:8443/
* Hostname tcp.lan was found in DNS cache
*   Trying 192.168.8.130...
* TCP_NODELAY set
* Connected to tcp.lan (192.168.8.130) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: ...
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fffbcf26920)
> GET / HTTP/2
> Host: tcp.lan:8443
> User-Agent: curl/7.58.0
> Accept: */*
> Referer: 
> 
* Unexpected EOF
* Connection #0 to host tcp.lan left intact
curl: (56) Unexpected EOF
```

```
Proxy https.http.ingress.443 started.
Proxy https.proxy.tcp.lan.0 started.
Proxy https.proxy.tcp.lan.0.http started.
Proxy https.proxy.tcp.lan.0.alpn started.
Proxy https.proxy.tcp.lan.0.alpn-tcp started.
Proxy https.proxy.tcp.lan.0 started.
Proxy https.proxy.tcp.lan.0.alpn started.
Proxy https.proxy.tcp.lan.0.http started.
Proxy http.h1.default started.
Proxy http.h2.default started.
Proxy tcp.sshd.default started.
[NOTICE] 206/184454 (1) : New worker #1 (8) forked
192.168.8.1:52282 [26/Jul/2019:18:45:14.534] https.proxy.tcp.lan.0~ tcp.sshd.default/sshd 5006/0/5866 32 -- 2/1/0/0/0 0/0
192.168.8.1:52282 [26/Jul/2019:18:45:14.530] https.http.ingress.443 https.proxy.tcp.lan.0/socket_0 1/3/5870 1907 -- 1/1/0/0/0 0/0
[ALERT] 206/184523 (1) : Current worker #1 (8) exited with code 139 (Segmentation fault)
[ALERT] 206/184523 (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING] 206/184523 (1) : All workers exited. Exiting... (139)
```

However if I run with http1.1 it's ok:
```
$ curl -vvv --resolve tcp.lan:8443:$(docker-machine ip default) https://tcp.lan:8443 -k -i --http1.1

* Added tcp.lan:8443:192.168.8.130 to DNS cache
* Rebuilt URL to: https://tcp.lan:8443/
* Hostname tcp.lan was found in DNS cache
*   Trying 192.168.8.130...
* TCP_NODELAY set
* Connected to tcp.lan (192.168.8.130) port 8443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  ...
> GET / HTTP/1.1
> Host: tcp.lan:8443
> User-Agent: curl/7.58.0
> Accept: */*
> Referer: 
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< date: Fri, 26 Jul 2019 18:39:33 GMT
date: Fri, 26 Jul 2019 18:39:33 GMT
< content-length: 3
content-length: 3

< 
h1
* Connection #0 to host tcp.lan left intact
```

And testing for a tcp passthrough:
```
$ openssl s_client -connect $(docker-machine ip default):8443 -servername tcp.lan -quiet

depth=0 C = US, ST = None, O = None, CN = tcp.lan
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = None, O = None, CN = tcp.lan
verify error:num=21:unable to verify the first certificate
verify return:1
SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
^C
```

## Expected behavior

HAproxy should respond with `h2` when running that request

## Do you have any idea what may have caused this?
no

## Do you have an idea how to solve the issue?
no

**Comment by cognet** [comment] 2019-07-31 16:13
Hi,

I think I understand what the bug is. Can you try the patch attached ?

Thanks !
[patch-h2-upgrade-crash.txt](https://github.com/haproxy/haproxy/files/3452875/patch-h2-upgrade-crash.txt)

**Comment by weikinhuang** [comment] 2019-07-31 16:47
segfault is still happening with the patch against clean 2.0.3, also it broke the h1 connection where haproxy now prematurely closes the h1 stream

on the node server
```
http_1       | events.js:180
http_1       |       throw er; // Unhandled 'error' event
http_1       |       ^
http_1       |
http_1       | Error: read ECONNRESET
http_1       |     at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
http_1       | Emitted 'error' event at:
http_1       |     at emitErrorNT (internal/streams/destroy.js:91:8)
http_1       |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
http_1       |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
http_1       |   errno: 'ECONNRESET',
http_1       |   code: 'ECONNRESET',
http_1       |   syscall: 'read'
http_1       | }
```

how I tested was copy the dockerfile and the docker-entrypoint.sh, add git to the list of required packages then added this line before building:
```
&& ( cd /usr/src/haproxy && git apply - < /patch-h2-upgrade-crash.txt ) \
```

**Comment by weikinhuang** [comment] 2019-07-31 16:53
I also imagine that one can run haproxy and node locally, and move all references to 127.0.0.1 if you don't want to run the container format. would just need to generate new ssl certs instead.

**Comment by cognet** [comment] 2019-07-31 17:15
Yeah that's what I did, and I can't reproduce the problem anymore after the patch, so I'm a bit confused as to what is happenign for you

**Comment by weikinhuang** [comment] 2019-07-31 18:12
can you try inside a docker container, also are you trying this on linux?

**Comment by cognet** [comment] 2019-08-01 11:06
Hi,

Yes I run linux, but I can't easily use docker. I found a flaw in my previous patch however, can you try the attached updated patch ?

Thanks !
[patch-h2-upgrade-crash.txt](https://github.com/haproxy/haproxy/files/3456340/patch-h2-upgrade-crash.txt)

**Comment by weikinhuang** [comment] 2019-08-01 15:01
Hi @cognet I applied the patch against tag 2.0.3, the patch fixes http mode with h2 connections, but breaks the h1 http connections, it just stalls:

```
$ curl -vvv --resolve tcp.test.lan:8443:$(docker-machine ip behance) https://tcp.test.lan:8443 --CACert certs/server-ca.crt -i --http1.1
* Added tcp.test.lan:8443:172.16.0.128 to DNS cache
* Hostname tcp.test.lan was found in DNS cache
*   Trying 172.16.0.128:8443...
* TCP_NODELAY set
* Connected to tcp.test.lan (172.16.0.128) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: certs/server-ca.crt
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=None; O=None; CN=*.test.lan
*  start date: Jul 31 16:35:54 2019 GMT
*  expire date: Jul 28 16:35:54 2029 GMT
*  common name: *.test.lan (matched)
*  issuer: C=US; ST=None; L=None; O=None; CN=Dev CA
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: tcp.test.lan:8443
> User-Agent: curl/7.65.3
> Accept: */*
> Referer:
>
```

then when i `^C` the curl request, this is what happens on the haproxy end:
```
haproxy-1_1  | 172.16.0.1:50316 [01/Aug/2019:14:59:34.459] https.proxy.tcp.test.lan.0~ tcp.tcp.default/tcp 4/0/4 166 -- 1/1/0/0/0 0/0
haproxy-1_1  | [ALERT] 212/150100 (270) : Current worker #1 (272) exited with code 139 (Segmentation fault)
haproxy-1_1  | [ALERT] 212/150100 (270) : exit-on-failure: killing every processes with SIGTERM
haproxy-1_1  | [WARNING] 212/150100 (270) : All workers exited. Exiting... (139)
haproxy-1_1  | Proxy stats started.
```

**Comment by weikinhuang** [comment] 2019-08-01 15:03
Should I try against master?

**Comment by cognet** [comment] 2019-08-01 15:22
Ah sorry when I backported the patch to 2.0, I forgot one bit. Hopefully this version will work for you in H1 as well :)
[patch-h2-upgrade-crash.txt](https://github.com/haproxy/haproxy/files/3457438/patch-h2-upgrade-crash.txt)

**Comment by weikinhuang** [comment] 2019-08-01 15:38
@cognet the patch does fix h1/h2/tcp, however it seems to cut the h1 connection short:

```
http_1       | events.js:180
http_1       |       throw er; // Unhandled 'error' event
http_1       |       ^
http_1       |
http_1       | Error: read ECONNRESET
http_1       |     at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
http_1       | Emitted 'error' event at:
http_1       |     at emitErrorNT (internal/streams/destroy.js:91:8)
http_1       |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
http_1       |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
http_1       |   errno: 'ECONNRESET',
http_1       |   code: 'ECONNRESET',
http_1       |   syscall: 'read'
http_1       | }
test_http_1 exited with code 1
```

**Comment by cognet** [comment] 2019-08-01 15:52
Which one is this, the client or the server ? Do you get the response anyway ? Can you run multiple requests in the same connection ?

**Comment by weikinhuang** [comment] 2019-08-01 15:52
the client is making the curl request, the node server is erroring when the request completes, I do get a full response

**Comment by weikinhuang** [comment] 2019-08-01 15:53
```
$ curl -vvv --resolve tcp.test.lan:8443:$(docker-machine ip behance) https://tcp.test.lan:8443 --CACert certs/server-ca.crt -i --http1.1
* Added tcp.test.lan:8443:172.16.0.128 to DNS cache
* Hostname tcp.test.lan was found in DNS cache
*   Trying 172.16.0.128:8443...
* TCP_NODELAY set
* Connected to tcp.test.lan (172.16.0.128) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: certs/server-ca.crt
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=None; O=None; CN=*.test.lan
*  start date: Jul 31 16:35:54 2019 GMT
*  expire date: Jul 28 16:35:54 2029 GMT
*  common name: *.test.lan (matched)
*  issuer: C=US; ST=None; L=None; O=None; CN=Dev CA
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: tcp.test.lan:8443
> User-Agent: curl/7.65.3
> Accept: */*
> Referer:
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< date: Thu, 01 Aug 2019 15:36:06 GMT
date: Thu, 01 Aug 2019 15:36:06 GMT
< content-length: 519
content-length: 519

<
{
  "proto": "http",
  "httpVersion": "1.1",
  "tlsVersion": "none",
  "method": "GET",
  "url": "http://tcp.test.lan:8443/",
  "origin": "172.16.0.1",
  "headers": {
    "accept": "*/*",
    "connection": "close",
    "host": "tcp.test.lan:8443",
    "referer": "",
    "user-agent": "curl/7.65.3",
    "x-forwarded-for": "172.16.0.1",
    "x-forwarded-proto": "https",
    "x-unique-id": "AC100001:C65E_AC120003:01BB_5D4306E6_0008:00F7:88c316100e40, AC100001:C65E_AC120003:01BB_5D4306E6_0009:00F7:88c316100e40"
  }
}
* Connection #0 to host tcp.test.lan left intact
```

**Comment by weikinhuang** [comment] 2019-08-01 15:55
I'm using the option `option http-server-close`

**Comment by weikinhuang** [comment] 2019-08-01 15:55
same issue without that option

**Comment by cognet** [comment] 2019-08-01 16:02
And it happens for each request, and wasn't happening before my patch, back when H1 worked but H2 did not ? Does it happen immediately after the request, or a few seconds later ?

**Comment by weikinhuang** [comment] 2019-08-01 16:07
correct, this was fine before the patch, as only h2 was broken before, it happens immediately after the curl request is done

**Comment by cognet** [comment] 2019-08-01 16:23
That is strange, I don't see that happening in my tests, even using your example echo.js. I could see that happening with the checks, but not with the request. Any chance you can use tcpdump to capture traffic between haproxy and the server ?

**Comment by weikinhuang** [comment] 2019-08-01 16:33
sure, do you mind giving me some instructions on how i would use tcp dump in this case?

**Comment by weikinhuang** [comment] 2019-08-01 17:25
@cognet here you go:

[haproxy.pcap.tar.gz](https://github.com/haproxy/haproxy/files/3457982/haproxy.pcap.tar.gz)

this is the dump from the beginning (starting the container) to after the http service crashes

**Comment by weikinhuang** [comment] 2019-08-01 21:13
@cognet I'm so sorry, I moved the backend test server to node:

```
const tcpServer = net.createServer((socket) => {
  console.error('connect: tcp');
  socket.on('data', function(data) {
    socket.write('================================================================================\n');
    socket.write(data.toString().trim() + '\n');
    socket.write('================================================================================\n');
    // socket.end();
  });
  socket.on('end', () => console.log('client disconnected'));
});
tcpServer.listen(8001, () => console.log('ready: tcp'));
```

And that's what's actually crashing the process.

If i remove that server, and go back to sshd, your patch works great!

Though I'm curious why it's also making a connection to the tcp server backend when i'm making a http1/2 request

**Comment by weikinhuang** [comment] 2019-08-02 00:30
Thanks a bunch, the patch works great! Is there a chance to get this into 2.0.4?

**Comment by cognet** [comment] 2019-08-02 11:05
Thanks for letting me know ! Yes it will certainly be part of 2.0.4, although I can see that I get connections to the TCP port as well when doing a HTTP connection, so I'm going to investigate that as well

**Comment by weikinhuang** [comment] 2019-08-02 13:00
Thank you so much!

**Comment by weikinhuang** [comment] 2019-08-09 15:27
@cognet This problem is actually worse on 2.0.4 now, as both h1 and h2 now returns a segmentation fault, but tcp request is ok

**Comment by cognet** [comment] 2019-08-09 15:41
Can you reproduce that easily ?

**Comment by weikinhuang** [comment] 2019-08-09 15:44
yes, i'm running a clean version of the 2.0.4 docker image https://github.com/docker-library/haproxy/blob/2e948aa9880c8184c8e001bc5416cabf10d507f1/2.0/Dockerfile, and using the same above scripts and config.


you can update the node server with this tcp segment:
```
const tcpServer = net.createServer((socket) => {
  console.error('connect: tcp');
  socket.on('error', (e) => console.log('tcp: socket error', e));
  socket.on('data', function(data) {
    socket.write('================================================================================\n');
    socket.write(data.toString().trim() + '\n');
    socket.write('================================================================================\n');
    // socket.end();
  });
  socket.on('end', () => console.log('client disconnected'));
});
tcpServer.listen(8001, () => console.log('ready: tcp'));
```

**Comment by cognet** [comment] 2019-08-09 15:55
Ok there was a stupid bug for H1, I just fixed it, the attached patch should apply on 2.0.4 if you're interested in trying, however I can't seem to reproduce it with H2.
[0001-BUG-MEDIUM-proxy-Don-t-forget-the-SF_HTX-flag-when-u.txt](https://github.com/haproxy/haproxy/files/3487077/0001-BUG-MEDIUM-proxy-Don-t-forget-the-SF_HTX-flag-when-u.txt)

**Comment by cognet** [comment] 2019-08-09 15:56
Ah, now I can reproduce it :) let me investigate

**Comment by cognet** [comment] 2019-08-09 16:05
Ok, attached patch will hopefully fix H2.
[0001-BUG-MEDIUM-proxy-Don-t-use-cs_destroy-when-freeing-t.txt](https://github.com/haproxy/haproxy/files/3487119/0001-BUG-MEDIUM-proxy-Don-t-use-cs_destroy-when-freeing-t.txt)

**Comment by weikinhuang** [comment] 2019-08-09 16:23
the second patch fixed h2, but broke h1

**Comment by weikinhuang** [comment] 2019-08-09 16:24
should i apply both?

**Comment by cognet** [comment] 2019-08-09 16:28
Yes, you need both, as they fix 2 separate issues

**Comment by weikinhuang** [comment] 2019-08-09 16:30
awesome, they did indeed fix the problem after I applied both, thanks!

**Comment by cognet** [comment] 2019-08-09 16:31
They should be part of 2.0.5, and hopefully it won't break again for you :)

**Comment by wtarreau** [comment] 2019-08-16 14:33
Now closing since 2.0.5 is about to be issued with these fixes.

**Closed as completed by wtarreau** 2019-08-16 14:33 UTC
Labels: type: bug, severity: medium, status: fixed
