### ISSUE TITLE
Health check is stopped under special conditions. ( haproxy 2.2.x ) 

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#991] opened 2020-12-04 05:43 UTC
## Detailed description of the problem

We've experienced this happen during service.

![image](https://user-images.githubusercontent.com/5656233/101126898-c6bc4980-363f-11eb-98ed-0328919822d0.png)

![image](https://user-images.githubusercontent.com/5656233/101126690-59101d80-363f-11eb-8273-fffcd20b2e78.png)

![image](https://user-images.githubusercontent.com/5656233/101132471-67b00200-364a-11eb-91a7-9cbbd0554e8e.png)

compare 2.1.4 and 2.2.4
![image](https://user-images.githubusercontent.com/5656233/101131845-4dc1ef80-3649-11eb-9f9a-12f69674f068.png)

## Steps to reproduce the behavior
conditions : 
origin server : nginx or apache ( any version )
haproxy : 2.2.4

1. Change nginx l7 check file  ( l7 check down ) and  Haproxy recognized health check-down.
2. nginx stop and Haproxy recognized l4 connection  down 
3. nginx start and Haproxy health status : *L4CON ( exist asterisk ) 
4. haproxy does not operating health check and cpu usage is rapidly increased 

additional condition:
if l7 health check file changed , nginx response 404 error file (not found error) and the file size is over 16k.

## Do you have any idea what may have caused this?
Correct operating is haproxy have to reset packet after getting 404 not found.
but there is no reset.

* 2.2.4 version ( l4 check up and l7 check down ) 
![image](https://user-images.githubusercontent.com/5656233/101126243-6d074f80-363e-11eb-8eca-b0d9df83c664.png)
and no more health check 

* 2.1.4 version ( l4 check up and l7 check down ) 
![image](https://user-images.githubusercontent.com/5656233/101126296-87412d80-363e-11eb-9142-cbb67851068c.png)
there is no problem

**Small error file size works fine. <-- it's important fact.**

## Do you have an idea how to solve the issue?
1. Does not happen in Haproxy 2.1.x 
2. if httpchk use HEAD method there is no problem ( if httpchk use GET method  is occurred )

## Expected behavior
haproxy health check status change

correct change  ( error file : 15k or less )
1. l7 file exist                     status: UP, check: L7OK
2. l7 file remove                status : NOLB, check: L7OKC
3. l4 down(was down)      status: DOWN, check: L4CON
4. l4 up(was up)               status: DOWN, check: L7STS
5. l7 file exist                    status: UP, check: L7OK

weird change  ( error file : over 16k )
1. l7 file exist                     status: UP, check: L7OK
2. l7 file remove                status : NOLB, check: L7OKC
3. l4 down(was down)      status: DOWN, check: L4CON
4. l4 up(was up)               status: DOWN, check: *L4CON or *L7STS ( with asterisk )
5. health check is stopped

**Comment by zino7825** [comment] 2020-12-04 08:50
No problem until 15k error file 
![image](https://user-images.githubusercontent.com/5656233/101142547-18250280-3659-11eb-89de-fe13cd2b7068.png)

**Comment by capflam** [comment] 2020-12-04 09:12
Could you share your redacted HAProxy configuration please ?

**Comment by capflam** [comment] 2020-12-04 09:19
Note also the 2.2.6 was released few days ago and it fixes a major issue regarding the health-checks. Thus you should upgrade. I don't know if this will solve your issue or not. But it remains important to upgrade

**Comment by zino7825** [comment] 2020-12-04 11:21
> Could you share your redacted HAProxy configuration please ?

* backend configuration ( with l7 httpchk )
```
backend xxx.xxx.com
    balance roundrobin
    option httpchk GET /monitor/l7.html HTTP/1.1\r\nHost:\ xxx.xxx.com\r\nUser-Agent:\ nfront-check/1.0\r\nConnection:\ close
    http-check disable-on-404

    server xxx1 10.10.10.10:80 check
    server xxx2 10.10.10.11:80 check
```

**Comment by capflam** [comment] 2020-12-04 12:59
You must upgrade. It is useless to try to figure out what happens if there is still the doubt it is a known fixed bug. If the issue persistent on the 2.2.6, you may try to enable the H1 traces. If the issue is reproducible without traffic it should be really useful to understand what happens.
To do so, you must configure a stats socket in your global section. Then to enable the traces, you may use the following command :
```
echo "trace h1 sink buf0; trace h1 level developer; trace h1 verbosity complete; trace h1 start now; show events buf0 -w"| socat {HA-SOCK-STAT}
```

Another solution is to send me privately a full network capture between HAProxy and your server. What surprises me here is that you don't hit the health-check timeout.

**Comment by zino7825** [comment] 2020-12-05 03:08
@capflam I will try to trace h1.
this connectin status is close_wait.

**Comment by zino7825** [comment] 2020-12-05 04:16
@capflam The log below repeats continuously when tracking the problem situation. (as infinite looping )

It also have a problem when I set the `timeout check 200` 

```
<0>2020-12-05T12:58:42.294926+09:00 [03|h1|4|mux_h1.c:2710] h1_rcv_buf(): leaving : [B] [MSG_DONE, MSG_DATA] - VAL=0 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294928+09:00 [03|h1|4|mux_h1.c:2661] h1_subscribe(): subscribe(recv) : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294929+09:00 [03|h1|4|mux_h1.c:2260] h1_io_cb(): in : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294930+09:00 [03|h1|4|mux_h1.c:2128] h1_send(): entering : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294931+09:00 [03|h1|4|mux_h1.c:2166] h1_send(): leaving with everything sent : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294933+09:00 [03|h1|4|mux_h1.c:2178] h1_send(): leaving : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294934+09:00 [03|h1|4|mux_h1.c:2024] h1_recv(): entering : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294935+09:00 [03|h1|4|/mux_h1.c:367] h1_recv_allowed(): recv not allowed because of (error|read0) on connection : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294936+09:00 [03|h1|4|mux_h1.c:2032] h1_recv(): leaving on !recv_allowed : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294938+09:00 [03|h1|4|mux_h1.c:1995] h1_wake_stream_for_recv(): in : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294939+09:00 [03|h1|2|mux_h1.c:2102] read0 on connection : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294940+09:00 [03|h1|4|mux_h1.c:2113] h1_recv(): leaving : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294942+09:00 [03|h1|4|mux_h1.c:2192] h1_process(): entering : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294943+09:00 [03|h1|2|mux_h1.c:2216] read0 on connection : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294944+09:00 [03|h1|4|mux_h1.c:2229] h1_process(): leaving : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294946+09:00 [03|h1|4|mux_h1.c:2690] h1_rcv_buf(): entering : [B] [MSG_DONE, MSG_DATA] - VAL=8 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294954+09:00 [03|h1|4|mux_h1.c:1417] h1_process_input(): entering : [B] [MSG_DONE, MSG_DATA] - VAL=8 - "HTTP/1.1 404 Not Found" - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
         htx=0x2903600(size=16336,data=16240,used=11,wrap=NO,flags=0x00000000,extra=418,first=0,head=0,tail=10,tail_addr=16240,head_addr=0,end_addr=0)
                [0] type=HTX_BLK_RES_SL    - size=44     - addr=0       HTTP/1.1 404 Not Found
                [1] type=HTX_BLK_HDR       - size=33     - addr=44      date: Sat, 05 Dec 2020 03:58:39 GMT
                [2] type=HTX_BLK_HDR       - size=27     - addr=77      server: Apache/2.4.6 (CentOS)
                [3] type=HTX_BLK_HDR       - size=42     - addr=104     last-modified: Fri, 04 Dec 2020 09:01:06 GMT
                [4] type=HTX_BLK_HDR       - size=24     - addr=146     etag: "4000-5b59fb77a3243"
                [5] type=HTX_BLK_HDR       - size=18     - addr=170     accept-ranges: bytes
                [6] type=HTX_BLK_HDR       - size=19     - addr=188     content-length: 16384
                [7] type=HTX_BLK_HDR       - size=30     - addr=207     vary: Accept-Encoding,User-Agent
                [8] type=HTX_BLK_HDR       - size=36     - addr=237     content-type: text/html; charset=UTF-8
                [9] type=HTX_BLK_EOH       - size=1      - addr=273     <empty>
                [10] type=HTX_BLK_DATA      - size=15966  - addr=274

<0>2020-12-05T12:58:42.294956+09:00 [03|h1|1|mux_h1.c:1452] parsing message payload : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294957+09:00 [03|h1|4|mux_h1.c:1290] h1_process_data(): entering : [B] [MSG_DONE, MSG_DATA] - VAL=8 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294959+09:00 [03|h1|4|mux_h1.c:1293] h1_process_data(): leaving on missing data or error : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294961+09:00 [03|h1|4|mux_h1.c:1323] h1_process_data(): leaving : [B] [MSG_DONE, MSG_DATA] - VAL=0 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294969+09:00 [03|h1|4|mux_h1.c:1535] h1_process_input(): leaving : [B] [MSG_DONE, MSG_DATA] - VAL=0 - "HTTP/1.1 404 Not Found" - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
         htx=0x2903600(size=16336,data=16240,used=11,wrap=NO,flags=0x00000000,extra=418,first=0,head=0,tail=10,tail_addr=16240,head_addr=0,end_addr=0)
                [0] type=HTX_BLK_RES_SL    - size=44     - addr=0       HTTP/1.1 404 Not Found
                [1] type=HTX_BLK_HDR       - size=33     - addr=44      date: Sat, 05 Dec 2020 03:58:39 GMT
                [2] type=HTX_BLK_HDR       - size=27     - addr=77      server: Apache/2.4.6 (CentOS)
                [3] type=HTX_BLK_HDR       - size=42     - addr=104     last-modified: Fri, 04 Dec 2020 09:01:06 GMT
                [4] type=HTX_BLK_HDR       - size=24     - addr=146     etag: "4000-5b59fb77a3243"
                [5] type=HTX_BLK_HDR       - size=18     - addr=170     accept-ranges: bytes
                [6] type=HTX_BLK_HDR       - size=19     - addr=188     content-length: 16384
                [7] type=HTX_BLK_HDR       - size=30     - addr=207     vary: Accept-Encoding,User-Agent
                [8] type=HTX_BLK_HDR       - size=36     - addr=237     content-type: text/html; charset=UTF-8
                [9] type=HTX_BLK_EOH       - size=1      - addr=273     <empty>
                [10] type=HTX_BLK_DATA      - size=15966  - addr=274

<0>2020-12-05T12:58:42.294971+09:00 [03|h1|4|mux_h1.c:2710] h1_rcv_buf(): leaving : [B] [MSG_DONE, MSG_DATA] - VAL=0 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294972+09:00 [03|h1|4|mux_h1.c:2661] h1_subscribe(): subscribe(recv) : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294973+09:00 [03|h1|4|mux_h1.c:2260] h1_io_cb(): in : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294975+09:00 [03|h1|4|mux_h1.c:2128] h1_send(): entering : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294976+09:00 [03|h1|4|mux_h1.c:2166] h1_send(): leaving with everything sent : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294977+09:00 [03|h1|4|mux_h1.c:2178] h1_send(): leaving : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294978+09:00 [03|h1|4|mux_h1.c:2024] h1_recv(): entering : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294979+09:00 [03|h1|4|/mux_h1.c:367] h1_recv_allowed(): recv not allowed because of (error|read0) on connection : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294981+09:00 [03|h1|4|mux_h1.c:2032] h1_recv(): leaving on !recv_allowed : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294984+09:00 [03|h1|4|mux_h1.c:1995] h1_wake_stream_for_recv(): in : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294986+09:00 [03|h1|2|mux_h1.c:2102] read0 on connection : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294988+09:00 [03|h1|4|mux_h1.c:2113] h1_recv(): leaving : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294990+09:00 [03|h1|4|mux_h1.c:2192] h1_process(): entering : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294993+09:00 [03|h1|2|mux_h1.c:2216] read0 on connection : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294995+09:00 [03|h1|4|mux_h1.c:2229] h1_process(): leaving : [B] - h1c=0x7f6400059920(0x00000000) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.294998+09:00 [03|h1|4|mux_h1.c:2690] h1_rcv_buf(): entering : [B] [MSG_DONE, MSG_DATA] - VAL=8 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.295006+09:00 [03|h1|4|mux_h1.c:1417] h1_process_input(): entering : [B] [MSG_DONE, MSG_DATA] - VAL=8 - "HTTP/1.1 404 Not Found" - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
         htx=0x2903600(size=16336,data=16240,used=11,wrap=NO,flags=0x00000000,extra=418,first=0,head=0,tail=10,tail_addr=16240,head_addr=0,end_addr=0)
                [0] type=HTX_BLK_RES_SL    - size=44     - addr=0       HTTP/1.1 404 Not Found
                [1] type=HTX_BLK_HDR       - size=33     - addr=44      date: Sat, 05 Dec 2020 03:58:39 GMT
                [2] type=HTX_BLK_HDR       - size=27     - addr=77      server: Apache/2.4.6 (CentOS)
                [3] type=HTX_BLK_HDR       - size=42     - addr=104     last-modified: Fri, 04 Dec 2020 09:01:06 GMT
                [4] type=HTX_BLK_HDR       - size=24     - addr=146     etag: "4000-5b59fb77a3243"
                [5] type=HTX_BLK_HDR       - size=18     - addr=170     accept-ranges: bytes
                [6] type=HTX_BLK_HDR       - size=19     - addr=188     content-length: 16384
                [7] type=HTX_BLK_HDR       - size=30     - addr=207     vary: Accept-Encoding,User-Agent
                [8] type=HTX_BLK_HDR       - size=36     - addr=237     content-type: text/html; charset=UTF-8
                [9] type=HTX_BLK_EOH       - size=1      - addr=273     <empty>
                [10] type=HTX_BLK_DATA      - size=15966  - addr=274

<0>2020-12-05T12:58:42.295008+09:00 [03|h1|1|mux_h1.c:1452] parsing message payload : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.295010+09:00 [03|h1|4|mux_h1.c:1290] h1_process_data(): entering : [B] [MSG_DONE, MSG_DATA] - VAL=8 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.295011+09:00 [03|h1|4|mux_h1.c:1293] h1_process_data(): leaving on missing data or error : [B] [MSG_DONE, MSG_DATA] - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.295013+09:00 [03|h1|4|mux_h1.c:1323] h1_process_data(): leaving : [B] [MSG_DONE, MSG_DATA] - VAL=0 - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
<0>2020-12-05T12:58:42.295021+09:00 [03|h1|4|mux_h1.c:1535] h1_process_input(): leaving : [B] [MSG_DONE, MSG_DATA] - VAL=0 - "HTTP/1.1 404 Not Found" - h1c=0x7f6400059920(0x00000000) h1s=0x7f6400059ad0(0x00004048) ibuf=418@0x7f640006a550+392/65536 obuf=0@(nil)+0/0
         htx=0x2903600(size=16336,data=16240,used=11,wrap=NO,flags=0x00000000,extra=418,first=0,head=0,tail=10,tail_addr=16240,head_addr=0,end_addr=0)
                [0] type=HTX_BLK_RES_SL    - size=44     - addr=0       HTTP/1.1 404 Not Found
                [1] type=HTX_BLK_HDR       - size=33     - addr=44      date: Sat, 05 Dec 2020 03:58:39 GMT
                [2] type=HTX_BLK_HDR       - size=27     - addr=77      server: Apache/2.4.6 (CentOS)
                [3] type=HTX_BLK_HDR       - size=42     - addr=104     last-modified: Fri, 04 Dec 2020 09:01:06 GMT
                [4] type=HTX_BLK_HDR       - size=24     - addr=146     etag: "4000-5b59fb77a3243"
                [5] type=HTX_BLK_HDR       - size=18     - addr=170     accept-ranges: bytes
                [6] type=HTX_BLK_HDR       - size=19     - addr=188     content-length: 16384
                [7] type=HTX_BLK_HDR       - size=30     - addr=207     vary: Accept-Encoding,User-Agent
                [8] type=HTX_BLK_HDR       - size=36     - addr=237     content-type: text/html; charset=UTF-8
                [9] type=HTX_BLK_EOH       - size=1      - addr=273     <empty>
                [10] type=HTX_BLK_DATA      - size=15966  - addr=274

```

**Comment by zino7825** [comment] 2020-12-05 04:59
@capflam No problem this issue in Haproxy 2.2.6

I want to know which file is changed. 

`BUG/MINOR: tcpcheck: Don't forget to reset tcp-check flags on new kind of check` ?

**Comment by capflam** [comment] 2020-12-08 14:13
Ok, thanks. The main commit fixing the health-checks is b381a505c. I'm glad the problem gone on the 2.2.6. But I'm still puzzled you don't hit the check timeout. In addition, I don't understand why the matching on the status code is not performed on received data, incomplete or not. I just hope it is not another bug, hidden by the above commit.

Could we consider the bug as fixed ?

**Comment by zino7825** [comment] 2020-12-09 03:06
@capflam if the connection status is stucked, check timeout becomes useless.

I think it resolves problem that `reset tcp-check flags on new kind of check`
because we affected Health-check bug, Haproxy did not send a reset or fin flags but 2.2.6 version send the find or reset when I captured packet.

You can make this environment very easily.

**Comment by capflam** [comment] 2020-12-09 08:19
The commit 1faf18ae (`BUG/MINOR: tcpcheck: Don't forget to reset tcp-check flags on new kind of check`) is just a fix for the health-checks parsing during the startup. Thus it is not related to the current issue.

The check timeout is set on the health-checks task. Thus, if the connection is stucked for any reason, this task should expire with the L7TOUT status. Except if you have an loop inside the check. But in this case, the watchdog should abort the process. So, for an unknown reason, here, the check is waiting for more data while the buffer is full. That's no explain why the matching on the status code is not performed while it should and why the check timeout is never reached while it should.

In the 2.2.5 and lower, there is a major bug leading to memory corruption and thus any kind of undefined behaviours. It may be the origin of your bug. Your buffers are configured to 64K while the check buffers are set to 16k. It may also be the reason. But I'm unable to reproduce any issue with this kind of configuration on the 2.2.4. However, since the 2.2.6, both are always the same size. You may try the 2.2.4 setting `tune.bufsize` to 16k.

For now, I'm too busy to make more tests. But if you have a minimal configuration to reproduce the bug, I'm interested. Because I still thinking it might be a bug, just harder to trigger on the 2.2.6.

**Comment by zino7825** [comment] 2020-12-09 09:30
@capflam I use the `tune.bufsize 65536` 

I also have a  minimal config
haproxy IP: 10.113.10.101
origin IP : 10.114.102.26

1. l7check file change : l7.html -> l7.html.bak
2. curl -s localhost/l7.html -> 404 response and content-length : 16k or more 
3. if hatop status is L7OKC, use reject haproxy healthcheck IP by iptables on origin server
4. iptables rule delete  
5. you can see the bug 
* simple config
```
global
    log 127.0.0.1 local0 notice
    log 127.0.0.1 len 8092 local0
    #log "${logserver}:514" len 2048 local0
    log-send-hostname
    log-tag default
    daemon
    nbthread 4
    hard-stop-after 120s

    # User
    user haproxy
    group haproxy

    # http statistics socket
    stats socket /var/run/haproxy.stat-1 uid 0 level admin expose-fd listeners

    pidfile /var/run/haproxy.pid
    unix-bind prefix /var/run/ mode 660 user haproxy group nfront
    spread-checks 5
    tune.bufsize 65536
    tune.maxrewrite 4096
    tune.ssl.cachesize 500000
    tune.ssl.lifetime 86000
    maxconn 3200000

    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-ciphers EECDH+AES128+AESGCM:EECDH+AES256+AESGCM:EECDH+CHACHA20:EECDH+AES128+SHA:EECDH+AES256+SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:RSA+3DES:+aRSA
    ssl-default-bind-options ssl-min-ver TLSv1.0 ssl-max-ver TLSv1.3
    server-state-base /var/run
    ## intel quickassist
    #ssl-engine qat algo RSA,EC,DSA,DH,PKEY,PKEY_CRYPTO,PKEY_ASN1
    #ssl-mode-async

    lua-load lua/functions.lua

###################################################################
####################### SSL offloading #############################
####################################################################
    listen ssl-proxy
    mode tcp
    log-tag ssl
    log 127.0.0.1 len 8092 local0
    #log-format "%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq"

    option dontlog-normal
    option dontlognull
    option log-health-checks
    option redispatch
    option tcp-smart-accept
    option tcp-smart-connect
    option abortonclose
    option splice-auto
    option tcplog

    ### server connection retries ####
    retries 2

    #### timeout parameter ####
    timeout connect 3100
    timeout client 65s
    timeout server 65s
    timeout check 3s
    timeout queue 10s
    timeout tarpit 30s

    backlog 20000
    maxconn 200000

    bind :443 ssl curves X25519:P-256 crt-list /opt/crt-list.txt alpn h2,http/1.1

    server https unix@/var/run/https send-proxy-v2 maxconn 500000

######################################################################################################################################
####################################################### Default HTTP Definition ######################################################
######################################################################################################################################
defaults HTTP

    mode http

    #### option ####
    option http-keep-alive
    option http-ignore-probes
    option dontlognull
    option log-health-checks
    #option dontlog-normal
    option contstats
    option redispatch
    option tcp-smart-accept
    option tcp-smart-connect
    option abortonclose
    option splice-auto

    #### not comply with RFC7230 ####
    option accept-invalid-http-request

    #### server connection retries ####
    retries 2

    #### timeout parameter ####
    timeout connect 3100
    timeout client 65s
    timeout server 65s
    timeout check 3s
    timeout queue 10s
    timeout tarpit 30s
    timeout http-request 10s
    timeout http-keep-alive 60s

    #### default proxy max connection ####
    maxconn 3100000

    #### default balance algorithm ####
    balance roundrobin

    #### listen queue ####
    backlog 20000

    #### default server options ####
    default-server maxconn 10000 inter 5s fastinter 2s downinter 10s rise 3 fall 2 slowstart 10s agent-inter 10s agent-port 9999
    #load-server-state-from-file global


frontend http-edge
    id 11
    bind :80
    bind unix@https accept-proxy

    #### timeout configuration ####
    timeout http-keep-alive 10s
    use_backend default_backend

backend default_backend
    balance roundrobin
    option httpchk
    http-check send meth GET uri /monitor/l7.html ver HTTP/1.1 hdr host example.com hdr User-Agent nfront-check/1.0
    http-check disable-on-404

    server cweb01.example 10.114.102.26:80 check ### test server 
    server cweb02.example 10.114.120.87:80 check
```

* hatop status 
![image](https://user-images.githubusercontent.com/5656233/101612362-e7284180-3a4d-11eb-825e-535cf952be4c.png)

* cweb01.example l7check down 
![image](https://user-images.githubusercontent.com/5656233/101612139-ab8d7780-3a4d-11eb-8927-eb28e3912338.png)

* `curl -H 'host: example.com' localhost/monitor/l7.html`
404 not found and content-length 16k or more 

* iptables insert on origin server  
`iptables -I INPUT -s {haproxy ip} -j REJECT` 

* hatop status L4CON
![image](https://user-images.githubusercontent.com/5656233/101613172-c8767a80-3a4e-11eb-98b5-3242165b0926.png)

* iptables delete on origin server
`iptables -D INPUT 1` 

* You can see the bug ( never try health check to origin server ) 
![image](https://user-images.githubusercontent.com/5656233/101613215-d75d2d00-3a4e-11eb-8ce8-d79cc33adf64.png)

**Comment by zino7825** [comment] 2020-12-11 08:38
@capflam Are you testing now?

**Comment by capflam** [comment] 2020-12-11 08:45
Yes, I finally reproduced the issue on the 2.2.4 with a small hack in the code to get the right condition. I'm on a fix. However, it is hard (maybe impossible) to trigger it on the 2.2.6 because the buffers used for health-checks have now the same size of other buffers. But the bug still there and only waiting another way to resurface.

In fact there are 2 bugs: the first one is the loop to read more data while the buffer is full. The other one is about the check expiration never reached because the timeout is rearmed on each loop. I'll push the fixes soon.

**Comment by capflam** [comment] 2020-12-11 12:08
FYI, the fixes were pushed to 2.4-dev. Not backported yet.

**Comment by zino7825** [comment] 2020-12-11 12:12
ok! I got it!!
Let me know the patch~ !
thanks to your effort!


2020년 12월 11일 (금) 오후 9:08, Christopher Faulet <notifications@github.com>님이
작성:

**Comment by zino7825** [comment] 2020-12-14 06:10
@capflam This problem is resolved if i use your patch `Use right condition to consider HTX ..` in 2.2.4 
but I can't test of timeout bug patch and I will wait backport to 2.2 !!

thx !!

**Comment by capflam** [comment] 2020-12-14 08:07
@zino7825 Thanks for testing. I'll try to do all backports today. The patch about health-check timeout must be adapted for the 2.2.

**Comment by capflam** [comment] 2020-12-14 11:11
Ok, backported now. I'm closing the issue. Thanks !

**Closed as completed by capflam** 2020-12-14 11:11 UTC
Labels: type: bug, subsystem: checks, status: fixed
