### ISSUE TITLE
Coverity Makefile hack broken

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1592] opened 2022-03-01 19:24 UTC
### Detailed Description of the Problem

The Coverity Makefile hack to set `DEBUG=` got broken in the latest changes.

### Expected Behavior

Coverity should build with `-DDEBUG_USE_ABORT=1`.

### Steps to Reproduce the Behavior

Run `sed -i 's/^DEBUG =$/DEBUG = -DDEBUG_STRICT=1 -DDEBUG_USE_ABORT=1/' Makefile` and notice that nothing changes.

### Do you have any idea what may have caused this?

8de7f2822b6d7bfdac83fa04c434e76f7a9fd4b0

### Do you have an idea how to solve the issue?

Slightly adjust the `sed` command in https://github.com/haproxy/haproxy/blob/master/.github/workflows/coverity.yml.

### What is your configuration?

```haproxy
n/a
```

### Output of `haproxy -vv`

```plain
n/a
```

**Comment by wtarreau** [comment] 2022-03-04 07:24
Tim,

I'm sorry but I don't understand what broke. The patch above only changed the default options and you seem to indicate that coverity already forces DEBUG_USE_ABORT=1, hence it ignores the default DEBUG settings set by this patch. Could you please enlighten me about what I'm missing ?

**Comment by TimWolla** [comment] 2022-03-04 08:36
Okay, maybe faithfully filling in the template resulted in me being unclear.

It's very simple: The `DEBUG=` line in the Makefile changed to be non-empty. Thus the sed expression no longer matches, which leads to Coverity no longer building with `DEBUG_USE_ABORT=1` which is undesirable, because it does not understand the process dies without that.

The sed command in coverity.yml will need to be adjusted. Possible like this (to prepend the `-DDEBUG_USE_ABORT=1` option):

```
sed -i 's/^DEBUG =/DEBUG = -DDEBUG_USE_ABORT=1/' Makefile
```

or possibly like this:

```
sed -i 's/^DEBUG =.*/DEBUG = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS -DDEBUG_USE_ABORT=1/' Makefile
```

to change the full line.

See this commit for further context: https://github.com/haproxy/haproxy/commit/66d28e7045459c63e9f5988277926ba74d64697e

**Comment by wtarreau** [comment] 2022-03-04 09:14
Ah OK, I wouldn't have imagined that :-) Then the issue is patching the makefile in the first place, we should never do that. I think the following should fix it once for all instead, I'm interested in a feedback if this is testable without being merged, otherwise a confirmation that I can merge it.
[0001-CI-simplify-coverity-debug-options.patch.txt](https://github.com/haproxy/haproxy/files/8184537/0001-CI-simplify-coverity-debug-options.patch.txt)

**Comment by TimWolla** [comment] 2022-03-04 09:24
Oh, interesting. I didn't know this was possible. From the look of it, it should work.

Whether it is testable without a commit: @chipitsine can probably answer.

**Comment by wtarreau** [comment] 2022-03-04 09:28
OK cool, let's wait for Ilya's approval and/or test then.

**Comment by chipitsine** [comment] 2022-03-04 13:25
that's better. let us take wtarreau patch

**Comment by wtarreau** [comment] 2022-03-04 13:34
OK thank you guys, now merged!

**Closed as completed** 2022-03-05 22:26 UTC
Labels: type: bug, status: fixed
