### ISSUE TITLE
haproxy=2.3.9: Crashes with the message "A bogus APPCTX is spinning and refuses to die"

### ISSUE THREAD

**Issue by pr0grammm** [haproxy/haproxy#1263] opened 2021-05-19 13:14 UTC
## Detailed description of the problem

I am using Lua with Haproxy to make a few socket calls. I have implemented these socket calls as part of an Action as described here https://www.haproxy.com/blog/5-ways-to-extend-haproxy-with-lua/#actions using Lua Socket class. data is fetched correctly sometimes but most of the time code crashes with the below message:

```
[ALERT] 138/112505 (16269) : A bogus APPCTX [0x28845b0] is spinning at 100002 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x2884840 src=<LUA_TCP> fe=LUA-SOCKET be=LUA-SOCKET dst=LUA-SSL-CONN rqf=848000 rqa=0 rpf=8000c020 rpa=0 sif=EST,204048 sib=EST,280058 af=0x28845b0,0 csf=(nil),0 ab=(nil),0 csb=0x2885310,9000 cof=(nil),0:NONE((nil))/NONE((nil))/NONE(0) cob=0x28814f0,10042300:PASS(0x28860f0)/SSL(0x2885360)/tcpv4(199) filters={}]
```

I intend to pass on the  return value of the action as argument to SPOE filter. (I have not implemented this part yet)
## Steps to reproduce the behavior

Try the below. Might have to repeat the below 3 steps multiple times. There will be a crash in step 2 eventually. For me it usually crashes within 10 tries.
1. start haproxy (`sudo haproxy -d -f /etc/haproxy/haproxy.cfg`)
2. make a request (`curl -I localhost`)
3. stop haproxy (<kbd>Ctrl</kbd> + <kbd>C</kbd>)

Crash happens sometimes when making continuous requests also but I found the above was more consistent...

## Do you have any idea what may have caused this?
I think it has something to do with SPOE filter. When I commented out in the filter in my configuration it seemed not to crash. But not a 100% sure though.

## Do you have an idea how to solve the issue?
No.
### socket_connect.lua
```
local function http_request(txn, data)
    local addr = 'my-ip'
    local port = 80

    -- Set up a request to the service
    local hdrs = {
        [1] = string.format('host: %s:%s', addr, port),
        [2] = 'accept: */*',
        [3] = 'connection: close'
    }
    
    table.insert(hdrs,"header: "..data.headers["header"])
   
    local req = {
        [1] = string.format('GET %s HTTP/1.1', data.url.path),
        [2] = table.concat(hdrs, '\r\n'),
        [3] = '\r\n'
    }

    req = table.concat(req,  '\r\n')

    -- Use core.tcp to get an instance of the Socket class
    local socket = core.tcp()
    --socket:settimeout(data.timeout)

    -- Connect to the service and send the request
    local connect
    
    if  data.url.schema == "https://"  then
        connect = socket:connect_ssl(addr, 443)
    else
        connect = socket:connect(addr, port)
    end

    if connect then
        if socket:send(req) then
            -- Skip response headers
            while true do
                local line, _ = socket:receive('*l')

                if not line then break end
                if line == '' then break end
            end

            -- Get response body, if any
            local content = socket:receive('*a')
            socket:close()
            return content

        else
            core.Alert('Could not connect to server (send)')
            
        end

        
    else
        core.Alert('Could not connect to server (connect)')
    end
    
    socket:close()
    return content
end

socket={}
socket.http_request = http_request
return socket
```
### fetch-data.lua
```
local socket_connect = require("socket_connect")

core.register_action("fetch_data", { "http-req" },function(txn)
    http_request_data = {
        timeout= 1000,
        headers= {
            header= "value"
        },
        url= {
            domain=  "...",
            path= "...",
            schema=  "https://"
        }
    }
    local content = socket_connect.http_request(txn,http_request_data)
    return content --TODO: or set a variable?
end)

```
### haproxy.cfg
```
#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    pidfile     /var/run/haproxy.pid
    daemon
    nbthread    64
    lua-load    /path/to/fetch_data.lua #loading lua file that does socket calls
    stats       socket      /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode        http
    log 127.0.0.1 local0
    option      httplog
    option      dontlognull
    option      http-keep-alive
    timeout     http-request    90s
    timeout     queue           1m
    timeout     connect         10s
    timeout     client          1m
    timeout     server          1m
    timeout     http-keep-alive 10s
    timeout     check           10s

    retries     3
    maxconn     100000


#---------------------------------------------------------------------


frontend            http-in
    bind *:80
    mode            http

    option httplog
    log /dev/log local0 debug
    http-request lua.fetch_data
    filter spoe engine my-spoe config /path/to/my-spoe.conf #spoe filter 
    http-request set-header resp %[var(txn.response)] #txn.response: this is set by backend used by spoe
    http-response set-header resp %[var(txn.response)]
    default_backend success_backend

#---------------------------------------------------------------------
# round robin balancing between the various backends
#---------------------------------------------------------------------
backend         success_backend
    mode http
    balance     roundrobin
    server      app1 127.0.0.1:8080 check

backend spoe-backend
    mode tcp
    timeout connect 5s
    timeout server  3m
    option spop-check
    server spoa-server 66.66.66.66:6666 



```
### spoe.conf
```
[my-spoe]

spoe-agent my-spoe 
    messages data-packet 

    option continue-on-error

    timeout hello 3s 
    timeout idle  1m
    timeout processing 100ms

    use-backend spoe-backend

    spoe-message data-packet
        
        #TODO: args data= set the result from fetch-data action here
        event on-frontend-http-request
```
## Output of `haproxy -vv` and `uname -a`

output of `haproxy -vv`
```
HA-Proxy version 2.3.9-53945bf 2021/03/30 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.9.html
Running on: Linux 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_THREAD=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```
output of  `uname -a`
```
Linux  3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
[NOTICE] 138/121759 (18880) : haproxy version is 2.3.9-53945bf
[NOTICE] 138/121759 (18880) : path to executable is /sbin/haproxy
[ALERT] 138/121759 (18880) : A bogus APPCTX [0x24235c0] is spinning at 173744 calls per second and refuses to die, aborting now! Please report this error to developers [strm=0x2423850 src=<LUA_TCP> fe=LUA-SOCKET be=LUA-SOCKET dst=LUA-SSL-CONN rqf=848000 rqa=0 rpf=8000c020 rpa=0 sif=EST,204048 sib=EST,280058 af=0x24235c0,0 csf=(nil),0 ab=(nil),0 csb=0x2424320,9000 cof=(nil),0:NONE((nil))/NONE((nil))/NONE(0) cob=0x2420500,10042300:PASS(0x2425100)/SSL(0x2424370)/tcpv4(199) filters={}]
Aborted
```

**Comment by capflam** [comment] 2021-05-19 16:51
Thanks, I'll take a look

**Comment by pr0grammm** [comment] 2021-05-19 19:32
Thank you, please do let me know if you require any additional info

**Comment by capflam** [comment] 2021-05-19 19:49
I'm able to reproduce the bug. I can now try to figure out what happens. Thanks !

**Comment by pr0grammm** [comment] 2021-05-20 13:25
OK that's good, thank you. If I may ask one question related to the above code, I want to use the content returned by socket call to create some new content and then pass that to spoe filter. Something like this is possible using fetch I know but I am struggling to do the same with action...wanted to know how I can achieve this..?
```
spoe-message data-packet
        args  data=lua.data_packet() #doesn't work if data_packet is not a fetch
        event on-frontend-http-request
```

**Comment by capflam** [comment] 2021-05-20 21:02
I think I found the bug. If possible, could you try the following patch ?

[0001-BUG-MEDIUM-filters-Exec-pre-post-analysers-only-one-.patch.txt](https://github.com/haproxy/haproxy/files/6518670/0001-BUG-MEDIUM-filters-Exec-pre-post-analysers-only-one-.patch.txt)

The SPOE `on-frontend-http-request` event is executed before the frontend http-request ruleset evaluation. Thus, your lua script is called after sending of the SPOE `data-packet` message. A solution is use a SPOE group instead, using a HTTP `send-spoe-group` action after the call to `lua.fetch_data` action. To get the response payload to your request, you should set a variable. You may also use the private storage via `TXN.set_priv()`/`TXN.get_priv()` and register a dedicated lua sample fetch to get it from the SPOE.

**Comment by pr0grammm** [comment] 2021-05-21 11:32
Hi, strangely even without the patch I have not been able to reproduce this in my setup all day - . If I start seeing the crash again I will definitely try the patch
Regarding the second point, I am sorry I did not understand entirely . Could you please give an example how I should define my spoe-group section in the spoe conf such that I can pass the output of my action as an argument to spoe? I could not find details on this...
thank you

**Comment by capflam** [comment] 2021-05-21 16:49
For me, to reproduce the bug, I must shut down the SPOA. BTW, I'll push the patch because it really fixes a bug.

Here is how you may change your SPOE configuration:
```
[my-spoe]

spoe-agent my-spoe
    groups data-packet-grp

    option continue-on-error

    timeout hello 3s
    timeout idle  1m
    timeout processing 100ms

    use-backend spoe-backend

spoe-group data-packet-grp
    messages data-packet

spoe-message data-packet
    args data=var(txn.data_packet)
```

You may have several messages in a group.

Then, in HAProxy configuration, you should add a new http-request rule:
```
frontend    http-in
    bind *:80
    mode            http

    option httplog
    log /dev/log local0 debug
    filter spoe engine my-spoe config /path/to/my-spoe.conf #spoe filter
    http-request lua.fetch_data
    http-request  send-spoe-group my-spoe data-packet-grp
   ...
```

You should then set `txn.data_packet` in your lua script. For more details : 
* SPOE: https://github.com/haproxy/haproxy/blob/master/doc/SPOE.txt
* lua API: https://www.arpalert.org/src/haproxy-lua-api/2.3/index.html

**Comment by pr0grammm** [comment] 2021-05-24 07:44
Hi, thank you very much for the details. This was really helpful and things are working like a charm now !

**Comment by pr0grammm** [comment] 2021-05-24 07:56
Ah okay I tried with SPOA up/down but still no luck with the bug.  So version > 2.4 will have the fix correct? If I want to use version 2.4 or below I must apply the patch...

**Comment by capflam** [comment] 2021-05-31 08:41
Sorry, I missed your comment. The fix will be backported as far as 1.8. For now, it was only pushed to the 2.5-dev. But it will be shipped with the next stable releases (not planned for now).

**Comment by pr0grammm** [comment] 2021-06-02 08:52
Hi no issues, thank you!
**EDIT: sorry for the confusing question below. It is resolved now!. I had multiple haproxy processes running which was causing weird issues!**
Also I was wondering if you could please help me with some strange behaviour I observed.  I hope it is okay to ask here. As per your suggestion I have implemented like this but I have a doubt whether the statements are getting executed one after the other or there is some caching going on. I have print statements inside my fetches and actions. : 
```
    frontend    http-in
    bind *:80
    mode            http

    option httplog
    log /dev/log local0 debug
    filter spoe engine my-spoe config /path/to/my-spoe.conf #spoe filter
    http-request lua.fetch_data
    http-request  send-spoe-group my-spoe data-packet-grp
    acl redirect hdr(My-Response) some-value #todo: some-value will be set by the agent to which spoe filter posts the data 
    http-request redirect code 307 location %[lua.redirect] if redirect #lua.redirect is a fetch that returns url to redirect to
    http-response lua.set_some_cookies #this action adds some set-cookie headers
```
If I try this request `curl -I  -H "My-Response:some-value" localhost -v` I see different behaviours:
1)  lua.fetch_data gets executed (I see the print statements), lua.redirect code gets executed (I see the print statements) and redirection happens, no cookies in the response - so response flow is not executed.
2) lua.fetch_data does not get executed (no print statements) , redirection happens with some older cached value of url (some parts of url are actually decided by lua.fetch_data). None of the print statements inside lua.redirect are getting executed.
3) lua.fetch_data does not get executed, redirection does not happen, I see cookies in the response. None of the print statements inside lua.set_some_cookies are getting executed
Please let me know if I am missing something here. 
Thank you

**Comment by capflam** [comment] 2021-06-02 11:37
>     1. lua.fetch_data gets executed (I see the print statements), lua.redirect code gets executed (I see the print statements) and redirection happens, no cookies in the response - so response flow is not executed.

It is expected. `http-response` ruleset is evaluated on the server response. The redirect is produced by HAProxy. You should use `http-after-response` ruleset instead. It will be evaluated on all responses, the server and HAProxy ones.
 
>     2. lua.fetch_data does not get executed (no print statements) , redirection happens with some older cached value of url (some parts of url are actually decided by lua.fetch_data). None of the print statements inside lua.redirect are getting executed.

It is unexpected. `lua.fetch_data` must always be evaluated because there is no if/unless statement on the rule. But there is no cache at this stage. However, it is hard to diagnose the issue without the lua scripts.

>     3. lua.fetch_data does not get executed, redirection does not happen, I see cookies in the response. None of the print statements inside lua.set_some_cookies are getting executed

If the cookie is added by your script, it means it is executed. It is expected because there is no redirection, thus the request is sent to the server. The cookie is inserted into the server response. To know what happens exactly, I need to take a look to your Lua script.

Note that it is no longer an bug report. You may have more support on the mailing-list (haproxy@formilux.org) or on the forum (https://discourse.haproxy.org/).

**Comment by pr0grammm** [comment] 2021-06-02 13:20
Hi, thank you for the response. Actually I resolved it a little while ago! I had multiple haproxy processes running and that was causing weird things to happen. After I killed the extra processes, things started working as expected! I had edited my comment above with the update but I guess you must have missed that. Thanks again !

**Comment by pr0grammm** [comment] 2021-06-02 13:21
Also sure I will take my questions to the email thread, thanks

**Comment by capflam** [comment] 2021-06-02 13:22
Indeed, I missed the "edit" part in your comment :/ Sorry for the noise.

**Comment by HiggTh** [comment] 2021-08-04 20:32
Hi, I am having an issue as a result of this change. I hope you can help.

I was using haproxy v2.2.14 and I encountered an issue as a result of this change upon upgrading to v2.2.15.

I am running haproxy in tcp passthrough mode and I was using SPOE to analyse a TLS server hello message by sending the response payload to the SPOA once the server hello is received. To do this, I use the `on-tcp-response` event in my SPOE which looks something like this:
`event on-tcp-response if { res.ssl_hello_type 2 }`.

Previously every tcp-response during the tcp-response inspection period would pass through this event until the server hello was received, which would trigger the sending of the message to my SPOA. Now however, the event is only hit once so my SPOA never receives a message, as the server hello has not yet been received in the response buffer.

As an alternative, I tried using `tcp-response content send-spoe-group`, but this doesn't appear to work even though `tcp-request content send-spoe-group` will work.

Can you consider allowing the former functionality for the `on-tcp-response` event, or support calling `send-spoe-group` for a tcp-response.

I am pretty restricted in what I can do, as I am not allowed to terminate the TLS connection.

Any help would be appreciated.

**Comment by capflam** [comment] 2021-08-12 07:37
ACLs used on SPOE events are final. It means there is no way to wait for more data. If the SSL hello message is not received when the `on-tcp-response` event is evaluated, the message is not sent but there is no way to wait at this stage. Instead you must use a SPOE group as you tried. But you must add an ACL on the `tcp-response content` rule to wait the SSL hello message. Indeed, at this stage, it is possible to wait for more data by setting an `inspect-delay`. For instance:
```
tcp-response inspect-delay 1s
tcp-response content send-spoe-group my-spoe-engine my-group if { res.ssl_hello_type 2 }
```

**Comment by HiggTh** [comment] 2021-08-15 22:37
Thank you for the reply. The solution you have suggested was what I originally intended on using, but it does not appear to work.
When testing a backend with the above included, no message is sent to my SPOA. If I change the action to run on a tcp-request as shown below however, a message is sent as expected.
```
tcp-request inspect-delay 1s
tcp-request content send-spoe-group my-spoe-engine my-group if { req.ssl_hello_type 1 }
```

In the tcp-response case, I confirmed that the condition is evaluating to true so the server hello is being received, it just seems as if the send-spoe-group action is not doing anything. 

This is the reason why I am currently using the on-tcp-response event. Before this bug fix was merged, on each tcp-response the event condition shown below would prevent the message being sent to my SPOA unless the server hello had been received in the response buffer. Now the event is only ever triggered on the first tcp-response and never again. 

`event on-tcp-response if { res.ssl_hello_type 2 }`

I am fine using either solution, but currently neither work.

**Comment by wtarreau** [comment] 2021-08-19 09:24
Just a quick note on this issue, Christopher definitely is the expert on this but he's away from keyboard till the end of the month, so rest assured we're not letting your issue die, we're just avoiding to say stupidities to keep the discussion running :-)

**Comment by HiggTh** [comment] 2021-08-19 10:01
Thanks, I appreciate the update. I've rolled back to v2.2.14 for now to keep my current solution working.

**Comment by capflam** [comment] 2021-09-06 18:31
In fact, it is not a SPOE bug, but an old issue with the configuration parser fixed by chance by the commit 42c6cf950 (not backported because it was not identified as a bug fix). The post-parsing of `tcp-response content` ruleset is never performed on HAProxy 2.3 and lower. However, it should work on HAProxy 2.4. I guess the commit above must be backported or a specific fix must be provided for older versions.

**Comment by capflam** [comment] 2021-09-07 16:37
The above commit was backported as far as 2.0 and a new 2.3 release was emitted. It should work now.

**Comment by HiggTh** [comment] 2021-09-09 16:42
Thank you for looking into this. I will migrate to using `send-spoe-group` now instead of events.

**Closed as completed** 2022-08-25 10:01 UTC
Labels: type: bug, status: fixed
