### ISSUE TITLE
splice-response issue in 2.0.8 latest

### ISSUE THREAD

**Issue by felipewd** [haproxy/haproxy#356] opened 2019-11-04 21:21 UTC
Output of `haproxy -vv` and `uname -a`
uname -a:

```Linux <host> 5.2.7 #1 SMP Wed Aug 7 00:00:34 -03 2019 x86_64 Intel(R) Xeon(R)```

Version is 2.0.8 with patches up to `27ebcefd41b3e44395c3fe71939ef98b03f98e7b` compiled with `linux-glibc`:

```
HA-Proxy version 2.0.8 2019/10/23 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -fPIC -g -march=sandybridge
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_ZLIB=1 USE_NS=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=40).
Built with OpenSSL version : OpenSSL 1.1.1b  26 Feb 2019
Running on OpenSSL version : OpenSSL 1.1.1b  26 Feb 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

Our setup is haproxy in front of a web server listening on a unix socket.

When we enabled `splice-response` on defaults, we had long (20+ seconds) delays and incomplete objects, both chunked-encoding and content-length ones.

So we were able to narrow down the issue to this simplest config:

```
global
    nbproc 1
    nbthread 1
    user haproxy
    group haproxy
    daemon
    log /dev/log local0

defaults
    mode    http
    option splice-response

    timeout connect 1s
    timeout server 10s
    timeout client 10s
    timeout tunnel 10s

listen test-splice
    bind 127.0.0.1:6666 

    acl scheme req.hdr(X-Scheme) -m found
    http-request set-header X-Scheme "HTTPS" unless scheme

    server splice1 /var/run/server.sock
```

We were able to reproduce this with a request to a file over 600KB with a chunked-encoding response.

The file is incomplete (sometimes 102KB, sometimes 90KB), and curl complains before closing:

```
3f50: d1 01 35 57 2c 95 df ac 5c bf 59 8d 3a 57 b4 bd ..5W,...\.Y.:W..
3f60: 93 54 6f 00 b2 59 44 bf 7e 7a b6 31 f4 eb a7 c0 .To..YD.~z.1....
3f70: 77 bf 9c 0f 36 d4 28 58 c5 4b e1 11 1e 83 e8 9b w...6.(X.K......
3f80: d5 3c 3d 7b f1 37 b7 85 68 60 74 8e 2f 45 e6 67 .<={.7..h`t./E.g
3f90: e7 ce a9 62 8a e0 c1 14 5d 39 77 4b a4 0d 31 e5 ...b....]9wK..1.
3fa0: 28 33 67 a2 5b 82 6c bd 9a cc 93 d9 df d0 17 26 (3g.[.l........&
3fb0: cd 30 8f 30 08 ee f6 d6 d8 3d 78 2c bd 08 0d 0a .0.0.....=x,....
3fc0: c1 c3 f4 c4 d1 24 0b b0 0e eb 0b db b9 22 cc 44 .....$.......".D
3fd0: 0c 40 c1 b2 1d 9d 3d cb 1c 71 0f 20 d9 85 e3 55 .@....=..q. ...U
3fe0: 93 80 c7 38 4a a8 3b 80 23 16 f2 fb 34 ff a9 1c ...8J.;.#...4...
3ff0: b8 7b c8 83 82 27 5e 95                         .{...'^.
== Info: Illegal or missing hexadecimal sequence in chunked-encoding
== Info: Closing connection 0
```

The issue is intermittent, but a few (10) parallel requests trigger it quite reliably.

Disabling HTX seemed to solve the issue, BUT...`strace` reveals that disabling HTX actually turns-off any `splice` syscalls, so we can't be sure this is an HTX-only issue.

When the error happens, the `httplog` line is:

```
test-splice/splice1 0/0/0/565/739 200 65496 - - CD-- 1/1/0/0/0 0/0 "GET /url.js?v=1572384047414 HTTP/1.1". 
```

This file, in particular, ended up with 104316 bytes.

A partial strace which shows the issue is this (we removed `epoll` and `gettime`):

```
18:13:26.148905 accept4(4, {sa_family=AF_INET, sin_port=htons(31464), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_NONBLOCK) = 7
18:13:26.153121 setsockopt(7, SOL_TCP, TCP_NODELAY, [1], 4) = 0
18:13:26.153596 accept4(4, 0x7ffff3dc98d0, [128], SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
18:13:26.160106 recvfrom(7, "GET /url.js?v=1572384047414 HTTP/1.1"..., 16320, 0, NULL, NULL) = 613
18:13:26.161035 getsockname(7, {sa_family=AF_INET, sin_port=htons(6666), sin_addr=inet_addr("127.0.0.1")}, [128->16]) = 0
18:13:26.161073 getsockopt(7, SOL_IP, 0x50 /* IP_??? */, 0x14f3b70, [16]) = -1 ENOPROTOOPT (Protocol not available)
18:13:26.161203 socket(AF_UNIX, SOCK_STREAM, 0) = 8
18:13:26.161325 fcntl(8, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
18:13:26.161476 connect(8, {sa_family=AF_UNIX, sun_path="/var/run/server.sock"}, 110) = 0
18:13:26.161688 sendto(8, "GET /url.js?v=1572384047414 HTTP/1.1"..., 639, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 639
18:13:26.161736 recvfrom(8, 0x152eaf0, 16320, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
18:13:26.728211 recvfrom(8, "HTTP/1.1 200 OK\r\ndate: Mon, 04 Nov 2019 20:13:26 GMT\r\ncontent-ty"..., 16320, 0, NULL, NULL) = 16320
18:13:26.728280 recvfrom(8, "\x9d\x48\x25\xe5\xa8\x0f\x14\x4e\x8b\x49\xd8\x29\xf0\x44\xe6\x84", 16, 0, NULL, NULL) = 16
18:13:26.728312 recvfrom(8, "\x0b\xd4\x1f\x97\xad\x54\x4a\x26\x93\xc9\x24\x4e\xdf\x5d\x7c\x38\x2f\xfa\x8d\x13\x2c\xaa\x29\x5d\x0f\xaf\x3a\x24\xdf\x7a\x8b\x49\x83\x0d\x61\xc0\xfb\x09\x0e\x66\x9a\x7f\x47\x86\xc5\xa7\xf4\x18\x5e\x60\xe9\xf2\x0b\x59\x5e\xd6\x3f\x76\xef\x6a\xe3\xd4\x9c\x23"..., 15201, 0, NULL, NULL) = 131
18:13:26.728441 recvfrom(8, 0x152eb43, 15070, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
18:13:26.728495 sendto(7, "HTTP/1.1 200 OK\r\ndate: Mon, 04 Nov 2019 20:13:26 GMT\r\ncontent-ty"..., 15193, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 15193
18:13:26.728587 pipe([9, 10])           = 0
18:13:26.728648 sendto(7, "\x34\x45\x30\x0d\x0a\xf5\x57\xaa\xd1\x64\xfc\x02\x49\x29\xd6\xf4\x49\xce\x3e\xa2\xb2\xea\xef\x13\xa2\x3d\x4d\xb5\x23\x07\x0f\x09\x43\x56\x02\xe8\x04\x58\xb2\xcf\xad\xb7\xb0\x26\xfe\x5b\x4f\x6b\xc1\x14\x75\x72\xa5\xd0\xf6\xf3\x31\xaf\x92\x45\x3e\x57\x44\x55"..., 1255, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 1255
18:13:26.778300 recvfrom(8, "\x30\x30\x33\x66\x66\x30\x0d\x0a\x0a\x53\x0b\x53\x1d\xf6\xd5\xf3\x79\xc0\xf4\x1d\x8c\xf6\x3c\x53\xef\x4c\x7e\x35\x39\x4f\xbd\x6b\xf2\xbe\xd3\x1a\xf4\x8b\x3d\x52\xad\x29\x24\xeb\x2e\xd7\xc7\x63\x66\xb3\x61\x19\x16\x2f\x48\xee\x4c\x8a\xf5\xab\xec\x42\x80\xb7"..., 16320, 0, NULL, NULL) = 16320
18:13:26.778368 sendto(7, "\x33\x46\x42\x38\x0d\x0a\x0a\x53\x0b\x53\x1d\xf6\xd5\xf3\x79\xc0\xf4\x1d\x8c\xf6\x3c\x53\xef\x4c\x7e\x35\x39\x4f\xbd\x6b\xf2\xbe\xd3\x1a\xf4\x8b\x3d\x52\xad\x29\x24\xeb\x2e\xd7\xc7\x63\x66\xb3\x61\x19\x16\x2f\x48\xee\x4c\x8a\xf5\xab\xec\x42\x80\xb7\xad\xda"..., 16320, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_MORE, NULL, 0) = 16320
18:13:26.778415 splice(8, NULL, 10, NULL, 56, SPLICE_F_MOVE|SPLICE_F_NONBLOCK) = 56
18:13:26.778756 splice(9, NULL, 7, NULL, 56, SPLICE_F_MOVE|SPLICE_F_NONBLOCK) = 56
18:13:26.778889 recvfrom(8, "\r\n", 16320, 0, NULL, NULL) = 2
18:13:26.779008 recvfrom(8, 0x1557040, 16320, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
18:13:26.869762 recvfrom(8, "\x30\x30\x33\x66\x66\x38\x0d\x0a\x75\xb8\xb5\x59\x07\x5b\x32\x51\xd9\x22\xfa\xd1\x6c\xac\x0e\xfb\xbe\x55\xb8\x82\xdb\xd5\x64\xa3\xb9\x02\x7d\xa5\xc5\xc2\x96\x05\xc5\x99\xe1\x10\xcc\x74\x99\x62\xcd\xfd\xb6\x3e\xf3\xa6\xd9\x4b\x34\x5b\x45\x87\xe4\xe1\x97\xf0"..., 16320, 0, NULL, NULL) = 16320
18:13:26.869839 sendto(7, "\x33\x46\x42\x38\x0d\x0a\x75\xb8\xb5\x59\x07\x5b\x32\x51\xd9\x22\xfa\xd1\x6c\xac\x0e\xfb\xbe\x55\xb8\x82\xdb\xd5\x64\xa3\xb9\x02\x7d\xa5\xc5\xc2\x96\x05\xc5\x99\xe1\x10\xcc\x74\x99\x62\xcd\xfd\xb6\x3e\xf3\xa6\xd9\x4b\x34\x5b\x45\x87\xe4\xe1\x97\xf0\xb3\x5e"..., 16320, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_MORE, NULL, 0) = 16320
18:13:26.869916 splice(8, NULL, 10, NULL, 64, SPLICE_F_MOVE|SPLICE_F_NONBLOCK) = 64
18:13:26.869967 splice(9, NULL, 7, NULL, 64, SPLICE_F_MOVE|SPLICE_F_NONBLOCK) = 64
18:13:26.870155 recvfrom(8, "\r\n", 16320, 0, NULL, NULL) = 2
18:13:26.870256 recvfrom(8, 0x152eaf0, 16320, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
18:13:26.903811 recvfrom(8, "\x30\x30\x34\x30\x30\x30\x0d\x0a\x26\x04\x5b\x96\x0e\x1f\x78\xdf\xb1\xfc\x17\x9f\x9f\xc7\x27\x7f\xf8\x8c\xe4\x42\xb4\xf0\x9e\x09\xc1\x13\xba\xeb\x7d\x63\xee\xea\x19\xf7\xd3\xef\xc7\x83\x83\xe7\xc3\x40\xc8\xb0\x2c\xfd\x02\xbf\x15\x98\xbb\xcf\xfc\x5e\x7f\x36"..., 16320, 0, NULL, NULL) = 16320 
18:13:26.903897 sendto(7, "\x33\x46\x42\x38\x0d\x0a\x26\x04\x5b\x96\x0e\x1f\x78\xdf\xb1\xfc\x17\x9f\x9f\xc7\x27\x7f\xf8\x8c\xe4\x42\xb4\xf0\x9e\x09\xc1\x13\xba\xeb\x7d\x63\xee\xea\x19\xf7\xd3\xef\xc7\x83\x83\xe7\xc3\x40\xc8\xb0\x2c\xfd\x02\xbf\x15\x98\xbb\xcf\xfc\x5e\x7f\x36\x99\x4f"..., 16320, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_MORE, NULL, 0) = -1 EPIPE (Broken pipe)
18:13:26.903950 splice(8, NULL, 10, NULL, 72, SPLICE_F_MOVE|SPLICE_F_NONBLOCK) = 72 
18:13:26.904077 recvfrom(8, "\r\n", 16320, 0, NULL, NULL) = 2
18:13:26.904114 close(10)               = 0
18:13:26.904249 close(9)                = 0
18:13:26.904281 close(8)                = 0
18:13:26.904307 close(7)                = 0
```

We can provide the traces off github if you think they'll help. tcpdumps are also quite easy to collect since this is a http frontend on a non-production port.

**Comment by capflam** [comment] 2019-11-05 09:29
@felipewd, I unable to reproduce the bug. So I'm interested by a network capture and a trace to figure out what's happen. I hope it will help me to find the issue quickly. Thanks.

**Comment by capflam** [comment] 2019-11-05 09:53
In fact, with chunked responses, I able to reproduce the bug. I replied too quickly. But I'm still interested by info about truncated responses with a content-length.

**Comment by rnsanchez** [comment] 2019-11-05 11:01
If it helps knowing, when repeating the request with either `identity` as `Accept-encoding:` or disabling compression altogether, the response does not use chunking and succeeds.

So, it seems that at least chunking is bringing in an issue.

(Noting that I've just seen your reply, @capflam )

**Comment by felipewd** [comment] 2019-11-05 12:37
Hey @capflam,

Good to know you can reproduce the case with chunked responses.

With content-length is a lot more tricky and we could only see it in production:  It happened with a H2 (TLS) frontend, but the symptom was: The response would take a _long_ time to be received (usual: 1s, this case over 20s), and in some cases, the response would be truncated.

We're still trying to reproduce those in a more controlled environment if we manage to reproduce that case with a simpler config (and traffic) and can post here. We're doing more experiments today.

Cheers!

**Comment by capflam** [comment] 2019-11-05 12:40
@felipewd, Note there is no splicing with H2. So the issue is probably not related to the option `splice-response`. But I will test it. In this case, the response sent by the server is chunked or not ?

**Comment by chipitsine** [comment] 2019-11-05 12:47
We are suffer from chunked encoding pretty often. Seem, we need some auto tests on it ))

**Comment by capflam** [comment] 2019-11-05 12:51
OK, easy to reproduce too. It is because of an old test (pre-mux) in `process_stream()` on the splicing support at the channel level. I will fix it quickly. @felipewd, don't bother with traces.

**Comment by felipewd** [comment] 2019-11-05 14:58
@capflam We've only been able to reproduce the issue with chunked responses. content-length ones only in production. But I've checked and it is on a H2 frontend...so since you've said there's so `splice` in that case, we'll try to reproduce it and recheck.

**Comment by capflam** [comment] 2019-11-06 10:41
It should be fixed now. Everything was backported to 2.0 and 1.9. Note that, for now, the splicing is disabled for chunked messages in the mux h1. I'll try to work on it. But it will possibly required too many changes to be backported. Don't know yet. It is a design problem of the HTX API or the mux API. nothing simple to fix unfortunately.

**Closed as completed** 2019-11-06 10:41 UTC
Labels: type: bug, severity: medium, status: fixed, subsystem: h1
