### ISSUE TITLE
Possible race condition while using do-resolve

### ISSUE THREAD

**Issue by davidmogar** [haproxy/haproxy#227] opened 2019-08-21 07:13 UTC
## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.0.0 2019/06/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1c  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.33 2019-04-16
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

# uname -a
Linux server 4.19.3-300.fc29.x86_64 #1 SMP Wed Nov 21 15:27:25 UTC 2018 x86_64 Linux
```

## What's the configuration?

```
global
    daemon
    log stdout format raw local0 info
    tune.ssl.default-dh-param 2048

defaults
    log global
    log-format %f\ %ci\ %[capture.req.hdr(0)]\ [%t]\ %ST\ %B\ %U\ %Tr\ %Tt\ %r
    mode http
    timeout client 1m
    timeout connect 10s
    timeout server 4m

resolvers dns
    parse-resolv-conf

frontend puppetserver-frontend
    bind :80 ssl crt /ssl/cert ca-file /ssl/bundle.pem verify required no-sslv3 v4v6

    default_backend puppetserver-backend

    http-request capture req.hdr(X-Namespace) len 50

    http-request set-var(sess.namespace) hdr(X-Namespace)
    http-request do-resolve(txn.service,dns,ipv4) str(),concat(puppetserver.,sess.namespace,.svc.cluster.local)

    http-request set-header X-Client-Verify-Real %[ssl_c_verify]
    http-request set-header X-Client-Verify NONE if !{ hdr_val(X-Client-Verify-Real) eq 0 }
    http-request set-header X-Client-Verify SUCCESS if { hdr_val(X-Client-Verify-Real) eq 0 }
    http-request set-header X-Client-DN CN=%{+Q}[ssl_c_s_dn(cn)]

    http-request deny if { method PUT POST } { hdr_val(Content-length) ge 62914560 }
    http-request deny unless { var(txn.service) -m found }

backend puppetserver-backend
    http-request set-dst var(txn.service)
    http-request set-dst-port int(80)
    server service 0.0.0.0:0
```

## Steps to reproduce the behavior

1. Spawn an haproxy instance in a Kubernetes cluster with coredns.
2. Spawn a service and any kind of container listening for HTTP traffic.
3. Send traffic. Specially POSTs or PUTs.

## Actual behavior

When sending requests to haproxy (specially POSTs and PUTs generated by Puppet), haproxy denies the requests as txn.service contains no value. CoreDNS received and attend rather quickly the request, returning a valid IP.

## Expected behavior

The requests should be redirected to the listening service after resolving the dns entry.

## Do you have any idea what may have caused this?

If the rule `http-request deny unless { var(txn.service) -m found }` is removed, everything works as expected and the traffic flows without problems. The same doesn't occur if the line is moved to the backend section. It looks like there's a race condition and the check for the existence of `txn.service` value is performed before storing the value resolved by `do-resolve`.

## Do you have an idea how to solve the issue?

As mentioned, removing the line helps the problem so I guess that http-requests are not being executed in sequence as stated by the docs. At least in the case of using do-resolve.

**Comment by pyhd** [comment] 2019-08-22 04:48
I also encountered this issue: `req.ssl_sni` was fetched, but `{ var(txn.myip) -m found }` failed.

**Comment by bedis** [comment] 2019-09-10 07:53
Sorry I did not update you, but I did spend some time on this case and I found that do-resolve function is currently not compatible with multi threads.
If you did not enforce `nbthread 1` in your configuration, then HAProxy 2.0 would spawn up one thread per CPU core you have in your machine, so you may fall into this limitation.

Can you try enforce `nbthread 1` in your global section and let us know if that fixes your issue?
It's a short term workaround until we make dns thread safe.

**Comment by davidmogar** [comment] 2019-09-10 08:20
Doesn't seem to fix anything on my case. I still get the same errors if I add these lines:
```diff
global
+    nbthread 1

frontend puppetserver-frontend
+    http-request deny unless { var(txn.service) -m found }
```

**Comment by bedis** [comment] 2019-09-24 16:15
Hi @davidmogar 

From my point of view, if the variable is empty, this should mean that the resolution did not ended up properly.

Maybe you want to use this SPOE Agent to run the resolutions at runtime: 
  https://github.com/bedis/haproxy-spoa-do-resolve

Its execution will happen right before your other http rules and there is a nice debug mode to see what is done exactly.

Let me know if you need help to set it up.

**Comment by davidmogar** [comment] 2019-09-24 17:02
> From my point of view, if the variable is empty, this should mean that the resolution did not ended up properly.

That is what makes sense to me The thing is that in that case, removing the check should cause agents contacting HAProxy to get errors and that's not the case. All the traffic is resolved and routed. The problems appear only if I check.

> Maybe you want to use this SPOE Agent to run the resolutions at runtime:
> https://github.com/bedis/haproxy-spoa-do-resolve

I can take a look. Thanks for the suggestion.

**Comment by davidmogar** [comment] 2019-09-25 12:40
Hello @bedis. I was taking a look again to your answer and in fact I forgot to comment that we already discarded problems with the DNS resolution. We used tcpdump to listen to coredns traffic and the resolutions are working and are fast enough. HAProxy error occurs after the resolution has been done.

**Comment by bedis** [comment] 2019-09-27 06:21
> > From my point of view, if the variable is empty, this should mean that the resolution did not ended up properly.
> 
> That is what makes sense to me The thing is that in that case, removing the check should cause agents contacting HAProxy to get errors and that's not the case. All the traffic is resolved and routed. The problems appear only if I check.

Can you explain what you mean by "check" ?

> Hello @bedis. I was taking a look again to your answer and in fact I forgot to comment that we already discarded problems with the DNS resolution. We used tcpdump to listen to coredns traffic and the resolutions are working and are fast enough. HAProxy error occurs after the resolution has been done.

Well, this is not because HAProxy receives a response that the variable will be set. There is some code checking the response and extracting the data before the variable can be set.
A bug can still lie in there (even if this code is available for a long time in HAProxy)

**Comment by davidmogar** [comment] 2019-09-27 08:15
By check I mean this:
```
frontend puppetserver-frontend
    http-request deny unless { var(txn.service) -m found }
```
There the request is denied unless the variable where dns-resolve put the result of the dns resolution is empty. What we saw is that doing this check causes a lot of problems in the service as requests are denied. The request never reach the application layer as they are denied by HAProxy.

Removing that check should still cause problems. If the variable is empty, the `http-request set-dst var` should not point the server to the requested service. Instead, what we found out is that the traffic gets routed normally and we see no errors at all. This by itself means that the dns resolution is working, so it seems more like a race condition.

**Comment by davidmogar** [comment] 2019-09-30 15:24
We managed to reproduce the problem without `http-request deny unless { var(txn.service) -m found }`.

This is what we've seen:
- The problems appear only for `POST` and `PUT` requests. At least we haven't seen it with GETs.
- There's no difference if we set a higher timeout in the resolver. It just takes longer to finally fail but the number of failures seems constant.
- The `http-request` rule to deny the traffic if the `txn.service` variable was not set has an impact in the number of errors. The problem is easier to reproduce if present.
- We still have to collect more data but it seems that the size of the payload affects the number of errors. We have right now a single host causing a 100% of the errors. This host is the one sending the smallest payload to the HAProxy. Even with this, the POST or PUT requests for this node don't fail constantly. Some of the request work properly. The DNS record is resolved to an IP and the traffic is sent to that backend.
- The number of errors is the same with or without `nbthread` set to 1.

As I see it, this looks to me like a race condition. The DNS resolution works but HAProxy doesn't wait for it or doesn't know it worked.

**Comment by wtarreau** [comment] 2019-09-30 18:35
Thanks for your investigations. This makes me think that the do-resolve
action doesn't expect to be woken up by incoming data and would possibly
fail, believing it's woken up by a response. I easily see how this mistake
could have been done in fact. Will double-check with Baptiste.

Willy

**Comment by davidmogar** [comment] 2019-09-30 18:37
It's great to see that you have some kind of clue. We'll keep this issue updated with any data we collect in the following days.

**Comment by davidmogar** [comment] 2019-10-01 12:33
We have send more traffic today and what we saw yesterday stills apply. Out of all the errors, the request failing are the ones with the smallest number of bytes uploaded (%U on the logs). As far as we see, less than 16000.

Another thing that can help you to identify the problem is the fact that usually the requests failing are POST requests. The next request after this POST is usually a PUT. In this case, the request will work most of the times, although not always. It seems like the DNS answer gets cached between the POST and the PUT requests and it can be used.

**Comment by bedis** [comment] 2019-10-01 13:13
Hi David,

Thanks for your investigation.
Willy and I talked about this issue this morning and Willy thinks that the
POST / PUT wake up the tasks.
The code I wrote clearly does not handle such wake up and so I would say
that if we're wake up before the DNS response is there we consider there
was no response.
I am going to investigate on this basis and come back to you shortly with a
confirmation of the behavior and hopefully a patch.

**Comment by bedis** [comment] 2019-10-01 13:42
Hi David,

So I am able to reproduce the issue easily and I could fix it as well.
I'll send the patch to te ML since I can't attach .patch files into this form.

Thanks for reporting!

**Comment by wtarreau** [comment] 2019-10-01 13:45
On Tue, Oct 01, 2019 at 06:42:46AM -0700, Baptiste Assmann wrote:
> So I am able to reproduce the issue easily and I could fix it as well.

Great!

> I'll send the patch to te ML since I can't attach .patch files into this form.

By the way, in order to send patches to this crappy interface, you need
to first rename it to .txt then upload it by clicking the discrete bar
under the text...

Willy

**Comment by davidmogar** [comment] 2019-10-02 08:34
Thank you for the patch. Nice to see that the data we collected helped to identify the problem.

We are deploying HAProxy in Kubernetes and this bug is stopping us from sending production traffic to the cluster. Do you have an estimate of when a docker image with this patch will be generated? I see it's in master but last docker image is from 4 days ago.

**Comment by bedis** [comment] 2019-10-02 09:59
Which docker image are you using?

Well, I flagged this patch to be backported into 2.0. The backport did not happen yet.
I'll update you once the backport is done, and then next docker build will have this patch.

**Comment by davidmogar** [comment] 2019-10-02 10:15
I'm currently using 2.0.0-alpine, but I could use the latest one if needed. The sooner we send real traffic, the better. Thanks for the backport.

**Comment by nbarrientos** [comment] 2019-10-07 08:59
Hi,

I'm replying on behalf of @davidmogar. He's currently a bit busy and I thought that it'd be useful for you to get our feedback as soon as possible. 

We built and deployed in a test environment an image based on `2.1-dev2` and indeed the problem seems to be gone. We're not seeing any more spurious 503s due to the variable where the result of the resolution of the name is stored being empty :)

Thanks guys!

**Comment by wtarreau** [comment] 2019-10-24 17:11
And 2.0.8 was issued with this patch if you're interested. I think we can mark the issue fixed now, thanks for your tests!

**Closed as completed by wtarreau** 2019-10-24 17:11 UTC
Labels: type: bug, status: fixed
