### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [haproxy/haproxy#2239] opened 2023-08-05 09:27 UTC
### Your Feature Request

Is it possible next time on release new version make the github release to have entry on https://github.com/haproxy/haproxy/releases entry? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

### What are you trying to do?

I'm asking to spread notifications about new release releases to those who have set watch->release.

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by git001** [comment] 2023-08-05 17:31
Even when I understand the request, I would suggest to contribute to the https://github.com/haproxy/haproxy/tree/master/scripts so that this could be handled easier. From my point of view is the [mailing-list](https://www.haproxy.org/#tact) haproxy@formilux.org the best way to stay informed :smile: . As you can see in the archive is the announcement of new releases always the same `https://www.mail-archive.com/search?a=1&l=haproxy%40formilux.org&haswords=&x=11&y=15&from=&subject=%5E%5C%5BANNOUNCE%5C%5D&datewithin=1d&date=&notwords=&o=newest` this means that you setup a filter which just keep this mails from the list, just one option to highlight new releases. IMHO

Another issue is that HAProxy maintain several versions as you can see on https://www.haproxy.org/ and the GH is only for the development tree used which creates a overhead to create for every version a own release especially that HAProxy does not run the development on GH. IMHO

I vote against such a overhead.

**Comment by kloczek** [comment] 2023-08-05 18:55
As I'm interested of receive async information about new releases I'm not so much interested to subscribe to every-possible-mialing-list 😋 
GH provides excellent platform to receive suuch notyfications 😄 
```console
[tkloczko@pers-jacek SPECS]$ grep github.com *spec -l| wc -l; ls -1 *spec|wc -l
2989
4648
```
As you almost 65% of all my spec file packages already is using github 😝

**Comment by lukastribus** [comment] 2023-08-06 23:29
Duplicate of #49

**Closed as not planned by lukastribus** 2023-08-06 23:29 UTC
Labels: status: duplicate
