### ISSUE TITLE
Large CRL files cannot be loaded and crash haproxy/openssl

### ISSUE THREAD

**Issue by shauntarves** [haproxy/haproxy#819] opened 2020-08-17 12:16 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Mon Jul 20 22:32:16 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered
 -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCR
E -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO
 +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-39)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
[SPOE] spoe
[COMP] compression
[TRACE] trace
[CACHE] cache
[FCGI] fcgi-app
```

```
Linux access 3.10.0-1127.18.2.el7.x86_64 #1 SMP Mon Jul 20 22:32:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
  user haproxy
  group haproxy

  #log 127.0.0.1 local0 debug
  log /dev/log local0 debug

  maxconn 4096

  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:
ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256
  ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

  ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:!EXPORT:!RC4:!aNULL:!MD5:!DSS
  ssl-default-server-options ssl-min-ver TLSv1.2 no-tls-tickets

  tune.ssl.default-dh-param 2048
  tune.ssl.lifetime 3600s

defaults
  balance leastconn
  log global

  maxconn 1024

  option dontlognull
  option http-server-close
  option redispatch

  mode    http
  option  httplog

  timeoutcheck 5s
  timeoutclient 61s
  timeoutconnect 10s
  timeout http-keep-alive 15s
  timeout    http-request 10s
  timeoutqueue 1m
  timeoutserver 61s

frontend fe-ssl-clientcert
  bind abns@haproxy-clientcert accept-proxy ssl crt /etc/haproxy/certs/ ca-file /etc/haproxy/cert/ca.file ca-verify-file /etc/haproxy/cert/ca.crt verify optional crt-ignore-err all crl-file /etc/haproxy/cert/ca.crl
```

## Steps to reproduce the behavior

1. Attempt to support large, US Government CRL files (some individual files > 30MB) (see below)
2. Concatenate the individual CRL files together, as required by haproxy
3. Attempting to start haproxy eventually segfaults

## Actual behavior

haproxy fails to start, creating an error like:

```
Aug 17 12:12:20 access haproxy[21930]: [NOTICE] 229/121220 (21930) : haproxy version is 2.2.2
Aug 17 12:12:20 access haproxy[21930]: [NOTICE] 229/121220 (21930) : path to executable is /usr/local/sbin/haproxy
Aug 17 12:12:20 access haproxy[21930]: [ALERT] 229/121220 (21930) : [/usr/local/sbin/haproxy.main()] Cannot fork.
Aug 17 12:12:20 access systemd[1]: haproxy.service: main process exited, code=exited, status=1/FAILURE
Aug 17 12:12:20 access systemd[1]: Failed to start HAProxy Load Balancer.
-- Subject: Unit haproxy.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit haproxy.service has failed.
-- 
-- The result is failed.
Aug 17 12:12:20 access systemd[1]: Unit haproxy.service entered failed state.
Aug 17 12:12:20 access systemd[1]: haproxy.service failed.
Aug 17 12:12:20 access systemd[1]: haproxy.service holdoff time over, scheduling restart.
Aug 17 12:12:20 access systemd[1]: Stopped HAProxy Load Balancer.
-- Subject: Unit haproxy.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit haproxy.service has finished shutting down.
....
```

when configured with a large CRL file:
```
-rw-rw----+ 1 root root 245M Aug 17 05:01 ca.crl
```

Here is the list of our required CRL files that get concatenated together:
```
http://crl.disa.mil/crl/DODSWCA_60.crl
http://crl.disa.mil/crl/DODSWCA_61.crl
http://crl.disa.mil/crl/DODIDCA_33.crl
http://crl.disa.mil/crl/DODIDCA_34.crl
http://crl.disa.mil/crl/DODIDCA_39.crl
http://crl.disa.mil/crl/DODIDCA_40.crl
http://crl.disa.mil/crl/DODIDCA_41.crl
http://crl.disa.mil/crl/DODIDCA_42.crl
http://crl.disa.mil/crl/DODIDCA_43.crl
http://crl.disa.mil/crl/DODIDCA_44.crl
http://crl.disa.mil/crl/DODIDCA_49.crl
http://crl.disa.mil/crl/DODIDCA_50.crl
http://crl.disa.mil/crl/DODIDCA_51.crl
http://crl.disa.mil/crl/DODIDCA_52.crl
http://crl.disa.mil/crl/DODIDCA_59.crl
http://crl.disa.mil/crl/DODIDSWCA_35.crl
http://crl.disa.mil/crl/DODIDSWCA_36.crl
http://crl.disa.mil/crl/DODIDSWCA_37.crl
http://crl.disa.mil/crl/DODIDSWCA_38.crl
http://crl.disa.mil/crl/DODIDSWCA_45.crl
http://crl.disa.mil/crl/DODIDSWCA_46.crl
http://crl.disa.mil/crl/DODIDSWCA_47.crl
http://crl.disa.mil/crl/DODIDSWCA_48.crl
http://crl.disa.mil/crl/DODINTEROPERABILITYROOTCA1.crl
http://crl.disa.mil/crl/DODINTEROPERABILITYROOTCA2.crl
http://crl.disa.mil/crl/DODNPEROOTCA1.crl
http://crl.disa.mil/crl/DODROOTCA2.crl
http://crl.disa.mil/crl/DODROOTCA3.crl
http://crl.disa.mil/crl/DODROOTCA4.crl
http://crl.disa.mil/crl/DODROOTCA5.crl
http://crl.disa.mil/crl/DODSWCA_53.crl
http://crl.disa.mil/crl/DODSWCA_54.crl
http://crl.disa.mil/crl/DODSWCA_55.crl
http://crl.disa.mil/crl/DODSWCA_56.crl
http://crl.disa.mil/crl/DODSWCA_57.crl
http://crl.disa.mil/crl/DODSWCA_58.crl
http://crl.disa.mil/crl/DODWCFROOTCA1.crl
http://crl.disa.mil/crl/USDODCCEBINTEROPERABILITYROOTCA1.crl
http://crl.disa.mil/crl/USDODCCEBINTEROPERABILITYROOTCA2.crl
```
## Expected behavior

haproxy starts successfully

## Do you have any idea what may have caused this?

I have _read but not confirmed_ that openssl has a limit on the size (64MB) of x509 files it can load into memory (see: https://support.f5.com/csp/article/K10054)

Because the individual files are so large, a concatenated set to support the US Government/DoD CRL list easily reaches ~250MB.

## Do you have an idea how to solve the issue?

Apache httpd has solved this issue by allowing configuration based on either a single CRL file OR a directory of individual CRL files (https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcarevocationpath).

I have not seen a similar option in haproxy.

**Comment by chipitsine** [comment] 2020-08-17 12:21
each CRL is signed. I'm curious how one can concatenate multiple CRLs together. is signing kept ?

**Comment by shauntarves** [comment] 2020-08-17 13:07
It's done exactly the same way as chaining any other PEM-encoded certificates is done. Multiple CA's (root and intermediate) can be concatenated into a single file (for example, to create a list of multiple "trusted" CAs). Additionally, a certificate, its key, and its intermediate can be concatenated into a single file.

**Comment by wlallemand** [comment] 2020-08-18 09:45
Hello,

I downloaded the CRL files, converted them from DER to PEM and concatened them to obtain the same 245MB file.
But HAProxy is loading successfully, I tried with openssl 1.0.2 and openssl 1.1.1.

I don't see any segfault in your logs, I'm only seeing this error:

> Aug 17 12:12:20 access haproxy[21930]: [ALERT] 229/121220 (21930) : [/usr/local/sbin/haproxy.main()] Cannot fork.

Which seems unrelated to your CRL file in my opinion.

Did you try to start this configuration without the CRL file?

 Do you have any security enforcement options in your systemd unit file? or security tools activated like selinux?

**Comment by shauntarves** [comment] 2020-08-18 12:48
The configuration works perfectly without the CRL file loaded - process fork just fine and haproxy is happy. But, this is great news. I will look further into the security enforcement stuff to see if selinux is the problem here. Thanks for the quick response - will keep you posted.

**Comment by shauntarves** [comment] 2020-08-18 13:52
Confirmed. The problem was actually that the server was undersized at only 4GB of RAM. After upping to 16GB, haproxy loaded with the large CRL file. Thanks again for the help.

**Comment by TimWolla** [comment] 2020-08-18 14:10
I believe there still might be a bug within HAProxy, because this looks like the return value of some `malloc` is not properly checked. Thus I'm reopening for now.

**Comment by chipitsine** [comment] 2020-08-18 16:19
to reproduce it, small vm without swap should be enough ? just creating such vm, and load some huge crl, right ?

**Comment by wlallemand** [comment] 2020-08-19 15:25
> I believe there still might be a bug within HAProxy, because this looks like the return value of some `malloc` is not properly checked. Thus I'm reopening for now.

I don't see why, if that was the case it would cause a segfault. The current error is a fork failure. Which means the system does not have enough memory when it tries to fork, and then exits with an error. The configuration and the CRL file is loaded before the fork so it could reach the limit of the system just before the fork. What I'm seeing is a clean error management there, not a segfault.

**Comment by TimWolla** [comment] 2020-08-19 15:35
Okay, yes. If that was indeed the only actual error and the segfault was just an _assumption_ from @shauntarves, then everything is good of course. I primarily reopened so that it can be investigated whether HAProxy does the right thing after the *cause* of the issue became clear.

**Comment by wlallemand** [comment] 2020-08-19 16:31
Sure, everything looks fine in my opinion. Closing the issue.

**Closed as completed by wlallemand** 2020-08-19 16:31 UTC
Labels: type: bug, status: invalid, subsystem: ssl
