### ISSUE TITLE
[haproxy 2.2 - all?] Lua server:set_weight() does not plays well with numbers

### ISSUE THREAD

**Issue by khvzak** [haproxy/haproxy#1155] opened 2021-03-02 15:34 UTC
## Detailed description of the problem
There are two bugs:
1) Setting server weight using Lua numbers does not work after arithmetic operations
2) Function `hlua_pushstrippedstring` strips last symbol in a string before `\0`

## Expected behavior
1) Haproxy rounds doubles to integers

2) Haproxy prints correct error message
The string **Trailing garbage in weight strin** has missing letter **g**

## Steps to reproduce the behavior

```
$ haproxy -d -f haproxy.cfg
[NOTICE] 060/151732 (48339) : New worker #1 (48340) forked
Trailing garbage in weight strin
```

## Do you have any idea what may have caused this?
```
int hlua_server_set_weight(lua_State *L)
{
....
// Returned string could be in format "Integer.0" after converting double to a string
// It should be normalised before applying strtol()
weight = luaL_checkstring(L, 2); 
...
}
```

## What is your configuration?
```
global
    master-worker
    lua-load haproxy.lua

defaults
    mode http
    option httplog
    log stdout format raw daemon info
    timeout connect 1s
    timeout client 3s
    timeout server 3s

listen http-in
    bind 127.0.0.1:8080

backend test
    server a 1.1.1.1
```

**haproxy.lua**
```
core.register_task(function ()
    local weight = 100 / 1
    print(core.backends["test"].servers["a"]:set_weight(weight))
end)
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.9-a947cc2 2021/02/06 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
Running on: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
Build options :
  TARGET  = osx
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-string-plus-int -Wtype-limits -Wshift-negative-value -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_THREAD=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : -EPOLL +KQUEUE -NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL +LUA -FUTEX -ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with clang compiler version 12.0.0 (clang-1200.0.32.29)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

**Comment by capflam** [comment] 2021-03-02 15:54
`hlua_pushstrippedstring()` seems indeed to be buggy. However, the `set_weight()` lua function is documented to get a positive integer. See "set weight" command in management.txt. You may use `math.floor()` or the floor division (`//`) in your lua script.

**Comment by capflam** [comment] 2021-03-03 18:58
I fixed `hlua_pushstrippedstring()` function. However, the main issue is not a bug. It works as expected and documented. Thus I'm closing this issue.

**Closed as completed by capflam** 2021-03-03 18:58 UTC
Labels: type: bug, status: works as designed
