### ISSUE TITLE
Does HAProxy Load balancing works on UDP??

### ISSUE THREAD

**Issue by Yasminkundur** [haproxy/haproxy#1963] opened 2022-12-13 05:48 UTC
### Your Feature Request

Need HAProxy load balancing for UDP mode.

### What are you trying to do?

I am trying to set haproxy for load balancing for UDP mode. Here mode=http(tcp) if not mentioned it defaults to tcp can we achieve this for UDP??
======================================================================
```
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend myfrontend
        bind 127.0.0.1:2125
default_backend myservers

backend myservers
  server server 127.0.0.1:8000

=======================================
error when udp mode is set
cat /etc/haproxy/haproxy.cfg
#---------------------------------------------------------------------
# Example configuration for a possible web application.  See the
# full configuration options online.
#
#   http://haproxy.1wt.eu/download/1.4/doc/configuration.txt
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    # to have these messages end up in /var/log/haproxy.log you will
    # need to:
    #
    # 1) configure syslog to accept network log events.  This is done
    #    by adding the '-r' option to the SYSLOGD_OPTIONS in
    #    /etc/sysconfig/syslog
    #
    # 2) configure local2 events to go to the /var/log/haproxy.log
    #   file. A line like the following can be added to
    #   /etc/sysconfig/syslog
    #
    #    local2.*                       /var/log/haproxy.log
    #
    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    udp
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# main frontend which proxys to the backends
#---------------------------------------------------------------------
frontend myfrontend
        bind 127.0.0.1:2125
        dgram-bind 0.0.0.0:514
default_backend myservers

backend myservers
  server server 127.0.0.1:8000
  server server 127.0.0.1:12123
  server server 127.0.0.1:12152
  server server 127.0.0.1:3386
```

```
# systemctl restart haproxy
# systemctl status haproxy -l
● haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2022-12-13 11:17:43 IST; 4s ago
  Process: 23457 ExecStart=/usr/sbin/haproxy-systemd-wrapper -f /etc/haproxy/haproxy.cfg -p /run/haproxy.pid $OPTIONS (code=exited, status=1/FAILURE)
 Main PID: 23457 (code=exited, status=1/FAILURE)

Dec 13 11:17:43 kubernetes-master haproxy-systemd-wrapper[23457]: [WARNING] 346/111743 (23458) : config : 'option forwardfor' ignored for frontend 'myfrontend' as it requires HTTP mode.
Dec 13 11:17:43 kubernetes-master haproxy-systemd-wrapper[23457]: [WARNING] 346/111743 (23458) : parsing [/etc/haproxy/haproxy.cfg:70] : backend 'myservers', another server named 'server' was defined without an explicit ID at line 69, this is not recommended.
Dec 13 11:17:43 kubernetes-master haproxy-systemd-wrapper[23457]: [WARNING] 346/111743 (23458) : parsing [/etc/haproxy/haproxy.cfg:71] : backend 'myservers', another server named 'server' was defined without an explicit ID at line 69, this is not recommended.
Dec 13 11:17:43 kubernetes-master haproxy-systemd-wrapper[23457]: [WARNING] 346/111743 (23458) : parsing [/etc/haproxy/haproxy.cfg:72] : backend 'myservers', another server named 'server' was defined without an explicit ID at line 69, this is not recommended.
Dec 13 11:17:43 kubernetes-master haproxy-systemd-wrapper[23457]: [WARNING] 346/111743 (23458) : config : 'option forwardfor' ignored for backend 'myservers' as it requires HTTP mode.
Dec 13 11:17:43 kubernetes-master haproxy-systemd-wrapper[23457]: [ALERT] 346/111743 (23458) : Fatal errors found in configuration.
Dec 13 11:17:43 kubernetes-master systemd[1]: haproxy.service: main process exited, code=exited, status=1/FAILURE
Dec 13 11:17:43 kubernetes-master haproxy-systemd-wrapper[23457]: haproxy-systemd-wrapper: exit, haproxy RC=1
Dec 13 11:17:43 kubernetes-master systemd[1]: Unit haproxy.service entered failed state.
Dec 13 11:17:43 kubernetes-master systemd[1]: haproxy.service failed.
```
 

### Output of `haproxy -vv`

```plain
HA-Proxy version 1.5.18 2016/05/10
Copyright 2000-2016 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 8192, maxpollevents = 200

Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.7
Compression algorithms supported : identity, deflate, gzip
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
Built with PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
```

**Comment by TimWolla** [comment] 2022-12-13 08:28
Generic UDP load-balancing is not supported. This is effectively a duplicate of #62.

**Closed as not planned** 2022-12-13 08:28 UTC
Labels: status: duplicate, type: feature
