### ISSUE TITLE
accept-invalid-http-request option does not work

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#2773] opened 2024-10-31 02:25 UTC
### Detailed Description of the Problem

I checked that even if I enabled the option, I got an error response.
It seems that the intention is to leave only log on the code.

```
                        if (h1m->err_pos < -1) { /* PR_O2_REQBUG_OK not set */
                                state = H1_MSG_HDR_VAL;
                                goto http_msg_invalid;
                        }
                        if (h1m->err_pos == -1) /* PR_O2_REQBUG_OK set: just log */
                                h1m->err_pos = ptr - start + skip;

```

### Expected Behavior

I got a error response message that defined in http.c ( HTTP_ERR_400 )

### enable option ###
``` 
    #### option ####
    option accept-invalid-http-request
```

### Steps to Reproduce the Behavior

1. enable  accept-invalid-http-request option
2. bad header test
curl -i -v -H 'content-length: -1' http://haproxy_serve
3. bad url test
curl -i -v 'http://haproxy_server/test?oq=haproxy invalid request'

### What is your configuration?

```haproxy
#### option ####
    option accept-invalid-http-request
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.9 2024/04/05 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.9.html
Running on: Linux 5.11.0-1.el7.elrepo.x86_64 #1 SMP Sun Feb 14 18:10:38 EST 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = cc
  CFLAGS  = -Og -march=native -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DHAPROXY_TARGET_VERSION=280 -DTLS_TICKETS_NO=4
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_QUIC=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1w+quic  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w+quic  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-16)
```

**Comment by Darlelet** [comment] 2024-10-31 10:43
When this option is set, haproxy will relax some checks, but it doesn't mean that it will accept any invalid request, there are some parsing checks that may still "fail" even when the option is set, because haproxy simply doesn't know how to deal with it.

The documentation gives some hints about what is expected to be "relaxed" when the option is set:
https://docs.haproxy.org/dev/configuration.html#4.2-option%20accept-unsafe-violations-in-http-request

(Note that the option was renamed to be more explicit in 4de663269367f689cb1607d621d77db2d88d95f0)

**Comment by Darlelet** [comment] 2024-10-31 10:51
Example:
```haproxy
listen test
  mode http
  #option accept-invalid-http-request
  http-request return status 200
```

With `option accept-unsafe-violations-in-http-request`:

```
GET / HTTP

HTTP/1.1 200 OK
content-length: 0
connection: close
```

Without option:
```
GET / HTTP

HTTP/1.1 400 Bad request
Content-length: 90
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
```

**Comment by capflam** [comment] 2024-11-04 07:39
Indeed, an invalid content-length cannot be supported at all because it directly impacts the message parsing. In addition, note your second example of invalid request, about the bad url, is not rejected by haproxy but by curl itself
```
curl  -v 'http://abcdef.abcdef:666/test?oq=haproxy invalid request'
* processing: http://abcdef.abcdef:666/test?oq=haproxy invalid request
* URL rejected: Malformed input to a URL function
* Closing connection
curl: (3) URL rejected: Malformed input to a URL function
```

Here no connexion was established. I guess we can close the issue considering it works as designed.

**Closed as completed by capflam** 2024-11-04 07:39 UTC
Labels: type: bug, status: works as designed
