### ISSUE TITLE
ssl-min-ver SSLv3 does not work; min-ver still TLSv1.0 without force-sslv3

### ISSUE THREAD

**Issue by in4mer** [haproxy/haproxy#676] opened 2020-06-11 08:53 UTC
## Output of `haproxy -vv` and `uname -a`

```
Linux hostname 4.14.154-99.181.amzn1.x86_64 #1 SMP Sat Nov 16 01:38:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
HA-Proxy version 1.8.25 2020/04/02
Copyright 2000-2020 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = x86_64
  CC      = gcc
  CFLAGS  = -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-null-dereference -Wno-unused-label -Wno-stringop-overflow
  OPTIONS = USE_LINUX_SPLICE=1 USE_LINUX_TPROXY=1 USE_ZLIB=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.21 2011-12-12
Running on PCRE version : 8.21 2011-12-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace

```

## What's the configuration?

```
global
  user haproxy
  group haproxy
  log /dev/log local0
  log-tag haproxy
  chroot /var/lib/haproxy
  daemon
  quiet
  stats socket /var/lib/haproxy/stats level admin
  stats timeout 5m
  maxconn 8192
  pidfile /var/run/haproxy.pid
  tune.bufsize 262144
  ssl-default-bind-ciphers ECDH:TLSv1.2:+CBC:SSLv3:!aNULL:!eNULL:!MD5:!RC4:!DES:!3DES:!RC2:!DH:+SHA1
  ssl-default-bind-options ssl-min-ver TLSv1.1 no-tls-tickets
  ssl-dh-param-file /etc/haproxy/dhparam

defaults
  timeout connect 12s
  timeout server 180s
  timeout client 180s
  log global
  mode http
  balance roundrobin
  option httplog
  option dontlognull
  option redispatch
  retries 5
  stats uri /unicorn-stats
  compression algo gzip raw-deflate
  compression type text/html text/css text/plain text/xml application/javascript application/x-javascript application/json application/json;charset=utf-8 application/xml application/soap+xml

frontend world-in
  mode tcp
  default_backend https-normal
  bind *:443
  maxconn 4096
  acl internal src 10.0/8 127.0/8
  acl luddites src 1.2.3.4/32 64.41.200.0/24
  use_backend httpr if luddites
  option dontlog-normal

frontend https-in
  mode http
  default_backend nope
  bind *:80
  bind *:444 ssl crt /etc/haproxy/certs/lol.bundle.pem accept-proxy ssl-min-ver TLSv1.1 no-tls-tickets
  maxconn 4096
  acl internal src                           10.0/8 127.0/8
  acl isping path                        -i  /ping
  option forwardfor
  http-request redirect scheme https code 301 if !internal !isping !{ ssl_fc }

frontend httpr-in
  mode http
  default_backend nope
  bind 127.0.0.1:442 ssl crt /etc/haproxy/certs/lol.bundle.pem accept-proxy ssl-min-ver SSLv3 no-tls-tickets ciphers SSLv3:!DES:!aNULL:!eNULL:!RC2:!SEED:DH:3DES:RC4
  option forwardfor

backend httpr
  mode tcp
  server localhost 127.0.0.1:442 send-proxy-v2

backend https-normal
  mode tcp
  server localhost 127.0.0.1:444 send-proxy-v2

backend nope
  server no_servers_in_config 127.0.0.1:1 disabled


```

## Steps to reproduce the behavior

1. Start haproxy
2. Run qualys ssl scanner against the listener
3. Observed supported protocols

## Actual behavior

TLSv1.0 is oldest supported protocol with this bind configuration

## Expected behavior

SSLv3 should be the oldest supported protocol with this bind configuration

## Do you have any idea what may have caused this?

Nope.  I used force-sslv3 and SSLv3 worked, to the exclusion of all the other previously available protocols.  I have a need for clients to be able to use the best encryption they're capable of supporting; no reason to force SSLv3 if it's unnecessary.

TLSv1.0 has ciphers available that are from SSLv3, so it isn't the cipher list.

## Do you have an idea how to solve the issue?

No I do not.

I tried removing all the defaults in global to see if they were messing with the bind options for httpr-in.  They were not.

**Comment by wlallemand** [comment] 2020-06-11 09:07
Hello,

This is a duplicate of #595, it was not backported to 1.8 yet.

**Comment by in4mer** [comment] 2020-06-11 09:32
Hmmm, I think the scope is larger than the linked issue suggests.  At least in severity; I'm unable to select SSLv3 on the bind line itself.  If I disable defaults entirely..  still no SSLv3.

**Comment by lukastribus** [comment] 2020-06-11 10:16
Most likely your underlying OpenSSL library has been compiled without support for SSLv3.

Are you able to use SSLv3 with openssl command line?

**Comment by chipitsine** [comment] 2020-06-11 10:33
when you run `haproxy -vv`, does it show sslv3 support ?

**Comment by chipitsine** [comment] 2020-06-11 10:33
in your above output - it does.
if that could happen when openssl lib is built with sslv3 support, it looks like a bug

**Comment by wlallemand** [comment] 2020-06-11 10:46
This is activated at build, it could be available in the .h during the build and then disabled in openssl.cnf for example.

**Comment by wlallemand** [comment] 2020-06-11 10:48
But the fact that it worked with force-sslv3 shows that there is a problem, I'll take a look at the code.

**Comment by chipitsine** [comment] 2020-06-11 10:56
Hmm, this is build time setting, not runtime?

**Comment by wlallemand** [comment] 2020-06-11 15:48
> Hmm, this is build time setting, not runtime?

Some parts of this code are built depending on macros.

I think I found the problem with the help of @jmagnin.

With OpenSSL >= 1.1.0, there is an API which sets the minimum and maximum SSL version to use on a bind line, it was implemented as ssl-min-ver and ssl-max-ver in HAProxy. However, to be compatible with previous version of OpenSSL it is emulated by putting the right SSL options.

We can't reproduce the problem with standard OpenSSL versions, but it seems that Amazon patched the SSL_CTX_new() function with a SSL_OP_NO_SSLv3 option. Which explains the difference.


[0001-BUG-MINOR-ssl-fix-ssl-min-max-ver-with-openssl-1.1.0.patch.txt](https://github.com/haproxy/haproxy/files/4765852/0001-BUG-MINOR-ssl-fix-ssl-min-max-ver-with-openssl-1.1.0.patch.txt)

The attached patch should fix the issue.

**Comment by jmagnin** [comment] 2020-06-11 15:51
I was able to test the patch on an amazon linux ami and can confim it fixes the issue.

**Comment by in4mer** [comment] 2020-06-11 21:17
I tossed in that line addition to the beginning of the CONF_TLSV loop in 1.8.25 and I've observed the same no-sslv3 behavior.  So it's either pebkac or my obvious lack of domain knowledge.

I have as well confirmed desired operation with 2.2-dev9.

**Comment by in4mer** [comment] 2020-06-11 22:02
OK it was pebkac for sure.  `make PREFIX=/usr install` cleaned all that up.  Pathing is hard.  Confirmed working in 1.8.25, thank you all very much.

**Comment by jmagnin** [comment] 2020-06-11 22:06
@in4mer thanks for confirming, and thanks for reporting this problem. I will re open this issue and it will be closed when the fix is backported to all affected branches.

**Comment by in4mer** [comment] 2020-06-11 22:13
Ah thanks, sorry for the confusion.  Here's the 1.8.25 patch backport for posterity.

```diff --git a/src/ssl_sock.c b/src/ssl_sock.c
index fa37bc0..b6f5080 100644
--- a/src/ssl_sock.c
+++ b/src/ssl_sock.c
@@ -3846,7 +3846,11 @@ ssl_sock_initial_ctx(struct bind_conf *bind_conf)
        /* find min, max and holes */
        min = max = CONF_TLSV_NONE;
        hole = 0;
-       for (i = CONF_TLSV_MIN; i <= CONF_TLSV_MAX; i++)
+       for (i = CONF_TLSV_MIN; i <= CONF_TLSV_MAX; i++) {
+               /* clear every version flags in case SSL_CTX_new()
+                * returns an SSL_CTX with disabled versions */
+               SSL_CTX_clear_options(ctx, methodVersions[i].option);
+
                /*  version is in openssl && version not disable in configuration */
                if (methodVersions[i].option && !(flags & methodVersions[i].flag)) {
                        if (min) {
@@ -3867,6 +3871,7 @@ ssl_sock_initial_ctx(struct bind_conf *bind_conf)
                        if (min)
                                hole = i;
                }
+       }
        if (!min) {
                ha_alert("Proxy '%s': all SSL/TLS versions are disabled for bind '%s' at [%s:%d].\n",
                         bind_conf->frontend->id, bind_conf->arg, bind_conf->file, bind_conf->line);
```

**Closed as completed** 2020-08-03 14:59 UTC
Labels: type: bug, status: fixed
