### ISSUE TITLE
HAPROXY-NOTIFY frame not being sent by haproxy on `tcp-request content send-spoe-group`

### ISSUE THREAD

**Issue by jakubzytka** [haproxy/haproxy#1736] opened 2022-06-08 10:53 UTC
### Detailed Description of the Problem

After sending a request to haproxy a connection with SPOA is established (HAPROXY-HELLO, AGENT-HELLO), but a NOTIFY frame never gets sent to the agent. Eventually, the connection times out.

After changing `tcp-request content send-spoe-group` to sending SPOP messages on some event, e.g. `on-frontend-tcp-request` haproxy communicates with the agent correctly.

Logs from haproxy:
```Note: setting global.maxconn to 524264.
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result FAILED
Total: 3 (2 usable), will use epoll.

Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
Using epoll() as the polling mechanism.

1654684473.494026 [SPOE/test           ] spoe_start: stream=0x557519b9c280
Connect from 127.0.0.1:59422 to 127.0.0.1:1234 (frontend/TCP)
Connect from 127.0.0.1:59422 to 127.0.0.1:1234 (frontend/TCP)
00000000:frontend.accept(0004)=0029 from [127.0.0.1:59422] ALPN=<none>
1654684473.494026 [SPOE/test           ] spoe_start_analyze: stream=0x557519b9c280 - ctx-state=READY - ctx-flags=0x00000000
1654684473.494026 [SPOE/test           ] spoe_process_event: stream=0x557519b9c280 - ctx-state=READY - Process messages for event=on-client-session
1654684473.494026 [SPOE/test           ] spoe_process_group: stream=0x557519b9c280 - ctx-state=READY - Process messages for group=testgroup
1654684473.494026 [SPOE/test           ] spoe_encode_messages: stream=0x557519b9c280 - encode unfragmented messages - spoe_appctx=(nil)- max_size=16348 - encoded=26
1654684473.494026 [SPOE/test           ] spoe_queue_context: stream=0x557519b9c280 - try to create new SPOE appctx
1654684473.494026 [SPOE/test           ] spoe_queue_context: stream=0x557519b9c280 - Add stream in sending queue - applets=1 - idles=0 - processing=1
1654684473.494026 [SPOE/test           ] spoe_send_group: stream=0x557519b9c280 - failed to process group 'testgroup': interrupted by caller
1654684473.494026 [SPOE/test           ] spoe_end_analyze: stream=0x557519b9c280 - ctx-state=NONE - ctx-flags=0x00000001
1654684473.494026 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=CONNECT
1654684473.494026 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=CONNECTING
1654684473.494233 [SPOE/test           ] spoe_start_analyze: stream=0x557519b9c280 - ctx-state=READY - ctx-flags=0x00000001
1654684473.494233 [SPOE/test           ] spoe_process_event: stream=0x557519b9c280 - ctx-state=READY - Process messages for event=on-server-session
1654684473.494233 [SPOE/test           ] spoe_end_analyze: stream=0x557519b9c280 - ctx-state=READY - ctx-flags=0x00000003
1654684473.494486 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=CONNECTING
1654684473.494486 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=IDLE
1654684473.494486 [SPOE/test           ] spoe_handle_processing_appctx: appctx=0x557519df6940 - process: fpa=0/20 - appctx-state=PROCESSING - weight=0 - flags=0x00000000

... here passes 5 seconds ...

1654684478.499206 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=IDLE
1654684478.499206 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=DISCONNECT
1654684478.499206 [SPOE/test           ] spoe_handle_disconnect_appctx: appctx=0x557519df6940 - disconnected by HAProxy (2): a timeout occurred
1654684478.499206 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=DISCONNECTING
1654684478.499390 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=DISCONNECTING
1654684478.499412 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=DISCONNECTING
1654684478.499412 [SPOE/test           ] spoe_handle_disconnecting_appctx: appctx=0x557519df6940 - disconnected by peer (0): normal
1654684478.499412 [SPOE/test           ] spoe_handle_appctx: appctx=0x557519df6940 - appctx-state=EXIT
1654684478.499412 [SPOE/test           ] spoe_release_appctx: appctx=0x557519df6940
00000001:testspoa.clicls[ffff:002a]
00000001:testspoa.srvcls[ffff:ffff]
00000001:testspoa.closed[ffff:ffff]
00000000:servers.srvcls[0029:ffff]
00000000:servers.clicls[ffff:ffff]
00000000:servers.closed[ffff:ffff]
1654684503.496316 [SPOE/test           ] spoe_stop: stream=0x557519b9c280
```

logs from spoa-mirror:
```[ 2][  165.061131]       <2:46> --> Receiving data
[ 2][  165.061148]         <2:46> 4/4/4 byte(s) received frame length
[ 2][  165.061154]         <2:46> 129/129/129 byte(s) received frame data
[ 2][  165.061161]       <2:46> New frame of 129 bytes received: <0100000001000012737570706f727465642d76657273696f6e730803322e300e6d61782d6672616d652d73697a6503fcf0060c6361706162696c69746965730810706970656c696e696e672c6173796e6309656e67696e652d6964082433373164336335312d633734382d346366392d383435312d666431346533393864313130> <........supported-versions..2.0.max-frame-size.....capabilities..pipelining,async.engine-id.$371d3c51-c748-4cf9-8451-fd14e398d110>
[ 2][  165.061167]         <2> --> HAPROXY-HELLO decoding frame
[ 2][  165.061172]         <2> --> HAPROXY-HELLO header 1 0x01000000 0 0
[ 2][  165.061176]         <2> --> HAPROXY-HELLO stream-id=0 - frame-id=0
[ 2][  165.061180]         <2> K/V item: key=supported-versions
[ 2][  165.061184]             <2> --> HAPROXY-HELLO supported versions: 2.0
[ 2][  165.061188]         <2> K/V item: key=max-frame-size
[ 2][  165.061191]             <2> --> HAPROXY-HELLO maximum frame size: 16380
[ 2][  165.061195]         <2> K/V item: key=capabilities
[ 2][  165.061198]             <2> --> HAPROXY-HELLO capabilities check: pipelining,async
[ 2][  165.061202]             <2> --> HAPROXY-HELLO capabilities set: pipelining async 
[ 2][  165.061206]         <2> K/V item: key=engine-id
[ 2][  165.061210]             <2> --> HAPROXY-HELLO engine id: 371d3c51-c748-4cf9-8451-fd14e398d110
[ 2][  165.061215]         <2> <-- AGENT-HELLO encoding frame
[ 2][  165.061221]         <2> <-- AGENT-HELLO stream-id=0 - frame-id=0
[ 2][  165.061225]       <2> <-- AGENT-HELLO version: 2.0
[ 2][  165.061228]       <2> <-- AGENT-HELLO maximum frame size: 16380
[ 2][  165.061232]       <2> <-- AGENT-HELLO capabilities: 
[ 2][  165.061237]       <2:46> <-- Sending data
[ 2][  165.061265]         <2:46> 4/4/4 byte(s) send frame length
[ 2][  165.061279]         <2:46> 54/54/54 byte(s) send frame data
[ 2][  165.061285]       <2:46> Frame of 54 bytes sent: <650000000100000776657273696f6e0803322e300e6d61782d6672616d652d73697a6503fcf0060c6361706162696c69746965730800> <e.......version..2.0.max-frame-size.....capabilities..>
[ 2][  170.066096]       <2:46> --> Receiving data
[ 2][  170.066117]         <2:46> 4/4/4 byte(s) received frame length
[ 2][  170.066123]         <2:46> 49/49/49 byte(s) received frame data
[ 2][  170.066126]       <2:46> New frame of 49 bytes received: <020000000100000b7374617475732d636f64650302076d6573736167650812612074696d656f7574206f63637572726564> <........status-code...message..a timeout occurred>
[ 2][  170.066130]         <2> --> HAPROXY-DISCONNECT decoding frame
[ 2][  170.066134]         <2> --> HAPROXY-DISCONNECT header 2 0x01000000 0 0
[ 2][  170.066137]         <2> --> HAPROXY-DISCONNECT stream-id=0 - frame-id=0
[ 2][  170.066140]         <2> K/V item: key=status-code
[ 2][  170.066143]             <2> --> HAPROXY-DISCONNECT status code: 2 (a timeout occurred)
[ 2][  170.066146]         <2> K/V item: key=message
[ 2][  170.066148]             <2> --> HAPROXY-DISCONNECT message: a timeout occurred
[ 2][  170.066153]         <2> <-- AGENT-DISCONNECT encoding frame
[ 2][  170.066156]         <2> <-- AGENT-DISCONNECT stream-id=0 - frame-id=0
[ 2][  170.066160]       <2> <-- AGENT-DISCONNECT status code: 0
[ 2][  170.066163]       <2> <-- AGENT-DISCONNECT message: normal
[ 2][  170.066171]       <2:46> <-- Sending data
[ 2][  170.066194]         <2:46> 4/4/4 byte(s) send frame length
[ 2][  170.066211]         <2:46> 37/37/37 byte(s) send frame data
[ 2][  170.066218]       <2:46> Frame of 37 bytes sent: <660000000100000b7374617475732d636f64650300076d65737361676508066e6f726d616c> <f.......status-code...message..normal>
[ 2][  170.066224]       <2:46> Release client
```

`failed to process group 'testgroup': interrupted by caller` looks weird. I do not see a reason why `ret == 0`, which leads to logging "interrupted by caller" would mean any interrupt (but I only took a quick glance through the code)

### Expected Behavior

I expect NOTIFY frame to be delivered to the agent for processing.

### Steps to Reproduce the Behavior

1. start haproxy 
```./haproxy -V -d -f haproxy-bug.cfg```
2. start a backend
`netcat -l -k 23456`
3. start a `spoa-mirror` agent (NOTE: spoa-mirror agent is only being used to show SPOP communication; the same behavior can be observed e.g. with `spoa-server` that has a trivial callback, printing out the args (which never gets called back)
```./spoa-mirror --runtime 0 --mirror-url http://localhost:34567```
4. call the proxy
```echo "whatever" | netcat localhost 1234```

### What is your configuration?
haproxy
Configuration:
`haproxy-bug.cfg`
```
global
    log stdout  format raw  local0 

defaults
    log global
    timeout connect 10s
    timeout client 30s
    timeout server 30s

# Production frontend
frontend frontend
    log stdout  format raw local0 
    mode tcp
    bind :1234
    filter spoe  engine testengine  config testengine-group.cfg
    tcp-request content send-spoe-group testengine testgroup
    default_backend servers

# Production servers
backend servers
    mode tcp
    server s1 localhost:23456

backend testspoa
    mode tcp
    balance roundrobin
    timeout connect 5s
    timeout server 5s
    server agent1 localhost:12345
```

`testengine-group.cfg`

```
[testengine]
spoe-agent test
    groups testgroup
    use-backend testspoa
    timeout hello 1500ms
    timeout idle 5s
    timeout processing 5s

spoe-message testreq
    args len=req.len req=req.payload(0,0)

spoe-group testgroup
    messages testreq
```

### Output of `haproxy -vv`

```plain
version 2.6.0-a1efc048bf8 2022/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.0.html
Running on: Linux 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_OPENSSL=1 USE_LUA=1
  DEBUG   = -DDEBUG_SPOE

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=12).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

It looks to me very suspicious that a super simple use of a standard feature wouldn't work.
Did I mess up the configuration?

**Comment by capflam** [comment] 2022-06-08 13:14
At first glance, I thought it was just because there is no inspect-delay. And indeed, you should specify an inspect-delay to make it work. In your case, this should work. But there are some cases where it will not work as expected. For an HTTP proxy, this will not work if the whole message is received before the end of the inspect-delay.

Note that with your configuration, even with an inspect-delay, you are not waiting for data. Thus only data available when the rule is executed will be considered.

**Comment by jakubzytka** [comment] 2022-06-09 08:39
Thanks for a prompt response, and please bear with me, because it looks like I'm missing some basics.

First, in my example, the SPOP message is supposed to carry `req.payload`. Suppose that this message contains say `src`. In such a case, the `NOTIFY` frame is not sent either. Why would I need any delay to be able to send the source address?

I understand that `tcp-request content` directive is supposed to perform an action on a new *session*.
However, the `tcp-request inspect-delay` docs say:
> Note that when performing content inspection, HAProxy will evaluate the whole
> rules for every new chunk which gets in, taking into account the fact that
> those data are partial. (...) If no delay is set, HAProxy will not wait at all
> and will immediately apply a verdict based on the available information.
> Obviously this is unlikely to be very useful and might even be racy, so such
> setups are not recommended.

and so my understanding was the following:

HAProxy got a chunk. Those data are partial. I'm fine. I'd like this partial data to be sent in a SPOP message to my agent without any delay. And when another chunk comes in I'd like another SPOP message with that new chunk to be sent.
Does the comment about raciness mean that e.g. two subsequent chunks could be sent in parallel so that the agent wouldn't be able to order the chunks properly?

Did I make unwarranted assumptions about what SPOE can do? (I'm looking at the "Stream" part of the name specifically ;)

On a more general level - is there a way to utilize SPOE to do an external inspection of a TCP stream that is being proxied by HAProxy? (say - count the number of bytes in the stream that are equal to 0x12).
I'm willing to accept data copying, but I'd like to avoid any additional delays or buffering in the proxy that would hurt latency on regular backends.

Is perhaps The Right Way™ (in HAProxy world) to write own filter (and be able to explicitly deal with edge cases like the agent being slower than the backends)?

**Comment by capflam** [comment] 2022-06-10 07:41
A TCP or an HTTP rule is an action performed under some conditions. Rulesets evaluations are performed before any forwarding. Thus, on the request side, the evaluation is performed before the server connection is established. It is important to understand this point. The data are sent to the server only when the content inspection is finished (and the request is not rejected of course). For TCP rules, you can wait for more data if necessary but never more than a buffer. It is a hard limit to the content inspection via TCP/HTTP rules. To do so, you should add an inspect-delay (for the TCP part only). In this case, depending on your rules, this can add a latency in the request processing.

About the rules evaluation, it may be stopped because an ACL is waiting for more data or because an action is yielding. When this happens, it is the restart point for the next evaluation. The reason is that a rule must not be executed more than once. Think about `track-sc` actions. Counter must not be incremented several times for the same connection. The documentation is confusing on this point.

Note that most of actions doesn't yield. For the SPOE, `send-spoe-group` action can yield. But not to wait for more data. It  only waits the agent response. Samples used to create SPOE messages are final. So you must guard this action with ACLs to be sure to have expected data.

About your use case, unfortunately, it is not possible yet with the SPOE. Data streaming is planned since a while but it is not on the short term roadmap. The only available solution is to write your own filter, in C or lua.

**Comment by capflam** [comment] 2022-06-10 12:38
My bad, I made a mistake. the whole rules are indeed evaluated for every new chunk, as documented. But only if an ACL is waiting for more data. However, if an action yields, the next evaluation will restart from the corresponding rule, without evaluating its ACLs. Content analysis ends when all rules are evaluated, when a final rule matches (accept,reject...) or when the inspect-delay is reached.

So, in your case, the inspect-delay is missing. Because without such delay, ACLs and actions cannot yield. For the SPOE, it means the `send-spoe-group` action will not wait for the agent response. Note that with such delay, only one message will be sent to your agent except if you add a rule to wait for more data.

**Comment by capflam** [comment] 2022-06-13 06:12
I'm closing with "Works as designed" label.

**Closed as completed by capflam** 2022-06-13 06:12 UTC
Labels: type: bug, status: works as designed
