### ISSUE TITLE
Lua task timeout with 0 timeout

### ISSUE THREAD

**Issue by jorisgio** [haproxy/haproxy#2356] opened 2023-11-23 08:53 UTC
### Detailed Description of the Problem

I have a lua task that runs in loop, and fetch health for various services to store in a map. It works with haproxy 2.6.12, but when upgrading to haproxy 2.8, i get 
`  (3586898) : Lua task: execution timeout. `

### Expected Behavior

I tried to set tune.lua.task-timeout to 0 even though it is the default, but i expect the task to keep running for the entire duration of haproxy running.

### Steps to Reproduce the Behavior

Launch a task that takes some time to run.
If it does not yield for 1s, it will get killed

### Do you have any idea what may have caused this?

MEDIUM: hlua: introduce tune.lua.burst-timeout
New setting was added, default to 1s, and it applies to every lua, including tasks

### Do you have an idea how to solve the issue?

Maybe there should be  tune.lua.task-burst-timeout ?

### What is your configuration?

```haproxy
global
  log /dev/log len 16384 local0 info
  stats socket /run/haproxy/admin.sock mode 660 level admin
  stats timeout 30s
  tune.bufsize 128000
  tune.lua.task-timeout 0
  h1-accept-payload-with-any-method
  lua-load backend_status.lua
  lua-load check_backend.lua

defaults
  timeout check 3s
  timeout connect 2s
  timeout server 60s
  timeout client 90s
  timeout http-keep-alive 3600s
  log global
  option allbackups

The check_backend script : 

local function startsWith(str, substr)
    return string.sub(str, 1, string.len(substr)) == substr
end

local function split_into_kv(str)
  local result = {}
  for line in str:gmatch("[^\r\n]+") do
    local key, value = line:match("([^=]+)=([^=]+)")
    result[key] = value
  end
  return result
end

local function set_default (t, d)
  local mt = {__index = function () return d end}
  setmetatable(t, mt)
end

local function check_backend(server)
  local httpclient = core.httpclient()

  local res = httpclient:get { url = "http://127.0.0.1:9999/" .. server }

  if not (res.status == 200) then
    core.Warning("Failed to fetch backend status : ".. res.status)
    return {}
  end
  return split_into_kv(res.body)
end

local function check_regions()
  local regions = {}
  set_default(regions, {})
  local backends = {"router-node-asia-1","router-node-asia-2","router-node-us-1","router-node-us-2", "router-node-eu-1", "router-node-eu-2"}

  for _, backend_name in pairs(backends) do
    local region = string.match(backend_name, "router%-node%-(%a+)%-")
    local region_services = regions[region]
    set_default(region_services, 1)
    local services = check_backend(backend_name)
    for k, v in pairs(services) do
      if region_services[k] == 1 and v == 1 then
        region_services[k] = 1
      else
        region_services[k] = 0
      end
    end
    regions[region] = region_services
  end
  return regions
end

local function do_health_check()
  while true do
    regions = check_regions()
    for region, services in pairs(regions) do
      for service, status in pairs(services) do
        core.set_map(region .. "-enabled-services.map", service, status)
      end
    end
    core.msleep(100)
  end
end

core.register_task(do_health_check)
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.4-1~bpo11+1 2023/11/18 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.4.html
Running on: Linux 6.1.0-0.deb11.6-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.15-1~bpo11+1 (2023-03-16) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=96).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by Darlelet** [comment] 2023-11-23 09:09
Hi,

Well this is not expected, because as it names implies `tune.lua.burst-timeout` should only trigger timeouts when a lua execution fails to finish or yield before the timeout. It is set to 1000ms by default indeed. It should not cause a long-living task to be killed after 1 second of cumulative runtime: burst-timeout applies on the runtime between 2 yields (that is, lua execution being interrupted and requeued at the end of the hot tasks list, which allows other haproxy tasks to be executed "in parallel" by the current thread)

Indeed, for tasks running alongside haproxy for the whole process lifetime, it is expected that they are often interrupted and rescheduled, either manually by using `core.yield()` or `core.sleep()` functions or automatically by the lua processing engine every `tune.lua.forced-yield` instructions which defaults to 10000.

Did you change `tune.lua.forced-yield` default value?
Just to confirm, when you manually set `tune.lua.burst-timeout` to 0, do you confirm that you observe the same behavior as in 2.6.12 where you previously had no apparent issues with the task?

Perhaps your task is relying on heavy functions that cannot be interrupted, so passed 1 second without being able to interrupt the task, `tune.lua.burst-timeout` kicks in to prevent thread contention. 
Unless there is a bug somewhere in the timeout detection, triggering `tune.lua.burst-timeout` is something you want to avoid, because it means that you're creating contention because of your Lua script which could ultimately lead to the watchdog panicking.

**Comment by Darlelet** [comment] 2023-11-23 09:14
I see that you're relying on the `core.set_map()` function in your script, and that this function may be called multiple times in a row without sleep or yield in between (only the while..true between two `check_regions()` has some delay using `core.msleep()` function)

I don't know what your exact setup is nor how large your map is, but abusing the map class by doing frequent and heavy updates could be one possible cause of contention here.

**Comment by jorisgio** [comment] 2023-11-23 10:03
> Did you change tune.lua.forced-yield default value?

No, all timeouts were defaults. 

> Just to confirm, when you manually set tune.lua.burst-timeout to 0, do you confirm that you observe the same behavior as in 2.6.12 where you previously had no apparent issues with the task?

Yes, it works by setting burst-timeout to 0. But can also confirm with code, see there https://github.com/haproxy/haproxy/blob/7fc52357cb10e98c0c13358aa6f7babc3d81da95/src/hlua.c#L453 while timer->max is set for different kind, burst-timeout is generic. 

>  I see that you're relying on the core.set_map() function in your script, and that this function may be called multiple times in a row without sleep or yield in between (only the while..true between two check_regions() has some delay using core.msleep() function)

> I don't know what your exact setup is nor how large your map is, but abusing the map class by doing frequent and heavy updates could be one possible cause of contention here.

Thanks for the pointer. The setup is quite new, as we are just switching from nginx to haproxy. The map is ~1000 items, i wanted to use stick tables but i didn't see a way to update them from lua. I'll add more yields, it is indeed the for loop that causes the timeout to update the map, that being said i didn't notice any issue but possibly it is a bad idea and will hold a lock or something. Still testing this setup.

**Comment by Darlelet** [comment] 2023-11-23 10:44
Thanks for confirming

>Yes, it works by setting burst-timeout to 0. But can also confirm with code, see there 

Yes indeed, burst-timeout should be considered as some kind of protection/detection against thread contention caused by Lua which should be avoided whenever possible since it will not only affect Lua but also tcp/http request processing, thus it is a global setting.

>Thanks for the pointer. The setup is quite new, as we are just switching from nginx to haproxy. The map is ~1000 items, i wanted to use stick tables but i didn't see a way to update them from lua. I'll add more yields, it is indeed the for loop that causes the timeout to update the map, that being said i didn't notice any issue but possibly it is a bad idea and will hold a lock or something. Still testing this setup.

Oh ok thanks for the details!
Well I'm not expert in this area so I let others complete my answer but yeah maps are often chosen for their simplicity but they are not always the proper choice performance-wise since they were not designed to be used on intensive paths during runtime initially.

Recently there have been some work in 2.9 to try to improve things a bit but I don't know if this could make things better for you:
- 0a20be8915e982afe635f3e16d6c03b5c7d16f3d  DOC: map/acl: Remove the comments about map/acl performance issue 
- 81815a9a83517e0b4f2ec0e33f5de02e3927d86c  MEDIUM: map/acl: Replace map/acl spin lock by a read/write lock. 
- 5fea59754b7765ca83aea3813f8b375160c7f3b0  MEDIUM: map/acl: Accelerate several functions using pat_ref_elt struct ->head list
- 745d1a269b3fdc969abbb7181d534f41c2bcd5e8  MEDIUM: map/acl: Improve pat_ref_set_elt() efficiency (for "set-map", "add-acl"action perfs)
- 0844bed7d365c32e39368c9ee072ecb0572c6bde MEDIUM: map/acl: Improve pat_ref_set() efficiency (for "set-map", "add-acl" action perfs)


>i wanted to use stick tables but i didn't see a way to update them from lua

Indeed you're right, Lua.sticktable class currently lacks methods for writing to tables.

So I understand that your Lua task is responsible for maintaining the services maps up-to-date. But how are you using theses maps within haproxy? Maybe this could give someone some ideas in order to help you achieve the same goal without performance limitations.
Also feel free to ask for help on the mailing list (haproxy@formilux.org, subscribe using [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)), some users might have or know about similar setups and could probably help.

**Comment by jorisgio** [comment] 2023-11-24 18:09
Thanks again for the help that being said I suspect as you pointed out this is better discussed on the mailing list probably.

I spend the last 3 days rolling this out to prod, added some yields and so far even if it is probably not the best setup it works so I am happy enough with it.

Back to the issue, when I started opening this I didn't find the reason then I realised it was about burst timeout. I opened it because I assumed it was not intentional change to apply this to the tasks.
I assumed tasks being out of line of the direct requests path they were running in the background it was probably fine, but you suggested it is not.

Feel free to close this issue if all of this is intentional and burst timeout is indeed important for tasks. Though it might be good to drop a line about it in doc because I was quite confused by this and had to dig in the code, was under the impression from doc burst timeout was also excluded from tasks

**Comment by Darlelet** [comment] 2023-11-27 08:29
Glad you got it to work

>I assumed tasks being out of line of the direct requests path they were running in the background it was probably fine, but you suggested it is not.

Well, from user point of view, Lua tasks are effectively running in parallel from http requests path, so even if they loop forever, they will work without affecting other haproxy features.

However, Lua tasks rely on the haproxy's scheduler API, which is also used for other haproxy tasks such as http/tcp request processing. Unlike general-purpose thread implementations, haproxy scheduler will not interrupt a task in the middle of a function: it is up to the task to manually "yield" when it knows that it's been running for too long already.

For Lua tasks, it is a bit different, since we are able to save Lua's context and this allows us to yield almost everywhere from Lua's code (this is why `tune.lua.forced-yield` is important to ensure no contention is created in most setups), but there is one limitation to that: some Lua functions may not be interrupted, this is the case of blocking functions such as `io.*` library functions or when Lua is executing C function (exposed through Lua) that are not capable of yielding themselves. For the latter,  this is the case with  some haproxy-specific functions such as `core.set_map()` : as long as the function remains relatively fast, there's no harm.. but once it becomes slow due to the number of items to be processed at once for instance, then things could get bad.

So in this case, great care must be taken when relying on such uninterruptible functions, because if the function takes too long to run, then it means the current thread will be stuck in Lua, meaning it will not be able to pick other tasks on the top of haproxy scheduler's run queue. Even worse, the current uninterruptible function may hold locks that other tasks running in parallel (ie: tasks related to http/tcp processing) may rely on, so it might create nasty contention because then multiple threads could become stuck. This is what `tune.lua.burst-timeout` tries to address, when it detects that too much time has been spent in Lua in a single run (without interruption), it aborts the execution to prevent things from getting worse.

Reducing `tune.lua.forced-yield` or manually yielding at some key points within your Lua task (ie: right before and right after a function that is known to cause contention to ensure a full task cycle is dedicated to the function) could help to overcome some issues at the cost of slightly reduced task performance if you're just starting to reach the limits, but this won't help if the function already smashes the "burst" timeout on it's own.

If you're interested in implementation details for how Lua is integrated within haproxy, I suggest that you give a look at : `doc/lua.txt`

It may not be 100% up-to-date but it could give you some valuable insights about the pros and cons of the current implementation.

**Comment by wtarreau** [comment] 2024-01-31 16:31
Hi! Anything else needs to be done for this issue ? It's still qualified as "need triage" and I admit not feeling very enthousiast reading the whole wall of text :-)

**Comment by Darlelet** [comment] 2024-01-31 17:15
No bug here: working as expected technically speaking.

However this issue suggests that Lua tasks may be confusing to some users in the sense that they might not expect tasks to be handled as haproxy tasks internally (or put simpler: that they can negatively impact other haproxy core features, including data processing, when doing heavy processing that cannot be interrupted/yielded from a Lua task).

Somewhat by "Lua task" they may expect fully asynchronous task that runs on a dedicated CPU space (ie: separate thread).

At least, we can say that this confusion was revealed by `lua.burst-timeout` since poorly coded Lua tasks (not poorly coded from Lua perspective, but performance-wise within haproxy context) could silently ruin haproxy performance in the past.

But now such Lua tasks will likely be interrupted and raise "Lua task: execution timeout" generic error messages in such cases with HAProxy 2.8+ (thanks to burst-timeout kicking in), but the user may be tempted to think that the issue lies in haproxy but not in the Lua script. Perhaps we should make a dedicated "Lua task: burst timeout" error message to clearly indicate why the task had to be interrupted.

**Comment by capflam** [comment] 2024-02-29 15:29
So, it seems there is no real issue here. I'm closing. Thanks !

**Closed as not planned by capflam** 2024-02-29 15:29 UTC
Labels: type: bug, status: works as designed
