### ISSUE TITLE
haproxy proxy postgres database,  postgres database canot get client ip

### ISSUE THREAD

**Issue by chenglin321** [haproxy/haproxy#2206] opened 2023-07-07 09:17 UTC
### Your Feature Request

haproxy proxy postgres database,  postgres database canot get client ip

### What are you trying to do?

when i use haproxy proxy postgres databases,  postgres database canot get client ip

haproxy config file:

[root@muban ~]# cat /etc/haproxy18/haproxy.cfg
global
    maxconn 65535
    external-check

defaults
    log global
    retries 2
    timeout client 30m
    timeout connect 4s
    timeout server 30m
    timeout check 5s

listen stats
    mode http
    bind *:4000
    stats enable
    stats uri /

frontend pgReadWrite
    mode tcp
    bind *:5432
    default_backend pgBackend-RW

frontend pgRead
    mode tcp
    bind *:5433
    default_backend pgBackend-RW

backend pgBackend-RW
    mode tcp
    option external-check
    external-check path "/usr/bin:/bin:/usr/local/bin"
    external-check command /usr/local/bin/check_pg_master.sh
    server pg01 pg-1:5432 check inter 6s fall 3
    server pg02 pg-2:5432 check inter 6s fall 3

backend pgBackend-RO
    mode tcp
    option external-check
    external-check path "/usr/bin:/bin:/usr/local/bin"
    # external-check command /usr/local/bin/check_pg_replica.sh
    external-check command /usr/local/bin/check_pg_master.sh
    server pg01 pg-1:5432 check inter 6s fall 3
    server pg02 pg-2:5432 check inter 6s fall 3

========================================================================
postgres log:

2023-07-07 17:12:41 CST [92474]: db=iho_emr,user=emr,app=PostgreSQL JDBC Driver,client=169.169.53.51 DETAIL:

======================================================
 "169.169.53.51" is haproxy ip is not client realip

### Output of `haproxy -vv`

```plain
[root@muban ~]# haproxy18 -vv
HA-Proxy version 1.8.27-493ce0b 2020/11/06
Copyright 2000-2020 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
```

**Comment by git001** [comment] 2023-07-07 10:26
That's quite clear as PostgreSQL does not support [proxy protocol](https://github.com/haproxy/haproxy/blob/master/doc/proxy-protocol.txt), afaik.  
Anyhow as this trackers are only for Bugs, Features or Code report, please use the HAProxy Mailing list for such Questions.

https://www.haproxy.org/#tact

**Comment by chipitsine** [comment] 2023-07-07 10:32
there were some [discussion](https://www.postgresql.org/message-id/CABUevExJ0ifpUEiX4uOREy0s2kHBrBrb=pXLEHhpMTR1vVR1XA@mail.gmail.com), seems patches were not accepted

**Comment by wtarreau** [comment] 2023-07-07 16:38
In fact it's not even that they were not accepted but the discussion died. In any case the issue here is indeed not related to haproxy but to postgresql not supporting the feature, so I'm marking it as "invalid - the problem is not in haproxy". I'm closing to keep the issues list browsable but do not hesitate to ask other questions if needed.

**Closed as completed by wtarreau** 2023-07-07 16:38 UTC
Labels: type: feature, status: invalid
