### ISSUE TITLE
HAProxy 2.0.3 segfault when changing weight

### ISSUE THREAD

**Issue by pickelsandcarrots316** [haproxy/haproxy#189] opened 2019-07-25 17:48 UTC
## Output of `haproxy -vv` and `uname -a`

haproxy -vv
```
HA-Proxy version 2.0.3 2019/07/23 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -DTCP_USER_TIMEOUT=18
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1c  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

```

uname -a
```
Linux lb02.example.com 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
    ssl-mode-async
    log /dev/log   local0 debug
    log 127.0.0.1   local1 debug
    maxconn 4096
    user haproxy
    group haproxy
    daemon
    tune.ssl.default-dh-param 2048
    node lb02.example.com
    stats socket /run/haproxy.sock user haproxy group haproxy mode 660 level admin
    stats socket ipv4@192.168.1.222:3333 level admin
    master-worker
    spread-checks 2
    mailers mta
    mailer smtp.example.com 192.168.3.26:25


peers mypeers
    peer lb01.example.com 192.168.1.221:1024
    peer lb02.example.com 192.168.1.222:1024

listen stats
    bind 192.168.1.222:4444
    mode http
    maxconn 10
    no log
    option http-use-htx
    acl network_allowed src 127.0.0.0/8
    acl network_allowed src 192.168.0.0/16
    tcp-request connection reject if !network_allowed
    stats enable
    stats uri /
    stats refresh 10s
    timeout connect     5000
    timeout client     50000
    timeout server     50000


defaults
    log     global
    mode    http
    option  dontlognull
    retries 3
    option redispatch
    option httplog
    maxconn 2000
    timeout connect     5000
    timeout client     50000
    timeout server     50000
    timeout http-request 15s

    email-alert mailers mta
    email-alert level warning
    email-alert from haproxy@example.com
    email-alert to sadfsadfasdfs@example.slack.com

userlist controller
    user admin password changeme

program api
    command dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "systemctl reload haproxy" --reload-delay 5 --userlist controller --log-to file --log-level trace --log-file /var/log/dataplaneapi.log



frontend www.example2.com
    bind 192.168.1.218:80
    bind 192.168.1.218:443 ssl crt /etc/pki/tls/certs/example2.com.combined.pem alpn h2,http/1.1
    option tcplog
    option logasap
    mode http
    tcp-request inspect-delay 10s


    http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
    acl host_test hdr(host) -i www.example2.com
    redirect scheme https if !{ ssl_fc } host_test

    acl isWEB2IIS path_beg -i /finder
    use_backend finder if isWEB2IIS

    default_backend wordpress_silo
    option http-use-htx
    option http-server-close

frontend www.example.com
    bind 192.168.1.150:80
    bind 192.168.1.150:443 ssl crt /etc/pki/tls/certs/www.example.com.combined.pem alpn h2,http/1.1
    bind 192.168.1.219:80
    bind 192.168.1.219:443 ssl crt /etc/pki/tls/certs/www.example.com.combined.pem alpn h2,http/1.1
    option httplog
    option logasap
    mode http
    tcp-request inspect-delay 10s
    option log-separate-errors



    acl has_www hdr_beg(host) -i www
    acl has_services hdr_beg(host) -i services
    acl is_WEB hdr(host) -i example.com
    http-request redirect code 301 location http://www.example.com%[capture.req.uri] unless has_www OR has_services
    http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
    acl host_test hdr(host) -i www.example.com

    acl isWP path_beg -i /Web/
    use_backend wordpress_silo if isWP
    use_backend internet_443 if { ssl_fc -i example.com }

    acl isSVC path_end .svc
    use_backend internet_80 if isSVC


    default_backend internet_443
    option http-use-htx
    log /dev/log local0 debug

    log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %sslv %sslc"






backend internet_80
    mode http
    balance source
    hash-type consistent
    hash-balance-factor 150
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    option http-use-htx
    option log-health-checks
    server web01 192.168.1.11 track internet_443/web01 weight 10
    #server web02 192.168.1.12 track internet_443/web02 weight 10
    #server web03 192.168.1.13 track internet_443/web03 weight 10
    server web04 192.168.1.14 track internet_443/web04 weight 10
    server web05 192.168.1.15 track internet_443/web05 weight 10
    server web06 192.168.1.16 track internet_443/web06 weight 10
    server web07 192.168.1.17 track internet_443/web07 weight 10
    server web08 192.168.1.18 track internet_443/web08 weight 10


backend internet_443
    balance source
    hash-type consistent
    hash-balance-factor 150
    option http-use-htx
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    option log-health-checks

    server web01 192.168.1.11:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 check weight 10 inter 5s
    #server web02 192.168.1.12:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 check weight 10 inter 5s
    #server web03 192.168.1.13:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt cookie s3 alpn h2,http/1.1 check weight 10 inter 5s
    server web04 192.168.1.14:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 check weight 10 inter 5s
    server web05 192.168.1.15:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 check weight 10 inter 5s
    server web06 192.168.1.16:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 check weight 10 inter 5s
    server web07 192.168.1.17:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 check weight 10 inter 5s
    server web08 192.168.1.18:443 ssl ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 check weight 10 inter 5s




backend wordpress_silo
    balance roundrobin
    mode http
    option http-use-htx
    option forwardfor
    option log-health-checks
    http-request set-header X-Forwarded-Port %[dst_port]
    server wordpress01 192.168.2.21:443 ssl check ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 inter 5s
    server wordpress02 192.168.2.22:443 ssl check ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 backup inter 5s


backend finder
    mode http
    option http-use-htx
    cookie SERVERID insert indirect nocache
    option forwardfor
    option log-health-checks
    http-request set-header X-Forwarded-Port %[dst_port]
    server finder 192.168.1.139:443 ssl check ca-file /etc/ssl/certs/ca-bundle.crt alpn h2,http/1.1 inter 5s

```

## Steps to reproduce the behavior

1. echo "set server internet_443/web01 weight 100" | socat stdio /run/haproxy.sock
2. haproxy[8419]: segfault at 18 ip 0000000000541b99 sp 00007ffeb31b5398 error 4 in haproxy[400000+1a5000]

## Actual behavior

Changing the weight of a server in the backend causes haproxy to crash
## Expected behavior

Changing weight should not crash
## Do you have any idea what may have caused this?
no
## Do you have an idea how to solve the issue?
If the config is set so that the starting weight is 100, I can change it to 10 and it won't crash

**Comment by capflam** [comment] 2019-07-26 08:21
Thanks! I'm able to reproduce the segfault. It is a bug when the array of nodes (`srv->lb_nodes`) is reallocated to increase the number of nodes. I will fix it quickly.

**Comment by capflam** [comment] 2019-07-26 12:39
I pushed a fix and it was backported to 2.0, 1.9 and 1.8. Thanks !

**Comment by TimWolla** [comment] 2019-07-26 12:57
@capflam I'm not seeing anything yet for 1.8. Did you forget to push there?

**Comment by capflam** [comment] 2019-07-26 13:00
@TimWolla, nop. It was pushed: [5c0e731a](http://git.haproxy.org/?p=haproxy-1.8.git;a=commitdiff;h=5c0e731a)

**Comment by pickelsandcarrots316** [comment] 2019-07-31 22:27
After applying that fix, I can still make haproxy crash on demand.

If a server in the backend config has a weight of 10, and the balance algorithm is set to source and the hash-type is set to consistent, ```echo "set server internet_443/web02 weight 100" | socat stdio /var/run/haproxy.sock``` causes a segfault ``` haproxy[25720]: segfault at 18 ip 0000000000541b99 sp 00007ffcb4690e08 error 4 in haproxy[400000+1a5000]  ```

**Comment by capflam** [comment] 2019-08-01 08:07
Hum. Indeed. I've made my tests with smaller weights and the other part of the bug didn't hit me because I was lucky :). In fact, when the weight of a server is increased, its nodes array is re-alloced to have more entries, possibly changing all node pointers. These nodes are referenced in the chash tree. So all server's entries must first be removed from the chash tree, to be reinserted after the realloc.

I'll push a fix quickly. Thanks !

**Comment by capflam** [comment] 2019-08-01 10:07
I pushed the fix. It should be good now. It was also backported. Thanks

**Closed as completed** 2019-10-22 18:10 UTC
Labels: type: bug, severity: medium, status: fixed
