### ISSUE TITLE
2.9-dev SPOE timeouts since at least 2.9-dev7

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#2335] opened 2023-11-07 09:00 UTC
### Detailed Description of the Problem

Hi,

we updated our two dev nodes from 2.9-dev2 to 2.9-dev7 and since then we have like a 100% SPOE failure rate. It looks like the requests timing out for some reason. Upgrading to 2.9-dev9 didn't help. Still broken.
Our other ~50 nodes, running 2.7.10 are all good. no problems. Downgrade seems to fix the problem on the two dev nodes.

### Expected Behavior

Should not timeout, st=0 should be logged

### Steps to Reproduce the Behavior

1. Use the configs provided
2. Trigger some SPOE requests

### Do you have any idea what may have caused this?

Some change between 2.9-dev2 to 2.9-dev7

### What is your configuration?

```haproxy
global
        no strict-limits

        user haproxy
        group haproxy

        log-send-hostname

        set-dumpable

        hard-stop-after 24h

        no-memory-trimming

        log 127.0.0.1 len 65535 local0

        tune.http.logurilen 20480

        stats socket unix@/run/haproxy.stat user haproxy gid haproxy mode 600 level admin
        stats timeout 30m

        maxconn 10000000

        tune.maxrewrite 4096

        tune.bufsize 20480

        ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA

        ssl-default-bind-options no-sslv3 no-tls-tickets

        tune.ssl.default-dh-param 2048

        tune.ssl.capture-buffer-size 96

defaults
        timeout client 13s
        timeout client-fin 5s
        timeout http-request 7s
        timeout server 5m
        timeout connect 7s
        timeout queue 60s
        timeout http-keep-alive 10s
        maxconn 10000000

backend genbackend_coraza_minimal_spop
        mode tcp
        log global
        timeout server 6m
        timeout connect 1s
        option spop-check
        default-server check ssl verify required sni str(coraza-spoa.example.com) ca-file /etc/ssl/certs/ca-certificates.crt
        server k8s-prod 192.168.122.2:12346
        server k8s-dc2 192.168.125.5:12346
        server k8s-ber 192.168.241.4:12346

frontend somefrontend
        ...
        filter spoe engine coraza_minimal config /etc/haproxy/coraza_minimal.conf
        http-request send-spoe-group coraza_minimal check-request
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9-dev9-ff3dcb2 2023/11/04 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DMAX_SESS_STKCTR=12
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB= USE_SLZ=1 USE_NS= USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE= USE_PCRE_JIT= USE_PCRE2=1 USE_PCRE2_JIT=
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```
Nov  7 09:51:24.000 n095157 haproxy[988881]: SPOE: [coraza_minimal] <GROUP:check-request> sid=21587 st=1 0/0/-1/-1/100 12/12 0/0 21/21
Nov  7 09:51:26.000 n095157 haproxy[988881]: SPOE: [coraza_minimal] <GROUP:check-request> sid=21844 st=1 0/4/-1/-1/99 10/10 0/0 22/22
```

### Additional Information

/etc/haproxy/coraza_minimal.conf
```
[coraza_minimal]
spoe-agent coraza_minimal
    groups check-request
    log global
    option       var-prefix  coraza_minimal
    timeout      hello       100ms
    timeout      idle        5m
    timeout      processing  100ms
    use-backend  genbackend_coraza_minimal_spop
    max-waiting-frames 500
    maxconnrate 200

spoe-message check-request
    args   fe_name=fe_name src=src src_port=src_port dst=dst dst_port=dst_port method=method url=url ver=req.ver hdrs_bin=req.hdrs_bin body=req.body,bytes(0,5000)
spoe-group check-request
    messages check-request
```

**Comment by capflam** [comment] 2023-11-08 09:47
It is strange. The timeout occurs when waiting for the agent response. Nothing has changed in the SPOE between the dev2 and dev7. If the issue is easily reproducible on an instance with low traffic, you can try to enable the PT mux traces by adding following config after your global section:
```

ring buf1
       size 104857600 # 10MB
       format timed
       backing-file /tmp/blah
global
       expose-experimental-directives
       trace pt sink buf1
       trace pt level developer
       trace pt verbosity complete
       trace pt start now
```

You can show the traces by running:
```
strings /tmp/blah | less
```

If it does not work, you may use haring tool from HAProxy sources. To do so, you should compile it (```make dev/haring/haring```). Then run ```./dev/haring/haring -f /tmp/blah | less```. If it is too painful, you can share the file instead. 

Another way to enable and show traces is to use the following CLI command:
```
(echo "trace pt sink buf0; trace pt level developer; trace pt verbosity complete; trace pt start now; show events buf0 -w" ; cat ) | socat - /run/haproxy.stat
```

In this case, no need to modify your config.

**Comment by capflam** [comment] 2023-11-08 11:04
Just a quick update. I've check with your config and a coraza SPOA running  locally. And there is no error. But I'm not using SSL connections with the agent.

**Comment by idl0r** [comment] 2023-11-08 12:07
Hm, are we looking for something specific there? It's getting quite huge even after just a few seconds I already have >1G
I was using the runtime commands via stats socket.


haring, at least from dev9 doesn't seem to work. Neither with the ringbuffer nor with the stats command:
haring /tmp/blah 
FATAL: header in file is 64 bytes long vs 56 expected!

**Comment by capflam** [comment] 2023-11-08 12:52
if you have traces when the timeout occurres, it is enough. Use `-f` argument with haring.

**Comment by capflam** [comment] 2023-11-08 15:15
My bad Christian. I suggested you to use the CLI to show PT mux traces. But the CLI uses the PT mux too. Thus this generates an huge amount of traces, recursively... It was a bad idea :/

However, from your traces, I can see one message sent to the agent at `2023-11-08T13:57:32.005206+01:00` and no response at all. The last message from the traces was dumped at `2023-11-08T13:57:34.960137+01:00`. So it may be a side effect of the trace messages from the CLI itself. But it is pretty strange.

**Comment by idl0r** [comment] 2023-11-08 15:26
No problem.
I'll try to bisect it tomorrow. Might be easier

**Comment by capflam** [comment] 2023-11-08 15:27
Ok thanks !

**Comment by idl0r** [comment] 2023-11-09 13:53
Sp it looked like it really was introduced in dev6, since dev5 worked. I then bisected 5..6.
It really seems to be
915e48675ae67ae2725f3646af37862ddaf26720 is the first bad commit
commit 915e48675ae67ae2725f3646af37862ddaf26720
Author: Lokesh Jindal <15ljindal@gmail.com>
Date:   Wed Sep 6 11:11:23 2023 -0700

    MEDIUM: sample: Enhances converter "bytes" to take variable names as arguments
    
    Prior to this commit, converter "bytes" takes only integer values as
    arguments.  After this commit, it can take variable names as inputs.
    This allows us to dynamically determine the offset/length and capture
    them in variables.  These variables can then be used with the converter.
    Example use case: parsing a token present in a request header.

 doc/configuration.txt         |  16 ++++-
 reg-tests/converter/bytes.vtc | 156 ++++++++++++++++++++++++++++++++++++++++++
 src/sample.c                  |  82 +++++++++++++++++++---
 3 files changed, 244 insertions(+), 10 deletions(-)
 create mode 100644 reg-tests/converter/bytes.vtc

Is that possible? I tried to bisect it twice and ended up with that commit twice as well.

**Comment by capflam** [comment] 2023-11-09 14:00
You are using bytes converter. So, yes, it is possible. I don't know yet how. But it is not crazy. Many thanks, I'll review the commit

**Comment by capflam** [comment] 2023-11-09 15:27
Ok, so possible return value for the converter has changed. Before, an empty binary was reported when the offset was greater or equal to the sample length (`req.body` in your case). Now, in this specific case, a conversion failure is returned.  In the SPOE context, it means a NULL value (not a empty string/binary) is sent to the agent.

So, I will fix it of course because this change the converter behavior.  But on your side, you may check how coraza spoa handle this case. It may be a bug.

Just a side note, in your config, you are not waiting for the HTTP payload. Thus, request body will be randomly available, depending if it is received with the request headers or not. It may be on-purpose but not sure it is safe for a waf application. Just my 2 cents.

If your are curious, here is the quick patch. I must validate it but it should be ok
```diff
diff --git a/src/sample.c b/src/sample.c
index 3d9958645..1d4724c71 100644
--- a/src/sample.c
+++ b/src/sample.c
@@ -2728,11 +2728,23 @@ static int sample_conv_bytes(const struct arg *arg_p, struct sample *smp, void *
                smp->data.u.str.data = 0;
                return 0;
        }
-       if (smp_arg0.data.u.sint < 0 || (smp_arg0.data.u.sint >= smp->data.u.str.data)) {
-               // empty output if the arg0 value is negative or >= the input length
+
+       if (smp_arg0.data.u.sint < 0) {
+               // failure if the arg0 value is negative
                smp->data.u.str.data = 0;
                return 0;
        }
+       if ((smp_arg0.data.u.sint >= smp->data.u.str.data)) {
+               // the arg0 >= the input length
+               if (smp->opt & SMP_OPT_FINAL) {
+                       // empty output
+                       smp->data.u.str.data = 0;
+                       return 1;
+               } else {
+                       smp->data.u.str.data = 0;
+                       return 0;
+               }
+       }
        start_idx = smp_arg0.data.u.sint;
 
        // length comes from arg1 if present, otherwise it's the remaining length
@@ -2742,8 +2754,9 @@ static int sample_conv_bytes(const struct arg *arg_p, struct sample *smp, void *
                        smp->data.u.str.data = 0;
                        return 0;
                }
+
                if (smp_arg1.data.u.sint < 0) {
-                       // empty output if the arg1 value is negative
+                       // failure if the arg1 value is negative
                        smp->data.u.str.data = 0;
                        return 0;
                }
```

**Comment by idl0r** [comment] 2023-11-09 15:43
I couldn't apply that patch on the current master HEAD (haproxy.git) but I applied it by hand. It seems to fix the issue at the first glance. No more st=1 so far. So that's really it.

**Comment by idl0r** [comment] 2023-11-09 15:45
> So, I will fix it of course because this change the converter behavior. But on your side, you may check how coraza spoa handle this case. It may be a bug.
> 
> Just a side note, in your config, you are not waiting for the HTTP payload. Thus, request body will be randomly available, depending if it is received with the request headers or not. It may be on-purpose but not sure it is safe for a waf application. Just my 2 cents.

I'll discuss this with my college. Thanks!

**Comment by capflam** [comment] 2023-11-09 16:33
Ok, thanks for the test. I will fix the converter

**Comment by mxey** [comment] 2023-11-10 09:14
> Just a side note, in your config, you are not waiting for the HTTP payload. Thus, request body will be randomly available, depending if it is received with the request headers or not. It may be on-purpose but not sure it is safe for a waf application. Just my 2 cents.

@capflam Our production config enables `option http-buffer-request`, it's just not shown in the reported config above. AFAIK that should work, right?

**Comment by capflam** [comment] 2023-11-10 09:18
With this directive, indeed, the request body will be captured. However, about the issue, the converter must still be fixed in case there is no body. I suspect you have errors for requests with no payload.

**Comment by capflam** [comment] 2023-11-13 10:07
I pushed a fix, it should be good now.

**Closed as completed** 2023-11-13 10:07 UTC
Labels: type: bug, status: fixed
