### ISSUE TITLE
FEATURE: Include config files

### ISSUE THREAD

**Issue by silviubajenaru** [haproxy/haproxy#2045] opened 2023-02-15 11:52 UTC
### Your Feature Request

From my knowledge, one cannot include additional config files in a haproxy.cfg file. This is, at least for me, a bummer, as it would make my life way easier.
The scenario: I'm using Ansible to provision HAProxies + update their configuration. It would be way easier if I could have a "base config", let's call it haproxy.cfg and inside that file, to be able to include whatever files I want. In case a parameter becomes deprecated, I would only need to edit the base config / the file that contains that parameter and redeploy.
Right now, I need to edit multiple files (I've got multiple HAProxy configurations, based on what each does) and it's a bit tedious.

### What are you trying to do?

I'm trying to have something like:
```
--- haproxy.cfg:
      # global settings
      include frontend-http.cfg
      include frontend-https.cfg
      include common-backend.cfg
      include stats-bind.cfg
```
From my point of view (not a dev, not trying to step on anyone's tails) it's not a huge thing to do (not being ignorant, it just feels easily achievable) and I feel like it would benefit a lot of people.

### Output of `haproxy -vv`

```plain
---
```

**Comment by phemmer** [comment] 2023-02-19 02:12
Just fyi, you kinda can do this. Haproxy can load a directory instead of a single file.

https://docs.haproxy.org/2.7/management.html

```
   -f <cfgfile|cfgdir> : adds <cfgfile> to the list of configuration files to be
    loaded. If <cfgdir> is a directory, all the files (and only files) it
    contains are added in lexical order (using LC_COLLATE=C) to the list of
    configuration files to be loaded ; only files with ".cfg" extension are
    added, only non hidden files (not prefixed with ".") are added.
    Configuration files are loaded and processed in their declaration order.
    This option may be specified multiple times to load multiple files. See
    also "--". The difference between "--" and "-f" is that one "-f" must be
    placed before each file name, while a single "--" is needed before all file
    names. Both options can be used together, the command line ordering still
    applies. When more than one file is specified, each file must start on a
    section boundary, so the first keyword of each file must be one of
    "global", "defaults", "peers", "listen", "frontend", "backend", and so on.
    A file cannot contain just a server list for example.
```

If you run multiple haproxy instances on a single machine, and you want to share the config snippets, you can just put a symlink inside the config directory for each instance.

**Comment by wtarreau** [comment] 2023-02-20 09:55
Also duplicate of #183, closing.

**Closed as completed by wtarreau** 2023-02-20 09:55 UTC
Labels: status: duplicate, type: feature
