### ISSUE TITLE
option httpchk do not work with HAProxy 2.2 and mode tcp

### ISSUE THREAD

**Issue by Pkuutn** [haproxy/haproxy#874] opened 2020-09-25 11:26 UTC
## Detailed description of the problem

When using "option httpchk" in "mode tcp" backend (postgresql with patroni in my case) HAProxy reports backend DOWN, with log message: 
```
Server pg-patroni-1/pgsql-db01 is DOWN, reason: Layer7 invalid response, info: “TCPCHK got an empty response at step 1”
```

It seems to work with "option httpchk GET /" config though.

## Expected behavior

Mark server as "UP", curl returns 200:
```
curl -s -w “%{http_code}” -X OPTIONS http://pgsql-db01:8008
200
```

## Do you have any idea what may have caused this?

Broken server check logic

## What is your configuration?

```
frontend pg-patroni-1
        bind 0.0.0.0:5499
        mode tcp
        timeout client 30m
        option tcplog
        default_backend pg-patroni-1

backend pg-patroni-1
        option httpchk
        http-check expect status 200
        default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
        server pgsql-db01 192.168.7.200:5432 check port 8008
        server pgsql-db02 192.168.7.201:5432 check port 8008
        server pgsql-db03 192.168.7.202:5432 check port 8008
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.2-1ppa1~bionic 2020/08/01 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-VfyFQA/haproxy-2.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.5.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app


Linux test1.local 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

**Comment by capflam** [comment] 2020-09-28 09:53
I'm unable to reproduce the bug. I checked quickly and with a similar configuration, it works as expected. You may try to enable the trace on the H1 to figure out what happens. To do so, you should use the following CLI command (or something similar):

```
socat  {HA-SOCK-STAT} readline
trace h1 sink buf0; trace h1 level developer; trace h1 verbosity complete; trace h1 start now; show events buf0 -w 
```
This will wait for events from the H1 multiplexer. Just replace `{HA-SOCK-STAT}` with the path of your stats socket.

**Comment by wtarreau** [comment] 2020-09-29 17:49
Just to confirm, I cannot reproduce it either. For me http checks sent in a TCP backend work fine. There might possibly be fine details (timing or whatever) that affect how the response is processed. The trace Christopher suggests should help.

**Comment by beluc** [comment] 2020-11-27 17:08
Got quite the same for smtpchk. Was working fine under 1.6.14 but since 2.2.5 check is broken. I tried trace too but I'm not familiar with it so don't know what to check after.
Regards.

**Comment by capflam** [comment] 2020-11-27 17:57
If it doesn't work for smtpchk it may be a different issue. Thus provide more info: config and logs. The above trace commands are only useful to debug HTTP/1 checks. Or better, open a new issue. This one is more or less a dead end. No info since 2 months.  If finally you really hit a bug, we will be annoyed once fixed to close this issue because there is no way to know if it is the same issue or not.

Just a hint, it may be good to get a network capture between haproxy and your smtp server. This could really help.

**Comment by wopincm** [comment] 2020-12-03 02:23
I have a similar problem, my haproxy version is 2.3.0
This is my configuration:
```
    listen rw_direct
        bind *:5432
        option httpchk OPTIONS /master
    {{- range .Values.configmap.listen }}
        server {{ .hostname }} {{ .ipaddr }}:5432 check port 8008 maxconn {{ .maxconn }}
    {{- end }}
```
Problems using this configuration
```
Server rw_direct/pg01 is DOWN, reason: Layer7 invalid response, info: "TCPCHK got an empty response at step 1", check duration: 96ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue .
```
This problem did not occur in haproxy version 2.0
Use curl to test
```
curl -i -X ​​OPTIONS x.x.x.x:8008/master -v
* About to connect() to x.x.x.x port 8008 (#0)
* Trying x.x.x.x...
* Connected to x.x.x.x (x.x.x.x) port 8008 (#0)
> OPTIONS /master HTTP/1.1
> User-Agent: curl/7.29.0
> Host: x.x.x.x:8008
> Accept: */*
>
* HTTP 1.0, assume close after body
<HTTP/1.0 200 OK
HTTP/1.0 200 OK
* Closing connection 0
```
If you rewrite `option httpchk OPTIONS /master` to `option httpchk GET /master`, haproxy can work normally, but `Exception happened during processing of request from 172.16.34.243:53240` appears in my backend server log

**Comment by capflam** [comment] 2020-12-04 09:04
@Pkuutn, please see #989. It is a patroni bug: https://github.com/zalando/patroni/issues/1569

**Comment by capflam** [comment] 2020-12-04 10:31
Duplicate of #989

**Closed as completed** 2020-12-04 10:32 UTC
Labels: type: bug, status: invalid
