### ISSUE TITLE
Assertion failure in version 2.6.6

### ISSUE THREAD

**Issue by maksimlikharevau** [haproxy/haproxy#1950] opened 2022-11-29 22:41 UTC
### Detailed Description of the Problem

FATAL: bug condition "task->expire == 0" matched at src/task.c:310
  call trace(11):
  | 0x5573bd56e9d6 [c6 04 25 01 00 00 00 00]: main-0x153a
  | 0x5573bd6c94e7 [e9 5e ff ff ff 44 89 c0]: main+0x1595d7
  | 0x5573bd6caf92 [44 8b 04 24 e9 66 05 00]: listener_accept+0x402/0xebb
  | 0x5573bd710d94 [48 8b 35 25 44 0f 00 64]: fd_update_events+0x1c4/0x2e6
  | 0x5573bd574e44 [83 f8 02 75 8f 64 41 8b]: main+0x4f34
  | 0x5573bd6b2699 [64 41 8b 45 00 48 c1 e0]: run_poll_loop+0xd9/0x3c5
  | 0x5573bd6b2b35 [48 8b 1d 64 f7 14 00 4c]: main+0x142c25
  | 0x7fe17ed46ea7 [64 48 89 04 25 30 06 00]: libpthread:+0x7ea7
  | 0x7fe17e80ba2f [48 89 c7 b8 3c 00 00 00]: libc:clone+0x3f/0x5a
[NOTICE]   (1) : haproxy version is 2.6.6-274d1a4
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (1) : Current worker (8) exited with code 139 (Segmentation fault)
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING]  (1) : All workers exited. Exiting... (139)

### Expected Behavior

no Segmentation fault

### Steps to Reproduce the Behavior

haproxy serving TCP connections, MQTT traffic, 

### What is your configuration?

```haproxy
/usr/local/etc/haproxy/haproxy.cfg
global
  pidfile /var/run/haproxy.pid
  close-spread-time "${CLOSE_SPREAD_TIME}"
  hard-stop-after "${HARD_STOP_AFTER}"
  lua-load /usr/local/etc/haproxy/scripts/custom_actions.lua

  hard-stop-after 130s
  nbthread 2
  spread-checks 3

  log stdout format raw local0 info
  stats socket /var/run/haproxy.sock mode 600 expose-fd listeners level admin
  stats timeout 2m

frontend metrics
  bind *:8080
  mode http
  http-request use-service prometheus-exporter if { path /metrics }
  stats enable
  stats uri /stats
  stats refresh 10s
  option dontlog-normal
  timeout client 60s

/config/haproxy/haproxy-defaults.cfg
global
  maxconn 150000   # maximum per-process number of concurrent connections
  maxconnrate 325  # maximum per-process number of connections per second

# defaults section
defaults
  log global
  option dontlognull
  option dontlog-normal

  timeout connect 5s
  timeout client 300s
  timeout server 300s

  mode tcp
  option tcplog
  balance leastconn

/config/haproxy/haproxy-env.cfg
resolvers dns-resolver
  nameserver kubedns *.*.*.*:53
  accepted_payload_size 8192

/config/haproxy/haproxy-backends.cfg
backend mqtt_01_alpha
  server-template mqtt-alpha 6 "mqtt-alpha-headless.${MQTT_NAMESPACE}.svc.cluster.local:1883" resolvers dns-resolver init-addr none check inter 3s fall 3 rise 2

backend mqtt_02_beta
  server-template mqtt-beta 6 "mqtt-beta-headless.${MQTT_NAMESPACE}.svc.cluster.local:1883" resolvers dns-resolver init-addr none check inter 3s fall 3 rise 2

backend mqtt_03_gamma
  server-template mqtt-gamma 6 "mqtt-gamma-headless.${MQTT_NAMESPACE}.svc.cluster.local:1883" resolvers dns-resolver init-addr none check inter 3s fall 3 rise 2

backend mqtt_04_delta
  server-template mqtt-delta 6 "mqtt-delta-headless.${MQTT_NAMESPACE}.svc.cluster.local:1883" resolvers dns-resolver init-addr none check inter 3s fall 3 rise 2

backend mqtt_05_epsilon
  server-template mqtt-epsilon 6 "mqtt-epsilon-headless.${MQTT_NAMESPACE}.svc.cluster.local:1883" resolvers dns-resolver init-addr none check inter 3s fall 3 rise 2

backend mqtt_06_zeta
  server-template mqtt-zeta 6 "mqtt-zeta-headless.${MQTT_NAMESPACE}.svc.cluster.local:1883" resolvers dns-resolver init-addr none check inter 3s fall 3 rise 2

backend mqtt_07_eta
  server-template mqtt-eta 6 "mqtt-eta-headless.${MQTT_NAMESPACE}.svc.cluster.local:1883" resolvers dns-resolver init-addr none check inter 3s fall 3 rise 2


/config/haproxy/haproxy-cloud.cfg
frontend mqtt
  bind *:1883
  tcp-request inspect-delay 10s
  acl data_in_buffer req.len ge 4

  tcp-request content set-var(txn.client_id) req.payload(0,0),mqtt_field_value(connect,client_identifier) if data_in_buffer
  tcp-request content set-var(txn.mqtt_prefix) str(mqtt)

  use_backend %[lua.shard_selection(txn.client_id)] if { var(txn.client_id) -m len gt 0 }
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.6-274d1a4 2022/09/22 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.6.html
Running on: Linux 5.11.0-1020-aws #21~20.04.2-Ubuntu SMP Fri Oct 1 13:03:59 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -ENGINE +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Support for malloc_trim() is enabled.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
FATAL: bug condition "task->expire == 0" matched at src/task.c:310
  call trace(11):
  | 0x557a3f0419d6 [c6 04 25 01 00 00 00 00]: main-0x153a
  | 0x557a3f19c4e7 [e9 5e ff ff ff 44 89 c0]: main+0x1595d7
  | 0x557a3f19df92 [44 8b 04 24 e9 66 05 00]: listener_accept+0x402/0xebb
  | 0x557a3f1e3d94 [48 8b 35 25 44 0f 00 64]: fd_update_events+0x1c4/0x2e6
  | 0x557a3f047e44 [83 f8 02 75 8f 64 41 8b]: main+0x4f34
  | 0x557a3f185699 [64 41 8b 45 00 48 c1 e0]: run_poll_loop+0xd9/0x3c5
  | 0x557a3f185b35 [48 8b 1d 64 f7 14 00 4c]: main+0x142c25
  | 0x7fe8c85d9ea7 [64 48 89 04 25 30 06 00]: libpthread:+0x7ea7
  | 0x7fe8c809ea2f [48 89 c7 b8 3c 00 00 00]: libc:clone+0x3f/0x5a
[NOTICE]   (1) : haproxy version is 2.6.6-274d1a4
[NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
[ALERT]    (1) : Current worker (7) exited with code 139 (Segmentation fault)
[ALERT]    (1) : exit-on-failure: killing every processes with SIGTERM
[WARNING]  (1) : All workers exited. Exiting... (139)
```

**Comment by Darlelet** [comment] 2022-11-30 07:32
Duplicate of https://github.com/haproxy/haproxy/issues/1930

**Comment by Darlelet** [comment] 2022-11-30 07:40
The fix was already backported to 2.6 branch last week.
It would be nice if you could update from there (git.haproxy.org) while waiting for 2.6.7 release.

**Closed as not planned** 2022-11-30 09:00 UTC
Labels: type: bug, status: duplicate

**Comment by maksimlikharevau** [comment] 2022-11-30 17:39
nice to see it is fixed, when do you expect 2.6.7 ?

**Comment by Darlelet** [comment] 2022-11-30 17:42
Current efforts are aimed at 2.7 release that should land this week.
2.6.7 should follow pretty quickly (in the following weeks)

**Comment by Darlelet** [comment] 2022-12-02 20:52
Spreading the good news: 2.6.7 was released today!

**Comment by TimWolla** [comment] 2022-12-06 08:35
I'm a little late to the party, but for posterity I'd like to note that this is not a regular segmentation fault, but rather an assertion failure (“bug condition …”). I've renamed the issue as such.
