### ISSUE TITLE
lua regtest fail on lua-5.4.3

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1240] opened 2021-05-01 19:31 UTC
Fedora 34 (lua-5.4.2) works (tested on laptop)

Fedora Rawhide (lua-5.4.3) fails

https://gitlab.com/chipitsine/haproxy-ci-playground/-/jobs/1228913534

```
###### Test case: reg-tests/lua/txn_get_priv-thread.vtc ######
## test results in: "/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.401d9780"
---- c0    EXPECT resp.status (500) == "200" failed
###### Test case: reg-tests/lua/txn_get_priv.vtc ######
## test results in: "/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.337f37ea"
---- c0    EXPECT resp.status (500) == "200" failed
make: *** [Makefile:1088: reg-tests] Error 1
Test case: reg-tests/lua/txn_get_priv.vtc
**** dT    0.000
*    top   TEST reg-tests/lua/txn_get_priv.vtc starting
**** top   extmacro def pwd=/builds/chipitsine/haproxy-ci-playground
**** top   extmacro def no-htx=
**** top   extmacro def localhost=127.0.0.1
**** top   extmacro def bad_backend=127.0.0.1:36335
**** top   extmacro def listen_addr=127.0.0.1:0
**** top   extmacro def bad_ip=192.0.2.255
**** top   macro def testdir=/builds/chipitsine/haproxy-ci-playground/reg-tests/lua
**** top   macro def tmpdir=/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.337f37ea
**   top   === varnishtest "Lua: txn:get_priv() scope"
*    top   VTEST Lua: txn:get_priv() scope
**   top   === feature ignore_unknown_macro
**   top   === haproxy h1 -conf {
**** h1    macro def h1_closed_sock=127.0.0.1:33913
**** h1    macro def h1_closed_addr=127.0.0.1
**** h1    macro def h1_closed_port=33913
**** dT    0.004
**** h1    macro def h1_cli_sock=127.0.0.1:34451
**** h1    macro def h1_cli_addr=127.0.0.1
**** h1    macro def h1_cli_port=34451
**** h1    setenv(cli, 4)
**** h1    macro def h1_fe1_sock=127.0.0.1:38731
**** h1    macro def h1_fe1_addr=127.0.0.1
**** h1    macro def h1_fe1_port=38731
**** h1    setenv(fe1, 5)
**   h1    haproxy_start
**** h1    opt_worker 0 opt_daemon 0 opt_check_mode 0 opt_mcli 0
**** h1    argv|exec "/builds/chipitsine/haproxy-ci-playground/haproxy" -d -dM  -f "/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.337f37ea/h1/cfg" 
**** h1    conf|    global
**** h1    conf|\tstats socket "/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.337f37ea/h1/stats.sock" level admin mode 600
**** h1    conf|    stats socket "fd@${cli}" level admin
**** h1    conf|
**** h1    conf|    global
**** h1    conf|        lua-load /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua
**** h1    conf|        lua-load /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv-print_r.lua
**** h1    conf|
**** h1    conf|    frontend fe1
**** h1    conf|        mode http
**** h1    conf|         option http-use-htx
**** h1    conf|        bind "fd@${fe1}"
**** h1    conf|        default_backend b1
**** h1    conf|
**** h1    conf|    frontend fe2
**** h1    conf|        mode http
**** h1    conf|         option http-use-htx
**** h1    conf|        bind ":8443" ssl crt /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/common.pem
**** h1    conf|        stats enable
**** h1    conf|        stats uri /
**** h1    conf|
**** h1    conf|    backend b1
**** h1    conf|        mode http
**** h1    conf|         option http-use-htx
**** h1    conf|        http-request use-service lua.fakeserv
**** h1    XXX 7 @750
**** dT    0.005
***  h1    PID: 7239
**** h1    macro def h1_pid=7239
**** h1    macro def h1_name=/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.337f37ea/h1
**   top   === client c0 -connect ${h1_fe1_sock} {
**   c0    Starting client
**   c0    Waiting for client
**   c0    Started on 127.0.0.1:38731 (1 iterations)
***  c0    Connect to 127.0.0.1:38731
***  c0    connected fd 6 from 127.0.0.1 43252 to 127.0.0.1:38731
**   c0    === txreq -url "/"
**** c0    txreq|GET / HTTP/1.1\r
**** c0    txreq|Host: 127.0.0.1\r
**** c0    txreq|\r
**   c0    === rxresp
**** dT    0.015
***  h1    debug|[WARNING] 120/153119 (7239) : config : missing timeouts for frontend 'fe1'.
***  h1    debug|   | While not properly invalid, you will certainly encounter various problems
***  h1    debug|   | with such a configuration. To fix this, please ensure that all following
***  h1    debug|   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
***  h1    debug|[WARNING] 120/153119 (7239) : config : missing timeouts for frontend 'fe2'.
***  h1    debug|   | While not properly invalid, you will certainly encounter various problems
***  h1    debug|   | with such a configuration. To fix this, please ensure that all following
***  h1    debug|   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
**** dT    0.017
***  h1    debug|Note: setting global.maxconn to 524274.
**** dT    0.018
***  h1    debug|Available polling systems :
***  h1    debug|      epoll : 
***  h1    debug|pref=300, 
***  h1    debug| test result OK
***  h1    debug|
***  h1    debug|       poll : 
***  h1    debug|pref=200, 
***  h1    debug| test result OK
***  h1    debug|
***  h1    debug|     select : 
***  h1    debug|pref=150, 
***  h1    debug| test result FAILED
***  h1    debug|
***  h1    debug|Total: 3 (2 usable), will use epoll.
***  h1    debug|
***  h1    debug|Available filters :
***  h1    debug|\t[SPOE] spoe
***  h1    debug|\t[CACHE] cache
***  h1    debug|\t[FCGI] fcgi-app
***  h1    debug|\t[COMP] compression
***  h1    debug|\t[TRACE] trace
**** dT    0.035
***  h1    debug|Using epoll() as the polling mechanism.
**** dT    0.062
***  h1    debug|00000000:fe1.accept(0005)=000b from [127.0.0.1:43252] ALPN=<none>
***  h1    debug|00000000:fe1.clireq[000b:ffffffff]: GET / HTTP/1.1
***  h1    debug|00000000:fe1.clihdr[000b:ffffffff]: host: 127.0.0.1
**** dT    0.063
***  h1    debug|[info] 120/153119 (7239) : APPLET START
***  h1    debug|[info] 120/153119 (7239) : APPLET GET
***  h1    debug|[info] 120/153119 (7239) : MAKING SOCKET
**** dT    0.065
***  h1    debug|[info] 120/153119 (7239) : SOCKET MADE
***  h1    debug|[info] 120/153119 (7239) : SENDING REQUEST
***  h1    debug|[info] 120/153119 (7239) : 1
***  h1    debug|[NOTICE] 120/153119 (7239) : haproxy version is 2.4-dev18
***  h1    debug|[NOTICE] 120/153119 (7239) : path to executable is /builds/chipitsine/haproxy-ci-playground/haproxy
***  h1    debug|[ALERT] 120/153119 (7239) : Lua applet http '<lua.fakeserv>': [state-id 0] runtime error: /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua:62: Expect a 'string' for the prefix from [C]: in method 'receive', /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua:62: in function line 59 ..., /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua:171: in function line 165.
**** dT    0.066
***  h1    debug|00000000:b1.srvrep[000b:ffffffff]: HTTP/1.1 500 Internal Server Error
***  h1    debug|00000000:b1.srvhdr[000b:ffffffff]: content-length: 97
***  h1    debug|00000000:b1.srvhdr[000b:ffffffff]: cache-control: no-cache
***  h1    debug|00000000:b1.srvhdr[000b:ffffffff]: content-type: text/html
**** c0    rxhdr|HTTP/1.1 500 Internal Server Error\r
**** c0    rxhdr|content-length: 97\r
**** c0    rxhdr|cache-control: no-cache\r
**** c0    rxhdr|content-type: text/html\r
**** c0    rxhdr|\r
**** c0    rxhdrlen = 108
**** c0    http[ 0] |HTTP/1.1
**** c0    http[ 1] |500
**** c0    http[ 2] |Internal Server Error
**** c0    http[ 3] |content-length: 97
**** c0    http[ 4] |cache-control: no-cache
**** c0    http[ 5] |content-type: text/html
**** c0    c-l|<html><body><h1>500 Internal Server Error</h1>
**** c0    c-l|An internal server error occurred.
**** c0    c-l|</body></html>
**** c0    bodylen = 97
**   c0    === expect resp.status == 200
---- c0    EXPECT resp.status (500) == "200" failed
*    top   RESETTING after reg-tests/lua/txn_get_priv.vtc
**   h1    Reset and free h1 haproxy 7239
**   h1    Wait
**   h1    Stop HAproxy pid=7239
**** h1    Kill(2)=0: Success
**** dT    0.067
**** h1    STDOUT EOF
**** dT    0.166
**   h1    WAIT4 pid=7239 status=0x0002 (user 0.037405 sys 0.022649)
*    top   TEST reg-tests/lua/txn_get_priv.vtc FAILED
Test case: reg-tests/lua/txn_get_priv-thread.vtc
**** dT    0.000
*    top   TEST reg-tests/lua/txn_get_priv-thread.vtc starting
**** top   extmacro def pwd=/builds/chipitsine/haproxy-ci-playground
**** top   extmacro def no-htx=
**** top   extmacro def localhost=127.0.0.1
**** top   extmacro def bad_backend=127.0.0.1:36335
**** top   extmacro def listen_addr=127.0.0.1:0
**** top   extmacro def bad_ip=192.0.2.255
**** top   macro def testdir=/builds/chipitsine/haproxy-ci-playground/reg-tests/lua
**** top   macro def tmpdir=/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.401d9780
**   top   === varnishtest "Lua: txn:get_priv() scope"
*    top   VTEST Lua: txn:get_priv() scope
**   top   === feature ignore_unknown_macro
**   top   === haproxy h1 -conf {
**** h1    macro def h1_closed_sock=127.0.0.1:34081
**** h1    macro def h1_closed_addr=127.0.0.1
**** h1    macro def h1_closed_port=34081
**** dT    0.004
**** h1    macro def h1_cli_sock=127.0.0.1:33293
**** h1    macro def h1_cli_addr=127.0.0.1
**** h1    macro def h1_cli_port=33293
**** h1    setenv(cli, 4)
**** h1    macro def h1_fe1_sock=127.0.0.1:34441
**** h1    macro def h1_fe1_addr=127.0.0.1
**** h1    macro def h1_fe1_port=34441
**** h1    setenv(fe1, 5)
**   h1    haproxy_start
**** h1    opt_worker 0 opt_daemon 0 opt_check_mode 0 opt_mcli 0
**** h1    argv|exec "/builds/chipitsine/haproxy-ci-playground/haproxy" -d -dM  -f "/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.401d9780/h1/cfg" 
**** h1    conf|    global
**** h1    conf|\tstats socket "/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.401d9780/h1/stats.sock" level admin mode 600
**** h1    conf|    stats socket "fd@${cli}" level admin
**** h1    conf|
**** h1    conf|    global
**** h1    conf|        lua-load-per-thread /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua
**** h1    conf|        lua-load-per-thread /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv-print_r.lua
**** h1    conf|
**** h1    conf|    frontend fe1
**** h1    conf|        mode http
**** h1    conf|         option http-use-htx
**** h1    conf|        bind "fd@${fe1}"
**** h1    conf|        default_backend b1
**** h1    conf|
**** h1    conf|    frontend fe2
**** h1    conf|        mode http
**** h1    conf|         option http-use-htx
**** h1    conf|        bind ":8443" ssl crt /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/common.pem
**** h1    conf|        stats enable
**** h1    conf|        stats uri /
**** h1    conf|
**** h1    conf|    backend b1
**** h1    conf|        mode http
**** h1    conf|         option http-use-htx
**** h1    conf|        http-request use-service lua.fakeserv
**** h1    XXX 7 @750
***  h1    PID: 7191
**** h1    macro def h1_pid=7191
**** h1    macro def h1_name=/tmp/haregtests-2021-05-01_15-30-33.acgufJ/vtc.5916.401d9780/h1
**   top   === client c0 -repeat 4 -connect ${h1_fe1_sock} {
**   c0    Starting client
**** dT    0.005
**   c0    Waiting for client
**   c0    Started on 127.0.0.1:34441 (4 iterations)
***  c0    Connect to 127.0.0.1:34441
***  c0    connected fd 6 from 127.0.0.1 60204 to 127.0.0.1:34441
**   c0    === txreq -url "/0"
**** c0    txreq|GET /0 HTTP/1.1\r
**** c0    txreq|Host: 127.0.0.1\r
**** c0    txreq|\r
**   c0    === rxresp
**** dT    0.014
***  h1    debug|[WARNING] 120/153118 (7191) : config : missing timeouts for frontend 'fe1'.
***  h1    debug|   | While not properly invalid, you will certainly encounter various problems
***  h1    debug|   | with such a configuration. To fix this, please ensure that all following
***  h1    debug|   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
***  h1    debug|[WARNING] 120/153118 (7191) : config : missing timeouts for frontend 'fe2'.
***  h1    debug|   | While not properly invalid, you will certainly encounter various problems
***  h1    debug|   | with such a configuration. To fix this, please ensure that all following
***  h1    debug|   | timeouts are set to a non-zero value: 'client', 'connect', 'server'.
**** dT    0.016
***  h1    debug|Note: setting global.maxconn to 524274.
***  h1    debug|Available polling systems :
***  h1    debug|      epoll : 
***  h1    debug|pref=300, 
***  h1    debug| test result OK
***  h1    debug|
***  h1    debug|       poll : 
***  h1    debug|pref=200, 
***  h1    debug| test result OK
***  h1    debug|
***  h1    debug|     select : 
***  h1    debug|pref=150, 
***  h1    debug| test result FAILED
***  h1    debug|
***  h1    debug|Total: 3 (2 usable), will use epoll.
***  h1    debug|
***  h1    debug|Available filters :
***  h1    debug|\t[SPOE] spoe
***  h1    debug|\t[CACHE] cache
***  h1    debug|\t[FCGI] fcgi-app
***  h1    debug|\t[COMP] compression
***  h1    debug|\t[TRACE] trace
**** dT    0.032
***  h1    debug|Using epoll() as the polling mechanism.
**** dT    0.060
***  h1    debug|00000000:fe1.accept(0005)=000b from [127.0.0.1:60204] ALPN=<none>
***  h1    debug|00000000:fe1.clireq[000b:ffffffff]: GET /0 HTTP/1.1
***  h1    debug|00000000:fe1.clihdr[000b:ffffffff]: host: 127.0.0.1
**** dT    0.061
***  h1    debug|[info] 120/153118 (7191) : APPLET START
***  h1    debug|[info] 120/153118 (7191) : APPLET GET
***  h1    debug|[info] 120/153118 (7191) : MAKING SOCKET
**** dT    0.063
***  h1    debug|[info] 120/153118 (7191) : SOCKET MADE
***  h1    debug|[info] 120/153118 (7191) : SENDING REQUEST
***  h1    debug|[info] 120/153118 (7191) : 1
***  h1    debug|[NOTICE] 120/153118 (7191) : haproxy version is 2.4-dev18
***  h1    debug|[NOTICE] 120/153118 (7191) : path to executable is /builds/chipitsine/haproxy-ci-playground/haproxy
***  h1    debug|[ALERT] 120/153118 (7191) : Lua applet http '<lua.fakeserv>': [state-id 1] runtime error: /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua:62: Expect a 'string' for the prefix from [C]: in method 'receive', /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua:62: in function line 59 ..., /builds/chipitsine/haproxy-ci-playground/reg-tests/lua/txn_get_priv.lua:171: in function line 165.
***  h1    debug|00000000:b1.srvrep[000b:ffffffff]: HTTP/1.1 500 Internal Server Error
***  h1    debug|00000000:b1.srvhdr[000b:ffffffff]: content-length: 97
***  h1    debug|00000000:b1.srvhdr[000b:ffffffff]: cache-control: no-cache
***  h1    debug|00000000:b1.srvhdr[000b:ffffffff]: content-type: text/html
**** dT    0.064
**** c0    rxhdr|HTTP/1.1 500 Internal Server Error\r
**** c0    rxhdr|content-length: 97\r
**** c0    rxhdr|cache-control: no-cache\r
**** c0    rxhdr|content-type: text/html\r
**** c0    rxhdr|\r
**** c0    rxhdrlen = 108
**** c0    http[ 0] |HTTP/1.1
**** c0    http[ 1] |500
**** c0    http[ 2] |Internal Server Error
**** c0    http[ 3] |content-length: 97
**** c0    http[ 4] |cache-control: no-cache
**** c0    http[ 5] |content-type: text/html
**** c0    c-l|<html><body><h1>500 Internal Server Error</h1>
**** c0    c-l|An internal server error occurred.
**** c0    c-l|</body></html>
**** c0    bodylen = 97
**   c0    === expect resp.status == 200
---- c0    EXPECT resp.status (500) == "200" failed
*    top   RESETTING after reg-tests/lua/txn_get_priv-thread.vtc
**   h1    Reset and free h1 haproxy 7191
**   h1    Wait
**   h1    Stop HAproxy pid=7191
**** h1    Kill(2)=0: Success
**** dT    0.065
**** h1    STDOUT EOF
**** dT    0.164
**   h1    WAIT4 pid=7191 status=0x0002 (user 0.037491 sys 0.020737)
*    top   TEST reg-tests/lua/txn_get_priv-thread.vtc FAILED
* ```

**Comment by a-denoyelle** [comment] 2021-05-03 06:56
I forgot to report it but I confirm the issue on Archlinux as well. The problem is definitely triggered by the upgrade from lua 5.4.2 to 5.4.3.

**Comment by capflam** [comment] 2021-05-03 07:32
It is a change in `LuaL_buffinit()` function. Before the 5.4.3, this function only creates a buffer but nothing is pushed on the top of the stack. In the 5.4.3, a light userdata pointing on the buffer is pushed on the top of the stack. Of course, this changes the index of the top element in the stack. Here is the corresponding commit: https://github.com/lua/lua/commit/cf23a93d

In fact, it seems to be expected to not rely on the top of the stack when buffers are used. From `LuaL_Buffer`:

> During its normal operation, a string buffer uses a variable number of stack slots. So, while using a buffer, you cannot assume that you know where the top of the stack is.

Thus, we must review all the Lua code to be sure to use buffers in the right way.

**Comment by capflam** [comment] 2021-05-03 08:43
It should be fixed now.

**Comment by a-denoyelle** [comment] 2021-05-03 08:51
@capflam I confirm you on Archlinux the regtest is fixed thanks to your commit.

**Comment by chipitsine** [comment] 2021-05-03 09:02
Fedora rawhide is broken on itself.

https://gitlab.com/chipitsine/haproxy-ci-playground/-/jobs/1231069535

closing the issue for now

**Comment by chipitsine** [comment] 2021-05-03 09:03
sorry, did not mention backporting labels

**Closed as completed** 2022-08-25 10:00 UTC
Labels: type: bug, subsystem: lua, status: fixed
