### ISSUE TITLE
Haproxy replies with TCP FIN on HTTP GET

### ISSUE THREAD

**Issue by lukenowak** [haproxy/haproxy#1109] opened 2021-02-09 09:59 UTC
## Detailed description of the problem
(Comes from [the forum](https://discourse.haproxy.org/t/haproxy-replies-with-tcp-fin-on-http-get/6150), but I improved the configuration example)

I am using haproxy (2.0.18, but confirmed with 2.0.19 and 2.0.20).

It works pretty well ~99,995% of time, but sometimes haproxy replies with TCP FIN to proper HTTP GET from a client on a long lasting connection, on which before it responded a lot with proper reply: [see](https://aws1.discourse-cdn.com/business6/uploads/haproxy/original/2X/c/c9953357667620f86e75008bdbcfa46fc5be1b7f.png), ([less edited screenshot](https://aws1.discourse-cdn.com/business6/uploads/haproxy/original/2X/d/d01f9b936feaea5e0b00953d8c1bf424b5b38993.png))

The client here is Apache Traffic Server and Caddy version 1, this happens for both cases.

## Expected behavior

I'd expect haproxy to not send TCP FIN after receiving HTTP GET even for the small amount of cases.

## Steps to reproduce the behavior

1. Setup haproxy as defined
2. Setup some crawling system which constantly does HTTP requests to haproxy
3. After some unpredictable time you'll get TCP FIN after sending HTTP GET

## Do you have any idea what may have caused this?

My specific configuration...

## Do you have an idea how to solve the issue?

I have no solution, workaround is do re-connection from the client, but it can lead to HTTP 5xx in some cases emitted by the clients back to their clients.

## What is your configuration?

Configuration:

```
global
  pidfile haproxy.pid
  master-worker

log log.sck local0
defaults
  log global
  mode http
  option httplog
  timeout queue 60s
  timeout server 600s
  timeout client 600s
  timeout connect 5s
  retries 3

frontend http-backend
  bind <ip>:41080

  acl is_<N> hdr_reg(host) -i ^<N>.example.com($|:.*)
  use_backend <N>-http if is_<N>

frontend https-backend
  bind <ip>:42080

  acl is_<N> hdr_reg(host) -i ^<N>.example.com($|:.*)
  use_backend <N>-https if is_<N>

backend <N>-http
  timeout server 600s
  timeout connect 5s
  retries 3
  server backend ip:v6:port ssl verify none

backend <N>-https
```

The `N` exceeds 3000 (so there are more than 2*3000 backend configurations).

## Output of `haproxy -vv` and `uname -a`
`haproxy -vv`
```
HA-Proxy version 2.0.17 2020/07/31 - https://haproxy.org/
Build options :                             
  TARGET  = linux-glibc
  CPU     = generic        
  CC      = gcc                        
  CFLAGS  = -m64 -march=x86-64 -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-para
meter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overf
low -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_DL=1
                                 
Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPAR
M -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4
+ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS
                                                        
Default settings :                                        
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
                         
Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.1
Built with network namespace support.   
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND                                                             
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")                                   
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

Applies to `uname -a`:
```
Linux xxx 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
Linux xxx 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux
Linux xxx 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
Linux xxx 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
Linux xxx 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux
Linux xxx 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
Linux xxx 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux
Linux xxx 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
Linux xxx 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux
Linux xxx 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
Linux xxx 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

No crash.

## Additional information (if helpful)

It happens on low and high load. I think that load increase does not follow error rate, it seems quite constant per amount of requests (I didn't calculated).

**Comment by wtarreau** [comment] 2021-02-09 14:28
I'm seeing exactly 5.00 seconds between the last response and the FIN, making me think that this is a `timeout http-keep-alive` striking. But you don't have this in your config so it should default to `timeout client` which is much larger. Could you check in other traces if this delay is stable, and if so, if changing any timeout changes the behavior ? Maybe we're having a bug with a timeout that's not properly reset and which still strikes, or maybe the keep-alive timeout is set to 5s by default for a reason I'm ignoring at this point.

**Comment by lukenowak** [comment] 2021-02-10 09:18
I rechecked real configuration and for sure I do not set `http-keep-alive`, and `timeout client` is set to `600s`

> Could you check in other traces if this delay is stable, and if so, if changing any timeout changes the behavior ?

I'll come back with findings, I need some time to gather them.

**Comment by lukenowak** [comment] 2021-02-25 14:02
> Could you check in other traces if this delay is stable

So I was able to gather few issues like this:

 * one around 5 seconds after last correct reply
 * one problem seen in pcap at 12:04:23,722875, last correct reply in the TCP stream was 12:04:23,254164
 * one problem around 5s after last correct 304 reply
 * one problem around 1.5s after last correct 200 reply

> , and if so, if changing any timeout changes the behavior ?

So, seems a bit "stable" - 50% of them. I'll try now to update my system to setup some easy to detect values for those timeouts and I'll observe - despite if this input is enough, I'll stop - it's quite hard to catch the needle in a haystack, and I have troubles to reproduce it easily in the lab (those findings are from real machine, tcpdumps are big beasts there).

**Comment by wtarreau** [comment] 2021-02-26 21:47
By the way, I'm thinking about something. The only 5s timeout I'm seeing is the `connect` timeout in the defaults and in the backend. It could be nice to increase it to an easily recognizable value such a `7s` to see if it has any effect. Maybe in some cases it's armed and not stopped and tears the connection down when it strikes. This should obviously not happen but as you say it's OK 99.995% of the time so I guess it could be a completely overlooked rare corner case.

**Comment by lukenowak** [comment] 2021-03-04 12:31
So I set:
```
timeout connect 7s
```

And I gathered some timings:

- problem 2021-03-02 11:56:08,935309 last good 2021-03-02 11:56:04,460989
- problem 2021-03-02 12:02:14,846110 last good 2021-03-02 12:02:11,202797
- problem 2021-03-02 12:03:10,566840 last good 2021-03-02 12:03:09,524478
- problem 2021-03-02 12:03:32,830380 last good 2021-03-02 12:03:30,565677
- problem 2021-03-02 12:07:23,615056 last good 2021-03-02 12:07:21,341006
- problem 2021-03-02 12:08:15,721020 last good 2021-03-02 12:08:11,959935
- problem 2021-03-02 12:11:19,875803 last good 2021-03-02 12:11:19,197956
- problem 2021-03-02 12:12:29,200725 last good 2021-03-02 12:12:27,616673

Where problem is the time of `HTTP GET` followed by `TCP FIN`, and last good is the time of last good response seen in the TCP stream.

**Comment by capflam** [comment] 2021-03-04 13:02
Is there any specific termination state in the logs for those requests ?

**Comment by lukenowak** [comment] 2021-03-05 09:14
> Is there any specific termination state in the logs for those requests ?

I forgot to copy this information from the [forum thread](https://discourse.haproxy.org/t/haproxy-replies-with-tcp-fin-on-http-get/6150), but there are **no** log entries with disconnection states for those TCP FIN requests.

**Comment by capflam** [comment] 2021-03-05 10:42
Ok, I missed this info reading the thread. So, if there is no log entries for these requests, it may be an abort on the server side before receiving any response. After a successful connection (thus no retries), if a server abort is caught, the connection is closed on the client side without returning any info. It is mandatory to let the client know it may safely retry.

So of course, it is still possible you hit a bug. But if possible, could you get a network capture on both sides (client and server) ? I truly understand it is painful. Another solution may be to enable the L7-retry on empty response using :
```
retry-on conn-failure empty-response
```

**Comment by lukenowak** [comment] 2021-03-30 08:05
> But if possible, could you get a network capture on both sides (client and server) ?

Do you mean server side and client side of haproxy itself? I can do.

> Another solution may be to enable the L7-retry on empty response using :

I'll give a try and provide feedback.

**Comment by lukenowak** [comment] 2021-03-30 08:08
> > Another solution may be to enable the L7-retry on empty response using :
> I'll give a try and provide feedback.

I just checked and `retry-on` is by default `conn-failure` according to the [documentation](https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4-retry-on), and I am keeping this default. Do you want me to force it?

**Comment by wtarreau** [comment] 2021-03-30 08:18
For the network capture, yes, both sides from the haproxy machine would be nice. I think we'll see a FIN from the server at the same time as the GET sent by haproxy, resulting in the loss of the request and a FIN being sent to the client.

Regarding the L7 retry, that's it, it would need to be forced so that haproxy keeps a local copy of the request before reusing an idle connection, and is able to replay it in the rare event that the connection closes just after the response was sent.

**Comment by lukenowak** [comment] 2021-04-02 09:54
> For the network capture, yes, both sides from the haproxy machine would be nice. I think we'll see a FIN from the server at the same time as the GET sent by haproxy, resulting in the loss of the request and a FIN being sent to the client.

I'll work on it (requires a bit of preparation from live system).

> Regarding the L7 retry, that's it, it would need to be forced so that haproxy keeps a local copy of the request before reusing an idle connection, and is able to replay it in the rare event that the connection closes just after the response was sent.

After adding:

```
defaults
  retry-on conn-failure
```

I still get the same issue.

Shall I put it in some other section?

**Comment by wtarreau** [comment] 2021-04-02 09:57
`retry-on conn-failure` is always set by default. Here the issue is not a connection failure (which happens before trying to send the data) but an empty response (a close just after sending the data). You can use `retry-on conn-failure empty-response` for this.

**Comment by lukenowak** [comment] 2021-04-02 10:02
Oh, indeed, of course! I can't imagine how I missed the additional `empty-response` in @capflam post. I'll redo my checks with the parameter.

**Comment by lukenowak** [comment] 2021-04-09 08:54
So after adding:

```
defaults
  log global
  mode http
  option httplog
  timeout queue 60s
  timeout server 600s
  timeout client 600s
  timeout connect 7s
  retries 3
  retry-on conn-failure empty-response
```

I do not observe issues from the client to haproxy anymore.

Can I track somehow such requests retried requests in haproxy log?

**Comment by wtarreau** [comment] 2021-04-09 08:59
Yes, their retry counter will be > 0. It's the 5-number field just before the request, which is followed by a two-number filed such as "3/2/2/2/1 0/0". The retry count is the 5ths field of the first one ("1") in this case. It may be prefixed by a "+" to indicate that a redispatch occurred (choice of another server due to repeated impossibility to contact the first one).

**Comment by lukenowak** [comment] 2021-04-21 09:21
> I do not observe issues from the client to haproxy anymore.

I was too fast with this. I still observe some disconnections to haproxy, so now it's time for me to prepare:

> > But if possible, could you get a network capture on both sides (client and server) ?

> Do you mean server side and client side of haproxy itself? I can do.

I'll come back to you with results.

**Comment by lukenowak** [comment] 2021-04-21 13:48
So. In order to catch traffic from haproxy itself with tshark, I need to generate about 1G pcap file per 1-2 minutes. I have about 2-3 problematic requests per day (I rechecked all logs around, can't find any indication of a problem correlating with time).

I'll try to find the information this way.

Maybe there is something else crazy I could try (like configuration change), which would result with "fixing"/revealing the issue in the haproxy logs, which would then result with narrowing down the problem?

Regarding the `retry-on` - I'd be ok to not retry to backend, but here the problem is that haproxy itself becomes unavailable (so maybe it means that problematic backend will NOT impact the whole process by itself, I assume it was the idea here).

**Comment by ktosiek** [comment] 2021-09-13 15:38
I can see similar behaviour, and I can confirm the backend responds with a FIN. But shouldn't something still get logged?

**Comment by infa-ugunugan** [comment] 2021-11-04 00:50
We are also facing similar issue Haproxy 2.0.17 sending FIN with no response , sometime returns FIN in milliseconds and sometimes in 4 minutes, nothing is logged in access logs, any solution for this ?
![image](https://user-images.githubusercontent.com/32852899/140238822-7e8c0960-7bcb-4c1f-8c6b-b5f78e24b919.png)

**Comment by capflam** [comment] 2021-11-04 04:53
First of all, the 2.0.17 is a bit old. You must update. Note that we'll emit a 2.0.26 very soon. Then could your share you configuration and log messages corresponding to those requests ?

**Comment by infa-ugunugan** [comment] 2021-11-04 05:49
Thanks Capflam, can you confirm if this is fixed in 2.0.26 ? 
BTW, my configuration

 log     global
   mode    http
   option  httplog
   option  dontlognull
   option persist
   option redispatch
   option forwardfor

   option http-keep-alive 
   timeout http-keep-alive 30s

   timeout connect 5s
   timeout check   5s
   timeout client  30s
   timeout server  600s
   timeout queue 60s
   retries 3
   retry-on conn-failure empty-response

 frontend localnodes
    http-response set-header Keep-Alive timeout=29

**Comment by capflam** [comment] 2021-11-04 06:09
The issue was not clearly identified. Thus, I cannot confirm it is fixed. But the 2.0.17 was released over a year ago and is affected by more than 250 known bugs (http://www.haproxy.org/bugs/bugs-2.0.17.html). Before investigating deeper, I prefer to be sure the issue is still there.

Otherwise, do you have log messages for these requests ? And in case the problem persists after the update, is the issue easy to reproduce on your end ?

**Comment by wtarreau** [comment] 2021-11-04 06:10
> Thanks Capflam, can you confirm if this is fixed in 2.0.26 ?

That's not the question. The comment about your outdated version is that you're using a version that contains **259 known bugs** 16 of which were considered **MAJOR**: http://www.haproxy.org/bugs/bugs-2.0.17.html

How do you want anyone to know if one of these could cause what you're observing ? It's important to always apply the known fixes before asking for help on bugs, because very often when there's a bug you're not the only one to see it and it's very likely that if anyone else also faced it, it got already fixed.

Thus it would be much appreciated that you first apply the fixes and test again, if the issue is easy to observe on your side.

Thanks.

**Comment by capflam** [comment] 2021-11-04 06:13
The 2.0.26 will be released on next Monday or Tuesday.

**Comment by ktosiek** [comment] 2021-11-04 22:00
I've prepared a small reproduction for the missing logs, tested on HAProxy version 2.4.7-1ppa1~focal.

This example shows that HAProxy closes the connection without logging that fact for the "test-proxy" frontent - the first /?fin is only logged for "test-responder".
You can see in the curl output that HAProxy has closed a reused client connection ("Connection died, retrying a fresh connect"). But when the same backend-side close happened on a fresh connection HAProxy has returned a 502 Bad Gateway.

haproxy.conf
```
global
  log stdout local0 debug

defaults
  log global
  mode http
  option httplog

listen test-proxy
  bind 0.0.0.0:4100
  server backend 127.0.0.1:4101

listen test-responder
  bind 0.0.0.0:4101

  acl should_fin query -m sub fin
  http-request reject if should_fin
  http-request return content-type text/plain string "Ok" unless should_fin
```

`curl --http1.1 -s -v 127.0.0.1:4100/?{1,2,3,fin} >/dev/null`
```
*   Trying 127.0.0.1:4100...
* Connected to 127.0.0.1 (127.0.0.1) port 4100 (#0)
> GET /?1 HTTP/1.1
> Host: 127.0.0.1:4100
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2
< content-type: text/plain
< 
{ [2 bytes data]
* Connection #0 to host 127.0.0.1 left intact
* Found bundle for host 127.0.0.1: 0x562107fb1180 [serially]
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 4100 (#0)
> GET /?2 HTTP/1.1
> Host: 127.0.0.1:4100
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2
< content-type: text/plain
< 
{ [2 bytes data]
* Connection #0 to host 127.0.0.1 left intact
* Found bundle for host 127.0.0.1: 0x562107fb1180 [serially]
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 4100 (#0)
> GET /?3 HTTP/1.1
> Host: 127.0.0.1:4100
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2
< content-type: text/plain
< 
{ [2 bytes data]
* Connection #0 to host 127.0.0.1 left intact
* Found bundle for host 127.0.0.1: 0x562107fb1180 [serially]
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 4100 (#0)
> GET /?fin HTTP/1.1
> Host: 127.0.0.1:4100
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Connection died, retrying a fresh connect(retry count: 1)
* Closing connection 0
* Issue another request to this URL: 'http://127.0.0.1:4100/?fin'
* Hostname 127.0.0.1 was found in DNS cache
*   Trying 127.0.0.1:4100...
* Connected to 127.0.0.1 (127.0.0.1) port 4100 (#1)
> GET /?fin HTTP/1.1
> Host: 127.0.0.1:4100
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
< content-length: 107
< cache-control: no-cache
< content-type: text/html
< 
{ [107 bytes data]
* Connection #1 to host 127.0.0.1 left intact
```

`haproxy -f haproxy.conf` output:
```
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:47350 [04/Nov/2021:22:47:13.374] test-responder test-responder/<NOSRV> 0/-1/-1/-1/0 200 73 - - LR-- 2/1/0/0/3 0/0 "GET /?1 HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:60268 [04/Nov/2021:22:47:13.374] test-proxy test-proxy/backend 0/0/0/0/0 200 73 - - ---- 2/1/0/0/0 0/0 "GET /?1 HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:47350 [04/Nov/2021:22:47:13.375] test-responder test-responder/<NOSRV> 0/-1/-1/-1/0 200 73 - - LR-- 2/1/0/0/3 0/0 "GET /?2 HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:60268 [04/Nov/2021:22:47:13.375] test-proxy test-proxy/backend 0/0/0/0/0 200 73 - - ---- 2/1/0/0/0 0/0 "GET /?2 HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:47350 [04/Nov/2021:22:47:13.375] test-responder test-responder/<NOSRV> 0/-1/-1/-1/0 200 73 - - LR-- 2/1/0/0/3 0/0 "GET /?3 HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:60268 [04/Nov/2021:22:47:13.375] test-proxy test-proxy/backend 0/0/0/0/0 200 73 - - ---- 2/1/0/0/0 0/0 "GET /?3 HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:47350 [04/Nov/2021:22:47:13.375] test-responder test-responder/<NOSRV> -1/-1/-1/-1/0 -1 0 - - PR-- 2/1/0/0/3 0/0 "GET /?fin HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:47352 [04/Nov/2021:22:47:13.376] test-responder test-responder/<NOSRV> -1/-1/-1/-1/0 -1 0 - - PR-- 2/1/0/0/3 0/0 "GET /?fin HTTP/1.1"
<134>Nov  4 22:47:13 haproxy[439748]: 127.0.0.1:60270 [04/Nov/2021:22:47:13.376] test-proxy test-proxy/backend 0/0/0/-1/0 502 209 - - SH-- 1/1/0/0/0 0/0 "GET /?fin HTTP/1.1"
```

**Comment by capflam** [comment] 2021-11-05 07:23
Here everything works as expected. From `test-proxy` point of view, the first reject is interpreted as a server connection shutdown on a keep-alive connection while waiting for a response. Thus it closes the client connection with no response to let a change to the client to retry. At this stage, no log message is emitted. From the client point of view, you can see that as a connection closed just when the request is sent.  As expected, curl retires. But this time, on the reject, it is a fresh connection. Thus a 502-bad-gateway is returned.

**Comment by ktosiek** [comment] 2021-11-05 08:06
Thank you, I think I'm starting to grasp how it currently works.

What I don't understand is:
1. Why is server connection shutdown translated into a client connection shutdown? It seems to me the client->proxy and proxy->server connections are independent. Is that to avoid buffering the request?
2. Why is nothing logged? There was a request sent to the backend server, and there was a response (or at least an explicit lack of response) sent to the client. This is the scary part for me, as I can't see how often this situation shows up in my infrastructure.

**Comment by wtarreau** [comment] 2021-11-05 08:12
1) it's because an intermediary must not retry connections by default. So we're only aggregating retryable requests over existing connections by default, because a client must always be able to retry if a second request on an existing connection is aborted by a close (e.g. server timeout). As such, the best we can do without taking risks on the client's behalf is to simply close to the client without sending anything so that the client concludes its reused connection was closed and can safely decide to replay its request. Note that if the client had talked to the server directly, exactly the same would have happened. It is possible to hide this from the client by using l7 retries, but you need to know if the application is safe for this, and it consumes a bit of RAM and CPU (duplication of a request before sending it).

2) nothing is logged because nothing was performed. That's on purpose. In the past we used to log them but that was very confusing since there was no processing nor an status code sent. Think about those doing accounting based on such logs, or who would use such requests to detect some bad activity for example. I think we have a counter for this though I don't have it in mind right now, I can have a look.

**Comment by infa-ugunugan** [comment] 2021-11-08 16:04
Seen same issue with version 2.0.25.

**Comment by wtarreau** [comment] 2021-11-08 16:21
@infa-ugunugan as mentioned above in the analysis, none of this is abnormal and this is quite expected.

**Comment by capflam** [comment] 2021-11-09 10:07
In addition, on your screenshot, there is 30s between the last request and its predecessor. With a `http-keep-alive` timeout set to 30s, it is most probably a timing issue. If there is no log message it means it is a keep-alive connection abort. On the client side or the server side. But in both cases, nothing is returned and the client is required to retry.

**Comment by capflam** [comment] 2021-11-26 08:45
what is the status of this issue ? can we close it or there is still something strange requiring our expertise ?

**Closed as completed** 2021-12-02 08:52 UTC
Labels: type: bug, status: feedback required

**Comment by ivpr** [comment] 2022-07-21 09:37
> 2. nothing is logged because nothing was performed. That's on purpose. In the past we used to log them but that was very confusing since there was no processing nor an status code sent. Think about those doing accounting based on such logs, or who would use such requests to detect some bad activity for example. I think we have a counter for this though I don't have it in mind right now, I can have a look.

@wtarreau Would you be able to help with the counter that get's increased in this case? 
We are observing this issue when connection is reused with backend server and it sends a TCP FIN during the request to haproxy and haproxy sends FIN to the client. 
This issue is getting highlighted in our case since our client is envoy(sidecar) and envoy converts these upsream connection terminations to a 503 for the client application container. We are observing that the [intermittent 503s reported by envoy](https://github.com/envoyproxy/envoy/issues/14981) are because of this in our case. 
When this happens, even though client sees it as 503, there is no trace of the request in haproxy logs. `srv_abrt` stats for haproxy are also not increased. I see the counter only increased when backend server sends a TCP RST during request but not for TCP FIN. 
It would be really great if there is a counter in haproxy for this

**Comment by wtarreau** [comment] 2022-07-22 07:48
I would be quite surprised that envoy doesn't properly handle persistent HTTP connections, maybe you need to tweak its configuration. There's indeed no trace of the request in the logs because in the end, the request was not processed and the client will immediately retry it according to the standard way to deal with persistent connections, so we find it's better not to confuse users by letting them imagine there were errors or that requests were processed. Arguably we could have an "ignored" status that's neither a success nor failure, but I'm not sure how to best report this without confusing log processing tools.

However I agree that we could have a counter for this, indeed.

For your case, if you can't find how to configure envoy to properly support persistent connections, one thing you can do is to enable layer-7 retries in haproxy with `retry-on conn-failure empty-response`. In this case it will make a copy of the request before transfering it and will reconnect and send it again if the server closes before responding. It uses slightly more RAM and a little bit of extra CPU due to the memory copy, but could help you work around this problem.

**Comment by ivpr** [comment] 2022-10-27 08:00
@wtarreau Thank you for your reply. Apologies for the delay in getting back. Can we enable retries(`retry-on conn-failure empty-response`) in haproxy without any other implications? Is there a possibility that backend service could be getting the request multiple times in which case it needs to idempotent?

To give more context, below is our setup. We are providing a platform to offer Load Balancer as a Service using haproxy.
![haproxy-1109](https://user-images.githubusercontent.com/14174960/198213801-7609fefc-1682-46d0-bd28-c6d06ce739e8.png)
1. Client makes a call without using any connection pool. Each request is using a separate TCP connection
2. Envoy while making a connection to haproxy uses the [connection pool](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/connection_pooling#http-1-1) and re-uses the conections
3. haproxy in turn uses a connection pool while calling the backend application

If the connection on the backend app is terminated for any reason during the middle of the request handling, we are observing no trace in haproxy for the request as previously mentioned. Haproxy is closing the connection with envoy by sending TCP FIN. Envoy is responding to the client with 503 and UC([Upstream connection termination](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators))

We can technically configure retry on reset in envoy or retry in haproxy. But since we are providing a platform, we can't add this configuration by default since service may not be handling the requests in an idempotent way

On the observability side, in this case client is seeing the 503 errors on their side while there are no errors seen by the service in their haproxy metrics which makes it confusing. Shall I create a new issue for adding a counter metric to capture the connection terminations?

**Comment by git001** [comment] 2022-10-27 13:13
@ivpr what haproxy version do you use now?

**Comment by ivpr** [comment] 2022-10-27 13:17
@git001 I've tested this with 2.4.18

**Comment by ivpr** [comment] 2022-11-03 09:23
@wtarreau Any update on this? Shall I go ahead and create a new issue for this?
