### ISSUE TITLE
Backport "BUG/MEDIUM: ssl: Verify error codes can exceed 63" to HAProxy LTS 2.6

### ISSUE THREAD

**Issue by maxmoehl** [haproxy/haproxy#2003] opened 2023-01-17 12:39 UTC
We recently ran into an issue where HAProxy received openssl error code 68 but reported it as 63 due to the missing space in the variable (which caused a lot of confusion on our end). We found the fix in 2.7 and would like to request a backport to the current LTS version of HAProxy 2.6 (as it is also mentioned in the commit message).

Thanks!

**Comment by maxmoehl** [comment] 2023-01-17 13:08
ping @wlallemand @rlebreton

**Comment by wlallemand** [comment] 2023-01-17 14:13
I marked it to wait before backporting it, because it could introduce some regression, I backported both 9b25982716f0416c28f8fc894c58eb40885cf9e5 and e239e4938d89956e7820be4a0f26e782a86bcf6d to the 2.6 branch so the fixes will be in the next 2.6 release!

**Closed as completed by wlallemand** 2023-01-17 14:13 UTC
Labels: status: fixed
