### ISSUE TITLE
Random routing suspected

### ISSUE THREAD

**Issue by LM1LC3N7** [haproxy/haproxy#594] opened 2020-04-21 15:22 UTC
## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.0.14 2020/04/02 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_EPOLL=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_THREAD=1 USE_PTHREAD_PSHARED=1 USE_REGPARM=1 USE_TPROXY=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_ZLIB=1USE_CPU_AFFINITY=1 USE_TFO=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD +PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

# uname -a
Linux HAP-SRV-001-B 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

HAProxy is running in transparent mode and in HA using `keepalived`.

@ (internet)  <-->  Firewall  <-->  VIP (virtual IP)  <-->  Active HAProxy (transparent)  <-->  Web apps

```
# Global options
global
  # Makes the process fork into background
  daemon
  # This mode  willlaunch a "master" which will monitor the "workers". Using
  # this mode, you can reload HAProxy directly by sending a SIGUSR2 signal to
  # the master.
  master-worker
  maxconn                         60000
  log                             127.0.0.1 local0
  log-tag                         "HAP-SRV-001-B"
  max-spread-checks               2
  user                            root # user "haproxy" cannot run transparent
  group                           root # user "haproxy" cannot run transparent
  chroot                          "/usr/sbin"
  # Node name (in case of HA)
  node                            "HAP-SRV-001-B"
  description                     "HAProxy and Transparent Reverse-Proxy"
  # Number of daemon process
  nbproc                          4
  # One thread on each CPU
  cpu-map                         1 0
  cpu-map                         2 1
  cpu-map                         3 2
  cpu-map                         4 3
  # Maximum CPU usage
  # Setting a lower value will prevent the compression work from slowing the whole
  # process down and from introducing high latencies
  maxcompcpuusage                 90
  # ENV variables
  setenv FRONTEND_SSL_PORT 443
  setenv EMAIL_TO "xx@xxx.xx"
  setenv EMAIL_FROM "HAP-SRV-001-B@xxx.xx"
  # Stats socket tune
  stats timeout 10s
  stats maxconn 5

# Defaults options
defaults
  log                             global
  option                          dontlognull
  option                          tcplog
  mode                            tcp
  timeout connect                 5s
  timeout client                  20s
  timeout server                  20s

  email-alert mailers SMTP-ALERTS
  email-alert from "${EMAIL_FROM}"
  email-alert to "${EMAIL_TO}"


frontend FRONTEND-SSL
  bind *:${FRONTEND_SSL_PORT} transparent
  tcp-request inspect-delay 5s
  tcp-request content accept if { req_ssl_hello_type 1 }
  use_backend APP-001 if { req_ssl_sni -i sub.domain.tld }
  # [...] and more "use-backend", all identical


# Backend for APP-001
backend APP-001
  source * usesrc clientip
  server APP-001 sub.domain.tld:443 check inter 10s fastinter 2s downinter 2s rise 2 fall 3

  # [...] and more backends, all identical



# Listen for <IP>:9000/stats to access to the HA Proxy stats page
listen stats
  bind *:9000 # DEFAULT: 9000
  mode http
  # Enable stats page
  stats enable
  # Title text for popup window
  stats realm "HAProxy Statistics"
  # Hide HAProxy version
  #stats hide-version
  # Stats URI
  stats uri /stats
  stats show-desc
  stats show-node
  stats show-legends
  stats refresh 5

  # Auth users
  acl auth-admin http_auth_group(basic-auth-list) AdminGroup
  # Auth users from viewer group
  acl auth-viewer http_auth_group(basic-auth-list) ViewerGroup
  http-request auth unless auth-admin OR auth-viewer

  # Access admin options only for users from admin group
  # WARNING: limited to process assigned to the current request (/stats)
  stats admin if auth-admin

# Send emails alerts when the state changes
mailers SMTP-ALERTS
  mailer SMTP-1 mx.domain.tld:25 # An email will be sent to all available smtp relay


# It is possible to control access to frontend/backend/listen sections or to
# http stats by allowing only authenticated and authorized users. To do this,
# it is required to create at least one userlist and to define users.
userlist basic-auth-list
  # Define groups. Admin will have some action possible on servers
  # Multiple users : group <GROUP NAME> users <USER1>,<USER2>,<USER3>
  group AdminGroup users yyy,zzz
  group ViewerGroup users

  # Define users
  # Generate a SHA512 Hash from a password using "/sbin/grub-crypt --sha-512" on bash
  # Or using "expect" package (centos 7) and: python -c 'import crypt; print(crypt.crypt("Password01", crypt.mksalt(crypt.METHOD_SHA512)))'
  user yyy password OnzmYaohWPr058Xr0QGWkyHbH2cImQuWulcdbSAeY89sCwuORlV3GIC1lLRPOKjHKo9v5oyC5uiZ2lAPlTgbC1

  user zzz password OnzmYaohWPr058Xr0QGWkyHbH2cImQuWulcdbSAeY89sCwuORlV3GIC1lLRPOKjHKo9v5oyC5uiZ2lAPlTgbC1

  # Or insecure password
  # EXEMPLE: user <NAME> insecure-password <PASSWORD>
  #user test insecure-password test
```

#### HAProxy is running in transparent reverse proxy 

**Kernel config**

`/etc/sysctl.d/90-disable-rp_filter.conf`:

```
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.default.rp_filter=0
net.ipv4.conf.lo.rp_filter=0
```

`/usr/lib/sysctl.d/50-default.conf`:

```
# Enable Forwarding
net.ipv4.ip_forward = 1

# Allow the use of IP_TRANSPARENT to bind to non-local addresses
net.ipv4.ip_nonlocal_bind = 1
```

**iptable config**

```
systemctl mask firewalld && systemctl stop firewalld && systemctl disable firewalld
yum install -y iptables iptables-services
systemctl enable iptables && systemctl start iptables
systemctl enable ip6tables && systemctl start ip6tables
```

```
#!/bin/sh
iptables -F
iptables -X
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -t nat -F
iptables -t nat -X
iptables -t nat -P PREROUTING ACCEPT
iptables -t nat -P POSTROUTING ACCEPT
iptables -t nat -P OUTPUT ACCEPT
iptables -t mangle -F
iptables -t mangle -X
iptables -t mangle -P PREROUTING ACCEPT
iptables -t mangle -P INPUT ACCEPT
iptables -t mangle -P OUTPUT ACCEPT
iptables -t mangle -P FORWARD ACCEPT
iptables -t mangle -P POSTROUTING ACCEPT
iptables -t mangle -N DIVERT
iptables -t mangle -A PREROUTING -p tcp -m socket -j DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -j ACCEPT
```

**Routes**

`/etc/sysconfig/network-scripts/route-lo`:

```
flush table 100
local 0.0.0.0/0 dev lo table 100
```

`/etc/sysconfig/network-scripts/rule-lo`:

```
fwmark 1 lookup 100
```

## Steps to reproduce the behavior

1. Multiple VMs are created, hosting a web server. All VMs are containing the same web server, sometimes in different version (during updates that can take up to 1 month). Each VM is dedicated to one customer and has one dedicated URL (only the subdomain is changed).
2. On the client side, open a web browser, access to web 1 and login. Web 1 is running version 1.
3. Open another tab, access to web 2 and login. Web 2 is running version 2.
4. Now web 1 has closed my user session (here, I suspect a HAProxy error).
5. I log again on web 1
6. Back to web 2, it detect another web version. It ask me to reload: now version 1 is loaded! (I suspect again an HAProxy error)

## Actual behavior

It seems that some packets are sent to another backend server, or maybe to multiple one.

## Expected behavior

Be able to use web 1 in version 1 and web 2 in version 2 on the same web browser.

## Do you have any idea what may have caused this?
It may be related to https://github.com/haproxy/haproxy/issues/19.
I already worked with the developer team of the application, they ran tests and tells me that it should be the HAProxy.

## Do you have an idea how to solve the issue?
Not really, maybe you can indicate me some steps to find out if it is HAProxy or if not.
I would like to be sure at 100% if Haproxy is involved or not.

Also, if my configuration can be improved, please tell me :-)

**Comment by lukastribus** [comment] 2020-04-21 15:56
In your explanation, when you say "web 1" and "web 2", those would be different backends? Like "web 1" is a backend, and "web 2" is another backend, right?

I'd guess that the certificate on those backend servers is the same or overlapping, and this is causing 
browsers to reuse the wrong connection, because the SNI based routing by design can only consider the SNI value in the first packet and is not aware of any further changes in the requests by the browser (because that is encrypted).

So if you want to continue to use SNI based routing, you need to make sure that the certificates on the servers are not overlapping.

**Comment by lukastribus** [comment] 2020-04-21 16:06
In your explanation, when you say "web 1" and "web 2", those would be different backends? Like "web 1" is a backend, and "web 2" is another backend, right?

I'd guess that the certificate on those backend servers is the same or overlapping, and this is causing 
browsers to reuse the wrong connection, because the SNI based routing by design can only consider the SNI value in the first packet and is not aware of any further changes in the requests by the browser (because that is encrypted).

So if you want to continue to use SNI based routing, you need to make sure that the certificates on the servers are not overlapping.

**Comment by LM1LC3N7** [comment] 2020-04-21 16:28
I tries to edit my first message, but GitHub is not working well.
Here what I tries to add.

I think it is HAProxy because of my last test:

1. Open both web 1 and web 2 nginx access logs
2. Open a new tab and log in into web 1
3. Logs are OK.
4. Open another tab and load the login page for web 2
5. Web 2 access logs are empty. But **web 1 access logs shows the request**!
They indicate that the login page was called with web 2 as referer. So it exist a referer even if I opened another tab to load the other login page.


> In your explanation, when you say "web 1" and "web 2", those would be different backends? Like "web 1" is a backend, and "web 2" is another backend, right?

Yes, web 1 and web 2 are different VMs.

> I'd guess that the certificate on those backend servers is the same or overlapping, and this is causing browsers to reuse the wrong connection, because the SNI based routing by design can only consider the SNI value in the first packet and is not aware of any further changes in the requests by the browser (because that is encrypted).

I think that this is possible!
Each backend is using a wildcard certificate.

Is there an alternative to configure HAProxy to work as reverse proxy and in TCP mode?
Or I have to generate a unique certificate per backend?

**Comment by TimWolla** [comment] 2020-04-21 18:36
> I think that this is possible!

You should be able to find out by checking the client port within HAProxy logs. If both requests share the same port then you're only “seeing” the SNI for the first request.

> Is there an alternative to configure HAProxy to work as reverse proxy and in TCP mode?

You would need to send a `421 Misdirected Request` in the backend if the `Host` header is not the expected value. This should force the browser to create a new connection.

**Comment by lukastribus** [comment] 2020-04-21 19:20
I'm not a big fan of the `421 Misdirected Request` response, because things have already gone wrong at that point - data has already been sent to the wrong place - sending the data to the correct place requires additional round trips and we you actually need to implement this 421 response on all your backends.

I find it simpler to just remove overlapping certificates.

**Comment by TimWolla** [comment] 2020-04-21 22:26
> I find it simpler to just remove overlapping certificates.

Sure. But Louis specifically asked for an alternative to using disjoint certificates.

**Comment by LM1LC3N7** [comment] 2020-04-22 08:48
Thanks a lot guys, it been a long time I was wondering how to solve this.
I am generating new CSR on each backend servers in order to have SNI matching to certificates.

It will be much easier and clean as I understand!

**Comment by LM1LC3N7** [comment] 2020-04-22 16:13
We have changed all certificates, but they all are (again) wilcard certificates with a SAN field corresponding to the FQDN used.
As you can suspect, this has not solve the problem.

Two questions:
1. Is there a way to use HAProxy at L7 (application mode and not TCP mode) with one wilcard certificate for HA, and keep it transparent?
2. If not, how to implement a 421 code?

Thanks again for your help!

**Comment by lukastribus** [comment] 2020-04-22 21:38
You can enable TLS termination at haproxy (installing the certificate there, instead of your backend servers). Then haproxy can look at the host header, instead of the SNI value and can make correct routing decisions for each transaction.

But that's no longer "transparent" of course.


> If not, how to implement a 421 code?

On each backend application, implement an check which return this error code when a host header for a different server is detected.


I'm closing this, as it is clearly a support issue. Please use mailing list/discourse for follow up questions.

**Closed as completed by lukastribus** 2020-04-22 21:38 UTC
Labels: status: invalid
