### ISSUE TITLE
maybe bug: when backend hosts dont resolve, they are marked as MAINT and not as 'not checked'

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxy/haproxy#791] opened 2020-08-02 13:15 UTC
I switched to 2.2, it could be this is not an issue with 2.0, however I am still on a test environment, so I do not really use this very often.

What I noticed is that my backend servers were marked as being MAINT, and I was trying to figure out why this was, even check status headers with curl. Then I noticed that no tcp packets were send to the backend servers, turned out I did not configure dns correctly. 

I would say this brown/MAINT is not a good representation of reality, this should be grey/not checked.

bad:
```
backend exchange_owa
  mode http
  balance roundrobin
  option log-health-checks
  option httpchk GET /owa/healthcheck.htm
  #http-check expect status 440
  #option tcp-check
  #default-server check
  default-server check
  server mail01 mail01.local:443 ssl verify required
  server mail02 mail02.local:443 ssl verify required
```

good:
```
backend exchange_owa
  mode http
  balance roundrobin
  option log-health-checks
  option httpchk GET /owa/healthcheck.htm
  #http-check expect status 440
  #option tcp-check
  #default-server check
  default-server check resolvers dnssvrs1
  server mail01 mail01.local:443 ssl verify required
  server mail02 mail02.local:443 ssl verify required
```

**Comment by jmagnin** [comment] 2020-08-03 14:12
Hi,

This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

If you believe you found a bug, please file a bug report using the template so you can provide all the information required to assess the issue.

If you need support, use the forum or the mailing list rather than opening a bug or feature request.

The forum is at: https://discourse.haproxy.org/

The mailing list (no need to subscribe) is: haproxy@formilux.org
Subscribe to the list: haproxy+subscribe@formilux.org
Unsubscribe from the list: haproxy+unsubscribe@formilux.org

**Comment by wtarreau** [comment] 2020-08-07 11:55
Is this still relevant since bug 793 mentioned this one and was closed ?

**Comment by capflam** [comment] 2020-08-07 13:39
I also think we can close this issue. First of all, it is not really clear if it is a bug or a question. There is no required information for a bug report. And, if the server address is not resolved, at startup, HAProxy failed to start, at runtime the server is marked as MAINT as documented in the management guide:

> SRV_ADMF_RMAINT
>       The server is in maintenance because of an IP address resolution failure.

Thus, I'm tempted to add "works as designed" status.

**Comment by jmagnin** [comment] 2020-08-12 07:43
I'm closing this one, feel free to re-open it if needed, but if you do please provide the information asked for a bug report.

**Closed as completed by jmagnin** 2020-08-12 07:43 UTC
Labels: status: works as designed
