### ISSUE TITLE
HAProxy 2.3.6 backend server list frequently in MAINT status when SRV records are in use

### ISSUE THREAD

**Issue by romeg** [haproxy/haproxy#1180] opened 2021-03-11 20:00 UTC
## Detailed description of the problem
After upgrade to 2.3.6 version I observe strange behavior of stats page indicating MAINT status  _too frequently_ for my back-ends, logs were full of messages that the backends are flapping. All the flapping back-ends were configured via server template and queried from Consul via SRV record. Other back-ends (static hostname + port combination) were not affected this issue.
Observed status changes:
UP -> SOCKERR -> MAINT -> UP every several seconds. 

After playing around DNS resolver timeout settings I found out that the SOCKERR -> MAINT error happens every `obsolete` timeout period. 

## Expected behavior

The backend are not flapping due to DNS resolution.

## Steps to reproduce the behavior

1. Configure resolver to use Consul DNS endpoint
2. Add server-template with SRV record for service registered in Consul
3. Observe.

## Do you have any idea what may have caused this?

HAProxy 2.3.5 working well in Consul + HAProxy combo. It's looks like several bugfixes in resolver introduced in 2.3.6 version causing this regression. 

## Do you have an idea how to solve the issue?
I tried to increase timeout valid > timeout obsolete - but it doesn't help

## What is your configuration?

```
global
        log 127.0.0.1:2000 len 4096 format rfc5424 local2
        log-send-hostname
        maxconn 200000
        user haproxy
        group haproxy
        daemon
	stats socket /var/run/haproxy.socket mode 0600 level admin
	tune.ssl.default-dh-param 2048
	tune.maxrewrite 1024
        maxsslrate 3500
        spread-checks 4
        nbthread 8

        ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS:!3DES

        ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS:!3DES

        ssl-default-bind-options no-sslv3 no-tls-tickets no-tlsv10 no-tlsv11

        ssl-default-server-options no-sslv3 no-tls-tickets no-tlsv10 no-tlsv11


resolvers local
        nameserver consul 127.0.0.1:8600
        accepted_payload_size 8192

defaults
        log global
        mode http

	option httplog
	option http-server-close
	option abortonclose
	option http-pretend-keepalive
	option redispatch

	option forwardfor except 127.0.0.0/8
        retries 3
        balance leastconn
        log-format "%ci:%cp [%t] %ft %sslv %b/%s %Tq/%Tw/%Tc/%Tr/%Tt/%TR/%Ta %ST %B %U %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs [%HP] %HV %{+Q}r"


	timeout connect 2s
	timeout http-request 201s
	timeout http-keep-alive 30s
	timeout client 200s
	timeout server 10s
	timeout queue 60s
	timeout check 2s

        errorfile 408 /dev/null
        errorfile 500 /etc/haproxy/errors/500-empty.http
        errorfile 502 /etc/haproxy/errors/500-empty.http
        errorfile 503 /etc/haproxy/errors/500-empty.http
        errorfile 504 /etc/haproxy/errors/500-empty.http


frontend stats
	option http-use-htx
	http-request use-service prometheus-exporter if { path /metrics }
	bind :8003
	stats uri /blabla
        stats refresh 20
        stats show-legends
        stats http-request allow if { src 127.0.0.1/8 }
        stats http-request deny

frontend https_proxy
	bind _:443 ssl crt /etc/ssl/
	maxconn 100000
	use_backend https-fast

frontend main
	option forwardfor except 127.0.0.0/8
	maxconn 50000
	bind _:80
        bind 127.1.0.243:80
        bind 127.1.0.243:81 accept-proxy name https_wrap
        errorfile 403 /etc/haproxy/errors/403.json
        errorfile 503 /etc/haproxy/errors/503.json
        errorfile 504 /etc/haproxy/errors/504.json
        capture request header origin len 128
        capture request header Host len 30
        capture request header Referer len 40

        use_backend consul-backend 

backend https-fast
        balance roundrobin
	timeout server 300s
        server http 127.1.0.243:81 send-proxy-v2

backend consul-backend
	http-check disable-on-404
	default-server inter 1000 fastinter 200 downinter 200 rise 2 fall 2 maxconn 30 resolve-opts allow-dup-ip
	server-template consul-backend-a 8 consul-backend-a._tcp.service.consul:8001 check resolvers local
        server-template consul-backend-b 8 consul-backend-b._tcp.service.consul:8002 check resolvers local
```

## Output of `haproxy -vv` and `uname -a`

```
uname -a
Linux nje03 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
haproxy -vv
HA-Proxy version 2.3.6-1ppa1~focal 2021/03/04 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.6.html
Running on: Linux 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2I2g5n/haproxy-2.3.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=48).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with the Prometheus exporter as a service
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

## Additional information (if helpful)

I suppose it might be due to the fact that Consul trying to randomize the order of backends within the SRV record.

**Comment by lukastribus** [comment] 2021-03-11 20:14
This is a duplicate of #1160

**Closed as completed by lukastribus** 2021-03-11 20:14 UTC
Labels: type: bug, status: duplicate
