### ISSUE TITLE
High CPU usage after few hours of normal work

### ISSUE THREAD

**Issue by vmihailenco** [haproxy/haproxy#399] opened 2019-12-05 14:42 UTC
Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.1.0-1ppa1~bionic 2019/11/28 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.0.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-lODsWl/haproxy-2.1.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
```

```
Linux 4.15.0-1056-aws #58-Ubuntu SMP Tue Nov 26 15:14:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## Config

```
peers req_rate_global
    # ~10 peers here

global
    daemon

    log /dev/log len 2048 local0
    log /dev/log len 2048 local1 notice

    # Tune request URI log in the logs. Default is 1024
    # http://cbonte.github.io/haproxy-dconv/2.0/configuration.html#3.2-tune.http.logurilen
    tune.http.logurilen 2048

    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    maxconn 32000

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL).
    tune.ssl.default-dh-param 2048
    ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

defaults
    log	global
    option httplog
    option dontlognull
    option log-separate-errors

    mode http
    http-reuse safe
    option redispatch
    maxconn 32000

    timeout connect 5s
    timeout client 10s
    timeout server 20s
    timeout http-request 10s
    timeout http-keep-alive 30s

    errorfile 500 /etc/haproxy/errors/50x.http
    errorfile 502 /etc/haproxy/errors/50x.http
    errorfile 503 /etc/haproxy/errors/50x.http
    errorfile 504 /etc/haproxy/errors/50x.http
```

## Actual behavior

Haproxy works fine (CPU usage is around 80%) for several hours but then CPU usage jumps to 300% (basically all available CPU). Haproxy response time seems to be unaffected. Restarting haproxy helps for several hours - then the problem comes back.

![Selection_010](https://user-images.githubusercontent.com/290976/70245395-a9c80e80-177e-11ea-8565-87e5f535c07c.png)

## Do you have an idea how to solve the issue?

- [socat interval 10](https://gist.github.com/vmihailenco/933f258fdc641955a524d6995d8b29c9)
- [socat interval 1](https://gist.github.com/vmihailenco/ee187728e62f9ced637a6872b8bad0d8)
- [strace](https://gist.github.com/vmihailenco/6872c230e55905cdda1137d9563ba813)

**Comment by wtarreau** [comment] 2019-12-05 14:55
This one is totally new and unknown! There's some outgoing readiness on fd 27 and nothing to handle it. It might be related to a connection attempt maybe. You could possibly find more about this fd using "show fd 27" on the CLI. I'm interested in knowing whether it's still attached to a connection or anything else.

**Comment by vmihailenco** [comment] 2019-12-05 15:11
I've just restarted that instance :( I guess fd=27 comes from strace - here is another [one](https://gist.github.com/vmihailenco/7742de71bd84da0507b4fe29ec7aaf79). Which fd should I check? In case it is 26:

```
echo 'show fd 26' | sudo socat /run/haproxy/admin.sock stdio
     26 : st=0x21(R:rA W:Ra) ev=0x04(heOpi) [lc] tmask=0xffffffffffffffff umask=0xffffffffffffffff owner=0x55a4f665abe0 iocb=0x55a4f41513e0(dgram_fd_handler)
```

PS [show fd](https://gist.github.com/vmihailenco/e35e1ac127cebd017b0fa1f6520c2040)

**Comment by wtarreau** [comment] 2019-12-05 16:21
Yep good catch it was 26. I'm focusing on the one appearing alone with EPOLLOUT in strace and for which nothing is done at all till the next epollwait().

I'm seeing that it's dgram_fd_handler() that's supposed to deal with this. Do you have DNS resolvers enabled somewhere in your configuration ?

**Comment by wtarreau** [comment] 2019-12-05 17:40
So I'm still not convinced the threads are handled correctly there. If this happens often enough you can try with this patch, it will force DNS resolutions to be always handled by the first thread (which is really not a problem). If this alone is enough to fix the issue it will further confirm a threading issue. Still it's strange that the fd is not stopped when the function is woken up.

```
diff --git a/src/dns.c b/src/dns.c
index c52f1cabef..78ddf57471 100644
--- a/src/dns.c
+++ b/src/dns.c
@@ -204,7 +204,7 @@ static int dns_connect_namesaver(struct dns_nameserver *ns)
 
        /* Add the fd in the fd list and update its parameters */
        dgram->t.sock.fd = fd;
-       fd_insert(fd, dgram, dgram_fd_handler, MAX_THREADS_MASK);
+       fd_insert(fd, dgram, dgram_fd_handler, 1);
        fd_want_recv(fd);
        return 0;
 }
@@ -1947,7 +1947,7 @@ static int dns_finalize_config(void)
                }
 
                /* Create the task associated to the resolvers section */
-               if ((t = task_new(MAX_THREADS_MASK)) == NULL) {
+               if ((t = task_new(1)) == NULL) {
                        ha_alert("config : resolvers '%s' : out of memory.\n", resolvers->id);
                        err_code |= (ERR_ALERT|ERR_ABORT);
                        goto err;
```

**Comment by vmihailenco** [comment] 2019-12-06 07:36
>Do you have DNS resolvers enabled somewhere in your configuration ?

Yes, one backend that receives less than 1% of the traffic has EC2 DNS resolvers

```
resolvers dns_ec2
    nameserver public0 10.1.0.2:53
```

>try with this patch

That patch does not apply cleanly on 2.1 master or v2.1.0 tag. In the end I've used v2.1.0 and manually applied changes you suggested. Let me know if I should try v2.2...


```
diff --git a/src/dns.c b/src/dns.c
index 6e726bf96..69105d29f 100644
--- a/src/dns.c
+++ b/src/dns.c
@@ -204,7 +204,7 @@ static int dns_connect_namesaver(struct dns_nameserver *ns)
 
        /* Add the fd in the fd list and update its parameters */
        dgram->t.sock.fd = fd;
-       fd_insert(fd, dgram, dgram_fd_handler, MAX_THREADS_MASK);
+       fd_insert(fd, dgram, dgram_fd_handler, 1);
        fd_want_recv(fd);
        return 0;
 }
@@ -1952,7 +1952,7 @@ static int dns_finalize_config(void)
                }
 
                /* Create the task associated to the resolvers section */
-               if ((t = task_new(MAX_THREADS_MASK)) == NULL) {
+               if ((t = task_new(1)) == NULL) {
                        ha_alert("config : resolvers '%s' : out of memory.\n", resolvers->id);
                        err_code |= (ERR_ALERT|ERR_ABORT);
                        goto err;
```

**Comment by wtarreau** [comment] 2019-12-06 07:42
On Thu, Dec 05, 2019 at 11:36:52PM -0800, Vladimir Mihailenco wrote:
> That patch does not apply cleanly on master or v2.1.0. In the end I've used
> v2.1.0 and manually applied changes you suggested. Let me know if I should
> try v2.2...

Ah, it must be because of the copy-paste. For now 2.1 and 2.2 are the same
so don't worry, your manual apply is OK. Let's see if the problem comes
again, but I suspect not. Based on your output, the update_mask=ff...ff
suggests that the pollers (one per thread) don't see the latest update
caused bu fd_stop_send(). But that part is tricky and we're still trying
to figure if anything is wrong there or not.

**Comment by vmihailenco** [comment] 2019-12-06 15:05
All seems to be working good during this day. I will keep checking and will post an update if the issue comes back. Thank you!

**Comment by wtarreau** [comment] 2019-12-06 16:31
OK thanks for your feedback

**Comment by wtarreau** [comment] 2019-12-10 18:13
Guys, we finally found the root cause of this, it's been addressed in -master with the two aforementioned patches. They're currently being backported. You can apply them as-is to 2.1. The workaround with the single thread is not sufficient when facing an error unfortunately, it just lowers the risk to meet the problem. Thanks for all your feedback!

Note, I'm tagging it as major because once the problem strikes there's no way to recover except restarting the process :-(

**Comment by wtarreau** [comment] 2019-12-11 10:54
closing since backported to all versions now.

**Closed as completed by wtarreau** 2019-12-11 10:54 UTC
Labels: type: bug, severity: major, subsystem: dns, status: fixed
