### ISSUE TITLE
Increased IH requests after updating to 2.4.16 from 2.4.15

### ISSUE THREAD

**Issue by jvgutierrez** [haproxy/haproxy#1684] opened 2022-05-03 15:28 UTC
### Detailed Description of the Problem

After updating to HAProxy 2.4.16 (we're using the haproxy.debian.net build for debian buster) we've observed an increase of internal errors reported by HAProxy where previously sat at zero. Temporarily enabling httplog shows 500 responses with session state at disconnection set to IH for HTTP/2 requests using POST as HTTP method.

### Expected Behavior

handle HTTP/2 traffic as version 2.4.15

### Steps to Reproduce the Behavior

1. Update to HAProxy 2.4.16

### What is your configuration?

```haproxy
vgutierrez@cp3050:~$ sudo cat /etc/haproxy/haproxy.cfg 
# Note: This file is managed by puppet.

global
    user haproxy
    group haproxy
    stats socket /run/haproxy/haproxy.sock mode 600 expose-fd listeners level admin
    log /var/lib/haproxy/dev/log local0 info
    # do not keep old processes longer than 5m after a reload
    hard-stop-after 5m


defaults
    mode       http
    log-format "%rt %Tr %ST %hr %hs"
    option     dontlognull
    option     accept-invalid-http-request
    option     accept-invalid-http-response
    retries    1
    timeout    connect 50000
    timeout    client 500000
    timeout    server 500000
vgutierrez@cp3050:~$ sudo cat /etc/haproxy/conf.d/tls.cfg 
global

    nbproc 1
    nbthread 24
    cpu-map 1/1- 0 24 2 26 4 28 6 30 8 32 10 34 12 36 14 38 16 40 18 42 20 44 22 46


    ssl-default-bind-options ssl-min-ver TLSv1.2 ssl-max-ver TLSv1.3
    ssl-default-bind-ciphers -ALL:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256
    ssl-default-bind-ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
    ssl-dh-param-file /etc/ssl/dhparam.pem
    tune.ssl.cachesize 512000
    tune.ssl.lifetime 86400
    maxconn 200000


    tune.h2.header-table-size 4096
    tune.h2.initial-window-size 65535
    tune.h2.max-concurrent-streams 100


listen tls
    log global
    maxconn 199000
    bind :443 tfo ssl crt-list /etc/haproxy/crt-list.cfg tls-ticket-keys /run/haproxy-secrets/stek.keys

    bind :::443 tfo v6only ssl crt-list /etc/haproxy/crt-list.cfg tls-ticket-keys /run/haproxy-secrets/stek.keys

    http-reuse always

    # time to wait for a complete HTTP request, It only applies to the header part of the HTTP request (unless option http-buffer-request is used)
    timeout http-request 3600s
    # set the maximum allowed time to wait for a new HTTP request to appear
    timeout http-keep-alive 120s
    # set the maximum inactivity time on the client side
    timeout client 120s
    # inactivity timeout on the client side for half-closed connections
    timeout client-fin 120s
    # connect timeout against a backend server
    timeout connect 3s
    # set the maximum inactivity time on the server side
    timeout server 180s
    # timeout used after upgrading a connection (websockets) or after the first response when no keepalive/close option is specified
    timeout tunnel 3600s

    # TODO: refactor to a more configurable approach
    capture response header X-Cache-Status len 10
    capture request header Host len 25

    http-request set-var(txn.xwd_count) req.hdr_cnt(X-Wikimedia-Debug)
    http-request set-var(req.ciph) ssl_fc_cipher,regsub('^ECDHE-ECDSA-',''),regsub('^ECDHE-RSA-',''),regsub('^TLS_',''),regsub('_','-','g'),regsub('^CHACHA20-POLY1305$','CHACHA20-POLY1305-SHA256')

    acl missing_xwd var(txn.xwd_count) eq 0
    acl h2 fc_http_major eq 2
    acl ssl_session_reused ssl_fc_is_resumed eq 1
    acl ssl_auth_rsa ssl_fc_cipher -m reg ^ECDHE-RSA

    http-request set-var(req.h2) int(1) if h2
    http-request set-var(req.h2) int(0) if !h2
    http-request set-var(req.h2s) str(h2) if h2
    http-request set-var(req.h2s) str(h1) if !h2
    http-request set-var(req.sess) str(new) if !ssl_session_reused
    http-request set-var(req.sess) str(reused) if ssl_session_reused
    http-request set-var(req.auth) str(RSA) if ssl_auth_rsa
    http-request set-var(req.auth) str(ECDSA) if !ssl_auth_rsa


    http-request set-header X-Client-IP "%[src]"
    http-request set-header X-Client-Port "%[src_port]"
    http-request set-header X-Forwarded-Proto "https"
    http-request set-header X-Connection-Properties "H2=%[var(req.h2)]; SSR=%[ssl_fc_is_resumed]; SSL=%[ssl_fc_protocol]; C=%[ssl_fc_cipher]; EC=UNKNOWN;"
    http-request set-header X-Analytics-TLS "vers=%[ssl_fc_protocol];keyx=unknown;auth=%[var(req.auth)];ciph=%[var(req.ciph)];prot=%[var(req.h2s)];sess=%[var(req.sess)]"
    http-response del-header X-Analytics
    http-response del-header Backend-Timing if missing_xwd
    http-response del-header X-ATS-Timestamp if missing_xwd
    http-response del-header X-Envoy-Upstream-Service-Time if missing_xwd
    http-response del-header X-OpenStack-Request-ID if missing_xwd
    http-response del-header X-Powered-By if missing_xwd
    http-response del-header X-Request-Id if missing_xwd
    http-response del-header X-Timestamp if missing_xwd
    http-response del-header X-Trans-Id if missing_xwd
    http-response del-header X-Varnish if missing_xwd

    server backend_server_0 unix@/run/varnish-frontend-0.socket
    server backend_server_1 unix@/run/varnish-frontend-1.socket
    server backend_server_2 unix@/run/varnish-frontend-2.socket
    server backend_server_3 unix@/run/varnish-frontend-3.socket
    server backend_server_4 unix@/run/varnish-frontend-4.socket
    server backend_server_5 unix@/run/varnish-frontend-5.socket
    server backend_server_6 unix@/run/varnish-frontend-6.socket
    server backend_server_7 unix@/run/varnish-frontend-7.socket
    option forwardfor

frontend stats
    no log
    maxconn 1000
    bind :9422
    bind :::9422 v6only
    http-request use-service prometheus-exporter if { path /metrics }
    stats enable
    stats uri /stats
    stats refresh 10s
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.16-1~bpo10+1 2022/04/29 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.16.html
Running on: Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.4.16=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclar
ation-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshi
ft-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPRO
XY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOL
ETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=48).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression. 
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes 
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
httplog example:
cp3050 haproxy[20295]: REDACTED [03/May/2022:15:03:27.430] tls~ tls/backend_server_4 0/0/0/-1/4 500 208 - - IH-- 63734/63733/170/23/0 0/0 {query.wikidata
.org} {} "POST https://query.wikidata.org/sparql HTTP/2.0"
cp3050 haproxy[20295]: REDACTED [03/May/2022:15:03:29.209] tls~ tls/backend_server_1 0/0/0/-1/19 500 208 - - IH-- 63813/63812/
186/20/0 0/0 {intake-analytics.wikimedi} {} "POST https://intake-analytics.wikimedia.org/v1/events?hasty=true HTTP/2.0
```

**Comment by Roguelazer** [comment] 2022-05-03 20:46
I am also seeing this for about 0.08% of HTTP/2 POSTs on a test LB after upgrading to 2.4.16. Haven't figured out yet those particular requests have in common yet. They do all appear to be coming from golang's `http.Client` but that could just be a coincidence.

**Comment by capflam** [comment] 2022-05-04 06:04
`IH--` at this stage means most probably there is a problem with the request when we try to forward it to the server. Do you have any idea what the request looks like ? Do you know if you combine trailers with a specified `content-length` ?

**Comment by capflam** [comment] 2022-05-04 06:07
That's it, the regression was introduced by commit 2eb5243e7

**Comment by capflam** [comment] 2022-05-05 08:22
It should be fixed now. I'm on the backports.

**Comment by capflam** [comment] 2022-05-05 08:38
Now backported. I'm closing the issue. Thanks !

**Closed as completed by capflam** 2022-05-05 08:38 UTC
Labels: type: bug, status: fixed, subsystem: h1

**Comment by wdauchy** [comment] 2022-05-05 08:50
> Now backported. I'm closing the issue. Thanks !

Thanks for the quick fix.
As we are impacted, but also had other issues in 2.4.15, do you think you may emit a new version soon?

**Comment by jvgutierrez** [comment] 2022-05-05 11:15
> Now backported. I'm closing the issue. Thanks !

Thanks, amazing bug handling
