### ISSUE TITLE
Program option: start order, stop order, reload signal

### ISSUE THREAD

**Issue by sodabrew** [haproxy/haproxy#215] opened 2019-08-10 01:46 UTC
## Output of `haproxy -vv` and `uname -a`

From Alpine 3.10:

```
HA-Proxy version 2.0.3 2019/07/23 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -Os -fomit-frame-pointer
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_NS=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1c  28 May 2019
Running on OpenSSL version : OpenSSL 1.1.1c  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

## What should haproxy do differently? Which functionality do you think we should add?

I suggest adding options to control the order in which the program is started, stopped, and the signal used to restart it.

Hypothetical example:
```
program foo
    command /usr/local/bin/foo --arguments
    option start-before-workers
    option stop-before-workers
    option restart-signal SIGUSR1
```

Adding the parsing code is super straightforward, and the signal should be easy enough too. What looks more difficult is ordering the start and stop of the external program with respect to the internal haproxy children, because they all appear to be in the same structure together (am I reading mworker.c right?)

## What are you trying to do?

The new `program` command allows haproxy to manage one or more additional child processes. This is interesting new functionality, and I'm testing it out to run Cloudflare's Argo Tunnel Daemon as a child of haproxy. https://github.com/cloudflare/cloudflared

One problem I'm working on right now is that when haproxy terminates, it signals all of the children simultaneously. Queries that are in-flight in tunnel land on the tunnel daemon just as the `haproxy` workers are shutting down, resulting in user-facing 5xx errors.

On startup, haproxy workers begin much faster than cloudflared, and so are ready to receive traffic when the tunnel comes up, but also on shutdown haproxy workers react to the shutdown signal more quickly than cloudflared. Nevertheless, even on startup this is a race condition against the backend stanzas and their server lists, healthchecks, etc.

A mechanism to order the startup and shutdown sequence would solve this problem:

Startup:
1. Master forks haproxy workers.
2. Wait for haproxy workers to reach a ready-state.
3. Master fork-execs "program" child process.
4. Normal course of business.

Shutdown:
1. Master receives SIGTERM.
2. Signal "program" child process.
3. Wait for "program" to exit.
4. Signal haproxy workers to exit.

I'm sure there are use cases for the opposite ordering, such as using haproxy to manage an application service. In that case, you'd want the haproxy workers to terminate first to drain inbound queries, and then terminate the application last.

There's some useful range of functionality here before getting into more detailed service orchestration. For my use case, I would draw the line at ordering haproxy workers either before or after the program child, but not ordering multiple program children to each other.

**Comment by lukastribus** [comment] 2019-08-11 11:56
This is what a process/service manager like systemd does. Write appropriate unit files and it will cover your use-case just fine.

Forking third party applications from haproxy? I strongly disagree with this feature request, this is not haproxy's job at all.

**Comment by sodabrew** [comment] 2019-08-11 15:56
@lukastribus Please read the notes regarding the `program` feature that haproxy has added as of the 2.0 release: https://github.com/haproxy/haproxy/commit/9a1ee7ac31c56fd7d881adf2ef4659f336e50c9f

This ticket is a feature request to augment the new `program` option with what I believe are relevant details to best make use of this new feature.

To clarify: the original `program` feature commit notes make clear that the external workers are started, stopped, and signaled in the same pool as the haproxy child workers. I assert however that this invites race conditions that limit the effective use of the feature, and so I'd like to request some ordering of the external processes.

**Comment by lukastribus** [comment] 2019-08-11 16:39
I see, I didn't know about this feature.

I guess we brought this on ourselfs, now we need to deal with all those issues.

**Comment by wtarreau** [comment] 2019-08-12 07:39
I'm still not a fan of this feature at all and am pretty sure it will bring more issues than it solves, especially once combined with the need for reloads since sometimes users will want to reload just haproxy and sometimes also the sidecar process. I think its sole valid use case is for complementary utilities like we used to have with stunnel a long time ago, where the other process has to quit at the same time as haproxy, or more recently with SPOA agents which also have to be reloaded (think about an SSO agent for example). Thus in short, if a program comes with dependency ordering with the haproxy workers, it probably has nothing to do in this section.

Also the "startup" sequence you describe doesn't match reality. Workers are immediately operational once started, they don't (and cannot) wait for anything.

**Comment by sodabrew** [comment] 2019-08-12 16:03
@wtarreau I understand your overall reservations about this feature, truly. But it's there so I'd like to make it work really well.

In my case, I'm using it for something that has dependency ordering, and I'm going to pursue another avenue for now, but I still think it's a relevant use-case. I will rebut your points:

- The `stunnel` case is exactly the same as my use case. You really should signal `stunnel` before signaling `haproxy` workers to quit, to give a moment for `stunnel` to stop processing inbound requests, otherwise there is a race where `stunnel` accepts a request, but cannot connect to the `haproxy` worker that has shut down first.

- Workers are _not necessarily_ immediately operational. Two example cases: one, if you have servers default off until a positive healthcheck, and two, if using DNS SRV configuration, the workers will take a moment to make their initial DNS lookups.

**Comment by wtarreau** [comment] 2019-08-12 20:30
On Mon, Aug 12, 2019 at 04:03:48PM +0000, Aaron Stone wrote:
> @wtarreau I understand your overall reservations about this feature, truly.
> But it's there so I'd like to make it work really well.

I understand your point, I just mean that I don't see how this can work
well *by design*. It's the poor man's auxiliary proess management in fact,
for those who don't care about ordering and have no dependencies.

> In my case, I'm using it for something that has dependency ordering, and I'm going to pursue another avenue for now, but I still think it's a relevant use-case. I will rebut your points:
> 
> - The `stunnel` case is exactly the same as my use case. You really should
> signal `stunnel` before signaling `haproxy` workers to quit, to give a moment
> for `stunnel` to stop processing inbound requests, otherwise there is a race
> where `stunnel` accepts a request, but cannot connect to the `haproxy` worker
> that has shut down first.

In fact you'll note that ordering here doesn't matter, because if you stop
stunnel first, you'll stop accepting connections at the edge and send TCP
resets generating lots of errors on clients. If conversely haproxy was
reloaded immediately, stunnel could possibly reduce its invisibility
period. Moreover the example is still not the best one since it's one
case here it would be better not to restart stunnel when you just want
to reload haproxy, and not to reload haproxy when you want to reload
stunnel. If the services are independent, they'd rather be managed
outside of haproxy.

> - Workers are _not necessarily_ immediately operational. Two example cases:
> one, if you have servers default off until a positive healthcheck, and two,
> if using DNS SRV configuration, the workers will take a moment to make their
> initial DNS lookups.

I'm sorry to disappoint you but yes they are. The process only forks *after*
successfully binding the listeners, so there is no way to have a non
operational worker. The fact that it would be able to immediately deliver
traffic is totally orthogonal to process management and is more related to
the ability to transfer the current state from the previous worker via the
state file.

Willy

**Comment by sodabrew** [comment] 2019-08-12 20:43
> I'm sorry to disappoint you but yes they are. The process only forks *after* successfully binding the listeners, 

Is there not a window where the workers have running listeners but haven’t yet looked up their backends?

**Comment by wtarreau** [comment] 2019-08-13 09:34
This window can exist if you make your config like this but it's not the common one: you're supposed not to depend on dynamic server resolution OR to preload the state file upon reload so that their addresses are known upon startup. It is important to keep in mind that haproxy is not a traffic generator, it passes traffic it *receives*. And having it refrain from processing incoming requests during a certain time frame for whatever reason cannot help and would only result in these requests to fail. So in any case, if haproxy is running, it must be operational.

**Comment by sodabrew** [comment] 2019-08-13 10:02
> This window can exist if you make your config like this but it's not the common one

In a highly ephemeral containerized environment, dynamic configs that must be looked up on start is the new normal. The Dataplane API can configure an haproxy that has started with only an extremely minimal config file, for example. My understanding is these are valid use cases for haproxy, and so now comes time to work through systems integration details.

**Comment by wtarreau** [comment] 2019-08-13 14:37
On Tue, Aug 13, 2019 at 03:02:11AM -0700, Aaron Stone wrote:
> > This window can exist if you make your config like this but it's not the common one
> 
> In a highly ephemeral containerized environment, dynamic configs that must be
> looked up on start is the new normal. The Dataplane API can configure an
> haproxy that has started with only an extremely minimal config file,

Exactly and that's precisely why you need your worker to be ready early,
otherwise it will never receive anything from the DPAPI!

Willy

**Comment by sodabrew** [comment] 2019-08-13 22:36
That doesn't make sense to me. What's the point of running a dataplane configurator process as a child of the haproxy master if you also need a dataplane configurator process to generate a config before starting haproxy?

**Comment by wtarreau** [comment] 2019-08-14 03:29
I'm sorry but I don't understand what you're saying. My point was that for workers to receive commands from the DPAPI to update their servers (for example), they need to be started to be listening to the API. If you were to find a way to delay the startup of workers, then they would not be able to receive such updates since they wouldn't be started.

**Comment by sodabrew** [comment] 2019-08-16 15:44
So... a funny thing happened on the way to my alternate solution: I learned that the subprocess I wanted to run, Cloudflare's Tunnel Daemon, has a hidden default shutdown delay of 30 seconds. The flag is not in the docs, but is present in code. Setting it to 0 works well.

While ordering would still be helpful, the window of error during a stop is now down to "acceptable on the internet" levels.

I'll focus on an adjustable restart signal next, if you're amenable to that change?

**Comment by wlallemand** [comment] 2019-08-28 16:02
In my opinion the configurable **reload** signal is something doable which does not complexify too much the process management. I don't have any objection to this feature.

**Comment by capflam** [comment] 2024-12-03 06:45
Considering the `program` section is now deprecated, I guess we can close this feature request.

**Closed as not planned by capflam** 2024-12-03 06:45 UTC
Labels: type: feature
