### ISSUE TITLE
retry-on all-retryable-errors makes use of wrong backend servers

### ISSUE THREAD

**Issue by bjacke** [haproxy/haproxy#623] opened 2020-05-10 21:05 UTC
## Output of `haproxy -vv` and `uname -a`

HA-Proxy version 2.0.14-1~bpo10+1 2020/04/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-kKmitW/haproxy-2.0.14=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

## What's the configuration?

backend b1
    server s1 10.10.0.1:8080 maxconn 20
    option tcp-smart-connect
    retry-on all-retryable-errors
    http-request disable-l7-retry if METH_POST

## Steps to reproduce the behavior

If the backend server here returns http 503 codes instead of 200's (in my case behause the server used 503's when it went into maintenance mode), then haproxy will starty replying to clients results of random other backends that are configured on the server but which only be used by other frontends.

## Actual behavior

wrong backend servers are used by frontend

## Expected behavior

only servers from the right backend server should be used

## Do you have any idea what may have caused this?

As soon as I disable "retry-on all-retryable-errors" the 503 from the right backend server is returned to the clients directly and no wrong backend server is consulted any more.

**Comment by cognet** [comment] 2020-05-10 21:48
Hi,

Can you provide a more complete configuration file that reproduces that problem (with any confidential data redacted, of course) ?

Thanks !!

**Comment by wtarreau** [comment] 2020-05-10 22:08
I'm sorry but there are statements that I cannot parse in your description: "haproxy will starty replying to clients results of random other backends that are configured on the server". What do you mean exactly ? A server belongs to a single backend so you certainly meant something else but based on the rest of your description I cannot figure what.

If the issue is that a different server from the same backend is being used, this is expected when you have "option redispatch" and depending on the number of configured retries, since the purpose is to find a working server to process the request.

**Comment by bjacke** [comment] 2020-05-10 22:28
the backend configuration I posted is actually complete, I was hoping that this is enough for this problem description. The mentioned bogus result from the random other server is really coming from other backends unrelated. Each backend has just one server. I'll try to condense the conf file and send that later.

**Comment by cognet** [comment] 2020-05-10 22:43
I just tried with a simple configuration, two frontends, two backends, one backend per frontend, and couldn't reproduce it, so it may be caused by something in your defaults section, or related to the frontend.

**Comment by bjacke** [comment] 2020-05-11 00:14
here's a condensed config of the maching. The client connections came in through ft_f1 and/or ft_443_v4. As soon as s1 from backend b1 starts sending http 503 to signal maintenance work, the client receives http content from the b2/b3/b4 backend servers (s2/s3/s4).

`global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	server-state-file /var/lib/haproxy/server-state
	stats bind-process 1
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
	master-worker
	maxconn 10000
	hard-stop-after 8h
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private
	ssl-default-bind-ciphers ECDH+CHACHA20:ECDH+AESGCM
	ssl-default-bind-ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384
	ssl-mode-async
	tune.ssl.lifetime 1h
	tune.ssl.default-dh-param 2048

defaults
	mode	http
	log	global
	maxconn 40000
        timeout connect 5500
        timeout client  120s
        timeout server  5500
	timeout tunnel  1h
	timeout queue	9s
	timeout tarpit	1s
	option	dontlognull
	option	httplog
	option	abortonclose
	option http-buffer-request
	option splice-auto
	compression type text/html text/plain text/css application/javascript
	compression algo gzip
	compression offload
	http-reuse safe
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http
	load-server-state-from-file global


frontend ft_f1
 bind 127.0.2.6:443 ssl crt name1.rsa ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 no-tls-tickets accept-proxy
 bind <dedicated_pub_ipv6_addr>:443 ssl crt f1name.pem ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 no-tls-tickets
 option tcp-smart-accept
 tcp-request content track-sc0 src table per_ip_web
 tcp-request content reject if { sc_conn_cur(0) gt 35 } || { sc_conn_rate(0) gt 150 }
 http-request tarpit deny_status 429 if { sc_conn_cur(0) gt 30 } || { sc_conn_rate(0) gt 100 }
 http-request deny if HTTP_1.0 !{ hdr_sub(user-agent) -m beg w3m/ -m beg Lynx/ }
 option forwardfor
 http-request del-header ^X-Forwarded-For:.*
 http-response del-header Server
 http-response replace-header location ^http://(.*) //\1
 use_backend b1

frontend ft_f2
 bind 127.0.2.3:443 ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 accept-proxy ssl crt name1.pem crt name2.pem no-tls-tickets
 bind <pubic_ipv6_addr>:443	ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 ssl crt name1.pem crt name2.pem  no-tls-tickets
 option tcp-smart-accept
 http-request deny if HTTP_1.0 !{ hdr_sub(user-agent) -m beg w3m/ -m beg Lynx/ }
 option forwardfor
 http-request del-header ^X-Forwarded-For:.*
 http-response del-header Server
 use_backend b3

frontend ft_f3
 bind 127.0.2.5:443 ssl crt f3.pem ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 no-tls-tickets accept-proxy
 bind <pub_ipv6_addr>:443 ssl crt f3.pem ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 no-tls-tickets
 option tcp-smart-accept
 use_backend b4

frontend ft_f4
 bind 127.0.2.1:443 ssl crt f4.pem ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 no-tls-tickets accept-proxy
 bind <public_ipv6_ip>:443 ssl crt f4.pem ssl-min-ver TLSv1.2 allow-0rtt strict-sni tfo alpn h2,http/1.1 no-tls-tickets
 option tcp-smart-accept
 use_backend b2


backend b2
    server s2 10.11.0.147:8080 maxconn 30 proto h2
    option tcp-smart-connect
    timeout server 120000

backend b3
    server s3 10.11.0.3:8080 maxconn 200
    option tcp-smart-connect
    timeout server 120000

backend b4
    server s4 10.11.0.5:8080 maxconn 30
    option tcp-smart-connect
    timeout server 120000

backend b1
    server s1 10.11.0.6:8080 maxconn 20
    option tcp-smart-connect
# this is broken with intended 503 failaures on the backend server, see https://github.com/haproxy/haproxy/issues/623
    retry-on all-retryable-errors
    http-request disable-l7-retry if METH_POST

mailers mymailers
 mailer local_smtp ::1:25

# #####################################################
# ########       TCP frontends/backends:        #######
# #####################################################
defaults
	mode	tcp
	log	global
	maxconn 40000
        timeout connect 5500
        timeout client  120s
        timeout server  5500
	timeout tunnel  1h
	option splice-auto
	option	abortonclose
	load-server-state-from-file global

frontend ft_443_v4
 bind :443 defer-accept tfo
 bind <specific_ipv6_adress>:443 defer-accept tfo
 mode tcp
 option tcp-smart-accept
# mapping SNI's to backends below:
 use_backend %[req.ssl_sni,lower,map_str(/etc/haproxy/maps.tls-sni-backends,bk_sni2)]

backend bk_sni1
 server sl1 127.0.2.1:443 source 127.1.2.1 send-proxy-v2
 mode tcp

backend bk_sni2
 server sl2 127.0.2.3:443 source 127.1.2.3 send-proxy-v2
 mode tcp

backend bk_sni3
 server sl3 127.0.2.5:443 source 127.1.2.5 send-proxy-v2
 option tcp-smart-connect
 mode tcp

backend bk_sni4
 server sl4 127.0.2.6:443 source 127.1.2.6 send-proxy-v2
 mode tcp


`

**Comment by wtarreau** [comment] 2020-05-11 05:38
But this doesn't make any sense, I'm sorry to have to say this. It's the *backend* which chooses a server from its list. Backends don't know each other. Further, in your configuration, each frontend seems to be hard-coded to a single backend, so we couldn't even imagine a situation where a backend connection from a previous request could have accidently been reused. What do you see in your logs for these requests ?

**Comment by capflam** [comment] 2020-05-11 06:17
503 may be handled as a transient error by the client which retries the request. If so, you will have multiple lines in your log for the "same" request.

**Comment by wtarreau** [comment] 2020-05-11 08:07
I didn't think about it but that's a very good point!

**Comment by bjacke** [comment] 2020-05-11 13:45
I was suprised by that, too - but this is how it is. Let me know if you need anything else from me. I would like to avoid reproducing the error but I can do that if needed.

**Comment by wtarreau** [comment] 2020-05-11 13:52
I'm sorry, but without the logs and a detailed capture on each side, it's really impossible to imagine what can lead to anything looking like this behavior. It's almost as if you said that a request starts on one haproxy and finishes on another one. There are certain things that are technically not possible in the code because the amount of changes required to implement something like this can hardly let it happen just by mistake.

I'm not saying there's not a bug, it's very likely that you faced one. I'm just contesting the analysis and without the details it's not possible to make any progress on this.

**Comment by cognet** [comment] 2020-05-12 20:33
Hi,

I think I understood what the problem is. Can you try the attached patch, and let me lnow if it fixes it for you ? Thanks !
[0001-BUG-MEDIUM-streams-Remove-SF_ADDR_SET-if-we-re-retry.txt](https://github.com/haproxy/haproxy/files/4618316/0001-BUG-MEDIUM-streams-Remove-SF_ADDR_SET-if-we-re-retry.txt)

**Comment by wtarreau** [comment] 2020-05-12 21:06
That indeed makes quite some sense. And it would explain why the connections are seen on the wrong server from outside while from inside they're seen as directed to the correct server. In fact they go to the correct server but with a wrong target address!

**Comment by cognet** [comment] 2020-05-12 21:11
Yes that is my understanding as well :) And i couldn't reproduce it because I tested with 2.2, which behaves differently

**Comment by cognet** [comment] 2020-05-13 17:11
Bah, I just accidentally pushed the patch in master, while I wanted to wait for feedback. It doesn't mention that issue, for the record, 8cabc9783aaa8309f4ec6f7dd95cd74c61ed2e61 should fix this in 2.2.

**Comment by bjacke** [comment] 2020-05-13 22:35
> Can you try the attached patch, and let me lnow if it fixes it for you ?

the fix looks quite reasonable, thank you! Testing a self-compiled haproxy on the system where I observed this will take me a little while however. Maybe it's better to release the obviously good patch already and I can give the feedback later on also.

**Comment by cognet** [comment] 2020-05-13 22:40
@bjacke There's no hurry, your feedback would be appreciated, I'd like to be sure it fixes your issue :)
Thanks !

**Comment by bjacke** [comment] 2020-05-27 00:49
the patch seems to fix the issue

**Comment by wtarreau** [comment] 2020-05-29 04:45
Thank you, much appreciated! Given the patch was backported to 2.1 and 2.0 already, I'm marking this fixed and closing.

**Closed as completed by wtarreau** 2020-05-29 04:45 UTC
Labels: type: bug, status: fixed
