### ISSUE TITLE
build fails on reg-tests/checks/tcp-checks-socks4.vtc

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#937] opened 2020-11-03 18:29 UTC
repro steps:

```
make -j3 CC=gcc ERR=1 TARGET=linux-glibc USE_OPENSSL=1
make reg-tests VTEST_PROGRAM=../vtest/vtest -- --debug reg-tests/checks/tcp-checks-socks4.vtc
```

test output:

```
########################## Preparing to run tests ##########################
Testing with haproxy version: 2.3-dev9-dfe792-15
Target : linux-glibc
Options : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS
########################## Gathering tests to run ##########################
  Add test: reg-tests/checks/tcp-checks-socks4.vtc
########################## Starting vtest ##########################
Testing with haproxy version: 2.3-dev9-dfe792-15
**** dT   0.000
*    top  TEST reg-tests/checks/tcp-checks-socks4.vtc starting
**** top  extmacro def pwd=/home/ilia/haproxy
**** top  extmacro def no-htx=
**** top  extmacro def localhost=127.0.0.1
**** top  extmacro def bad_backend=127.0.0.1 44059
**** top  extmacro def bad_ip=192.0.2.255
**** top  macro def testdir=/home/ilia/haproxy/reg-tests/checks
**** top  macro def tmpdir=/tmp/haregtests-2020-11-03_23-27-57.2eEkHc/vtc.109824.34c33db2
**   top  === varnishtest "Health-checks: basic HTTP health-check though a...
*    top  VTEST Health-checks: basic HTTP health-check though a socks4 proxy
**   top  === feature ignore_unknown_macro
**   top  === server s1 {
**   s1   Starting server
**** s1   macro def s1_addr=127.0.0.1
**** s1   macro def s1_port=33759
**** s1   macro def s1_sock=127.0.0.1 33759
*    s1   Listen on 127.0.0.1 33759
**   top  === server socks {
**   socks Starting server
**** socks macro def socks_addr=127.0.0.1
**** socks macro def socks_port=35705
**** socks macro def socks_sock=127.0.0.1 35705
*    socks Listen on 127.0.0.1 35705
**   top  === syslog S1 -level notice {
**   s1   Started on 127.0.0.1 33759 (1 iterations)
**   S1   Starting syslog server
**** S1   macro def S1_addr=127.0.0.1
**** S1   macro def S1_port=55734
**** S1   macro def S1_sock=127.0.0.1 55734
*    S1   Bound on 127.0.0.1 55734
**   socks Started on 127.0.0.1 35705 (1 iterations)
**   top  === haproxy h1 -conf {
**   S1   Started on 127.0.0.1 55734 (level: 5)
**** dT   0.001
**   S1   === recv
**** h1   macro def h1_closed_sock=::1 36095
**** h1   macro def h1_closed_addr=::1
**** h1   macro def h1_closed_port=36095
**** dT   0.007
**** h1   macro def h1_cli_sock=::1 37359
**** h1   macro def h1_cli_addr=::1
**** h1   macro def h1_cli_port=37359
**** h1   setenv(cli, 9)
**** h1   macro def h1_socks_sock=::1 40231
**** h1   macro def h1_socks_addr=::1
**** h1   macro def h1_socks_port=40231
**** h1   setenv(socks, 10)
**   h1   haproxy_start
**** h1   opt_worker 0 opt_daemon 0 opt_check_mode 0 opt_mcli 0
**** h1   argv|exec "/home/ilia/haproxy/haproxy" -d  -f "/tmp/haregtests-2020-11-03_23-27-57.2eEkHc/vtc.109824.34c33db2/h1/cfg" 
**** dT   0.008
**** h1   conf|    global
**** h1   conf|\tstats socket "/tmp/haregtests-2020-11-03_23-27-57.2eEkHc/vtc.109824.34c33db2/h1/stats.sock" level admin mode 600
**** h1   conf|    stats socket "fd@${cli}" level admin
**** h1   conf|
**** h1   conf|    defaults
**** h1   conf|        mode tcp
**** h1   conf|        timeout client 1s
**** h1   conf|        timeout server 1s
**** h1   conf|        timeout connect 100ms
**** h1   conf|
**** h1   conf|    backend be1
**** h1   conf|        log 127.0.0.1:55734 daemon
**** h1   conf|        option log-health-checks
**** h1   conf|        option httpchk
**** h1   conf|        server srv 127.0.0.1:33759 socks4 ::1:40231 check-via-socks4 check inter 1s rise 1 fall 1
**** h1   conf|
**** h1   conf|    listen socks
**** h1   conf|        bind "fd@${socks}"
**** h1   conf|        tcp-request inspect-delay 500ms
**** h1   conf|        ## Accept socks4 request on 16 bytes :
**** h1   conf|        ##    version(1) : 0x04
**** h1   conf|        ##    command(1) : 0x01
**** h1   conf|        ##    port(2)    : 33759
**** h1   conf|        ##    addr(4)    : 127.0.0.1
**** h1   conf|        ##    user-id    : "HAProxy\0"
**** h1   conf|        tcp-request content accept if { req.len eq 16 } { req.payload(0,1) -m bin "04" } { req.payload(1,1) -m bin "01" } { req.payload(2,2),hex,hex2i eq 33759 } { req.payload(4,4),hex,hex2i -m ip 127.0.0.1 } { req.payload(8,8) -m bin "484150726F787900" }
**** h1   conf|        tcp-request content reject
**** h1   conf|        server srv 127.0.0.1:35705
**** h1   conf|
**** h1   XXX 12 @727
***  h1   PID: 109832
**** h1   macro def h1_pid=109832
**** h1   macro def h1_name=/tmp/haregtests-2020-11-03_23-27-57.2eEkHc/vtc.109824.34c33db2/h1
**   top  === syslog S1 -wait
**   S1   Waiting for syslog server (7)
**** dT   0.016
***  h1   debug|Note: setting global.maxconn to 262126.
***  h1   debug|Available polling systems :
***  h1   debug|      epoll : pref=300,  test result OK
***  h1   debug|       poll : pref=200, 
***  h1   debug| test result OK
***  h1   debug|     select : pref=150,  test result FAILED
***  h1   debug|Total: 3 (2 usable), will use epoll.
***  h1   debug|
***  h1   debug|Available filters :
***  h1   debug|\t[SPOE] spoe
***  h1   debug|\t[COMP] compression
***  h1   debug|\t[TRACE] trace
***  h1   debug|\t[CACHE] cache
***  h1   debug|\t[FCGI] fcgi-app
**** dT   0.038
***  h1   debug|Using epoll() as the polling mechanism.
**** dT   0.048
***  h1   debug|[WARNING] 307/232758 (109832) : Health check for server be1/srv failed, reason: Layer4 connection problem, info: "General socket error (Address family not supported by protocol)", check duration: 0ms, status: 0/1 DOWN.
**** S1   syslog|<29>Nov  3 23:27:58 localhost.localdomain haproxy[109832]: Health check for server be1/srv failed, reason: Layer4 connection problem, info: "General socket error (Address family not supported by protocol)", check duration: 0ms, status: 0/1 DOWN.
**   S1   === expect ~ "[^:\\[ ]\\[${h1_pid}\\]: Health check for server b...
***  h1   debug|[WARNING] 307/232758 (109832) : Server be1/srv is DOWN. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
***  h1   debug|[NOTICE] 307/232758 (109832) : haproxy version is 2.3-dev9-dfe792-15
***  h1   debug|[NOTICE] 307/232758 (109832) : path to executable is /home/ilia/haproxy/haproxy
***  h1   debug|[ALERT] 307/232758 (109832) : backend 'be1' has no server available!
---- S1   EXPECT FAILED ~ "[^:\[ ]\[109832\]: Health check for server be1/srv succeeded, reason: Layer7 check passed.+code: 200.+check duration: [[:digit:]]+ms, status: 1/1 UP."
*    top  RESETTING after reg-tests/checks/tcp-checks-socks4.vtc
**   h1   Reset and free h1 haproxy 109832
**   h1   Wait
**   h1   Stop HAproxy pid=109832
**** h1   Kill(2)=0: Success
**** dT   0.051
**** h1   STDOUT EOF
**** dT   0.148
**   h1   WAIT4 pid=109832 status=0x0002 (user 0.019848 sys 0.022848)
**** dT   0.149
**   s1   Waiting for server (4/-1)
**   socks Waiting for server (5/-1)
*    top  TEST reg-tests/checks/tcp-checks-socks4.vtc FAILED
#    top  TEST reg-tests/checks/tcp-checks-socks4.vtc FAILED (0.150) exit=2
1 tests failed, 0 tests skipped, 0 tests passed
########################## Gathering results ##########################
###### Test case: reg-tests/checks/tcp-checks-socks4.vtc ######
## test results in: "/tmp/haregtests-2020-11-03_23-27-57.2eEkHc/vtc.109824.34c33db2"
---- S1   EXPECT FAILED ~ "[^:\[ ]\[109832\]: Health check for server be1/srv succeeded, reason: Layer7 check passed.+code: 200.+check duration: [[:digit:]]+ms, status: 1/1 UP."
make: *** [Makefile:1020: reg-tests] Error 1
```

**Comment by chipitsine** [comment] 2020-11-03 18:30
this issue is derived from https://github.com/haproxy/haproxy/issues/924

**Comment by chipitsine** [comment] 2020-11-03 18:38
reg-tests/checks/tcp-checks-socks4.vtc is marked "slow"
in travis-ci we do not run "slow" tests

```
make reg-tests VTEST_PROGRAM=../vtest/vtest REGTESTS_TYPES=default,bug,devel
```


by occasion all tests were enabled for no-deprecated openssl build.
maybe that test is broken by itself ?

**Comment by wlallemand** [comment] 2020-11-03 18:45
Yes, that's what I was saying in the initial ticket.

But something is strange with this bug, I can't reproduce it on some machines with the same version of HAProxy. I suspect that something changed in the dependencies. OpenSSL is probably unrelated here.

**Comment by capflam** [comment] 2020-11-04 14:02
Here the bug is that ipv4 and ipv6 are mixed, for an unknown reason. First, ipv6 are not supported by SOCKS4 protocol. But here the error is triggered during the connect because the server family is not the same than the socks4 one. The server family (AF_INET) is used to create the socket, but the connect() is performed with an ipv6 address. 

I don't know if there is way to instruct vtest to use ipv4 addresses only.

**Comment by wlallemand** [comment] 2020-11-04 14:35
Unfortunately, you can't. It's randomly selected depending on your environment.

**Comment by wlallemand** [comment] 2020-11-04 14:43
Basically the problem is that vtest will resolve localhost that could return either ::1 or 127.0.0.1, if you remove the ipv6 from /etc/hosts the problem disappear. An ugly fix could be to replace the address by 127.0.0.1.

**Comment by wlallemand** [comment] 2020-11-04 14:51
It does not look like it's possible with vtest.

**Comment by wlallemand** [comment] 2020-11-04 15:22
It's fixeable easily in our own part of VTest with the attached patch.
[0001-vtc_haproxy-VTCP_listen_on-127.0.0.1-instead-of-loca.patch.txt](https://github.com/haproxy/haproxy/files/5488666/0001-vtc_haproxy-VTCP_listen_on-127.0.0.1-instead-of-loca.patch.txt)

I'm submitting this to phk.

**Comment by wlallemand** [comment] 2020-11-11 21:36
The pull request was merged into VTest master so you shouldn't have the problem anymore.

**Closed as completed by wlallemand** 2020-11-11 21:36 UTC
Labels: type: bug, status: fixed
