### ISSUE TITLE
Can't fetch tcp-request content capture results anymore

### ISSUE THREAD

**Issue by dgl** [haproxy/haproxy#2642] opened 2024-07-17 05:20 UTC
### Detailed Description of the Problem

In a `mode tcp` frontend, it is possible to capture some content, e.g.:

```
  tcp-request content capture req.payload(0,0) len 64
```

In 2.8 it is then possible to do something like:

```
  log-format "%[capture.req.hdr(0),field(1,\r\n)]"
```

### Expected Behavior

It was possible to log captured content. Instead, the configuration is invalid on 3.0.2:

```
failed to parse log-format : logformat expression not usable here (at least one node depends on HTTP mode).
```

### Steps to Reproduce the Behavior

With minimal config below, nc localhost 444, type something, see it logged. haproxy 3.0.2 doesn't accept the config.

### Do you have any idea what may have caused this?

7a21c3a4ef maybe

### Do you have an idea how to solve the issue?

```
diff --git a/src/http_fetch.c b/src/http_fetch.c
index ad1e8c543..1446f9f4d 100644
--- a/src/http_fetch.c
+++ b/src/http_fetch.c
@@ -2236,7 +2236,7 @@ static struct sample_fetch_kw_list sample_fetch_keywords = {ILH, {
        { "baseq",              smp_fetch_base,               0,                NULL,   SMP_T_STR,  SMP_USE_HRQHV },
 
        /* capture are allocated and are permanent in the stream */
-       { "capture.req.hdr",    smp_fetch_capture_req_hdr,    ARG1(1,SINT),     NULL,   SMP_T_STR,  SMP_USE_HRQHP },
+       { "capture.req.hdr",    smp_fetch_capture_req_hdr,    ARG1(1,SINT),     NULL,   SMP_T_STR,  SMP_USE_L5CLI },
 
        /* retrieve these captures from the HTTP logs */
        { "capture.req.method", smp_fetch_capture_req_method, 0,                NULL,   SMP_T_STR,  SMP_USE_HRQHP },
```

Which is a bit hacky, but works, proving it's just the config validation; it might be better to add a new fetch method for TCP connections, but this has regressed this slightly obscure config.

### What is your configuration?

```haproxy
global
  log stdout format raw local1 info info

defaults
  timeout connect 10s
  timeout client 60s
  timeout server 5m
  log global

frontend tcp
  mode tcp
  bind :444
  tcp-request inspect-delay 10s
  tcp-request content reject if { req.payload(0,4) -m str "abcd" }
  tcp-request content capture req.payload(0,0) len 64
  option logasap
  log-format "%T %ci:%cp %{+Q,+E}[capture.req.hdr(0),field(1,\r\n)]"
```
```


### Output of `haproxy -vv`

```plain
Tested on:

HAProxy version 3.1-dev3-a9e3de-68 2024/07/16 - https://haproxy.org/
Status: development branch - not safe for use in production.
```

**Comment by Darlelet** [comment] 2024-07-17 08:53
Hi @dgl 

Thanks for reporting this

Arf, you're right, prior to 7a21c3a4 there should have been a warning already:
https://github.com/haproxy/haproxy/blob/56d8074798772978f37fbca5667ad3d3ddc8ab20/src/proxy.c#L1282-L1287

(See 59ad1a2e7584669d591ccd290fd027e8c190ebe4)

Unfortunately, due to implementation limitations, some logformat expressions such as `log-format` directive were resolved after the check, so the check was ineffective. Since 7a21c3a4 expressions are ensured to be resolved before the postparsing checks.

So this is a regression indeed, but it should have been working this way initially (if the postparsing checks weren't broken in the past).

Perhaps we should relax the check to raise a warning instead of a hard error to let people adjust they configs.. and/or provide a non-http fetch alternative as you suggested to stop "hacking" with the http-oriented one from tcp proxies.

Meanwhile, you could work around the error by letting haproxy think that the proxy may upgrade to HTTP at some point (even if it doesn't):
```diff
@@ -13,5 +13,6 @@
   tcp-request inspect-delay 10s
   tcp-request content reject if { req.payload(0,4) -m str "abcd" }
   tcp-request content capture req.payload(0,0) len 64
+  tcp-request content switch-mode http if FALSE
   option logasap
   log-format "%T %ci:%cp %{+Q,+E}[capture.req.hdr(0),field(1,\r\n)]"
```

**Comment by capflam** [comment] 2024-07-17 12:44
Captures are somewhat old and some parts are not really usable. For instance, It is not really handy to mix captures via TCP/HTTP rule and declared captures , or captures in frontends and backends. In fact, the main usage is to capture info from HTTP messages to automatically have them in the logs. Outside this usage, it is pretty hard to use. In addition, the documentation is not quite clear. The captures are mainly HTTP related. But it is not really clear if it is mandatory or not. And the code is foggy too on this point. We must definitely work on it for the 3.1, in a way or another.

In the mean time, it seems the variables may be a better alternative in your case. You are not capturing part of HTTP request and you are not relying on default log-format messages. Thus you can just use variables to do the same. For instance:

```
   tcp-request inspect-delay 10s
   tcp-request content reject if { req.payload(0,4) -m str "abcd" }
   tcp-request content set-var(txn.payload) req.payload(0,64)
   option logasap
   log-format "%T %ci:%cp %{+Q,+E}[var(txn.payload),field(1,\r\n)]"
```

**Comment by wtarreau** [comment] 2024-07-18 13:15
Instead I think there's nothing that technically blocks from retrieving captures at any point in the logs, because captures have always been opportunistic, and their retrieval is conditioned to their existence. If there was a risk, it would rather be on the action itself: we could very well imagine a risk of leak if a tcp-request rule allocates a capture entry that would only be released in HTTP mode or something like this. But there's currently nothing preventing from using the capture rule in TCP, so I'd be tempted to think that we could relax this dependency. The real issue in fact is rather the lack of dependency bit to characterize the presence of persistent data in non-HTTP mode. Ideally we'd need a pair of L6RQP and L6RSP for that, and captures could be placed there.
But I really don't feel like changing all the SMP_USE_* matrix!

A lighter option could be to drop HRQHP and HRSHP from SMP_USE_HTTP_ANY. They're covering exactly this:
- capture.req.*
- http_first_req
- method
- req.proto_http
- req_proto_http
- res.cache_hit
- res.cache_name
- res.comp
- res.comp_algo
- capture.res.*
- server_status
- status
- txn.status

It doesn't seem *that* bad to let them be accessible in TCP mode. I tend to agree that variables are more flexible than captures nowadays, but it's also true that captures have the benefit of being allocatable from pools instead of malloc()/free().

**Comment by capflam** [comment] 2024-07-18 15:41
Indeed, functionally speaking,  captures are not explicitly related to HTTP. However, the sample fetches suggest it is only usable in an HTTP context.  We can capture anything from a tcp-request content. But to retrieve the captured value, you should use `capture.req.hdr()`  sample fetch.  There is no generic sample fetch (but easy to add). There are 2 generic converters: `capture-req` and `capture-res`. But honestly, those converters are all but natural. I don't understand the purpose. They don't convert anything.  The only way I can see to use them is with `always_true` sample fetch.

All you said is right, there is no reason to have restrictions on HTTP for captures. But the API must be adapted to be clear on this point, and the doc too. In addition, I found pretty hard to know what is captured or not and for a given capture, what is its id. With a simple configuration, it manageable. But in more complex cases, it is pretty hard. I guess it could be good to check if we could improve slots configuration and management.

**Comment by wtarreau** [comment] 2024-07-18 16:19
The only thing in the sample fetches that restrict their compatibility to HTTP is the SMP_USE_HRQHP. The functions themselves are pretty clear on the tests they are making, and do not make any use of HTTP at all, they only retrieve captures **if they exist**. I really don't see any API change to be performed for the sample fetch operations.

I think the converters were made to perform the captures from retrieved data and passing that data to the next stage (sort of a "tee" operation, just like "debug()"), but nowadays it would probably be easier to use set-var.

The approach of captures historically has always been that the user must know what goes where. You assign fixed slots for a given variable and always use the same. I'd say that the code is usually easier to read than a config involving them :-)  Nowadays we support environment variables in config, that would allow to assign names to these slots. But I wouldn't want to extend captures too much unless there would be really compelling reasons. They're still at the plumbery layer, very efficient when properly used but complicated to use. I'd keep them for experts only. This could be another reason for maybe relaxing their dependencies BTW.

**Comment by nwehrman** [comment] 2024-08-12 16:32
One concern that I have about this change is if anyone uses a custom log format for a tcp mode frontend and then does an upgrade their configuration will fail to load.  Since many users are implementing more API automation that could be problematic.  I think that all of these 4 will cause a load failure but the manual doesn't list them as requiring mode HTTP.

```
        { "ST", LOG_FMT_STATUS, PR_MODE_TCP, LW_RESP, NULL },   /* status code */
        { "hr", LOG_FMT_HDRREQUEST, PR_MODE_TCP, LW_REQHDR, NULL }, /* header request */
        { "hrl", LOG_FMT_HDRREQUESTLIST, PR_MODE_TCP, LW_REQHDR, NULL }, /* header request list */
        { "rt", LOG_FMT_COUNTER, PR_MODE_TCP, LW_REQ, NULL }, /* request counter (HTTP or TCP session) */
```

Which results in this error
`failed to parse log-format : logformat expression not usable here (at least one node depends on HTTP mode).`

For this reason I think it's better to keep prior behavior where the configuration would load but could we perhaps improve the log message?

For example:
log-format option <logformat name> attempts to gather http data on a TCP proxy <name here>.  It MAY return an empty value.

That way the know exactly which value in their log-format string is the issue.

**Comment by Darlelet** [comment] 2024-08-12 20:53
>if anyone uses a custom log format for a tcp mode frontend and then does an upgrade their configuration will fail to load.

Normally it should work as expected on 3.0: as long as the frontend leaves the possibility that the connection may upgrade to HTTP, the postparsing check will consider that the proxy may handle HTTP so the check won't prevent the use of HTTP-only fetches or log aliases from the proxy.

this should raise an error:
```
listen test
bind localhost:8888
mode tcp
log-format "%ST"
```

This should start without errors :

```
listen test
bind localhost:8888
mode tcp
tcp-request content switch-mode http if FALSE # even if this is set to FALSE, the postcheck will think that the connection may be upgraded to HTTP
log-format "%ST"
```
```
frontend front
bind localhost:8888
mode tcp
log-format "%ST"
use_backend back # if the backend is HTTP, then the postcheck will think that the connection may be upgraded to HTTP
# this works with dynamic backend name as well: the postcheck will consider the connection may be upgraded even if it doesn't

backend back
mode http
server s1 haproxy.org:80
```

**Comment by nwehrman** [comment] 2024-08-12 21:50
In prior versions the use of "%ST" is allowed in all frontends regardless of the backend.  In the latest version if you use that same configuration then it will fail to load the config and exit. 

This configuration:
```
global
  log 127.0.0.1 local0

defaults unnamed_defaults_1
  mode tcp
  log global
  timeout connect 10000
  timeout client 10000
  timeout server 10000

frontend fe_test_log from unnamed_defaults_1
  mode tcp
  bind *:88
  log-format "%ST"
  default_backend be_test_log

backend be_test_log from unnamed_defaults_1
  mode tcp
  server server1 172.16.22.32:80
```

In 2.8 haproxy starts and runs fine:
```
haproxy version is 2.8.0-1.0.0-319.723
Aug 12 21:17:31 hapee02 hapee-lb[1325862]: [NOTICE]   (1325862) : New worker (1325864) forked
Aug 12 21:17:31 hapee02 hapee-lb[1325862]: [NOTICE]   (1325862) : Loading success.
Aug 12 21:17:31 hapee02 systemd[1]: Started HAPEE Load Balancer.
```

In 3.1-dev5 (latest) haproxy will fail to start:
```
[NOTICE]   (164748) : haproxy version is 3.1-dev5
[NOTICE]   (164748) : path to executable is ./haproxy
[ALERT]    (164748) : config : Parsing [/home/nate/haproxy-lb.cfg:14]: failed to parse log-format : logformat expression not usable here (at least one item depends on HTTP mode).
[ALERT]    (164748) : config : Fatal errors found in configuration.
```

**Comment by wtarreau** [comment] 2024-08-13 03:21
Generally speaking we should make sure not to break legitimate configs. This one is indeed border line, but it may be legitimate to some extents. I'm wondering what happens with the following:
```
frontend front
  bind localhost:8888
  mode tcp
  log-format "%ST"
  use_backend %[req.hdr(host),map(blah.map)]  ## this one returns "back"

backend back
  mode http
  server s1 haproxy.org:80
```
Dynamic backends are indeed a case where we don't know upfront what backends may be visited by a frontend. I just don't remember if the upgrade is dynamic or not. 

Overall I'm wondering if there is still any legitimacy in checking where some of these log tags may be used, beyond providing diagnostics. I mean, originally their code was very sensitive and the checks were made to make sure we didn't dereference uninitialized fields. Nowadays that's no longer the case. The proof of that is that we can log errors at the session level using a regular log-format string and just report an empty string for fields that are not accessible. Thus I'm seriously wondering if all these checks should not just be relegated to the diag mode, at least when it comes to log-format strings (which can be used at many places nowadays). @Darlelet if you have a moment today we can discuss this.

**Comment by Darlelet** [comment] 2024-08-13 08:40
We've had a quick talk about that with Willy. We're thinking about relaxing the logformat compatibility checks in 3.0+ so that they only emit diag_warnings (haproxy will only report them if it was started with `-dD`).

Most of the time, configs shouldn't trigger those checks. But when they do, we may fall into one of the possibilities below:

- it may indicate that the fetch / log alias won't work as the user intended it to work due to configuration issue and the user isn't aware of it. In such case the diag warning will help him to troubleshoot its configuration. (common use-cases)
- the user is explicitly using the theoretically incompatible fetch/alias because he knows that conditions will be met for the fetch/alias to work during runtime even though it's too complex for the postparsing check to understand it at config time. In this case the user may safely ignore the diag warning. (advanced use-cases)

Also, as Willy stated, from a technical point of view, there doesn't seem to be anything justifying those strict checks anymore as of 3.0. Historically they were preventing potential bugs from happening at runtime due to fetches/aliases not being resilient enough when leveraged from incompatible context. This is not the case anymore. The simple fact that those checks didn't work consistently prior to 7a21c3a4ef1577985621953a79e2776ef97837ab (although they existed) without impacting the process stability in multiple stable versions demonstrates that (when used from an incompatible context, fetches/aliases silently fail).

So in the end, those checks should be seen as configuration hints, which is what diagnostic mode is made for (and we actually encourage users to use it from time to time)

**Comment by nwehrman** [comment] 2024-08-13 15:34
That sounds great. I really like that approach. While you are doing that if you can squeeze it in to make the error message (diagnostic message) a tad more verbose and point out the specific object that would be great.  I mainly say that because from my personal experience I knew something was failing but didn't know which option.  If we make this a diagnostic message as is then it will just output the line number but a log-format variable of %rt will fail but it's still valid for both HTTP and TCP.

Without knowing the specific object it becomes very difficult to spot from documentation alone.  Even if it's just the first object that fails that would be a nice improvement. Thanks so much for all the work on this!

**Comment by wtarreau** [comment] 2024-08-13 15:42
For sample expressions used in variables etc normally you know exactly what it is because the details are reported (e.g. "sample fetch foobar cannot be used since it depends on http headers which are not yet available here". But with log-format expressions it's more difficult: currently we report a synthetic message for the whole expression, and there could be more than one error. Maybe by moving the diag warnings into the function as Aurélien suggested, it could do the job, but I don't want to promise something too early!

**Comment by Darlelet** [comment] 2024-08-13 18:03
>While you are doing that if you can squeeze it in to make the error message (diagnostic message) a tad more verbose and point out the specific object that would be great

>it could do the job, but I don't want to promise something too early!

@wtarreau @nwehrman turns out it's our lucky day, this was actually simple this time :)

I think I got it right, but I'm not committing today because I still have some more tests to do, but if you're willing to try and provide feedback, here's the patch: 
[0001-MEDIUM-log-relax-some-checks-and-emit-diag-warnings-.patch.txt](https://github.com/user-attachments/files/16603530/0001-MEDIUM-log-relax-some-checks-and-emit-diag-warnings-.patch.txt)

**Comment by wtarreau** [comment] 2024-08-13 21:03
Cool, Aurélien! I think at the same time it may also address some of Nathan's concerns regarding the details of what causes the warning, since I'm seeing for example "format alias '%s' used ..." indicating that each message will report some precise info about what was found.

**Comment by wtarreau** [comment] 2024-09-05 15:45
Now that was backported to 3.0, we can close it!

**Closed as completed by wtarreau** 2024-09-05 15:45 UTC
Labels: type: bug, status: fixed
