### ISSUE TITLE
Cannot set userlist insecure-password from environment variable

### ISSUE THREAD

**Issue by slimhazard** [haproxy/haproxy#590] opened 2020-04-19 19:31 UTC
## Output of `haproxy -vv` and `uname -a`

```
$ /usr/sbin/haproxy -vv
HA-Proxy version 2.0.13-1~bpo10+1 2020/02/15 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-Dphp8U/haproxy-2.0.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

$ uname -a
Linux <hostname> 4.15.0 #1 SMP Wed Sep 18 07:44:58 PDT 2019 x86_64 GNU/Linux
```

## What's the configuration?

```
userlist controller
    user dataplaneapi insecure-password "${SECRET_DATAPLANEAPI}"
```
I don't believe that any other part of the configuration is relevant to the problem. As you can see, I'm doing this for the dataplaneapi, but I believe the issue doesn't depend on that.

I can see in `/proc/<pid>/environ` that the environment variable is indeed set for the master process:

```
$ cat /proc/$pid/environ | tr '\0' '\n'
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SECRET_DATAPLANEAPI=e24bb312-cb21-46d6-aaec-8ae676f06fea
[...]
```
To verify that setting configuration with that env variable does work elsewhere, I am adding a response header to a frontend in http mode that is set to the variable:

```
frontend foo
        mode http
        http-response add-header X-Env "${SECRET_DATAPLANEAPI}"
        [...]
```
## Steps to reproduce the behavior

1. I'm using haproxy in master-worker mode, including the configuration shown above.
2. Send a request for which the response header is added (frontend foo).
3. Send a request for which the userlist password is required, in this case basic auth for the dataplaneapi. Use the value of the variable as the password (`e24bb312-cb21-46d6-aaec-8ae676f06fea`).
4. Send the same request using the literal string `"${SECRET_DATAPLANEAPI}"` as the password -- as shown, with the dollar sign, quotation marks, and curly braces enclosing the string `SECRET_DATAPLANEAPI`.

## Actual behavior

In the response in which the header is set, header `X-Env` has the value of the env variable (`e24bb312-cb21-46d6-aaec-8ae676f06fea`), verifying that, in general, configuration can be set from the variable.

Basic auth fails with the value of the env variable as the password. It succeeds when the literal string `"${SECRET_DATAPLANEAPI}"` is used as the password.

## Expected behavior

Basic auth in this case should succeed with the value of the env variable as the password. That is, `userlist insecure-password` should evaluate the env variable, just as it was evaluated for `http-response add-header`.

## Do you have any idea what may have caused this?

Presumably, configuration parsing does not evaluate the variable in the case of `insecure-password`, although it does so for other elements of the config. I don't see any reason why `insecure-password` would have intentionally been an exception; at any rate, I couldn't find anything in the documentation indicating that it wouldn't work.

From the look of this [serverfault question](https://serverfault.com/questions/720831/haproxy-userlist-password-from-an-environment-variable), this appears to have been a problem since 2015. There was never an answer to the serverfault question, and I couldn't find any references to it in a github issue search.

## Do you have an idea how to solve the issue?

There appears to be no other option but to set a fixed string as the password. I wanted to use the environment variable so that the password can be different for different deployments (the env variable, in turn, was to be set from a Kubernetes Secret). Of course, using the same password for every deployment defeats the purpose of authentication.

**Comment by wlallemand** [comment] 2020-04-20 12:45
I'm not able to reproduce the problem using the following configuration:

```
listen foo
	bind :8888
	mode http


	acl auth http_auth(controller)
	http-request auth realm foobar unless auth

	http-response add-header X-Env "${SECRET_DATAPLANEAPI}"
	server foobar 127.0.0.1:80

userlist controller
	user dataplaneapi insecure-password "${SECRET_DATAPLANEAPI}"
```

Launching HAProxy this way: `SECRET_DATAPLANEAPI=e24bb312-cb21-46d6-aaec-8ae676f06fea ./haproxy -W -f userlist-env.cfg`

and sending a request this way:

`curl -v -u dataplaneapi:e24bb312-cb21-46d6-aaec-8ae676f06fea http://localhost:8888`

Everything seems to work fine using the 2.0.13 version.

Regarding the serverfault question, it looks like this guy doesn't use the correct format, variables should be evaluated only between double quotes, there are few historical exceptions where it's not needed, though. But you must avoid doing that.

**Comment by slimhazard** [comment] 2020-04-20 16:27
Hmm, the rest of the configuration may be more relevant than I thought, as well as the specifics of the dataplaneapi.

I did not use the `acl auth http_auth(controller)` config, following [these instructions](https://www.haproxy.com/documentation/hapee/1-9r1/configuration/dataplaneapi/) for setting up dataplaneapi, which don't mention it. The dataplaneapi implements basic auth, and uses the haproxy userlist `controller` by default (can be changed via CLI option). Without the environment variable, I was able to use dataplaneapi that way, without the `http_auth` config.

So my understanding was that dataplaneapi checks the credentials, not haproxy, but it uses the haproxy `userlist` to get the definition of credentials.

But I'll try again with the `http_auth` config.

**Comment by wlallemand** [comment] 2020-04-20 16:43
From what I understand of your explanation and the documentation, the dataplane-api loads the userlist section of your configuration itself, so if there is no support for variables in the dataplane-api, the problem is probably there.

**Comment by slimhazard** [comment] 2020-04-20 17:15
I frankly don't understand it, but this is working:
```
userlist controller
    user dataplaneapi insecure-password "${SECRET_DATAPLANEAPI}"

listen dataplane
       bind :5555
       mode http
       acl auth http_auth(controller)
       http-request auth realm dataplane unless auth
       server dplane unix@/dplane.sock
       
program api
        command /usr/bin/dataplaneapi --socket-path=/run/offload/dplane.sock --haproxy-bin /usr/sbin/haproxy --reload-cmd "/bin/kill -SIGUSR2 1" -i --log-to=stdout --log-level=info
        no option start-on-reload
```
And then:
```
$ curl -I -X GET --user 'dataplaneapi:e24bb312-cb21-46d6-aaec-8ae676f06fea' http://localhost:5555/v1/info
HTTP/1.1 200 OK
[...]
```
So, haproxy now has a listener for the dataplaneapi, which is running as a backend -- none of which is mentioned in the instructions for dataplaneapi, nor was it necessary before I tried it with the env variable. With that, I get authorized access, using the password set from the variable.

I guess I could say that my use case works now, so whatever, but it seems strange. dataplaeapi is developed by haproxytech, who of course understands haproxy very well. Could it be that they have a feature that says, "I notice that I'm being frontended by haproxy, who is checking the credentials, so that'll be good enough for me!"

@wlallemand thanks for the hint (even if the result seems a bit mysterious).

**Comment by wlallemand** [comment] 2020-04-20 17:48
I'm going to open an issue on the dataplane API side regarding this, thanks for the feedback.

**Comment by wlallemand** [comment] 2020-04-20 17:58
I'm closing this ticket now, feel free to discuss this on https://github.com/haproxytech/dataplaneapi/issues/83. Thanks!

**Closed as completed by wlallemand** 2020-04-20 17:58 UTC
Labels: type: bug, status: invalid
