### ISSUE TITLE
reg-tests/seamless-reload/abns_socket fails on ppce64le

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#543] opened 2020-03-11 10:08 UTC
https://travis-ci.com/github/haproxy/haproxy/jobs/296839766

I tried to repro on x86_64, it does not fail.

if someone has ppc64le, please investigate

**Comment by wtarreau** [comment] 2020-03-12 19:01
Hi Ilya,

I'm glad that you created this entry, I wanted to do it. A quick update, a week ago I applied for an account on a ppc64 machine in order to reproduce this one which I didn't like. I got the account ready yesterday and could figure the bug(s) today. They *should* now be fixed.

Neither was specific to ppc64. One is a race affecting the (supposedly safer) version of the locked memory pools but not the lock-free ones. The lockfree ones require a double-word CAS that is present on the x86_64 and aarch64 machines we use daily, and other machines usually don't enable threads so it was hard to detect. It's now fixed. The other one was caused by the incoming queue load balancing which sometimes sends an incoming connection to a thread which decides to stop at the same instant. This was causing the very rare (1/100 to 1/50) failures of this test on x86. Now I can't make any of them fail anymore so I'm hopeful that the problem is now fixed.
I'm tagging the entry as fixed and must backport now.

**Comment by TimWolla** [comment] 2020-03-12 19:38
> I got the account ready yesterday and could figure the bug(s) today. They _should_ now be fixed.

Good that hear that this actually was a real bug and not just a bad / unreliable test.



>  I'm tagging the entry as fixed and must backport now.

You forgot to adjust the labels. Could you also give the commit hashes for proper tracking?

**Comment by wtarreau** [comment] 2020-03-12 19:44
On Thu, Mar 12, 2020 at 12:38:17PM -0700, Tim Düsterhus wrote:
> Good that hear that this actually was a real bug and not just a bad /
> unreliable test.

Yes, definitely!

> >  I'm tagging the entry as fixed and must backport now.
> 
> You forgot to adjust the labels.

No I didn't forget, they don't show up anymore when I click. They probably
broke their WebUI again to make it incompatible with the browser on the
mini-pc I'm responding from.

> Could you also give the commit hashes for proper tracking?

Yep, these are 51d9339, a7da5e8, 4b3f27b.

I didn't reference the issue in them since I didn't notice it in time.

**Comment by TimWolla** [comment] 2020-03-12 19:51
> No I didn't forget, they don't show up anymore when I click. They probably broke their WebUI again to make it incompatible with the browser on the mini-pc I'm responding from.

Okay, I've updated the labels based on the commit message in the three commits you linked.

**Comment by chipitsine** [comment] 2020-03-13 03:53
I came to idea that I cam try ppc64le on virtualbox. I'll give it a try next weekend

**Comment by wtarreau** [comment] 2020-03-13 04:02
Don't worry, I do have a real account on a real ppc64 (power8), so that allows to discover trickier things (like unaligned atomics). At least it managed to reproduce exactly this issue, which is nice. I think we should also split the abns test into abns AND seamless reload, so that the seamless reload part can work on non-linux systems as well, because I noticed it used to fail even without the abns backend.

**Comment by chipitsine** [comment] 2020-03-13 10:04
failed one more time 

https://travis-ci.com/github/haproxy/haproxy/jobs/297700592

(I still hope to play with virtualbox on weekend)

**Comment by wtarreau** [comment] 2020-03-13 16:32
On Fri, Mar 13, 2020 at 03:04:33AM -0700, Ilya Shipitsin wrote:
> failed one more time 
> 
> https://travis-ci.com/github/haproxy/haproxy/jobs/297700592

Yep, just noticed as well and I was confused into thinking it was the
s390x again that was failing. I hate that vtc. We've seen it far too
much and it gives little information. When I'm too much fed up with
seeing it I'll cut it in two: 1) seamless  2) abns

At least the good thing is that s390x doesn't fail anymore. Theorically
it should randomly just like ppc64le and for the same reasons, so we
should not claim victory too fast but it's not alarming either if it
does.

Willy

**Comment by wtarreau** [comment] 2020-04-02 12:02
Fix backported everywhere now, closing.

**Closed as completed by wtarreau** 2020-04-02 12:02 UTC
Labels: type: bug, status: fixed
