### ISSUE TITLE
HAProxy fails whenever a backend server changes the ip

### ISSUE THREAD

**Issue by ChristianTaidi** [haproxy/haproxy#1278] opened 2021-06-03 08:21 UTC
## Detailed description of the problem

I´m trying to use HAProxy as a reverse proxy to redirect incoming traffic to a private domain that resolves ro different machines but whenever a backend server terminates or changes ip, HAProxy refuses to resolve the new ip via the DNS provided in the resolvers section.

I have HAProxy V2.3.9 running on FreeBSD 12.2

## Expected behavior

The expected behavior is for HAProxy to re-resolve the server ips after a certain time so it does not redirect the traffic to the first resolved ip forever via the ```hold valid``` parameter in the ```resolvers``` section

## Steps to reproduce the behavior

1. Have a number of http servers running under the same domain 
2. Have HAProxy running in another machine configured as a reverse proxy
3. Run traffic through HAProxy to the backend servers
4. While running traffic, kill a server machine but have still some available so it should resolve to a new machine
5. Read the ```haproxy[<pid>]: backend filters has no server available!``` message
6. Now running ```curl -v <haproxy address>``` returns empty responses or Error: socket hang up

## Do you have any idea what may have caused this?

I have no idea why this is happening given the configuration file

## Do you have an idea how to solve the issue?

I don't know how to resolve this, I understand the configuration I set should:

1. Re-resolve ips every 100ms due to the ```hold valid``` 100 parameter which should make HAProxy do all the resolve process again
2. If the ip resolved related to one backend machine fails to respond, it should also resolve a new ip with the given domain and dns.

## What is your configuration?

```
global
        # Log file
        log /var/run/log local0 notice
        # User and group running the service
        user <user>
        group <group>
        # Websocket API for Dynamic configuration of the load balancer
        stats socket /tmp/haproxy/admin.sock user <user> group <group>
        stats timeout 30s
        daemon
	maxconn 32768

        # Default SSL material locations
        ca-base /etc/ssl
        crt-base /etc/ssl

        # Default ciphers to use on SSL-enabled listening sockets.
        # For more information, see ciphers(1SSL). This list is from:
        #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
        # ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:$
        ssl-default-bind-options no-sslv3
	# MultiProcess/Multithreading options
	#nbproc 1
 	nbthread 16
	cpu-map auto:1/1-16 0-15

defaults
        # Log configuration used by next frontend and backend declarations
        log     global
        # Connection mode http or tcp
        mode    http
        option  httplog
        option  dontlognull
	option  httpclose
	option  abortonclose
        timeout connect 1000
        timeout client  1000
        timeout server  1000
	maxconn 32768
        # maxconn 3000
	errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend proxy
        # Listener set on all ip adresses on the server and port 80, 443 for ht$
        bind 0.0.0.0:80
        bind :443 ssl <ssl .pem file location>
        # Responds to the client with a different URL to try and connect (For e$
        # unless { ssl_fc } is used to redirect only if the request comes over$
        # http-request redirect scheme https unless { ssl_fc }
        # use_backend backend if <condition_for_backend>
        # filters is the label used to define our default backend
	acl valid_http_method method GET POST
        default_backend filters

backend filters
        # Balance loading algorithm
        balance roundrobin
        # Enables cookie-based persistence (Session oriented)
	# cookie SERVERUSED insert indirect nocache
        # Runs health checks at /nop looking for status 500
        option httpchk GET /<check path>
        server server1  private.domain.net:80@ar check resolvers resolver init-addr libc inter 2000 fall 5        

resolvers resolver
	nameserver ns1 172.x.x.x:53 
	nameserver ns2 172.x.x.x:53
	hold valid 100
	resolve_retries 3
```

### HAProxy -vv
```
HA-Proxy version 2.3.9-53945bf 2021/03/30 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2022.
Known bugs: http://www.haproxy.org/bugs/bugs-2.3.9.html
Running on: FreeBSD 12.2-RELEASE-p6 FreeBSD 12.2-RELEASE-p6 GENERIC amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-string-plus-int -Wtype-limits -Wshift-negative-value -Wnull-dereference -DFREEBSD_PORTS
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_STATIC_PCRE=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1
  DEBUG   = 

Feature list : -EPOLL +KQUEUE -NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE +STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H +GETADDRINFO +OPENSSL -LUA -FUTEX +ACCEPT4 +CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1h-freebsd  22 Sep 2020
Running on OpenSSL version : OpenSSL 1.1.1h-freebsd  22 Sep 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace

```

### Uname -a

```FreeBSD freebsd 12.2-RELEASE-p6 FreeBSD 12.2-RELEASE-p6 GENERIC  amd64```

## If HAProxy crashed: Last outputs and backtraces

```
haproxy[<pid>]: backend filters has no server available!```

## Additional information (if helpful)

I'm using baton to benchmark the configuration and to test the connections

**Comment by capflam** [comment] 2021-06-04 13:16
The resolvers  has nothing to do with the health-checks. At least for now. It is a way to dynamically assign an address to a server using a fqdn. If the IP address announced by the DNS server changes, the server IP address will change too, regardless the server state. In the same way, if a DNS server announces several IP addresses for the same fqdn, one will be chosen regardless the server state. And the address is only changed if the response returned by the DNS server changes.

Here, you should add more servers with the same fqdn or use a server-template. The former solution may be used with `backup` keyword if you want to use only one server at a time.

Except if I misunderstood your issue, it is not a bug. It works as expected. However, you can create a feature request because this area will significantly change in the 2.5. And all inputs are welcome.

**Comment by wtarreau** [comment] 2021-06-09 06:15
To complete what Christopher said above, nowhere you mentioned in your reproducer that you changed a DNS entry, yet you expect that haproxy would discover some way that a new address is available. But definitely this address must be advertised by the DNS for this, and if the name configured for the server correctly changes from the old to the new address, there is no reason for it not to work.

**Comment by capflam** [comment] 2021-06-17 14:44
I'm closing this issue for now. If you though it is really a bug, feel free to reopen it.

**Closed as completed by capflam** 2021-06-17 14:44 UTC
Labels: type: bug, status: feedback required

**Comment by paul-civitas** [comment] 2023-10-09 20:20
Hello we're encountering this in the wild a lot, when we try and route haproxy traffic to a AWS RDS database.

I was hoping someone might have knowledge of how to handle this situation. Currently we need to reload haproxy whenever the RDS database ip address changes.

**Comment by lukastribus** [comment] 2023-10-09 20:36
@paul-civitas Tthere is an entire section in the documentation dedicated to "Server IP address resolution using DNS":

http://docs.haproxy.org/2.6/configuration.html#5.3


Read that, and if you gone through it all and it is still not clear, use the mailing list or community forum for support.

**Comment by paul-civitas** [comment] 2023-10-09 20:48
Thanks. Those docs are really good. They even mention the AWS use case specifically.

If I google: haproxy backend hostname ip change

One of the top results is this: https://haproxy.formilux.narkive.com/1DMrml37/make-notice-that-backend-server-ip-has-changed

Which is from 12 years ago! And doesn't have good up to date information. Something is up with google lately and it seems to not be giving good search results, specifically I've had a hard time getting up to date docs when googling as of recent. Maybe they decided keeping their search up to date wasn't a good use of money, and that if people spent longer looking for the correct answer they'd view more ads anyway.

**Comment by wtarreau** [comment] 2023-10-10 05:41
I've long been suspecting that their engine favors pages exhibiting some of their ads. Given that there are no ads on our docs, they're probably much less interesting to them ;-)
