### ISSUE TITLE
Haproxy 2.0 is corrupting Websocket payloads with htx enabled

### ISSUE THREAD

**Issue by robin-anil** [haproxy/haproxy#131] opened 2019-06-21 19:32 UTC
Here is what my config looks like, we are sending a binary frame from server to client and since it has protobuf serialized data, our JS monitoring has detected parse errors from the moment we switched to HAproxy 2.0. Turning off htx has fixed it. So it is definitely isolated to htx. We were running fine on 1.9.8 which in the default mode has htx disabled

```
defaults
    log global
    mode http
    compression algo gzip
    compression type text/html text/plain text/css application/javascript application/octet-stream application/json
    option httplog
    option dontlognull
    option redispatch
    option tcp-smart-accept
    option tcp-smart-connect
    option forwardfor if-none
    option splice-auto
    option socket-stats
    option http-buffer-request
    timeout check 5s
    timeout client 300s
    timeout tunnel 60000s
    timeout connect 20s
    timeout http-keep-alive 300s
    timeout http-request 30s
    timeout queue 20s
    timeout server 50s
    hash-balance-factor 125
    balance hdr(Cookie)
    hash-type consistent djb2
    default-server inter 5s fall 3 rise 1

backend ws
    reqidel ^.*x-webkit-deflate-frame.*
    timeout server 60000s
    option http-server-close
    # Health check path.
    option httpchk GET /monitorz/healthcheck?pretty=true
    http-response set-header X-backends api-server-ws
    #enter the IP of your application here
    server node-1 ws-server-1:80 maxconn 500 check
    server node-2 ws-server-1:80 maxconn 500 check
    server node-3 ws-server-1:80 maxconn 500 check
```

**Comment by capflam** [comment] 2019-06-21 19:44
Could you provide output of the command ``haproxy -vv`` ? 

And, if you're running the version 2.0.0, try to use the latest 2.0 snapshot: http://www.haproxy.org/download/2.0/src/snapshot/haproxy-ss-LATEST.tar.gz. Some fixes on the HTX could help.

If not, try to disable the compression or the splicing.

**Comment by Kishi85** [comment] 2019-07-02 14:59
I'm seeing a similar (reproducible) issue with websockets and htx when trying to proxy a Nextcloud setup with Collabora CODE (which uses websockets for its communication) on latest haproxy 2.0.1 with htx enabled. Without htx everything is working just fine. With htx enabled documents rendered with Collabora fail to load (either due to a timeout or with 400 Bad request). HTTP2 is currently fully disabled on both backend and frontend but the issue still remains with htx enabled. I can provide mitmproxy dumps for a good and a bad request case to a test file if necessary.

```
# haproxy -vv
HA-Proxy version 2.0.1-1ppa1~bionic 2019/06/27 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-O7_wB6/haproxy-2.0.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

**Comment by lukastribus** [comment] 2019-07-02 15:37
@Kishi85 please share your configuration also.

Can you guys try without `option http-buffer-request` in the configuration?

**Comment by Kishi85** [comment] 2019-07-02 15:59
Setting ```no option http-buffer-request``` in defaults doesn't make any difference.

Configuration (sanitized, only the affected backend and necessary ACLs) is as follows:
```
global
	nbproc 1
	nbthread 1
	stats socket /run/haproxy/admin.sock mode 600 level admin
	maxconn 64000
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	user haproxy
	group haproxy
	daemon
	# Restrict ssl backend connections to TLSv1.[012]
	ssl-default-server-options no-sslv3
	# As recommended by cipherli.st
	ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11
        ssl-default-bind-ciphers EECDH+AESGCM:EDH+AESGCM
        tune.ssl.default-dh-param 3072


defaults
	log	global
	mode	http
	balance roundrobin
	option  redispatch
	option	httplog
	option	dontlognull
	option  forwardfor except 127.0.0.1
	option http-use-htx
	no option http-buffer-request # Removing no breaks websockets
	timeout connect 5s # HAProxy recommends 5s as best-practice
	timeout client 900s # Windows default TCP idle timeout (15m)
        timeout server 900s # Windows default TCP idle timeout (15m)
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http


peers hapeers
	peer haproxy1 10.255.31.8:32023
	peer haproxy2 10.255.31.9:32023

frontend http-stats
	maxconn 100
	bind 	:::8080 v4v6
	acl path_haproxy path_beg -i /haproxy
	http-request redirect location /haproxy?stats if !path_haproxy
	default_backend statistics

frontend http-in
	maxconn 1900
	bind :::80 v4v6

	# HTTP header manipulation
	http-request del-header Proxy
	http-request redirect scheme https code 302 unless { ssl_fc }

	default_backend unspecified

frontend https-in
	maxconn 62000
	bind :::443 v4v6 ssl crt /etc/haproxy/ssl/ alpn http/1.1

	acl domain_cloud.localdomain hdr(host) -i cloud.localdomain
	tcp-request connection reject if { src_conn_cur(logger) ge 192 }
	tcp-request content track-sc0 src table logger

	# HTTP header manipulation
	http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
	http-request del-header Proxy
	http-request set-header X-Forwarded-Proto https
	# cloud
	use_backend cloud if domain_cloud.localdomain

	default_backend unspecified

backend logger
	stick-table type ip size 100k expire 3m store conn_rate(3s),gpc0,conn_cur,http_req_rate(10s),http_err_rate(10s) peers hapeers

backend statistics
	stats 	enable
	stats	refresh 30s
	stats	show-node
	stats	auth admin:password
	stats	uri /haproxy?stats
	# This can be used for testing the unavailable page
	errorfile 503 /etc/haproxy/unavailable.http

backend unspecified
	timeout tarpit 10s
	errorfile 503 /etc/haproxy/unspecified.http

backend cloud
	default-server maxconn 25 check check-ssl ssl verify none check-alpn http/1.1 alpn http/1.1
	retry-on none
	cookie SERVERID insert indirect nocache
	option httpchk HEAD /
	timeout check 20s
	errorfile 503 /etc/haproxy/unavailable.http
	server ipv6-cloud ipv6@2001:DB8:4648:3033::10:443 cookie cloud
	server ipv4-cloud ipv4@10.255.33.10:443 cookie cloud backup
```

**Comment by capflam** [comment] 2019-07-05 12:54
This issue should be fixed now. The patch was pushed and backported to 2.0. Thanks !

**Comment by Kishi85** [comment] 2019-07-08 10:29
This is working for me now with htx for http/1.1 on backend and either h2 or http/1.1 on frontend. 

However utilizing h2 on the backend connection still yields me a "400 Bad request" on the Websocket when using Collabora CODE via nginx. Connecting directly to the CODE instance via nginx using h2 works fine.

**Comment by capflam** [comment] 2019-07-08 19:29
@Kishi85, the WebSockets  are not supported on HTTP/2 by default because the support of 101 (Switching Protocols) informational status code was removed (see [RFC-7540 8.1.1](https://tools.ietf.org/html/rfc7540#section-8.1.1)).

There is an [extension to HTTP/2 to bootstrap WebSockets](https://tools.ietf.org/html/rfc8441). But HAProxy does not supported it yet. So for now, only h1-to-h1 WebSockets are supported. Feel free to add a feature request if you want. For now, it is not on the roadmap.

**Closed as completed** 2019-07-08 19:30 UTC
Labels: type: bug, severity: medium, status: fixed, subsystem: h1
