### ISSUE TITLE
haproxy 2.2-dev7: Segmentation fault with check and proxy-v2-options unique-id options

### ISSUE THREAD

**Issue by shimas** [haproxy/haproxy#640] opened 2020-05-20 09:38 UTC
## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.2-dev7 2020/05/05 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.0l  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.0l  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with gcc compiler version 6.3.0 20170516
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression

```
```
# uname -a
Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```
## What's the configuration?

```
listen server1
    bind x.x.x.x:443
    mode tcp
    unique-id-format %bi:%ci
    balance roundrobin
    server dev-ha x.x.x.x:443 source x.x.x.x send-proxy-v2 proxy-v2-options unique-id check
```

## Steps to reproduce the behavior   

1. To backend server add `check` option together with send-proxy-v2 proxy-v2-options unique-id

## Actual behavior

Haproxy crashes
```
haproxy[20612]: [NOTICE] 140/092453 (20612) : New worker #1 (20613) forked
haproxy[20612]: [NOTICE] 140/092453 (20612) : haproxy version is 2.2-dev7
haproxy[20612]: [NOTICE] 140/092453 (20612) : path to executable is /usr/sbin/haproxy
haproxy[20612]: [ALERT] 140/092453 (20612) : Current worker #1 (20613) exited with code 139 (Segmentation fault)
haproxy[20612]: [ALERT] 140/092453 (20612) : exit-on-failure: killing every processes with SIGTERM
haproxy[20612]: [WARNING] 140/092453 (20612) : All workers exited. Exiting... (139)
```

gdb
```
# gdb /usr/local/sbin/haproxy core
Reading symbols from /usr/local/sbin/haproxy...done.
[New LWP 23536]
[New LWP 23533]
[New LWP 23535]
[New LWP 23534]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `haproxy -f /etc/haproxy/haproxy.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  make_proxy_line_v2 (buf=0x7f76b06f1010 "\r\n\r\n", buf_len=2000000, srv=<optimized out>, remote=0x7f76a80023f0, strm=0x0) at src/connection.c:1474
1474			struct ist unique_id = stream_generate_unique_id(strm, &sess->fe->format_unique_id);
[Current thread is 1 (Thread 0x7f76b2a72700 (LWP 23536))]
```

## Expected behavior
Not to crash :)

## Do you have any idea what may have caused this?
There was already similar check option issues with previous haproxy versions. 

## Do you have an idea how to solve the issue?
No

**Comment by capflam** [comment] 2020-05-20 10:36
I confirm the bug. It is not related to the checks. I will investigate deeper but the bug seems to have been introduced by the commit cf6e0c8a83. I don't know if we should try to generate a unique id without a stream or not generate it when the stream is missing.

**Comment by TimWolla** [comment] 2020-05-20 10:46
@capflam For type “LOCAL” connections (i.e. checks) the proxy protocol v2 specification does not allow sending TLV (though I'd argue it should, because unique IDs would make sense for health checks). Without TLV you don't need to generate a unique ID. I'm not sure though what the current state of actually using the LOCAL type is with all the issues within non-HAProxy consumers.

Hope this helps in making a decision.

**Comment by capflam** [comment] 2020-05-20 12:39
@TimWolla , It also segfault with outgoing connections. For instance, with such line servers : 
```
 server srv A.B.C.D:443 send-proxy-v2 proxy-v2-options unique-id alpn h2,http/1.1 ssl
```

In [`conn_si_send_proxy()`](https://github.com/haproxy/haproxy/blob/master/src/stream_interface.c#L375) function, `make_proxy_line()` may be called with no stream. But It is a problem to generate a unique id. [`make_proxy_line_v2()`](https://github.com/haproxy/haproxy/blob/master/src/connection.c#L1473) expects to have a stream defined.

So it is not only a bug with the health checks.

**Comment by TimWolla** [comment] 2020-05-20 12:50
> In [`conn_si_send_proxy()`](https://github.com/haproxy/haproxy/blob/master/src/stream_interface.c#L375) function, `make_proxy_line()` may be called with no stream.

Ugh, yeah. I was aware of that, but was unable to trigger that condition within my tests (see: https://www.mail-archive.com/haproxy@formilux.org/msg36417.html) and subsequently forgot to account for that properly.

Can you clarify what part of your `server` line triggers that? With that additional information that not only checks are affected and me being the one that added that feature:

> I don't know if we should try to generate a unique id without a stream or not generate it when the stream is missing.

I would expect to receive a unique ID for all non-healthcheck connection. Thus I suspect the solution must be "generate unique ID without a stream" or "ensure there is always a stream when sending the proxy v2 header". However I don't know the implications of all that and which sample fetches might be unavailable without a stream.

**Comment by capflam** [comment] 2020-05-20 13:28
Because of the alpn, the mux on the backend side cannot be installed before sending the proxy protocol line. So `cs_get_first(conn)` returns NULL. But it this case, the connection context is the conn-stream. We can probably get the conn-stream this way in `conn_si_send_proxy()`:
```
   cs = (conn->mux ? cs_get_first(conn) : conn->ctx);
```

But it seems to be possible to send a proxy protocol line with no conn-stream. And for the checks, there is a conn-stream, but `cs->data` is not a stream-interface. So I'm puzzled.

I don't know the proxy protocol details. But is there any reason to use the stream to generate the unique id ? It is on purpose (to have the same id for the connection and the stream) or just to reuse existing code ?

**Comment by TimWolla** [comment] 2020-05-20 13:57
> I don't know the proxy protocol details. But is there any reason to use the stream to generate the unique id ? It is on purpose (to have the same id for the connection and the stream) or just to reuse existing code ?

During development I had no luck generating a string based off a log format without having a stream. So the reason is a combination of “re-use existing code” and “Tim did what appeared to work”.

To expand on that a bit: I wanted to re-use the existing `unique-id-format` setting for the Proxy v2 based unique ID. I considered it unnecessarily complicated for the administrator to configure the  unique ID format using different options. Why should the administrator have to care about the underlying implementation, when all they want is a unique ID? Especially since the existing option has a nice generic name that can easily be re-used and is also supported within the `defaults` section, allowing to configure a unique ID format that automatically works for all frontends, both HTTP as well as TCP based ones.

The fact that the Proxy v2 unique ID matches the unique ID of the first HTTP request on the connection is an implementation detail that was caused by the re-use of both the configuration as well as the internal storage and not something the administrator should rely on. I've specifically documented that it can result in unexpected unique IDs when being used in `mode http`.

**Comment by capflam** [comment] 2020-05-26 15:44
Ok, I finally got the time to fix this bug.

@TimWolla , thanks for your explanation. It indeed makes sense. Now, The unique ID is only generated for connections with a stream. So health checks will not have unique ID. The issue should be fixed.

**Closed as completed** 2020-05-26 15:46 UTC
Labels: type: bug, severity: medium, status: fixed

**Comment by TimWolla** [comment] 2020-05-26 15:59
@capflam Thank you for cleaning this up. Good that my mistake failed loudly for health checks, otherwise it would probably have failed silently for ALPN servers.

I will look into adding a reg test to ensure that unique IDs work with ALPN server (and continue to do so in the future).
