### ISSUE TITLE
Wolfssl doesn't support ocsp stapling?

### ISSUE THREAD

**Issue by zino7825** [haproxy/haproxy#2441] opened 2024-02-05 09:30 UTC
### Detailed Description of the Problem

I'm trying to switch to Wolfssl because of openssl 1.1.1 eol, but I checked the ocsp related error.

if use ocsp-updat on in crt-list
 'bind :443' in section 'frontend' : 'crt-list' : error processing line 1 in file '/opt/haproxy/ssl/certs/crt-list.txt' :  '/opt/haproxy/ssl/certs/xxx.pem' has an OCSP URI and OCSP auto-update is set to 'on' but an error occurred (maybe the issuer could not be found)'.

if include ocsp file 
 'bind :443' in section 'frontend' : 'crt-list' : error processing line 1 in file '/opt/haproxy/ssl/certs/crt-list.txt' :  '/opt/haproxy/ssl/certs/xxx.pem.ocsp' is present and activates OCSP but it is impossible to compute the OCSP certificate ID (maybe the issuer could not be found)'.

### Expected Behavior

Config check success 

### Steps to Reproduce the Behavior

1. wolfssl build with enable-ocsp 
2. haproxy build with wolfssl
3. use ocsp file or use ocsp-update on in crt-list 

### Do you have any idea what may have caused this?

I don't have any idea but it's related below code. 

https://github.com/haproxy/haproxy/blob/52cc45dfa5bb9db69697a2dc98d6fcc3216addb9/src/ssl_sock.c#L3340-L3356

### What is your configuration?

```haproxy
I had a problem both version ( 2.8.5 or 2.9.3 )
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.5-wolf 2023/12/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.5.html
Running on: Linux 5.11.0-1.el7.elrepo.x86_64 #1 SMP Sun Feb 14 18:10:38 EST 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = cc
  CFLAGS  = -O2 -march=native -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DTLS_TICKETS_NO=4
  OPTIONS = USE_OPENSSL_WOLFSSL=1 USE_LUA=1 USE_ZLIB=1 USE_QUIC=1 USE_PCRE=1 USE_PCRE_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL +OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT +PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION +QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : wolfSSL 5.6.6
Running on OpenSSL version : wolfSSL 5.6.6
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-16)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
       quic : mode=HTTP  side=FE     mux=QUIC  flags=HTX|NO_UPG|FRAMED
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
```
```


### Last Outputs and Backtraces

_No response_

### Additional Information

_No response_

**Comment by git001** [comment] 2024-02-05 09:46
please can you check if oscp and ocspstapling is enabled in wolfssl at build time?
https://www.wolfssl.com/documentation/manuals/wolfssl/chapter02.html#-enable-ocsp

In any case I think this issue could be a feature request as I can't find https://www.wolfssl.com/documentation/manuals/wolfssl/ssl_8h.html#function-wolfssl_setocsp_cb in the code .

**Comment by zino7825** [comment] 2024-02-05 10:05
@git001  I've checked that ocsp, ocsp-stapling, ocsp-stapling are enabled after wolfssl build.

I guess that wolfssl contains ocsp but seems to be unable to utilize ocsp function of wolfssl in the haproxy.

**Comment by wlallemand** [comment] 2024-02-05 14:55
The OCSP feature with wolfSSL is not supported yet. WolfSSL support with HAProxy is still experimental and not every reg-tests are working yet.

**Comment by wlallemand** [comment] 2024-07-02 15:34
I'm closing this, as this is a duplicate of #2535 and there are problems on WolfSSL side.

**Closed as completed** 2024-07-02 15:35 UTC
Labels: type: bug, status: duplicate, status: reviewed
