### ISSUE TITLE
Backends goes down and never goes back up since 2.2.9

### ISSUE THREAD

**Issue by Linkyu3** [haproxy/haproxy#1234] opened 2021-04-23 14:40 UTC
## Detailed description of the problem

Since version 2.2.9 we've had trouble with healthchecking on a particular set of backends.

Backends are behind a traefik cluster so we check the SSL traefik port on connect (here 6380) te be sure traefik is up and run a bunch of tcp-check in plain (as they don't work through ssl) on 6379 to be sure the service is UP.

Until 2.2.8 healthcheck worked normally and since 2.2.9 we've had backends randomly go down and never go back up, while service is still up and running, until all backends go down and the service with it. A reloading of Haproxy got the backends up again.

## Expected behavior

Healtchecks working.

## Steps to reproduce the behavior

Hard to reproduce but
1. Install FreeBSD 12 amd64 with Haproxy 2.2.9 to 2.2.11
2. Install a Docker cluster with traefik and KeyDB services
3. Put similar healthcheck in Haproxy configuration

## Do you have any idea what may have caused this?
no

## Do you have an idea how to solve the issue?
Downgrading to 2.2.8 solved the problem, we've tested with different checks but couldn't come to another work around.

## What is your configuration?

```
backend KeyDB_Cluster_6380_SSL
    mode tcp
    balance roundrobin
    timeout connect 3s
    timeout server 3h
    option srvtcpka
    option log-health-checks
    option tcp-check
    tcp-check connect port 6380
    tcp-check connect port 6379
    tcp-check send AUTH\ PASSWORD\r\n
    tcp-check expect string +OK
    tcp-check send PING\r\n
    tcp-check expect string +PONG
    tcp-check send QUIT\r\n
    tcp-check expect string +OK
    server KeyDB1_6380_TLS_Bridge_SNI IP:6380 ssl verify required ca-file /tmp/haproxy/ssl/5ea6fc3ec75ee6.86253890.calist sni str(keydb1.foo.bar) check inter 3s downinter 3s
    server KeyDB2_6380_TLS_Bridge_SNI IP:6380 ssl verify required ca-file /tmp/haproxy/ssl/5ea704185dc604.75395562.calist sni str(keydb2.foo.bar) check inter 3s downinter 3s
    server KeyDB3_6380_TLS_Bridge_SNI IP:6380 ssl verify required ca-file /tmp/haproxy/ssl/5ea7042fbaa326.16158317.calist sni str(keydb3.foo.bar) check inter 3s downinter 3s
```

## Output of `haproxy -vlv` and `uname -a`

```
Latest version :
HA-Proxy version 2.2.11-c58c4e4 2021/03/18 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.11.html
Running on: FreeBSD 12.1-RELEASE-p15-HBSD FreeBSD 12.1-RELEASE-p15-HBSD #0  5ee0fd2f334(stable/21.1)-dirty: Fri Mar 26 08:58:41 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64

After Downgrading :
HA-Proxy version 2.2.8-7bf78d7 2021/01/13 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.8.html
Running on: FreeBSD 12.1-RELEASE-p15-HBSD FreeBSD 12.1-RELEASE-p15-HBSD #0  5ee0fd2f334(stable/21.1)-dirty: Fri Mar 26 08:58:41 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP amd64

FreeBSD server 12.1-RELEASE-p15-HBSD FreeBSD 12.1-RELEASE-p15-HBSD #0  5ee0fd2f334(stable/21.1)-dirty: Fri Mar 26 08:58:41 CET 2021     root@sensey:/usr/obj/usr/src/amd64.amd64/sys/SMP  amd64
```

## If HAProxy crashed: Last outputs and backtraces
no crashes.

## Additional information (if helpful)

We've had this problem in our DEV and Production environnement (different servers but same configuration).

**Comment by capflam** [comment] 2021-04-23 17:56
There is nothing obvious between the 2.2.8 and the 2.2.9 that could explain this. Could you provide your logs please ?

**Comment by Linkyu3** [comment] 2021-04-27 09:00
Sorry for the late reply, had to make the conditions again to create some logs.

Sadly we can't see anything specific apart from  the healtchecks going down once, here are the logs : 

```
Startup :
2021-04-26T10:15:47	haproxy[34678]	Proxy KeyDB_Cluster_6380_SSL started.
2021-04-26T10:15:48	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB3_6380_TLS_Bridge_SNI succeeded, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 2ms, status: 3/3 UP.	
2021-04-26T10:15:48	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB2_6380_TLS_Bridge_SNI succeeded, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 2ms, status: 3/3 UP.	
2021-04-26T10:15:48	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB1_6380_TLS_Bridge_SNI succeeded, reason: Layer7 check passed, code: 0, info: "(tcp-check)", check duration: 2ms, status: 3/3 UP.	


then later :

2021-04-26T14:11:33	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB1_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 2 of tcp-check (connect port 6379)", check duration: 3006ms, status: 2/3 UP.
2021-04-26T14:11:39	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB1_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 1 of tcp-check (connect port 6380)", check duration: 3017ms, status: 1/3 UP.	 
2021-04-26T14:11:45	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB1_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 1 of tcp-check (connect port 6380)", check duration: 3013ms, status: 0/2 DOWN.	
2021-04-26T14:11:45	haproxy[41541]	Server KeyDB_Cluster_6380_SSL/KeyDB1_6380_TLS_Bridge_SNI is DOWN. 2 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.	 

2021-04-26T19:23:28	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB3_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 2 of tcp-check (connect port 6379)", check duration: 3019ms, status: 2/3 UP.
2021-04-26T19:23:34	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB3_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 1 of tcp-check (connect port 6380)", check duration: 3005ms, status: 1/3 UP.	 
2021-04-26T19:23:40	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB3_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 1 of tcp-check (connect port 6380)", check duration: 3013ms, status: 0/2 DOWN.	
2021-04-26T19:23:40	haproxy[41541]	Server KeyDB_Cluster_6380_SSL/KeyDB3_6380_TLS_Bridge_SNI is DOWN. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.	

2021-04-26T19:38:10	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB2_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 2 of tcp-check (connect port 6379)", check duration: 3015ms, status: 2/3 UP.	 
2021-04-26T19:38:16	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB2_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 1 of tcp-check (connect port 6380)", check duration: 3029ms, status: 1/3 UP.	 
2021-04-26T19:38:23	haproxy[41541]	Health check for server KeyDB_Cluster_6380_SSL/KeyDB2_6380_TLS_Bridge_SNI failed, reason: Layer7 timeout, info: " at step 1 of tcp-check (connect port 6380)", check duration: 3017ms, status: 0/2 DOWN.	
2021-04-26T19:38:23	haproxy[41541]	Server KeyDB_Cluster_6380_SSL/KeyDB2_6380_TLS_Bridge_SNI is DOWN. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.	 

2021-04-26T19:38:23	haproxy[41541]	backend KeyDB_Cluster_6380_SSL has no server available!
```

Logs are on Haproxy 2.2.11 but i had same behavior on 2.2.10 and 2.2.9.

**Comment by capflam** [comment] 2021-04-27 12:27
No problem. Thanks for the logs. L7 timeout is indeed pretty strange because it means a timeout expired on a connect rule but it is not a L4 timeout. Thus it means the connection is established. At this stage if a L7 timeout is reported, it means the timeout of the check task has expired. I guess it happens when the connection is immediately established. 

I'll try to provide you a patch to validate my theory. Because it also happens on a DEV environment, it should be possible to test it.

**Comment by Linkyu3** [comment] 2021-04-27 12:50
Indeed, this is strange. Apart from the Health check failing i found strange that there was no retry after the down status but i thought it might have been a misconfiguration from our part.

Thank you for your time!

**Comment by capflam** [comment] 2021-04-28 09:58
Could you try this patch, on top of the 2.2 ? 

[0001-BUG-MINOR-checks-Handle-synchronous-connect-when-a-t.patch.txt](https://github.com/haproxy/haproxy/files/6390929/0001-BUG-MINOR-checks-Handle-synchronous-connect-when-a-t.patch.txt)

**Comment by Linkyu3** [comment] 2021-04-29 12:00
Thanks a lot for your quick work!
I tried to patch on top of the 2.2-dev11 (as this was the closest version deployed by opnsense) but the patch didn't seem to pass the check : 
```
git apply --check ../haproxy.patch
error: patch failed: src/check.c:881
error: src/check.c: patch does not apply
```
I've had the same error with the dev12 that seems to be the latest version in the 2.2 branch.
I'm sorry if not doing the right thing, i'm kind of newbie on these subjects.

**Comment by capflam** [comment] 2021-04-29 12:24
I guess you mean 2.2.11 or 2.2.12. It is pretty strange because I can apply manually the patch on both. Could you confirm you really checkout the 2.2.11/2.2.12 and not the -dev11/-dev12 ?

**Comment by Linkyu3** [comment] 2021-05-05 14:42
Yep, sorry about that the tags in the github misslead me.
Took me some time to tame freebsd port patching lol, got to patch on top of the 2.2.13 and it seem to have solved the issue.
Healtcheck works perfectly and we had no down in 24h, thanks a lot!

**Comment by capflam** [comment] 2021-05-05 14:44
Ok thanks for the feedback ! I'll merge the fix soon.

**Comment by foobar4711** [comment] 2021-05-06 09:24
Hello,

yesterday we run into a similar issue.

All 6 webserver from Backend-Web are marked down and not coming back until restart of haproxy. But where still reachable.
Some other backends are unaffected from this issue during this time and working properly.
With the Alert "backend 'Backend-Web' has no server available!" I don't see any further availability checks on any Systems in any backend until restart! Feels like the check thread is crashed. At this time we are not able to reproduce this issue.


System:
```
CentOS Linux release 7.9.2009
Linux LB1 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

haproxy build from haproxy-2.2.13.tar.gz:
```
haproxy -vv
HA-Proxy version 2.2.13-5f3eb59 2021/04/02 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.13.html
Running on: Linux 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_LIBCRYPT=1 USE_CRYPT_H=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
Running on OpenSSL version : OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with network namespace support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.32 2012-11-30
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

Backend Configuration:
```
backend Backend-Web
        mode http
        balance roundrobin
        compression algo gzip
        compression offload
        option http-server-close
        stick-table type ip size 999k expire 1m store conn_rate(30s)
        acl rate_limit_whitelist src -f /etc/haproxy/whitelist-ips
        tcp-request content  track-sc2 src
        acl conn_rate_abuse  sc2_conn_rate gt 10
        acl mark_as_abuser   sc1_inc_gpc0 gt 3
        tcp-request content  reject if conn_rate_abuse !rate_limit_whitelist mark_as_abuser
        option httpchk GET /check.txt
        http-check expect string ONLINE
        default-server inter 2000 rise 2 fall 3
        server http1_1 212.222.150.141:80 check observe layer7
        server http1_2 212.222.150.142:80 check observe layer7
        server http1_3 212.222.150.143:80 check observe layer7
        server http1_4 212.222.150.144:80 check observe layer7
        server http1_5 212.222.150.145:80 check observe layer7
        server http1_6 212.222.150.146:80 check observe layer7
        option forwardfor
        source 0.0.0.0 usesrc clientip
        http-check disable-on-404
        default-server error-limit 1 on-error mark-down
        http-request set-header X-Forwarded-Port %[dst_port]
        http-request add-header X-Forwarded-Proto https if { ssl_fc }
```

Part of log:
```
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 2/3 UP.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 2/3 UP.
May  5 21:09:29 weblb2 haproxy: [WARNING] 124/210929 (59014) : Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 2/3 UP.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:29 weblb2 haproxy: [WARNING] 124/210929 (59014) : Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:29 weblb2 haproxy: [WARNING] 124/210929 (59014) : Health check for server Backend-Web/http1_3 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_1 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_1 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:29 weblb2 haproxy: [WARNING] 124/210929 (59014) : Health check for server Backend-Web/http1_1 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_1 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:29 localhost haproxy[59014]: Health check for server Backend-Web/http1_1 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:29 weblb2 haproxy: [WARNING] 124/210929 (59014) : Health check for server Backend-Web/http1_1 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_4 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_4 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 weblb2 haproxy: [WARNING] 124/210930 (59014) : Health check for server Backend-Web/http1_4 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_6 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_6 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 weblb2 haproxy: [WARNING] 124/210930 (59014) : Health check for server Backend-Web/http1_6 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_4 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_4 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 weblb2 haproxy: [WARNING] 124/210930 (59014) : Health check for server Backend-Web/http1_4 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_2 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_2 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 weblb2 haproxy: [WARNING] 124/210930 (59014) : Health check for server Backend-Web/http1_2 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_2 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_2 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 weblb2 haproxy: [WARNING] 124/210930 (59014) : Health check for server Backend-Web/http1_2 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_6 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 localhost haproxy[59014]: Health check for server Backend-Web/http1_6 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:30 weblb2 haproxy: [WARNING] 124/210930 (59014) : Health check for server Backend-Web/http1_6 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:31 localhost haproxy[59014]: Health check for server Backend-Web/http1_5 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:31 localhost haproxy[59014]: Health check for server Backend-Web/http1_5 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:31 weblb2 haproxy: [WARNING] 124/210931 (59014) : Health check for server Backend-Web/http1_5 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 1/3 UP.
May  5 21:09:31 localhost haproxy[59014]: Health check for server Backend-Web/http1_5 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:31 localhost haproxy[59014]: Health check for server Backend-Web/http1_5 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:31 weblb2 haproxy: [WARNING] 124/210931 (59014) : Health check for server Backend-Web/http1_5 failed, reason: Health analyze, info: "Detected 10 consecutive errors, last one was: L4 unsuccessful connection", status: 0/2 DOWN.
May  5 21:09:31 localhost haproxy[59014]: backend Backend-Web has no server available!
May  5 21:09:31 localhost haproxy[59014]: backend Backend-Web has no server available!
May  5 21:09:31 weblb2 haproxy: [ALERT] 124/210931 (59014) : backend 'Backend-Web' has no server available!
```

**Comment by capflam** [comment] 2021-05-06 14:33
@foobar4711, it is not the same issue. Here the servers are set to down because of true connection failures, because of `observer layer7` option.

**Comment by foobar4711** [comment] 2021-05-06 16:29
> @foobar4711, it is not the same issue. Here the servers are set to down because of true connection failures, because of `observer layer7` option.

The Server where down only for some seconds because of reaching connection limit. After that they working properly. 
But haproxy didnt check them again and as well dont check all the other server in different backends after backend-web has no servers. why stop haproxy checking the other bbackends? Only haproxy restart helps, after that everthing runs fine.

**Comment by capflam** [comment] 2021-05-07 08:37
There is indeed no reason to stop health-checks in this case. For servers in other backends and into the same backend. But it is a different issue. Are you sure both events are linked ? If there is a bug, I can understand that the health-check for a specific server may be influenced by the connection errors on this same server. But it is highly unlikely to have such interaction between different servers/backends. 

If it happens again, it could be a good idea to create a new issue with a full config and logs for all servers.

**Comment by capflam** [comment] 2021-05-07 10:16
@Linkyu3 I pushed the fix. It will be backported soon. Thanks !
@foobar4711, I finally found a bug that may explain what you observed. I push a fix too (ea8608371).

**Comment by capflam** [comment] 2021-05-07 10:16
oops. Closed to quickly :)

**Comment by Linkyu3** [comment] 2021-05-07 12:09
Merci Capitaine !

**Closed as completed** 2021-05-17 07:04 UTC
Labels: type: bug, subsystem: checks, status: fixed
