### ISSUE TITLE
src/h1_htx.c: possible null pointer dereference found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#286] opened 2019-09-18 07:45 UTC
```
*** CID 1405696:  Null pointer dereferences  (NULL_RETURNS)
/src/h1_htx.c: 421 in h1_copy_msg_data()
415                     dsthtx = (struct htx *)htxbuf->area;
416                     dsthtx->size = htxbuf->size - sizeof(*dsthtx);
417                     htx_reset(dsthtx);
418                     b_set_data(htxbuf, b_size(htxbuf));
419     
420                     blk = htx_add_blk(dsthtx, HTX_BLK_DATA, count);
>>>     CID 1405696:  Null pointer dereferences  (NULL_RETURNS)
>>>     Dereferencing "blk", which is known to be "NULL".
421                     blk->info += count;
422                     /* nothing else to do, the old buffer now contains an
423                      * empty pre-initialized HTX header
424                      */
425                     return count;
426             }
```

**Comment by capflam** [comment] 2019-09-18 08:35
It is a duplicate of #259. The code was just moved in another file.

**Closed as completed by capflam** 2019-09-18 08:35 UTC
Labels: status: duplicate
