### ISSUE TITLE
cli: patterns containing separators are truncated when adding an acl through the cli

### ISSUE THREAD

**Issue by ylafon** [haproxy/haproxy#400] opened 2019-12-06 04:37 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.10 2019/11/25 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = gcc
  CFLAGS  = -O2 -march=native -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_REGPARM=1 USE_OPENSSL=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```
```
Linux orcus 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) x86_64 GNU/Linux
```

## What's the configuration?

```
acl testacl req.hdr(X-Sample) -m sub -f /etc/haproxy/samplecheck.txt
```

## Steps to reproduce the behavior

1. let `/etc/haproxy/samplecheck.txt` have separators in in like `foo bar toto`
2. try to add another entry via cli like this: `echo "add acl /etc/haproxy/samplecheck.txt bar foo glop" | socat /var/run/haproxy.sock -
3. display the content of that acl `echo "show acl /etc/haproxy/samplecheck.txt" | socat /var/run/haproxy.sock -`

## Actual behavior

The output of 3. is currently:
`0x564265a4c000 foo bar toto`
`0x564265a4c040 bar`

So the first space in the pattern value on the cli is singling the end of the payload unlike the file case. 

## Expected behavior

The output of 3. is currently:
`0x564265a4c000 foo bar toto`
`0x564265a4c040 bar foo glop`

**Comment by wtarreau** [comment] 2019-12-06 04:44
Hi Yves!
I remember we had this limitation on the input, which is also what made us refrain from supporting some form of escaping. But I didn't notice it on output. And it is very interesting that we have this limitation because it simply proves that nobody can reliably use the output when there are spaces. I *think* that if you enter the new pattern using a backslash or place double-quotes around the word it will work, but I'm not 100% certain. However we can definitely change the output format to escape it since it's ambiguous already. In your output of expected behavior we could ver well have "foo bar" being the pattern to match in one case and "foo glop" the one to replace in the other case and there's no way to distinguish them right now.

**Comment by ylafon** [comment] 2019-12-06 04:49
I tried to single-quote or to \\ escape it and it failed, quotes and \\ are added to the value but do not modify the parsing (arguments seems to be parsed in advance before calling `cli_parse_add_map` which is used for both map and acl modification, and they have a different number of arguments.
`add acl <acl> <pattern>` so the expected behaviour is really to add "bar foo glop" and not a truncated version of it.

Unless the pattern check in the acl `acl testacl req.hdr(X-Sample) -m sub -f /etc/haproxy/samplecheck.txt` is actually not working as expected (ie: not able to match value with spaces)... I will test that, but it seems to work as-is.

**Comment by wtarreau** [comment] 2019-12-06 04:54
OK thanks so we must definitely do something on this one. Otherwise those using it to match user-agents for example cannot update them!

**Comment by ylafon** [comment] 2020-08-06 09:14
I guess this has been addressed at least partially (as it may not match other places in terms of parsing), so I suggest to close this issue and open a new one if the goal is to harmonise the way argument parsing is done in general.
Thanks!

**Comment by wlallemand** [comment] 2020-08-06 09:35
Thanks for the reminder, it was backported as far as 1.9. I'm closing the issue.

**Closed as completed** 2020-08-06 09:35 UTC
Labels: type: bug, status: fixed
