### ISSUE TITLE
Potential FD leak on reload (/dev/random and /dev/urandom)

### ISSUE THREAD

**Issue by mpitt** [haproxy/haproxy#314] opened 2019-10-07 13:18 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.7-1ppa1~bionic 2019/09/28 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-TXZjzi/haproxy-2.0.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

```
Linux ip-172-31-22-108 4.15.0-1039-aws #41-Ubuntu SMP Wed May 8 10:43:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    #  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5s
    timeout client  50s
    timeout server  50s
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

# typical frontend/backend pair, we have a few
frontend frontend1
    bind *:55123
    mode http
    option http-server-close
    default_backend backend1

backend backend1
    mode http
    balance roundrobin
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]
    option httpchk GET /status HTTP/1.1\r\nHost:checkhost
    
    server server1.example.com ip-172-31-20-15.example.com:1234
    

# typical listen section, we have a few
listen service1
    bind *:56345
    mode http
    balance roundrobin
    option forwardfor
    http-request set-header X-Forwarded-Port %[dst_port]

    
    server server2.example.com ip-172-31-20-23.example.com:4567
 ```

## Steps to reproduce the behavior

1. Start HAProxy
2. Find PID
3. Run `lsof -p $PID | grep -E '/dev/u?random' | wc -l`
4. Reload HAProxy (`/bin/kill -USR2 $PID`)
5. Repeat 3. and 4. a few times

## Actual behavior

The number of open file descriptors for `/dev/random` and `/dev/urandom` increases at every reload.

## Expected behavior

The number of FDs should remain constant across reloads.

## Do you have any idea what may have caused this?

Some FD leak, possibly in SSL-related code?

## Do you have an idea how to solve the issue?

**Comment by wlallemand** [comment] 2019-10-14 14:36
This problem should have been fixed with commit 56996da ("BUG/MINOR: mworker/ssl: close OpenSSL FDs on reload").

However, I see that you don't use any SSL in your configuration, it's possible that the random keep being initialized because of the SSL options in the global section and is not deinit because you don't have any backend/frontend which uses it.

**Comment by wlallemand** [comment] 2019-10-14 16:21
On my setup I can see several call to the getrandom() syscall I built with USE_OPENSSL=1 and without any openssl configuration, even in the global section. They disappear if I build without openssl.

Looks like it is really initialized by ssl_initialize_random() which is called by ssl_sock_prepare_srv_ctx() even when there is no SSL configuration. the ssl_sock_prepare_srv_ctx() is in fact called by the lua code src/hlua.c:7501.

The lua init code does reinit the global.ssl_used_backend variable to its previous value once it initialized the srv. The global.ssl_used_backend is used to compute the maxconn so we should be careful.

The problem is global.ssl_used_backend is still 0, but some SSL was initialized by the lua and it prevents the FD to be closed. Which mean that we always init the random when the binary is built with openssl AND the lua, and we never deinit it in the master process.

**Comment by wlallemand** [comment] 2019-10-15 12:19
[0001-BUG-MINOR-mworker-ssl-close-openssl-FDs-unconditiona.patch.txt](https://github.com/haproxy/haproxy/files/3729167/0001-BUG-MINOR-mworker-ssl-close-openssl-FDs-unconditiona.patch.txt)


Hello,

Could you try this patch? It should fix your issue.

Thanks

**Comment by mpitt** [comment] 2019-10-17 09:26
> [0001-BUG-MINOR-mworker-ssl-close-openssl-FDs-unconditiona.patch.txt](https://github.com/haproxy/haproxy/files/3729167/0001-BUG-MINOR-mworker-ssl-close-openssl-FDs-unconditiona.patch.txt)

I built 2.0.7 from source on Ubuntu 18.04 and reproduced the issue. After applying the patch I confirm the issue is fixed. Thanks!

**Closed as completed** 2019-10-17 09:41 UTC
Labels: type: bug, status: fixed
