### ISSUE TITLE
mqtt_is_valid converter seems to be broken

### ISSUE THREAD

**Issue by ertanden** [haproxy/haproxy#1310] opened 2021-06-28 11:01 UTC
### Detailed Description of the Problem

Tried to use the new MQTT aware HAProxy version 2.4.1 (using the docker image `haproxy:2.4.1`). However having a similar configuration like below causes the MQTT connections to be dropped and not accepted.

By just commenting out the line `tcp-request content reject unless { req.payload(0,0),mqtt_is_valid }` the connections can be established properly.

The behavior is the same for both MQTT versions 3.1.1 and 5.

### Expected Behavior

Only non-valid connections should be dropped and valid MQTT connections should be accepted.

### Steps to Reproduce the Behavior

Try connection with mosquitt_sub

### What is your configuration?

```haproxy
frontend fe_mqtt
  mode tcp  
  bind :1883

  # Reject connections that have an invalid MQTT packet
  tcp-request inspect-delay 10s
  tcp-request content reject unless { req.payload(0,0),mqtt_is_valid }

  default_backend be_mqtt

backend be_mqtt
  mode tcp

  server mosquitto1 10.1.0.6:1883
  server mosquitto2 10.1.0.7:1883
```
```


### Output of `haproxy -vv`

```plain
HAProxy version 2.4.1-1ce7d49 2021/06/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.1.html
Running on: Linux 4.14.214-160.339.amzn2.x86_64 #1 SMP Sun Jan 10 05:53:05 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by jmagnin** [comment] 2021-06-28 11:09
Hello,
you need an [inspect-delay](https://cbonte.github.io/haproxy-dconv/2.4/configuration.html#tcp-request%20inspect-delay) rule for this to work. This is not a bug.

Please use the forum or mailing list if you have a question, e.g. to get help with building a configuration to achieve your desired behavior.

The forum is at: https://discourse.haproxy.org/

The mailing list (no need to subscribe) is: haproxy@formilux.org
Subscribe to the list: haproxy+subscribe@formilux.org
Unsubscribe from the list: haproxy+unsubscribe@formilux.org

**Comment by ertanden** [comment] 2021-06-28 11:30
It doesn't work even with inspect-delay. Please see the updated configuration I tried. 

The example given in the announcement of `2.4` is not working: https://www.haproxy.com/blog/announcing-haproxy-2-4/

I still  think this needs to be checked, instead of saying `works as designed`.

**Comment by jmagnin** [comment] 2021-06-28 11:43
apologies  @ertanden , I can indeed reproduce with mosquitto_sub.
interestingly enough, the reg-test for the converter succeeds, so it needs to be fixed as well.
on needing inspect-delay or not, I am pretty sure it is needed to make sure the converter will always have the data it expects.

**Comment by capflam** [comment] 2021-06-28 12:23
Hum it is strange because `mqtt_is_valid` convert is waiting for complete packet before returning an error. And I'm unable to reproduce the error by hand by sending a 3.1.1 CONNECT message byte per byte.  So it may be a bug with the CONNECT message parser. Can you get a network capture please ?

**Comment by capflam** [comment] 2021-06-28 12:36
And after a quick test, Mosquitto is working for me. Did you use any specific options for your tests ?

**Comment by ertanden** [comment] 2021-06-28 12:37
So seems like could be related to lengths of ClientId, Username and Password. The following according to my tests.

```
works:

  mosquitto_sub -h localhost -p 1883 -d -t "test" -q 1 -i aaa -u aaa -P aaa
```

```
not working:

  mosquitto_sub -h localhost -p 1883 -d -t "test" -q 1 -i aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -u aaa -P aaa
  mosquitto_sub -h localhost -p 1883 -d -t "test" -q 1 -i aaa -u aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -P aaa
  mosquitto_sub -h localhost -p 1883 -d -t "test" -q 1 -i aaa -u aaa -P aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

I think MQTT >= 3.1.1  should support length of 65535 for ClientId, Username and Password.

**Comment by jmagnin** [comment] 2021-06-28 12:54
I did my tests with zero length clientid.
as per specs 

> MQTT-3.1.3-6: A Server MAY allow a Client to supply a ClientId that has a length of zero bytes. However if it does so the Server MUST treat this as a special case and assign a unique ClientId to that Client. It MUST then process the CONNECT packet as if the Client had provided that unique ClientId.

**Comment by capflam** [comment] 2021-06-28 12:55
@ertanden, Indeed, you're right. I found the bug. Thanks !

**Comment by ertanden** [comment] 2021-06-28 12:59
@capflam Please also consider what @jmagnin said. Also `empty` values for ClientId, Username and Password should be valid.

Currently this doesn't work as well;

```
mosquitto_sub -h localhost -p 1883 -d -t "test" -q 1
```

**Comment by capflam** [comment] 2021-06-28 13:08
Thanks, I'll take care to fix this case too.

**Comment by capflam** [comment] 2021-06-28 14:31
Thanks guys, it should be fixed now.

**Comment by jmagnin** [comment] 2021-06-28 14:34
thanks @capflam , confirmed working for zero length clientid.

**Comment by ertanden** [comment] 2021-06-28 15:55
Thanks @capflam. Appreciate the quick fix 👍

**Closed as completed** 2021-06-30 16:07 UTC
Labels: type: bug, status: fixed
