### ISSUE TITLE
HAProxy crashed with message "Thread 1 is about to kill the process."

### ISSUE THREAD

**Issue by infa-sanaik** [haproxy/haproxy#2613] opened 2024-06-21 17:58 UTC
### Detailed Description of the Problem

Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]: Thread 1 is about to kill the process.
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]: *>Thread 1 : id=0x7f17841d80c0 act=1 glob=0 wq=1 rq=0 tl=0 tlsz=0 rqsz=0
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:             stuck=1 prof=0 harmless=0 wantrdv=0
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:             cpu_ns: poll=228627474654400 now=228629880759600 diff=2406105200
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:             curr_task=0x261d4d0 (task) calls=1434736 last=0
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:               fct=0x535860(main+0x110540) ctx=0x23c1920
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:             call trace(16):
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:             |       0x5d5c37 [48 83 c4 10 5b 5d 41 5c]: wdt_handler+0x107/0x114
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:             | 0x7f178377bcf0 [48 c7 c0 0f 00 00 00 0f]: libpthread:+0x12cf0
Jun  9 22:35:21 HOST_REMOVED haproxy[1691719]:             |       0x535ad9 [89 43 2c 48 8b 83 d8 01]: main+0x1107b9
Jun  9 22:35:21 HOST_REMOVED haproxy[84492]: [NOTICE]   (84492) : haproxy version is 2.4.17-9f97155
Jun  9 22:35:21 HOST_REMOVED haproxy[84492]: [NOTICE]   (84492) : path to executable is /usr/sbin/haproxy
Jun  9 22:35:21 HOST_REMOVED haproxy[84492]: [ALERT]    (84492) : Current worker #4 (1691719) exited with code 134 (Aborted)
Jun  9 22:35:21 HOST_REMOVED haproxy[84492]: [ALERT]    (84492) : exit-on-failure: killing every processes with SIGTERM
Jun  9 22:35:22 HOST_REMOVED haproxy[84492]: [ALERT]    (84492) : Current worker #1 (1691716) exited with code 143 (Terminated)
Jun  9 22:35:22 HOST_REMOVED haproxy[84492]: [ALERT]    (84492) : Current worker #2 (1691717) exited with code 143 (Terminated)
Jun  9 22:35:22 HOST_REMOVED haproxy[84492]: [ALERT]    (84492) : Current worker #3 (1691718) exited with code 143 (Terminated)
Jun  9 22:35:22 HOST_REMOVED haproxy[84492]: [WARNING]  (84492) : All workers exited. Exiting... (134)
Jun  9 22:35:22 HOST_REMOVED systemd[1]: haproxy.service: Main process exited, code=exited, status=134/n/a
Jun  9 22:35:22 HOST_REMOVED systemd[1]: haproxy.service: Failed with result 'exit-code'.

### Expected Behavior

HAProxy should not crash

### Steps to Reproduce the Behavior

Not able to reproduce.

### What is your configuration?

```haproxy
We are using nbproc 4 with max threads 6000
```

### Output of `haproxy -vv`

```plain
$ haproxy -vv
HAProxy version 2.4.17-9f97155 2022/05/13 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.17.html
Running on: Linux 4.18.0-513.11.1.el8_9.x86_64 #1 SMP Wed Jan 10 22:58:54 UTC 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =
 
Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING
 
Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
 
Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0 20210514 (Red Hat 8.5.0-20)
 
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
 
Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG
 
Available services : prometheus-exporter
Available filters :
[SPOE] spoe
[CACHE] cache
[FCGI] fcgi-app
[COMP] compression
[TRACE] trace
```

**Comment by capflam** [comment] 2024-06-24 05:51
The 2.4.17 is outdated. First of all, you must upgrade. 

> We are using nbproc 4 with max threads 6000

What does "max threads" mean here ? there is no way to configure a maximum number of threads, just the number of running threads. And 6000 is a fancy value. If you still observe crashes after the upgrade, please share your configuration.

**Comment by capflam** [comment] 2024-06-26 13:20
I'm closing the issue for now because the latest 2.4 must be tested first before. If the issue is still there, please reopen it. Thanks !

**Closed as not planned by capflam** 2024-06-26 13:20 UTC
Labels: type: bug, status: feedback required
