### ISSUE TITLE
Admin socket command parser does not handle spaces

### ISSUE THREAD

**Issue by bitfehler** [haproxy/haproxy#534] opened 2020-03-05 11:36 UTC
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.1.3 2020/02/12 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.3.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -march=x86-64 -mtune=generic -O2 -pipe -fno-plt
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[TRACE] trace
	[COMP] compression
```
```
Linux tryptophan 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux
```

## What's the configuration?

```
global
    log         127.0.0.1 local0
    pidfile     ./haproxy.pid
    stats socket /tmp/haproxy.sock level admin

frontend  main
    bind :5000
    mode                 http
    log                  global
    option               httplog
    option               dontlognull
    option               http_proxy
    option forwardfor    except 127.0.0.0/8
    timeout              client  30s

    acl url_static       path_beg       -f acl.lst

    use_backend static          if url_static
    default_backend             app

backend static
    mode        http
    http-request deny deny_status 500

backend app
    mode        http
    http-request deny deny_status 403
```

## Steps to reproduce the behavior

1. `touch acl.lst && haproxy -f ./haproxy.cfg` where `haproxy.cfg` is above config, works as user
2. `echo 'add acl acl.lst with\ space' | socat - UNIX-CONNECT:/tmp/haproxy.sock`
3. `echo 'show acl acl.lst' | socat - UNIX-CONNECT:/tmp/haproxy.sock`

## Actual behavior

```
$ echo 'show acl acl.lst' | socat - UNIX-CONNECT:/tmp/haproxy.sock
0x557cac392280 with
```

## Expected behavior

```
$ echo 'show acl acl.lst' | socat - UNIX-CONNECT:/tmp/haproxy.sock
0x557cac392280 with spaces
```

## Do you have any idea what may have caused this?

See next item.

## Do you have an idea how to solve the issue?

Please also see [this thread](https://www.mail-archive.com/haproxy@formilux.org/msg34827.html) on the mailing list for more details and Willy's proposed solution.

Sorry for taking so long to create the issue. Note that I used `path_beg` here because I copied from some example config, I know it's non-sensical, but we acutally use this for user agent matching.

**Comment by wtarreau** [comment] 2020-03-05 14:49
Hi Conrad,

indeed, thanks for creating the entry. It was also reported by another person a few months ago, again related to the user-agent. I'd like to see this addressed for 2.2, otherwise we're constantly postponing. I recently stole some code from the config tokenizer to update make_arg_list and it proved to be quite easy to do, I think that should really be done this way. I'm marking this as must fix.

**Comment by wlallemand** [comment] 2020-06-19 14:30
This is a duplicate of issue #400. A fix was pushed in the git today.

**Comment by TimWolla** [comment] 2020-06-19 22:09
I'll mark it as such.

Duplicate of #400

**Closed as completed** 2020-06-19 22:10 UTC
Labels: type: bug, status: duplicate
