### ISSUE TITLE
2.0.5 - external-check failed with PROCOUT when nbproc = 1

### ISSUE THREAD

**Issue by nightguide** [haproxy/haproxy#247] opened 2019-09-01 15:19 UTC
## Log from haproxy 2.0.5

```
сен 01 09:51:22 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095122 (28426) : Health check for server mysql_master_backend/atlas-nsk-mysqldb-new-01 succeeded,
сен 01 09:51:24 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095124 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-02 succeeded, re
сен 01 09:51:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095125 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-03 succeed
сен 01 09:51:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095125 (28426) : Health check for backup server mysql_readonly_backend/atlas-nsk-mysqldb-new-01 su
сен 01 09:51:26 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095126 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-04 succeed
сен 01 09:51:27 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095127 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-07 succeed
сен 01 09:51:28 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095128 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-08 succeed
сен 01 09:51:29 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095129 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-09 succeed
сен 01 09:51:30 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095130 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-05 succeeded
сен 01 09:51:31 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095131 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-06 succeeded
сен 01 09:52:57 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095257 (28426) : kill 28612
сен 01 09:52:57 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095257 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-04 failed,
сен 01 09:52:58 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095258 (28426) : kill 28614
сен 01 09:52:58 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095258 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-07 failed,
сен 01 09:52:59 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095259 (28426) : kill 28618
сен 01 09:52:59 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095259 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-08 failed,
сен 01 09:53:00 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095300 (28426) : kill 28622
сен 01 09:53:00 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095300 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-09 failed,
сен 01 09:53:01 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095301 (28426) : kill 28626
сен 01 09:53:01 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095301 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-05 failed, r
сен 01 09:53:02 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095302 (28426) : kill 28630
сен 01 09:53:02 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095302 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-06 failed, r
сен 01 09:53:05 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095305 (28426) : kill 28633
сен 01 09:53:05 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095305 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-02 failed, reaso
сен 01 09:53:06 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095306 (28426) : kill 28637
сен 01 09:53:06 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095306 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-03 failed,
сен 01 09:53:17 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095317 (28426) : kill 28643
сен 01 09:53:17 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095317 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-04 failed,
сен 01 09:53:18 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095318 (28426) : kill 28645
сен 01 09:53:18 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095318 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-07 failed,
сен 01 09:53:19 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095319 (28426) : kill 28647
сен 01 09:53:19 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095319 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-08 failed,
сен 01 09:53:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095320 (28426) : kill 28649
сен 01 09:53:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095320 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-09 failed,
сен 01 09:53:21 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095321 (28426) : kill 28651
сен 01 09:53:21 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095321 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-05 failed, r
сен 01 09:53:21 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095321 (28426) : kill 28653
сен 01 09:53:21 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095321 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-06 failed, r
сен 01 09:53:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095325 (28426) : kill 28655
сен 01 09:53:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095325 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-02 failed, reaso
сен 01 09:53:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095325 (28426) : kill 28635
сен 01 09:53:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095325 (28426) : Health check for backup server mysql_readonly_backend/atlas-nsk-mysqldb-new-01 fa
сен 01 09:53:26 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095326 (28426) : kill 28657
сен 01 09:53:26 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095326 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-03 failed,
сен 01 09:53:37 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095337 (28426) : kill 28660
сен 01 09:53:37 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095337 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-04 failed,
сен 01 09:53:38 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095338 (28426) : kill 28662
сен 01 09:53:38 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095338 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-07 failed,
сен 01 09:53:39 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095339 (28426) : kill 28664
сен 01 09:53:39 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095339 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-08 failed,
сен 01 09:53:40 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095340 (28426) : kill 28666
сен 01 09:53:40 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095340 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-09 failed,
сен 01 09:53:41 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095341 (28426) : kill 28668
сен 01 09:53:41 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095341 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-05 failed, r
сен 01 09:53:41 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095341 (28426) : kill 28670
сен 01 09:53:41 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095341 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-06 failed, r
сен 01 09:53:45 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095345 (28426) : kill 28672
сен 01 09:53:45 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095345 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-02 failed, reaso
сен 01 09:53:46 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095346 (28426) : kill 28674
сен 01 09:53:46 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095346 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-03 failed,
сен 01 09:53:57 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095357 (28426) : kill 28676
сен 01 09:53:57 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095357 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-04 failed,
сен 01 09:53:58 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095358 (28426) : kill 28678
сен 01 09:53:58 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095358 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-07 failed,
сен 01 09:53:59 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095359 (28426) : kill 28680
сен 01 09:53:59 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095359 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-08 failed,
сен 01 09:54:00 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095400 (28426) : kill 28682
сен 01 09:54:00 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095400 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-09 failed,
сен 01 09:54:00 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095400 (28426) : kill 28684
сен 01 09:54:00 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095400 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-05 failed, r
сен 01 09:54:01 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095401 (28426) : kill 28686
сен 01 09:54:01 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095401 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-06 failed, r
сен 01 09:54:05 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095405 (28426) : kill 28688
сен 01 09:54:05 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095405 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-02 failed, reaso
сен 01 09:54:06 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095406 (28426) : kill 28692
сен 01 09:54:06 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095406 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-03 failed,
сен 01 09:54:17 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095417 (28426) : kill 28694
сен 01 09:54:17 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095417 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-04 failed,
сен 01 09:54:17 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095417 (28426) : Server mysql_readonly_backend/atlas-nsk-mysqldb-slave-04 is DOWN. 5 active and 1
сен 01 09:54:18 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095418 (28426) : kill 28696
сен 01 09:54:18 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095418 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-07 failed,
сен 01 09:54:18 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095418 (28426) : Server mysql_readonly_backend/atlas-nsk-mysqldb-slave-07 is DOWN. 4 active and 1
сен 01 09:54:19 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095419 (28426) : kill 28712
сен 01 09:54:19 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095419 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-08 failed,
сен 01 09:54:19 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095419 (28426) : Server mysql_readonly_backend/atlas-nsk-mysqldb-slave-08 is DOWN. 3 active and 1
сен 01 09:54:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095420 (28426) : kill 28715
сен 01 09:54:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095420 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-09 failed,
сен 01 09:54:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095420 (28426) : Server mysql_readonly_backend/atlas-nsk-mysqldb-slave-09 is DOWN. 2 active and 1
сен 01 09:54:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095420 (28426) : kill 28718
сен 01 09:54:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095420 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-05 failed, r
сен 01 09:54:20 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095420 (28426) : Server mysql_report_backend/atlas-nsk-mysqldb-slave-05 is DOWN. 1 active and 0 ba
сен 01 09:54:21 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095421 (28426) : kill 28720
сен 01 09:54:21 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095421 (28426) : Health check for server mysql_report_backend/atlas-nsk-mysqldb-slave-06 failed, r
сен 01 09:54:21 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095421 (28426) : Server mysql_report_backend/atlas-nsk-mysqldb-slave-06 is DOWN. 0 active and 0 ba
сен 01 09:54:21 atlas-nsk-haproxy-01 haproxy[22578]: [ALERT] 243/095421 (28426) : backend 'mysql_report_backend' has no server available!
сен 01 09:54:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095425 (28426) : kill 28726
сен 01 09:54:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095425 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-02 failed, reaso
сен 01 09:54:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095425 (28426) : Server mysql_readonly_backend/atlas-nsk-mysqldb-02 is DOWN. 1 active and 1 backup
сен 01 09:54:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095425 (28426) : kill 28690
сен 01 09:54:25 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095425 (28426) : Health check for backup server mysql_readonly_backend/atlas-nsk-mysqldb-new-01 fa
сен 01 09:54:26 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095426 (28426) : kill 28728
сен 01 09:54:26 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095426 (28426) : Health check for server mysql_readonly_backend/atlas-nsk-mysqldb-slave-03 failed,
сен 01 09:54:26 atlas-nsk-haproxy-01 haproxy[22578]: [WARNING] 243/095426 (28426) : Server mysql_readonly_backend/atlas-nsk-mysqldb-slave-03 is DOWN. 0 active and 1
```

## Output of `haproxy -vv` and `uname -a`

```
root@atlas-nsk-qa2-mysqldb-01:/# haproxy -vv
HA-Proxy version 2.0.5-1ppa1~xenial 2019/08/16 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.21 2016-01-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace


root@atlas-nsk-qa2-mysqldb-01:/# uname -a
Linux atlas-nsk-qa2-mysqldb-01 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
# _version=20

defaults
  mode tcp
  log global
  option tcplog
  option dontlognull
  timeout connect 180s
  timeout client 1h
  timeout server 1h

global
  daemon
  master-worker
  external-check
  nbthread 8
  maxconn 80000
  stats socket /var/run/admin.sock mode 660 level admin
  stats timeout 60s
  log /dev/log local0 warning alert
  log /dev/log local1 warning alert
  user haproxy
  group haproxy
  #     cpu-map auto:all   0-7
  #     nbthread        2
  #     cpu-map         1 0
  #     cpu-map         2 1
  #     cpu-map         3 2
  #     cpu-map         4 3

userlist STATSUSERS
  group admin users admin
  user admin insecure-password admin
  user stats insecure-password stats

userlist dataplane-api
  user dataplaneapi password $5$uF2eSnwMxX9fEGqV$pP1eWASJw6aOPAl8YZ/A5CHRhv5aMVmY5E9k8Li8b02

frontend mysql_master
  mode tcp
  bind :3308
  log global
  option tcplog
  default_backend mysql_master_backend
  option tcpka

frontend mysql_readonly
  mode tcp
  bind :3309
  log global
  option tcplog
  default_backend mysql_readonly_backend
  option tcpka

frontend mysql_report
  mode tcp
  bind :3310
  log global
  option tcplog
  default_backend mysql_report_backend
  option tcpka

backend mysql_master_backend
  balance roundrobin
  option redispatch
  default-server rise 2 fall 3
  server atlas-nsk-mysqldb-new-01 192.168.0.51:3308 weight 1 check inter 15s rise 2 fall 3 maxconn 10000
  option log-health-checks

backend mysql_readonly_backend
  balance roundrobin
  option redispatch
  option external-check
  external-check path "/usr/bin:/bin:/opt/bin"
  external-check command mysql_lag.py
  default-server rise 2 fall 3
  server atlas-nsk-mysqldb-new-01 192.168.0.51:3308 backup weight 1 check inter 30s rise 2 fall 3 maxconn 10000
  server atlas-nsk-mysqldb-02 192.168.1.85:3309 weight 150 check inter 10s rise 2 fall 3 maxconn 10000
  server atlas-nsk-mysqldb-slave-02 192.168.1.195:3309 check maxconn 10000 weight 100 inter 1000
  server atlas-nsk-mysqldb-slave-03 192.168.1.165:3309 weight 100 check inter 10s rise 2 fall 3 maxconn 10000
  server atlas-nsk-mysqldb-slave-04 192.168.0.15:3309 weight 100 check inter 10s rise 2 fall 3 maxconn 10000
  server atlas-nsk-mysqldb-slave-07 192.168.0.251:3309 weight 100 check inter 10s rise 2 fall 3 maxconn 10000
  server atlas-nsk-mysqldb-slave-08 192.168.1.3:3309 weight 100 check inter 10s rise 2 fall 3 maxconn 10000
  server atlas-nsk-mysqldb-slave-09 192.168.1.4:3309 weight 100 check inter 10s rise 2 fall 3 maxconn 10000
  option log-health-checks
  # server atlas-nsk-mysqldb-slave-05     192.168.1.179:3309 weight 50 check inter 10s rise 2 fall 3 maxconn 10000

backend mysql_report_backend
  balance roundrobin
  option redispatch
  option external-check
  external-check path "/usr/bin:/bin:/opt/bin"
  external-check command mysql_lag.py
  default-server rise 2 fall 3
  server atlas-nsk-mysqldb-slave-05 192.168.1.179:3309 weight 100 check inter 10s rise 2 fall 3 maxconn 10000
  server atlas-nsk-mysqldb-slave-06 192.168.1.213:3309 weight 100 check inter 10s rise 2 fall 3 maxconn 10000
  option log-health-checks
  #     server srv-mysqldb-slave-03.cdek.ru     192.168.1.165:3309 backup weight 50 check inter 10s rise 2 fall 3 maxconn 10000

listen admin_page
  bind 0.0.0.0:9600
  mode http
  stats enable
  stats refresh 10s
  stats uri /
  acl AuthOkay_ReadOnly http_auth(STATSUSERS)
  acl AuthOkay_Admin http_auth_group(STATSUSERS) admin
  stats http-request auth realm admin_page unless AuthOkay_ReadOnly

program api
  command /usr/local/sbin/dataplaneapi --host 0.0.0.0 --port 5555 --haproxy-bin /usr/sbin/haproxy --config-file /etc/haproxy/haproxy.cfg --reload-cmd "kill -SIGUSR2 1" --reload-delay 5 --userlist dataplane-api
  no option start-on-reload
  #####

```

## My External Check Script on Python

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import mysql.connector

DEFAULT_MAX_LAG = 300

CLUSTER_ADDR = sys.argv[1]
CLUSTER_PORT = sys.argv[2]
PEER_ADDR = sys.argv[3]
PEER_PORT = sys.argv[4]

DB_USERNAME = "replica"
DB_PASSWORD = "pD3kYV3JWg7ek8$"

CLUSTERS = {
    '3309': 100,
    '3310': 86400
}

def slave_status(host, port, username, password):
    result = {}
    dbconn = mysql.connector.connect(host=host, port=port, user=username, passwd=password)
    cursor = dbconn.cursor()
    cursor.execute("SHOW SLAVE STATUS")
    rawdata = cursor.fetchall()
    if not rawdata:
        result['is_master'] = True
    else:
        data = list(rawdata[0])
        result['is_master'] = False
        result['Seconds_Behind_Master'] = data[32]
        result['Last_IO_Errno'] = data[34]
        result['Last_SQL_Errno'] = data[36]

    cursor.close()
    dbconn.close()

    return result

def main():
    lag = CLUSTERS.get(CLUSTER_PORT, DEFAULT_MAX_LAG)
    status = slave_status(PEER_ADDR, PEER_PORT, DB_USERNAME, DB_PASSWORD)

    if status['is_master']:
#        print('master')
        sys.exit(0)
    elif (status['Seconds_Behind_Master'] < lag) and (status['Last_IO_Errno'] == 0) and (status['Last_SQL_Errno'] == 0):
#        print(status['Seconds_Behind_Master'])
        sys.exit(0)
    else:
#        print('1')
        sys.exit(1)

if __name__ == '__main__':
    main()

```

## Steps to reproduce the behavior

1. Run haproxy with above config
2. Give a load to the frontend 'mysql_readonly'
3. look through hatop -s /var/run/haproxy/admin.sock and make sure that when loading the load, the external backend check failed with PROCOUT
4. If set nbproc >1 , health checks work correctly, but i want using nbthread but not nbproc

## Actual behavior

When haproxy 2.0.5 runs in single process mode and uses nbthread, there are problems with external checks. If there is a load, after one minute all checks failed with PROCOUT. p.s See the logs above.
If you set nbproc> 1, for example 4. Then everything works OK and the statuses are updated with PROCOK.

with single process and nbthread = 8 ( 1 CPU = 1 nbthread , i have 8 virtual cpu)

![image](https://user-images.githubusercontent.com/37993560/64078525-0a6e2800-cd06-11e9-8505-e7b94ad22a7d.png)

with nbproc = 4

![image](https://user-images.githubusercontent.com/37993560/64078538-2c67aa80-cd06-11e9-9529-4a6796d91786.png)

## Expected behavior

I want external-check to work just as well in single process mode as in multi-process mode

## Do you have any idea what may have caused this?

I don’t know, maybe this is a bug?

## Do you have an idea how to solve the issue?

I don't know((((

**Comment by lukastribus** [comment] 2019-09-01 19:20
This is a duplicate of #141

**Closed as completed by lukastribus** 2019-09-01 19:20 UTC
Labels: type: bug, status: duplicate
