### ISSUE TITLE
Connection reset/PR_CONNECT_RESET_ERROR in 2.2.11

### ISSUE THREAD

**Issue by JonnyRoller** [haproxy/haproxy#1199] opened 2021-03-25 19:25 UTC
## Detailed description of the problem

Users experience "connection reset" and PR_CONNECT_RESET_ERROR browser messages intermittently. I would occasionally see this on the "Statistics Report" page as well. Also, SSL Labs tests (https://www.ssllabs.com/ssltest/index.html) would fail to produce a complete report on the SSL certs.

## Expected behavior

No "connection reset" or PR_CONNECT_RESET_ERROR browser message; completed SSL Labs reports.

## Steps to reproduce the behavior

The problems were intermittent. However, the SSL Labs tests always failed to complete.

## Do you have an idea how to solve the issue?

Downgrading to 2.2.8 (I couldn't find packages for 9 or 10) has corrected the problems.

## What is your configuration?

```
global
  # Logging... just for debugging
  # See also /etc/rsyslog.conf and /etc/logrotate.d/haproxy
  # Both enabled
  log 127.0.0.1 local0 info
  log 127.0.0.1 local1

  # 10,000 connections... not sure what the max should be
  maxconn 10000
  daemon

  # Default ciphers to use on SSL-enabled listening sockets.
  # For more information, see ciphers(1SSL).

  # Passes ssllabs.com tests but does not work on Windows XP, SP3
  # ssl-default-bind-ciphers kEECDH+aRSA+AES:kRSA+AES:+AES256:RC4-SHA:!kEDH:!LOW:!EXP:!MD5:!aNULL:!eNULL:!RC4
  # ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11

        # From https://ssl-config.mozilla.org/#server=haproxy&version=2.2&config=intermediate&openssl=1.1.1d&guideline=5.6
  ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES
256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
  ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

  ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-A
ES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
  ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
  ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

  tune.ssl.default-dh-param 2048
  crt-base /etc/haproxy
  ca-base /etc/haproxy

  # To help prevent 502 errors; default is 16384
  tune.bufsize 32768

  # Send commands via socket
  stats socket /var/run/haproxy.sock mode 600 level admin
  stats timeout 2m

defaults
  log     global

  # These are HTTP connections
  mode    http

  # Use the cookie named "proxy" to stick to a backend server
  cookie proxy insert

  # Again, just for debugging
  # Enabled
  option  httplog
  option  dontlognull

  # Adds a HTTP_X_FORWARDED_FOR header the includes the client's real IP address; needed by lib.php
  option  forwardfor

  # Keep client connections open to "pipeline" (keep-alive) traffic
  # option  http-server-close

  # Timeouts
  timeout connect 20s
  timeout http-request 20s                  # Keep low to prevent slow loris attacks; unclear if this affects POSTs
  timeout http-keep-alive 10s
  timeout server 180s
  timeout client 180s
  timeout queue 180s

  # If the web server goes down between health checks, this will retry the request on the other web server
  option redispatch

  # Enable HAProxy web stats
  stats   enable
  stats   refresh 10s
  stats   auth xxxxx:xxxxx

  stats   uri /xxxxx.html
  # stats   uri /simulate-failure.html

  # Load balance based on source IP address
  balance source

  # Where to check for the health of our servers
  option httpchk HEAD /health.php?cyan HTTP/1.0

  # See http://blog.haproxy.com/2014/05/26/haproxy-and-http-errors-408-in-chrome/
  errorfile 408 /dev/null

  # Error handlers
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

# Inbound connections
frontend server_frontend
  bind    *:80
  maxconn 10000
  default_backend server_backend

  # For logging the host name
  capture request header Host len 30

  # Limits
  stick-table type ip size 100k expire 30s store conn_cur,conn_rate(5s)
  tcp-request connection reject if { src_conn_cur ge 10 }                  # 10 open connection per IP address max
  tcp-request connection reject if { src_conn_rate ge 80 }                 # 80 connections max in 5 seconds
  tcp-request connection track-sc1 src

  # Certificates are all listed in certificates.txt
  bind *:443 strict-sni ssl crt-list /etc/haproxy/certificates.txt

  # So we can attach an SSL cert and still force servers to handle request
  acl azure_acl hdr_end(host) -i xxxx.com hdr_end(host) -i xxxx.com
  use_backend azure_backend if azure_acl

  acl blue_acl hdr_end(host) -i xxxx.com hdr_end(host) -i xxxx.com
  use_backend blue_backend if blue_acl

  # Route Lets Encrypt security challenge to main server
  acl letsencrypt_acl path_beg /.well-known/acme-challenge
  use_backend azure_backend if letsencrypt_acl

  # Force eleap traffic though main server
  acl eleapsaml_test_acl hdr(host) -i xxxx.com
  use_backend azure_backend if eleapsaml_test_acl

  acl eleapsaml_acl hdr(host) -i xxxx.com
  use_backend azure_backend if eleapsaml_acl

  # sileadspace.com goes through main server
  # acl sileadspace_acl hdr_end(host) -i sileadspace.com
  # use_backend azure_backend if sileadspace_acl

  # For testing "bad gateway"... append "?test-502" to URL
  acl test502 url_end -i test-502
  use_backend error502 if test502

  # For testing "all servers down"... append "?test-503" to URL
  acl test503 url_end -i test-503
  use_backend error503 if test503

  # For testing "request took too long"... append "?test-504" to URL
  acl test504 url_end -i test-504
  use_backend error504 if test504

  # Country block
  # acl blocked src,map_ip(/etc/haproxy/geoip.txt) -m found
  # acl blocked url_end -i blocked
  # use_backend blocked if blocked

  # Send back the country we think this browser is in
  # http-response set-header X-Country %[src,map_ip(/etc/haproxy/geoip.txt)]

  # Speedbump when experiencing a lot of connections... append "?speedbump" to URL
  acl running_hot url_end -i speedbump
  acl running_hot fe_sess_rate ge 200
  acl web_page path_end .html
  acl speedbump_pass hdr_sub(cookie) speedbump=pass
  use_backend speedbump if METH_GET running_hot web_page !speedbump_pass
  
  # Block a bad IP address
  # acl bad_ip src 54.71.158.53
  # tcp-request connection reject if bad_ip

# Outbound connections
backend server_backend
  # Communicate with local web server over the internal IP address
  server azure xxx.xxx.xxx.xxx:80       maxconn 5000  check inter 10s  cookie azure check

  # Communicate with remote server over the ssh tunnel
  server blue 127.0.0.1:8080   maxconn 5000  check inter 10s  cookie blue check

  # Remove the "Server: Apache..." header that gets sent back from the web server
  http-response del-header ^Server:.*

  # Add a header to let us know who our proxy is
  http-response add-header X-Proxy cyan

  # Add the port to let the web server know how we've connected
  http-request set-header X-Port %fp
  http-request set-header X-SSL-Protocol %[ssl_fc_protocol]

# Connect using internal IP address
backend azure_backend
  server azure xxx.xxx.xxx.xxx:80  maxconn 5000  check inter 10s  cookie azure check

  # Remove the "Server: Apache..." header that gets sent back from the web server
  http-response del-header ^Server:.*

  # Add a header to let us know who our proxy is
  http-response add-header X-Proxy cyan

  # Add the port to let the web server know how we've connected
  http-request set-header X-Port %fp
  http-request set-header X-SSL-Protocol %[ssl_fc_protocol]

# For blocked countries
backend blocked
  errorfile 503 /etc/haproxy/errors/blocked.http

# For speedbump'ing
backend speedbump
  errorfile 503 /etc/haproxy/errors/speedbump.http

# For testing 502 (bad gateway) handling
backend error502
  errorfile 502 /etc/haproxy/errors/502.http

# For testing 503 (all servers down) handling
backend error503
  errorfile 503 /etc/haproxy/errors/503.http

# For testing 504 (server took too long) handling
backend error504
  errorfile 504 /etc/haproxy/errors/504.http
```

## Output of `haproxy -vv` and `uname -a`

After downgrade...
```
HA-Proxy version 2.2.8-1~bpo10+1 2021/01/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.8.html
Running on: Linux 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-Dyw9cm/haproxy-2.2.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app


Linux xxxxx.com 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

## Additional information (if helpful)

Checking the domain at https://www.ssllabs.com/ssltest/index.html would always result in an error being encountered by the ssllabs site, causing it to not be able to score the certificate. I apologize for not documenting what the exact message was before falling back to an older version of the software. It's a pretty generic error message though.

**Comment by wtarreau** [comment] 2021-03-25 21:42
Hi,

thanks for your report. I'm pretty sure it's caused by the rate check. There was a bug there causing it to be randomly reset with threads, and the fix only worked for periods of 1 second or less, but fails to rotate the periods for larger durations. The latest maintenance version as well as the recently released 2.3.8 both have the fix. Otherwise early next week we'll issue 2.2.12 with it.

**Comment by JonnyRoller** [comment] 2021-03-26 10:34
Thanks, Willy! I'll keep an eye out for the new version.

**Comment by lukastribus** [comment] 2021-03-26 11:53
In this case, it's a duplicate of #1196

**Closed as completed by lukastribus** 2021-03-26 11:53 UTC
Labels: type: bug, status: duplicate
