### ISSUE TITLE
Haproxy not picking up changed port when using servers-state-file

### ISSUE THREAD

**Issue by tmccombs** [haproxy/haproxy#1412] opened 2021-10-13 23:09 UTC
### Detailed Description of the Problem

If I change the port of a server in a server-template in configuration, reloading haproxy either using SIGUSR2 or saving state to state file and restarting haproxy using the `-sf` option does not use the new port, and instead continues to use the port from the old configuration. In order to get the new port change, I either need to change the name of the server, or stop haproxy and restart it without preserving state.

### Expected Behavior

After 

### Steps to Reproduce the Behavior

1. Use configuration similar to that given below
2. change the port number for example.com in the server-template line.
3. Run `echo "show servers state"| socat /tmp/haproxy-stats - > /tmp/haproxy-server-state` to store the server state
4. Run `haproxy -W -f $haproxyCfg  -sf $oldPid
5. Look at current server state (for example with `echo show servers state | socat /tmp/haproxy-stats -`. 
6. The servers are still using the old port

Steps 3-5 can be replaced with sending a SIGUSR2 signal to the process with the same effect

### What is your configuration?

```haproxy
global
    server-state-file /tmp/haproxy-server-state
    stats socket      /tmp/haproxy-stats
    nbthread          2

defaults
  load-server-state-from-file global
  mode             http
  retries          3
  maxconn          65000
  timeout connect  5000
  timeout client   30000
  timeout client-fin  5000
  timeout http-keep-alive 90000
  timeout server   300000

resolvers systemdns 
  parse-resolv-conf 
  accepted_payload_size 8192

backend BACKEND_example
  balance leastconn
  default-server inter 3s fall 2 rise 2
  option httpchk GET /health

  server-template servername 4 example.com:80 check resolvers systemdns init-addr none
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.17-dd94a25 2021/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.17.html
Running on: Linux 5.4.0-1038-aws #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2_JIT=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

### Additional Information

Also happens in haproxy 2.0.25

**Comment by wtarreau** [comment] 2021-10-14 05:19
This is caused by a more genreal design limitation of the state file, which is why we wanted to have it reworked for 2.5 (but it will have to be postponed to 2.6). The issue is that some runtime-changeable settings are stored in the state file (such as the port) and are preserved upon reload, voiding the ability to apply config changes. And of course, this was done because other users were complaining about the opposite.

The right solution consists in dumping into that file both the config and current states so that config changes can be detected upon reload and always have precedence over the state file. That's in part what was already made with the maintenance flags by the way. But all other elements need to support this.

A simpler workaround for now in your case consists in removing that server line from the state file when you change the server's config. The server will not be found and only its config settings will be used.

I'm marking it as "works as designed", because it's just that even though it's absolutely not satisfying, but the rework of this file is the only solution and is already on the todo list.

**Closed as completed** 2021-12-02 10:51 UTC
Labels: type: bug, status: works as designed
