### ISSUE TITLE
Regression in supporting plain `query()` fetch sample (i.e. with no optional arguments, but with parentheses)

### ISSUE THREAD

**Issue by cipriancraciun** [haproxy/haproxy#2815] opened 2024-12-09 20:36 UTC
### Detailed Description of the Problem

Until 3.1 (or perhaps earlier, but definitively after 2.8) the following syntax used to be supported (i.e. `query()`):
~~~~
acl SOME_ACL query() -m found
~~~~

Now HAProxy 3.1 complains that the only argument expected is `with_qm`, as in only the following two syntaxes are supported:  either just `query`, or `query(with_qm)`.

Please note that other argument-less (but with parentheses) samples are still supported such as `path()` or `src()`, etc.

### Expected Behavior

As described above, other samples are supported such as `path()`, `src()`, etc.

### Steps to Reproduce the Behavior

Just use an ACL like:
~~~~
acl SOME_ACL query() -m found
~~~~

### What is your configuration?

```haproxy
I don't think there is any need for a full configuration, as just the ACL above triggers the issue.
```

### Output of `haproxy -vv`

```plain
~~~~
> haproxy -vv                                                                                             
HAProxy version 3.1.0 2024/11/26 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-3.1.0.html
Running on: Linux 6.4.0-150600.23.25-default #1 SMP PREEMPT_DYNAMIC Tue Oct  1 10:54:01 UTC 2024 (ea7c56d) x86_64
Build options :
  TARGET  = linux-glibc    
  CC      = cc                         
  CFLAGS  = -O2 -g -fwrapv             
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1 USE_PIE=1 USE_STACKPROTECTOR=1 USE_RELRO_NOW=1
  DEBUG   =                         

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH
 -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +S
HM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB
                                                                                                          
Default settings :                                                                                        
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200               
                                                                                                          
Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
Running on OpenSSL version : OpenSSL 3.1.4 24 Oct 2023     
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes      
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes     
Built with gcc compiler version 7.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG
       spop : mode=SPOP  side=BE     mux=SPOP  flags=HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags= 
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
~~~~
```

**Comment by Darlelet** [comment] 2024-12-09 23:13
Caused by 17d4e6eaf9f5fa5f13fad74b76ec2d31408abf6a

I'm unable to tell if this can be considered as a legit regression or not (ie: if we want to emulate the old behavior) because I failed to find other fetches taking optional arguments that still accept being called with parentheses but with no argument

(`path` and `src` for instance don't take argument, like it was the case for `query` before the above patch)

**Comment by capflam** [comment] 2024-12-10 07:04
Indeed, for string arguments, no argument is equivalent to an empty string. So I guess `val_query()` function should be changed to just ignore empty string as argument.

**Comment by cipriancraciun** [comment] 2024-12-10 19:42
> @Darlelet [...] because I failed to find other fetches taking optional arguments that still accept being called with parentheses but with no argument [...]

I can tell with certainty (as I've just searched the Git log for the HAProxy deployment) that I've used the following two lines (or very similar) in production since May 2019, until this day (when it's running on 2.7):
~~~~
http-response set-header "Expires" "%[date(3600),http_date()]"
http-response set-header "Date" "%[date(),http_date()]"
~~~~

Another example (from the same config) would also be `json()` and `sc0_bytes_out_rate()`, all of which according to the documentation (for example for v2.5) do accept one or more optional arguments.

----

Why I'm raising this issue?  Since many years ago I've written myself a HAProxy configurator in Python (<https://github.com/cipriancraciun/haproxy-configurator>) that generates HAProxy configurations automatically based on Python code, and I've used to always generate samples calls with `()`, because I've found it reasonable to consider them "function calls", thus like in all programming languages no arguments would require `()`.

(Granted, I can easily change my generator to remove the `()`, which I actually did to temporarily fix the issue, but I think as @capflam mentioned, `sample()` should be a valid syntax, especially given how close the sample syntax resembles a functional language, with `,` as a pipeline `|`.)

**Comment by capflam** [comment] 2024-12-10 21:41
You're right, no argument (without `()` or empty argument (with `()`) should be equivalent. But technically speaking, there is a difference between an optionnel string argument and other types. `date` and `date()` are really equivalent. after the parsing, there is no argument at all when the sample is evaluated. But here `query` and `query()` are not equivalent. In the first case, there is no argument. In the second one, there is an empty string as argument. So at the end, it should be evaluated in the same manner. But we must be aware of the difference. I will do the fix tomorrow morning.

**Comment by cipriancraciun** [comment] 2024-12-10 22:17
> But here `query` and `query()` are not equivalent. In the first case, there is no argument. In the second one, there is an empty string as argument. So at the end, it should be evaluated in the same manner. But we must be aware of the difference.

Unfortunately, I understand HAProxy's particularities of string arguments (i.e. `function(,)` would actually be equivalent to `function("","")` in normal languages), and I was happy in the latest releases when HAProxy has introduced proper argument quoting.

However as a general rule (if possible), given not many would dig deep enough to understand these particularities, please do not introduce diverging behaviours between `function`, `function()`, `function("")`, `function(,)`, or `function("","")` (in case `function` has two optional arguments).

> I will do the fix tomorrow morning.

Thanks!  There is no hurry.  (I'll have to wait for the next release, so it goes into the next OpenSUSE testing repository.)

**Comment by capflam** [comment] 2024-12-11 09:26
Fixed now. Thanks !

**Closed as completed** 2024-12-16 06:51 UTC
Labels: type: bug, status: fixed
