### ISSUE TITLE
nolinger makes prom-exporter send a premature RST,ACK

### ISSUE THREAD

**Issue by pgaxatte** [haproxy/haproxy#896] opened 2020-10-13 08:16 UTC
## Detailed description of the problem

When using the `option nolinger`, the embedded prometheus exporter sends a premature RST,ACK which breaks the client-side (either a simple curl or a prometheus scraper).

The normal stats backend does not seem to be affected.

## Expected behavior

The connection to the promex should be closed after haproxy has received all ACKs from the client.

## Steps to reproduce the behavior

1. Minimal configuration to reproduce the problem:
```
defaults
  option  nolinger

listen stats
  bind *:9000
  mode http
  http-request use-service prometheus-exporter if { path /metrics }
  stats enable
  stats refresh 10s
  stats uri /
```
2. Curl the promex endpoint and get a RST before obtaining all metrics:
```
$ curl http://localhost:9000/metrics
# HELP haproxy_process_nbthread Configured number of threads.
# TYPE haproxy_process_nbthread gauge
haproxy_process_nbthread 2
[...random number of lines...]
curl: (56) Recv failure: Connection reset by peer
```

Validated this problem on 2.1.8, 2.2.4 and 2.3-dev6.
I did not try on the latest master.

The test were done in Kubernetes, here is the YAML if you want to reproduce it:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-haproxy-etc
data:
  haproxy.cfg: |
    defaults
      option  nolinger

    listen stats
      bind *:9000
      mode http
      http-request use-service prometheus-exporter if { path /metrics }
      stats enable
      stats refresh 10s
      stats uri /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: test
    component: haproxy
  name: test-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      application: test
      component: haproxy
  template:
    metadata:
      labels:
        application: test
        component: haproxy
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - haproxy
        - -f
        - /usr/local/etc/haproxy/haproxy.cfg
        image: haproxy:2.3-dev6
        imagePullPolicy: IfNotPresent
        name: haproxy
        ports:
        - containerPort: 9000
          name: haproxy-stats
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          mountPropagation: None
          name: haproxy-etc
          readOnly: true
          subPath: haproxy.cfg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          name: test-haproxy-etc
          defaultMode: 292
          optional: false
        name: haproxy-etc
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.3-dev6-b7ffe19 2020/10/10 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with gcc compiler version 8.3.0
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

```
Linux test-haproxy-75f47b859b-hvbf8 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 GNU/Linux
```

**Comment by pgaxatte** [comment] 2020-10-13 08:33
BTW, the fix is to add `no option nolinger` on the stats frontend.

**Comment by wtarreau** [comment] 2020-10-14 08:42
But this is by design and documented!
```
it is not recommended to use this option when not absolutely needed.
```
Why in the first place would you want to use such a dangerous option, and further, why in the `defaults` section ?

**Comment by pgaxatte** [comment] 2020-10-14 09:18
I kinda inherited this option and did not question it at first.

It is in default because we only have 3 proxies: stats and 2 proxies for a mariadb cluster.

I know MySQL/MariaDB clients badly handle closing connections so it probably was for this reason that the nolinger option was used.

I understand this option is probably a bad idea but still it seems to only break the prometheus exporter in my setup, nothing else

**Comment by wtarreau** [comment] 2020-10-14 09:59
No, it breaks absolutely *everything*. The principle is ask the system to destroy any data still pending in the socket buffers at the moment of a close. Just try it with a close HTTP response and you'll get truncated responses. It was added long ago to work around a few client bugs so I can easily understand why you're using it for the same reason, but this must definitely be limited to the mentioned proxies and must in no way be placed in defaults. You're just making me think right now that we should emit a warning on this because it's very easy to inherit such a setup by accident :-/

**Comment by pgaxatte** [comment] 2020-10-14 13:19
Yeah, although the documentation is explicit on the fact that this option is not recommended, it does not really say that this option is very dangerous.

A fair warning would be great :)

And I'm going to reconsider all the default options I inherited and see if I really need them

**Comment by wtarreau** [comment] 2020-10-14 15:00
I looked at adding an option when this one is inherited from defaults, and it definitely is not an easy thing to do! We don't know when validating a proxy if its options come from itself or the default proxy. I see how to achieve this, it will require a bit of code updates to store the locally-set options just for this purpose. But it's definitely worth it! By the way if you think a different wording in the doc would help, feel free to suggest!

Regarding your options, a good practice is to never use the same defaults section for both TCP and HTTP proxies. Have one defaults section for TCP and another one for HTTP. This will save you a lot of hassle and even avoid irrelevant warnings.

**Comment by pgaxatte** [comment] 2020-10-14 18:30
I could propose something to make a stronger case against this option, saying this can be a dangerous option but I would not have a sufficient technical understanding of what it does to back that up and explain why.

Thanks for the tip on separate defaults, I'll definitely do that!

**Comment by wtarreau** [comment] 2020-10-15 03:27
OK, I'll probably update it at least to emphasize this.

**Comment by wtarreau** [comment] 2020-10-16 02:56
I updated the doc and am closing now. Thanks!

**Closed as completed by wtarreau** 2020-10-16 02:56 UTC
Labels: type: bug, status: works as designed
