### ISSUE TITLE
src/http_fetch.c: uninitialized value suspected by coverity (new finding)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1089] opened 2021-01-29 08:08 UTC
```
    9. Condition !occ, taking false branch.
 924        if (!occ)
 925                /* prepare to report multiple occurrences for ACL fetches */
 926                smp->flags |= SMP_F_NOT_LAST;
 927
 928        smp->data.type = SMP_T_STR;
 929        smp->flags |= SMP_F_VOL_HDR | SMP_F_CONST;
    CID 1445803 (#1 of 1): Uninitialized scalar variable (UNINIT)10. uninit_use_in_call: Using uninitialized value name when calling http_get_htx_hdr. [show details]
 930        if (http_get_htx_hdr(htx, name, occ, ctx, &smp->data.u.str.area, &smp->data.u.str.data))
 931                return 1;
 932
 933        smp->flags &= ~SMP_F_NOT_LAST;
 934        return 0;
```

**Comment by capflam** [comment] 2021-01-29 12:48
It should be fixed now. It is the same than #1087. Fixed by commit 623af937

**Comment by chipitsine** [comment] 2021-01-29 18:56
is it going to be backported or we just close it ?

**Comment by capflam** [comment] 2021-01-30 07:34
No, it is not a bug. There is no reason to backport it. Thus we can close the issue.

**Closed as completed by capflam** 2021-01-30 07:34 UTC
Labels: status: fixed, type: code-report
