### ISSUE TITLE
Problem with connections in 2.6.8

### ISSUE THREAD

**Issue by lukenowak** [haproxy/haproxy#2033] opened 2023-02-06 16:37 UTC
### Detailed Description of the Problem

Having provided configuration, where the 127.0.0.1 8888 and 8889 are single threaded, fast (I can reply superfast with curl, and replies when there is such problem with haproxy), "backend1" or "backend2" replying backends, which do not set any cookie.

In the beginning when I access it with `curl -m 2 http://[ipv6]:8888/` I can see that all works well, round-robin works as expected, but after some time, or after such command:

```
while :; do curl -m 2 http://[ipv6]:8888/ ; done
```

it timeouts (curl one), if I'd wait for `timeout queue 60s` then I have 503 from haproxy.

In the log I observe:
```
family_default family_default/ -1/-1/-1/-1/80845 400 0 - - CR-- 16/16/14/0/0 0/0 “”
family_default family_default/ 0/60001/-1/-1/60001 503 217 - - sQNN 15/15/13/0/0 0/1 “GET /
```

The status of haproxy is in attached screenshot.

![screenshot](https://user-images.githubusercontent.com/334019/217029432-19923401-1753-4f91-9f45-054f4b8bda44.png)

### Expected Behavior

I expect haproxy to reply with roundrobin without any problem, like with 2.6.7.

### Steps to Reproduce the Behavior

1. Install haproxy 2.6.8
2. Prepare
3. Apply given configuration
4. Tr

### What is your configuration?

```haproxy
global
  maxconn 4096
  master-worker
  pidfile haproxy.pid
  stats socket ha.sock level admin

defaults
  mode http
  retries 1
  option redispatch
  maxconn 2000
  balance roundrobin
  stats uri /haproxy
  stats realm Global\ statistics
  timeout connect 10s
  timeout queue 60s
  timeout client 305s
  option http-server-close
  log stdout format raw daemon
  option httplog

listen family_default
  bind ipv6:8888 alpn http/1.1 
  cookie SERVERID rewrite
  http-request set-header X-Balancer-Current-Cookie SERVERID

  server default-0 127.0.0.1:8888 cookie default-0 check inter 3s rise 1 fall 2 maxqueue 5 maxconn 1
  server default-1 127.0.0.1:8889 cookie default-1 check inter 3s rise 1 fall 2 maxqueue 5 maxconn 1
  option httpchk GET /
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.8-ab6ee7f 2023/01/24 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.8.html
Running on: Linux 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64
Build options :            
  TARGET  = linux-glibc                                                    
  CPU     = generic                                                        
  CC      = cc                                                             
  CFLAGS  = -m64 -march=x86-64 -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-o
verflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clo
bbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_DL=1       
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS                         
                                                                           
Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE +LIBCRYPT
 +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCT
L -PROMEX -QUIC +RT -SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB
                                                                           
Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1o  3 May 2022
Running on OpenSSL version : OpenSSL 1.1.1o  3 May 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.3
Built with network namespace support.                 
Support for malloc_trim() is enabled. 
Built with zlib version : 1.2.12
Running on zlib version : 1.2.12
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.5.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

**Comment by wtarreau** [comment] 2023-02-07 08:00
Thanks for your report. How many attempts do you need to make for the problem to happen in general ? On your test I'm seeing 245 connections, but I can't manage to trigger the problem even after thousands of tests.

I'm wondering if instead it could be related to the communicatoin on the server side, for example something making the server believe the request is not finished, or making haproxy believe the response is not finished, keeping the connection reserved for the pending request.

If it's easy to reproduce on your side, could you please take a tcpdump of the communcation between haproxy and one of the servers ?

**Comment by lukenowak** [comment] 2023-02-07 14:46
Thanks for follow-up :)

> How many attempts do you need to make for the problem to happen in general ?

~20

> I'm wondering if instead it could be related to the communicatoin on the server side...

Indeed, the backend might be not perfect, but we are very often in situation of unprefect backends.

> If it's easy to reproduce on your side, could you please take a tcpdump of the communcation between haproxy and one of the servers ?

With a bit of change:
```
  timeout connect 1s
  timeout queue 1s
  timeout client 305s
```
here is attached tcpdump:
[to8888.pcap.gz](https://github.com/haproxy/haproxy/files/10676188/to8888.pcap.gz)

That's not all, I played a bit with `timeout client`:

 * 10s - problem happens
 * 5s - problem happens
 * 1s (like the rest) - I can't observe the issue

Then in logs I have some kind of pauses,with log line:
```
[07/Feb/2023:15:43:20.296] family_default family_default/default-0 0/0/0/0/1001 200 123 - - cDNN 3/3/2/0/0 0/0 "GET / HTTP/1.1"
```

**Comment by wtarreau** [comment] 2023-02-07 15:31
Thanks! Outgoing connection from port 49178 looks bad: the server closes and we don't. That explains why there's no more progress, the maxconn limit is reached and extraneous connections die in the queue. The issue description surprisingly matches the issue reported in this fix that was backported to 2.6.8, except that it was precisely supposed to avoid such cases:

```
commit 585d4687cdeaf986406335a9788fdf88ae0c0b53
Author: Christopher Faulet <cfaulet@haproxy.com>
Date:   Mon Dec 5 07:42:00 2022 +0100

    BUG/MEDIIM: stconn: Flush output data before forwarding close to write side
    
    In process_stream(), we wait to have an empty output channel to forward a
    close to the write side (a shutw). However, at the stream-connector level,
    when a close is detected on one side and we don't want to keep half-close
    connections, the shutw is unconditionally forwarded to the write side. This
    typically happens on server side.
    
    At first glance, this bug may truncate messages. But depending on the muxes
    and the stream states, the bug may be more visible. On recent versions
    (2.8-dev and 2.7) and on 2.2 and 2.0, the stream may be freezed, waiting for
    the client timeout, if the client mux is unable to forward data because the
    client is too slow _AND_ the response channel is not empty _AND_ the server
    closes its connection _AND_ the server mux has forwarded all data to the
    upper layer _AND_ the client decides to send some data and to close its
    connection. On 2.6 and 2.4, it is worst. Instead of a freeze, the client mux
    is woken up in loop.
```

I'm wondering if it could be possible that from time to time some data remain stuck there in the channel, further delaying the close, but given that you're just using regular GETs with curl, I don't see how this could be possible (unless of course it uncovered another latent bug). CCing @capflam in case he has any idea about this.

Since you're building from the sources, are you able to revert the patch above from your tree and try again ? If you need me to attach the patch or to pass instruction, do not hesitate to ask; I just don't want to spam you with instructions if you know how to proceed.

**Comment by lukenowak** [comment] 2023-02-07 16:06
Wow, nice catch.

I'll try with "unpatching", I know how to proceed now. I'll report back as soon as it's done.

**Comment by capflam** [comment] 2023-02-07 16:15
Thanks @wtarreau for the diag. I'm investigating.

**Comment by capflam** [comment] 2023-02-08 07:59
I'm able to reproduce the issue on 2.7 and lower but not on 2.8. The commit above is responsible, at least indirectly. I'll try to better understand the issue to figure out how to fix it. Thanks !

**Comment by lukenowak** [comment] 2023-02-08 09:32
> I'll try with "unpatching", I know how to proceed now. I'll report back as soon as it's done.

After unpatching the change 2.6.8 works correctly.

**Comment by capflam** [comment] 2023-02-08 14:38
Ok, I found a way to fix the issue. In the above commit, the write side is closed only if there is no outgoing data. Otherwise nothing is performed. I was hoping `process_stream()` would be able to shut the write side down on its own. But it does not. Thus instead of skipping the shutdown for write, we can flag the write side to be closed ASAP via a call to `channel_shutw_now()`. Concretely it means we should use this kind of construct:

```c
       if ((sc->flags & SC_FL_NOHALF)) {
               if (!channel_is_empty(ic)) {
                       /* Forward the close asap but flush outgoing data first */
                       channel_shutw_now(oc);
               }
               else {
                       /* we want to immediately forward this close to the write side */
                       /* force flag on ssl to keep stream in cache */
                      ...
               }
```
I will work on a proper patch.

**Comment by wtarreau** [comment] 2023-02-08 14:49
Cool!

I think you should create a dedicated function for this, such as channel_is_empty_or_shut() or something that ugly, that performs the test, does shutw_now() and returns the result of the test. It would make the code less ugly at the various call places.

**Comment by capflam** [comment] 2023-02-08 14:51
Yes it is a good idea. This part remains hard to maintain...

**Comment by capflam** [comment] 2023-02-08 15:39
Here is the patch. It can be applied on top of the original 2.6.8. @lukenowak Could you try it please ?

[0001-BUG-MEDIUM-stconn-Schedule-a-shutw-on-shutr-if-data-.patch.txt](https://github.com/haproxy/haproxy/files/10687251/0001-BUG-MEDIUM-stconn-Schedule-a-shutw-on-shutr-if-data-.patch.txt)

**Comment by wtarreau** [comment] 2023-02-08 15:45
Yeah it's clean like this. I hope it fixes the issue :-)

**Comment by capflam** [comment] 2023-02-08 15:46
Me too ...

**Comment by wtarreau** [comment] 2023-02-08 16:45
At least for now I can't figure a way to make it fail (i.e. it doesn't seem to break more than it fixes), that's already a good point!

**Comment by lukenowak** [comment] 2023-02-09 07:05
Thank you very much, that was fast.

> Here is the patch. It can be applied on top of the original 2.6.8. @lukenowak Could you try it please ?

@capflam I applied, works correctly.

**Comment by capflam** [comment] 2023-02-09 08:05
Thanks ! I'll push it

**Closed as completed** 2023-03-16 08:26 UTC
Labels: type: bug, status: fixed
