### ISSUE TITLE
[ DNS ] Server-template after reload with sever-state cleanup

### ISSUE THREAD

**Issue by ACenterA** [haproxy/haproxy#1795] opened 2022-07-19 22:45 UTC
### Detailed Description of the Problem

Link discours issue : https://discourse.haproxy.org/t/dns-server-state-cleanup/7847

We use HAPROXY with SRV records, it works great but we have a small issue where it supposed to have only 2 Backend active (can scale up to 4  -> server-template is also set to 4 ) but we only had 2 at the current time (using the DIG on the SRV Record).

We use haproxy 2.4.17 and this is the behavior we observed.

### Expected Behavior

Somehow there is no cleanup of previous SRV Records in the HAPROXY server state / template. 

It would be great to have an option to cleanup the server-state resolved IP if the SRV Records get deleted (since some container got removed and changed IP / Port ).

### Steps to Reproduce the Behavior

1. HA Proxy server-template with 4 current options :   
        server-template domain-x 4 "_tcp_.entrypoint.my-custom-discovery-dns.local" resolvers dns resolve-opts allow-dup-ip resolve-prefer ipv4 fastinter 10s rise 2 fall 2 on-error fastinter check inter 10000

1. Create SRV Record with 2 IP/PORT Address
2. Add new SRV Record with different IP/PORT Address
3. Update SRV Record to remove 1 IP/PORT
4. Socat show server state  would show up the 3 IP  / PORT.

### Do you have any idea what may have caused this?

The Container hosting solution we use can 're-use same IP and ports' at random times. Thus making wrong backend to access a different HAProxy backend configuration and sending wrong traffic.

### Do you have an idea how to solve the issue?

Upon L4 Error ha proxy could potentially execute "one SRV" lookup to validate if that IP is still part of the SRV Record. (based on a configuration)

### What is your configuration?

```haproxy
global
  default-server init-addr last,libc,none resolvers dns resolve-opts allow-dup-ip resolve-prefer ipv4

resolvers dns
  nameserver docker x.y.z.w:53
  parse-resolv-conf
  resolve_retries 50
  timeout resolve       2s
  timeout retry         2s
  accepted_payload_size 8192
  hold other           30s
  hold refused         30s
  hold nx              30s
  hold timeout         30s
  hold valid           20s
  hold obsolete        30s

...

backend...
  server-template domain-x 4 "_tcp_.entrypoint.my-custom-discovery-dns.local" resolvers dns resolve-opts allow-dup-ip resolve-prefer ipv4 fastinter 10s rise 2 fall 2 on-error fastinter check inter 10000
```

### Output of `haproxy -vv`

```plain
2.4.17
```

**Comment by capflam** [comment] 2022-08-25 11:35
Sorry, I don't understand the report. First `default-server` cannot be set in global section. Then, when your are talking about "server-state", do you mean server-state file ? Because in this case, the problem is about the resolution or about the state of the servers after a reload ? Your reproducer does not mentioned any reload. So it is confusing. Honestly I don't understand what you observe and what you expect.

If you really think there is a bug, you must provide more information. For instance `show stat` outputs when it works and when there is an issue with associated dig outputs.

**Comment by FLavalliere** [comment] 2022-08-26 19:01
@capflam hello, apologize if my comments / description on both here / discourse was not clear enough.

In short, the `show servers state` seems to keep 'old' DNS Entries which did not exists anymore for that specific SRV DNS Response.

Let say that there is a DNS that resolve to two SRV Records  IP/Port address
IPA:PORTA
IPB:PORTB

During the haproxy live, the DNS Entry add two new IP/Port (add 2 new containers, by rolling update... 50% ratio).

So the `show servers state` command  would return something like 

IPA:PORTA
IPB:PORTB
IPC:PORTC

Then

IPA:PORTA
IPB:PORTD
IPC:PORTC


What we expect HA Proxy to do is that IPA:PORTA be removed at some point (obsolete 30s flag?) so that the `show servers` command line only shows that there are only 2 IP's as the previous one is no more in the DNS Response... leaving the server-state  with only two entries:

IPB:PORTD
IPC:PORTC

**Comment by FLavalliere** [comment] 2022-08-26 19:03
Here was the comment on the discourse:

The show stat unix command gave us the following:

```
domain-x-4_back,domain-x-41,0,0,0,0,0,0,0,0,0,0,0,0,UP,1,1,0,0,0,410,0,1,861,1,0,2,0,0,L4OK,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,Layer4 check passed,2,2,3,10.10.12.203:49156,http,0,0,0,0,0,0,0,0,0,0,0,0,0,1,-,0,0,0,
domain-x-4_back,domain-x-42,0,0,0,0,0,0,0,0,0,0,0,0,UP,1,1,0,0,0,103995,0,1,861,2,0,2,0,0,L4OK,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,Layer4 check passed,2,2,3,10.10.21.180:49157,http,0,0,0,0,0,0,0,0,0,0,0,0,0,1,-,0,0,0,
domain-x-4_back,domain-x-43,0,0,0,0,0,0,0,0,0,0,0,0,UP,1,1,0,0,0,410,0,1,861,3,0,2,0,0,L4OK,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,Layer4 check passed,2,2,3,10.10.12.157:49295,http,0,0,0,0,0,0,0,0,0,0,0,0,0,1,-,0,0,0,
domain-x-4_back,domain-x-44,0,0,0,0,0,0,0,0,0,0,0,0,UP,1,1,0,0,0,103488,0,1,861,4,0,2,0,0,L4OK,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,Layer4 check passed,2,2,3,10.10.12.44:49160,http,0,0,0,0,0,0,0,0,0,0,0,0,0,1,-,0,0,0,
```

As we can see somehow we have 4 Servers, but there should be only 2 (valid).

If we would do DIG SRV DNSNAME, Only two IP/PORT would be returned, but haproxy still believed that the previous IP should be kept.

**Comment by FLavalliere** [comment] 2022-08-29 15:00
We came accross https://github.com/haproxy/haproxy/issues/1694 and our understanding would  of been that the 'hold obsolete' or something like that would remove the DNS entry after that TTL. But i guess that was not the case.

**Comment by capflam** [comment] 2022-08-29 16:01
So, it I correctly understand your issue, your DNS announces 2 hosts (A and B) and after an upgrade, it announces 2 new hosts (C and D), removing the first ones. With a `hold obsolete` set to 30s, A and B records will be kept 30s. Because you have 4 servers, you will see the 4 servers up during 30s. C and D will be provisioned immediately. With only 2 servers, the update will only be propagated after the `hold obsolete` timeout. At least, it is the expected behavior.

To be sure, could you provide outputs for `show servers state` command  and dig on the SRV record before the update and 1m after the record update ?

**Comment by FLavalliere** [comment] 2022-08-29 16:16
You are almost right.

The problem we were seeing is that the records actually never gets 'removed' from the `show servers state`, and at some point some other containers starts re-using the same IP / Port. Thus having the service sending the HTTP Request to the wrong set of containers.

I'll check if I have another example like this in our current system (or if i can find back some previous screenshots ).

**Comment by FLavalliere** [comment] 2022-08-30 14:22
@capflam  i think we can probably close this ticket. I have tried to reproduce and in all cases it seems that the servers get cleaned up properly. I am not 100% sure why it did occurs then, maybe could be related to #1840  ....

If i get another occuring i'll check the values of the `show resolvers` commands. I do know that the DIG was returning 2 SRV records while in the server-state command it was still showing 4 entries. And upon restart everything was fine. But i have no idea why or how to reproduce at the moment.

Thank you,

**Comment by FLavalliere** [comment] 2022-08-30 14:23
We will also reduce the `hold obsolete` for now to something like 5s, or 1s as we dont really need to keep it as we use Consul with Healthcheck and supports signterm gracefully on our containers.

**Comment by capflam** [comment] 2022-08-30 14:26
Ok, fine. I'm closing the issue with `cannot reproduce` label. Thanks !

**Closed as not planned by capflam** 2022-08-30 14:26 UTC
Labels: type: bug, status: cannot reproduce
