### ISSUE TITLE
Request fails and process is stuck at 100% CPU (HAProxy 2.0)

### ISSUE THREAD

**Issue by bjoernbessert** [haproxy/haproxy#132] opened 2019-06-22 02:29 UTC
I'm using 2 HAProxy processes and Lua for generating (self signed) ssl certs on the fly with HAProxy. This has been working without a problem with 1.8 and 1.9, but unfortunately 2.0 breaks this. I've stripped down and simplified the config and the lua code to a minimum for reproducing.  

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.0.0-1ppa1~bionic 2019/06/21 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-SXk3vY/haproxy-2.0.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

```
```
Linux XXX 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

/etc/haproxy/haproxy_front.cfg  ("frontend"-process, this process is running the lua code (which is restarting the "backend"-process)):
```
global
    lua-load /etc/haproxy/lua_files/on_the_fly_cert.lua
    nbthread 1
    noreuseport

defaults
    log     global
    mode    http
    timeout connect 20s
    timeout client  50s
    timeout server  60s

frontend fe
    mode tcp
    bind *:443
    tcp-request inspect-delay 10s
    tcp-request content reject if ! { req_ssl_hello_type 1 }
    tcp-request content reject if ! { req_ssl_sni -m found }
    tcp-request content lua.cert_otf
    default_backend be

backend be
    mode tcp
    server haproxy_back 127.0.0.1:44300 send-proxy
```
/etc/haproxy/haproxy_back.cfg ("backend"-process):
```
global
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-bind-options no-sslv3
    tune.ssl.default-dh-param 2048
    nbthread 1
    noreuseport

defaults
    log     global
    mode    http
    timeout connect 20s
    timeout client  50s
    timeout server  60s

frontend fe
    mode http
    bind *:44300 accept-proxy ssl crt /etc/haproxy/certs/
    default_backend be

backend be
    mode http
    server apache 127.0.0.1:8888
```

I've tried with nbthread 1 and noreuseport, but that didn't help.<br/>

/etc/haproxy/lua_files/on_the_fly_cert.lua: (strongly minimized/simplified)
```
function cert_otf(txn)
    os.execute("ps aux | grep -i haproxy_back | grep -v grep |  awk '{print $2}' | xargs kill -9")
    os.execute("/usr/sbin/haproxy -f /etc/haproxy/haproxy_back.cfg -dR &")
end
```

## Steps to reproduce the behavior

1. /usr/sbin/haproxy -f /etc/haproxy/haproxy_front.cfg -dR
2. /usr/sbin/haproxy -f /etc/haproxy/haproxy_back.cfg -dR
3. time curl -I https://sub1.example.local

## Actual behavior

time curl -I https://sub1.example.local
```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sub1.example.local:443

real    1m1.039s
user    0m0.004s
sys     0m0.009s
```

ps aux | grep /usr/sbin/haproxy | grep -v grep
```
root      14406 73.1  0.8  47704  8320 pts/1    R+   02:55   2:40 /usr/sbin/haproxy -f /etc/haproxy/haproxy_front.cfg -dR
root      14463  0.0  1.3  52572 13692 pts/1    S+   02:55   0:00 /usr/sbin/haproxy -f /etc/haproxy/haproxy_back.cfg -dR
```

lsof -i -n -P | grep haproxy | grep '*:443 '
(Output after the "backend" process is stopped and started. "reuseport" is disabled,
Is it normal that 2 processes are listening on the same port? (when "reuseport" is disabled)
```
haproxy   14406            root    6u  IPv4 111002      0t0  TCP *:443 (LISTEN)
haproxy   14463            root    6u  IPv4 111002      0t0  TCP *:443 (LISTEN)
```

top (the "frontend" process is stuck at CPU usage (this is a test VM with no traffic))
```
%Cpu0  : 43.1 us, 56.9 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :   985072 total,   265192 free,   224864 used,   495016 buff/cache
KiB Swap:  1970172 total,  1970172 free,        0 used.   596636 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 14406 root      20   0   47704   8320   6984 R 98.0  0.8   4:50.16 /usr/sbin/haproxy -f /etc/haproxy/haproxy_front.cfg -dR
```

strace -tt -p 14406  (stuck process)
```
03:08:36.541069 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=715, tv_nsec=6781237}) = 0
03:08:36.541150 epoll_wait(3, [{EPOLLIN|EPOLLHUP|EPOLLRDHUP, {u32=9, u64=9}}], 200, 1000) = 1
03:08:36.541174 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=715, tv_nsec=6788868}) = 0
03:08:36.541189 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=715, tv_nsec=6791794}) = 0
03:08:36.541202 epoll_wait(3, [{EPOLLIN|EPOLLHUP|EPOLLRDHUP, {u32=9, u64=9}}], 200, 1000) = 1
03:08:36.541217 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=715, tv_nsec=6796391}) = 0
03:08:36.541230 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=715, tv_nsec=6798745}) = 0
03:08:36.541244 epoll_wait(3, [{EPOLLIN|EPOLLHUP|EPOLLRDHUP, {u32=9, u64=9}}], 200, 1000) = 1
03:08:36.541258 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=715, tv_nsec=6803257}) = 0
03:08:36.541271 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=715, tv_nsec=6805576}) = 0
03:08:36.541285 epoll_wait(3, [{EPOLLIN|EPOLLHUP|EPOLLRDHUP, {u32=9, u64=9}}], 200, 1000) = 1
.
.
.
```

strace -tt -p 14463
```
03:09:28.944015 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17694607}) = 0
03:09:28.944090 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17699655}) = 0
03:09:28.944106 epoll_wait(10, [], 200, 1000) = 0
03:09:29.944561 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17716464}) = 0
03:09:29.944597 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17720675}) = 0
03:09:29.944612 epoll_wait(10, [], 200, 1000) = 0
03:09:30.946662 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17740174}) = 0
03:09:30.946697 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17744332}) = 0
03:09:30.946713 epoll_wait(10, [], 200, 1000) = 0
03:09:31.948677 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17763027}) = 0
03:09:31.948712 clock_gettime(CLOCK_THREAD_CPUTIME_ID, {tv_sec=0, tv_nsec=17767081}) = 0
.
.
.
```

## Expected behavior

A Request should work (like in 1.8 and 1.9) and the process should not be stuck at 100% CPU Usage.

**Comment by d22d101852** [comment] 2019-06-22 06:00
@bjoernbessert I have the same issue with the CPU usage in https://github.com/haproxy/haproxy/issues/129 but none of your connection problems.

I see that you have enabled the Prometheus exporter as well. This is definitely the reason for the issue with the CPU usage. I've tested this twice by now. Of the four instances of HAProxy I have running, only the two with the Prometheus exporter enabled are showing the weird CPU usage.

Try compiling without support for the Prometheus exporter, I bet your connection troubles go away as well.

**Comment by bjoernbessert** [comment] 2019-06-22 11:45
@d22d101852 I didn't enable it intentionally (i'm using the Ubuntu package from haproxy.debian.net).

The CPU usage of the process spikes to 100% after only one request (not after several hours).

My bigger problem is actually the failed request.

**Comment by capflam** [comment] 2019-06-25 07:10
@bjoernbessert, just to keep you informed. Olivier pushed some patches in the upstream. It should fix your issue. It was a bug about the proxy protocol and the SSL. I will backport it very soon to 2.0.

**Comment by capflam** [comment] 2019-06-26 09:53
I close the issue. HAProxy 2.0.1 will be released today. Feel free to reopen the issue if the problem is still there. Thanks !
For the record, the commit 6c6dc58da should fix the issue.

**Closed as completed by capflam** 2019-06-26 09:53 UTC
Labels: type: bug, severity: medium, status: fixed, subsystem: core

**Comment by bjoernbessert** [comment] 2019-06-27 10:06
I can confirm that 2.0.1 fixes the issue, thanks.

**Comment by capflam** [comment] 2019-06-27 10:07
Thanks for your feedback !
