### ISSUE TITLE
Syslog messages lost with log-forward?

### ISSUE THREAD

**Issue by tuxillo** [haproxy/haproxy#2731] opened 2024-09-27 19:03 UTC
### Detailed Description of the Problem

Apparently, with different `log-forward` configurations, almost always there are syslog messages lost. I've created a small docker compose configuration to test it on a smaller scale than what I intend to use it for and I can reproduce it consistently.

Now, I don't know if I'm missing a fundamental behavior from haproxy or if I'm having some mistake in my setup but it never happens when I don't use frontend/backend in mode `tcp`.

The setup is fairly simple:

```
                         + ------> axosyslog 1 ---> log files to disk
 loggen --- > haproxy  --|
                         + ------> axosyslog 2 ---> log files to disk
```

The results are as follow:

```
Testing tcp.logbackends
Attaching to haproxy-1, syslog-gen-1, syslog-server-1-1, syslog-server-2-1
syslog-gen-1 exited with code 0
syslog-gen-1  | average rate = 391594.70 msg/sec, count=4162000, time=10.6283, (average) msg size=2048, bandwidth=783189.39 kB/sec
   91529 log-1/events-2024-09-27.log
   94857 log-2/events-2024-09-27.log
  186386 total
Testing udp.logbackends
Attaching to haproxy-1, syslog-gen-1, syslog-server-1-1, syslog-server-2-1
syslog-gen-1 exited with code 0
syslog-gen-1  | average rate = 251008.54 msg/sec, count=3090000, time=12.3103, (average) msg size=2048, bandwidth=502017.09 kB/sec
   54629 log-1/events-2024-09-27.log
   62191 log-2/events-2024-09-27.log
  116820 total
Testing tcpbackends
Attaching to haproxy-1, syslog-gen-1, syslog-server-1-1, syslog-server-2-1
syslog-gen-1 exited with code 0
syslog-gen-1  | average rate = 125330.57 msg/sec, count=1465500, time=11.6931, (average) msg size=2048, bandwidth=250661.14 kB/sec
  730000 log-1/events-2024-09-27.log
  735500 log-2/events-2024-09-27.log
 1465500 total
Testing rings
Attaching to haproxy-1, syslog-gen-1, syslog-server-1-1, syslog-server-2-1
syslog-gen-1 exited with code 0
syslog-gen-1  | average rate = 249432.62 msg/sec, count=2500000, time=10.0227, (average) msg size=2048, bandwidth=498865.23 kB/sec
  290272 log-1/events-2024-09-27.log
  281835 log-2/events-2024-09-27.log
  572107 total
```

The loggen message count should match the wc total output, but that only happens with the tcpbackends case.

The docker compose and configuration files are in a github repo, just in case it helps: https://github.com/tuxillo/haproxy-syslog-forwarding.

### Expected Behavior

Minimal to no syslog messages lost? :smil

### Steps to Reproduce the Behavior

I've provided a repo with configurations and such.

### What is your configuration?

```haproxy
Already shared in the repo
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0.4-7a59afa 2024/09/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.4.html
Running on: Linux 6.10.0-linuxkit #1 SMP Wed Jul 17 10:51:09 UTC 2024 aarch64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.0.14 4 Jun 2024
Running on OpenSSL version : OpenSSL 3.0.14 4 Jun 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace

haproxy@79049495c0a8:~$ haproxy -vv
HAProxy version 3.0.4-7a59afa 2024/09/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2029.
Known bugs: http://www.haproxy.org/bugs/bugs-3.0.4.html
Running on: Linux 6.10.0-linuxkit #1 SMP Wed Jul 17 10:51:09 UTC 2024 aarch64
Build options :
  TARGET  = linux-glibc
  CC      = cc
  CFLAGS  = -O2 -g -fwrapv
  OPTIONS = USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   =

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=8).
Built with OpenSSL version : OpenSSL 3.0.14 4 Jun 2024
Running on OpenSSL version : OpenSSL 3.0.14 4 Jun 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by wtarreau** [comment] 2024-09-29 08:12
It's very likely due to the small default buffer sizes on the servers in the log backends. By default they're equal to `tune.bufsize` (16kB). You can change them with the `log-bufsize` server keyword. At your bandwidth, the buffer only holds 20 microseconds of traffic! There should be a loss counter reported somewhere on the server but it doesn't immediately come to my sight, which means that at the very least we need to improve the log-forward doc to mention log-bufsize, and the log-bufsize doc to mention this metric.

In your case I suggest using much larger buffers, to cover at least several milliseconds of traffic (e.g. 20ms, allowing a few other tasks to take a full time slice on the same CPU). 20ms of traffic at 783MB/s is roughly 16 MB! But that's probably OK as you have few servers, and we're speaking about 6 Gbps here...

**Comment by tuxillo** [comment] 2024-09-29 11:03
I've checked the `log-bufsize` server parameter in the manual and it says it allows you to specify the buffer size of the implicit ring that's created for that backend (I didn't know there was a ring under the hood). Anyways, I already played around with the buffer size in the rings here which I believe it's the same thing as `log-bufsize`, right?: https://github.com/tuxillo/haproxy-syslog-forwarding/blob/main/haproxy/haproxy.cfg.rings#L31:

```
ring logbuffer1
  description "buffer 1 for logs"
  maxlen 16384
  size 134217728
  timeout connect 10s
  timeout server 60s
``` 

I used 128MB of ring buffer size there and it didn't make a difference and I think I went as far as 512MB even. This corresponds with the "Testing rings" output above, btw.

 I'm not sure if it's the docker compose test environment that's constraining the processing or what, it requires more investigation. If I need to hold a few seconds worth of messages the buffer is going to need to be way way higher (in the Gigabytes of RAM), which is fine I guess.

With regards to the metrics, would it be possible to calculate the messages ingested vs the messages sent out to produce a metric which would provide messages loss numbers?

**Comment by wtarreau** [comment] 2024-09-29 12:05
Ah indeed. A "perf top" during the test would be useful, to figure what's slowing everything down. Regarding losses, the loss counter is set on the ring and when a ring restarts sending, it first starts by emitting a message indicating the number of messages lost. I just don't know what other stats we currently have with log-forward, ideally it would be nice to have an explicit counter of lost messages along the chain (not including incoming ones, of course).

BTW regarding the test with rings, how did you count the number of logs received ? The rings in your config don't have any server and are not mapped to a file, so I'd like to figure how that was measured.

**Comment by wtarreau** [comment] 2024-09-29 12:06
Ah sorry my bad, I misread the config due to the empty line, the server is indeed in the section. That answers my question.

**Comment by Darlelet** [comment] 2024-09-30 08:20
When testing `tcpbackends` vs `tcp.logbackends` for instance, did you notice a difference in the time the test takes to complete? (do you measure it in your bench?) What I'm interested about is the time the log producer takes to send all its logs.

Because as Willy suspected, I also think that a non-negligible amount of logs are "dropped" because the final log consumer (which seems to be writing to a file on the disk right?) is much slower than the log producer, and neither haproxy nor log consumer are able to bufferize an indefinite amount of data.


With `tcpbackends` (which doesn't seem to suffer from any loss) I suspect that the consumer is automatically slowed down because tcp is used all along the chain, thus when buffers are full, the `write()` on the consumer will either return EAGAIN or block until some data is consumed.. whereas when relying on haproxy log-forward, when haproxy reads a message, it relays it to the configured endpoint (ring, udp, tcp over ring), but it can't/doesn't check if the other end keeps up the pace, thus it may very well overwhelm the consumer and haproxy will never slow down as long as it is able to keep up with the producer. It's pretty similar to using UDP on a local link, the producer needs to take into account the consumer processing time, and/or `rmem_max` on the consumer must be large enough to compensate for small bursts due to delay induced by the consuming application to prevent loss.. but in the end if the data flow is continuous, the consumer processing rate must (at least) match the producer's rate otherwise loss will occur once buffers are full anyway.

**Comment by wtarreau** [comment] 2024-09-30 09:05
I think the timer is there, it mentions ~10s for the ring test for example.

I've tested locally (with much smaller logs), by logging directly to a ring. On my laptop I'm sending 1 million logs in 0.55s, that's ~400 MB/s. One must keep in mind that this is when using a single haproxy thread (since it's a single connection). Maybe that's something that counts in this test. With 4 connections spread on 4 threads / 2 cores, I'm getting 880 MB/s and 4.5M msg/s.

BTW I'm seeing 40% CPU spent in co_getline()! That's probably something we could improve!

**Comment by wtarreau** [comment] 2024-09-30 09:32
I could recover that performance from co_getline(), but the limit in multi-thread remains the ring, which caps at around 4.6M msg/s on my laptop.

**Comment by wtarreau** [comment] 2024-09-30 10:05
With the tcp-log-forwarding approach (2 backends, 1 srv each), I retested using 1kB log messages. I managed to transfer 20M logs (20 GB) in about 9 seconds to nc6 on the same laptop using 2 cores, that's 2GB/s, and way more than you're seeing. For minimal losses at this speed, I had to use 150MB logbufsize on the servers (less than 2 logs per million lost). Otherwise there were around 6% lost at 50 MB due to nc6 being saturated.

I also noticed that the performance varied a lot between runs, depending on the threads the outgoing connections were bound to. It indeed takes more time to parse on the same thread that is sending (but causes less losses since reads are slower).

At this point, given the important differences we're each observing, I think it would make sense that you try again out of your docker environment, to rule out any risk that something there would be responsible for the slowdown (NAT rules, proxy, etc).

**Comment by tuxillo** [comment] 2024-09-30 11:20
@wtarreau @Darlelet  thanks a lot for the feedback! I'm going to try to do a more detailed analysis with and without docker and see if there are interferences and, if so, where they are and how.

**Comment by Darlelet** [comment] 2024-09-30 12:39
and perhaps without writing logs to actual drive, but on ramfs (for testing purposes to rule out haproxy) since IO on disk will rarely sustain more than a few hundreds MB/s (in your docker-compose you seemed to be writing under `./logs` directory which I assumed was backed by persistent storage device)

**Comment by tuxillo** [comment] 2024-10-03 09:44
Initially, I was going to do tests with and without docker and then, have a deeper look. But first, I decided to move out the test from my laptop to an c7g.8xlarge AWS EC2 instance to avoid any interference, which BTW is a Macbook PRO thus Docker Desktop runs the containers in a VM.

I started by removing the file destination in the syslog server as @Darlelet suggested and the result were quite revealing, see below some makeshift graphs:

![image](https://github.com/user-attachments/assets/08948f7e-05fa-45c0-96a7-4f8b98d7b902)

The results were obtained by a script which increasingly bumps the buffer for HAProxy rings and the number of connections (and hence the threads) for loggen, see here: https://github.com/tuxillo/haproxy-syslog-forwarding/blob/main/scripts/test_docker.sh . I also saved the data of one of the runs here: https://github.com/tuxillo/haproxy-syslog-forwarding/blob/main/tests/c7g.8xlarge.txt , just in case you want to check the details. Please note that I query syslog-ng-ctl for the stats now instead of just counting the lines in files, which is more accurate and also because there are no files now.

Apparently, if you size haproxy/syslog-server appropriately in terms of available CPU resources it rarely lose any messages. The UDP case where a lot of messages are lost are probably more related to things in axosyslog/syslog-ng than in haproxy (see https://axoflow.com/syslog-over-udp-kernel-syslog-ng-tuning-avoid-losing-messages/) . Also, having the logs written to disk by syslog-ng will make messages to be missed somehow, probably the syslog server chokes on so much data and drops them but we would have to confirm that.

I’m not sure if it’s worth chasing more details on this issue, what do you people think?

**Comment by tuxillo** [comment] 2024-10-08 18:25
Any thoughts @wtarreau @Darlelet ?

**Comment by Darlelet** [comment] 2024-10-08 18:27
Looks legit to me
However I'll let @wtarreau have the closing word, but thanks for the feedback and the interesting stats!

**Comment by capflam** [comment] 2024-11-06 13:51
@wtarreau, shall we close the issue or not ? (I have not read all the history, sorry ...)

**Comment by tuxillo** [comment] 2024-11-06 16:37
I would think a final conclusion should be shared in this issue, for future reference.

**Comment by wtarreau** [comment] 2024-11-07 07:56
I think we can close and retag it (there's no label for such discussions related to sharing performance observations, but "works as designed" will likely be the best match). I still don't understand well why
there are losses in the ring and not with an external server, unless the test involved TCP on the two sides.

I agree that your results could interest other users who are hesitating about their logging architecture.
By the way, do you have the (rough) number of messages per second for the tests you graphed above ? I can't find it in the graphs nor in the accompanying test. From one of the output files, it looks like it's 49k msg per connection for 10 seconds, i.e. 4.9k msg/s/conn. But I'm not certain I'm reading them perfectly. I think that's probably not bad for docker environments and VMs.

A last point which can possibly improve the delivery rate over UDP is to change the system's per-socket limits in /proc/sys/net/core/rmem_{default,max} for the receiver, and wmem_{default,max} for the sender. Default buffers are 208kB and that can be quite low when dealing with hundreds of thousands of messages per second. The losses which only start past one load level could definitely be caused by this.

**Closed as completed** 2024-11-07 07:57 UTC
Labels: status: works as designed
