### ISSUE TITLE
src/listener.c: null pointer dereference suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1859] opened 2022-09-10 05:08 UTC
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1497865:  Null pointer dereferences  (FORWARD_NULL)
/src/listener.c: 518 in resume_listener()
512     {
513             struct proxy *px = l->bind_conf->frontend;
514             int was_paused = px && px->li_paused;
515             int ret = 1;
516     
517             if (!lpx)
>>>     CID 1497865:  Null pointer dereferences  (FORWARD_NULL)
>>>     Dereferencing null pointer "__lk_r".
518                     HA_RWLOCK_WRLOCK(PROXY_LOCK, &px->lock);
519     
520             HA_RWLOCK_WRLOCK(LISTENER_LOCK, &l->lock);
521     
522             /* check that another thread didn't to the job in parallel (e.g. at the
523              * end of listen_accept() while we'd come from dequeue_all_listeners().
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment] 2022-09-11 13:55
Related to https://github.com/haproxy/haproxy/commit/001328873c352e5e4b1df0dcc8facaf2fc1408aa
But it's actually weird it's only reported for resume_listener() and not for pause_listener() that follow the exact same logic regarding **px** pointer usage (actually changes made in https://github.com/haproxy/haproxy/commit/001328873c352e5e4b1df0dcc8facaf2fc1408aa are based on stop_listener() existing logic).

I don't know yet if px could be NULL by design or not in those 3 functions.

**Comment by Darlelet** [comment] 2022-09-11 14:02
> I don't know yet if px could be NULL by design or not in those 3 functions.

Related coverity suspicions marked as 'intentional':
- https://github.com/haproxy/haproxy/issues/672
- https://github.com/haproxy/haproxy/issues/675
- https://github.com/haproxy/haproxy/issues/679

Is this still the case? (fe cannot be NULL)

**Comment by Darlelet** [comment] 2022-09-11 14:09
On the other hand, **fe** is being handled with more precaution (NULL check performed systematically before dereferencing the pointer)
in listener_accept() function.

See:
- https://github.com/haproxy/haproxy/issues/264

Who's right?

**Comment by chipitsine** [comment] 2022-09-11 18:52
@Darlelet , here's longer coverity transcript

```
511int resume_listener(struct listener *l, int lpx)
512{
513        struct proxy *px = l->bind_conf->frontend;
   	1. var_compare_op: Comparing px to null implies that px might be null.
514        int was_paused = px && px->li_paused;
515        int ret = 1;
516
   	2. Condition !lpx, taking true branch.
517        if (!lpx)
   	3. Condition 1 /* sizeof (long) == 8 && sizeof (px->lock) == 8 */, taking true branch.
   	4. alias_transfer: Assigning: __lk_r = &px->lock.
   	5. Condition 1, taking true branch.
   	6. Condition 1 /* sizeof (long) == 8 && sizeof (*__lk_r) == 8 */, taking true branch.
   	
CID 1497865 (#1 of 1): Dereference after null check (FORWARD_NULL)
7. var_deref_op: Dereferencing null pointer __lk_r.
518                HA_RWLOCK_WRLOCK(PROXY_LOCK, &px->lock);
```

**Comment by capflam** [comment] 2022-09-12 06:20
Well, in fact, a listener has always a frontend. Some tests remain from early ages of haproxy when it was considered to support listeners without frontends. And out of habits, this test on the listener's frontend was replicated here and there since then. So I guess the test on the proxy existence in `resume_listener()` should be removed.

**Comment by Darlelet** [comment] 2022-09-12 06:48
Thank you both, coverity only complains about resume_listener() because of **was_paused** variable assignment (line 514) that let coverity thinks that px might be NULL.

@capflam I'll send you a patch

**Comment by wtarreau** [comment] 2022-09-12 07:14
Please note, as @capflam mentioned, this comes from the early times where a listener could be alone. *however* the integrality of the current architecture remains compatible with having isolated listeners, something for example that could be required in order to handle some multi-connection protocols such as FTP. That's why all that code hadn't been simplified over the years. For sure there are some caveats that arrived over time, like this one with threads and locks. But I'd rather try to make coverity happy (including by marking it as intentional if that's easier) rather than completely lose the ability to have detached listeners in the future.

**Comment by chipitsine** [comment] 2022-09-12 08:04
maybe some comment to code should be added clarifying this

**Comment by capflam** [comment] 2022-09-12 08:13
It should be fixed. Thanks

**Closed as completed** 2022-09-12 09:16 UTC
Labels: type: code-report
