### ISSUE TITLE
Sticky sessions does not work in some cases

### ISSUE THREAD

**Issue by pawellrus** [haproxy/haproxy#2196] opened 2023-06-28 15:01 UTC
### Detailed Description of the Problem

In some cases haproxy does not respect the sticky sessions table and simply uses round-robin algorythm when routing request to backend servers.

### Expected Behavior

After first request with specified auth token completed by some backend server other subsequent requests with same token should be routed to the same backend server.

### Steps to Reproduce the Behavior

1. Perform request to server
2. See in logs that requests mostly come to one backend server but small amount requests are being routed to another server

### What is your configuration?

```haproxy
Backend with sticky table is configured like that:

  backend backend_api from web
      stick-table type string len 512 size 100k expire 60m
      stick on req.hdr(Authorization)
      http-request set-header X-Client-IP %[src]
      http-request set-path "%[path,regsub(^/prod/,/)]"
      server backendserver101_7777 1.1.1.1:7777 check
      server backendserver108_7777 2.2.2.2:7777 check
      server backendserver208_7777 3.3.3.3:7777 check
      errorfile 503 /etc/haproxy/custom_errors/maintenance.http
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.0-fdd8154ed37f 2023/05/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.0.html
Running on: Linux 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_LIBCRYPT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_NS=1 USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
        [BWLIM] bwlim-in
        [BWLIM] bwlim-out
        [CACHE] cache
        [COMP] compression
        [FCGI] fcgi-app
        [SPOE] spoe
        [TRACE] trace
```

### Last Outputs and Backtraces

```plain
Jun 28 16:32:04 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:03.782] webapi_company_com_https~ backend_api/backendserver208_7777 17/0/1/305/323 200 14205 - - ---- 221/208/3/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:04 linehaproxysrvr haproxy[2487428]: clientip:16990 [28/Jun/2023:16:32:03.782] webapi_company_com_https~ backend_api/backendserver101_7777 237/0/2/595/838 200 44406 - - ---- 233/219/2/1/0 0/0 {token_here} "GET ...
Jun 28 16:32:05 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:04.104] webapi_company_com_https~ backend_api/backendserver101_7777 863/0/5/818/1686 200 4315 - - ---- 234/220/2/1/0 0/0 {token_here} "GET ...
Jun 28 16:32:06 linehaproxysrvr haproxy[2487428]: clientip:16068 [28/Jun/2023:16:32:03.782] webapi_company_com_https~ backend_api/backendserver108_7777 247/0/4/2713/2981 200 145028 - - ---- 226/212/1/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:06 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:05.791] webapi_company_com_https~ backend_api/backendserver101_7777 241/0/4/807/1052 200 4315 - - ---- 226/212/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:10 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:06.843] webapi_company_com_https~ backend_api/backendserver101_7777 134/0/3/3175/3314 200 31780 - - ---- 211/198/1/1/0 0/0 {token_here} "GET ...
Jun 28 16:32:12 linehaproxysrvr haproxy[2487428]: clientip:15272 [28/Jun/2023:16:32:12.054] webapi_company_com_https~ backend_api/backendserver101_7777 60/0/1/171/232 200 3696 - - ---- 216/203/1/1/0 0/0 {token_here} "GET ...
Jun 28 16:32:12 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:10.157] webapi_company_com_https~ backend_api/backendserver101_7777 133/0/2/2685/2821 200 31780 - - ---- 210/197/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:16 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:12.978] webapi_company_com_https~ backend_api/backendserver101_7777 3571/0/1/441/4014 200 18487 - - ---- 213/200/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:17 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:16.993] webapi_company_com_https~ backend_api/backendserver101_7777 349/0/1/167/517 200 3696 - - ---- 211/198/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:24 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:17.509] webapi_company_com_https~ backend_api/backendserver101_7777 3184/0/2/3531/6719 200 54425 - - ---- 201/188/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:28 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:24.228] webapi_company_com_https~ backend_api/backendserver101_7777 3214/0/1/652/3869 200 59383 - - ---- 195/182/1/0/0 0/0 {token_here} "POST ...
Jun 28 16:32:29 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:28.096] webapi_company_com_https~ backend_api/backendserver101_7777 1196/0/4/181/1381 200 3696 - - ---- 200/187/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:31 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:29.477] webapi_company_com_https~ backend_api/backendserver101_7777 1638/0/3/554/2198 200 38715 - - ---- 211/198/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:34 linehaproxysrvr haproxy[2487428]: clientip:15775 [28/Jun/2023:16:32:34.547] webapi_company_com_https~ backend_api/backendserver101_7777 55/0/10/177/242 200 3696 - - ---- 230/217/1/1/0 0/0 {token_here} "GET ...
Jun 28 16:32:37 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:31.676] webapi_company_com_https~ backend_api/backendserver101_7777 2751/0/3/3007/5765 200 25550 - - ---- 220/207/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:40 linehaproxysrvr haproxy[2487428]: clientip:16682 [28/Jun/2023:16:32:37.440] webapi_company_com_https~ backend_api/backendserver101_7777 2399/0/4/348/2751 200 3696 - - ---- 203/190/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:45 linehaproxysrvr haproxy[2487428]: clientip:16697 [28/Jun/2023:16:32:45.331] webapi_company_com_https~ backend_api/backendserver101_7777 58/0/1/195/254 200 3696 - - ---- 217/204/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:50 linehaproxysrvr haproxy[2487428]: clientip:15167 [28/Jun/2023:16:32:50.684] webapi_company_com_https~ backend_api/backendserver101_7777 54/0/1/143/198 200 3696 - - ---- 215/201/2/1/0 0/0 {token_here} "GET ...
Jun 28 16:32:51 linehaproxysrvr haproxy[2487428]: clientip:15229 [28/Jun/2023:16:32:50.612] webapi_company_com_https~ backend_api/backendserver101_7777 54/0/1/1193/1254 200 64757 - - ---- 228/214/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:52 linehaproxysrvr haproxy[2487428]: clientip:15229 [28/Jun/2023:16:32:51.866] webapi_company_com_https~ backend_api/backendserver101_7777 255/0/1/339/597 200 16290 - - ---- 232/218/2/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:56 linehaproxysrvr haproxy[2487428]: clientip:15229 [28/Jun/2023:16:32:55.739] webapi_company_com_https~ backend_api/backendserver101_7777 204/0/1/137/342 200 3696 - - ---- 235/222/2/0/0 0/0 {token_here} "GET ...
Jun 28 16:32:57 linehaproxysrvr haproxy[2487428]: clientip:15229 [28/Jun/2023:16:32:56.081] webapi_company_com_https~ backend_api/backendserver101_7777 500/0/1/473/998 200 142494 - - ---- 222/209/3/1/0 0/0 {token_here} "GET ...
Jun 28 16:33:00 linehaproxysrvr haproxy[2487428]: clientip:15229 [28/Jun/2023:16:32:57.078] webapi_company_com_https~ backend_api/backendserver101_7777 1621/0/1/2185/3810 200 18588 - - ---- 206/193/1/0/0 0/0 {token_here} "GET ...
Jun 28 16:33:01 linehaproxysrvr haproxy[2487428]: clientip:15229 [28/Jun/2023:16:33:00.889] webapi_company_com_https~ backend_api/backendserver101_7777 254/0/5/248/507 200 3696 - - ---- 202/189/1/0/0 0/0 {token_here} "GET ...
Jun 28 16:33:06 linehaproxysrvr haproxy[2487428]: clientip:16703 [28/Jun/2023:16:33:06.448] webapi_company_com_https~ backend_api/backendserver101_7777 57/0/2/164/223 200 3696 - - ---- 217/204/0/0/0 0/0 {token_here} "GET ...
Jun 28 16:33:13 linehaproxysrvr haproxy[2487428]: clientip:16703 [28/Jun/2023:16:33:06.672] webapi_company_com_https~ backend_api/backendserver101_7777 705/0/1/6099/6813 200 54425 - - ---- 238/224/3/1/0 0/0 {token_here} "GET ...
Jun 28 16:33:18 linehaproxysrvr haproxy[2487428]: clientip:15641 [28/Jun/2023:16:33:18.547] webapi_company_com_https~ backend_api/backendserver101_7777 54/0/2/177/233 200 3696 - - ---- 245/231/4/1/0 0/0 {token_here} "GET ...
Jun 28 16:33:20 linehaproxysrvr haproxy[2487428]: clientip:16703 [28/Jun/2023:16:33:13.485] webapi_company_com_https~ backend_api/backendserver101_7777 4135/0/2/2377/6517 200 59383 - - ---- 243/229/4/0/0 0/0 {token_here} "POST ...
Jun 28 16:33:23 linehaproxysrvr haproxy[2487428]: clientip:16613 [28/Jun/2023:16:33:23.849] webapi_company_com_https~ backend_api/backendserver101_7777 53/0/1/78/132 200 3696 - - ---- 231/217/6/1/0 0/0 {token_here} "GET ...
Jun 28 16:33:24 linehaproxysrvr haproxy[2487428]: clientip:16703 [28/Jun/2023:16:33:20.001] webapi_company_com_https~ backend_api/backendserver101_7777 2824/0/1/1665/4493 200 59383 - - ---- 232/218/4/0/0 0/0 {token_here} "POST ...
```

### Additional Information

Length of token is always less than 512 symbols.
I also checked sticky table via cli and saw that 1 record with token were created.

**Comment by git001** [comment] 2023-06-28 15:32
Please update to the latest 2.7 or 2.8 and take a look if the problem still exist

**Comment by pawellrus** [comment] 2023-06-29 14:18
> Please update to the latest 2.7 or 2.8 and take a look if the problem still exist

Done. But issue persists. Initial post updated.

**Comment by Darlelet** [comment] 2023-06-29 15:14
It seems that 3 initial requests were simultaneously handled from 3 different clients:
![image](https://github.com/haproxy/haproxy/assets/6534701/65a0d924-a8ad-4091-92b1-e4ce47288149)

Maybe 2nd and 3rd requests (108, 208) routing decisions were performed simultaneously before the 1st request (101) completed  and had enough time to create the sticktable entry?

Because, apart from these "initial" requests, stickiness seems to work properly according to your logs:
- once a second request was successfully routed to the 101 server (assuming the sticktable is now populated), other servers don't receive any request

I don't know if this is expected behavior but the impact seems quite limited.

**Comment by pawellrus** [comment] 2023-06-29 15:34
> It seems that 3 initial requests were simultaneously handled from 3 different clients: ![image](https://user-images.githubusercontent.com/6534701/249806834-65a0d924-a8ad-4091-92b1-e4ce47288149.png)
> 
> Maybe 2nd and 3rd requests (108, 208) routing decisions were performed simultaneously before the 1st request (101) completed and had enough time to create the sticktable entry?
> 
> Because, apart from these "initial" requests, stickiness seems to work properly according to your logs:
> 
> * once a second request was successfully routed to the 101 server (assuming the sticktable is now populated), other servers don't receive any request
> 
> I don't know if this is expected behavior but the impact seems quite limited.



Ok can you please comment this log sample. Here I see that backend selection is less consistent.

```
Jun 29 17:10:45 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:44.862] webapi_company_com_https~ webapi/backendserver108_7777 0/0/4/486/490 200 14205 - - ---- 177/144/5/1/0 0/0 {token_here} "GET ...
Jun 29 17:10:45 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:44.862] webapi_company_com_https~ webapi/backendserver101_7777 0/0/1/948/952 200 46594 - - ---- 182/149/6/3/0 0/0 {token_here} "GET ...
Jun 29 17:10:46 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:45.937] webapi_company_com_https~ webapi/backendserver101_7777 202/0/2/773/977 200 8052 - - ---- 186/153/4/2/0 0/0 {token_here} "GET ...
Jun 29 17:10:48 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:41.821] webapi_company_com_https~ webapi/backendserver208_7777 3040/0/2/3359/6410 200 145044 - - ---- 184/151/3/1/0 0/0 {token_here} "GET ...
Jun 29 17:10:51 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:48.660] webapi_company_com_https~ webapi/backendserver208_7777 2419/0/2/237/2658 200 3696 - - ---- 187/154/5/2/0 0/0 {token_here} "GET ...
Jun 29 17:10:51 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:46.915] webapi_company_com_https~ webapi/backendserver101_7777 974/0/2/3967/4960 200 54425 - - ---- 183/150/4/2/0 0/0 {token_here} "GET ...
Jun 29 17:10:52 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:48.232] webapi_company_com_https~ webapi/backendserver208_7777 428/0/1/3568/3999 200 32438 - - ---- 186/153/2/0/0 0/0 {token_here} "GET ...
Jun 29 17:11:26 haproxysrvr haproxy[2496516]: clientip:16702 [29/Jun/2023:17:11:26.772] webapi_company_com_https~ webapi/backendserver208_7777 53/0/2/36/91 404 191 - - ---- 187/151/2/0/0 0/0 {token_here} "POST...
```

**Comment by Darlelet** [comment] 2023-06-29 15:49
This one feels weird indeed!

From my understanding, 1st request would be:
```
Jun 29 17:10:48 haproxysrvr haproxy[2496516]: clientip:16410 [29/Jun/2023:17:10:41.821] webapi_company_com_https~ webapi/backendserver208_7777 3040/0/2/3359/6410 200 145044 - - ---- 184/151/3/1/0 0/0 {token_here} "GET ...
```
Started at `17:10:41.821`, finished at ~`17:10:48` -> routed to `208` server

All requests that were performed between `17:10:41.821` and `17:10:48` seem to be routed to servers in a round-robin fashion (stick table entry not yet created/effective?)

Following requests, started after `17:10:48` seem to be routed to the proper backend (208)

This is just an assumption, and while I'm not sure, it seems that the stick table is populated late in request processing, and not immediately when the routing decision is made, leading to these inconsistent results with concurrent long-running requests.

**Comment by Darlelet** [comment] 2023-06-29 16:06
With that said, I'm not able to reproduce on my end by manually delaying requests so we could be missing something.
Would you mind sharing some of your relevant frontend config directives?

Edit: I think I'm able to reproduce:
```
[NOTICE]   (2023271) : Loading success.
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52864 [29/Jun/2023:18:28:33.137] foo bar/s2 0/0/0/0/0 200 21684 - - ---- 7/5/3/1/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52874 [29/Jun/2023:18:28:33.138] foo bar/s2 0/0/0/0/0 200 21896 - - ---- 7/5/3/0/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52882 [29/Jun/2023:18:28:33.139] foo bar/s2 0/0/0/0/0 200 21899 - - ---- 8/5/2/0/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52888 [29/Jun/2023:18:28:33.141] foo bar/s2 0/0/0/0/0 200 21899 - - ---- 10/6/2/0/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52892 [29/Jun/2023:18:28:33.141] foo bar/s2 0/0/0/0/0 200 21899 - - ---- 14/8/3/1/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52900 [29/Jun/2023:18:28:33.142] foo bar/s2 0/0/0/0/0 200 21901 - - ---- 14/8/2/0/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52916 [29/Jun/2023:18:28:33.143] foo bar/s2 0/0/0/0/0 200 21906 - - ---- 16/9/2/0/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52920 [29/Jun/2023:18:28:33.143] foo bar/s2 0/0/0/0/0 200 21927 - - ---- 18/11/3/0/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52924 [29/Jun/2023:18:28:33.143] foo bar/s2 0/0/0/0/0 200 21927 - - ---- 19/11/2/0/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52872 [29/Jun/2023:18:28:33.138] foo bar/s1 0/0/35/39/74 200 548 - - ---- 9/2/1/1/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:28:33 haproxy[2023273]: 127.0.0.1:52862 [29/Jun/2023:18:28:33.137] foo bar/s1 0/0/35/40/75 200 548 - - ---- 9/2/0/0/0 0/0 "GET / HTTP/1.1"
```
> 10 first concurrent requests, s1 is remote, slower server compared to s2 that is localhost.

show table bar:
```
# table: bar, type: string, size:102400, used:1
0x7f5400033770: key=ok use=0 exp=3586528 shard=0 server_id=1 server_key=s1
```

Now if I run another 10 simultaneous requests (without reloading haproxy):
```
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44420 [29/Jun/2023:18:30:52.779] foo bar/s1 0/0/35/42/77 200 548 - - ---- 11/11/10/10/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44394 [29/Jun/2023:18:30:52.778] foo bar/s1 0/0/36/42/78 200 548 - - ---- 11/11/9/9/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44380 [29/Jun/2023:18:30:52.778] foo bar/s1 0/0/36/44/80 200 548 - - ---- 9/9/8/8/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44404 [29/Jun/2023:18:30:52.779] foo bar/s1 0/0/35/44/79 200 548 - - ---- 9/9/7/7/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44434 [29/Jun/2023:18:30:52.779] foo bar/s1 0/0/35/46/81 200 548 - - ---- 7/7/6/6/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44382 [29/Jun/2023:18:30:52.778] foo bar/s1 0/0/37/52/89 200 548 - - ---- 6/6/2/2/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44442 [29/Jun/2023:18:30:52.783] foo bar/s1 0/0/36/48/84 200 548 - - ---- 6/6/2/2/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44446 [29/Jun/2023:18:30:52.783] foo bar/s1 0/0/36/48/84 200 548 - - ---- 6/6/2/2/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44368 [29/Jun/2023:18:30:52.779] foo bar/s1 0/0/36/52/88 200 548 - - ---- 6/6/2/2/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44440 [29/Jun/2023:18:30:52.783] foo bar/s1 0/0/36/50/86 200 548 - - ---- 2/2/1/1/0 0/0 "GET / HTTP/1.1"
<134>Jun 29 18:30:52 haproxy[2023273]: 127.0.0.1:44436 [29/Jun/2023:18:30:52.783] foo bar/s1 0/0/37/49/86 200 548 - - ---- 2/2/0/0/0 0/0 "GET / HTTP/1.1"
```
(now everything is fine)

**Comment by pawellrus** [comment] 2023-06-30 10:02
@Darlelet thank you for your participation.

So such combination of long-running and short-running queries can lead to behaviour, that we can see? And it is working as intended? Until the first request from user will be processed the record in sticky-session table won't be created? And if this request is longer than subsequent ones, they will be routed by round-robin algorythm? Is it correct?

**Comment by wtarreau** [comment] 2023-06-30 13:39
@pawellrus, @Darlelet is right, actually the stick mechanism is based on convergence, i.e. the last one applying a change as the last say. There can sometimes be some little uncertainty periods but eventually the last update will fix all further accesses. It can sound strange at first but when you consider that the purpose of stickiness is to 1) use an LB algo to pick a **working** server, and 2) to stick all **subsequent** requests to the same server, you realize that it makes a lot of sense: you don't want to stick before the access to the server is confirmed. You seem to be in a very special case where a client sends multiple connections or requests at once, but this rarely matches the pattern where one wants absolute stickiness (though when it's only about optimization that's of course fine). When you have multiple concurrent initial requests, there are always uncertainty in time and space. For example, let's say that your traffic arrives at the edge on multiple haproxy nodes. Each one may pick a different server, and inform the other nodes. Thanks to the way it works, it quickly converges, and eventually all nodes agree on the server.

If for any reason it's not acceptable that a few initial request reach different servers even for a short period (for reasons ranging from tracing to database integrity etc), then it means that you need a different LB algo, one that is deterministic. For example, some people combine stick-tables with hashing. This sounds strange at first, but hashing guarantees a consistent initial choice for all parallel traffic, and stick-table guarantees the traffic is not redistributed in the case a new server is inserted or an existing server fails.

Hoping this enlightens it a bit.

**Comment by capflam** [comment] 2024-02-29 13:26
So it seems everything works as expected and there is no bug. I'm closing. Thanks !

**Closed as not planned by capflam** 2024-02-29 13:26 UTC
Labels: type: bug, status: works as designed
