### ISSUE TITLE
cannot build on MacOS-14 Silicon

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2540] opened 2024-04-18 20:24 UTC
### Tool Name and Version

Apple clang version 15.0.0 (clang-1500.0.40.1)

### Code Report

```plain
src/stats.c:2248:24: error: passing arguments to 'stats_dump_html_end' without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
  CC      src/uri_normalizer.o
                                stats_dump_html_end(chk);
                                                   ^
1 error generated.
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by chipitsine** [comment] 2024-04-18 20:45
I tried to switch to macos-14

https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

**Comment by cognet** [comment] 2024-04-19 00:00
I'm actually amazed no other compiler seem to be grumpy about that.
This should be fixed with a7caa14a643da10e26c6248915626c8d79374883
Thank you!

**Comment by chipitsine** [comment] 2024-04-19 04:50
is it going to be backported ? or should I close the issue ?

**Comment by a-denoyelle** [comment] 2024-04-19 06:53
@cognet My mistake, thank you for the quick fix.
@chipitsine it does not need to be backported so the issue can be closed.

**Closed as completed by a-denoyelle** 2024-04-19 06:53 UTC
Labels: type: code-report

**Comment by a-denoyelle** [comment] 2024-04-19 06:54
In fact, I found other invalid prototypes so I will complete this with another fix.

**Comment by chipitsine** [comment] 2024-04-19 07:03
I didn't (yet) enabled all options on macos-14 ))

**Comment by wtarreau** [comment] 2024-04-19 14:35
BTW it's because an "int f()" forward declaration is not the same as "int f(void)". It just says "this is a function returning int" whereas the latter is rather "this is a function returning it and taking no arguments". I *think* this was used as the early way to support variadic arguments: just don't declare anything and handle the stack yourself. You can try yourself, the following doesn't give any warning at -Wall:
```
char *f();

char *f(char *a, int b)
{
        return a + b;
}
```
The problem is when such a function taking no arg is declared in a .h instead of being declared explicitly as "f(void)", because it becomes permissive and accepts anything, and this can hide typos:
```
char *f1();

char *f2(char *a, int b)
{
        return f1(a, b);
}
```

It's great that we now have one environment where this is detected. I don't know if any known flags in ancient compilers detect these, but it could be a late cleanup to perform on the code to make sure we don't have any "()" anymore in our declarations.

**Comment by chipitsine** [comment] 2024-04-19 14:49
macos-14 detected that because of `-Wdeprecated-non-prototype`
I think it is something we can enable on linux as well

**Comment by wtarreau** [comment] 2024-04-19 14:52
Yes I just checked, that's a clang option, but I don't have it on gcc-11.4

**Comment by chipitsine** [comment] 2024-04-19 14:54
yes, it was built by clang-15.0 on macos-14

I think at least we use the very latest clang on Fedora monthly (i'm surprized the issue was not caught there)

**Comment by chipitsine** [comment] 2024-04-19 14:56
<img width="647" alt="image" src="https://github.com/haproxy/haproxy/assets/2217296/61304859-44d4-410c-8301-a22d1f4ea4c0">

**Comment by zaga00** [comment] 2024-04-19 15:19
`-Wstrict-prototypes` can be used for gcc:

test.c:
```
char *f();

char *f(char *a, int b)
{
        return a + b;
}
```

```
% gcc -c -Wstrict-prototypes test.c
test.c:1:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
    1 | char *f();
      | ^~~~

```

**Comment by wtarreau** [comment] 2024-04-19 15:24
Ah yes good catch, I now remember having tested it long ago. It produces 7417 warnings on our code base! It will be fun to address at once!

**Comment by wtarreau** [comment] 2024-04-19 15:25
BTW I'd like to retry with -std=gnu89 since it produces 0 warnings here and catches some mistakes we've got in the past. I just seem to remember encountering a weird combination previously with an OS, I have to recheck my notes.
