### ISSUE TITLE
src/mux_h2.c: null pointer dereference suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1699] opened 2022-05-14 02:22 UTC
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1488837:  Null pointer dereferences  (REVERSE_INULL)
/src/mux_h2.c: 6764 in h2_show_fd()
6758                                  h2s->endp->cs);
6759                    if (h2s->endp->cs)
6760                            chunk_appendf(msg, "(.flg=0x%08x .app=%p)",
6761                                          h2s->endp->cs->flags, h2s->endp->cs->app);
6762     
6763                    chunk_appendf(msg, "endp=%p", h2s->endp);
>>>     CID 1488837:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "h2s->endp" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
6764                    if (h2s->endp)
6765                            chunk_appendf(msg, "(.flg=0x%08x)",
6766                                          h2s->endp->flags);
6767     
6768                    chunk_appendf(&trash, " .subs=%p", h2s->subs);
6769                    if (h2s->subs) {
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by capflam** [comment] 2022-05-18 07:27
The test on `h2s->endp` is useless. This field always exists. However this part will be refactored for the 2.6.0. Thus I'm closing the issue. Note it is not a bug, just a useless test on `h2s->endp`

**Closed as completed by capflam** 2022-05-18 07:27 UTC
Labels: type: code-report
